import{describe,expect,it}from"vitest";import{CommunicationTemplateRegistry,evaluateCommunicationGuidance,renderVersionedCommunicationTemplate,type CommunicationTemplateDefinition,type GuestContextProjection}from"./index";
const at="2026-07-26T12:00:00Z";
function context(overrides:Partial<GuestContextProjection>={}):GuestContextProjection{return{projectionVersion:"guest-context-projection.v1",generatedAt:at,identity:{workspaceId:"workspace-1",guestId:"guest-1",conversationId:"conversation-1",reservationId:"reservation-1",propertyId:"property-1"},guest:{name:"Avery",preferredName:{state:"available",value:"Avery"},language:{state:"available",value:"en"},communicationPreference:{state:"available",value:"platform-messaging"},email:{state:"unavailable",reason:"hidden"},phone:{state:"unavailable",reason:"hidden"},guestSince:{state:"unknown",reason:"unknown"},repeatStayCount:0,status:"new-guest"},reservation:{id:"reservation-1",confirmation:{state:"available",value:"confirmation-1"},arrival:"2026-07-26",departure:"2026-07-29",lengthOfStay:3,adults:{state:"available",value:2},children:{state:"available",value:0},pets:{state:"available",value:0},bookingSource:"Direct",status:"arrival-today",stage:"arriving-today"},property:{id:"property-1",name:"Retreat",address:{state:"available",value:"123 Main"},timezone:"America/Chicago",operationalStatus:"active",guidebookStatus:{state:"unavailable",reason:"missing"},doorCode:{state:"unavailable",reason:"missing"},parking:{state:"available",value:"Space 2"},wifi:{state:"available",value:"Guest WiFi"},emergencyContact:{state:"unknown",reason:"unknown"},houseRulesVersion:{state:"available",value:at}},operations:{issues:[],blockers:[]},communication:{status:"waiting-on-operator",unreadCount:1,waitingOn:"operator",lastReply:{state:"available",value:"2026-07-26T02:00:00Z"},lastSent:{state:"not-applicable",reason:"none"},lastViewed:{state:"unknown",reason:"unknown"}},guidebook:{exists:false,status:{state:"unavailable",reason:"missing"},publicUrl:{state:"not-applicable",reason:"missing"},needsUpdate:false},history:{previousStayCount:0,previousConversationCount:0,knownPreferences:[]},provider:{connected:true,synchronizationStatus:"active",lastSync:{state:"available",value:at},conversationSource:"test"},timelineSummary:[],suggestedActions:[],dataQuality:{state:"partially-available",confidence:"moderate",completeness:75,missing:["guidebook","door code"],stale:[],guidance:"Review gaps.",sources:{reservation:"fresh",conversation:"fresh",property:"fresh",guidebook:"missing",operations:"fresh"}},permissions:{level:"manager",contactDetails:false,financialDetails:false},...overrides};}
function template(overrides:Partial<CommunicationTemplateDefinition>={}):CommunicationTemplateDefinition{return{id:"template-1",seriesKey:"arrival",version:1,category:"check-in",language:"en",locale:"en-US",body:"Hello {{guestName}}, door {{doorCode}}.",variables:["guestName","doorCode"],attachments:[],deliveryMode:"immediate",status:"published",createdAt:at,updatedAt:at,...overrides};}
describe("Communication Guidance Engine",()=>{
 it("prioritizes overdue replies and operational dependencies deterministically",()=>{const guidance=evaluateCommunicationGuidance({context:context()});expect(guidance[0]).toMatchObject({actionKey:"reply",priority:"critical",confidence:"moderate"});expect(guidance.map(item=>item.actionKey)).toEqual(expect.arrayContaining(["publish-guidebook","resolve-access"]));expect(guidance.map(item=>item.actionKey)).not.toContain("send-checkin");expect(guidance[0].explanation.length).toBeGreaterThan(0);});
 it("removes a recommendation only for the matching context disposition",()=>{const initial=evaluateCommunicationGuidance({context:context()}),reply=initial.find(item=>item.actionKey==="reply")!;expect(evaluateCommunicationGuidance({context:context(),dispositions:[{actionKey:"reply",status:"dismissed",contextFingerprint:reply.contextFingerprint}]}).map(item=>item.actionKey)).not.toContain("reply");});
 it("renders only published immediate template versions after resolving every variable",()=>{expect(renderVersionedCommunicationTemplate(template(),{guestName:"Avery",doorCode:"2468"})).toMatchObject({templateVersion:1,body:"Hello Avery, door 2468.",deliveryMode:"immediate"});expect(()=>renderVersionedCommunicationTemplate(template(),{guestName:"Avery"})).toThrow("communication_template_variables_missing");expect(()=>renderVersionedCommunicationTemplate(template({status:"draft"}),{guestName:"Avery",doorCode:"2468"})).toThrow("communication_template_not_published");});
 it("selects localized published template versions with language fallback",()=>{const registry=new CommunicationTemplateRegistry().register(template()).register(template({id:"template-2",version:2,language:"es",locale:"es-MX",body:"Hola {{guestName}}, puerta {{doorCode}}."}));expect(registry.resolve("check-in","es","es-MX")?.id).toBe("template-2");expect(registry.resolve("check-in","fr")?.id).toBe("template-1");});
});
