import{describe,expect,it}from"vitest";import{buildGuestRelationshipSummary,createGuestTimelineAggregate,DEFAULT_GUEST_TIMELINE_EVENTS,guestTimelineEventHref,queryGuestTimeline,type GuestTimelineEvent}from"./index";
function event(sequence:number,eventType:string,occurredAt:string,overrides:Partial<GuestTimelineEvent>={}):GuestTimelineEvent{return{id:`event-${sequence}`,sequence,workspaceId:"workspace-1",guestId:"guest-1",occurredAt,recordedAt:occurredAt,eventType,category:DEFAULT_GUEST_TIMELINE_EVENTS.category(eventType),visibility:"operational",summary:eventType.replaceAll("-"," "),actor:{type:"system"},source:{type:"test",id:`source-${sequence}`},metadata:{},...overrides};}
describe("Guest Relationship Timeline",()=>{
 it("orders simultaneous events by immutable insertion sequence",()=>{const timeline=createGuestTimelineAggregate({workspaceId:"workspace-1",guestId:"guest-1",events:[event(2,"message-sent","2026-07-26T12:00:00Z"),event(1,"guest-replied","2026-07-26T12:00:00Z")]});expect(timeline.events.map(item=>item.sequence)).toEqual([1,2]);expect(timeline.eventCount).toBe(2);expect(Object.isFrozen(timeline.events)).toBe(true);});
 it("filters, searches, and paginates without altering history",()=>{const events=[event(1,"reservation-created","2026-07-24T12:00:00Z",{reservationId:"RES-1"}),event(2,"maintenance-issue","2026-07-25T12:00:00Z",{summary:"Air conditioning repair"}),event(3,"message-delivered","2026-07-26T12:00:00Z")];expect(queryGuestTimeline(events,{categories:["maintenance"],query:"conditioning"}).events.map(item=>item.sequence)).toEqual([2]);expect(queryGuestTimeline(events,{limit:2}).nextCursor).toBe(2);expect(events).toHaveLength(3);});
 it("derives relationship intelligence from immutable facts",()=>{const events=[event(1,"reservation-created","2026-06-01T12:00:00Z",{reservationId:"R1",propertyId:"P1",metadata:{arrival:"2026-06-05",departure:"2026-06-08"}}),event(2,"checkout","2026-06-08T12:00:00Z",{reservationId:"R1",propertyId:"P1",metadata:{arrival:"2026-06-05",departure:"2026-06-08",status:"completed"}}),event(3,"reservation-created","2026-07-01T12:00:00Z",{reservationId:"R2",propertyId:"P1",metadata:{arrival:"2026-07-05",departure:"2026-07-09"}}),event(4,"checkout","2026-07-09T12:00:00Z",{reservationId:"R2",propertyId:"P1",metadata:{arrival:"2026-07-05",departure:"2026-07-09",status:"completed"}}),event(5,"guest-replied","2026-07-10T10:00:00Z"),event(6,"message-sent","2026-07-10T10:30:00Z"),event(7,"maintenance-issue","2026-07-10T11:00:00Z",{metadata:{issueType:"hvac"}})];const summary=buildGuestRelationshipSummary(events);expect(summary).toMatchObject({recognition:"returning-guest",completedStays:2,lifetimeNights:7,preferredPropertyId:"P1",outstandingIssueCount:1});expect(summary.insights.averageResponseMinutes).toBe(30);expect(summary.insights.commonIssueTypes).toEqual(["hvac"]);});
 it("links events back to their canonical source",()=>{expect(guestTimelineEventHref(event(1,"message-sent","2026-07-26T12:00:00Z",{conversationId:"conversation-1"}))).toBe("/dashboard/communications/conversation-1");expect(guestTimelineEventHref(event(2,"guidebook-published","2026-07-26T12:00:00Z",{source:{type:"guidebook-version",id:"version-1"},metadata:{guidebookId:"guidebook-1"}}))).toBe("/dashboard/guidebooks/guidebook-1");});
 it("accepts future event types without a timeline schema change",()=>{expect(DEFAULT_GUEST_TIMELINE_EVENTS.category("future-concierge-request")).toBe("operations");});
});
