import type { NavigationItem } from "./navigation-types";

export const clientWorkspaceNavigation = [
  { id: "home", kind: "product", level: 1, label: "Home", href: "/dashboard", icon: "home", group: "home", experience: "client-workspace", availability: "available", activeMatch: { type: "exact", href: "/dashboard" }, requiredCapabilities: ["view_home"] },
  { id: "workspace-overview", kind: "product", level: 1, label: "Workspace", href: "/dashboard/workspace", icon: "workspace", group: "home", experience: "client-workspace", availability: "available", activeMatch: { type: "exact", href: "/dashboard/workspace" }, requiredCapabilities: ["view_home"] },

  { id: "observe", kind: "product", level: 1, lifecycleStage: "observe", label: "Observe", href: "/dashboard/observe/revenue", icon: "observe", group: "hpm", experience: "client-workspace", availability: "available", activeMatch: { type: "patterns", patterns: ["/dashboard/observe/**", "/dashboard/insights/**", "/dashboard/financial/**"] }, requiredCapabilities: ["view_observations"] },
  { id: "understand", kind: "product", level: 1, lifecycleStage: "understand", label: "Understand", href: "/dashboard/understand/executive", icon: "understand", group: "hpm", experience: "client-workspace", availability: "available", activeMatch: { type: "patterns", patterns: ["/dashboard/understand/**", "/dashboard/portfolio/**"] }, requiredCapabilities: ["view_executive_intelligence"] },
  { id: "decide", kind: "product", level: 1, lifecycleStage: "decide", label: "Decide", href: "/dashboard/investments", icon: "decide", group: "hpm", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/dashboard/investments" }, requiredCapabilities: ["view_investment_workspace"] },
  { id: "execute", kind: "product", level: 1, lifecycleStage: "execute", label: "Execute", href: "/dashboard/execute", icon: "execute", group: "hpm", experience: "client-workspace", availability: "available", activeMatch: { type: "patterns", patterns: ["/dashboard/execute/**", "/dashboard/actions/**"] }, requiredCapabilities: ["view_actions"], badge: { kind: "count", accessibleLabel: "Actions due", maximum: 99 } },
  { id: "learn", kind: "product", level: 1, lifecycleStage: "learn", label: "Learn", href: "/dashboard/learn", icon: "learn", group: "hpm", experience: "client-workspace", availability: "available", activeMatch: { type: "patterns", patterns: ["/dashboard/learn/**", "/dashboard/learning/**"] }, requiredCapabilities: ["view_executive_intelligence"] },

  { id: "properties", kind: "product", level: 1, label: "Properties", href: "/properties", icon: "property", group: "business", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/properties" }, requiredCapabilities: ["view_properties"] },
  { id: "bookings", kind: "product", level: 1, label: "Bookings", href: "/bookings", icon: "booking", group: "business", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/bookings" }, requiredCapabilities: ["view_observations"] },
  { id: "messages", kind: "product", level: 1, label: "Guest Communications", href: "/dashboard/communications", icon: "message", group: "business", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/dashboard/communications" }, requiredCapabilities: ["view_actions"] },
  { id: "reports", kind: "product", level: 1, label: "Reports", href: "/dashboard/reports", icon: "report", group: "business", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/dashboard/reports" }, requiredCapabilities: ["view_observations"] },
  { id: "guidebook-studio", kind: "product", level: 1, label: "Guidebook Studio", href: "/dashboard/guidebooks", icon: "service", group: "services", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/dashboard/guidebooks" }, requiredCapabilities: ["view_properties"] },
  { id: "furnishing-studio", kind: "product", level: 1, label: "Furnishing Studio", href: "/dashboard/furnishing", icon: "service", group: "services", experience: "client-workspace", availability: "available", activeMatch: { type: "prefix", prefix: "/dashboard/furnishing" }, requiredCapabilities: ["view_properties"], requiredEntitlements: ["furnishing.project.access"] },
] satisfies readonly NavigationItem[];
