import type { NavigationItem } from "./navigation-types";
export const operationsConsoleNavigation = [
  { id: "operations-dashboard", label: "Dashboard", href: "/admin", icon: "operations", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "exact", href: "/admin" }, requiredCapabilities: ["view_internal_operations"] },
  { id: "operations-organizations", label: "Organizations", icon: "operations", group: "operations", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/organizations/**"] }, requiredCapabilities: ["view_internal_operations"] },
  { id: "operations-customers", label: "Customers", href: "/admin/owners", icon: "operations", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/owners" }, requiredCapabilities: ["view_internal_operations"] },
  { id: "operations-properties", label: "Properties", href: "/admin/properties", icon: "property", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/properties" }, requiredCapabilities: ["view_internal_operations"] },
  { id: "operations-support", label: "Support", href: "/admin/inquiries", icon: "message", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/inquiries" }, requiredCapabilities: ["view_internal_operations"] },
  { id: "platform-integrations", label: "Integrations", href: "/admin/integrations", icon: "integration", group: "platform", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/integrations" }, requiredCapabilities: ["view_integrations"] },
  { id: "platform-sync-history", label: "Sync History", icon: "integration", group: "platform", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/sync-history/**"] }, requiredCapabilities: ["view_internal_operations"] },
  { id: "platform-health", label: "Provider Health", icon: "integration", group: "platform", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/provider-health/**"] }, requiredCapabilities: ["view_internal_operations"] },
  { id: "platform-audit", label: "Audit", icon: "operations", group: "platform", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/audit/**"] }, requiredCapabilities: ["view_internal_operations"] },
  { id: "content-catalog", label: "Service Catalog", icon: "content", group: "content", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/content/**"] }, requiredCapabilities: ["view_internal_operations"] },
  { id: "internal-settings", label: "Internal Settings", icon: "settings", group: "settings", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/settings/**"] }, requiredCapabilities: ["view_internal_operations"] },
] satisfies readonly NavigationItem[];
