import type { NavigationItem } from "./navigation-types";

export const operationsConsoleNavigation = [
  { kind: "product", level: 2, id: "operations-workspace", label: "Workspace", href: "/admin", icon: "home", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "exact", href: "/admin" }, requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "operations-customers", label: "Customers", href: "/admin/customers", icon: "operations", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/customers" }, description: "Manage organizations and user accounts", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "operations-properties", label: "Properties", href: "/admin/properties", icon: "property", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/properties" }, description: "Property inventory and ownership", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "operations-support", label: "Support", href: "/admin/support", icon: "message", group: "operations", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/support" }, description: "Customer inquiries", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "guidebook-projects", label: "Guidebook Projects", icon: "content", group: "services", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/guidebooks/**"] }, description: "Manage guidebook service delivery", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "design-projects", label: "Design Projects", icon: "content", group: "services", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/design/**"] }, description: "Manage design service delivery", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "service-catalog", label: "Service Catalog", icon: "content", group: "services", experience: "operations-console", availability: "coming-soon", activeMatch: { type: "patterns", patterns: ["/admin/catalog/**"] }, description: "Manage offerings and pricing", requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "platform-integrations", label: "Integrations", href: "/admin/integrations", icon: "integration", group: "infrastructure", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/integrations" }, description: "Connected systems and providers", requiredCapabilities: ["view_integrations"] },
  { kind: "product", level: 2, id: "platform-sync-history", label: "Sync History", href: "/admin/sync-history", icon: "integration", group: "infrastructure", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/sync-history" }, requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "platform-health", label: "Provider Health", href: "/admin/provider-health", icon: "integration", group: "infrastructure", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/provider-health" }, requiredCapabilities: ["view_internal_operations"] },
  { kind: "product", level: 2, id: "platform-audit", label: "Audit", href: "/admin/audit", icon: "operations", group: "infrastructure", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/audit" }, requiredCapabilities: ["view_internal_operations"] },
  { kind: "utility", level: 1, id: "internal-workspace", label: "Internal Workspace", href: "/admin/internal-workspace", icon: "settings", group: "settings", experience: "operations-console", availability: "available", activeMatch: { type: "prefix", prefix: "/admin/internal-workspace" }, description: "Internal reporting, learning, and commerce workspaces", requiredCapabilities: ["view_internal_operations"] },
] satisfies readonly NavigationItem[];
