export class InvestmentOpportunityError extends Error {
  constructor(public readonly code: "OPPORTUNITY_NOT_FOUND" | "OPPORTUNITY_ACCESS_DENIED" | "OPPORTUNITY_ARCHIVED" | "INVALID_STATUS_TRANSITION" | "OPPORTUNITY_ROUTE_MISMATCH" | "OPPORTUNITY_PROPERTY_MISMATCH" | "ANALYSIS_ALREADY_SAVED" | "ANALYSIS_NOT_FOUND" | "ANALYSIS_INVALID" | "CONCURRENT_OPPORTUNITY_MODIFICATION" | "INVALID_OPPORTUNITY_NAME" | "INVALID_OPPORTUNITY_TAG" | "OPPORTUNITY_PERSISTENCE_FAILED", message: string, public readonly cause?: unknown) { super(message); this.name = "InvestmentOpportunityError"; }
}
