import type { InvestmentWorkspaceAnalysisResult } from "@/features/investment-intelligence";
import { assessOpportunityStatusTransition, createOpportunityOwnerId, type InvestmentOpportunity, type InvestmentOpportunityRoute, type OpportunityPropertyReference } from "../domain";
import type { InvestmentOpportunityRepository } from "./ports/repository";

export function buildOpportunityPropertyReference(result: InvestmentWorkspaceAnalysisResult, capturedAt: Date): OpportunityPropertyReference {
  const resolution = result.propertyResolution, property = resolution.status === "resolved" ? resolution.property : undefined, subject = result.lifecycleResult.analysis.property, location = subject.location;
  const provider = property?.providerReferences[0];
  return Object.freeze({ ...(property ? { marketPropertyId: property.id } : {}), normalizedAddress: Object.freeze({ address1: location.address1, ...(location.address2 ? { address2: location.address2 } : {}), city: location.city, state: location.state, postalCode: location.postalCode, country: "US" }), displayAddress: property?.address.formatted ?? `${location.address1}, ${location.city}, ${location.state} ${location.postalCode}`, propertyType: property?.characteristics.propertyType, bedrooms: subject.bedrooms, bathrooms: subject.bathrooms, ...(subject.squareFeet ? { squareFeet: subject.squareFeet } : {}), ...(subject.yearBuilt ? { yearBuilt: subject.yearBuilt } : {}), ...(provider ? { providerReference: { provider: provider.provider, externalId: provider.externalId } } : {}), resolutionStatus: property ? "resolved" : "user-supplied", capturedAt: new Date(capturedAt) });
}
export function buildOpportunitySourceSummary(result: InvestmentWorkspaceAnalysisResult) { const assumptions = result.investmentAnalysisContext.assumptions, count = (source: string) => assumptions.filter(item => item.source === source).length; return Object.freeze({ userSuppliedCount: count("user"), learningSuppliedCount: count("applied-learning"), marketSuppliedCount: count("market"), defaultSuppliedCount: count("system-default"), overrides: Object.freeze([]), marketEvidenceAvailable: result.investmentMarketContext.evidence.length > 0, marketAnalysisStatus: result.investmentMarketContext.status }); }
export async function listCompatibleInvestmentOpportunities(repository: InvestmentOpportunityRepository, input: Readonly<{ ownerId: string; route: InvestmentOpportunityRoute; property: OpportunityPropertyReference }>) {
  const page = await repository.list({ ownerId: createOpportunityOwnerId(input.ownerId), route: input.route, includeArchived: false, limit: 100 });
  return Object.freeze(page.items.filter(value => compatible(value, input.route, input.property)).map(value => { const current = value.props.analyses.find(item => item.id.value === value.props.currentAnalysisId?.value); return Object.freeze({ id: value.id.value, name: value.props.name.value, status: value.props.status, aggregateVersion: value.version, analysisCount: value.props.analyses.length, currentRecommendation: current?.props.resultSnapshot.recommendation.recommendation, lastAnalyzedAt: current?.props.resultSnapshot.analyzedAt }); }));
}
function compatible(value: InvestmentOpportunity, route: InvestmentOpportunityRoute, property: OpportunityPropertyReference) { if (value.props.route !== route || value.props.archivedAt) return false; const left = value.props.property, normalize = (text: string) => text.toLowerCase().replace(/[^a-z0-9]/g, ""); return Boolean(left.marketPropertyId && property.marketPropertyId && left.marketPropertyId === property.marketPropertyId) || (normalize(left.normalizedAddress.address1) === normalize(property.normalizedAddress.address1) && normalize(left.normalizedAddress.postalCode) === normalize(property.normalizedAddress.postalCode)); }
export function getAllowedOpportunityStatusTransitions(opportunity: InvestmentOpportunity) { const statuses = ["evaluating", "researching", "shortlisted", "offer-submitted", "under-contract", "acquired", "rejected"] as const; return Object.freeze(statuses.filter(next => assessOpportunityStatusTransition(opportunity.props.status, next, Boolean(opportunity.props.archivedAt)).allowed)); }
export async function buildOpportunityReanalysisInput(repository: InvestmentOpportunityRepository, input: Readonly<{ ownerId: string; opportunityId: string }>): Promise<Readonly<{ opportunityId: string; opportunityName: string; currentSequence: number; lastAnalyzedAt: Date; route: InvestmentOpportunityRoute; property: OpportunityPropertyReference; userAssumptions: Readonly<Record<string, string | number | boolean>>; aggregateVersion: number }> | null> { const opportunity = await repository.findById((await import("../domain")).createInvestmentOpportunityId(input.opportunityId), createOpportunityOwnerId(input.ownerId)); if (!opportunity) return null; const current = opportunity.props.analyses.find(item => item.id.value === opportunity.props.currentAnalysisId?.value); if (!current) return null; return Object.freeze({ opportunityId: opportunity.id.value, opportunityName: opportunity.props.name.value, currentSequence: current.sequence, lastAnalyzedAt: current.props.resultSnapshot.analyzedAt, route: opportunity.props.route, property: opportunity.props.property, userAssumptions: current.props.resultSnapshot.reanalysis?.userAssumptions ?? Object.freeze({}), aggregateVersion: opportunity.version }); }
