"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { submitFurnishingActivationCommand } from "../activation/actions";
import { validateControlReason } from "@/features/furnishing-studio/release-controls";
export default function GlobalEmergencyControl({ releaseId, version, engaged }: { releaseId: string; version: number; engaged: boolean }) {
 const router=useRouter(),[open,setOpen]=useState(false),[reason,setReason]=useState(""),[message,setMessage]=useState(""),[busy,startTransition]=useTransition();
 async function suspend(){const error=validateControlReason(reason);if(error){setMessage(error);return}const result=await submitFurnishingActivationCommand({command:"global-kill-switch",target:"global",targetId:releaseId,state:"disabled",expectedVersion:version,reason,actorId:"authenticated-admin",actorRole:"admin",correlationId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID()});setMessage(result.ok?"Global furnishing release is protected.":`${result.code}: ${result.message}`);if(result.ok){setOpen(false);startTransition(()=>router.refresh())}}
 return <section className="rounded-2xl border border-red-300 bg-red-50 p-5"><h2 className="text-xl font-semibold">Global emergency suspension</h2><p className="mt-2 text-sm">Affects all furnishing release activity. Existing data and immutable evidence remain preserved.</p>{engaged?<p className="mt-4 font-semibold text-red-900">Global safety control is already engaged.</p>:<button onClick={()=>setOpen(true)} className="mt-4 min-h-11 rounded-xl bg-red-800 px-4 font-semibold text-white">Suspend globally…</button>}<p role="status" aria-live="polite" className="mt-2 text-sm">{busy?"Refreshing authoritative state…":message}</p>{open?<div role="dialog" aria-modal="true" aria-labelledby="global-suspension-title" className="fixed inset-0 z-50 grid place-items-center bg-stone-950/60 p-4" onKeyDown={event=>{if(event.key==="Escape")setOpen(false)}}><section className="w-full max-w-lg rounded-2xl bg-white p-6"><h2 id="global-suspension-title" className="text-xl font-semibold">Suspend the global furnishing release</h2><p className="mt-2 text-sm">All bounded capabilities become unavailable. This creates no external effect.</p><label htmlFor="global-suspension-reason" className="mt-5 block font-semibold">Required reason</label><textarea id="global-suspension-reason" value={reason} onChange={event=>setReason(event.target.value)} minLength={12} maxLength={500} className="mt-2 min-h-28 w-full rounded-xl border p-3"/><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button autoFocus onClick={()=>setOpen(false)} className="min-h-11 rounded-xl border px-4 font-semibold">Cancel</button><button onClick={suspend} className="min-h-11 rounded-xl bg-red-800 px-4 font-semibold text-white">Suspend global furnishing release</button></div></section></div>:null}</section>;
}
