import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import type { HpmOperationalHealth, HpmReportResult } from "@/platform/hpm";
import { HPM_STANDARD_REPORTS } from "@/platform/hpm";
import { parseHpmWorkspaceQuery } from "../application";
import { HpmOperationalHealthView, HpmPrintReport, HpmReportCatalog, HpmReportView } from "./hpm-reporting";

const query = parseHpmWorkspaceQuery({ to: "2026-08-09" }, new Date("2026-08-09T12:00:00Z"));
const metric = { metricKey: "active-attention-count", metricVersion: "v1", value: 2, unit: "count" as const, state: "available" as const, numerator: 2, explanation: "Authorized active attention items." };
const report = { runId: "run", definitionId: "definition", reportKey: "executive-summary", definitionVersion: "v1", metricPolicyVersions: { "active-attention-count": "hpm-metrics-v1" }, scope: { type: "portfolio", propertyCount: 1 }, from: "2026-07-10T00:00:00Z", to: "2026-08-09T23:59:59Z", timeZone: "America/Chicago", asOf: "2026-08-09T23:59:59Z", generatedAt: "2026-08-09T23:59:59Z", sourceVersions: [], sourceFreshness: [], coverage: { availableSources: 1, applicableSources: 7 }, completeness: "partial", limitations: ["Learning source unavailable"], caveats: ["Authorize before aggregation"], sections: [{ key: "summary", title: "Summary", metrics: [metric], rows: [] }, { key: "lifecycle", title: "Lifecycle stages", metrics: [], rows: [{ id: "learn", label: "Learn", values: [{ ...metric, metricKey: "stage-visible-count", value: null, state: "unavailable", explanation: "Source unavailable" }], drilldown: "/dashboard/hpm/lifecycle?stage=learn" }] }], drilldowns: [], exportEligibility: { csv: true, print: true }, warnings: [], resultChecksum: "checksum", correlationId: "correlation" } as HpmReportResult;

describe("HPM-001E reporting presentation", () => {
  it("renders ten deep-linked standard reports", () => { const html = renderToStaticMarkup(<HpmReportCatalog definitions={HPM_STANDARD_REPORTS} query={query} />); expect((html.match(/Run report/g) ?? [])).toHaveLength(10); expect(html).toContain("Executive HPM Summary"); });
  it("renders definition explanations, canonical values, unavailable state, accessible tables, and exports", () => { const html = renderToStaticMarkup(<HpmReportView report={report} query={query} exportsEnabled />); expect(html).toContain("Metric definition"); expect(html).toContain("Numerator:"); expect(html).toContain("Unavailable"); expect(html).toContain("<caption"); expect(html).toContain("CSV"); expect(html).toContain("Print view"); });
  it("renders a print representation from the same checksum", () => { const html = renderToStaticMarkup(<HpmPrintReport report={report} />); expect(html).toContain("checksum"); expect(html).toContain("<main"); expect(html).toContain("<caption"); });
  it("renders safe operational metadata and disabled controls", () => { const health = { status: "partial", evaluatedAt: report.asOf, featureFlags: { reports: true, exports: false, health: true, operations: false }, sources: [{ capability: "learning", freshness: "not-configured", policyVersion: "v1" }], projection: { completeness: "partial", projectedAt: report.asOf, failureCount: 0 }, cache: { status: "available", policyVersion: "v1", entries: 0 }, reports: { status: "available", definitionCount: 10, recentFailures: [] }, exports: { status: "disabled", formats: [] }, jobs: { status: "disabled", active: 0, oldestAgeMs: null }, degradedModes: ["learning:not-configured"], runbook: "/docs/runbooks/hpm-reporting-operations", validCommands: [] } as HpmOperationalHealth; const html = renderToStaticMarkup(<HpmOperationalHealthView health={health} />); expect(html).toContain("Operational commands are disabled"); expect(html).toContain("Learning Not Configured"); expect(html).not.toMatch(/token|credential|payload/i); });
});
