import Link from "next/link";
import { AlertTriangle, ArrowRight, Download, Printer, ShieldCheck } from "lucide-react";
import { StatusChip, WorkspaceCard, WorkspaceEmptyState, WorkspaceSectionHeading } from "@/components/application-layout";
import type { HpmOperationalHealth, HpmReportDefinition, HpmReportMetricValue, HpmReportResult } from "@/platform/hpm";
import { getHpmMetricDefinition } from "@/platform/hpm";
import { hpmContextSearch, type HpmWorkspaceQuery } from "../application";

export function HpmReportCatalog({ definitions, query }: { definitions: readonly HpmReportDefinition[]; query: HpmWorkspaceQuery }) {
  return <section><WorkspaceSectionHeading title="Standard reports" description="Governed cross-lifecycle reports. Definitions and metric policies are immutable and versioned." /><div className="grid gap-4 md:grid-cols-2">{definitions.map((definition) => <WorkspaceCard key={definition.id} className="p-6"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-teal-800">{definition.category}</p><h2 className="mt-2 text-xl font-semibold">{definition.name}</h2></div><StatusChip>{definition.version}</StatusChip></div><p className="mt-3 text-sm leading-6 text-stone-600">{definition.description}</p><p className="mt-4 text-xs text-stone-500">{definition.metricReferences.length} governed metrics · {definition.exportFormats.join(" and ")} ready</p><Link className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-semibold" href={`/dashboard/hpm/reports/${definition.key}?${hpmContextSearch(query)}`}>Run report <ArrowRight className="h-4 w-4" /></Link></WorkspaceCard>)}</div></section>;
}

export function HpmReportView({ report, query, exportsEnabled }: { report: HpmReportResult; query: HpmWorkspaceQuery; exportsEnabled: boolean }) {
  return <article className="space-y-10"><header><p className="text-sm font-semibold text-teal-800">Governed HPM report</p><h2 className="mt-2 text-3xl font-semibold">{title(report.reportKey)}</h2><div className="mt-4 flex flex-wrap gap-2"><StatusChip tone={report.completeness === "complete" ? "healthy" : "attention"}>{title(report.completeness)}</StatusChip><StatusChip>{report.definitionVersion}</StatusChip><StatusChip>{report.scope.propertyCount} properties</StatusChip></div><p className="mt-3 text-sm text-stone-600">Period <time>{report.from.slice(0, 10)}</time>–<time>{report.to.slice(0, 10)}</time> · {report.timeZone} · as of <time dateTime={report.asOf}>{format(report.asOf)}</time></p>{exportsEnabled ? <div className="mt-5 flex gap-3"><a className="inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-semibold" href={`/api/hpm/reports/${report.reportKey}/csv?${hpmContextSearch(query)}`}><Download className="h-4 w-4" />CSV</a><Link className="inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-semibold" href={`/dashboard/hpm/reports/${report.reportKey}/print?${hpmContextSearch(query)}`}><Printer className="h-4 w-4" />Print view</Link></div> : null}</header>
    {report.completeness !== "complete" ? <div role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 text-amber-800" /><div><h2 className="font-semibold">{title(report.completeness)} report</h2><p className="mt-1 text-sm">Unavailable sources remain unavailable and do not contribute zero values.</p></div></div></div> : null}
    {report.sections.map((section) => <section key={section.key}><WorkspaceSectionHeading title={section.title} />{section.metrics.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{section.metrics.map((metric) => <MetricCard key={metric.metricKey} metric={metric} />)}</div> : null}{section.rows.length ? <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[42rem] text-left text-sm"><caption className="sr-only">{section.title} by lifecycle stage</caption><thead><tr className="border-b"><th className="p-4" scope="col">Stage</th><th className="p-4" scope="col">Visible records</th><th className="p-4" scope="col">Attention</th><th className="p-4" scope="col">Detail</th></tr></thead><tbody>{section.rows.map((row) => <tr className="border-b last:border-0" key={row.id}><th className="p-4" scope="row">{row.label}</th>{row.values.map((metric) => <td className="p-4" key={metric.metricKey}>{display(metric)}</td>)}<td className="p-4">{row.drilldown ? <Link className="font-semibold text-teal-800" href={`${row.drilldown}&${hpmContextSearch(query)}`}>View lifecycle</Link> : "Unavailable"}</td></tr>)}</tbody></table></div> : null}</section>)}
    <section><WorkspaceSectionHeading title="Coverage and limitations" /><WorkspaceCard className="p-6"><p className="text-sm"><strong>{report.coverage.availableSources} of {report.coverage.applicableSources}</strong> applicable sources available.</p><ul className="mt-4 space-y-2 text-sm text-stone-600">{[...report.limitations, ...report.caveats].map((item) => <li key={item}>• {item}</li>)}</ul><p className="mt-5 break-all font-mono text-xs text-stone-500">Result {report.resultChecksum}</p></WorkspaceCard></section>
  </article>;
}

export function HpmOperationalHealthView({ health }: { health: HpmOperationalHealth }) { return <section className="space-y-10"><header><p className="text-sm font-semibold text-teal-800">Authorized operations</p><h2 className="mt-2 text-3xl font-semibold">HPM operational health</h2><div className="mt-4"><StatusChip tone={health.status === "healthy" ? "healthy" : "attention"}>{title(health.status)}</StatusChip></div><p className="mt-3 text-sm text-stone-600">Safe integration metadata only. Operational controls never mutate source-domain records.</p></header><section><WorkspaceSectionHeading title="Integration sources" /><div className="grid gap-4 md:grid-cols-2">{health.sources.map((source) => <WorkspaceCard className="p-5" key={source.capability}><div className="flex justify-between gap-3"><h3 className="font-semibold">{title(source.capability)}</h3><StatusChip tone={source.freshness === "current" ? "healthy" : "attention"}>{title(source.freshness)}</StatusChip></div><p className="mt-3 text-xs text-stone-500">Contract {source.contractVersion ?? "Unavailable"} · policy {source.policyVersion}</p>{source.lastSuccessfulAsOf ? <p className="mt-2 text-xs">Last success {format(source.lastSuccessfulAsOf)}</p> : null}</WorkspaceCard>)}</div></section><section><WorkspaceSectionHeading title="Subsystems" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><HealthCard title="Projection" state={health.projection.completeness} detail={`${health.projection.failureCount} failures`} /><HealthCard title="Cache" state={health.cache.status} detail={`${health.cache.entries} entries`} /><HealthCard title="Reports" state={health.reports.status} detail={`${health.reports.definitionCount} definitions`} /><HealthCard title="Jobs" state={health.jobs.status} detail={`${health.jobs.active} active`} /></div></section>{health.degradedModes.length ? <section><WorkspaceSectionHeading title="Current degraded modes" /><ul className="space-y-2">{health.degradedModes.map((mode) => <li className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm" key={mode}>{title(mode)}</li>)}</ul></section> : <WorkspaceEmptyState title="No degraded modes" description="The current operational projection found no degraded state." />}<section><WorkspaceSectionHeading title="Recovery controls" /><WorkspaceCard className="p-6"><ShieldCheck className="h-6 w-6 text-teal-800" /><p className="mt-3 text-sm text-stone-600">{health.validCommands.length ? "Operational commands are admitted only through bounded, authorized, idempotent jobs. Material rebuilds require dry-run rehearsal." : "Operational commands are disabled. Read-only health remains available."}</p><p className="mt-4 text-xs text-stone-500">Runbook: {health.runbook}</p></WorkspaceCard></section></section>; }

export function HpmPrintReport({ report }: { report: HpmReportResult }) { return <main className="mx-auto max-w-5xl bg-white p-10 text-stone-950"><h1 className="text-3xl font-semibold">{title(report.reportKey)}</h1><p className="mt-2 text-sm">{report.from.slice(0, 10)}–{report.to.slice(0, 10)} · {report.timeZone} · {title(report.completeness)}</p>{report.sections.map((section) => <section className="mt-8" key={section.key}><h2 className="text-xl font-semibold">{section.title}</h2><table className="mt-3 w-full border-collapse text-left text-sm"><caption className="sr-only">{section.title}</caption><thead><tr><th className="border p-2">Metric</th><th className="border p-2">Value</th><th className="border p-2">State</th></tr></thead><tbody>{section.metrics.map((metric) => <tr key={metric.metricKey}><th className="border p-2">{getHpmMetricDefinition(metric.metricKey)?.name ?? metric.metricKey}</th><td className="border p-2">{display(metric)}</td><td className="border p-2">{title(metric.state)}</td></tr>)}</tbody></table></section>)}<section className="mt-8"><h2 className="text-xl font-semibold">Limitations</h2><ul className="mt-3 list-disc pl-5 text-sm">{report.limitations.map((item) => <li key={item}>{item}</li>)}</ul></section><p className="mt-8 break-all font-mono text-xs">Result checksum {report.resultChecksum}</p></main>; }

function MetricCard({ metric }: { metric: HpmReportMetricValue }) { const definition = getHpmMetricDefinition(metric.metricKey, metric.metricVersion); return <WorkspaceCard className="p-5"><p className="text-sm font-semibold">{definition?.name ?? title(metric.metricKey)}</p><p className="mt-4 text-3xl font-semibold">{display(metric)}</p><p className="mt-2 text-xs leading-5 text-stone-600">{metric.explanation}</p>{definition ? <details className="mt-4 text-xs"><summary className="cursor-pointer font-semibold text-teal-800">Metric definition</summary><p className="mt-2">Numerator: {definition.numerator}</p><p>Denominator: {definition.denominator}</p><p>Policy: {definition.policyVersion}</p></details> : null}</WorkspaceCard>; }
function HealthCard({ title: label, state, detail }: { title: string; state: string; detail: string }) { return <WorkspaceCard className="p-5"><h3 className="font-semibold">{label}</h3><p className="mt-3 text-lg font-semibold">{title(state)}</p><p className="mt-1 text-xs text-stone-500">{detail}</p></WorkspaceCard>; }
function display(metric: HpmReportMetricValue) { if (metric.state === "empty-population") return "No eligible records"; if (metric.value === null) return "Unavailable"; return metric.unit === "percentage" ? `${metric.value}%` : String(metric.value); }
function title(value: string) { return value.replaceAll(/[-_:]/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function format(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Chicago" }).format(new Date(value)); }
