import { describe, expect, it } from "vitest";
import { AcquisitionType, PropertyType } from "../domain";
import { INVESTMENT_ASSUMPTION_GUIDANCE, INVESTMENT_NUMERIC_ASSUMPTION_POLICIES, applyStrategyTransition, buildInvestmentAnalysisReadiness, buildInvestmentAssumptionFingerprint, buildPreliminaryFinancialPreview, buildStrategyTransitionPlan, normalizeNumericAssumptionDraft, parseNumericAssumptionDraft } from "./index";
import type { InvestmentWorkspaceReadinessValues } from "./readiness";

const values: InvestmentWorkspaceReadinessValues = { acquisitionType: AcquisitionType.RentalArbitrage, address1: "Fort Worth property", city: "Fort Worth", state: "TX", postalCode: "76104", purchasePrice: 425000, closingCosts: 12000, furnishingBudget: 10000, propertyType: PropertyType.SingleFamily, bedrooms: 3, bathrooms: 2, squareFeet: 1068, downPaymentPercentage: 25, interestRatePercentage: 6.5, loanTermYears: 30, monthlyLease: 1574, securityDeposit: 750, leaseTermMonths: 12, startupCosts: 2500, utilitiesIncluded: false, projectedAdr: 150, projectedOccupancyPercentage: 60, averageLengthOfStay: 4, managementFeePercentage: 10, monthlyUtilities: 300, annualInsurance: 1800, annualTaxes: 4200, annualCleaning: 7200, annualSoftware: 1200, annualSupplies: 1800, maintenanceReservePercentage: 5, capitalReservePercentage: 3 };

describe("II-009 numeric input foundation", () => {
  it.each([["01068", "1068", 1068], ["02", "2", 2], ["15.50", "15.5", 15.5], ["1,574", "1574", 1574]] as const)("normalizes %s without changing economic meaning", (draft, text, normalizedValue) => expect(normalizeNumericAssumptionDraft(draft, INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.monthlyLease)).toMatchObject({ text, normalizedValue, status: "valid" }));
  it("preserves empty and incomplete editing states without coercing them", () => { expect(parseNumericAssumptionDraft("", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.purchasePrice)).toMatchObject({ status: "empty", normalizedValue: null }); expect(parseNumericAssumptionDraft("0.", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.interestRatePercentage)).toMatchObject({ status: "incomplete", normalizedValue: null }); expect(parseNumericAssumptionDraft(".", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.interestRatePercentage).status).toBe("incomplete"); });
  it("validates integer, precision, and range policies", () => { expect(parseNumericAssumptionDraft("2.5", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.bedrooms).status).toBe("invalid"); expect(parseNumericAssumptionDraft("101", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.projectedOccupancyPercentage).status).toBe("invalid"); expect(parseNumericAssumptionDraft("6.1234", INVESTMENT_NUMERIC_ASSUMPTION_POLICIES.interestRatePercentage).status).toBe("invalid"); });
});

describe("II-009 guidance and expense decision", () => {
  it("keeps priority guidance canonical and explicit", () => { expect(INVESTMENT_ASSUMPTION_GUIDANCE.startupCosts.excludes).toEqual(expect.arrayContaining(["Furnishing budget", "Security deposit"])); expect(INVESTMENT_ASSUMPTION_GUIDANCE.managementFeePercentage.excludes).toContain("Booking-platform fees"); expect(INVESTMENT_ASSUMPTION_GUIDANCE.annualCleaning.description).toContain("not a cleaning fee charged to a guest"); expect(INVESTMENT_ASSUMPTION_GUIDANCE.projectedAdr.description).toContain("accommodation revenue"); });
});

describe("II-009 preliminary preview and readiness", () => {
  it("projects seven explainable, explicitly preliminary rental metrics", () => { const preview = buildPreliminaryFinancialPreview(values); expect(preview.title).toBe("Preliminary Financial Preview"); expect(preview.metrics).toHaveLength(7); expect(preview.metrics.every(metric => metric.isPreliminary && metric.formulaDescription && metric.thresholdExplanation && metric.rationale)).toBe(true); expect(preview.metrics.map(metric => metric.label)).toContain("Return on initial cash"); expect(preview.metrics.map(metric => metric.label)).toContain("NOI before lease"); });
  it("shows negative cash flow as weak without blocking otherwise valid analysis", () => { const preview = buildPreliminaryFinancialPreview({ ...values, projectedAdr: 50, projectedOccupancyPercentage: 30 }); const cashFlow = preview.metrics.find(metric => metric.id === "cash-flow"); expect(cashFlow?.status).toBe("weak"); expect(cashFlow?.improvementDirection).toContain("Reduce lease cost"); expect(buildInvestmentAnalysisReadiness(values).fullAnalysis.available).toBe(true); });
  it("distinguishes draft, ready, stale, and integration-blocked states", () => { expect(buildInvestmentAnalysisReadiness({ ...values, address1: "" }).resultState).toBe("draft"); expect(buildInvestmentAnalysisReadiness(values).resultState).toBe("ready"); expect(buildInvestmentAnalysisReadiness(values, { stale: true }).resultState).toBe("stale"); const blocked = buildInvestmentAnalysisReadiness(values, { integrationAvailable: false }); expect(blocked.resultState).toBe("blocked"); expect(blocked.unavailableIntegrations[0].description).not.toContain("configured"); });
});

describe("II-009 strategy integrity", () => {
  it("uses a deterministic material fingerprint independent of object order", () => { const reordered = Object.fromEntries(Object.entries(values).reverse()) as unknown as InvestmentWorkspaceReadinessValues; expect(buildInvestmentAssumptionFingerprint(values)).toBe(buildInvestmentAssumptionFingerprint(reordered)); });
  it("requires confirmation for dirty route state and preserves only property fields", () => { const defaults = { ...values, monthlyLease: 2400, securityDeposit: 2400, startupCosts: 5000, furnishingBudget: 25000 }; const plan = buildStrategyTransitionPlan(values, AcquisitionType.Purchase, defaults, true); expect(plan.requiresConfirmation).toBe(true); const transitioned = applyStrategyTransition(values, AcquisitionType.Purchase, defaults); expect(transitioned.address1).toBe(values.address1); expect(transitioned.bedrooms).toBe(3); expect(transitioned.monthlyLease).toBe(defaults.monthlyLease); expect(transitioned.furnishingBudget).toBe(defaults.furnishingBudget); expect(transitioned.acquisitionType).toBe(AcquisitionType.Purchase); });
});
