import { ActionPlan, PlatformAction, createActionId, createWorkspaceId, type ActionActor, type ActionPlanProps, type ActionPriority, type ProposedPlanAction } from "../domain";
import type { PlatformActionRepository } from "./action-repository";

export type ExecuteFailureCode = "PLAN_NOT_FOUND" | "PLAN_VERSION_CONFLICT" | "PLAN_ACTIVATION_INVALID" | "ACTION_ASSIGNMENT_UNAUTHORIZED" | "PROPERTY_ACCESS_DENIED" | "CONCURRENT_MODIFICATION" | "PERSISTENCE_FAILURE";
export type ExecuteCommandResult<T> = Readonly<{ ok: true; value: T }> | Readonly<{ ok: false; code: ExecuteFailureCode; message: string; retryable: boolean; currentVersion?: number; submittedInput?: unknown }>;
export type ExecuteEntityType="plan"|"action"|"evidence"|"blocker"|"dependency"|"recurrence"|"escalation";
export type ExecuteActivityEvent = Readonly<{ id: string; workspaceId: string; entityType: ExecuteEntityType; entityId: string; actionId?: string; eventType: string; actor: ActionActor; occurredAt: Date; metadata: Readonly<Record<string, unknown>>; correlationId: string }>;
export type ExecuteNotificationIntent = Readonly<{ id: string; workspaceId: string; recipientType: string; recipientId: string; eventType: string; entityType: ExecuteEntityType; entityId: string; templateVariables: Readonly<Record<string, string>>; channel: "in-app" | "email" | "sms" | "slack" | "teams"; status: "pending"; idempotencyKey: string; attemptCount: 0; createdAt: Date }>;

export interface ActionPlanRepository { findById(workspaceId: string, planId: string): Promise<ActionPlan | null>; list(workspaceId: string): Promise<readonly ActionPlan[]>; add(plan: ActionPlan): Promise<void>; replace(plan: ActionPlan, expectedVersion: number): Promise<void>; }
export interface ExecuteActivityRepository { append(events: readonly ExecuteActivityEvent[]): Promise<void>; list(workspaceId: string, entityType: ExecuteActivityEvent["entityType"], entityId: string): Promise<readonly ExecuteActivityEvent[]>; }
export interface ExecuteNotificationOutbox { add(intents: readonly ExecuteNotificationIntent[]): Promise<void>; }
export type ExecuteTransactionContext = Readonly<{ plans: ActionPlanRepository; actions: PlatformActionRepository; activity: ExecuteActivityRepository; notifications: ExecuteNotificationOutbox }>;
export interface ExecuteUnitOfWork { execute<T>(operation: (context: ExecuteTransactionContext) => Promise<T>): Promise<T>; }
export class ExecutePersistenceConflict extends Error {
  public readonly code = "PLAN_VERSION_CONFLICT" as const;
  public constructor(public readonly currentVersion?: number) { super("Action plan version conflict."); this.name = "ExecutePersistenceConflict"; }
}
export interface ExecuteAuthorization { canManagePlans(input: Readonly<{ workspaceId: string; actor: ActionActor }>): Promise<boolean>; canAccessProperty(input: Readonly<{ workspaceId: string; propertyId: string; actor: ActionActor }>): Promise<boolean>; canAssign(input: Readonly<{ workspaceId: string; propertyId?: string; owner: ProposedPlanAction["owner"]; actor: ActionActor }>): Promise<boolean>; }

export type CreateManualPlanCommand = Readonly<{ id: string; workspaceId: string; title: string; description?: string; scope: ActionPlanProps["scope"]; owner: ActionPlanProps["owner"]; priority: ActionPriority; actions?: readonly ProposedPlanAction[]; actor: ActionActor; occurredAt: Date }>;
export type CreateDecisionPlanCommand = Readonly<{ id: string; workspaceId: string; decision: Parameters<typeof ActionPlan.fromApprovedDecision>[0]["decision"]; owner: ActionPlanProps["owner"]; proposedActions?: readonly ProposedPlanAction[]; actor: ActionActor }>;
export type UpdateDraftPlanCommand = Readonly<{ workspaceId: string; planId: string; expectedVersion: number; actor: ActionActor; changes: Parameters<ActionPlan["updateDraft"]>[0] }>;
export type ActivatePlanCommand = Readonly<{ workspaceId: string; planId: string; expectedVersion: number; actor: ActionActor; occurredAt: Date; correlationId: string; acknowledgeUnassigned?: boolean }>;
export type DraftActionCommandContext = Readonly<{ workspaceId:string;planId:string;expectedVersion:number;actor:ActionActor;correlationId?:string }>;
export type AddDraftActionCommand = DraftActionCommandContext & Readonly<{ input:Omit<ProposedPlanAction,"id"|"position"> }>;
export type UpdateDraftActionCommand = DraftActionCommandContext & Readonly<{ actionId:string;changes:Partial<Omit<ProposedPlanAction,"id"|"position">> }>;
export type RemoveDraftActionCommand = DraftActionCommandContext & Readonly<{ actionId:string }>;
export type ReorderDraftActionsCommand = DraftActionCommandContext & Readonly<{ orderedActionIds:readonly string[] }>;

export class ExecutePlanApplicationService {
  public constructor(private readonly dependencies: Readonly<{ unitOfWork: ExecuteUnitOfWork; authorization: ExecuteAuthorization; createId: () => string; now?: () => Date }>) {}

  public async createManualDraft(command: CreateManualPlanCommand): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => {
    await this.authorizePlan(command.workspaceId, command.actor); await this.authorizeProperties(command.workspaceId, command.scope.propertyIds, command.actor);
    const plan = ActionPlan.createDraft({ id: command.id, workspaceId: command.workspaceId, title: command.title, ...(command.description ? { description: command.description } : {}), origin: { type: "manual" }, scope: command.scope, owner: command.owner, priority: command.priority, successMetrics: [], actions: command.actions ?? [], createdBy: command.actor, createdAt: command.occurredAt });
    await this.dependencies.unitOfWork.execute(async (context) => { await context.plans.add(plan); await context.activity.append([this.event(command.workspaceId, "plan", plan.props.id, "plan-created", command.actor, command.occurredAt, `plan:${plan.props.id}:created`)]); }); return plan.props;
  }); }

  public async createFromDecision(command: CreateDecisionPlanCommand): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => {
    await this.authorizePlan(command.workspaceId, command.actor); await this.authorizeProperties(command.workspaceId, command.decision.propertyIds ?? [], command.actor);
    const plan = ActionPlan.fromApprovedDecision({ id: command.id, workspaceId: command.workspaceId, decision: command.decision, owner: command.owner, proposedActions: command.proposedActions });
    await this.dependencies.unitOfWork.execute(async (context) => { await context.plans.add(plan); await context.activity.append([this.event(command.workspaceId, "plan", plan.props.id, "decision-converted-to-plan", command.actor, command.decision.approvedAt, `decision:${command.decision.id}:plan:${plan.props.id}`)]); }); return plan.props;
  }); }

  public async getPlan(workspaceId: string, planId: string, actor: ActionActor): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => { await this.authorizePlan(workspaceId, actor); const plan = await this.dependencies.unitOfWork.execute((context) => context.plans.findById(workspaceId, planId)); if (!plan) throw failure("PLAN_NOT_FOUND", "Action plan was not found.", false); return plan.props; }); }
  public async listPlans(workspaceId: string, actor: ActionActor): Promise<ExecuteCommandResult<readonly ActionPlanProps[]>> { return this.guard(async () => { await this.authorizePlan(workspaceId, actor); return this.dependencies.unitOfWork.execute(async (context) => Object.freeze((await context.plans.list(workspaceId)).map((plan) => plan.props))); }); }

  public async updateDraft(command: UpdateDraftPlanCommand): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => {
    await this.authorizePlan(command.workspaceId, command.actor);
    return this.dependencies.unitOfWork.execute(async (context) => { const current = await context.plans.findById(command.workspaceId, command.planId); if (!current) throw failure("PLAN_NOT_FOUND", "Action plan was not found.", false); let updated: ActionPlan; try { updated = current.updateDraft({ ...command.changes, expectedVersion: command.expectedVersion }); } catch (error) { if (error instanceof TypeError && /version conflict/.test(error.message)) throw failure("PLAN_VERSION_CONFLICT", "This plan changed in another session. Reload the latest version.", true); throw error; } await context.plans.replace(updated, command.expectedVersion); await context.activity.append([this.event(command.workspaceId, "plan", command.planId, "plan-updated", command.actor, this.now(), `plan:${command.planId}:v${updated.props.version}`)]); return updated.props; });
  }); }

  public async activate(command: ActivatePlanCommand): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => {
    await this.authorizePlan(command.workspaceId, command.actor);
    return this.dependencies.unitOfWork.execute(async (context) => {
      const current = await context.plans.findById(command.workspaceId, command.planId); if (!current) throw failure("PLAN_NOT_FOUND", "Action plan was not found.", false); if (current.props.version !== command.expectedVersion) throw failure("PLAN_VERSION_CONFLICT", "This plan changed in another session. Reload the latest version.", true);
      await this.authorizeProperties(command.workspaceId, current.props.scope.propertyIds, command.actor);
      for (const proposed of current.props.actions) if (!(await this.dependencies.authorization.canAssign({ workspaceId: command.workspaceId, ...(proposed.propertyId ? { propertyId: proposed.propertyId } : {}), owner: proposed.owner, actor: command.actor }))) throw failure("ACTION_ASSIGNMENT_UNAUTHORIZED", `The owner for ${proposed.title} is not authorized.`, false);
      let active: ActionPlan; try { active = current.activate({ actor: command.actor, occurredAt: command.occurredAt, acknowledgeUnassigned: command.acknowledgeUnassigned }); } catch (error) { throw failure("PLAN_ACTIVATION_INVALID", error instanceof Error ? error.message : "The plan cannot be activated.", false); }
      const actions = current.props.actions.map((proposed) => this.actionFromProposal(command.workspaceId, current, proposed, command));
      for (const action of actions) await context.actions.add({ action });
      await context.plans.replace(active, command.expectedVersion);
      const events: ExecuteActivityEvent[] = [this.event(command.workspaceId, "plan", command.planId, "plan-activated", command.actor, command.occurredAt, command.correlationId), ...actions.map((action) => this.event(command.workspaceId, "action", action.id.value, "action-activated", command.actor, command.occurredAt, command.correlationId, action.id.value))];
      await context.activity.append(events);
      await context.notifications.add(actions.flatMap((action) => action.activeAssignment?.assigneeId ? [this.intent(command.workspaceId, action.activeAssignment.assigneeType, action.activeAssignment.assigneeId, action.id.value, action.title, command.occurredAt)] : []));
      return active.props;
    });
  }); }

  public async addDraftAction(command:AddDraftActionCommand):Promise<ExecuteCommandResult<ActionPlanProps>>{return this.mutateDraftAction(command,"draft-action-added",async(plan)=>{const action:ProposedPlanAction={...command.input,id:this.dependencies.createId(),position:plan.props.actions.length};await this.authorizeProposal(command.workspaceId,action,command.actor);return plan.addDraftAction({expectedVersion:command.expectedVersion,action});},{submittedInput:command.input});}
  public async updateDraftAction(command:UpdateDraftActionCommand):Promise<ExecuteCommandResult<ActionPlanProps>>{return this.mutateDraftAction(command,"draft-action-updated",async(plan)=>{const current=plan.props.actions.find((action)=>action.id===command.actionId);if(!current)throw failure("PLAN_ACTIVATION_INVALID","Draft Action does not belong to this plan.",false);const proposed={...current,...command.changes,id:current.id,position:current.position};await this.authorizeProposal(command.workspaceId,proposed,command.actor);return plan.updateDraftAction({expectedVersion:command.expectedVersion,actionId:command.actionId,changes:command.changes});},{actionId:command.actionId,submittedInput:command.changes});}
  public async removeDraftAction(command:RemoveDraftActionCommand):Promise<ExecuteCommandResult<ActionPlanProps>>{return this.mutateDraftAction(command,"draft-action-removed",async(plan)=>plan.removeDraftAction({expectedVersion:command.expectedVersion,actionId:command.actionId}),{actionId:command.actionId});}
  public async reorderDraftActions(command:ReorderDraftActionsCommand):Promise<ExecuteCommandResult<ActionPlanProps>>{return this.mutateDraftAction(command,"draft-actions-reordered",async(plan)=>plan.reorderDraftActions({expectedVersion:command.expectedVersion,orderedActionIds:command.orderedActionIds}),{submittedInput:command.orderedActionIds});}

  public async completePlan(workspaceId: string, planId: string, expectedVersion: number, actor: ActionActor, occurredAt: Date): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.changePlanStatus("complete", workspaceId, planId, expectedVersion, actor, occurredAt); }
  public async cancelPlan(workspaceId: string, planId: string, expectedVersion: number, actor: ActionActor, occurredAt: Date, reason: string): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.changePlanStatus("cancel", workspaceId, planId, expectedVersion, actor, occurredAt, reason); }
  public async history(workspaceId: string, planId: string, actor: ActionActor): Promise<ExecuteCommandResult<readonly ExecuteActivityEvent[]>> { return this.guard(async () => { await this.authorizePlan(workspaceId, actor); return this.dependencies.unitOfWork.execute((context) => context.activity.list(workspaceId, "plan", planId)); }); }

  private async changePlanStatus(operation: "complete" | "cancel", workspaceId: string, planId: string, expectedVersion: number, actor: ActionActor, occurredAt: Date, reason?: string): Promise<ExecuteCommandResult<ActionPlanProps>> { return this.guard(async () => { await this.authorizePlan(workspaceId, actor); return this.dependencies.unitOfWork.execute(async (context) => { const current=await context.plans.findById(workspaceId,planId); if(!current) throw failure("PLAN_NOT_FOUND","Action plan was not found.",false); let updated:ActionPlan; try { updated=operation==="complete"?current.complete({expectedVersion,actor,occurredAt}):current.cancel({expectedVersion,actor,occurredAt,reason:reason??""}); } catch(error){if(error instanceof TypeError&&/version conflict/.test(error.message))throw failure("PLAN_VERSION_CONFLICT","This plan changed in another session. Reload the latest version.",true);throw error;} await context.plans.replace(updated,expectedVersion); await context.activity.append([this.event(workspaceId,"plan",planId,`plan-${operation}d`,actor,occurredAt,`plan:${planId}:v${updated.props.version}`)]); return updated.props; }); }); }
  private async mutateDraftAction(command:DraftActionCommandContext,eventType:string,mutation:(plan:ActionPlan)=>Promise<ActionPlan>,metadata:Readonly<{actionId?:string;submittedInput?:unknown}>):Promise<ExecuteCommandResult<ActionPlanProps>>{return this.guard(async()=>{await this.authorizePlan(command.workspaceId,command.actor);return this.dependencies.unitOfWork.execute(async(context)=>{const current=await context.plans.findById(command.workspaceId,command.planId);if(!current)throw failure("PLAN_NOT_FOUND","Action plan was not found.",false);if(current.props.version!==command.expectedVersion)throw failure("PLAN_VERSION_CONFLICT","This plan changed in another session. Reload the latest version.",true,current.props.version,metadata.submittedInput);let updated:ActionPlan;try{updated=await mutation(current);}catch(error){throw failure("PLAN_ACTIVATION_INVALID",error instanceof Error?error.message:"The Draft Action change is invalid.",false,current.props.version,metadata.submittedInput);}await context.plans.replace(updated,command.expectedVersion);await context.activity.append([this.event(command.workspaceId,"plan",command.planId,eventType,command.actor,this.now(),command.correlationId??`plan:${command.planId}:v${updated.props.version}`,metadata.actionId)]);return updated.props;});});}
  private async authorizeProposal(workspaceId:string,proposed:ProposedPlanAction,actor:ActionActor):Promise<void>{if(proposed.propertyId&&!(await this.dependencies.authorization.canAccessProperty({workspaceId,propertyId:proposed.propertyId,actor})))throw failure("PROPERTY_ACCESS_DENIED","You do not have access to the proposed Action property.",false);if(!(await this.dependencies.authorization.canAssign({workspaceId,...(proposed.propertyId?{propertyId:proposed.propertyId}:{}),owner:proposed.owner,actor})))throw failure("ACTION_ASSIGNMENT_UNAUTHORIZED","The proposed Action owner is not authorized.",false);}
  private actionFromProposal(workspaceId: string, plan: ActionPlan, proposed: ProposedPlanAction, command: ActivatePlanCommand): PlatformAction { const owner = proposed.owner ?? plan.props.owner; if(!proposed.dueAt)throw failure("PLAN_ACTIVATION_INVALID",`A deadline is required for ${proposed.title}.`,false); let action=PlatformAction.createCommitted({id:createActionId(proposed.id),workspaceId:createWorkspaceId(workspaceId),title:proposed.title,...(proposed.description?{description:proposed.description}:{}),...(proposed.actionType?{actionType:proposed.actionType}:{}),priority:proposed.priority??plan.props.priority,owner,sources:[{type:plan.props.linkedDecisionId?"decision":"manual",...(plan.props.linkedDecisionId?{sourceId:plan.props.linkedDecisionId}:{}),...(plan.props.origin.capability?{capability:plan.props.origin.capability}:{}),recordedAt:command.occurredAt,recordedBy:command.actor}],createdAt:command.occurredAt,createdBy:command.actor,commandId:command.correlationId}); const context=()=>({workspaceId:action.workspaceId,expectedVersion:action.version,actor:command.actor,occurredAt:command.occurredAt,commandId:command.correlationId}); action=action.schedule({...context(),...(proposed.startAt?{startAfter:proposed.startAt}:{}),due:proposed.dueAt}); action=action.assign({...context(),assigneeType:owner.type,...(owner.id?{assigneeId:owner.id}:{queue:"unassigned"})}); return action.markReady(context()); }
  private async authorizePlan(workspaceId: string, actor: ActionActor): Promise<void> { if (!(await this.dependencies.authorization.canManagePlans({workspaceId,actor}))) throw failure("PROPERTY_ACCESS_DENIED","You do not have permission to manage action plans.",false); }
  private async authorizeProperties(workspaceId: string, propertyIds: readonly string[], actor: ActionActor): Promise<void> { for(const propertyId of propertyIds)if(!(await this.dependencies.authorization.canAccessProperty({workspaceId,propertyId,actor})))throw failure("PROPERTY_ACCESS_DENIED","You do not have access to one or more plan properties.",false); }
  private event(workspaceId:string,entityType:"plan"|"action",entityId:string,eventType:string,actor:ActionActor,occurredAt:Date,correlationId:string,actionId?:string):ExecuteActivityEvent{return Object.freeze({id:this.dependencies.createId(),workspaceId,entityType,entityId,...(actionId?{actionId}:{}),eventType,actor,occurredAt:new Date(occurredAt),metadata:Object.freeze({}),correlationId});}
  private intent(workspaceId:string,recipientType:string,recipientId:string,actionId:string,title:string,createdAt:Date):ExecuteNotificationIntent{return Object.freeze({id:this.dependencies.createId(),workspaceId,recipientType,recipientId,eventType:"new-assignment",entityType:"action",entityId:actionId,templateVariables:Object.freeze({title}),channel:"in-app",status:"pending",idempotencyKey:`action:${actionId}:assignment:${recipientType}:${recipientId}`,attemptCount:0,createdAt:new Date(createdAt)});}
  private now():Date{return new Date(this.dependencies.now?.()??new Date());}
  private async guard<T>(operation:()=>Promise<T>):Promise<ExecuteCommandResult<T>>{try{return{ok:true,value:await operation()};}catch(error){if(isFailure(error))return{ok:false,...error};if(error instanceof ExecutePersistenceConflict)return{ok:false,code:"PLAN_VERSION_CONFLICT",message:"This plan changed in another session. Reload the latest version.",retryable:true,...(error.currentVersion===undefined?{}:{currentVersion:error.currentVersion})};return{ok:false,code:"PERSISTENCE_FAILURE",message:"Execute could not save the change. Your prior records were not changed.",retryable:true};}}
}

type Failure=Readonly<{__executeFailure:true;code:ExecuteFailureCode;message:string;retryable:boolean;currentVersion?:number;submittedInput?:unknown}>;
function failure(code:ExecuteFailureCode,message:string,retryable:boolean,currentVersion?:number,submittedInput?:unknown):Failure{return{__executeFailure:true,code,message,retryable,...(currentVersion===undefined?{}:{currentVersion}),...(submittedInput===undefined?{}:{submittedInput})};}
function isFailure(value:unknown):value is Failure{return Boolean(value&&typeof value==="object"&&"__executeFailure" in value);}
