import { describe, expect, it } from "vitest";
import { ActionPlan, PlatformActionCollection, type ActionActor, type PlatformAction } from "../domain";
import type { PlatformActionQuery } from "./action-queries";
import type { PlatformActionRepository } from "./action-repository";
import { ExecutePlanApplicationService, type ActionPlanRepository, type ExecuteActivityEvent, type ExecuteActivityRepository, type ExecuteAuthorization, type ExecuteNotificationIntent, type ExecuteNotificationOutbox, type ExecuteTransactionContext, type ExecuteUnitOfWork } from "./execute-application";

const actor = { type: "user", id: "owner-1" } as const;
const now = new Date("2026-08-09T12:00:00Z");

class MemoryPlanRepository implements ActionPlanRepository { values=new Map<string,ActionPlan>(); async findById(workspaceId:string,id:string){return this.values.get(`${workspaceId}:${id}`)??null;} async list(workspaceId:string){return [...this.values.entries()].filter(([key])=>key.startsWith(`${workspaceId}:`)).map(([,value])=>value);} async add(plan:ActionPlan){this.values.set(`${plan.props.workspaceId}:${plan.props.id}`,plan);} async replace(plan:ActionPlan,expected:number){const key=`${plan.props.workspaceId}:${plan.props.id}`,current=this.values.get(key);if(!current||current.props.version!==expected)throw new Error("stale");this.values.set(key,plan);} }
class MemoryActionRepository implements PlatformActionRepository { values:PlatformAction[]=[]; failOnAddNumber?:number; async findById(input:Parameters<PlatformActionRepository["findById"]>[0]){return this.values.find((value)=>value.workspaceId.equals(input.workspaceId)&&value.id.equals(input.actionId))??null;} async find(query:PlatformActionQuery){void query;return PlatformActionCollection.create(this.values);} async add({action}:{action:PlatformAction}){if(this.failOnAddNumber===this.values.length+1)throw new Error("insert failed");this.values.push(action);} async replace(){throw new Error("not used");} }
class MemoryActivity implements ExecuteActivityRepository { values:ExecuteActivityEvent[]=[];async append(events:readonly ExecuteActivityEvent[]){this.values.push(...events);}async list(workspaceId:string,type:ExecuteActivityEvent["entityType"],id:string){return this.values.filter((event)=>event.workspaceId===workspaceId&&event.entityType===type&&event.entityId===id);} }
class MemoryOutbox implements ExecuteNotificationOutbox { values:ExecuteNotificationIntent[]=[];async add(values:readonly ExecuteNotificationIntent[]){this.values.push(...values);} }
class MemoryUnitOfWork implements ExecuteUnitOfWork { constructor(readonly context:ExecuteTransactionContext){} async execute<T>(operation:(context:ExecuteTransactionContext)=>Promise<T>):Promise<T>{const plans=new Map((this.context.plans as MemoryPlanRepository).values),actions=[...(this.context.actions as MemoryActionRepository).values],activity=[...(this.context.activity as MemoryActivity).values],notifications=[...(this.context.notifications as MemoryOutbox).values];try{return await operation(this.context);}catch(error){(this.context.plans as MemoryPlanRepository).values=plans;(this.context.actions as MemoryActionRepository).values=actions;(this.context.activity as MemoryActivity).values=activity;(this.context.notifications as MemoryOutbox).values=notifications;throw error;}} }
function harness(authorization:Partial<ExecuteAuthorization>={},failOnAction?:number){const plans=new MemoryPlanRepository(),actions=new MemoryActionRepository(),activity=new MemoryActivity(),notifications=new MemoryOutbox();actions.failOnAddNumber=failOnAction;const access:ExecuteAuthorization={canManagePlans:async()=>true,canAccessProperty:async()=>true,canAssign:async()=>true,...authorization};let id=0;const service=new ExecutePlanApplicationService({unitOfWork:new MemoryUnitOfWork({plans,actions,activity,notifications}),authorization:access,createId:()=>`generated-${++id}`,now:()=>now});return{service,plans,actions,activity,notifications};}
const proposed=(id:string,owner:ActionActor|undefined=actor)=>({id,position:id.charCodeAt(0)-97,title:`Action ${id}`,...(owner?{owner}:{}),dueAt:new Date("2026-08-12T12:00:00Z"),propertyId:"property-1"});
async function draft(h:ReturnType<typeof harness>,actions=[proposed("a")]){const result=await h.service.createFromDecision({id:"plan-1",workspaceId:"workspace-1",decision:{id:"decision-1",title:"Improve property",propertyIds:["property-1"],priority:"high",approvedBy:actor,approvedAt:now},owner:actor,proposedActions:actions,actor});expect(result.ok).toBe(true);return result;}

describe("EX-001B1 Execute plan application",()=>{
  it("creates and reads a decision-derived draft with lineage",async()=>{const h=harness();await draft(h);const read=await h.service.getPlan("workspace-1","plan-1",actor);expect(read).toMatchObject({ok:true,value:{linkedDecisionId:"decision-1",status:"draft",version:1}});expect(h.activity.values[0].eventType).toBe("decision-converted-to-plan");});
  it("updates a draft with optimistic concurrency",async()=>{const h=harness();await draft(h);const updated=await h.service.updateDraft({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,changes:{expectedVersion:1,title:"Updated plan"}});expect(updated).toMatchObject({ok:true,value:{title:"Updated plan",version:2}});const stale=await h.service.updateDraft({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,changes:{expectedVersion:1,title:"Stale"}});expect(stale).toMatchObject({ok:false,code:"PLAN_VERSION_CONFLICT",retryable:true});});
  it("activates atomically, creates canonical ready actions, lineage, activity, and durable notification intents",async()=>{const h=harness();await draft(h,[proposed("a"),proposed("b")]);const result=await h.service.activate({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,occurredAt:now,correlationId:"activation-1"});expect(result).toMatchObject({ok:true,value:{status:"active",version:2}});expect(h.actions.values).toHaveLength(2);expect(h.actions.values.every((action)=>action.status==="ready")).toBe(true);expect(h.actions.values[0].sources[0]).toMatchObject({type:"decision",sourceId:"decision-1"});expect(h.activity.values.map((event)=>event.eventType)).toEqual(expect.arrayContaining(["plan-activated","action-activated"]));expect(h.notifications.values).toHaveLength(2);expect(h.notifications.values[0]).toMatchObject({status:"pending",channel:"in-app",eventType:"new-assignment",attemptCount:0});});
  it("rolls back the plan, actions, activity, and outbox when activation partially fails",async()=>{const h=harness({},2);await draft(h,[proposed("a"),proposed("b")]);const beforeActivity=h.activity.values.length;const result=await h.service.activate({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,occurredAt:now,correlationId:"activation-fail"});expect(result).toMatchObject({ok:false,code:"PERSISTENCE_FAILURE"});expect((await h.plans.findById("workspace-1","plan-1"))?.props.status).toBe("draft");expect(h.actions.values).toEqual([]);expect(h.activity.values).toHaveLength(beforeActivity);expect(h.notifications.values).toEqual([]);});
  it("denies property and assignee authorization without leaking persistence errors",async()=>{const deniedProperty=harness({canAccessProperty:async()=>false});const property=await deniedProperty.service.createFromDecision({id:"plan-1",workspaceId:"workspace-1",decision:{id:"decision-1",title:"Denied",propertyIds:["other"],priority:"normal",approvedBy:actor,approvedAt:now},owner:actor,actor});expect(property).toMatchObject({ok:false,code:"PROPERTY_ACCESS_DENIED"});const deniedOwner=harness({canAssign:async()=>false});await draft(deniedOwner);const activation=await deniedOwner.service.activate({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,occurredAt:now,correlationId:"denied"});expect(activation).toMatchObject({ok:false,code:"ACTION_ASSIGNMENT_UNAUTHORIZED"});});
  it("adds, updates, removes, and reorders Draft Actions with one version increment and one activity event",async()=>{const h=harness();await draft(h,[proposed("a"),proposed("b")]);const added=await h.service.addDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,input:{title:"Action C",owner:actor,dueAt:new Date("2026-08-13T12:00:00Z"),propertyId:"property-1"}});expect(added.ok&&added.value.actions).toHaveLength(3);const id=added.ok?added.value.actions[2].id:"";const updated=await h.service.updateDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:2,actor,actionId:id,changes:{title:"Updated C",category:"maintenance"}});expect(updated).toMatchObject({ok:true,value:{version:3}});const reordered=await h.service.reorderDraftActions({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:3,actor,orderedActionIds:[id,"b","a"]});expect(reordered.ok&&reordered.value.actions.map((item)=>[item.id,item.position])).toEqual([[id,0],["b",1],["a",2]]);const removed=await h.service.removeDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:4,actor,actionId:"b"});expect(removed.ok&&removed.value.actions.map((item)=>item.id)).toEqual([id,"a"]);expect(h.activity.values.slice(-4).map((event)=>event.eventType)).toEqual(["draft-action-added","draft-action-updated","draft-actions-reordered","draft-action-removed"]);});
  it("returns current version and submitted input when two actors edit the same plan version",async()=>{const h=harness();await draft(h);const first=await h.service.updateDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,actionId:"a",changes:{title:"First edit"}});expect(first.ok).toBe(true);const second=await h.service.updateDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor:{type:"user",id:"owner-2"},actionId:"a",changes:{title:"Second edit"}});expect(second).toMatchObject({ok:false,code:"PLAN_VERSION_CONFLICT",currentVersion:2,submittedInput:{title:"Second edit"}});expect(h.activity.values.filter((event)=>event.eventType==="draft-action-updated")).toHaveLength(1);});
  it("rejects invalid reorder sets and mutations after activation without partial events",async()=>{const h=harness();await draft(h,[proposed("a"),proposed("b")]);const invalid=await h.service.reorderDraftActions({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,orderedActionIds:["a","a"]});expect(invalid).toMatchObject({ok:false,code:"PLAN_ACTIVATION_INVALID"});await h.service.activate({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:1,actor,occurredAt:now,correlationId:"active"});const after=await h.service.removeDraftAction({workspaceId:"workspace-1",planId:"plan-1",expectedVersion:2,actor,actionId:"a"});expect(after).toMatchObject({ok:false,code:"PLAN_ACTIVATION_INVALID"});});
});
