import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";
import { getSessionProfile } from "@/lib/auth/session";
import { sanitizeAuditMetadata, type AdminAuditEvent } from "../domain/operations";
import { assertTicketTransition, type TicketPriority, type TicketStatus } from "../domain/support-ticket";
async function context(){const{user,profile}=await getSessionProfile();if(!user||profile?.role!=="admin")throw new Error("Administrative authorization required.");return{user,profile,db:createAdminClient(),correlationId:crypto.randomUUID()};}
async function audit(db:ReturnType<typeof createAdminClient>,input:Omit<AdminAuditEvent,"id"|"occurredAt"|"metadata">&{metadata?:Readonly<Record<string,unknown>>}){const{error}=await db.from("admin_audit_events").insert({actor_id:input.actorId??null,actor_role:input.actorRole??null,action:input.action,category:input.category,target_type:input.targetType??null,target_id:input.targetId??null,result:input.result,correlation_id:input.correlationId??null,source:input.source,metadata:sanitizeAuditMetadata(input.metadata??{})});if(error){console.error(JSON.stringify({event:"admin_audit_write_failed",action:input.action,correlationId:input.correlationId}));throw new Error("The operation completed but its required audit event could not be recorded.");}}
export async function createSupportTicket(input:Readonly<{subject:string;priority?:TicketPriority;workspaceId?:string;customerId?:string}>){const c=await context(),subject=input.subject.trim();if(!subject||subject.length>300)throw new Error("Ticket subject must contain 1–300 characters.");const{data,error}=await c.db.from("support_tickets").insert({subject,priority:input.priority??"medium",workspace_id:input.workspaceId??null,customer_id:input.customerId??null,assigned_admin_id:c.user.id}).select("id,ticket_number").single();if(error)throw new Error("Unable to create support ticket.");await c.db.from("support_ticket_activity").insert({ticket_id:data.id,actor_id:c.user.id,action:"support.ticket.created",to_value:"open",correlation_id:c.correlationId});await audit(c.db,{actorId:c.user.id,actorRole:c.profile.role,action:"support.ticket.created",category:"support",targetType:"support_ticket",targetId:data.id,result:"succeeded",correlationId:c.correlationId,source:"server_action",metadata:{priority:input.priority??"medium"}});return data;}
export async function convertInquiryToSupportTicket(inquiryId:string){const c=await context();const existing=await c.db.from("support_tickets").select("id,ticket_number").eq("source_inquiry_id",inquiryId).maybeSingle();if(existing.error)throw new Error("Unable to inspect inquiry lineage.");if(existing.data)return existing.data;const{data:inquiry,error:inquiryError}=await c.db.from("contact_inquiries").select("id,name,inquiry_type").eq("id",inquiryId).maybeSingle();if(inquiryError||!inquiry)throw new Error("Inquiry not found.");const subject=(`${inquiry.inquiry_type||"Support"} inquiry from ${inquiry.name||"customer"}`).slice(0,300);const{data,error}=await c.db.from("support_tickets").insert({source_inquiry_id:inquiry.id,subject,priority:"medium",assigned_admin_id:c.user.id}).select("id,ticket_number").single();if(error?.code==="23505"){const retry=await c.db.from("support_tickets").select("id,ticket_number").eq("source_inquiry_id",inquiryId).single();if(retry.error)throw new Error("Unable to resolve converted inquiry.");return retry.data;}if(error)throw new Error("Unable to convert inquiry.");await c.db.from("support_ticket_activity").insert({ticket_id:data.id,actor_id:c.user.id,action:"support.inquiry.converted",to_value:"open",correlation_id:c.correlationId});await audit(c.db,{actorId:c.user.id,actorRole:c.profile.role,action:"support.inquiry.converted",category:"support",targetType:"support_ticket",targetId:data.id,result:"succeeded",correlationId:c.correlationId,source:"server_action",metadata:{sourceInquiryId:inquiry.id}});return data;}
export async function changeSupportTicketStatus(ticketId:string,to:TicketStatus){const c=await context();const{data:ticket,error}=await c.db.from("support_tickets").select("status").eq("id",ticketId).single();if(error)throw new Error("Ticket not found.");const from=ticket.status as TicketStatus;assertTicketTransition(from,to);const now=new Date().toISOString(),updates:Record<string,unknown>={status:to,updated_at:now};if(to==="resolved")updates.resolved_at=now;if(to==="closed")updates.closed_at=now;if(to==="open"){updates.resolved_at=null;updates.closed_at=null;}const{error:updateError}=await c.db.from("support_tickets").update(updates).eq("id",ticketId);if(updateError)throw new Error("Unable to update ticket status.");await c.db.from("support_ticket_activity").insert({ticket_id:ticketId,actor_id:c.user.id,action:to==="resolved"?"support.ticket.resolved":to==="open"&&["resolved","closed"].includes(from)?"support.ticket.reopened":to==="closed"?"support.ticket.closed":"support.ticket.status_changed",from_value:from,to_value:to,correlation_id:c.correlationId});await audit(c.db,{actorId:c.user.id,actorRole:c.profile.role,action:"support.ticket.status_changed",category:"support",targetType:"support_ticket",targetId:ticketId,result:"succeeded",correlationId:c.correlationId,source:"server_action",metadata:{fromStatus:from,toStatus:to}});}
async function updateField(ticketId:string,field:"assigned_admin_id"|"priority",value:string|null,action:string){const c=await context();const{error}=await c.db.from("support_tickets").update({[field]:value,updated_at:new Date().toISOString()}).eq("id",ticketId);if(error)throw new Error("Unable to update support ticket.");await c.db.from("support_ticket_activity").insert({ticket_id:ticketId,actor_id:c.user.id,action,to_value:value,correlation_id:c.correlationId});await audit(c.db,{actorId:c.user.id,actorRole:c.profile.role,action,category:"support",targetType:"support_ticket",targetId:ticketId,result:"succeeded",correlationId:c.correlationId,source:"server_action",metadata:{field}});}
export async function assignSupportTicket(ticketId:string,assignedAdminId?:string){return updateField(ticketId,"assigned_admin_id",assignedAdminId??null,"support.ticket.assigned");}
export async function changeSupportTicketPriority(ticketId:string,priority:TicketPriority){return updateField(ticketId,"priority",priority,"support.ticket.priority_changed");}
export async function addSupportInternalNote(ticketId:string,body:string){const c=await context(),clean=body.trim();if(!clean||clean.length>10_000)throw new Error("Internal note must contain 1–10,000 characters.");const{error}=await c.db.from("support_ticket_messages").insert({ticket_id:ticketId,author_id:c.user.id,visibility:"internal",body:clean,delivery_status:"not_requested"});if(error)throw new Error("Unable to add internal note.");await audit(c.db,{actorId:c.user.id,actorRole:c.profile.role,action:"support.ticket.internal_note_added",category:"support",targetType:"support_ticket",targetId:ticketId,result:"succeeded",correlationId:c.correlationId,source:"server_action"});}
