import type { MarketComparableSearchCriteriaInput } from "./comparable-acquisition";
import type { MarketComparableQualificationPolicy, MarketComparableQualificationResult } from "./comparable-qualification";
import type { MarketProperty, MarketPropertyResolutionResult } from "./property-resolution";

export type MarketEstimateStatus = "estimated" | "limited" | "insufficient" | "unsupported";
export type MarketAnalysisReportStatus = "complete" | "partial" | "insufficient" | "unsupported";
export type MarketConfidenceLevel = "high" | "medium" | "low" | "none";
export interface MarketAnalysisConfidence { readonly score: number; readonly level: MarketConfidenceLevel; readonly reasons: readonly string[]; readonly dimensions: Readonly<{ coverage: number; similarity: number; dispersion: number }> }
export interface MarketEstimateCalculation { readonly method: "weighted-comparable-mean"; readonly candidateIds: readonly string[]; readonly normalizedWeights: readonly Readonly<{ candidateId: string; weight: number }>[]; readonly values: readonly Readonly<{ candidateId: string; value: number }>[]; readonly lowPercentile: number; readonly highPercentile: number }
export interface MarketRisk { readonly code: "INSUFFICIENT_COMPARABLE_COVERAGE" | "LOW_COMPARABLE_SIMILARITY" | "STALE_MARKET_EVIDENCE" | "HIGH_ESTIMATE_DISPERSION" | "CONCENTRATED_COMPARABLE_WEIGHT" | "SUBJECT_CHARACTERISTICS_INCOMPLETE" | "RENTAL_EVIDENCE_LIMITED" | "SALE_EVIDENCE_LIMITED"; readonly severity: "low" | "medium" | "high"; readonly title: string; readonly description: string; readonly evidenceIds: readonly string[]; readonly dataGapIds: readonly string[] }
export interface MarketAnalysisDataGap { readonly id: string; readonly code: string; readonly description: string; readonly severity: "informational" | "material" | "blocking"; readonly sourceStage: "property-resolution" | "comparable-acquisition" | "comparable-qualification" | "valuation" | "rent-analysis"; readonly section: "subject" | "sale-valuation" | "long-term-rent" }
export interface MarketAnalysisObservation { readonly id: string; readonly type: string; readonly label: string; readonly value: string | number; readonly sourceIds: readonly string[] }
export interface MarketAnalysisEvidence { readonly id: string; readonly type: string; readonly description: string; readonly candidateIds: readonly string[] }
export interface MarketSaleValuationAnalysis { readonly status: MarketEstimateStatus; readonly estimatedValue?: number; readonly valueRange?: Readonly<{ lower: number; upper: number }>; readonly estimatedPricePerSquareFoot?: number; readonly qualification: MarketComparableQualificationResult; readonly calculation?: MarketEstimateCalculation; readonly confidence: MarketAnalysisConfidence; readonly risks: readonly MarketRisk[]; readonly dataGaps: readonly MarketAnalysisDataGap[] }
export interface MarketLongTermRentAnalysis { readonly status: MarketEstimateStatus; readonly estimatedMonthlyRent?: number; readonly rentRange?: Readonly<{ lower: number; upper: number }>; readonly estimatedRentPerSquareFoot?: number; readonly qualification: MarketComparableQualificationResult; readonly calculation?: MarketEstimateCalculation; readonly confidence: MarketAnalysisConfidence; readonly risks: readonly MarketRisk[]; readonly dataGaps: readonly MarketAnalysisDataGap[] }
export interface MarketAnalysisSummary { readonly estimatedValue?: number; readonly estimatedMonthlyRent?: number; readonly confidenceScore: number; readonly confidenceLevel: MarketConfidenceLevel; readonly saleComparableCount: number; readonly rentalComparableCount: number; readonly riskCount: number; readonly dataGapCount: number; readonly headline: string; readonly explanation: string }
export interface MarketAnalysisLineage { readonly propertyResolutionId: string; readonly sale?: Readonly<{ acquisitionId: string; qualificationId: string; includedCandidateIds: readonly string[] }>; readonly longTermRent?: Readonly<{ acquisitionId: string; qualificationId: string; includedCandidateIds: readonly string[] }>; readonly observationIds: readonly string[]; readonly evidenceIds: readonly string[]; readonly policyVersion: string }

export interface CanonicalMarketAnalysisReport { readonly analysisId: string; readonly subject: MarketProperty; readonly status: MarketAnalysisReportStatus; readonly saleValuation?: MarketSaleValuationAnalysis; readonly longTermRent?: MarketLongTermRentAnalysis; readonly confidence: MarketAnalysisConfidence; readonly risks: readonly MarketRisk[]; readonly dataGaps: readonly MarketAnalysisDataGap[]; readonly observations: readonly MarketAnalysisObservation[]; readonly evidence: readonly MarketAnalysisEvidence[]; readonly summary: MarketAnalysisSummary; readonly lineage: MarketAnalysisLineage; readonly analyzedAt: Date }
export interface MarketAnalysisRequest { readonly saleValuation?: Readonly<{ enabled: boolean; acquisitionCriteria?: MarketComparableSearchCriteriaInput }>; readonly longTermRent?: Readonly<{ enabled: boolean; acquisitionCriteria?: MarketComparableSearchCriteriaInput }> }
export interface MarketEstimationPolicy { readonly minimumEstimateComparables: number; readonly lowPercentile: number; readonly highPercentile: number }
export interface MarketAnalysisPolicies { readonly saleQualification: MarketComparableQualificationPolicy; readonly longTermRentQualification: MarketComparableQualificationPolicy; readonly saleEstimation: MarketEstimationPolicy; readonly longTermRentEstimation: MarketEstimationPolicy; readonly version: string }
export interface MarketAnalysisContext { readonly analysisId: string; readonly analyzedAt: Date; readonly requestedBy?: string; readonly marketId?: string }
export interface RunMarketAnalysisCommand { readonly propertyResolution: MarketPropertyResolutionResult; readonly analyses: MarketAnalysisRequest; readonly policies: MarketAnalysisPolicies; readonly context: MarketAnalysisContext }
