import Link from "next/link";
import { getCheckoutResult } from "@/app/actions/commerce-payments";
export default async function CheckoutSuccessPage({searchParams}:{searchParams:Promise<{session_id?:string}>}){
 const{session_id}=await searchParams,result=session_id?await getCheckoutResult(session_id):null;
 const paid=result?.orderStatus==="paid",failed=result?.orderStatus==="payment-failed",expired=result?.orderStatus==="expired",refunded=result?.orderStatus==="refunded"||result?.orderStatus==="partially-refunded";
 const title=paid?"Payment confirmed":failed?"Payment was not completed":expired?"Checkout expired":refunded?"Refund recorded":"Payment confirmation is processing";
 const detail=paid?"Your order is now ready for fulfillment. No product access is activated by this confirmation page.":failed?"Review your payment details or begin a new secure checkout.":expired?"Start a new secure checkout to continue.":refunded?"Your canonical order reflects the provider-confirmed refund.":"You do not need to submit another payment. This page will reflect the verified order state after webhook processing.";
 return <main className="mx-auto max-w-2xl px-5 py-20 text-center" aria-live="polite"><p className="eyebrow">Order status</p><h1 className="mt-3 font-serif text-5xl">{title}</h1><p className="mt-5 text-stone-600">{detail}</p>{result?<dl className="mt-8 rounded-xl bg-stone-50 p-5 text-left"><div><dt className="text-xs uppercase tracking-wider text-stone-500">Order</dt><dd className="mt-1 font-semibold">{result.orderNumber}</dd></div><div className="mt-4"><dt className="text-xs uppercase tracking-wider text-stone-500">Product</dt><dd className="mt-1">{result.productName}</dd></div></dl>:<p className="mt-8 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">Sign in with the purchasing account to view this order. Provider references alone never grant access.</p>}{failed||expired?<Link href="/pricing" className="mt-8 inline-flex rounded-full bg-stone-950 px-6 py-3 font-semibold text-white">Start a new checkout</Link>:null}</main>
}
