import type { InvestmentOpportunityRoute, OpportunitySource, OpportunityStatus } from "../../domain";

export type OpportunityComparisonIncompatibilityReason = "PURCHASE_RENTAL_ROUTE_MISMATCH" | "MISSING_CURRENT_ANALYSIS" | "UNSUPPORTED_SNAPSHOT_VERSION" | "OPPORTUNITY_NOT_ACCESSIBLE" | "ARCHIVED_OPPORTUNITY" | "TOO_FEW_OPPORTUNITIES" | "TOO_MANY_OPPORTUNITIES";
export class OpportunityComparisonError extends Error { constructor(public readonly reasons: readonly OpportunityComparisonIncompatibilityReason[]) { super(reasons.join(", ")); this.name = "OpportunityComparisonError"; } }
export type ComparisonMetric = Readonly<{ value?: number; source?: OpportunitySource; format: "money" | "percentage" | "number"; highlight?: "best" | "lowest" }>;
export type ComparisonAssumption = Readonly<{ key: string; label: string; value?: number; source?: OpportunitySource; overridden: boolean; analyzedAt: Date }>;
export type OpportunityComparisonCandidate = Readonly<{ id: string; name: string; address: string; route: InvestmentOpportunityRoute; status: OpportunityStatus; canShortlist: boolean; aggregateVersion: number; analysisId: string; analysisSequence: number; recommendation: string; score: number; confidence: string; analyzedAt: Date; stale: boolean; metrics: Readonly<Record<string, ComparisonMetric>>; assumptions: readonly ComparisonAssumption[]; risks: readonly Readonly<{ title: string; severity: string }>[]; dataGaps: readonly Readonly<{ code: string; description: string }>[]; evidenceCount: number }>;
export type OpportunityComparisonRank = Readonly<{ opportunityId: string; rank: number; compositeScore: number; summary: string; strengths: readonly string[]; tradeoffs: readonly string[] }>;
export type OpportunityComparisonView = Readonly<{ route: InvestmentOpportunityRoute; candidates: readonly OpportunityComparisonCandidate[]; ranks: readonly OpportunityComparisonRank[]; highlights: readonly string[]; assumptionDifferences: readonly Readonly<{ key: string; label: string; values: readonly Readonly<{ opportunityId: string; value?: number; source?: OpportunitySource; analyzedAt: Date }>[]; sourceDifference: boolean }>[]; rankingPolicy: typeof OPPORTUNITY_COMPARISON_RANKING_POLICY }>;
export const OPPORTUNITY_COMPARISON_RANKING_POLICY = Object.freeze({ version: "1", weights: Object.freeze({ investmentScore: 0.35, confidence: 0.15, cashOnCashReturn: 0.2, annualCashFlow: 0.1, capitalEfficiency: 0.1, riskBurden: 0.05, dataCompleteness: 0.05 }) });
