import Link from "next/link";
import type { LearningDashboardMaturityDistribution, LearningIntelligenceDashboard, LearningIntelligenceDashboardState } from "../application";

const outcomeLabels = Object.freeze({ successful: "Successful", "partially-successful": "Partially successful", unsuccessful: "Unsuccessful", harmful: "Harmful", inconclusive: "Inconclusive" });

export function LearningIntelligenceDashboardView({ state }: { state: LearningIntelligenceDashboardState }) {
  if (state.status === "no-outcomes" || state.status === "measurement-in-progress") return <EarlyDashboard state={state} />;
  const dashboard = state.dashboard;
  return <div className="mx-auto w-full max-w-[1500px] space-y-8 px-4 py-6 sm:px-6 lg:px-8">
    <header className="rounded-3xl bg-[#102925] px-6 py-7 text-white shadow-sm sm:px-8">
      <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
        <div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-teal-200">Learn · Executive orientation</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Learning Intelligence</h1><p className="mt-2 text-stone-300">{dashboard.portfolio.name} · {dateRange(dashboard.observationWindow.start, dashboard.observationWindow.end)}</p></div>
        <div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-white/20 px-3 py-1.5 text-sm">{title(dashboard.freshness.status)}</span><Link href={dashboard.workspaceDestination} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-stone-950 outline-none hover:bg-teal-50 focus-visible:ring-2 focus-visible:ring-teal-300">Open Continuous Improvement</Link></div>
      </div>
    </header>
    {state.status === "degraded" ? <Notice title="Some Learning Intelligence is unavailable">Available executive conclusions are shown. Missing sections are not represented as zero.</Notice> : null}
    {state.status === "insufficient-evidence" ? <Notice title="Learning is still developing">Individual decisions may be assessed, but the portfolio does not yet have enough evidence for a mature learning picture.</Notice> : null}
    {dashboard.freshness.status === "stale" ? <Notice title="Learning Intelligence needs reevaluation">{dashboard.freshness.reasons.join(" ")}</Notice> : null}
    <section aria-labelledby="executive-heading" className="space-y-4"><Heading id="executive-heading" kicker="First minute" title="Executive summary" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <HeroMetric label="Learning health" value={title(dashboard.executiveSummary.learningHealth)} detail={confidence(dashboard.executiveSummary.confidence)} />
      <HeroMetric label="Decision quality" value={dashboard.executiveSummary.decisionQuality} detail={title(dashboard.decisionQuality.trend)} />
      <HeroMetric label="Recommendation reliability" value={dashboard.executiveSummary.recommendationReliability} detail={title(dashboard.recommendationReliability.trend)} />
      <HeroMetric label="Strongest learning" value={dashboard.executiveSummary.strongestLearning?.statement ?? "Not established"} detail={dashboard.executiveSummary.strongestLearning ? title(dashboard.executiveSummary.strongestLearning.maturity) : "Insufficient evidence"} />
      <HeroMetric label="Measurement readiness" value={readiness(dashboard)} detail={`${dashboard.measurement.inconclusiveOutcomes} inconclusive Outcomes`} />
    </div></section>
    <div className="grid gap-6 xl:grid-cols-2"><DecisionQuality dashboard={dashboard} /><RecommendationReliability dashboard={dashboard} /></div>
    <section aria-labelledby="strongest-heading" className="space-y-4"><Heading id="strongest-heading" kicker="What we have learned" title="Strongest Learnings" /><div className="grid gap-4 lg:grid-cols-3">{dashboard.learningSummary.strongest.map((item) => <LearningBrief key={item.id} item={item} />)}{!dashboard.learningSummary.strongest.length ? <Empty>No validated or supported learning is available.</Empty> : null}</div></section>
    <div className="grid gap-6 xl:grid-cols-2">
      <LearningList title="Largest Recurring Misses" items={dashboard.learningSummary.recurringMisses} empty="No evidence-backed recurring miss is established." />
      <LearningList title="Emerging and Contested" items={dashboard.learningSummary.emerging} empty="No emerging or contested pattern is present." />
    </div>
    <section aria-labelledby="maturity-heading" className="space-y-4"><Heading id="maturity-heading" kicker="Organizational learning" title="Learning maturity" /><Maturity distribution={dashboard.learningSummary.maturity} /></section>
    <section id="assumptions" aria-labelledby="assumptions-heading" className="space-y-4"><Heading id="assumptions-heading" kicker="Recurring forecast quality" title="Assumption Accuracy" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{dashboard.assumptions.map((item) => <article key={item.id} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{title(item.bias)} bias</p><h3 className="mt-2 font-semibold text-stone-950">{item.label}</h3><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Stat label="Typical effect" value={item.effect ?? "Unavailable"} /><Stat label="Confidence" value={confidence(item.confidence)} /><Stat label="Materiality" value={title(item.materiality)} /><Stat label="Trend" value={title(item.trend)} /></dl></article>)}{!dashboard.assumptions.length ? <Empty>No recurring assumption bias is established.</Empty> : null}</div></section>
    <div className="grid gap-6 xl:grid-cols-2"><Measurement dashboard={dashboard} /><Changes dashboard={dashboard} /></div>
    <Attention dashboard={dashboard} />
    <footer className="rounded-2xl border border-stone-200 bg-stone-50 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-stone-950">Freshness and lineage</h2><p className="mt-1 text-sm text-stone-600">{title(dashboard.freshness.status)} · Evaluated {dateTime(dashboard.evaluatedAt)} · Portfolio version {dashboard.lineage.portfolioVersion}</p></div><Link href={dashboard.workspaceDestination} className="text-sm font-semibold text-teal-800 underline underline-offset-4">Review evidence and limitations</Link></div>{dashboard.limitations.length ? <p className="mt-4 text-sm text-amber-800">{dashboard.limitations.length} visible limitation{dashboard.limitations.length === 1 ? "" : "s"} affect this dashboard.</p> : null}</footer>
  </div>;
}

function DecisionQuality({ dashboard }: { dashboard: LearningIntelligenceDashboard }) {
  return <section aria-labelledby="decision-heading" className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><Heading id="decision-heading" kicker="LI-002 summary" title="Decision Quality" /><div role="group" aria-label="Decision Outcome distribution" className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5 xl:grid-cols-3">{Object.entries(dashboard.decisionQuality.distribution).map(([key, item]) => <div key={key} className="rounded-xl bg-stone-50 p-3"><p className="text-xs text-stone-500">{outcomeLabels[key as keyof typeof outcomeLabels]}</p><p className="mt-1 text-xl font-semibold">{item.count}</p><p className="text-xs text-stone-500">{item.percentage === null ? "Unavailable" : `${Math.round(item.percentage)}%`}</p></div>)}</div><p className="mt-4 text-sm text-stone-600">Trend: {title(dashboard.decisionQuality.trend)} · Confidence: {confidence(dashboard.decisionQuality.confidence)}</p></section>;
}
function RecommendationReliability({ dashboard }: { dashboard: LearningIntelligenceDashboard }) {
  const value = dashboard.recommendationReliability;
  return <section aria-labelledby="recommendation-heading" className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><Heading id="recommendation-heading" kicker="LI-003 summary" title="Recommendation Reliability" /><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><Stat label="Validated" value={String(value.validated)} /><Stat label="Conditional" value={String(value.conditional)} /><Stat label="Experimental" value={String(value.experimental)} /><Stat label="Deprecated" value={String(value.deprecated)} /><Stat label="Insufficient evidence" value={String(value.insufficientEvidence)} /><Stat label="Overall trend" value={title(value.trend)} /></dl><p className="mt-4 text-sm text-stone-600">Confidence: {confidence(value.confidence)}. Deprecated remains a governance status, not an automatic disablement.</p></section>;
}
function LearningBrief({ item }: { item: LearningIntelligenceDashboard["learningSummary"]["strongest"][number] }) { return <article className="rounded-2xl border border-teal-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-teal-800">{title(item.maturity)} · {title(item.category)}</p><h3 className="mt-2 font-semibold leading-6 text-stone-950">{item.statement}</h3><p className="mt-2 text-xs text-stone-500">Supported within this portfolio · {title(item.applicability)}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Stat label="Confidence" value={confidence(item.confidence)} /><Stat label="Materiality" value={title(item.materiality)} /><Stat label="Evidence" value={`${item.supportingCount} supporting`} /><Stat label="Contradiction" value={`${item.contradictingCount} · ${title(item.contradiction)}`} /></dl></article>; }
function LearningList({ title: heading, items, empty }: { title: string; items: LearningIntelligenceDashboard["learningSummary"]["strongest"]; empty: string }) { const id = heading.toLowerCase().replaceAll(" ", "-"); return <section aria-labelledby={id} className="space-y-4"><Heading id={id} kicker="Executive attention" title={heading} /><div className="space-y-3">{items.map((item) => <div key={item.id} className="rounded-2xl border border-stone-200 bg-white p-4"><p className="font-semibold text-stone-950">{item.statement}</p><p className="mt-1 text-sm text-stone-600">{title(item.materiality)} materiality · {confidence(item.confidence)} · {item.supportingCount} supporting / {item.contradictingCount} contradicting</p></div>)}{!items.length ? <Empty>{empty}</Empty> : null}</div></section>; }
function Maturity({ distribution }: { distribution: LearningDashboardMaturityDistribution }) { return <div role="group" aria-label="Portfolio Learning maturity distribution" className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(distribution).map(([key, value]) => <div key={key} className="rounded-xl border border-stone-200 bg-white p-4"><p className="text-sm text-stone-600">{title(key)}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div>; }
function Measurement({ dashboard }: { dashboard: LearningIntelligenceDashboard }) { return <section aria-labelledby="measurement-heading" className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><Heading id="measurement-heading" kicker="Can we trust the evidence?" title="Measurement Readiness" /><p className="mt-4 text-2xl font-semibold">{readiness(dashboard)}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Stat label="Completed Outcomes" value={String(dashboard.measurement.completedOutcomes)} /><Stat label="Incomplete Outcomes" value={String(dashboard.measurement.incompleteOutcomes)} /><Stat label="Inconclusive Outcomes" value={String(dashboard.measurement.inconclusiveOutcomes)} /><Stat label="Missing-baseline patterns" value={String(dashboard.measurement.missingBaselinePatterns)} /></dl></section>; }
function Changes({ dashboard }: { dashboard: LearningIntelligenceDashboard }) { return <section aria-labelledby="changes-heading" className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><Heading id="changes-heading" kicker="Compatible comparisons only" title="What Changed" />{dashboard.changes.length ? <ul className="mt-4 space-y-3">{dashboard.changes.map((item) => <li key={item.id} className="border-l-2 border-teal-500 pl-3 text-sm"><span className="font-semibold">{title(item.direction)}</span> · {item.label}</li>)}</ul> : <p className="mt-4 text-sm text-stone-600">No comparable prior Learning Intelligence assessment is available.</p>}</section>; }
function Attention({ dashboard }: { dashboard: LearningIntelligenceDashboard }) { return <section aria-labelledby="attention-heading" className="rounded-2xl border border-rose-200 bg-rose-50/50 p-5"><Heading id="attention-heading" kicker="Authoritative priority" title="Attention Required" />{dashboard.attention.length ? <ol className="mt-4 grid gap-3 md:grid-cols-2">{dashboard.attention.map((item) => <li key={`${item.type}:${item.sourceId}`} className="rounded-xl bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-rose-700">{item.rank}. {title(item.severity)}</p><p className="mt-2 font-medium text-stone-950">{item.label}</p></li>)}</ol> : <p className="mt-4 text-sm text-stone-600">No authoritative executive attention item is present.</p>}</section>; }
function EarlyDashboard({ state }: { state: Extract<LearningIntelligenceDashboardState, { status: "no-outcomes" | "measurement-in-progress" }> }) { const measuring = state.status === "measurement-in-progress"; return <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-teal-700">Learn · Learning Intelligence</p><h1 className="mt-3 text-3xl font-semibold">Learning Intelligence</h1><section role="status" className="mt-8 rounded-3xl border border-stone-200 bg-white p-8"><h2 className="text-2xl font-semibold">{measuring ? "Measurement is in progress." : "Learning begins with measured decisions."}</h2><p className="mt-3 text-stone-600">{measuring ? `${state.measuringCount} Outcomes are collecting evidence. Executive learning health will appear after completed assessments are available.` : "No decision-quality or learning-health conclusion is available yet."}</p><Link href={state.workspaceDestination} className="mt-6 inline-flex rounded-xl bg-stone-950 px-4 py-2 text-sm font-semibold text-white outline-none focus-visible:ring-2 focus-visible:ring-teal-600">Open Continuous Improvement</Link></section></div>; }
function Heading({ id, kicker, title: heading }: { id: string; kicker: string; title: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">{kicker}</p><h2 id={id} className="mt-1 text-xl font-semibold tracking-tight text-stone-950">{heading}</h2></div>; }
function HeroMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 font-semibold leading-6 text-stone-950">{value}</p><p className="mt-2 text-xs text-stone-500">{detail}</p></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-1 font-medium text-stone-950">{value}</dd></div>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="rounded-xl border border-dashed border-stone-300 bg-stone-50 p-5 text-sm text-stone-600">{children}</p>; }
function Notice({ title: heading, children }: { title: string; children: React.ReactNode }) { return <section aria-live="polite" className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><h2 className="font-semibold">{heading}</h2><p className="mt-1 text-sm">{children}</p></section>; }
function readiness(dashboard: LearningIntelligenceDashboard): string { const status = dashboard.measurement.readiness.status; return status === "limited" ? "Moderate" : title(status); }
function confidence(value: number | null): string { if (value === null) return "Unavailable"; return value >= 0.8 ? `High (${Math.round(value * 100)}%)` : value >= 0.55 ? `Moderate (${Math.round(value * 100)}%)` : `Low (${Math.round(value * 100)}%)`; }
function title(value: string): string { return value.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function dateRange(start: Date, end: Date): string { return `${date(start)} – ${date(end)}`; }
function date(value: Date): string { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(value); }
function dateTime(value: Date): string { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(value); }
