import { deepFreeze, validateOfferDefinition, type OfferDefinition } from "../domain/commercial-catalog";

// Commercial amounts and final inclusions are intentionally not activated until approved.
// These immutable drafts establish stable identities for the anticipated launch offers.
const draft = (input: Omit<OfferDefinition, "id" | "version" | "status" | "effectiveFrom" | "schemaVersion" | "priceDefinition" | "includedCapabilities" | "limits">): OfferDefinition => ({
  ...input, id: `${input.code}.v1`, version: 1, status: "draft", effectiveFrom: "2026-08-11T00:00:00.000Z", schemaVersion: 1,
  includedCapabilities: [], limits: [],
});

export const INITIAL_OFFER_CATALOG: readonly OfferDefinition[] = deepFreeze([
  draft({ code:"hpm.starter", productFamily:"hpm", name:"HPM Starter", shortDescription:"Hospitality performance management for an individual operator.", customerType:"individual_operator", acquisitionMode:"self_service", billingModel:"recurring", onboardingRequirements:["accept_terms","create_workspace","create_or_select_property","complete_property_profile"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:["guidebook.standalone"], upgradeOfferCodes:["hpm.portfolio","hpm.sales_assisted"] }),
  draft({ code:"hpm.portfolio", productFamily:"hpm", name:"HPM Portfolio", shortDescription:"Higher-capacity hospitality performance management.", customerType:"portfolio_operator", acquisitionMode:"self_service", billingModel:"recurring", onboardingRequirements:["accept_terms","create_workspace","create_or_select_property","complete_property_profile"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:["guidebook.standalone"], upgradeOfferCodes:["hpm.sales_assisted"] }),
  draft({ code:"hpm.sales_assisted", productFamily:"hpm", name:"HPM Sales Assisted", shortDescription:"A tailored HPM engagement for larger operators.", customerType:"portfolio_operator", acquisitionMode:"contact_sales", billingModel:"custom_quote", onboardingRequirements:["accept_terms","create_workspace","schedule_consultation"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:["guidebook.standalone"], upgradeOfferCodes:[] }),
  draft({ code:"guidebook.standalone", productFamily:"guidebook_studio", name:"Standalone Guidebook", shortDescription:"Create and publish a guidebook without HPM enrollment.", customerType:"individual_operator", acquisitionMode:"self_service", billingModel:"one_time", onboardingRequirements:["accept_terms","complete_guidebook_intake"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:["hpm.starter","hpm.portfolio","hpm.sales_assisted"], upgradeOfferCodes:["guidebook.multi"] }),
  draft({ code:"guidebook.multi", productFamily:"guidebook_studio", name:"Guidebook Multi", shortDescription:"Create and manage multiple guidebooks.", customerType:"portfolio_operator", acquisitionMode:"self_service", billingModel:"recurring", onboardingRequirements:["accept_terms","complete_guidebook_intake"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:["hpm.starter","hpm.portfolio","hpm.sales_assisted"], upgradeOfferCodes:[] }),
  draft({ code:"furnishing.consultation", productFamily:"furnishing", name:"Furnishing Consultation", shortDescription:"A scoped furnishing consultation.", customerType:"service_client", acquisitionMode:"proposal_required", billingModel:"custom_quote", onboardingRequirements:["accept_terms","schedule_consultation"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:["furnishing.essentials","furnishing.custom"] }),
  draft({ code:"furnishing.essentials", productFamily:"furnishing", name:"Essentials Furnishing Package", shortDescription:"A managed essentials furnishing engagement.", customerType:"service_client", acquisitionMode:"proposal_required", billingModel:"custom_quote", onboardingRequirements:["accept_terms","complete_furnishing_intake"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:["furnishing.custom"] }),
  draft({ code:"furnishing.custom", productFamily:"furnishing", name:"Custom Furnishing Engagement", shortDescription:"A custom managed furnishing engagement.", customerType:"service_client", acquisitionMode:"proposal_required", billingModel:"custom_quote", onboardingRequirements:["accept_terms","complete_furnishing_intake"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:[] }),
  draft({ code:"investment.single", productFamily:"investment_intelligence", name:"Single Property Analysis", shortDescription:"Analyze one investment property.", customerType:"investor", acquisitionMode:"self_service", billingModel:"one_time", onboardingRequirements:["accept_terms","complete_investment_profile"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:["investment.multi","investment.sales_assisted"] }),
  draft({ code:"investment.multi", productFamily:"investment_intelligence", name:"Investment Multi", shortDescription:"Recurring access for multiple analyses.", customerType:"investor", acquisitionMode:"self_service", billingModel:"recurring", onboardingRequirements:["accept_terms","complete_investment_profile"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:["investment.sales_assisted"] }),
  draft({ code:"investment.sales_assisted", productFamily:"investment_intelligence", name:"Investor Advisory", shortDescription:"A sales-assisted investment intelligence engagement.", customerType:"investor", acquisitionMode:"contact_sales", billingModel:"custom_quote", onboardingRequirements:["accept_terms","schedule_consultation"], standaloneEligible:true, prerequisiteOfferCodes:[], compatibleOfferCodes:[], upgradeOfferCodes:[] }),
].map(value => validateOfferDefinition(value)));

export function listAvailableOffers(input: Readonly<{ customerType: OfferDefinition["customerType"]; channel: "public" | "authenticated" | "internal"; asOf?: Date }>): readonly OfferDefinition[] {
  const asOf = input.asOf ?? new Date();
  return INITIAL_OFFER_CATALOG.filter(offer => offer.status === "active" && offer.customerType === input.customerType && Date.parse(offer.effectiveFrom) <= asOf.getTime() && (!offer.effectiveUntil || Date.parse(offer.effectiveUntil) > asOf.getTime()));
}

export function getOfferDefinition(code: string, version?: number, includeNonPublic = false): OfferDefinition | null {
  const matches = INITIAL_OFFER_CATALOG.filter(offer => offer.code === code && (version === undefined || offer.version === version) && (includeNonPublic || offer.status === "active"));
  return matches.sort((a,b) => b.version-a.version)[0] ?? null;
}
