import { Money } from "@/platform/kernel";
import {
  createCommercePrice,
  createCommerceProduct,
  type CommerceOffer,
} from "../domain";
import { InMemoryCommerceCatalogRepository } from "./in-memory-commerce-repository";

const createdAt = new Date("2026-07-25T00:00:00.000Z");
const products = [
  createCommerceProduct({
    id: "commerce-product-investment-analysis",
    slug: "investment-decision-analysis",
    name: "Investment Decision Analysis",
    shortDescription:
      "Transparent property underwriting with evidence, risks, and recommendation.",
    longDescription:
      "A complete Purchase or Rental Arbitrage investment decision analysis with inspectable calculations.",
    categoryId: "investment",
    type: "professional-service",
    fulfillmentType: "analysis-credit",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["investment.analysis.create", "reports.generate"],
    fulfillmentTemplateId: "grant-analysis-credit",
    createdAt,
    updatedAt: createdAt,
    metadata: { featured: "true" },
  }),
  createCommerceProduct({
    id: "commerce-product-guidebook-design",
    slug: "guidebook-design",
    name: "Guidebook Design",
    shortDescription: "Professional guest guidebook design.",
    longDescription:
      "A professionally configured digital guidebook for one property.",
    categoryId: "guidebooks",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "workspace",
    entitlementTemplateIds: ["guidebooks.design"],
    fulfillmentTemplateId: "create-guidebook-project",
    createdAt,
    updatedAt: createdAt,
  }),
  createCommerceProduct({
    id: "commerce-product-furnishing-essential",
    slug: "essential-furnishing-package",
    name: "Essential Furnishing Package",
    shortDescription: "A focused, guest-ready furnishing foundation.",
    longDescription:
      "Design direction for core living spaces, durable guest-grade furniture and décor selections, and delivery coordination.",
    categoryId: "furnishing",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "workspace",
    entitlementTemplateIds: ["furnishing.projects.create"],
    fulfillmentTemplateId: "create-furnishing-project",
    createdAt,
    updatedAt: createdAt,
  }),
  createCommerceProduct({
    id: "commerce-product-furnishing-elevated",
    slug: "elevated-furnishing-package",
    name: "Elevated Furnishing Package",
    shortDescription:
      "A curated, delivered, and installation-ready furnishing plan.",
    longDescription:
      "Professional room design, hospitality-grade product curation, procurement coordination, installation planning, and a direct Guidebook Studio handoff.",
    categoryId: "furnishing",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "workspace",
    entitlementTemplateIds: ["furnishing.projects.create"],
    fulfillmentTemplateId: "create-furnishing-project",
    createdAt,
    updatedAt: createdAt,
    metadata: { featured: "true" },
  }),
  createCommerceProduct({
    id: "commerce-product-furnishing-luxury",
    slug: "luxury-furnishing-package",
    name: "Luxury Furnishing Package",
    shortDescription:
      "Whole-property custom curation with white-glove installation.",
    longDescription:
      "Whole-property custom design direction, custom-curated furniture and art, white-glove installation, and a dedicated concierge project manager.",
    categoryId: "furnishing",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "workspace",
    entitlementTemplateIds: ["furnishing.projects.create"],
    fulfillmentTemplateId: "create-furnishing-project",
    createdAt,
    updatedAt: createdAt,
  }),
  createCommerceProduct({
    id: "commerce-product-investment-pro",
    slug: "investment-decision-analysis-pro",
    name: "Investment Decision Analysis — Pro",
    shortDescription:
      "Full underwriting with scenario modeling and comparable-set benchmarking.",
    longDescription:
      "A complete Purchase or Rental Arbitrage investment decision analysis with full financial modeling, base/optimistic/conservative scenario comparison, comparable-property benchmarking, and risk assessment.",
    categoryId: "investment",
    type: "professional-service",
    fulfillmentType: "analysis-credit",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["investment.analysis.create", "reports.generate"],
    fulfillmentTemplateId: "grant-analysis-credit",
    createdAt,
    updatedAt: createdAt,
    metadata: { featured: "true" },
  }),
  createCommerceProduct({
    id: "commerce-product-investment-premier",
    slug: "investment-decision-analysis-premier",
    name: "Investment Decision Analysis — Premier",
    shortDescription:
      "Full underwriting plus a licensed analyst's expert review.",
    longDescription:
      "Everything in Pro, plus a custom fourth scenario, a licensed analyst's review of assumptions and conclusions, and a polished executive report export.",
    categoryId: "investment",
    type: "professional-service",
    fulfillmentType: "analysis-credit",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["investment.analysis.create", "reports.generate"],
    fulfillmentTemplateId: "grant-analysis-credit",
    createdAt,
    updatedAt: createdAt,
  }),
  createCommerceProduct({
    id: "commerce-product-guidebook-diy",
    slug: "guidebook-diy",
    name: "Guidebook Studio DIY",
    shortDescription: "Templates and tools to build your own guidebook.",
    longDescription:
      "Access the full Guidebook Studio template library and step-by-step builder to create and publish your own guest guidebook.",
    categoryId: "guidebooks",
    type: "digital-product",
    fulfillmentType: "digital-download",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["guidebooks.design"],
    fulfillmentTemplateId: "create-guidebook-project",
    createdAt,
    updatedAt: createdAt,
  }),
  createCommerceProduct({
    id: "commerce-product-guidebook-done-for-you",
    slug: "guidebook-done-for-you",
    name: "Guidebook Studio Done For You",
    shortDescription: "Our team builds and designs your guidebook.",
    longDescription:
      "A professionally written and designed digital guidebook, customized to your property, with two rounds of revisions and priority support.",
    categoryId: "guidebooks",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["guidebooks.design"],
    fulfillmentTemplateId: "create-guidebook-project",
    createdAt,
    updatedAt: createdAt,
    metadata: { featured: "true" },
  }),
  createCommerceProduct({
    id: "commerce-product-guidebook-premium",
    slug: "guidebook-premium",
    name: "Guidebook Studio Premium",
    shortDescription: "Fully custom design with advanced integrations.",
    longDescription:
      "A fully custom, branded digital guidebook experience with unlimited revisions, a branded domain, and dedicated concierge support.",
    categoryId: "guidebooks",
    type: "professional-service",
    fulfillmentType: "service-project",
    status: "active",
    eligibilityPolicyId: "public",
    entitlementTemplateIds: ["guidebooks.design"],
    fulfillmentTemplateId: "create-guidebook-project",
    createdAt,
    updatedAt: createdAt,
  }),
] as const;
const prices = [
  createCommercePrice({
    id: "commerce-price-investment-analysis-v1",
    productId: products[0].id,
    type: "one-time",
    amount: Money.usd(199),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-guidebook-design-v1",
    productId: products[1].id,
    type: "custom-quote",
    amount: Money.usd(0),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-furnishing-essential-v1",
    productId: products[2].id,
    type: "one-time",
    amount: Money.usd(4995),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-furnishing-elevated-v1",
    productId: products[3].id,
    type: "one-time",
    amount: Money.usd(7995),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-furnishing-luxury-v1",
    productId: products[4].id,
    type: "one-time",
    amount: Money.usd(12995),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-investment-analysis-pro-v1",
    productId: products[5].id,
    type: "one-time",
    amount: Money.usd(499),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-investment-analysis-premier-v1",
    productId: products[6].id,
    type: "one-time",
    amount: Money.usd(999),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-guidebook-diy-v1",
    productId: products[7].id,
    type: "one-time",
    amount: Money.usd(99),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-guidebook-done-for-you-v1",
    productId: products[8].id,
    type: "one-time",
    amount: Money.usd(249),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
  createCommercePrice({
    id: "commerce-price-guidebook-premium-v1",
    productId: products[9].id,
    type: "one-time",
    amount: Money.usd(499),
    status: "active",
    effectiveFrom: createdAt,
    createdAt,
  }),
] as const;
const offers: readonly CommerceOffer[] = [
  Object.freeze({
    id: "commerce-offer-investment-starter",
    slug: "investment-starter-pack",
    name: "Investment Starter Pack",
    productIds: [products[0].id],
    priceIds: [prices[0].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({ featured: "true" }),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-furnishing-essential",
    slug: "essential-furnishing-package",
    name: "Essential Furnishing Package",
    productIds: [products[2].id],
    priceIds: [prices[2].id],
    eligibilityPolicyId: "workspace",
    status: "active",
    metadata: Object.freeze({}),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-furnishing-elevated",
    slug: "elevated-furnishing-package",
    name: "Elevated Furnishing Package",
    productIds: [products[3].id],
    priceIds: [prices[3].id],
    eligibilityPolicyId: "workspace",
    status: "active",
    metadata: Object.freeze({ featured: "true" }),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-furnishing-luxury",
    slug: "luxury-furnishing-package",
    name: "Luxury Furnishing Package",
    productIds: [products[4].id],
    priceIds: [prices[4].id],
    eligibilityPolicyId: "workspace",
    status: "active",
    metadata: Object.freeze({}),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-investment-pro",
    slug: "investment-decision-analysis-pro",
    name: "Investment Decision Analysis — Pro",
    productIds: [products[5].id],
    priceIds: [prices[5].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({ featured: "true" }),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-investment-premier",
    slug: "investment-decision-analysis-premier",
    name: "Investment Decision Analysis — Premier",
    productIds: [products[6].id],
    priceIds: [prices[6].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({}),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-guidebook-diy",
    slug: "guidebook-diy",
    name: "Guidebook Studio DIY",
    productIds: [products[7].id],
    priceIds: [prices[7].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({}),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-guidebook-done-for-you",
    slug: "guidebook-done-for-you",
    name: "Guidebook Studio Done For You",
    productIds: [products[8].id],
    priceIds: [prices[8].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({ featured: "true" }),
    createdAt,
    updatedAt: createdAt,
  }),
  Object.freeze({
    id: "commerce-offer-guidebook-premium",
    slug: "guidebook-premium",
    name: "Guidebook Studio Premium",
    productIds: [products[9].id],
    priceIds: [prices[9].id],
    eligibilityPolicyId: "public",
    status: "active",
    metadata: Object.freeze({}),
    createdAt,
    updatedAt: createdAt,
  }),
];
export const defaultCommerceCatalog = new InMemoryCommerceCatalogRepository(
  products,
  prices,
  offers,
);
