import type { SupabaseClient } from "@supabase/supabase-js";
import type { Oc001SpecialPurchaseRepository } from "../application";

export class SupabaseOc001SpecialPurchaseRepository implements Oc001SpecialPurchaseRepository{
 constructor(private readonly client:SupabaseClient){}
 async claimHpmPropertyAddon(input:Parameters<Oc001SpecialPurchaseRepository["claimHpmPropertyAddon"]>[0]):ReturnType<Oc001SpecialPurchaseRepository["claimHpmPropertyAddon"]>{return this.rpc("claim_oc001_hpm_property_addon",{p_actor_id:input.actorId,p_tenant_id:input.tenantId,p_customer_account_id:input.customerAccountId,p_quantity:input.quantity,p_idempotency_key:input.idempotencyKey,p_correlation_id:input.correlationId})}
 async completeHpmPropertyAddon(input:Parameters<Oc001SpecialPurchaseRepository["completeHpmPropertyAddon"]>[0]){return this.rpc("complete_oc001_hpm_property_addon",{p_operation_id:input.operationId,p_provider_subscription_item_reference:input.providerSubscriptionItemReference??"",p_provider_quantity:input.providerQuantity,p_provider_status:input.providerStatus,p_failure_code:input.failureCode??null})}
 async claimGuidebookRenewal(input:Parameters<Oc001SpecialPurchaseRepository["claimGuidebookRenewal"]>[0]):ReturnType<Oc001SpecialPurchaseRepository["claimGuidebookRenewal"]>{return this.rpc("claim_oc001_guidebook_hosting_renewal",{p_actor_id:input.actorId,p_tenant_id:input.tenantId,p_customer_account_id:input.customerAccountId,p_guidebook_id:input.guidebookId,p_account_mode:input.environment,p_idempotency_key:input.idempotencyKey,p_correlation_id:input.correlationId})}
 async completeGuidebookRenewalSchedule(input:Parameters<Oc001SpecialPurchaseRepository["completeGuidebookRenewalSchedule"]>[0]){return this.rpc("complete_oc001_guidebook_hosting_renewal_schedule",{p_obligation_id:input.obligationId,p_provider_subscription_reference:input.providerSubscriptionReference,p_provider_trial_end:input.providerTrialEnd})}
 async createFurnishingPurchaseIntent(input:Parameters<Oc001SpecialPurchaseRepository["createFurnishingPurchaseIntent"]>[0]):ReturnType<Oc001SpecialPurchaseRepository["createFurnishingPurchaseIntent"]>{return this.rpc("create_oc001_furnishing_approved_purchase_intent",{p_actor_id:input.actorId,p_approval_id:input.approvalId,p_expected_revision:input.expectedRevision,p_account_mode:input.environment,p_idempotency_hash:input.idempotencyHash,p_correlation_id:input.correlationId})}
 async attachCheckout(input:Parameters<Oc001SpecialPurchaseRepository["attachCheckout"]>[0]){return this.rpc("attach_oc001_checkout",{p_actor_id:input.actorId,p_purchase_intent_id:input.purchaseIntentId,p_attempt_id:input.attemptId,p_session_reference:input.sessionReference,p_customer_reference:input.customerReference,p_expires_at:input.expiresAt,p_idempotency_hash:input.idempotencyHash,p_correlation_id:input.correlationId})}
 private async rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const{data,error}=await this.client.rpc(name,args);if(error)throw new Error(mapCode(error.message));if(!data)throw new Error("OC001_OPERATION_UNAVAILABLE");return data as T}
}
function mapCode(message:string){const match=message.match(/OC001_[A-Z0-9_]+/);return match?.[0]??"OC001_OPERATION_UNAVAILABLE"}
