export const PROCUREMENT_READINESS_STATES = ["draft", "reconciling", "needs_resolution", "ready_for_review", "in_review", "changes_requested", "approved", "superseded", "archived"] as const;
export const AVAILABILITY_STATES = ["available", "limited", "backordered", "unavailable", "discontinued", "unknown", "verification_stale"] as const;
export type ReadinessSeverity = "blocking" | "warning" | "informational";

export function canTransitionProcurement(from: string, to: string) { return new Set(["draft:reconciling", "reconciling:needs_resolution", "reconciling:ready_for_review", "needs_resolution:reconciling", "ready_for_review:in_review", "in_review:changes_requested", "changes_requested:reconciling", "in_review:approved", "approved:superseded", "approved:archived"]).has(`${from}:${to}`); }

export type ReadinessLine = Readonly<{ productVersionId: string; retailerId: string | null; sku: string | null; variant: string | null; currency: string; fulfillmentMethod: string; destinationKey: string; requiredDate: string | null; quantity: number; sourceSelectionId: string; baselineUnitPriceMinor: number; currentUnitPriceMinor: number | null; deliveryMinor: number; taxMinor: number; assemblyMinor: number; installationMinor: number; availability: string; required: boolean }>;
export function aggregationKey(line: ReadinessLine) { return [line.productVersionId, line.retailerId ?? "unknown", line.sku ?? "", line.variant ?? "", line.currency, line.fulfillmentMethod, line.destinationKey, line.requiredDate ?? ""].join("|"); }
export function aggregateProcurementLines(lines: readonly ReadinessLine[]) { const groups = new Map<string, { key: string; quantity: number; sourceSelectionIds: string[] }>(); for (const line of lines) { const key = aggregationKey(line), group = groups.get(key) ?? { key, quantity: 0, sourceSelectionIds: [] }; if (group.sourceSelectionIds.includes(line.sourceSelectionId)) throw new Error("PROCUREMENT_DUPLICATE_SOURCE_ALLOCATION"); group.quantity += line.quantity; group.sourceSelectionIds.push(line.sourceSelectionId); groups.set(key, group); } return [...groups.values()].sort((a, b) => a.key.localeCompare(b.key)); }
export function reconcileQuantity(approved: number, planned: number, allocations: readonly number[]) { const allocated = allocations.reduce((n, value) => n + value, 0); return { approved, planned, allocated, reconciled: approved === planned && planned === allocated, difference: planned - approved }; }
export function classifyAvailability(state: string, required: boolean): ReadinessSeverity { if (required && ["unavailable", "discontinued", "unknown", "verification_stale"].includes(state)) return "blocking"; if (["limited", "backordered", "unknown", "verification_stale"].includes(state)) return "warning"; return "informational"; }
export function classifyPriceChange(baseline: number, current: number | null, priority = "essential") { if (current === null) return { severity: "blocking" as const, amountMinor: null, basisPoints: null, decision: "unresolved" }; const amountMinor = current - baseline, basisPoints = baseline ? Math.round(amountMinor * 10_000 / baseline) : null, material = Math.abs(amountMinor) >= 5000 || Math.abs(basisPoints ?? 0) >= 500; return { severity: material && priority === "essential" ? "blocking" as const : material ? "warning" as const : "informational" as const, amountMinor, basisPoints, decision: material ? "reapproval_required" : "within_policy" }; }
export function reconcileProcurementBudget(input: { productMinor: number; deliveryMinor: number; taxMinor: number; assemblyMinor: number; installationMinor: number; otherMinor?: number; approvedTotalMinor: number; contingencyMinor: number }) { const currentTotalMinor = input.productMinor + input.deliveryMinor + input.taxMinor + input.assemblyMinor + input.installationMinor + (input.otherMinor ?? 0), varianceMinor = currentTotalMinor - input.approvedTotalMinor, remainingContingencyMinor = input.contingencyMinor - Math.max(0, varianceMinor); return { currentTotalMinor, varianceMinor, remainingContingencyMinor, outcome: varianceMinor <= 0 ? "within_approved_budget" : remainingContingencyMinor >= 0 ? "within_approved_contingency" : "reapproval_required" }; }
export function validateDeliveryWindow(earliest: string | null, latest: string | null, target: string | null) { if (!earliest || !latest) return [{ code: "DELIVERY_WINDOW_REQUIRED", severity: "blocking" as const }]; if (new Date(earliest) > new Date(latest)) return [{ code: "DELIVERY_WINDOW_INVALID", severity: "blocking" as const }]; return target && new Date(latest) > new Date(target) ? [{ code: "DELIVERY_AFTER_TARGET", severity: "warning" as const }] : []; }
export function substitutionRequirement(input: { designApprovedAlternative: boolean; sameProductVersion: boolean; tvMountCompatible: boolean; measurementCompatible: boolean }) { if (!input.tvMountCompatible || !input.measurementCompatible || !input.designApprovedAlternative) return "design_revision_required" as const; return input.sameProductVersion ? "retailer_offer_review" as const : "procurement_approval_required" as const; }
