import Link from "next/link";
import type {
  OutcomeMetricReview, PortfolioDecisionOutcomeReview, PortfolioOutcomesWorkspace,
} from "../application/outcomes";

export function PortfolioOutcomesView({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  return <main className="mx-auto max-w-[1500px] space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <Header workspace={workspace} />
    {workspace.state === "empty" ? <Notice title="No completed portfolio decisions are ready for review">Learning will appear after execution completes and the measurement window elapses.</Notice> : null}
    {workspace.state === "insufficient-evidence" ? <Notice title="Outcome evidence is insufficient">Execution may be complete, but reliable measurement evidence is not yet available.</Notice> : null}
    {workspace.state === "degraded" ? <Notice title="Outcome evaluation is limited">Incomplete or stale operational data limits current validation. Historical reviews remain unchanged.</Notice> : null}
    {workspace.state === "permission-limited" ? <Notice title="Learning is read-only">Your Workspace role may inspect authorized learning but cannot publish reviews.</Notice> : null}
    <ReviewReadiness workspace={workspace} />
    <DecisionReviews workspace={workspace} />
    <RecommendationPerformance workspace={workspace} />
    <StrategyPerformance workspace={workspace} />
    <Assumptions workspace={workspace} />
    <KnowledgeBase workspace={workspace} />
  </main>;
}
function Header({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  const summary = workspace.summary;
  return <header className="rounded-[2rem] bg-[#101416] p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">Learn · Portfolio Intelligence</p><div className="mt-3 grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="text-3xl font-semibold sm:text-4xl">Outcomes, Learning &amp; Validation</h1><p className="mt-3 max-w-3xl text-stone-300">Compare immutable expectations with canonical measured outcomes, validate assumptions, and accumulate reusable organizational knowledge.</p></div><dl className="grid grid-cols-2 gap-5 text-sm sm:grid-cols-3"><Fact label="Reviewed" value={String(summary.reviewed)} /><Fact label="Exceeded" value={String(summary.exceeded)} /><Fact label="Met" value={String(summary.met)} /><Fact label="Partially met" value={String(summary.partiallyMet)} /><Fact label="Did not meet" value={String(summary.didNotMeet)} /><Fact label="Review completion" value={percent(summary.reviewCompletion)} /></dl></div></header>;
}
function ReviewReadiness({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  return <section aria-labelledby="readiness-heading"><Heading id="readiness-heading" title="Decision review readiness" description="A review opens only after approved execution completes, the measurement window elapses, and sufficient current evidence exists." />
    {workspace.readiness.length ? <ul className="mt-5 grid gap-3 md:grid-cols-2">{workspace.readiness.map((item) => <li key={item.decisionId} className="rounded-2xl border border-stone-200 bg-white p-5"><Pill>{title(item.state)}</Pill><p className="mt-3 font-semibold">{item.decisionId}</p><p className="mt-2 text-sm text-stone-600">{item.reasons.length ? item.reasons.join(" ") : "Ready for canonical Outcome evaluation and review."}</p>{item.reviewAt ? <time className="mt-2 block text-xs text-stone-500">Scheduled {date(item.reviewAt)}</time> : null}{item.state === "ready" ? <Link href={`/dashboard/learn/outcomes?decision=${encodeURIComponent(item.decisionId)}`} className="mt-4 inline-flex rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold">Collect and evaluate outcome</Link> : null}</li>)}</ul> : <Empty>No approved decisions are awaiting outcome review.</Empty>}
  </section>;
}
function DecisionReviews({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  return <section aria-labelledby="reviews-heading"><Heading id="reviews-heading" title="Decision reviews" description="Historical expectations remain immutable. Each later assessment creates another review version and additional learning." />
    {workspace.reviews.length ? <div className="mt-5 grid gap-5 lg:grid-cols-2">{workspace.reviews.map((review) => <ReviewCard key={review.id} review={review} />)}</div> : <Empty>No completed Portfolio Decision reviews are available.</Empty>}
  </section>;
}
function ReviewCard({ review }: Readonly<{ review: PortfolioDecisionOutcomeReview }>) {
  return <article className="rounded-[2rem] border border-stone-200 bg-white p-6"><div className="flex flex-wrap gap-2"><Pill>{title(review.success)}</Pill><Pill>{title(review.confidence)} confidence</Pill><Pill>{title(review.confidenceAdjustment)} future confidence</Pill></div><h3 className="mt-4 text-lg font-semibold">{review.decisionId}</h3><p className="mt-1 text-xs text-stone-500">Assessment v{review.assessmentVersion} · Evidence {review.decisionEvidenceVersion}</p><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><caption className="mb-2 text-left font-semibold">Expected versus realized outcomes</caption><thead><tr><th scope="col">Metric</th><th scope="col">Baseline</th><th scope="col">Expected</th><th scope="col">Actual</th><th scope="col">Variance</th></tr></thead><tbody>{review.metrics.map((metric) => <MetricRow key={metric.metric} metric={metric} />)}</tbody></table></div><div className="mt-5 rounded-xl bg-stone-50 p-4"><p className="font-semibold">Lesson</p><p className="mt-1 text-sm text-stone-700">{review.lessons.whatHappened}</p><p className="mt-2 text-xs text-stone-600">Future guidance: {review.lessons.futureGuidance}</p></div><Link href={`/dashboard/portfolio/outcomes/${encodeURIComponent(review.id)}`} className="mt-5 inline-flex rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold">Open immutable review</Link></article>;
}
function MetricRow({ metric }: Readonly<{ metric: OutcomeMetricReview }>) {
  return <tr className="border-t border-stone-100"><th scope="row" className="py-3 pr-3">{metric.metric}<span className="block font-normal text-stone-500">{title(metric.dimension)}</span></th><td className="px-3">{metric.baseline}</td><td className="px-3">{metric.expected}</td><td className="px-3">{metric.actual}</td><td className="px-3">{title(metric.direction)} · {title(metric.status)}</td></tr>;
}
function RecommendationPerformance({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  const performance = workspace.recommendationPerformance;
  return <section aria-labelledby="recommendation-heading"><Heading id="recommendation-heading" title="Recommendation performance &amp; calibration" description="Accumulated measured outcomes calibrate future confidence. Historical recommendation confidence is never rewritten." /><dl className="mt-5 grid gap-3 sm:grid-cols-4 lg:grid-cols-7">{[["Generated", performance.generated], ["Approved", performance.approved], ["Completed", performance.completed], ["Successful", performance.successful], ["Rejected", performance.rejected], ["Deferred", performance.deferred], ["Expired", performance.expired]].map(([label, value]) => <Summary key={String(label)} label={String(label)} value={String(value)} />)}</dl>{performance.byStrength.length ? <div className="mt-5 overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-sm"><caption className="sr-only">Recommendation calibration by strength</caption><thead><tr><th scope="col" className="p-4">Strength</th><th scope="col">Reviewed</th><th scope="col">Successful</th><th scope="col">Success rate</th><th scope="col">Calibration</th></tr></thead><tbody>{performance.byStrength.map((item) => <tr className="border-t" key={item.strength}><th scope="row" className="p-4">{title(item.strength)}</th><td>{item.reviewed}</td><td>{item.successful}</td><td>{item.successRate === null ? "Unavailable" : percent(item.successRate)}</td><td>{title(item.calibration)}</td></tr>)}</tbody></table></div> : null}</section>;
}
function StrategyPerformance({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  return <section aria-labelledby="strategy-heading"><Heading id="strategy-heading" title="Strategy effectiveness" description="Financial, operational, guest, resilience, and strategic results remain independently measurable." /><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{workspace.strategyEffectiveness.map((item) => <article className="rounded-2xl border bg-white p-5" key={item.decisionType}><h3 className="font-semibold">{title(item.decisionType)}</h3><p className="mt-2 text-sm">{item.reviewed} reviewed · {item.exceeded + item.met} successful</p><p className="mt-1 text-xs text-stone-500">{title(item.confidence)} evidence confidence</p></article>)}</div>{!workspace.strategyEffectiveness.length ? <Empty>No strategy outcomes are available.</Empty> : null}</section>;
}
function Assumptions({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  const assumptions = workspace.reviews.flatMap(({ assumptions }) => assumptions);
  return <section aria-labelledby="assumptions-heading"><Heading id="assumptions-heading" title="Assumption validation" description="Confirmed, invalidated, partially validated, and unevaluable assumptions remain linked to their originating decision." /><div className="mt-5 grid gap-4 lg:grid-cols-2">{assumptions.map((item) => <article key={`${item.assumptionId}:${item.reviewedAt}`} className="rounded-2xl border bg-white p-5"><Pill>{title(item.status)}</Pill><h3 className="mt-3 font-semibold">{item.statement}</h3><p className="mt-2 text-sm text-stone-600">{item.notes}</p><p className="mt-2 text-xs text-stone-500">{item.evidence.length} evidence references · {date(item.reviewedAt)}</p></article>)}</div>{!assumptions.length ? <Empty>No assumptions have been validated yet.</Empty> : null}</section>;
}
function KnowledgeBase({ workspace }: Readonly<{ workspace: PortfolioOutcomesWorkspace }>) {
  return <section aria-labelledby="knowledge-heading"><Heading id="knowledge-heading" title="Organizational knowledge" description="Structured learning accumulates from immutable reviews; later evidence appends new versions rather than rewriting history." /><div className="mt-5 grid gap-4 md:grid-cols-2">{workspace.learnings.map((item) => <article key={item.id} className="rounded-2xl border border-teal-100 bg-white p-5"><div className="flex gap-2"><Pill>{title(item.category)}</Pill><Pill>{title(item.maturity)}</Pill></div><h3 className="mt-3 font-semibold">{item.lesson}</h3><p className="mt-2 text-sm text-stone-600">{item.futureGuidance}</p><p className="mt-3 text-xs text-stone-500">{item.derivedFromReviewIds.length} reviews · {title(item.confidence)} confidence · version {item.version}</p></article>)}</div>{!workspace.learnings.length ? <Empty>No validated organizational knowledge has accumulated.</Empty> : null}</section>;
}
export function PortfolioOutcomesError({ message = "Portfolio outcomes could not be loaded. Historical reviews were not changed." }: Readonly<{ message?: string }>) { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="alert" tabIndex={-1} className="rounded-[2rem] border border-rose-200 bg-white p-8"><h1 className="text-3xl font-semibold">Portfolio outcomes are unavailable</h1><p className="mt-3 text-sm text-stone-600">{message}</p></section></main>; }
export function PortfolioOutcomesSkeleton() { return <main aria-hidden="true" className="mx-auto max-w-[1500px] animate-pulse space-y-7 px-4 py-8"><span className="sr-only">Loading portfolio outcomes</span><div className="h-64 rounded-[2rem] bg-stone-200" /><div className="grid gap-5 lg:grid-cols-2"><div className="h-80 rounded-[2rem] bg-stone-200" /><div className="h-80 rounded-[2rem] bg-stone-200" /></div></main>; }
function Heading({ id, title: heading, description }: Readonly<{ id: string; title: string; description: string }>) { return <div><h2 id={id} className="text-2xl font-semibold">{heading}</h2><p className="mt-1 max-w-4xl text-sm leading-6 text-stone-600">{description}</p></div>; }
function Fact({ label, value }: Readonly<{ label: string; value: string }>) { return <div><dt className="text-[11px] font-semibold uppercase tracking-wide text-stone-400">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
function Summary({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="rounded-2xl border bg-white p-4"><dt className="text-xs text-stone-500">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>; }
function Notice({ title: heading, children }: Readonly<{ title: string; children: React.ReactNode }>) { return <aside role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>{heading}.</strong> {children}</aside>; }
function Pill({ children }: Readonly<{ children: React.ReactNode }>) { return <span className="inline-flex rounded-full border border-stone-200 bg-stone-50 px-2.5 py-1 text-xs font-semibold">{children}</span>; }
function Empty({ children }: Readonly<{ children: React.ReactNode }>) { return <p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">{children}</p>; }
function title(value: string) { return value.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function date(value: string) { return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
function percent(value: number) { return `${(value * 100).toFixed(0)}%`; }
