import Link from "next/link";
import type {
  PortfolioDashboardAttentionItem,
  PortfolioDashboardCapitalSummary,
  PortfolioDashboardChange,
  PortfolioDashboardDriver,
  PortfolioDashboardHealthSummary,
  PortfolioDashboardRecommendation,
  PortfolioIntelligenceDashboard,
  PortfolioIntelligenceDashboardState,
} from "../application";
import { findingExplanation, portfolioLabel } from "./labels";

export function PortfolioDashboard({ state }: { state: PortfolioIntelligenceDashboardState }) {
  if (state.status === "empty") return <PortfolioDashboardEmpty dashboard={state.dashboard} />;
  if (state.status === "formation-stage") return <PortfolioDashboardFormation dashboard={state.dashboard} />;
  if (state.status === "insufficient-data") return <PortfolioDashboardInsufficient state={state} />;
  return <PortfolioDashboardReady dashboard={state.dashboard} degraded={state.status === "degraded" ? state.unavailableSections : []} />;
}

function PortfolioDashboardReady({ dashboard, degraded }: { dashboard: PortfolioIntelligenceDashboard; degraded: readonly string[] }) {
  return <div className="mx-auto max-w-[1500px] space-y-8 px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <PortfolioDashboardHeader dashboard={dashboard} />
    <PortfolioDashboardExecutiveSummaryView dashboard={dashboard} />
    {dashboard.freshness.overall !== "current" || degraded.length ? <IntelligenceNotice dashboard={dashboard} /> : null}
    <PortfolioAttentionList dashboard={dashboard} />
    <div className="grid gap-6 xl:grid-cols-2"><PortfolioHealthSummary dashboard={dashboard} /><PortfolioCapitalSummaryView capital={dashboard.capital} /></div>
    <div className="grid gap-6 xl:grid-cols-2"><PortfolioDashboardAllocationPosture dashboard={dashboard} /><PortfolioTopRecommendation dashboard={dashboard} /></div>
    <PortfolioChangeFeed dashboard={dashboard} />
    <PortfolioRecommendationList dashboard={dashboard} />
    <PortfolioDriverSummary dashboard={dashboard} />
    <PortfolioDataQualitySummary dashboard={dashboard} />
  </div>;
}

export function PortfolioDashboardHeader({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  return <header className="rounded-[2rem] bg-[#101416] px-6 py-7 text-white shadow-xl sm:px-8 lg:px-10"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-200">Portfolio Intelligence · Executive dashboard</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{dashboard.portfolio.name}</h1><p className="mt-3 text-sm text-stone-300">{dashboard.portfolio.activePropertyCount} active {dashboard.portfolio.activePropertyCount === 1 ? "property" : "properties"} · {dashboard.portfolio.activeOpportunityCount} active {dashboard.portfolio.activeOpportunityCount === 1 ? "opportunity" : "opportunities"}</p></div><div className="flex flex-col items-start gap-3 lg:items-end"><Status value={dashboard.freshness.overall === "current" ? "Intelligence current" : dashboard.freshness.overall === "stale" ? "Reevaluation required" : "Intelligence incomplete"} dark /><Link href={dashboard.portfolio.workspaceDestination} className="rounded-full border border-white/20 px-4 py-2 text-sm font-semibold text-white outline-none hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-teal-300">Open detailed workspace</Link></div></div></header>;
}

export function PortfolioDashboardExecutiveSummaryView({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const summary = dashboard.executiveSummary;
  const items = [
    ["Portfolio health", summary.healthBand ? portfolioLabel(summary.healthBand) : "Unavailable", summary.healthScore === undefined ? null : `${Math.round(summary.healthScore)}/100`],
    ["Health movement", movementLabel(summary.healthDirection), null],
    ["Primary constraint", summary.primaryConstraint ? findingExplanation(summary.primaryConstraint.code) : "No material constraint", null],
    ["Capital posture", portfolioLabel(summary.capitalStatus), dashboard.capital.deployable === null ? null : `${money(dashboard.capital.deployable)} deployable`],
    ["Top recommendation", summary.topRecommendation ? portfolioLabel(summary.topRecommendation.type) : "Unavailable", summary.topRecommendation ? portfolioLabel(summary.topRecommendation.priority) : null],
  ];
  return <section aria-labelledby="executive-summary-heading"><h2 id="executive-summary-heading" className="sr-only">Executive portfolio summary</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{items.map(([label, value, detail]) => <article key={label} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-500">{label}</p><p className="mt-2 text-xl font-semibold text-stone-950">{value}</p>{detail ? <p className="mt-1 text-xs text-stone-500">{detail}</p> : null}</article>)}</div><p className="mt-3 text-xs text-stone-500">Overall intelligence confidence: {summary.confidence ? portfolioLabel(summary.confidence.level) : "Unavailable"}</p></section>;
}

function IntelligenceNotice({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  return <section role="status" aria-live="polite" className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Portfolio intelligence needs attention.</h2><p className="mt-2 text-sm text-amber-900">{dashboard.limitations[0] ? limitationLanguage(dashboard.limitations[0].code) : "One or more executive conclusions are unavailable."}</p><p className="mt-2 text-xs text-amber-800">Refresh is unavailable in PI-006 until the assessment orchestration is deployed. Last completed intelligence remains visible where compatible.</p></section>;
}

export function PortfolioAttentionList({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  if (!dashboard.attention.items.length) return null;
  return <section aria-labelledby="dashboard-attention-heading" className="rounded-[2rem] border border-amber-200 bg-amber-50 p-6 sm:p-8"><Heading id="dashboard-attention-heading" title="Attention required" description="Bounded upstream priorities, mandatory constraints, critical recommendations, and intelligence gaps." /><ol className="mt-5 grid gap-3 lg:grid-cols-2">{dashboard.attention.items.map((item) => <AttentionRow key={`${item.rank}-${item.sourceReference.referenceId}`} item={item} />)}</ol></section>;
}
function AttentionRow({ item }: { item: PortfolioDashboardAttentionItem }) {
  const content = <><span aria-label={`Rank ${item.rank}`} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-stone-950 text-sm font-semibold text-white">{item.rank}</span><div><p className="font-semibold text-stone-950">{dashboardCode(item.code)}</p><p className="mt-1 text-xs text-stone-500">{portfolioLabel(item.type)} · Priority {portfolioLabel(item.severity)}{item.subject ? ` · ${item.subject.label}` : ""}</p></div></>;
  return <li>{item.destination ? <Link href={item.destination} className="flex min-h-20 gap-4 rounded-2xl bg-white p-4 shadow-sm outline-none hover:ring-1 hover:ring-amber-300 focus-visible:ring-2 focus-visible:ring-teal-600">{content}</Link> : <div className="flex min-h-20 gap-4 rounded-2xl bg-white p-4 shadow-sm">{content}</div>}</li>;
}

export function PortfolioHealthSummary({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const health = dashboard.health;
  return <Card title="Portfolio health" action={health.destination}><HealthHeadline health={health} /><div className="mt-6 grid grid-cols-2 gap-3">{health.limitingDimensions.map((item) => <div key={item.dimension} className="rounded-xl bg-stone-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{portfolioLabel(item.dimension)}</p><p className="mt-1 text-sm font-semibold text-stone-900">{item.band ? portfolioLabel(item.band) : "Not evaluated"}</p><p className="mt-2 text-xs leading-5 text-stone-600">{item.findingCode ? findingExplanation(item.findingCode) : "No bounded finding is available."}</p></div>)}</div>{health.dimensions.length ? <details className="mt-5 border-t border-stone-100 pt-4"><summary className="cursor-pointer text-sm font-semibold text-stone-900">All health dimensions</summary><ul className="mt-3 grid gap-2 sm:grid-cols-2">{health.dimensions.map((item) => <li key={item.dimension} className="flex justify-between rounded-lg bg-stone-50 px-3 py-2 text-sm"><span>{portfolioLabel(item.dimension)}</span><span className="font-semibold">{item.status === "evaluated" ? portfolioLabel(item.band!) : item.status === "insufficient-data" ? "Not evaluated" : "Not applicable"}</span></li>)}</ul></details> : null}</Card>;
}
function HealthHeadline({ health }: { health: PortfolioDashboardHealthSummary }) {
  if (health.status === "unavailable") return <Unavailable text="Portfolio Health is unavailable. No band or score is shown." />;
  return <div className="flex items-end justify-between gap-4"><div><p className="text-3xl font-semibold text-stone-950">{portfolioLabel(health.band!)}</p><p className="mt-2 text-sm text-stone-600">{health.movement.status === "not-comparable" ? noComparisonLabel(health.movement.reason) : `${movementLabel(health.movement.status)}${health.movement.scoreDelta === undefined ? "" : ` by ${Math.abs(health.movement.scoreDelta)} points`}.`}</p><p className="mt-1 text-xs text-stone-500">Confidence: {portfolioLabel(health.confidence!.level)} · Evaluated {formatDate(health.evaluatedAt!)}</p></div><p aria-label={`Portfolio health score ${health.score} out of 100`} className="text-3xl font-semibold text-stone-800">{Math.round(health.score!)}<span className="text-sm text-stone-400">/100</span></p></div>;
}

export function PortfolioCapitalSummaryView({ capital }: { capital: PortfolioDashboardCapitalSummary }) {
  return <Card title="Capital position" action={capital.destination}>{capital.status === "unavailable" ? <Unavailable text="Canonical capital data is unavailable. No zero values are substituted." /> : <><div className="rounded-2xl bg-stone-950 p-5 text-white"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-stone-400">Safely deployable</p><p className="mt-2 text-3xl font-semibold">{money(capital.deployable!)}</p><p className="mt-2 text-xs text-stone-400">Capital status: {portfolioLabel(capital.status)}</p></div><dl className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3"><Stat label="Available" value={amount(capital.available)} /><Stat label="Protected reserves" value={amount(capital.protected)} /><Stat label="Committed" value={amount(capital.committed)} /><Stat label="Near-term obligations" value={amount(capital.nearTermObligations)} /><Stat label="Unfunded" value={amount(capital.unfunded)} /><Stat label="Reserve coverage" value={capital.reserveCoverage === null ? "Unavailable" : `${Math.round(capital.reserveCoverage)}%`} /></dl><details className="mt-5 border-t border-stone-100 pt-4"><summary className="cursor-pointer text-sm font-semibold">Capital equation</summary><div className="mt-3 space-y-2 text-sm text-stone-700"><Equation label="Available capital" value={capital.available} /><Equation label="Protected reserves" value={capital.protected} negative /><Equation label="Existing commitments" value={capital.committed} negative /><Equation label="Near-term obligations" value={capital.nearTermObligations} negative /><Equation label="Deployable capital" value={capital.deployable} result /></div></details>{capital.unfunded !== null && capital.unfunded > 0 ? <div role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-rose-950"><strong>Capital attention required.</strong> {money(capital.unfunded)} of mandatory obligations remains unfunded.</div> : null}</>}</Card>;
}

export function PortfolioDashboardAllocationPosture({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const allocation = dashboard.allocation;
  return <Card title="Allocation posture" action={allocation.destination}>{allocation.status === "unavailable" ? <Unavailable text="Capital Allocation is unavailable. No posture is inferred." /> : <><p className="text-3xl font-semibold text-stone-950">{portfolioLabel(allocation.posture!)}</p><p className="mt-2 text-sm text-stone-600">Confidence: {portfolioLabel(allocation.confidence!.level)}{allocation.primaryConstraint ? ` · ${dashboardCode(allocation.primaryConstraint)}` : ""}</p>{allocation.primaryCandidate ? <div className="mt-5 rounded-xl border border-stone-200 p-4"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">Primary capital priority</p><p className="mt-1 font-semibold text-stone-950">{allocation.primaryCandidate.subject.label}</p></div>{allocation.primaryCandidate.rank !== null ? <Status value={`Rank ${allocation.primaryCandidate.rank}`} /> : null}</div><dl className="mt-4 grid grid-cols-2 gap-3"><Stat label="Required capital" value={amount(allocation.primaryCandidate.requiredCapital)} /><Stat label="Feasibility" value={portfolioLabel(allocation.primaryCandidate.feasibility)} /><Stat label="Health direction" value={portfolioLabel(allocation.primaryCandidate.healthDirection)} /><Stat label="Liquidity after" value={amount(allocation.primaryCandidate.liquidityAfter)} /><Stat label="Strategy" value={portfolioLabel(allocation.primaryCandidate.strategicAlignment)} /><Stat label="Trade-off" value={allocation.primaryCandidate.primaryTradeOff ? dashboardCode(allocation.primaryCandidate.primaryTradeOff) : "None established"} /></dl></div> : <p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">No primary candidate satisfies current authoritative constraints.</p>}</>}</Card>;
}

function PortfolioTopRecommendation({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const recommendation = dashboard.recommendations.topRecommendations[0];
  return <Card title="Top recommendation" action={dashboard.recommendations.destination}>{recommendation ? <RecommendationContent item={recommendation} prominent /> : <Unavailable text={dashboard.recommendations.status === "unavailable" ? "Portfolio Recommendations are unavailable." : "No active recommendation requires executive attention."} />}</Card>;
}

export function PortfolioRecommendationList({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const recommendations = dashboard.recommendations;
  if (recommendations.status === "unavailable") return <section aria-labelledby="recommendations-heading"><Heading id="recommendations-heading" title="Recommendations" description="Advisory recommendations are unavailable; Health and Allocation remain visible." /><div className="mt-4"><Unavailable text="No recommendation posture or active list has been fabricated." /></div></section>;
  return <section aria-labelledby="recommendations-heading"><Heading id="recommendations-heading" title="Top recommendations" description={`${portfolioLabel(recommendations.posture!)} posture · ${recommendations.totalActiveCount} active · ${recommendations.criticalCount} critical · ${recommendations.highCount} high`} />{recommendations.stale ? <p className="mt-3 text-sm font-semibold text-amber-800">Recommendations require reevaluation before being treated as current.</p> : null}<div className="mt-5 grid gap-4 lg:grid-cols-3">{recommendations.topRecommendations.map((item) => <article key={item.id} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><RecommendationContent item={item} /></article>)}</div>{recommendations.conflictingRecommendations.length ? <div className="mt-6 rounded-2xl border border-violet-200 bg-violet-50 p-5"><h3 className="font-semibold text-violet-950">Decision conflict</h3>{recommendations.conflictingRecommendations.map((item) => <p key={item.recommendationIds.join("-")} className="mt-2 text-sm text-violet-900">{dashboardCode(item.code)} The engine preserved both recommendations for operator review.</p>)}</div> : null}</section>;
}
function RecommendationContent({ item, prominent = false }: { item: PortfolioDashboardRecommendation; prominent?: boolean }) {
  return <div><div className="flex flex-wrap items-center gap-2"><Status value={`${portfolioLabel(item.priority)} priority`} /><Status value={portfolioLabel(item.lifecycleStatus)} /></div><h3 className={`mt-3 font-semibold text-stone-950 ${prominent ? "text-2xl" : "text-lg"}`}>{portfolioLabel(item.type)}</h3><p className="mt-1 text-sm text-stone-500">{item.subject.label} · {portfolioLabel(item.category)}</p><p className="mt-4 text-sm leading-6 text-stone-700">{dashboardCode(item.rationaleCode)}</p><dl className="mt-4 grid grid-cols-2 gap-3"><Stat label="Primary benefit" value={item.primaryBenefit ? portfolioLabel(item.primaryBenefit) : "Not quantified"} /><Stat label="Primary trade-off" value={item.primaryTradeOff ? portfolioLabel(item.primaryTradeOff) : "None established"} /><Stat label="Confidence" value={portfolioLabel(item.confidence.level)} /><Stat label="Evidence references" value={String(item.evidenceCount)} /></dl><Link href={item.destination} className="mt-5 inline-flex rounded-full border border-stone-300 px-4 py-2 text-sm font-semibold text-stone-900 outline-none hover:border-stone-500 focus-visible:ring-2 focus-visible:ring-teal-600">Review evidence</Link><p className="mt-3 text-xs text-stone-500">Advisory only. This recommendation has not been approved or executed.</p></div>;
}

export function PortfolioChangeFeed({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  return <section aria-labelledby="changes-heading"><Heading id="changes-heading" title="What changed" description="Only compatible assessment changes appear as movement." />{dashboard.changes.comparable ? dashboard.changes.items.length ? <ul className="mt-4 grid gap-3 lg:grid-cols-2">{dashboard.changes.items.map((item) => <ChangeRow key={item.id} item={item} />)}</ul> : <p className="mt-4 rounded-2xl bg-white p-5 text-sm text-stone-600">Compatible assessments show no material bounded change.</p> : <p className="mt-4 rounded-2xl border border-dashed border-stone-300 bg-white p-5 text-sm text-stone-600">No comparable prior portfolio assessment is available yet. This is different from “no change.”</p>}</section>;
}
function ChangeRow({ item }: { item: PortfolioDashboardChange }) {
  const content = <div><p className="font-semibold text-stone-950">{dashboardCode(item.code)}</p><p className="mt-1 text-xs text-stone-500">{portfolioLabel(item.type)} · {portfolioLabel(item.direction)}{item.occurredAt ? ` · ${formatDate(item.occurredAt)}` : ""}</p></div>;
  return <li>{item.destination ? <Link href={item.destination} className="block rounded-2xl border border-stone-200 bg-white p-4 outline-none hover:border-stone-400 focus-visible:ring-2 focus-visible:ring-teal-600">{content}</Link> : <div className="rounded-2xl border border-stone-200 bg-white p-4">{content}</div>}</li>;
}

export function PortfolioDriverSummary({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const drivers = dashboard.drivers;
  return <section aria-labelledby="drivers-heading"><Heading id="drivers-heading" title="Portfolio drivers and exposure" description="The strongest positive, constraining, and capital-consuming subjects in the current bounded assessment." />{drivers.singleProperty ? <p className="mt-4 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950">This is a single-property portfolio. Concentration is structural; no peer comparison or diversification failure is implied.</p> : null}<div className="mt-5 grid gap-5 lg:grid-cols-3"><DriverGroup title="Positive contributors" items={drivers.positive} empty="No positive contributor is currently established." /><DriverGroup title="Constraining contributors" items={drivers.constraining} empty="No constraining contributor is currently established." /><DriverGroup title="Capital-consuming opportunities" items={drivers.capitalConsuming} empty="No capital-consuming opportunity is currently established." /></div><div className="mt-5 grid gap-3 md:grid-cols-3">{drivers.exposures.map((item) => <Link key={`${item.type}-${item.key}`} href={item.destination} className="rounded-2xl border border-stone-200 bg-white p-4 outline-none focus-visible:ring-2 focus-visible:ring-teal-600"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{portfolioLabel(item.type)} exposure</p><p className="mt-2 text-xl font-semibold text-stone-950">{Math.round(item.share)}% · {item.key}</p><p className="mt-1 text-xs text-stone-500">Basis: {portfolioLabel(item.basis)} · {portfolioLabel(item.band)}</p></Link>)}</div></section>;
}
function DriverGroup({ title, items, empty }: { title: string; items: readonly PortfolioDashboardDriver[]; empty: string }) {
  return <section className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-semibold text-stone-950">{title}</h3>{items.length ? <ul className="mt-3 space-y-3">{items.map((item) => <li key={item.subject.id}><Link href={item.subject.destination ?? "#"} className="block rounded-xl bg-stone-50 p-3 outline-none focus-visible:ring-2 focus-visible:ring-teal-600"><p className="font-semibold text-stone-900">{item.subject.label}</p><p className="mt-1 text-xs text-stone-500">{item.driverCode ? dashboardCode(item.driverCode) : portfolioLabel(item.contribution)} · Confidence {portfolioLabel(item.confidence)}</p><p className="mt-1 text-xs text-stone-500">{shareText(item)}</p></Link></li>)}</ul> : <p className="mt-3 text-sm text-stone-500">{empty}</p>}</section>;
}

export function PortfolioDataQualitySummary({ dashboard }: { dashboard: PortfolioIntelligenceDashboard }) {
  const freshness = dashboard.freshness;
  return <section id="quality" aria-labelledby="quality-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6 sm:p-8"><Heading id="quality-heading" title="Intelligence quality and lineage" description="Current conclusions remain traceable to compatible Portfolio, Health, Allocation, and Recommendation versions." /><dl className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4"><Stat label="Overall confidence" value={freshness.confidence ? portfolioLabel(freshness.confidence.level) : "Unavailable"} /><Stat label="Property coverage" value={freshness.propertyCoverage ? `${freshness.propertyCoverage.covered} of ${freshness.propertyCoverage.total}` : "Unavailable"} /><Stat label="Stale observations" value={String(freshness.staleObservationCount)} /><Stat label="Blocking gaps" value={String(freshness.blockingGapCount)} /><Stat label="Health" value={portfolioLabel(freshness.healthStatus)} /><Stat label="Allocation" value={portfolioLabel(freshness.allocationStatus)} /><Stat label="Recommendations" value={portfolioLabel(freshness.recommendationStatus)} /><Stat label="Portfolio version" value={String(freshness.lineage.portfolioVersion)} /></dl><div className="mt-5 border-t border-stone-100 pt-4 text-xs leading-5 text-stone-500"><p>Health policy: {freshness.lineage.healthPolicyVersion ?? "Unavailable"} · Allocation policy: {freshness.lineage.allocationPolicyVersion ?? "Unavailable"} · Recommendation policy: {freshness.lineage.recommendationPolicyVersion ?? "Unavailable"}</p><p className="mt-1">Assessment fingerprints are intentionally excluded from this dashboard.</p></div></section>;
}

function PortfolioDashboardEmpty({ dashboard }: { dashboard: Extract<PortfolioIntelligenceDashboardState, { status: "empty" }>["dashboard"] }) {
  return <div className="mx-auto max-w-4xl space-y-6 px-4 py-16 text-center sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">Portfolio Intelligence</p><h1 className="text-4xl font-semibold text-stone-950">Build your portfolio intelligence foundation.</h1><p className="mx-auto max-w-xl text-sm leading-6 text-stone-600">Add an operating property or connect an acquisition opportunity to begin evaluating health and capital allocation. No health score or recommendation is shown.</p><PortfolioCapitalSummaryView capital={dashboard.capital} /><Link href={dashboard.portfolio.workspaceDestination} className="inline-flex rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white outline-none focus-visible:ring-2 focus-visible:ring-teal-600 focus-visible:ring-offset-2">Open portfolio workspace</Link></div>;
}
function PortfolioDashboardFormation({ dashboard }: { dashboard: Extract<PortfolioIntelligenceDashboardState, { status: "formation-stage" }>["dashboard"] }) {
  return <div className="mx-auto max-w-5xl space-y-6 px-4 py-10 sm:px-6"><header className="rounded-[2rem] bg-[#101416] p-8 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-200">Portfolio Intelligence</p><h1 className="mt-2 text-3xl font-semibold">{dashboard.portfolio.name}</h1><p className="mt-4 text-xl">Formation stage</p><p className="mt-2 text-sm text-stone-300">{dashboard.portfolio.activeOpportunityCount} active acquisition opportunities and no operating properties. Mature operating health and diversification assumptions are not applied.</p></header><div className="grid gap-6 lg:grid-cols-2"><PortfolioCapitalSummaryView capital={dashboard.capital} /><section className="rounded-[2rem] border border-stone-200 bg-white p-6"><h2 className="text-xl font-semibold">Formation posture</h2><p className="mt-3 text-2xl font-semibold">{dashboard.allocation.posture ? portfolioLabel(dashboard.allocation.posture) : "Unavailable"}</p><p className="mt-2 text-sm text-stone-600">{dashboard.recommendations.totalActiveCount} active recommendations where formation-stage evidence supports them.</p></section></div><Link href={dashboard.portfolio.workspaceDestination} className="inline-flex rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white">Open formation workspace</Link></div>;
}
function PortfolioDashboardInsufficient({ state }: { state: Extract<PortfolioIntelligenceDashboardState, { status: "insufficient-data" }> }) {
  return <div className="mx-auto max-w-3xl px-4 py-16"><section role="status" className="rounded-[2rem] border border-stone-200 bg-white p-8"><h1 className="text-3xl font-semibold text-stone-950">Portfolio intelligence is not yet evaluable.</h1><p className="mt-3 text-sm text-stone-600">Available sections remain accessible. Missing information is not shown as poor performance.</p><ul className="mt-4 list-disc pl-5 text-sm text-stone-700">{state.gaps.map((item) => <li key={item.code}>{dashboardCode(item.code)}</li>)}</ul></section></div>;
}

export function PortfolioDashboardSkeleton() {
  return <div role="status" aria-live="polite" aria-label="Loading Portfolio Intelligence dashboard" className="mx-auto max-w-[1500px] animate-pulse space-y-6 px-4 py-8 motion-reduce:animate-none sm:px-6 lg:px-8"><span className="sr-only">Loading portfolio condition, changes, attention, capital, and recommendations.</span><div className="h-48 rounded-[2rem] bg-stone-200" /><div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-28 rounded-2xl bg-stone-200" />)}</div><div className="h-48 rounded-[2rem] bg-stone-200" /><div className="grid gap-6 xl:grid-cols-2"><div className="h-80 rounded-[2rem] bg-stone-200" /><div className="h-80 rounded-[2rem] bg-stone-200" /></div></div>;
}

function Card({ title, action, children }: { title: string; action?: string; children: React.ReactNode }) { return <section className="rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm sm:p-7"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-xl font-semibold text-stone-950">{title}</h2>{action ? <Link href={action} className="rounded text-sm font-semibold text-stone-700 underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600">View detail</Link> : null}</div>{children}</section>; }
function Heading({ id, title, description }: { id: string; title: string; description: string }) { return <div><h2 id={id} className="text-2xl font-semibold tracking-tight text-stone-950">{title}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-600">{description}</p></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><dt className="text-[11px] font-semibold uppercase tracking-[0.1em] text-stone-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-stone-900">{value}</dd></div>; }
function Status({ value, dark = false }: { value: string; dark?: boolean }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${dark ? "border-white/20 bg-white/10 text-white" : "border-stone-200 bg-stone-50 text-stone-700"}`}>{value}</span>; }
function Unavailable({ text }: { text: string }) { return <div role="status" className="rounded-xl border border-dashed border-stone-300 bg-stone-50 p-5 text-sm text-stone-600"><strong className="text-stone-900">Unavailable.</strong> {text}</div>; }
function Equation({ label, value, negative, result }: { label: string; value: number | null; negative?: boolean; result?: boolean }) { return <div className={`flex justify-between gap-4 ${result ? "border-t border-stone-300 pt-2 font-semibold text-stone-950" : ""}`}><span>{negative ? "− " : ""}{label}</span><span>{amount(value)}</span></div>; }
function amount(value: number | null) { return value === null ? "Unavailable" : money(value); }
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
function formatDate(value: Date) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(value); }
function movementLabel(value: string) { return value === "not-comparable" ? "Not comparable" : value === "stable" ? "Stable" : portfolioLabel(value); }
function noComparisonLabel(reason: string) { return reason === "no-previous-assessment" ? "No comparable prior portfolio assessment is available yet." : reason === "policy-incompatible" ? "Health policies are incompatible; no trend is shown." : reason === "window-incompatible" ? "Observation windows are incompatible; no trend is shown." : "Coverage is insufficient for a comparable trend."; }
function shareText(item: PortfolioDashboardDriver) { const values = [item.revenueShare === undefined ? null : `${Math.round(item.revenueShare)}% revenue`, item.noiShare === undefined ? null : `${Math.round(item.noiShare)}% NOI`, item.capitalShare === undefined ? null : `${Math.round(item.capitalShare)}% capital`].filter(Boolean); return values.length ? values.join(" · ") : "Contribution share unavailable"; }
function limitationLanguage(code: string) { return code.includes("RECOMMENDATIONS") ? "Recommendations are unavailable, stale, or incompatible with current allocation intelligence." : code.includes("ALLOCATION") ? "Allocation intelligence is unavailable, stale, or incompatible with current Health." : code.includes("HEALTH") ? "Portfolio Health is unavailable or stale for the current Portfolio version." : "No compatible prior assessment is available for movement."; }
function dashboardCode(code: string) { return findingExplanation(code.replace(/^(NEW_|RESOLVED_)/, "")) || portfolioLabel(code.toLowerCase()); }
