import Link from "next/link";
import type { PortfolioPropertyComparison, PortfolioPropertyComparisonRow, PortfolioPropertyRanking } from "../application/property-comparison";

export function PortfolioPropertyComparisonView({ comparison }: { comparison: PortfolioPropertyComparison }) {
  if (!comparison.properties.length) return <ComparisonEmpty />;
  return <main className="mx-auto max-w-[1500px] space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <ComparisonHeader comparison={comparison} />
    {comparison.scope.authorization.type === "assigned-properties" ? <Notice title="Your Assigned Portfolio">Ranks, totals, shares, and medians are calculated only within properties assigned to your role.</Notice> : null}
    {comparison.properties.length === 1 ? <Notice title="Only one property is in scope">Current and prior-period metrics remain available. Portfolio-relative contribution, rank, and peer comparison require more properties.</Notice> : null}
    {comparison.freshness !== "current" ? <Notice title="Comparison is partially degraded">{comparison.evidence.currentProperties} of {comparison.properties.length} properties are current. Unaffected metrics remain available.</Notice> : null}
    <RoleSummary comparison={comparison} />
    <RankingSummary comparison={comparison} />
    <ComparisonTable comparison={comparison} />
    <div className="grid gap-8 xl:grid-cols-2"><ContributionView comparison={comparison} /><MomentumView comparison={comparison} /></div>
    <EvidenceView comparison={comparison} />
    {comparison.selectedProperty ? <PropertyDetail row={comparison.selectedProperty} comparison={comparison} /> : null}
  </main>;
}

function ComparisonHeader({ comparison }: { comparison: PortfolioPropertyComparison }) {
  return <header className="rounded-[2rem] bg-[#101416] p-6 text-white sm:p-8">
    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">Portfolio Intelligence · Properties</p>
    <div className="mt-3 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-semibold sm:text-4xl">Property Comparison</h1><p className="mt-3 text-lg text-stone-200">{comparison.scopeLabel}</p><p className="mt-1 text-sm text-stone-400">{comparison.properties.length} included {comparison.properties.length === 1 ? "property" : "properties"} · {dateRange(comparison.period.current)}</p></div><dl className="grid grid-cols-2 gap-5 text-sm sm:grid-cols-3"><Fact label="Comparison" value={comparison.period.comparisonType === "none" ? "None" : title(comparison.period.comparisonType)} /><Fact label="Confidence" value={title(comparison.confidence)} /><Fact label="Freshness" value={title(comparison.freshness)} /><Fact label="Currency" value="USD" /><Fact label="Evaluated" value={evaluated(comparison.evaluatedAt)} /></dl></div>
    <form aria-label="Property comparison controls" className="mt-7 grid gap-3 border-t border-white/10 pt-6 sm:grid-cols-2 xl:grid-cols-6">
      <Control label="Period" name="period" value="90d" values={[["30d","Last 30 days"],["90d","Last 90 days"],["ytd","Year to date"],["12m","Trailing 12 months"]]} />
      <Control label="Comparison" name="comparison" value={comparison.period.comparisonType} values={[["previous-period","Previous period"],["previous-year","Previous year"],["none","No comparison"]]} />
      <Control label="Metric family" name="family" value={comparison.metricFamily} values={[["revenue","Revenue"],["financial","Financial"],["operational","Operational"],["guest","Guest"],["evidence","Evidence"]]} />
      <Control label="Normalize by" name="normalize" value={comparison.normalization} values={[["absolute","Absolute"],["available-night","Available night"],["booked-night","Booked night"],["property","Property"],["bedroom","Bedroom"]]} />
      <Control label="Group by" name="group" value={comparison.grouping} values={[["none","None"],["market","Market"],["property-type","Property type"],["operating-model","Operating model"]]} />
      <Control label="View" name="view" value={comparison.view} values={[["table","Table"],["contribution","Contribution"],["momentum","Momentum"]]} />
      <button className="min-h-11 rounded-full bg-white px-5 text-sm font-semibold text-stone-950 focus-visible:ring-2 focus-visible:ring-teal-300 sm:col-span-2 sm:justify-self-start xl:col-span-6">Update comparison</button>
    </form>
  </header>;
}

function RoleSummary({ comparison }: { comparison: PortfolioPropertyComparison }) {
  return <section aria-labelledby="roles-heading"><Heading id="roles-heading" title="Property roles" description="One deterministic, evidence-aware descriptive role per property. Roles do not create recommendations or decisions." /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{comparison.roles.map(({ role, count }) => <div key={role} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-2xl font-semibold">{count}</p><p className="mt-1 text-sm text-stone-600">{title(role)}</p></div>)}</div></section>;
}
function RankingSummary({ comparison }: { comparison: PortfolioPropertyComparison }) {
  const visible = comparison.rankings.filter(({ entries }) => entries.length).slice(0, 4);
  return <section aria-labelledby="rankings-heading"><Heading id="rankings-heading" title="Decision-specific comparisons" description="There is no universal property score. Each list discloses eligibility, missing properties, period, normalization, and ties." /><div className="mt-5 grid gap-4 lg:grid-cols-2">{visible.map((ranking) => <Ranking key={ranking.id} ranking={ranking} />)}</div>{!visible.length ? <Empty>No properties meet the evidence requirements for the selected rankings.</Empty> : null}</section>;
}
function Ranking({ ranking }: { ranking: PortfolioPropertyRanking }) {
  return <article className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-semibold text-stone-950">{ranking.title}</h3><p className="mt-1 text-xs text-stone-500">{ranking.eligiblePropertyCount} eligible · {ranking.missingPropertyCount} unavailable · {title(ranking.normalization)}</p><ol className="mt-4 space-y-2">{ranking.entries.slice(0,3).map((entry) => <li key={entry.propertyId} className="flex justify-between gap-4 rounded-xl bg-stone-50 p-3 text-sm"><span><strong>{entry.position}.</strong> {entry.name}{entry.tied ? " · effectively tied" : ""}</span><span className="font-semibold">{rankingValue(ranking.metric, entry.value)}</span></li>)}</ol>{ranking.missingReasons.map((reason) => <p key={reason} className="mt-3 text-xs text-stone-500">{reason}</p>)}</article>;
}

function ComparisonTable({ comparison }: { comparison: PortfolioPropertyComparison }) {
  return <section aria-labelledby="table-heading"><div className="flex flex-wrap items-end justify-between gap-4"><Heading id="table-heading" title="Property comparison" description="Portfolio totals, weighted portfolio metrics, and property values remain distinct." /><form className="flex gap-2"><label className="text-xs font-semibold text-stone-600">Sort by<select name="sort" className="ml-2 min-h-10 rounded-lg border border-stone-300 px-3"><option value="revenue">Revenue</option><option value="revenue-change">Revenue change</option><option value="occupancy">Occupancy</option><option value="revpar">RevPAR</option><option value="burden">Burden</option><option value="confidence">Confidence</option></select></label><button className="min-h-10 rounded-full border border-stone-300 px-4 text-sm font-semibold">Sort</button></form></div>
    <div className="mt-5 hidden overflow-hidden rounded-2xl border border-stone-200 bg-white lg:block"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Authorized portfolio property performance and contribution comparison</caption><thead className="bg-stone-50"><tr>{["Property","Role","Revenue","Revenue change","Contribution","Occupancy","ADR","RevPAR",...(comparison.capabilities.financials ? ["NOI / Margin"] : []),...(comparison.capabilities.operations ? ["Operational burden"] : []),"Evidence"].map((heading) => <th key={heading} scope="col" className="px-4 py-3 font-semibold text-stone-700">{heading}</th>)}</tr></thead><tbody>{comparison.properties.map((row) => <DesktopRow key={row.property.propertyId} row={row} comparison={comparison} />)}</tbody></table></div>
    <div className="mt-5 space-y-4 lg:hidden">{comparison.properties.map((row) => <MobileCard key={row.property.propertyId} row={row} />)}</div>
  </section>;
}
function DesktopRow({ row, comparison }: { row: PortfolioPropertyComparisonRow; comparison: PortfolioPropertyComparison }) {
  return <tr className="border-t border-stone-100"><th scope="row" className="sticky left-0 bg-white px-4 py-4"><Link href={`?property=${row.property.propertyId}`} className="font-semibold text-stone-950 underline-offset-4 hover:underline">{row.property.name}</Link><span className="mt-1 block text-xs font-normal text-stone-500">{row.property.market ?? "Market unavailable"}{row.operatingContext.partialPeriod ? " · Partial period" : ""}</span></th><Cell>{title(row.role)}</Cell><Cell>{moneyOr(row.performance.grossRevenue)}</Cell><Cell>{signedMoneyOr(row.change.revenue)}<small>{percentOr(row.change.revenuePercent)}</small></Cell><Cell>{percentOr(row.contribution.revenue)}</Cell><Cell>{percentOr(row.performance.occupancy)}</Cell><Cell>{moneyOr(row.performance.adr)}</Cell><Cell>{moneyOr(row.performance.revpar)}</Cell>{comparison.capabilities.financials ? <Cell>{moneyOr(row.performance.netOperatingIncome ?? null)}<small>{percentOr(row.performance.operatingMargin ?? null)}</small></Cell> : null}{comparison.capabilities.operations ? <Cell>{row.operationalBurden.operationalIssues} issues<small>{row.operationalBurden.openActions} open actions</small></Cell> : null}<Cell>{title(row.evidence.confidence)}<small>{title(row.evidence.freshness)}</small></Cell></tr>;
}
function MobileCard({ row }: { row: PortfolioPropertyComparisonRow }) { return <article className="rounded-2xl border border-stone-200 bg-white p-5"><div className="flex justify-between gap-4"><div><h3 className="font-semibold text-stone-950">{row.property.name}</h3><p className="mt-1 text-xs text-stone-500">{title(row.role)}{row.operatingContext.partialPeriod ? " · Partial period" : ""}</p></div><Pill>{title(row.change.state)}</Pill></div><dl className="mt-5 grid grid-cols-2 gap-4"><Fact label="Revenue" value={moneyOr(row.performance.grossRevenue)} /><Fact label="Contribution" value={percentOr(row.contribution.revenue)} /><Fact label="Change" value={signedMoneyOr(row.change.revenue)} /><Fact label="Occupancy" value={percentOr(row.performance.occupancy)} /><Fact label="Evidence" value={title(row.evidence.confidence)} /><Fact label="Freshness" value={title(row.evidence.freshness)} /></dl><Link href={`?property=${row.property.propertyId}`} className="mt-5 inline-flex text-sm font-semibold text-teal-800 underline-offset-4 hover:underline">View {row.property.name} comparison</Link></article>; }

function ContributionView({ comparison }: { comparison: PortfolioPropertyComparison }) { return <section aria-labelledby="contribution-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6"><Heading id="contribution-heading" title="Contribution analysis" description="Mathematical shares of the authorized portfolio result, not inferred causation." />{comparison.contribution.reportedScopeChanged ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">Reported movement includes a scope change and is not like-for-like.</p> : null}<ul className="mt-5 space-y-4">{comparison.properties.map((row) => <li key={row.property.propertyId}><div className="flex justify-between text-sm"><span>{row.property.name}</span><strong>{percentOr(row.contribution.revenue)}</strong></div><div className="mt-2 h-2 rounded-full bg-stone-100" aria-hidden="true"><div className="h-2 rounded-full bg-teal-700" style={{width:`${Math.max(0,(row.contribution.revenue ?? 0)*100)}%`}} /></div><p className="mt-1 text-xs text-stone-500">{signedMoneyOr(row.contribution.revenueChange)} of portfolio revenue movement</p></li>)}</ul><p className="mt-5 text-xs text-stone-500">Revenue total reconciles: {comparison.contribution.revenueReconciles ? "Yes" : "No"} · Change reconciles: {comparison.contribution.revenueChangeReconciles ? "Yes" : "Unavailable"}</p></section>; }
function MomentumView({ comparison }: { comparison: PortfolioPropertyComparison }) { return <section aria-labelledby="momentum-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6"><Heading id="momentum-heading" title="Momentum & efficiency" description="Supported signals remain separate; no composite efficiency score is created." /><ul className="mt-5 divide-y divide-stone-100">{comparison.properties.map((row) => <li key={row.property.propertyId} className="py-4 first:pt-0"><div className="flex justify-between gap-4"><div><h3 className="font-semibold">{row.property.name}</h3><p className="mt-1 text-xs text-stone-500">{row.roleExplanation}</p></div><Pill>{title(row.change.state)}</Pill></div><p className="mt-2 text-sm text-stone-600">Revenue {percentOr(row.change.revenuePercent)} · Occupancy {pointsOr(row.change.occupancyPoints)} · Revenue / available night {moneyOr(row.efficiency.revenuePerAvailableNight)}</p></li>)}</ul></section>; }
function EvidenceView({ comparison }: { comparison: PortfolioPropertyComparison }) { return <section aria-labelledby="evidence-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6 sm:p-8"><Heading id="evidence-heading" title="Evidence quality" description="Ranking exclusions and section-level limitations remain visible." /><dl className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4"><Fact label="Current properties" value={`${comparison.evidence.currentProperties} of ${comparison.properties.length}`} /><Fact label="Stale properties" value={String(comparison.evidence.staleProperties)} /><Fact label="Degraded properties" value={String(comparison.evidence.degradedProperties)} /><Fact label="Financial eligible" value={comparison.capabilities.financials ? `${comparison.evidence.financialEligibleProperties} of ${comparison.properties.length}` : "Permission restricted"} /></dl></section>; }
function PropertyDetail({ row, comparison }: { row: PortfolioPropertyComparisonRow; comparison: PortfolioPropertyComparison }) { const peer = comparison.peerComparisons.find(({ propertyId }) => propertyId === row.property.propertyId); return <section id="property-detail" aria-labelledby="detail-heading" className="rounded-[2rem] border-2 border-teal-800 bg-white p-6 sm:p-8"><Heading id="detail-heading" title={row.property.name} description="Comparison-aware portfolio context; operational property management remains in the Property product." /><div className="mt-6 grid gap-6 md:grid-cols-3"><Detail title="Portfolio role"><p className="text-xl font-semibold">{title(row.role)}</p><p className="mt-2 text-sm text-stone-600">{row.roleExplanation}</p></Detail><Detail title="Operating context"><p>{row.operatingContext.availableNights ?? "Unavailable"} available nights</p><p>{row.operatingContext.bookedNights ?? "Unavailable"} booked nights</p><p>{row.operatingContext.activeDays} active days</p></Detail><Detail title="Peer context"><p>{peer?.available ? `${peer.label} median occupancy: ${percentOr(peer.medianOccupancy)}` : peer?.reason ?? "Peer comparison unavailable."}</p></Detail></div><div className="mt-6 flex flex-wrap gap-3"><Link href={`/properties/${row.property.propertyId}`} className="rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white">Open Property</Link><Link href="/dashboard/actions" className="rounded-full border border-stone-300 px-5 py-3 text-sm font-semibold">Related actions</Link></div></section>; }

function ComparisonEmpty() { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="status" className="rounded-[2rem] border border-stone-200 bg-white p-8 text-center"><h1 className="text-3xl font-semibold">No properties are available for comparison</h1><p className="mt-4 text-sm text-stone-600">Include an authorized property in the Workspace portfolio to begin.</p><Link className="mt-6 inline-flex rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white" href="/dashboard/workspace/properties">Review workspace properties</Link></section></main>; }
export function PortfolioPropertyComparisonError({ message = "Property comparison could not be loaded. No portfolio data was changed." }: { message?: string }) { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="alert" aria-live="assertive" className="rounded-[2rem] border border-rose-200 bg-white p-8"><h1 className="text-3xl font-semibold">Property comparison is unavailable</h1><p className="mt-3 text-sm text-stone-600">{message}</p></section></main>; }
export function PortfolioPropertyComparisonSkeleton() { return <main aria-hidden="true" className="mx-auto max-w-[1500px] animate-pulse space-y-7 px-4 py-8 motion-reduce:animate-none sm:px-6 lg:px-8"><span className="sr-only">Loading property comparison</span><div className="h-72 rounded-[2rem] bg-stone-200" /><div className="grid gap-4 sm:grid-cols-4">{Array.from({length:4},(_,index)=><div key={index} className="h-28 rounded-2xl bg-stone-200" />)}</div><div className="h-96 rounded-[2rem] bg-stone-200" /></main>; }
function Control({label,name,value,values}:{label:string;name:string;value:string;values:readonly (readonly [string,string])[]}) { return <label className="text-xs font-semibold text-stone-300">{label}<select aria-label={label} name={name} defaultValue={value} className="mt-2 min-h-11 w-full rounded-xl border border-white/20 bg-white/10 px-3 text-sm text-white focus-visible:ring-2 focus-visible:ring-teal-300">{values.map(([key,text])=><option className="text-stone-950" key={key} value={key}>{text}</option>)}</select></label>; }
function Heading({id,title:heading,description}:{id:string;title:string;description:string}) { return <div><h2 id={id} className="text-2xl font-semibold tracking-tight text-stone-950">{heading}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-600">{description}</p></div>; }
function Fact({label,value}:{label:string;value:string}) { return <div><dt className="text-[11px] font-semibold uppercase tracking-[0.1em] text-stone-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
function Cell({children}:{children:React.ReactNode}) { return <td className="px-4 py-4 text-stone-700">{children}</td>; }
function Detail({title:heading,children}:{title:string;children:React.ReactNode}) { return <section><h3 className="text-sm font-semibold uppercase tracking-wide text-stone-500">{heading}</h3><div className="mt-3 text-sm leading-6">{children}</div></section>; }
function Notice({title:heading,children}:{title:string;children:React.ReactNode}) { return <aside role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>{heading}.</strong> {children}</aside>; }
function Pill({children}:{children:React.ReactNode}) { return <span className="inline-flex h-fit rounded-full border border-stone-200 bg-stone-50 px-2.5 py-1 text-xs font-semibold">{children}</span>; }
function Empty({children}:{children:React.ReactNode}) { return <p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">{children}</p>; }
function moneyOr(value:number|null) { return value === null ? "Unavailable" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value); }
function signedMoneyOr(value:number|null) { return value === null ? "Comparison unavailable" : `${value>=0?"+":"−"}${moneyOr(Math.abs(value))}`; }
function percentOr(value:number|null|undefined) { return value === null || value === undefined ? "Unavailable" : `${(value*100).toFixed(1)}%`; }
function pointsOr(value:number|null) { return value === null ? "Unavailable" : `${value>=0?"+":"−"}${Math.abs(value*100).toFixed(1)} points`; }
function rankingValue(metric:string,value:number) { return ["revenue","noi"].includes(metric) ? moneyOr(value) : ["revenue-growth","occupancy-improvement","margin","largest-decline","operational-burden"].includes(metric) ? percentOr(value) : metric==="revpar" ? moneyOr(value) : String(value); }
function title(value:string) { return value.replaceAll("-"," ").replace(/\b\w/g,(character)=>character.toUpperCase()); }
function dateRange(range:{from:string;to:string}) { return `${range.from}–${range.to}`; }
function evaluated(value:string) { return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)); }
