export type StripeAccountMode="test"|"live";
export type BillingModel="one_time"|"recurring";
export type BillingPriceMapping=Readonly<{id:string;offerCode:string;offerVersion:number;billingModel:BillingModel;currency:string;amountMinor:number;interval?:"month"|"year";intervalCount?:number;stripeProductId:string;stripePriceId:string;stripeAccountMode:StripeAccountMode;status:"active"|"inactive"|"retired";effectiveFrom:string;effectiveUntil?:string;createdAt:string;createdBy:string;revision:number}>;
export type CheckoutAttempt=Readonly<{id:string;tenantId:string;customerAccountId:string;offerCode:string;offerVersion:number;billingPriceMappingId:string;mode:"payment"|"subscription";status:"created"|"session_created"|"completed"|"expired"|"cancelled"|"failed";stripeCustomerReference?:string;stripeCheckoutSessionReference?:string;idempotencyKeyHash:string;correlationId:string;createdAt:string;expiresAt:string;completedAt?:string;failureCode?:string;revision:number}>;
export type StripeCustomerAssociation=Readonly<{id:string;tenantId:string;customerAccountId:string;accountMode:StripeAccountMode;stripeCustomerReference:string;status:"active"|"ambiguous"|"retired";createdAt:string;revision:number}>;
export type AgreementStatus="pending"|"active"|"past_due"|"payment_action_required"|"paused"|"scheduled_to_cancel"|"cancelled"|"expired"|"refunded"|"disputed";
export type CommercialAgreement=Readonly<{id:string;tenantId:string;customerAccountId:string;offerCode:string;offerVersion:number;billingPriceMappingId:string;agreementType:"subscription"|"one_time_purchase"|"service_engagement";status:AgreementStatus;provider:"stripe";providerCustomerReference:string;providerAgreementReference?:string;currentPeriodStart?:string;currentPeriodEnd?:string;cancelAtPeriodEnd?:boolean;endedAt?:string;activatedAt?:string;createdAt:string;updatedAt:string;revision:number}>;
export type BillingProviderEvent=Readonly<{id:string;provider:"stripe";providerEventId:string;eventType:string;accountMode:StripeAccountMode;status:"received"|"processing"|"processed"|"ignored"|"failed"|"quarantined";receivedAt:string;processedAt?:string;correlationId:string;attemptCount:number;stableFailureCode?:string;payloadChecksum:string;revision:number}>;
export type BillingFailureCode="CHECKOUT_DISABLED"|"OFFER_NOT_PURCHASABLE"|"OFFER_VERSION_INACTIVE"|"CUSTOMER_NOT_ELIGIBLE"|"OFFER_PREREQUISITE_MISSING"|"OFFER_CONFLICT"|"BILLING_MODEL_UNSUPPORTED"|"BILLING_PRICE_MAPPING_MISSING"|"BILLING_PRICE_MAPPING_MISMATCH"|"BILLING_ENVIRONMENT_MISMATCH"|"CHECKOUT_ATTEMPT_CONFLICT"|"STRIPE_CUSTOMER_MAPPING_AMBIGUOUS"|"STRIPE_REQUEST_FAILED"|"WEBHOOK_SIGNATURE_INVALID"|"WEBHOOK_EVENT_DUPLICATE"|"WEBHOOK_EVENT_UNSUPPORTED"|"WEBHOOK_EVENT_OUT_OF_ORDER"|"COMMERCIAL_AGREEMENT_CONFLICT"|"PAYMENT_NOT_CONFIRMED"|"ENTITLEMENT_ACTIVATION_FAILED"|"SUBSCRIPTION_STATE_UNKNOWN"|"RECONCILIATION_REQUIRED"|"CUSTOMER_PORTAL_UNAVAILABLE";
export class BillingActivationError extends Error{constructor(public readonly code:BillingFailureCode,message:string){super(message);Object.freeze(this)}}

export type FailedPaymentPolicy=Readonly<{gracePeriodDays:number;firstFailureBehavior:"retain_access"|"suspend_access";graceExpirationBehavior:"suspend_access"|"expire_access";restorationBehavior:"automatic_after_payment"}>;
export const FAILED_PAYMENT_POLICY:FailedPaymentPolicy=Object.freeze({gracePeriodDays:7,firstFailureBehavior:"retain_access",graceExpirationBehavior:"suspend_access",restorationBehavior:"automatic_after_payment"});
export const SUBSCRIPTION_ENTITLEMENT_POLICY=Object.freeze({pending:"none",active:"activate_after_invoice_paid",payment_action_required:"retain_existing_during_grace",past_due:"retain_existing_during_grace",paused:"suspend",scheduled_to_cancel:"retain_through_period",cancelled:"expire_at_paid_through",expired:"expire",refunded:"registered_refund_policy",disputed:"suspend"}as const);

export function mapStripeSubscriptionStatus(status:string,cancelAtPeriodEnd=false):AgreementStatus{
 if(cancelAtPeriodEnd&&(status==="active"||status==="trialing"))return"scheduled_to_cancel";
 if(status==="active")return"active";if(status==="past_due"||status==="unpaid")return"past_due";if(status==="paused")return"paused";if(status==="canceled")return"cancelled";if(status==="incomplete_expired")return"expired";if(status==="incomplete")return"pending";
 throw new BillingActivationError("SUBSCRIPTION_STATE_UNKNOWN","The provider subscription state requires reconciliation.");
}
