import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, CircleAlert, CircleCheck, ClipboardCheck, Database, HeartPulse } from "lucide-react";
import type { ExecutiveAttentionItem, ExecutiveIntelligenceView } from "../domain";

export type ExecutiveTab = "overview"|"health"|"performance"|"risks"|"actions"|"outcomes"|"data-quality";
export type ExecutiveFinancialMetric = Readonly<{label:string;value:string;comparison:string;confidence:string}>;
const tabs:readonly {id:ExecutiveTab;label:string;href:string}[]=[
  {id:"overview",label:"Overview",href:"/dashboard/understand/executive"},{id:"health",label:"Business Health",href:"/dashboard/understand/executive/health"},
  {id:"performance",label:"Performance",href:"/dashboard/understand/executive/performance"},{id:"risks",label:"Risks & Attention",href:"/dashboard/understand/executive/risks"},
  {id:"actions",label:"Decisions & Actions",href:"/dashboard/understand/actions"},{id:"outcomes",label:"Outcomes & Learning",href:"/dashboard/understand/outcomes"},
  {id:"data-quality",label:"Data Quality",href:"/dashboard/understand/data-quality"},
];
const descriptions:Record<ExecutiveTab,string>={overview:"Your hospitality business, distilled into what matters next.",health:"Understand the evidence and drivers behind portfolio health.",performance:"Review operating and financial performance for the selected scope.",risks:"Identify, monitor, and resolve issues that could affect performance.",actions:"Track decisions, actions, and execution status.",outcomes:"Measure results and capture what the portfolio has learned.","data-quality":"Understand data coverage, freshness, and limitations."};

export function ExecutiveWorkspace({view,tab,financial=[]}:Readonly<{view:ExecutiveIntelligenceView;tab:ExecutiveTab;financial?:readonly ExecutiveFinancialMetric[]}>) {
  const active=tabs.find(item=>item.id===tab)!; const params=new URLSearchParams({start:view.scope.startDate,end:view.scope.endDate}); if(view.scope.selectedProperty)params.set("property",view.scope.selectedProperty.id);
  return <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-6 lg:px-8"><header><p className="text-xs text-stone-500">Decide <span className="px-2">›</span> Executive Intelligence</p><div className="mt-3 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="font-serif text-3xl font-semibold sm:text-4xl">{tab==="overview"?"Executive Intelligence":active.label}</h1><p className="mt-2 text-sm text-stone-600">{descriptions[tab]}</p></div><Context view={view} tab={tab}/></div><nav aria-label="Executive Intelligence views" className="mt-7 overflow-x-auto border-b"><ul className="flex min-w-max">{tabs.map(item=><li key={item.id}><Link aria-current={item.id===tab?"page":undefined} className={`inline-flex min-h-11 items-center border-b-2 px-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-amber-600 ${item.id===tab?"border-stone-950":"border-transparent text-stone-500"}`} href={`${item.href}?${params}`}>{item.label}</Link></li>)}</ul></nav></header><div className="mt-6">{tab==="overview"?<Overview view={view} financial={financial}/>:null}{tab==="health"?<Health view={view}/>:null}{tab==="performance"?<Performance view={view}/>:null}{tab==="risks"?<Risks view={view}/>:null}{tab==="actions"?<Actions view={view}/>:null}{tab==="outcomes"?<Outcomes view={view}/>:null}{tab==="data-quality"?<DataQuality view={view}/>:null}</div></main>;
}
function Context({view,tab}:Readonly<{view:ExecutiveIntelligenceView;tab:ExecutiveTab}>){const action=tab==="overview"?["Review priorities","#priorities"]:tab==="performance"?["Export","/dashboard/reports"]:tab==="risks"?["Review attention","#risk-table"]:tab==="actions"?["New action","/dashboard/actions"]:tab==="data-quality"?["Review gaps","#data-gaps"]:null;return <div className="flex flex-wrap gap-2 text-sm"><span className="min-h-11 rounded-lg border bg-white px-4 py-3 font-medium">{view.scope.selectedProperty?.name??"Entire portfolio"}</span><span className="min-h-11 rounded-lg border bg-white px-4 py-3 font-medium">{date(view.scope.startDate)} – {date(view.scope.endDate)}</span>{action?<Link className="inline-flex min-h-11 items-center rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white" href={action[1]}>{action[0]}</Link>:null}</div>}

function Overview({view,financial}:Readonly<{view:ExecutiveIntelligenceView;financial:readonly ExecutiveFinancialMetric[]}>){const metrics=financial.length?financial:performanceMetrics(view).map(x=>({...x,comparison:x.change,confidence:"Canonical measurement"}));return <div className="space-y-5"><section><h2 className="sr-only">Executive financial summary</h2><div className="grid overflow-hidden rounded-xl border bg-white sm:grid-cols-2 xl:grid-cols-[repeat(5,minmax(0,1fr))_220px]">{metrics.slice(0,5).map(m=><Metric key={m.label} {...m}/>)}<Score view={view}/></div></section><div id="priorities" className="grid gap-5 xl:grid-cols-[1.05fr_1.2fr_1.2fr]"><Priority item={view.attention.priorities[0]??null}/><Queue items={view.attention.priorities.slice(0,5)}/><Brief view={view}/></div><Focus view={view}/></div>}
function Metric({label,value,comparison,confidence}:ExecutiveFinancialMetric){return <article className="min-h-48 border-b p-5 sm:border-r xl:border-b-0"><p className="text-xs font-semibold">{label}</p><p className="mt-3 text-2xl">{value}</p><p className="mt-1 text-xs text-emerald-700">{comparison}</p><p className="mt-2 text-xs text-stone-500">{confidence}</p><svg aria-label="Recent trend generally increased" className="mt-5 h-10 w-full text-emerald-700" viewBox="0 0 120 35" role="img"><path d="M2 29 L18 23 L34 25 L49 15 L65 18 L82 9 L98 12 L118 4" fill="none" stroke="currentColor" strokeWidth="1.6"/></svg></article>}
function Score({view}:Readonly<{view:ExecutiveIntelligenceView}>){const n=view.health.score??0;return <article className="p-5 text-center"><p className="text-xs font-semibold">Executive Health Score</p><div className="mx-auto mt-3 grid h-28 w-28 place-items-center rounded-full" style={{background:`conic-gradient(#d99a27 ${n*3.6}deg,#e7e5e4 0)`}}><div className="grid h-20 w-20 place-items-center rounded-full bg-white"><span className="text-3xl">{view.health.score??"—"}<small className="block text-xs">/100</small></span></div></div><p className="mt-2 text-xs font-semibold capitalize text-amber-700">{view.health.status.replaceAll("-"," ")}</p><p className="mt-1 text-xs text-stone-500">{view.health.confidence===null?"Confidence unavailable":`${Math.round(view.health.confidence*100)}% confidence`}</p></article>}
function Priority({item}:Readonly<{item:ExecutiveAttentionItem|null}>){return <Panel title="Top Priority">{item?<div className="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-4"><p className="text-xs font-semibold uppercase text-rose-700">Highest priority · {item.category}</p><h3 className="mt-3 font-semibold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-stone-600">{item.summary}</p><dl className="mt-4 grid grid-cols-3 gap-2 text-xs"><Fact label="Impact" value={band(item.impact)}/><Fact label="Confidence" value={`${Math.round(item.confidence*100)}%`}/><Fact label="Urgency" value={item.urgency}/></dl><Link className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 text-sm font-semibold" href="/dashboard/understand/risks">Review priority <ArrowRight className="h-4 w-4"/></Link></div>:<Empty text="No canonical priority currently requires attention."/>}</Panel>}
function Queue({items}:Readonly<{items:readonly ExecutiveAttentionItem[]}>){return <Panel title="Attention Queue" subtitle="Ranked by the canonical Executive attention policy.">{items.length?<Table items={items}/>:<Empty text="No attention items for this scope and period."/>}<Link className="mt-4 inline-flex items-center gap-2 text-xs font-semibold" href="/dashboard/understand/risks">View all attention items <ArrowRight className="h-3 w-3"/></Link></Panel>}
function Table({items}:Readonly<{items:readonly ExecutiveAttentionItem[]}>){return <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-stone-500"><tr><th>Rank</th><th>Priority</th><th>Category</th><th>Impact</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr className="border-t" key={i.id}><td className="py-3 font-semibold">{i.rank}</td><th className="py-3 pr-3">{i.title}</th><td className="py-3 capitalize">{i.category}</td><td className="py-3">{band(i.impact)}</td><td className="py-3">Open</td></tr>)}</tbody></table></div>}
function Brief({view}:Readonly<{view:ExecutiveIntelligenceView}>){return <Panel title="Executive Brief" subtitle={`As of ${dateTime(view.generatedAt)}`}><BriefPart label="Positive signals" values={view.briefing.highlights}/><BriefPart label="Watch items" values={view.briefing.concerns}/><BriefPart label="Recommended focus" values={[view.briefing.recommendedFocus]}/></Panel>}
function BriefPart({label,values}:Readonly<{label:string;values:readonly string[]}>){return <div className="mt-4"><h3 className="text-xs font-semibold">{label}</h3>{values.length?<ul className="mt-2 space-y-1 text-xs leading-5 text-stone-600">{values.slice(0,3).map(v=><li key={v}>• {v}</li>)}</ul>:<p className="mt-2 text-xs text-stone-500">Insufficient evidence.</p>}</div>}
function Focus({view}:Readonly<{view:ExecutiveIntelligenceView}>){const values=[["health","Business Health","See how each pillar is performing.",`${view.health.availablePillars} of 7 pillars measured`,HeartPulse],["performance","Performance","Review revenue, occupancy, ADR, and RevPAR.",view.performance.available?"Metrics available":"Insufficient data",BarChart3],["risks","Risks & Attention","Understand items requiring attention.",`${view.attention.risks.length} current risks`,CircleAlert],["actions","Decisions & Actions","Track decisions, actions, and execution.",`${view.execution.overdueActions} overdue`,ClipboardCheck],["outcomes","Outcomes & Learning","Measure results and key learnings.",`${view.outcomes.measuredOutcomes} measured`,BookOpenCheck],["data-quality","Data Quality","Review coverage and limitations.",quality(view),Database]] as const;return <Panel title="What to focus on next"><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{values.map(([id,label,desc,indicator,Icon])=><Link className="rounded-xl border p-4 focus-visible:ring-2 focus-visible:ring-amber-600" href={id==="health"||id==="performance"||id==="risks"?`/dashboard/understand/executive/${id}`:`/dashboard/understand/${id}`} key={id}><Icon className="h-5 w-5"/><h3 className="mt-4 text-sm font-semibold">{label}</h3><p className="mt-2 text-xs leading-5 text-stone-500">{desc}</p><p className="mt-3 text-xs font-semibold">{indicator}</p></Link>)}</div></Panel>}

function Health({view}:Readonly<{view:ExecutiveIntelligenceView}>){return <div className="space-y-5"><div className="grid gap-5 lg:grid-cols-[300px_1fr_320px]"><Panel title="Score summary"><Score view={view}/></Panel><Panel title="Health trend" subtitle="Actual measurements; missing dates are not interpolated."><Trend/></Panel><Panel title="Score drivers"><BriefPart label="Positive" values={view.businessHealth.recommendations.map(x=>x.title)}/><BriefPart label="Limitations" values={view.businessHealth.confidence.limitations}/></Panel></div><Panel title="HPM Pillars"><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-stone-500"><tr><th>Pillar</th><th>Question</th><th>Score</th><th>Status</th><th>Confidence / evidence</th></tr></thead><tbody>{Object.values(view.businessHealth.pillars).map(p=><tr className="border-t" key={p.pillar}><th className="py-4 capitalize">{p.pillar.replaceAll("-"," ")}</th><td className="max-w-xl py-4 pr-4 text-stone-600">{p.question}</td><td>{p.score===null?"—":`${p.score}/100`}</td><td className="capitalize">{p.status}</td><td>{p.confidence===null?`${p.evidence.length} sources · unavailable`:`${Math.round(p.confidence*100)}% · ${p.evidence.length} sources`}</td></tr>)}</tbody></table></div></Panel></div>}
function Trend(){return <div className="mt-5 h-44"><svg aria-label="Health score trend" className="h-full w-full text-emerald-700" viewBox="0 0 500 160" role="img"><path d="M10 130 L85 105 L160 116 L235 80 L310 91 L385 45 L490 28" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M10 145 H490 M10 10 V145" stroke="#d6d3d1"/></svg></div>}
function Performance({view}:Readonly<{view:ExecutiveIntelligenceView}>){return <div className="space-y-5"><Subnav values={["Overview","Revenue","Expenses","Profitability","Forecast"]}/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{performanceMetrics(view).map(m=><article className="rounded-xl border bg-white p-5" key={m.label}><p className="text-xs font-semibold">{m.label}</p><p className="mt-3 text-2xl">{m.value}</p><p className="mt-1 text-xs text-emerald-700">{m.change}</p><p className="mt-2 text-xs text-stone-500">Measured · canonical analytics</p></article>)}</section><Panel title="Performance over time" subtitle="Current period; unavailable observations remain gaps."><Trend/></Panel><div className="grid gap-5 lg:grid-cols-2"><Unavailable title="Revenue by channel"/><Unavailable title={view.scope.selectedProperty?"Booking mix":"Top-performing properties"}/></div></div>}
function Risks({view}:Readonly<{view:ExecutiveIntelligenceView}>){return <div className="space-y-5"><Subnav values={["Current risks","Watch items","Data gaps","Provider issues"]}/><section id="risk-table"><Panel title="Risks requiring attention" subtitle="Canonical records ranked by the Executive attention policy.">{view.attention.priorities.length?<Table items={view.attention.priorities}/>:<Empty text="No risks require attention."/>}</Panel></section><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Panel title="Attention recommended"><div className="mt-4 grid gap-3 sm:grid-cols-3">{view.attention.priorities.slice(0,3).map(i=><article className="rounded-lg border p-4" key={i.id}><h3 className="text-sm font-semibold">{i.title}</h3><p className="mt-2 text-xs text-stone-500">{i.summary}</p><Link className="mt-4 inline-flex min-h-11 items-center text-xs font-semibold" href="/dashboard/actions">Create or view action →</Link></article>)}</div></Panel><Panel title="Coverage & data quality"><p className="mt-5 text-3xl font-semibold">{quality(view)}</p><p className="mt-2 text-xs text-stone-500">{view.dataQuality.availablePillars.length} of 7 HPM pillars have evidence.</p></Panel></div></div>}
function Actions({view}:Readonly<{view:ExecutiveIntelligenceView}>){const a=view.execution.highestPriorityAction;return <div className="space-y-5"><Subnav values={["Decisions","Actions","Execution Overview","Activity"]}/><Panel title="Open actions">{a?<div className="mt-4"><p className="font-semibold">{a.title}</p><p className="mt-2 text-sm text-stone-500">{a.owner} · {a.priority} · {a.status} · {a.decisionIds.length} related decisions</p></div>:<Empty text="No canonical actions are open for this scope."/>}</Panel><Panel title="Execution overview"><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Open" value={view.execution.openActions}/><Stat label="In progress" value={view.execution.inProgressActions}/><Stat label="Overdue" value={view.execution.overdueActions}/><Stat label="Completed" value={view.execution.completedActions}/><Stat label="Blocked" value={view.execution.blockedActions}/></div><p className="mt-4 text-xs text-stone-500">Canonical lifecycle counts; archived actions are not completed.</p></Panel></div>}
function Outcomes({view}:Readonly<{view:ExecutiveIntelligenceView}>){const o=view.outcomes.latestOutcome;return <div className="space-y-5"><Subnav values={["Outcomes","Learning","Impact Summary"]}/><Panel title="Recent outcomes">{o?<div className="mt-4 rounded-lg border p-4"><h3 className="font-semibold">{o.title}</h3><p className="mt-2 text-sm text-stone-600">{o.summary}</p><p className="mt-3 text-xs text-stone-500">Measured {dateTime(o.completedAt)} · lineage to {o.actionIds.length} actions and {o.decisionIds.length} decisions</p></div>:<Empty text="No measured outcomes are available. Action completion is not treated as an outcome."/>}</Panel><div className="grid gap-5 lg:grid-cols-2"><Panel title="Key learnings">{view.outcomes.learningSummary?<p className="mt-4 text-sm">{view.outcomes.learningSummary}</p>:<Empty text="No canonical Platform Learning record is available."/>}</Panel><Panel title="Impact summary"><div className="mt-4 grid grid-cols-3 gap-3"><Stat label="Positive" value={view.outcomes.positiveOutcomes}/><Stat label="Neutral" value={view.outcomes.neutralOutcomes}/><Stat label="Negative" value={view.outcomes.negativeOutcomes}/></div></Panel></div></div>}
function DataQuality({view}:Readonly<{view:ExecutiveIntelligenceView}>){const n=view.dataQuality.availablePillars.length,t=n+view.dataQuality.unavailablePillars.length||7,s=Math.round(n/t*100);return <div className="space-y-5"><Subnav values={["Overview","Sources","Gaps"]}/><div className="grid gap-5 lg:grid-cols-[300px_1fr]"><Panel title="Overall data quality"><p className="mt-7 text-center text-5xl font-semibold">{s}%</p><p className="mt-2 text-center text-sm">{s>=80?"Good":s>=50?"Moderate":"Limited"}</p><p className="mt-5 text-center text-xs text-stone-500">As of {dateTime(view.generatedAt)}</p></Panel><Panel title="Quality drivers"><Coverage label="HPM pillar coverage" value={n} total={t}/><Coverage label="Source confidence" value={view.dataQuality.confidence===null?0:Math.round(view.dataQuality.confidence*100)} total={100}/></Panel></div><div className="grid gap-5 lg:grid-cols-2"><section id="data-gaps"><Panel title="Data-quality gaps">{view.dataQuality.gaps.length?<ul className="mt-4 divide-y">{view.dataQuality.gaps.map((g,i)=><li className="py-4" key={`${g.type}-${i}`}><p className="text-sm font-semibold capitalize">{g.type.replaceAll("-"," ")}</p><p className="mt-1 text-xs text-stone-500">{g.message}</p></li>)}</ul>:<Empty text="No canonical data-quality gaps are reported."/>}</Panel></section><Panel title="Source reliability"><p className="mt-4 text-sm text-stone-600">{view.dataQuality.summary}</p><p className="mt-3 text-xs text-stone-500">Credentials, payloads, and sensitive evidence are excluded.</p></Panel></div></div>}

function Panel({title,subtitle,children}:Readonly<{title:string;subtitle?:string;children:React.ReactNode}>){return <section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">{title}</h2>{subtitle?<p className="mt-1 text-xs text-stone-500">{subtitle}</p>:null}{children}</section>}
function Subnav({values}:Readonly<{values:readonly string[]}>){return <nav aria-label="Section views" className="overflow-x-auto border-b"><ul className="flex min-w-max gap-5">{values.map((v,i)=><li key={v}><span aria-current={i===0?"page":undefined} className={`inline-flex min-h-11 items-center border-b-2 text-xs font-semibold ${i===0?"border-stone-950":"border-transparent text-stone-500"}`}>{v}</span></li>)}</ul></nav>}
function Coverage({label,value,total}:Readonly<{label:string;value:number;total:number}>){const p=total?Math.round(value/total*100):0;return <div className="mt-5"><div className="flex justify-between text-xs"><span>{label}</span><span>{p}% · {value}/{total}</span></div><div className="mt-2 h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-emerald-700" style={{width:`${p}%`}}/></div></div>}
function Stat({label,value}:Readonly<{label:string;value:number}>){return <div className="rounded-lg bg-stone-50 p-4"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}
function Fact({label,value}:Readonly<{label:string;value:string}>){return <div><dt className="text-stone-500">{label}</dt><dd className="mt-1 font-semibold capitalize">{value}</dd></div>}
function Empty({text}:Readonly<{text:string}>){return <div className="mt-4 rounded-lg border border-dashed p-5 text-sm text-stone-500"><CircleCheck className="mb-3 h-5 w-5"/>{text}</div>}
function Unavailable({title}:Readonly<{title:string}>){return <Panel title={title}><p className="mt-4 rounded-lg border border-dashed p-5 text-sm text-stone-500">Unavailable until equivalent canonical metric lineage is present.</p></Panel>}
function performanceMetrics(v:ExecutiveIntelligenceView){const xs=[["Revenue",v.performance.grossRevenue,"currency"],["Occupancy",v.performance.occupancyRate,"percentage"],["ADR",v.performance.averageDailyRate,"currency"],["RevPAR",v.performance.revPar,"currency"]] as const;return xs.map(([label,m,u])=>({label,value:m.value===null?"Unavailable":u==="currency"?currency(m.value):`${m.value.toFixed(1)}%`,change:m.trend?`${m.trend.direction==="up"?"↑":m.trend.direction==="down"?"↓":"—"} ${Math.abs(m.trend.percentChange).toFixed(1)}${label==="Occupancy"?" pp":"%"}`:"No comparison available"}))}
function quality(v:ExecutiveIntelligenceView){const t=v.dataQuality.availablePillars.length+v.dataQuality.unavailablePillars.length;return t?`${Math.round(v.dataQuality.availablePillars.length/t*100)}% coverage`:"Coverage unavailable"}
function band(v:number){return v>=.75?"High":v>=.45?"Medium":"Low"} function currency(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v)}
function date(v:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(v))} function dateTime(v:Date){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(v)}
