import Link from "next/link";
import Image from "next/image";
import {notFound} from "next/navigation";
import {getGuidebookEditorRequest} from "@/app/actions/guidebook-studio";
import {resolveGuidebookVariables,type GuidebookVariableContext} from "@/features/guidebook-studio";
import {propertyProjectionVariables} from "@/features/property-projection";

export default async function GuidebookPreview({params,searchParams}:{params:Promise<{guidebookId:string}>;searchParams:Promise<{viewport?:string}>}){
 const{id:guidebookId}={id:(await params).guidebookId},query=await searchParams,viewport=["desktop","tablet","mobile"].includes(query.viewport??"")?query.viewport!:"mobile",result=await getGuidebookEditorRequest(guidebookId);if(!result.ok)notFound();
 const width=viewport==="desktop"?"max-w-6xl":viewport==="tablet"?"max-w-3xl":"max-w-lg",variables=propertyProjectionVariables(result.propertyProjection,`/g/${result.guidebook.public_slug}`);
 return <main className="min-h-screen bg-[#eee5d7] px-4 py-8"><div className={`mx-auto mb-5 ${width}`}><div className="flex items-center justify-between gap-3"><Link href={`/dashboard/guidebooks/${guidebookId}`} className="text-sm font-semibold text-stone-800">← Return to Studio</Link><Link href={`/dashboard/guidebooks/${guidebookId}/publish`} className="rounded-lg bg-emerald-900 px-4 py-2 text-sm font-semibold text-white">Looks Good, Continue →</Link></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-stone-600">Read-only draft preview · {viewport}</p><p className="mt-1 text-xs text-stone-500">Draft revision {result.draft?.revision??result.guidebook.revision} · Property projection {result.propertyProjection.version} · Updated {new Date(result.draft?.persistedAt??result.propertyProjection.updatedAt).toLocaleString()}</p></div><nav aria-label="Preview viewport" className="flex rounded-full border bg-white p-1">{["desktop","tablet","mobile"].map(item=><Link key={item} href={`?viewport=${item}`} aria-current={viewport===item?"page":undefined} className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${viewport===item?"bg-stone-950 text-white":""}`}>{item}</Link>)}</nav></div>{result.propertyDrift.reviewRecommended?<p role="status" className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-950">{result.propertyDrift.summary} This preview uses current property values; the published guidebook remains unchanged.</p>:null}</div><div className={`mx-auto transition-all ${width}`}><GuidebookBody title={result.draft?.title??result.guidebook.title} description={result.draft?.description??result.guidebook.description} propertyName={result.propertyProjection.identity.name} sections={result.draftSections} variables={variables}/></div></main>
}
function GuidebookBody({title,description,propertyName,sections,variables}:{title:string;description:string;propertyName:string;sections:Record<string,unknown>[];variables:GuidebookVariableContext}){return <article className="w-full overflow-hidden rounded-[2rem] bg-[#fbf8f1] shadow-2xl"><header className="bg-[#1d1a17] px-7 py-12 text-white"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d7b77d]">{propertyName||title}</p><h1 className="mt-5 font-serif text-5xl leading-none">Welcome home.</h1><p className="mt-5 leading-7 text-stone-300">{description}</p></header><div className="space-y-5 p-5">{sections.filter(section=>section.visible).map(section=><section key={String(section.id)} className="rounded-2xl border border-stone-200 bg-white p-5"><h2 className="font-serif text-2xl">{String(section.title)}</h2><div className="mt-3 space-y-3">{((section.guidebook_blocks as Record<string,unknown>[])??[]).filter(block=>block.visible!==false).map(block=><PreviewBlock key={String(block.id)} block={block} variables={variables}/>)}</div></section>)}</div></article>}
function PreviewBlock({block,variables}:{block:Record<string,unknown>;variables:GuidebookVariableContext}){const content=(block.content as Record<string,unknown>)??{},text=resolveGuidebookVariables(String(content.text??content.markdown??content.label??""),variables).value;if(block.block_type==="divider")return <hr/>;if(block.block_type==="image"&&content.url)return <figure><Image src={String(content.url)} alt={String(content.alt??"")} width={1200} height={800} className="w-full rounded-xl"/>{content.caption?<figcaption className="mt-2 text-xs text-stone-500">{String(content.caption)}</figcaption>:null}</figure>;if(block.block_type==="heading")return <h3 className="font-serif text-xl">{text}</h3>;if(block.block_type==="callout")return <p className="rounded-xl bg-amber-50 p-4 text-sm">{text}</p>;return <p className="whitespace-pre-wrap text-sm leading-6 text-stone-700">{text}</p>}
