import type{AuthoringBlock,AuthoringBlockType,GuidebookDraft}from"@/features/guidebook-studio";
export type BuilderPreviewMode="desktop"|"tablet"|"mobile"|"pdf"|"guest_portal";
export type BuilderSaveState="loading"|"saving"|"saved"|"conflict"|"offline"|"failed";
export type BuilderPanel="content"|"bindings"|"media"|"actions"|"visibility"|"layout"|"validation";
export type BuilderIssue={code:string;severity:"error"|"warning"|"info";message:string;blocking:boolean;sectionId?:string;blockId?:string};
export const BUILDER_COMPONENTS:ReadonlyArray<{key:AuthoringBlockType;name:string;category:string;sectionHints:string[]}>= [
 {key:"heading",name:"Section Header",category:"foundation",sectionHints:["all"]},{key:"rich-text",name:"Rich Text",category:"foundation",sectionHints:["all"]},{key:"image",name:"Image / Gallery",category:"media",sectionHints:["welcome","explore","stay"]},{key:"instruction",name:"Arrival Instructions",category:"arrival",sectionHints:["arrival","wifi","departure"]},{key:"contact",name:"Emergency Contact",category:"safety",sectionHints:["emergency","safety","stay"]},{key:"location",name:"Map / Recommendation",category:"explore",sectionHints:["explore","restaurants","shopping"]},{key:"link",name:"Guest Action",category:"engagement",sectionHints:["all"]},{key:"callout",name:"Rule / Notice",category:"stay",sectionHints:["house rules","safety","stay"]},{key:"checklist",name:"Departure Checklist",category:"departure",sectionHints:["departure","checkout"]}
];
export function compatibleComponents(sectionName:string){const key=sectionName.toLowerCase();return BUILDER_COMPONENTS.filter(item=>item.sectionHints.includes("all")||item.sectionHints.some(h=>key.includes(h)))}
export function guidebookHealth(draft:GuidebookDraft):{score:number;issues:BuilderIssue[];publishable:boolean}{const issues:BuilderIssue[]=[];const visible=draft.sections.filter(s=>s.visible);if(!visible.length)issues.push({code:"sections_required",severity:"error",message:"At least one visible section is required.",blocking:true});const names=visible.map(s=>s.name.toLowerCase());for(const [needle,label]of[["wifi","Wi-Fi"],["rule","House Rules"],["depart","Departure"]]as const)if(!names.some(n=>n.includes(needle)))issues.push({code:`missing_${needle}`,severity:needle==="wifi"?"error":"warning",message:`Add a ${label} section.`,blocking:needle==="wifi"});for(const section of visible){if(!section.blocks.length)issues.push({code:"empty_section",severity:"warning",message:`${section.name} has no components.`,blocking:false,sectionId:section.id});for(const block of section.blocks)if(block.type==="image"&&!block.content.alt.trim())issues.push({code:"image_alt_missing",severity:"error",message:"Image alt text is required.",blocking:true,sectionId:section.id,blockId:block.id})}const penalty=issues.reduce((sum,i)=>sum+(i.severity==="error"?15:i.severity==="warning"?5:1),0);return{score:Math.max(0,100-penalty),issues,publishable:!issues.some(i=>i.blocking)}}
export function blockSummary(block:AuthoringBlock){switch(block.type){case"heading":return block.content.text;case"rich-text":return block.content.text;case"image":return block.content.caption||block.content.alt||"Image";case"instruction":return block.content.title||`${block.content.steps.length} steps`;case"contact":return block.content.name;case"location":return block.content.label;case"link":return block.content.label;case"callout":return block.content.title||block.content.body;case"checklist":return block.content.title||`${block.content.items.length} tasks`}}
export function autosaveDelay(changePending:boolean){return changePending?30_000:null}
