import Link from "next/link";
import { notFound } from "next/navigation";
import { addGuestCommunicationNote, getGuestCommunicationWorkspaceRequest, saveGuestCommunicationDraft } from "@/app/actions/guest-communications";

export default async function ConversationPage({ params }: { params: Promise<{ conversationId: string }> }) {
  const { conversationId } = await params;
  const result = await getGuestCommunicationWorkspaceRequest(conversationId);
  if (!result.ok) {
    if (result.code === "conversation_not_found") notFound();
    return <div role="alert" className="mx-auto mt-10 max-w-3xl rounded-2xl border border-amber-200 bg-amber-50 p-6">This conversation is unavailable or permission-limited.</div>;
  }
  const { reservation } = result;
  return <div className="mx-auto max-w-7xl space-y-6 py-8">
    <header><Link href="/dashboard/communications" className="text-sm font-semibold text-amber-800 hover:underline">← Inbox</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-700">{result.conversation.channel} · {result.conversation.status.replaceAll("-", " ")}</p><h1 className="mt-1 text-3xl font-semibold text-stone-950">{reservation.guest.name.display}</h1><p className="mt-1 text-stone-600">{reservation.property.name} · {reservation.reservationId}</p></div><span className="rounded-full border border-stone-300 px-3 py-1 text-sm text-stone-700">{reservation.freshness.status} context</span></div></header>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.7fr)_minmax(18rem,1fr)]">
      <main className="space-y-6">
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Communication timeline</h2>{result.messages.length === 0 && result.timeline.length === 0 ? <p className="mt-4 text-sm text-stone-500">No synchronized messages are available yet.</p> : <ol className="mt-4 space-y-4">{result.messages.map((message: Record<string, unknown>) => <li key={String(message.id)} className="rounded-xl bg-stone-50 p-4"><div className="flex justify-between gap-4 text-xs text-stone-500"><span className="font-semibold uppercase">{String(message.sender_display_name)}</span><span>{new Date(String(message.created_at)).toLocaleString()}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-stone-800">{String(message.body)}</p><span className="mt-2 inline-block text-xs capitalize text-stone-500">{String(message.delivery_status)}</span></li>)}</ol>}</section>
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Reply workspace</h2><p className="mt-1 text-sm text-stone-600">Drafts and scheduled messages require operator review. Provider delivery remains authoritative.</p><form action={saveGuestCommunicationDraft} className="mt-4 space-y-3"><input type="hidden" name="conversationId" value={conversationId} /><label className="block text-sm font-medium">Template<select name="templateId" className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2"><option value="">Start without a template</option>{result.templates.map((template: Record<string, unknown>) => <option key={String(template.id)} value={String(template.id)}>{String(template.title)}</option>)}</select></label><label className="block text-sm font-medium">Reviewed message<textarea required name="body" rows={6} maxLength={10000} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2" placeholder="Write a reply or adapt a template…" /></label><label className="block text-sm font-medium">Schedule for (optional)<input type="datetime-local" name="scheduledFor" className="mt-1 block rounded-xl border border-stone-300 px-3 py-2" /></label><button className="rounded-xl bg-stone-950 px-5 py-2 text-sm font-semibold text-white">Save reviewed draft</button></form></section>
      </main>
      <aside className="space-y-6">
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Reservation</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-stone-500">Stay</dt><dd>{reservation.stay.window.arrivalDate} – {reservation.stay.window.departureDate}</dd></div><div><dt className="text-stone-500">Guests</dt><dd>{reservation.party.totalGuests ?? "Unknown"} · {reservation.stay.stage.replaceAll("-", " ")}</dd></div><div><dt className="text-stone-500">Booking source</dt><dd>{reservation.source.bookingSource}</dd></div><div><dt className="text-stone-500">Check-in / checkout</dt><dd>{reservation.stay.window.checkInTime} / {reservation.stay.window.checkoutTime}</dd></div></dl></section>
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Guidebook</h2>{result.guidebook?<><p className="mt-2 text-sm text-stone-600">{result.guidebook.title} · Version {result.guidebook.published_version}</p><Link href={result.guidebook.publicUrl} className="mt-3 inline-block text-sm font-semibold text-amber-800 hover:underline">Open published Guidebook →</Link><p className="mt-2 break-all rounded-lg bg-stone-50 p-2 text-xs text-stone-600">{result.guidebook.publicUrl}</p></>:<p className="mt-2 text-sm text-stone-600">No published Guidebook is available for this property.</p>}</section>
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Private notes</h2><p className="mt-1 text-xs text-stone-500">Never visible to guests.</p>{result.notes.map((note: Record<string, unknown>) => <p key={String(note.id)} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-stone-800">{String(note.body)}</p>)}<form action={addGuestCommunicationNote} className="mt-4 space-y-3"><input type="hidden" name="conversationId" value={conversationId} /><textarea required name="body" rows={3} maxLength={5000} className="block w-full rounded-xl border border-stone-300 px-3 py-2" placeholder="Add an internal note…" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="pinned" /> Pin note</label><button className="rounded-xl border border-stone-300 px-4 py-2 text-sm font-semibold">Add note</button></form></section>
        <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Linked actions</h2><p className="mt-2 text-sm text-stone-600">{result.actionLinks.length ? `${result.actionLinks.length} Action Center item(s) linked.` : "No Action Center items linked."}</p><Link href="/dashboard/actions" className="mt-3 inline-block text-sm font-semibold text-amber-800 hover:underline">Open Action Center →</Link></section>
      </aside>
    </div>
  </div>;
}
