import { describe, expect, it, vi } from "vitest";
import { ExecuteAdminFurnishingAction, GetAdminFurnishingPurchaseOperations, type AdminFurnishingOperations } from "./admin-furnishing-operations";

const purchase: AdminFurnishingOperations = { purchaseId: "purchase-1", customer: { id: "customer-1", name: "Synthetic" }, workspace: { id: "workspace-1", tenantId: "tenant-1" }, offer: { id: "FS-CONSULT", version: 1, name: "Furnishing Consultation", amountMinor: 24900, currency: "USD", billingModel: "one_time" }, checkout: { id: "attempt-1", status: "session_created", createdAt: "2026-08-25", expiresAt: "2026-08-26" }, payment: { status: "payment_verified", amountPaidMinor: 24900, amountRefundedMinor: 0, remainingRefundableMinor: 24900 }, entitlement: { id: "ent-1", status: "active", activatedAt: "2026-08-25" }, handoff: { status: "pending_fs008c", available: true }, project: { exists: false }, version: 1, availableActions: ["retry_reconciliation", "suspend", "revoke", "request_refund"], audit: [] };
function setup(admin = true) { let current = purchase; const audits: unknown[] = []; const repo = { findPurchase: vi.fn(async () => current), transact: async (work: (tx: unknown) => Promise<unknown>) => work({ apply: async () => { current = { ...current, version: current.version + 1, availableActions: [] }; return current; }, audit: async (value: unknown) => { audits.push(value); } }) }; const auth = { isAdmin: async () => admin }; return { repo, audits, get: () => current, read: new GetAdminFurnishingPurchaseOperations(repo as never, auth), write: new ExecuteAdminFurnishingAction(repo as never, auth) }; }

describe("FS-008B P2.7 Admin operations", () => {
  it("returns complete safe lineage and explicit no-project state", async () => { const s = setup(); const result = await s.read.execute({ actorId: "admin", purchaseId: "purchase-1" }); expect(result.project.exists).toBe(false); expect(result.offer.version).toBe(1); expect(result.payment.remainingRefundableMinor).toBe(24900); });
  it("denies non-Admin projection and commands", async () => { const s = setup(false); await expect(s.read.execute({ actorId: "owner", purchaseId: "purchase-1" })).rejects.toThrow(); await expect(s.write.execute({ actorId: "owner", purchaseId: "purchase-1", action: "suspend", expectedVersion: 1, reason: "hold", idempotencyKey: "k", confirmed: true })).rejects.toThrow(); });
  it("requires confirmation, reason, expected version, and allowed action", async () => { const s = setup(); await expect(s.write.execute({ actorId: "admin", purchaseId: "purchase-1", action: "suspend", expectedVersion: 1, reason: "", idempotencyKey: "k", confirmed: true })).rejects.toThrow(); await expect(s.write.execute({ actorId: "admin", purchaseId: "purchase-1", action: "suspend", expectedVersion: 9, reason: "hold", idempotencyKey: "k", confirmed: true })).rejects.toThrow(); await expect(s.write.execute({ actorId: "admin", purchaseId: "purchase-1", action: "reinstate", expectedVersion: 1, reason: "restore", idempotencyKey: "k", confirmed: true })).rejects.toThrow(); });
  it("executes canonical suspension once and audits it", async () => { const s = setup(); const result = await s.write.execute({ actorId: "admin", purchaseId: "purchase-1", action: "suspend", expectedVersion: 1, reason: "dispute review", idempotencyKey: "k", confirmed: true }); expect(result.version).toBe(2); expect(s.audits).toHaveLength(1); });
  it("prohibits direct grant and downstream effects", async () => { const s = setup(); await expect(s.write.execute({ actorId: "admin", purchaseId: "purchase-1", action: "direct_grant" as never, expectedVersion: 1, reason: "grant", idempotencyKey: "k", confirmed: true })).rejects.toThrow(); expect(s.get().project.exists).toBe(false); });
});
