import { validateOfferSelection } from "./ca001a-entitlements";
import { validateBillingPriceMapping,type BillingProductionConfiguration } from "./ca001b-configuration";
import { BillingActivationError,type BillingPriceMapping,type CheckoutAttempt,type CommercialAgreement,type StripeCustomerAssociation } from "../domain/ca001b-billing";
import type { CustomerAccount } from "../domain/ca001a-entitlement";
import type { OfferDefinition } from "../domain/commercial-catalog";

export interface BillingCheckoutRepository{findAttemptByIdempotencyHash(hash:string):Promise<CheckoutAttempt|null>;insertAttempt(attempt:CheckoutAttempt):Promise<void>;attachSession(input:Readonly<{attemptId:string;customerReference:string;sessionReference:string;expiresAt:string;expectedRevision:number}>):Promise<CheckoutAttempt>;findActiveAgreement(customerAccountId:string,offerCode:string):Promise<CommercialAgreement|null>;findCustomerAssociations(customerAccountId:string,mode:"test"|"live"):Promise<readonly StripeCustomerAssociation[]>;saveCustomerAssociation(value:StripeCustomerAssociation):Promise<void>}
export interface BillingCatalog{getOffer(code:string,version:number):Promise<OfferDefinition|null>;getPriceMappings(code:string,version:number):Promise<readonly BillingPriceMapping[]>;getActiveOffers(customerAccountId:string):Promise<readonly Readonly<{code:string;version:number}>[]>}
export interface BillingCheckoutAuthorization{authorize(input:Readonly<{actorId:string;tenantId:string;customerAccountId:string}>):Promise<Readonly<{account:CustomerAccount;customerType:OfferDefinition["customerType"]}>|null>}
export interface BillingCheckoutProvider{createCustomer(input:Readonly<{customerAccountId:string;idempotencyKey:string}>):Promise<{id:string;mode:"test"|"live"}>;createSession(input:Readonly<{mode:"payment"|"subscription";customerId:string;priceId:string;successUrl:string;cancelUrl:string;expiresAt:number;metadata:Readonly<Record<string,string>>;idempotencyKey:string}>):Promise<Readonly<{id:string;url:string;expiresAt:string;mode:"test"|"live"}>>}
export type CheckoutCreationResult=Readonly<{attemptId:string;url:string;expiresAt:string}>;

export class CreateOfferCheckout{
 constructor(private readonly dependencies:Readonly<{configuration:BillingProductionConfiguration;repository:BillingCheckoutRepository;catalog:BillingCatalog;authorization:BillingCheckoutAuthorization;provider:BillingCheckoutProvider;hashIdempotency:(value:string)=>Promise<string>;now?:()=>Date}>){ }
 async execute(input:Readonly<{actorId:string;tenantId:string;customerAccountId:string;offerCode:string;offerVersion:number;billingCadence?:"month"|"year";correlationId:string;idempotencyKey:string}>):Promise<CheckoutCreationResult>{
  const {configuration}=this.dependencies;if(!configuration.checkoutEnabled)fail("CHECKOUT_DISABLED","Checkout is unavailable.");
  const auth=await this.dependencies.authorization.authorize(input);if(!auth||auth.account.tenantId!==input.tenantId||auth.account.status!=="active")fail("CUSTOMER_NOT_ELIGIBLE","This account cannot purchase the offer.");
  const offer=await this.dependencies.catalog.getOffer(input.offerCode,input.offerVersion);if(!offer||offer.status!=="active")fail("OFFER_VERSION_INACTIVE","The offer version is unavailable.");
  if(offer.acquisitionMode!=="self_service"||offer.billingModel==="custom_quote"||offer.billingModel==="usage_based")fail("OFFER_NOT_PURCHASABLE","This offer requires assisted purchase.");
  if(offer.billingModel==="recurring"&&!configuration.subscriptionsEnabled||offer.billingModel==="one_time"&&!configuration.oneTimePaymentsEnabled)fail("BILLING_MODEL_UNSUPPORTED","This billing model is unavailable.");
  const activeOffers=await this.dependencies.catalog.getActiveOffers(input.customerAccountId),selection=validateOfferSelection(offer,{customerAccountId:input.customerAccountId,customerType:auth.customerType,offerCode:offer.code,offerVersion:offer.version,activationChannel:"self_service",activeOffers});
  if(!selection.valid)fail(selection.reason==="prerequisite_missing"?"OFFER_PREREQUISITE_MISSING":selection.reason==="offer_incompatible"?"OFFER_CONFLICT":"CUSTOMER_NOT_ELIGIBLE","The offer selection is unavailable.");
  if(await this.dependencies.repository.findActiveAgreement(input.customerAccountId,offer.code))fail("COMMERCIAL_AGREEMENT_CONFLICT","An active agreement already exists.");
  const mappings=(await this.dependencies.catalog.getPriceMappings(offer.code,offer.version)).filter(value=>(!input.billingCadence||value.interval===input.billingCadence)&&value.stripeAccountMode===configuration.stripeAccountMode&&value.status==="active");
  if(mappings.length!==1)fail("BILLING_PRICE_MAPPING_MISSING","An approved price is unavailable.");const mapping=validateBillingPriceMapping(offer,mappings[0],configuration.stripeAccountMode);
  const hash=await this.dependencies.hashIdempotency(input.idempotencyKey),existing=await this.dependencies.repository.findAttemptByIdempotencyHash(hash);if(existing?.stripeCheckoutSessionReference)fail("CHECKOUT_ATTEMPT_CONFLICT","This Checkout attempt already has a session.");
  const now=this.dependencies.now?.()??new Date(),expiresAt=new Date(now.getTime()+configuration.checkoutSessionTtlSeconds*1000).toISOString();
  const attempt=existing??Object.freeze({id:crypto.randomUUID(),tenantId:input.tenantId,customerAccountId:input.customerAccountId,offerCode:offer.code,offerVersion:offer.version,billingPriceMappingId:mapping.id,mode:offer.billingModel==="recurring"?"subscription"as const:"payment"as const,status:"created"as const,idempotencyKeyHash:hash,correlationId:input.correlationId,createdAt:now.toISOString(),expiresAt,revision:1});if(!existing)await this.dependencies.repository.insertAttempt(attempt);
  const associations=await this.dependencies.repository.findCustomerAssociations(input.customerAccountId,configuration.stripeAccountMode);if(associations.length>1||associations.some(value=>value.status==="ambiguous"))fail("STRIPE_CUSTOMER_MAPPING_AMBIGUOUS","Billing identity requires review.");
  let association=associations[0];if(!association){const customer=await this.dependencies.provider.createCustomer({customerAccountId:input.customerAccountId,idempotencyKey:`${hash}:customer`});if(customer.mode!==configuration.stripeAccountMode)fail("BILLING_ENVIRONMENT_MISMATCH","Billing environment mismatch.");association=Object.freeze({id:crypto.randomUUID(),tenantId:input.tenantId,customerAccountId:input.customerAccountId,accountMode:configuration.stripeAccountMode,stripeCustomerReference:customer.id,status:"active",createdAt:now.toISOString(),revision:1});await this.dependencies.repository.saveCustomerAssociation(association)}
  const session=await this.dependencies.provider.createSession({mode:attempt.mode,customerId:association.stripeCustomerReference,priceId:mapping.stripePriceId,successUrl:`${configuration.checkoutSuccessUrl}?attempt=${encodeURIComponent(attempt.id)}`,cancelUrl:`${configuration.checkoutCancelUrl}?attempt=${encodeURIComponent(attempt.id)}`,expiresAt:Math.floor(Date.parse(expiresAt)/1000),metadata:{checkout_attempt_id:attempt.id,customer_account_id:input.customerAccountId,offer_code:offer.code,offer_version:String(offer.version),correlation_id:input.correlationId},idempotencyKey:`${hash}:session`});
  if(session.mode!==configuration.stripeAccountMode)fail("BILLING_ENVIRONMENT_MISMATCH","Billing environment mismatch.");await this.dependencies.repository.attachSession({attemptId:attempt.id,customerReference:association.stripeCustomerReference,sessionReference:session.id,expiresAt:session.expiresAt,expectedRevision:attempt.revision});return Object.freeze({attemptId:attempt.id,url:session.url,expiresAt:session.expiresAt});
 }
}
function fail(code:ConstructorParameters<typeof BillingActivationError>[0],message:string):never{throw new BillingActivationError(code,message)}

export interface BillingPortalAuthorization{authorize(input:Readonly<{actorId:string;tenantId:string;customerAccountId:string}>):Promise<boolean>}
export class CreateCustomerBillingPortal{constructor(private readonly dependencies:Readonly<{configuration:BillingProductionConfiguration;authorization:BillingPortalAuthorization;repository:Pick<BillingCheckoutRepository,"findCustomerAssociations">;provider:{createPortal(input:Readonly<{customerId:string;returnUrl:string;idempotencyKey:string}>):Promise<{url:string;expiresAt?:string}>}}>){}async execute(input:Readonly<{actorId:string;tenantId:string;customerAccountId:string;correlationId:string}>){if(!this.dependencies.configuration.customerPortalEnabled)fail("CUSTOMER_PORTAL_UNAVAILABLE","Billing support is currently unavailable.");if(!await this.dependencies.authorization.authorize(input))fail("CUSTOMER_PORTAL_UNAVAILABLE","Billing support is currently unavailable.");const values=await this.dependencies.repository.findCustomerAssociations(input.customerAccountId,this.dependencies.configuration.stripeAccountMode);if(values.length!==1||values[0].status!=="active"||values[0].tenantId!==input.tenantId)fail("CUSTOMER_PORTAL_UNAVAILABLE","Billing support is currently unavailable.");return this.dependencies.provider.createPortal({customerId:values[0].stripeCustomerReference,returnUrl:this.dependencies.configuration.customerPortalReturnUrl,idempotencyKey:`portal:${input.correlationId}`})}}
