import { BillingActivationError,FAILED_PAYMENT_POLICY,mapStripeSubscriptionStatus,type AgreementStatus,type BillingProviderEvent,type CommercialAgreement } from "../domain/ca001b-billing";

export type VerifiedCommercialEvent=Readonly<{providerEventId:string;accountMode:"test"|"live";eventType:string;occurredAt:string;providerCustomerReference:string;providerAgreementReference?:string;checkoutAttemptId?:string;subscriptionStatus?:string;invoicePaid?:boolean;paymentSucceeded?:boolean;cancelAtPeriodEnd?:boolean;periodStart?:string;periodEnd?:string}>;
export interface CommercialLifecycleRepository{claimEvent(event:BillingProviderEvent):Promise<"claimed"|"duplicate">;findAttempt(id:string):Promise<Readonly<{id:string;tenantId:string;customerAccountId:string;offerCode:string;offerVersion:number;billingPriceMappingId:string;mode:"payment"|"subscription";stripeCustomerReference?:string;status:string}>|null>;findAgreementByAttempt(id:string):Promise<CommercialAgreement|null>;saveAgreement(agreement:CommercialAgreement,eventId:string):Promise<CommercialAgreement>;markEvent(id:string,status:BillingProviderEvent["status"],failureCode?:string):Promise<void>;hasActivatedEntitlements(agreementId:string):Promise<boolean>;activateEntitlements(input:Readonly<{agreement:CommercialAgreement;idempotencyKey:string}>):Promise<void>;transitionSourceEntitlements(input:Readonly<{agreementId:string;action:"suspend"|"restore"|"expire";effectiveAt:string;idempotencyKey:string}>):Promise<void>}

export class ProcessVerifiedCommercialEvent{constructor(private readonly dependencies:Readonly<{mode:"test"|"live";repository:CommercialLifecycleRepository;checksum:(value:string)=>Promise<string>;now?:()=>Date}>){ }async execute(event:VerifiedCommercialEvent):Promise<Readonly<{status:"processed"|"duplicate"|"ignored";agreementId?:string}>>{
 if(event.accountMode!==this.dependencies.mode)throw new BillingActivationError("BILLING_ENVIRONMENT_MISMATCH","Provider event environment mismatch.");const now=this.dependencies.now?.()??new Date(),correlationId=event.checkoutAttemptId??`provider:${event.providerEventId}`,ledger:BillingProviderEvent=Object.freeze({id:crypto.randomUUID(),provider:"stripe",providerEventId:event.providerEventId,eventType:event.eventType,accountMode:event.accountMode,status:"received",receivedAt:now.toISOString(),correlationId,attemptCount:0,payloadChecksum:await this.dependencies.checksum(`${event.providerEventId}:${event.eventType}:${event.occurredAt}`),revision:1});
 if(await this.dependencies.repository.claimEvent(ledger)==="duplicate")return{status:"duplicate"};
 if(!["checkout.session.completed","invoice.paid","invoice.payment_failed","invoice.payment_action_required","customer.subscription.created","customer.subscription.updated","customer.subscription.deleted","payment_intent.succeeded","payment_intent.payment_failed","checkout.session.expired","charge.refunded","charge.dispute.created"].includes(event.eventType)){await this.dependencies.repository.markEvent(ledger.id,"ignored","WEBHOOK_EVENT_UNSUPPORTED");return{status:"ignored"}}
 try{if(!event.checkoutAttemptId)throw new BillingActivationError("RECONCILIATION_REQUIRED","The provider event is not linked to an approved attempt.");const attempt=await this.dependencies.repository.findAttempt(event.checkoutAttemptId);if(!attempt||attempt.stripeCustomerReference!==event.providerCustomerReference)throw new BillingActivationError("RECONCILIATION_REQUIRED","The provider event could not be reconciled.");let agreement=await this.dependencies.repository.findAgreementByAttempt(attempt.id);const status=agreementStatus(event,attempt.mode,agreement?.status);const timestamp=event.occurredAt;agreement=Object.freeze({...(agreement??{id:crypto.randomUUID(),tenantId:attempt.tenantId,customerAccountId:attempt.customerAccountId,offerCode:attempt.offerCode,offerVersion:attempt.offerVersion,billingPriceMappingId:attempt.billingPriceMappingId,agreementType:attempt.mode==="subscription"?"subscription"as const:"one_time_purchase"as const,provider:"stripe"as const,providerCustomerReference:event.providerCustomerReference,createdAt:timestamp,revision:0}),status,...(event.providerAgreementReference?{providerAgreementReference:event.providerAgreementReference}:{}),...(event.periodStart?{currentPeriodStart:event.periodStart}:{}),...(event.periodEnd?{currentPeriodEnd:event.periodEnd}:{}),...(event.cancelAtPeriodEnd!==undefined?{cancelAtPeriodEnd:event.cancelAtPeriodEnd}:{}),...(status==="active"&&!agreement?.activatedAt?{activatedAt:timestamp}:{}),updatedAt:timestamp,revision:(agreement?.revision??0)+1});agreement=await this.dependencies.repository.saveAgreement(agreement,event.providerEventId);
  if(status==="active"&&(event.invoicePaid||attempt.mode==="payment"&&event.paymentSucceeded)&&!await this.dependencies.repository.hasActivatedEntitlements(agreement.id))await this.dependencies.repository.activateEntitlements({agreement,idempotencyKey:`agreement:${agreement.id}:activate`});
  if(status==="paused"||status==="disputed")await this.dependencies.repository.transitionSourceEntitlements({agreementId:agreement.id,action:"suspend",effectiveAt:timestamp,idempotencyKey:`agreement:${agreement.id}:${status}`});
  if(status==="cancelled"||status==="expired"||status==="refunded")await this.dependencies.repository.transitionSourceEntitlements({agreementId:agreement.id,action:"expire",effectiveAt:event.periodEnd??timestamp,idempotencyKey:`agreement:${agreement.id}:${status}`});
  if(status==="active"&&event.invoicePaid)await this.dependencies.repository.transitionSourceEntitlements({agreementId:agreement.id,action:"restore",effectiveAt:timestamp,idempotencyKey:`agreement:${agreement.id}:restore:${event.providerEventId}`});await this.dependencies.repository.markEvent(ledger.id,"processed");return{status:"processed",agreementId:agreement.id};
 }catch(error){await this.dependencies.repository.markEvent(ledger.id,"failed",error instanceof BillingActivationError?error.code:"RECONCILIATION_REQUIRED");throw error}}
}
function agreementStatus(event:VerifiedCommercialEvent,mode:"payment"|"subscription",prior?:AgreementStatus):AgreementStatus{if(event.eventType==="charge.refunded")return"refunded";if(event.eventType==="charge.dispute.created")return"disputed";if(event.eventType==="invoice.payment_action_required")return"payment_action_required";if(event.eventType==="invoice.payment_failed")return prior==="active"?"past_due":"pending";if(event.eventType==="customer.subscription.deleted")return"cancelled";if(mode==="subscription"&&event.subscriptionStatus)return mapStripeSubscriptionStatus(event.subscriptionStatus,Boolean(event.cancelAtPeriodEnd));if(event.invoicePaid||event.paymentSucceeded)return"active";return prior??"pending"}

export interface ReconciliationProvider{retrieveAgreement(reference:string):Promise<Readonly<{status:string;cancelAtPeriodEnd:boolean;periodEnd?:string;initialInvoicePaid:boolean}>>;}
export class ReconcileCommercialAgreement{constructor(private readonly dependencies:Readonly<{repository:Pick<CommercialLifecycleRepository,"hasActivatedEntitlements"|"activateEntitlements"|"transitionSourceEntitlements">;provider:ReconciliationProvider;authorize:(actorId:string)=>Promise<boolean>}>){ }async execute(input:Readonly<{agreement:CommercialAgreement;initiatedBy:string;reason:string;correlationId:string}>){if(!await this.dependencies.authorize(input.initiatedBy)||!input.reason.trim())throw new BillingActivationError("RECONCILIATION_REQUIRED","Reconciliation requires an authorized reason.");if(!input.agreement.providerAgreementReference)throw new BillingActivationError("RECONCILIATION_REQUIRED","The agreement lacks a provider reference.");const state=await this.dependencies.provider.retrieveAgreement(input.agreement.providerAgreementReference),status=mapStripeSubscriptionStatus(state.status,state.cancelAtPeriodEnd);if(status==="active"&&state.initialInvoicePaid&&!await this.dependencies.repository.hasActivatedEntitlements(input.agreement.id))await this.dependencies.repository.activateEntitlements({agreement:input.agreement,idempotencyKey:`reconcile:${input.agreement.id}:activate`});if(["cancelled","expired","paused"].includes(status))await this.dependencies.repository.transitionSourceEntitlements({agreementId:input.agreement.id,action:status==="paused"?"suspend":"expire",effectiveAt:state.periodEnd??new Date().toISOString(),idempotencyKey:`reconcile:${input.agreement.id}:${status}`});return Object.freeze({agreementId:input.agreement.id,status,policy:FAILED_PAYMENT_POLICY,correlationId:input.correlationId})}}
