import { describe, expect, it } from "vitest";
import { ProcessFurnishingPaymentEvent, type FurnishingPaymentEventRecord, type VerifiedFurnishingProviderEvent } from "./furnishing-payment-events";

const attempt = { id: "attempt-1", productFamily: "furnishing" as const, actorId: "u1", customerAccountId: "acct-1", tenantId: "tenant-1", workspaceId: "workspace-1", offerId: "FS-CONSULT", offerVersion: 1, amountMinor: 24900, currency: "USD", billingModel: "one_time" as const, providerProductId: "prod-fs", providerPriceId: "price-fs", providerSessionId: "cs-1", status: "session_created" };
const event = (extra: Partial<VerifiedFurnishingProviderEvent> = {}): VerifiedFurnishingProviderEvent => ({ providerEventId: "evt-1", eventType: "payment_intent.succeeded", accountMode: "test", providerAccountId: "acct_platform_test", signatureVerified: true, occurredAt: "2026-08-25T20:00:00Z", checkoutAttemptId: "attempt-1", providerSessionId: "cs-1", providerPaymentId: "pi-1", providerCustomerReference: "cus-1", providerProductId: "prod-fs", providerPriceId: "price-fs", amountMinor: 24900, currency: "USD", paymentStatus: "succeeded", productFamily: "furnishing", offerId: "FS-CONSULT", offerVersion: 1, customerAccountId: "acct-1", tenantId: "tenant-1", workspaceId: "workspace-1", billingModel: "one_time", contentChecksum: "checksum-1", ...extra });
function setup() { const events = new Map<string, FurnishingPaymentEventRecord>(); const repo = { findEvent: async (id: string, mode: "test" | "live") => events.get(`${mode}:${id}`) ?? null, persistEvent: async (value: FurnishingPaymentEventRecord) => { events.set(`${value.accountMode}:${value.providerEventId}`, value); }, findAttempt: async (id: string) => id === attempt.id ? attempt : null }; return { repo, events, operation: new ProcessFurnishingPaymentEvent({ repository: repo, expectedAccountId: "acct_platform_test", expectedMode: "test" }) }; }

describe("FS-008B P2.3 payment event validation", () => {
  it("accepts a verified successful payment without entitlement effects", async () => { const { operation, events } = setup(); const result = await operation.execute(event(), "corr-1"); expect(result.status).toBe("payment_verified"); expect([...events.values()][0].status).toBe("payment_verified"); });
  it("maps processing and failed payments without activating", async () => { const first = setup(); expect((await first.operation.execute(event({ eventType: "payment_intent.processing", paymentStatus: "processing" }), "c")).status).toBe("payment_processing"); const second = setup(); expect((await second.operation.execute(event({ eventType: "payment_intent.payment_failed", paymentStatus: "failed" }), "c")).status).toBe("payment_failed"); });
  it.each([{ providerAccountId: "wrong" }, { accountMode: "live" as const }, { amountMinor: 1 }, { currency: "EUR" }, { offerId: "FS-DESIGN" }, { offerVersion: 2 }, { customerAccountId: "other" }, { tenantId: "other" }, { workspaceId: "other" }, { providerPriceId: "price-other" }, { productFamily: "furnishing" as const, billingModel: "one_time" as const, providerProductId: "prod-other" }])("rejects mismatched event %o", async override => { const { operation, events } = setup(); const result = await operation.execute(event(override), "c"); expect(result.status).toBe("event_rejected"); expect([...events.values()][0].status).toBe("rejected"); });
  it("rejects unsupported, unknown-attempt, and unsigned events", async () => { const a = setup(); expect((await a.operation.execute(event({ eventType: "customer.created" }), "c")).status).toBe("event_unsupported"); const b = setup(); expect((await b.operation.execute(event({ checkoutAttemptId: undefined }), "c")).status).toBe("event_rejected"); const c = setup(); await expect(c.operation.execute(event({ signatureVerified: false as true }), "c")).rejects.toThrow(); });
  it("returns exact replay and rejects reused event IDs with changed content", async () => { const { operation } = setup(); expect((await operation.execute(event(), "c")).status).toBe("payment_verified"); expect((await operation.execute(event(), "c")).status).toBe("event_replayed"); expect((await operation.execute(event({ contentChecksum: "changed" }), "c")).status).toBe("terminal_conflict"); });
  it("keeps payment verification free of entitlement, project, notification, and provider effects", async () => { const { operation, repo } = setup(); await operation.execute(event(), "c"); expect(repo).not.toHaveProperty("activateEntitlements"); expect(repo).not.toHaveProperty("createProject"); });
});
