import { describe, expect, it, vi } from "vitest";
import { CreateFurnishingCheckout, type FurnishingCheckoutAttempt } from "./furnishing-checkout";
import type { FurnishingProviderReference } from "./furnishing-offers";

const providerRef: FurnishingProviderReference = { productId: "prod_fs", priceId: "price_fs", accountMode: "test" };
const activation = { globalKillSwitch: false, globalState: "internal" as const, workspaceKillSwitch: false, workspaceEnabled: true, cohortEligible: true, capabilityEnabled: true, configurationValid: true, policyVersion: "fs008a-v1" };
function setup(overrides: Record<string, unknown> = {}) {
  let attempt: FurnishingCheckoutAttempt | null = null; const provider = { createSession: vi.fn(async () => ({ id: "cs_test", url: "https://checkout.stripe.test/cs_test", expiresAt: "2026-08-25T21:00:00Z" })) };
  const repo = { findByIdempotencyHash: vi.fn(async () => attempt), insert: vi.fn(async (v: FurnishingCheckoutAttempt) => { attempt = v; }), attachSession: vi.fn(async (v: { attemptId: string; providerSessionId: string; providerSessionUrl: string; expiresAt: string }) => { attempt = { ...attempt!, providerSessionId: v.providerSessionId, providerSessionUrl: v.providerSessionUrl, status: "session_created" }; return attempt!; }) };
  const operation = new CreateFurnishingCheckout({ repository: repo, provider, hashIdempotency: async (value: string) => `hash:${value}`, authorization: { authorize: async ({ actor }: { actor: { role: string } }) => actor.role === "owner" || actor.role === "customer" ? { actorId: "user-1", tenantId: "tenant-1", customerAccountId: "account-1", role: actor.role as "owner" | "customer" } : null }, resolveActivation: (x: any) => ({ allowed: !x.globalKillSwitch && x.globalState !== "disabled" && !x.workspaceKillSwitch && x.workspaceEnabled && x.cohortEligible && x.capabilityEnabled, reason: "enabled" }), activation, providerReferences: { "FS-CONSULT": providerRef, "FS-DESIGN": providerRef }, ...overrides } as any);
  return { operation, repo, provider };
}
const request = (offerId = "FS-CONSULT", extra: Record<string, unknown> = {}) => ({ actor: { role: "owner" as const, userId: "user-1", tenantId: "tenant-1" }, workspaceId: "workspace-1", offerId, idempotencyKey: "key-1", ...extra });

describe("FS-008B P2.2 Furnishing checkout boundary", () => {
  it.each(["FS-CONSULT", "FS-DESIGN"])("creates a server-priced %s checkout", async offerId => { const { operation, provider, repo } = setup(); const result = await operation.execute(request(offerId)); expect(result.redirectUrl).toContain("stripe.test"); expect(provider.createSession).toHaveBeenCalledWith(expect.objectContaining({ providerPriceId: "price_fs", providerProductId: "prod_fs", metadata: expect.objectContaining({ product_family: "furnishing" }) })); expect(repo.insert).toHaveBeenCalledWith(expect.objectContaining({ productFamily: "furnishing", offerId, priceMinor: offerId === "FS-CONSULT" ? 24900 : 149500 })); });
  it.each([{ globalKillSwitch: true }, { globalState: "disabled" }, { workspaceKillSwitch: true }, { workspaceEnabled: false }, { cohortEligible: false }, { capabilityEnabled: false }])("denies activation state %o before provider effect", async override => { const { operation, provider, repo } = setup({ activation: { ...activation, ...override } }); await expect(operation.execute(request())).rejects.toThrow(); expect(provider.createSession).not.toHaveBeenCalled(); expect(repo.insert).not.toHaveBeenCalled(); });
  it.each([{ role: "anonymous" }, { role: "operator" }])("denies unauthorized %o", async actor => { const { operation, provider } = setup(); await expect(operation.execute(request("FS-CONSULT", { actor }))).rejects.toThrow(); expect(provider.createSession).not.toHaveBeenCalled(); });
  it.each(["FS-FULL", "legacy-furnishing", "unknown"]) ("denies %s", async offerId => { const { operation, provider } = setup(); await expect(operation.execute(request(offerId))).rejects.toThrow(); expect(provider.createSession).not.toHaveBeenCalled(); });
  it("rejects unsafe return context and stale version", async () => { const { operation } = setup(); await expect(operation.execute(request("FS-CONSULT", { returnContext: "https://evil.example" }))).rejects.toThrow(); await expect(operation.execute(request("FS-CONSULT", { offerVersion: 0 }))).rejects.toThrow(); });
  it("reuses exact idempotent session", async () => { const { operation, provider } = setup(); const first = await operation.execute(request()); const second = await operation.execute(request()); expect(second.redirectUrl).toBe(first.redirectUrl); expect(provider.createSession).toHaveBeenCalledTimes(1); });
  it("binds the attempt to tenant, workspace, price, policy, and correlation", async () => { const { operation, repo } = setup(); await operation.execute(request("FS-DESIGN")); expect(repo.insert).toHaveBeenCalledWith(expect.objectContaining({ tenantId: "tenant-1", workspaceId: "workspace-1", currency: "USD", policyVersion: "fs008a-v1", status: "requested" })); });
  it("does not create payment success, entitlement, project, notification, or downstream effects", async () => { const { operation, repo } = setup(); await operation.execute(request()); const saved = (repo.insert.mock.calls[0] as [FurnishingCheckoutAttempt])[0]; expect(saved.status).toBe("requested"); expect(saved).not.toHaveProperty("entitlementId"); expect(saved).not.toHaveProperty("projectId"); });
  it("preserves non-Furnishing CA-001 implementation untouched", () => expect(CreateFurnishingCheckout).toBeTypeOf("function"));
});
