import type { FurnishingActivationContext } from "./furnishing-offers";
import type { FurnishingOnboardingActor, FurnishingOnboardingSession } from "./furnishing-onboarding";
export type RoomDraft = Readonly<{ id: string; sessionId: string; propertyId: string; type: string; name: string; instance: number; priority: "high" | "normal" | "low"; inventory: "keep" | "replace" | "evaluate" | "none" | "unknown"; workspaceRequired: boolean; tvRequired: boolean; mountRequired: boolean; measurementStatus: "complete" | "missing" | "unknown"; photoStatus: "complete" | "missing" | "unknown"; version: number }>;
export type RoomOperation = Readonly<{ kind: "generate_defaults" | "add" | "update" | "remove" | "restore"; room?: Partial<RoomDraft> & { id?: string; type?: string; name?: string } }>;
export interface RoomRepository { findSession(id: string): Promise<FurnishingOnboardingSession | null>; listRooms(sessionId: string): Promise<readonly RoomDraft[]>; save(input: Readonly<{ session: FurnishingOnboardingSession; rooms: readonly RoomDraft[]; expectedVersion: number; idempotencyKey: string }>): Promise<FurnishingOnboardingSession>; audit(value: Readonly<Record<string, string>>): Promise<void>; }
const required = new Set(["bedroom", "bathroom", "living_room", "kitchen", "workspace"]);
export function generateFurnishingRooms(session: FurnishingOnboardingSession, bedrooms = 1, bathrooms = 1): readonly RoomDraft[] { const types = [...Array.from({ length: bedrooms }, () => "bedroom"), ...Array.from({ length: bathrooms }, () => "bathroom"), "living_room", "kitchen", "workspace"]; return types.map((type, index) => ({ id: `${session.id}:room:${index + 1}`, sessionId: session.id, propertyId: "resolved", type, name: type.replaceAll("_", " "), instance: types.slice(0, index + 1).filter(value => value === type).length, priority: type === "workspace" ? "high" : "normal", inventory: "unknown", workspaceRequired: type === "workspace", tvRequired: false, mountRequired: false, measurementStatus: "unknown", photoStatus: "unknown", version: 1 })); }
export class UpdateFurnishingRoomIntake {
  constructor(private readonly dependencies: Readonly<{ repository: RoomRepository; activation: FurnishingActivationContext }>) {}
  async execute(input: Readonly<{ actor: FurnishingOnboardingActor; onboardingSessionId: string; expectedVersion: number; operation: RoomOperation; idempotencyKey: string; correlationId: string }>): Promise<Readonly<{ status: "saved" | "denied" | "conflict"; rooms?: readonly RoomDraft[]; session?: FurnishingOnboardingSession }>> {
    const session = await this.dependencies.repository.findSession(input.onboardingSessionId); if (!session || session.customerId !== input.actor.userId || session.tenantId !== input.actor.tenantId || session.offerId !== "FS-DESIGN") return { status: "denied" }; if (session.status !== "in_progress" || session.version !== input.expectedVersion || this.dependencies.activation.globalKillSwitch || this.dependencies.activation.globalState === "disabled" || !this.dependencies.activation.capabilityEnabled) return { status: session.version !== input.expectedVersion ? "conflict" : "denied", session }; let rooms = [...await this.dependencies.repository.listRooms(session.id)]; const op = input.operation;
    if (op.kind === "generate_defaults" && !rooms.length) rooms = [...generateFurnishingRooms(session)];
    if (op.kind === "add" && op.room?.type && op.room.name) { const type = op.room.type; if (rooms.some(room => room.type === type && room.name === op.room!.name)) return { status: "conflict", rooms, session }; rooms.push({ ...generateFurnishingRooms(session, 0, 0)[0], id: `${session.id}:room:${rooms.length + 1}`, type, name: op.room.name, instance: rooms.filter(room => room.type === type).length + 1 }); }
    if (op.kind === "remove" && op.room?.id && required.has(rooms.find(room => room.id === op.room!.id)?.type ?? "")) return { status: "conflict", rooms, session };
    if (op.kind === "remove") rooms = rooms.filter(room => room.id !== op.room?.id); if (op.kind === "restore" && op.room?.id && !rooms.some(room => room.id === op.room!.id)) rooms.push({ ...generateFurnishingRooms(session, 0, 0)[0], id: op.room.id, type: op.room.type ?? "living_room", name: op.room.name ?? "Living room", instance: 1 }); if (op.kind === "update" && op.room?.id) rooms = rooms.map(room => room.id === op.room!.id ? { ...room, ...(op.room as Partial<RoomDraft>), version: room.version + 1 } : room);
    try { const updated = await this.dependencies.repository.save({ session, rooms, expectedVersion: input.expectedVersion, idempotencyKey: input.idempotencyKey }); await this.dependencies.repository.audit({ event: "furnishing_room_intake_saved", sessionId: session.id, correlationId: input.correlationId }); return { status: "saved", rooms, session: updated }; } catch { return { status: "conflict", rooms, session }; }
  }
}
