import { describe, expect, it } from "vitest";
import { resolveFurnishingOnboardingSchema, SaveFurnishingOnboardingStep, type FurnishingDraftRepository } from "./furnishing-onboarding-drafts";
import type { FurnishingOnboardingSession } from "./furnishing-onboarding";
const activation = { globalKillSwitch: false, globalState: "limited" as const, workspaceKillSwitch: false, workspaceEnabled: true, cohortEligible: true, capabilityEnabled: true, configurationValid: true, policyVersion: "v1" };
const session: FurnishingOnboardingSession = { id: "s", customerId: "u", tenantId: "t", entitlementId: "e", handoffId: "h", offerId: "FS-CONSULT", offerVersion: 1, schemaVersion: 1, projectType: "consultation", status: "in_progress", currentStep: "service_confirmation", completedSteps: [], propertyPath: "existing", version: 1, idempotencyKey: "k", correlationId: "c", createdAt: "now", updatedAt: "now" };
function op() { let current = session; const repo: FurnishingDraftRepository = { findSession: async () => current, saveStep: async ({ session: value }) => current = { ...value, version: value.version + 1 }, audit: async () => undefined }; return new SaveFurnishingOnboardingStep({ repository: repo, activation, onboardingEnabled: true }); }
describe("FS-008C offer-aware drafts", () => {
  it("resolves only supported schemas", () => { expect(resolveFurnishingOnboardingSchema({ offerId: "FS-CONSULT", offerVersion: 1, schemaVersion: 1 })?.steps).toHaveLength(11); expect(resolveFurnishingOnboardingSchema({ offerId: "FS-DESIGN", offerVersion: 1, schemaVersion: 1 })?.steps).toHaveLength(16); expect(resolveFurnishingOnboardingSchema({ offerId: "FS-FULL", offerVersion: 1, schemaVersion: 1 })).toBeNull(); });
  it("saves a validated step and increments the version", async () => { const result = await op().execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", stepId: "service_confirmation", expectedVersion: 1, values: { confirmed: true }, idempotencyKey: "i", correlationId: "c" }); expect(result.status).toBe("saved"); expect(result.session?.version).toBe(2); });
  it("rejects missing, unsupported, and stale input", async () => { const operation = op(); expect((await operation.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", stepId: "target_guest", expectedVersion: 1, values: {}, idempotencyKey: "i", correlationId: "c" })).status).toBe("invalid"); expect((await operation.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", stepId: "unknown", expectedVersion: 1, values: { unknown: "x" }, idempotencyKey: "i", correlationId: "c" })).status).toBe("invalid"); expect((await operation.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", stepId: "service_confirmation", expectedVersion: 9, values: { confirmed: true }, idempotencyKey: "i", correlationId: "c" })).status).toBe("conflict"); });
  it("sanitizes text and preserves no customer answers in telemetry", async () => { const result = await op().execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", stepId: "service_confirmation", expectedVersion: 1, values: { confirmed: true, note: "<b>safe</b>" }, idempotencyKey: "i", correlationId: "c" }); expect(result.status).toBe("invalid"); });
});
