import type { FurnishingActivationContext } from "./furnishing-offers";
import type { FurnishingOnboardingActor, FurnishingOnboardingSession } from "./furnishing-onboarding";
export type FurnishingUploadPurpose = "property_photo" | "room_photo" | "floor_plan" | "measurement_document" | "existing_inventory_photo" | "listing_reference" | "design_inspiration" | "other_approved_reference";
export type FurnishingUpload = Readonly<{ id: string; tenantId: string; sessionId: string; propertyId: string; roomId?: string; purpose: FurnishingUploadPurpose; filename: string; objectKey: string; mimeType: string; size: number; state: "requested" | "uploading" | "uploaded" | "validating" | "available" | "rejected" | "failed" | "removed" | "expired"; version: number }>;
export type UploadResult = Readonly<{ status: "requested" | "available" | "denied" | "invalid" | "conflict"; upload?: FurnishingUpload; reason?: string }>;
const policy: Record<FurnishingUploadPurpose, Readonly<{ mimes: readonly string[]; max: number; room: boolean }>> = { property_photo: { mimes: ["image/jpeg", "image/png", "image/webp"], max: 10_000_000, room: false }, room_photo: { mimes: ["image/jpeg", "image/png", "image/webp"], max: 10_000_000, room: true }, floor_plan: { mimes: ["application/pdf", "image/jpeg", "image/png"], max: 20_000_000, room: false }, measurement_document: { mimes: ["application/pdf", "image/jpeg", "image/png"], max: 20_000_000, room: false }, existing_inventory_photo: { mimes: ["image/jpeg", "image/png", "image/webp"], max: 10_000_000, room: true }, listing_reference: { mimes: ["application/pdf", "text/plain"], max: 5_000_000, room: false }, design_inspiration: { mimes: ["image/jpeg", "image/png", "application/pdf"], max: 20_000_000, room: false }, other_approved_reference: { mimes: ["application/pdf", "image/jpeg", "image/png"], max: 20_000_000, room: false } };
export interface FurnishingUploadRepository { findSession(id: string): Promise<FurnishingOnboardingSession | null>; findUploadByIdempotency(key: string): Promise<FurnishingUpload | null>; create(value: FurnishingUpload): Promise<FurnishingUpload>; finalize(id: string, actualSize: number, version: number): Promise<FurnishingUpload>; audit(value: Readonly<Record<string, string>>): Promise<void>; }
const safeName = (name: string) => name.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 180);
export class RequestFurnishingIntakeUpload {
  constructor(private readonly dependencies: Readonly<{ repository: FurnishingUploadRepository; activation: FurnishingActivationContext }>) {}
  async execute(input: Readonly<{ actor: FurnishingOnboardingActor; onboardingSessionId: string; propertyId: string; roomId?: string; purpose: FurnishingUploadPurpose; filename: string; mimeType: string; size: number; idempotencyKey: string; correlationId: string }>): Promise<UploadResult> { const session = await this.dependencies.repository.findSession(input.onboardingSessionId); if (!session || session.customerId !== input.actor.userId || session.tenantId !== input.actor.tenantId || session.status !== "in_progress") return { status: "denied", reason: "session_not_eligible" }; if (this.dependencies.activation.globalKillSwitch || this.dependencies.activation.globalState === "disabled" || !this.dependencies.activation.capabilityEnabled) return { status: "denied", reason: "activation_disabled" }; const existing = await this.dependencies.repository.findUploadByIdempotency(input.idempotencyKey); if (existing) return { status: "requested", upload: existing }; const rule = policy[input.purpose]; if (!rule || !rule.mimes.includes(input.mimeType) || input.size <= 0 || input.size > rule.max || (rule.room && !input.roomId) || (!rule.room && input.roomId)) return { status: "invalid", reason: "file_policy_invalid" }; const id = crypto.randomUUID(); const upload: FurnishingUpload = { id, tenantId: session.tenantId, sessionId: session.id, propertyId: input.propertyId, ...(input.roomId ? { roomId: input.roomId } : {}), purpose: input.purpose, filename: safeName(input.filename), objectKey: `furnishing-intake/${session.tenantId}/${session.id}/${input.propertyId}/${id}`, mimeType: input.mimeType, size: input.size, state: "requested", version: 1 }; const created = await this.dependencies.repository.create(upload); await this.dependencies.repository.audit({ event: "furnishing_upload_requested", uploadId: id, sessionId: session.id, purpose: input.purpose, correlationId: input.correlationId }); return { status: "requested", upload: created }; }
}
export class FinalizeFurnishingIntakeUpload { constructor(private readonly dependencies: Readonly<{ repository: FurnishingUploadRepository }>) {} async execute(input: Readonly<{ actor: FurnishingOnboardingActor; uploadId: string; actualSize: number; expectedVersion: number; correlationId: string }>): Promise<UploadResult> { const upload = await this.dependencies.repository.finalize(input.uploadId, input.actualSize, input.expectedVersion); if (!upload || upload.tenantId !== input.actor.tenantId || upload.state === "removed") return { status: "denied" }; await this.dependencies.repository.audit({ event: "furnishing_upload_finalized", uploadId: upload.id, correlationId: input.correlationId }); return { status: "available", upload }; } }
