import { describe, expect, it } from "vitest";
import { ResolveFurnishingOnboardingProperty, type FurnishingProperty, type FurnishingPropertyRepository } from "./furnishing-property-resolution";
import type { FurnishingOnboardingSession } from "./furnishing-onboarding";
const activation = { globalKillSwitch: false, globalState: "limited" as const, workspaceKillSwitch: false, workspaceEnabled: true, cohortEligible: true, capabilityEnabled: true, configurationValid: true, policyVersion: "v1" };
const session: FurnishingOnboardingSession = { id: "s", customerId: "u", tenantId: "t", entitlementId: "e", handoffId: "h", offerId: "FS-DESIGN", offerVersion: 1, schemaVersion: 1, projectType: "design", status: "in_progress", currentStep: "service_confirmation", completedSteps: [], propertyPath: "not_selected", version: 1, idempotencyKey: "k", correlationId: "c", createdAt: "now", updatedAt: "now" };
const input = { name: "Lake House", propertyType: "home", country: "US", address: "1 Main St", city: "Austin", region: "TX", postalCode: "78701", timezone: "America/Chicago", bedrooms: 2, bathrooms: 2, maxGuests: 6 };
function setup(existing: FurnishingProperty | null = null, duplicate: { classification: "exact_match" | "probable_match"; property?: FurnishingProperty } | null = null) { let bound: FurnishingOnboardingSession | null = null; const property = existing; const repo: FurnishingPropertyRepository = { findSession: async () => session, findProperty: async () => property, findDuplicate: async () => duplicate, transact: async work => work({ createProperty: async value => value, bindProperty: async (_, id) => { bound = { ...session, version: 2, propertyPath: "existing" }; return bound; }, audit: async () => undefined }) }; return { op: new ResolveFurnishingOnboardingProperty({ repository: repo, activation }), getBound: () => bound }; }
describe("FS-008C property resolution", () => {
  it("creates and binds a new property", async () => { const s = setup(); const result = await s.op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 1, selection: { mode: "new", property: input }, idempotencyKey: "k", correlationId: "c" }); expect(result.status).toBe("resolved"); expect(result.property?.source).toBe("furnishing_onboarding"); });
  it("selects an authorized existing property", async () => { const p = { id: "p", tenantId: "t", ...input }; const s = setup(p); const result = await s.op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 1, selection: { mode: "existing", propertyId: "p" }, idempotencyKey: "k", correlationId: "c" }); expect(result.property?.id).toBe("p"); });
  it.each([["wrong tenant", { id: "p", tenantId: "other", ...input }, "wrong_tenant"], ["archived", { id: "p", tenantId: "t", archived: true, ...input }, "archived_property"]] as const)("denies %s property", async (_, p, reason) => { const s = setup(p); const result = await s.op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 1, selection: { mode: "existing", propertyId: "p" }, idempotencyKey: "k", correlationId: "c" }); expect(result.reason).toBe(reason); });
  it("requires review for probable duplicates and reuses exact duplicates", async () => { const p = { id: "p", tenantId: "t", ...input }; expect((await setup(null, { classification: "probable_match", property: p }).op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 1, selection: { mode: "new", property: input }, idempotencyKey: "k", correlationId: "c" })).status).toBe("review_required"); expect((await setup(null, { classification: "exact_match", property: p }).op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 1, selection: { mode: "new", property: input }, idempotencyKey: "k", correlationId: "c" })).duplicate).toBe("exact_match"); });
  it("rejects stale sessions and invalid input", async () => { const s = setup(); expect((await s.op.execute({ actor: { userId: "u", tenantId: "t", role: "customer" }, onboardingSessionId: "s", expectedVersion: 2, selection: { mode: "new", property: { ...input, address: "" } }, idempotencyKey: "k", correlationId: "c" })).reason).toBe("stale_session"); });
});
