import type { FurnishingActivationContext } from "./furnishing-offers";
import type { FurnishingOnboardingActor, FurnishingOnboardingSession } from "./furnishing-onboarding";
export type FurnishingDesignProfile = Readonly<{ targetGuest: string; designDirection: string; budgetMin?: number; budgetMax?: number; timeline: string; workspaceRequired: boolean; tvMountSummary: string; durability: string; priorityRooms: readonly string[]; existingInventory: "keep" | "replace" | "evaluate" | "none" | "unknown"; goals: string }>;
export interface DesignProfileRepository { findSession(id: string): Promise<FurnishingOnboardingSession | null>; save(input: Readonly<{ session: FurnishingOnboardingSession; profile: FurnishingDesignProfile; expectedVersion: number; idempotencyKey: string }>): Promise<FurnishingOnboardingSession>; audit(value: Readonly<Record<string, string>>): Promise<void>; }
export class SaveFurnishingDesignProfileDraft {
  constructor(private readonly dependencies: Readonly<{ repository: DesignProfileRepository; activation: FurnishingActivationContext }>) {}
  async execute(input: Readonly<{ actor: FurnishingOnboardingActor; onboardingSessionId: string; expectedVersion: number; profile: FurnishingDesignProfile; idempotencyKey: string; correlationId: string }>): Promise<Readonly<{ status: "saved" | "invalid" | "denied" | "conflict"; session?: FurnishingOnboardingSession; errors?: readonly string[] }>> {
    const session = await this.dependencies.repository.findSession(input.onboardingSessionId); if (!session || session.customerId !== input.actor.userId || session.tenantId !== input.actor.tenantId) return { status: "denied" }; if (session.status !== "in_progress" || session.version !== input.expectedVersion || this.dependencies.activation.globalKillSwitch || this.dependencies.activation.globalState === "disabled" || !this.dependencies.activation.capabilityEnabled) return { status: session.version !== input.expectedVersion ? "conflict" : "denied", session }; const p = input.profile; const errors: string[] = []; if (!p.targetGuest.trim()) errors.push("target_guest"); if (!p.designDirection.trim()) errors.push("design_direction"); if (!p.timeline.trim()) errors.push("timeline"); if (p.budgetMin !== undefined && p.budgetMax !== undefined && p.budgetMin > p.budgetMax) errors.push("budget_range"); if (!p.priorityRooms.length) errors.push("priority_rooms"); if (errors.length) return { status: "invalid", errors, session }; try { const updated = await this.dependencies.repository.save({ session, profile: p, expectedVersion: input.expectedVersion, idempotencyKey: input.idempotencyKey }); await this.dependencies.repository.audit({ event: "furnishing_design_profile_draft_saved", sessionId: session.id, correlationId: input.correlationId }); return { status: "saved", session: updated }; } catch { return { status: "conflict", session }; }
  }
}
