import { describe, expect, it } from "vitest";
import { resolveFurnishingOnboardingEligibility, StartFurnishingOnboarding, type FurnishingOnboardingEntitlement, type FurnishingOnboardingHandoff, type FurnishingOnboardingSession } from "./furnishing-onboarding";

const activation = { globalKillSwitch: false, globalState: "limited" as const, workspaceKillSwitch: false, workspaceEnabled: true, cohortEligible: true, capabilityEnabled: true, configurationValid: true, policyVersion: "fs008a-v1" };
const entitlement: FurnishingOnboardingEntitlement = { id: "e1", customerId: "u1", tenantId: "t1", productFamily: "furnishing", offerId: "FS-CONSULT", offerVersion: 1, status: "active" };
const handoff: FurnishingOnboardingHandoff = { id: "h1", entitlementId: "e1", customerId: "u1", tenantId: "t1", status: "pending_fs008c" };
function setup(existing: FurnishingOnboardingSession | null = null) { const audits: Record<string, string>[] = []; let session = existing; const repository = { findEntitlement: async () => entitlement, findHandoff: async () => handoff, findSessionByHandoff: async () => session, createSession: async (value: FurnishingOnboardingSession) => { if (session) throw new Error("duplicate"); session = value; return value; }, appendAudit: async (value: Record<string, string>) => { audits.push(value); } }; return { operation: new StartFurnishingOnboarding({ repository, activation, onboardingEnabled: true, now: () => new Date("2026-08-25T00:00:00Z") }), audits, getSession: () => session }; }

describe("FS-008C eligibility and session start", () => {
  it("allows an active consultation entitlement", () => expect(resolveFurnishingOnboardingEligibility({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlement, handoff, activation, onboardingEnabled: true }).reason).toBe("eligible"));
  it.each([["FS-FULL", "offer_unsupported"], ["suspended", "entitlement_suspended"], ["refunded", "entitlement_refunded"]] as const)("denies %s", (value, reason) => expect(resolveFurnishingOnboardingEligibility({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlement: { ...entitlement, ...(value === "FS-FULL" ? { offerId: value } : { status: value }) }, handoff, activation, onboardingEnabled: true }).reason).toBe(reason));
  it.each([["anonymous", { role: "anonymous" as const }], ["wrong tenant", { userId: "u1", tenantId: "t2", role: "customer" as const }], ["operator", { userId: "u2", tenantId: "t1", role: "operator" as const }]])("denies %s", (_, actor) => expect(resolveFurnishingOnboardingEligibility({ actor, entitlement, handoff, activation, onboardingEnabled: true }).allowed).toBe(false));
  it("creates exactly one resumable session and audit", async () => { const s = setup(); const first = await s.operation.execute({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlementId: "e1", handoffId: "h1", idempotencyKey: "k1", correlationId: "c1" }); const second = await s.operation.execute({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlementId: "e1", handoffId: "h1", idempotencyKey: "k1", correlationId: "c2" }); expect(first.status).toBe("created"); expect(second.status).toBe("resumed"); expect(first.session?.status).toBe("in_progress"); expect(first.session?.projectType).toBe("consultation"); expect(s.audits).toHaveLength(2); });
  it("fails closed while onboarding capability is disabled", async () => { const base = setup(); const s = new StartFurnishingOnboarding({ repository: { findEntitlement: async () => entitlement, findHandoff: async () => handoff, findSessionByHandoff: async () => null, createSession: async (value: FurnishingOnboardingSession) => value, appendAudit: async () => undefined }, activation: { ...activation, capabilityEnabled: false }, onboardingEnabled: true }); expect((await s.execute({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlementId: "e1", handoffId: "h1", idempotencyKey: "k", correlationId: "c" })).reason).toBe("activation_disabled"); expect(base.audits).toHaveLength(0); });
  it("does not create resources for an unavailable handoff", async () => { const s = setup(); const result = await s.operation.execute({ actor: { userId: "u1", tenantId: "t1", role: "customer" }, entitlementId: "e1", handoffId: "h1", idempotencyKey: "k", correlationId: "c" }); expect(result.status).toBe("created"); expect(s.getSession()?.propertyPath).toBe("not_selected"); });
});
