import { describe, expect, it } from "vitest";
import { ResolveFurnishingCommercialRemedy, type FurnishingPurchaseState } from "./furnishing-commercial-remedy";

const base: FurnishingPurchaseState = { id: "purchase-1", offerId: "FS-CONSULT", offerVersion: 1, paidAmountMinor: 24900, refundedAmountMinor: 0, paymentStatus: "paid", entitlementStatus: "active", handoffStatus: "pending_fs008c", version: 1 };
function setup(initial = base) { let purchase = initial; const audits: unknown[] = []; const repo = { findPurchase: async () => purchase, transact: async (work: any) => work({ savePurchase: async (value: FurnishingPurchaseState) => { purchase = value; }, appendAudit: async (value: unknown) => { audits.push(value); } }) }; return { operation: new ResolveFurnishingCommercialRemedy({ repository: repo, now: () => new Date("2026-08-25T20:00:00Z") }), get: () => purchase, audits }; }

describe("FS-008B P2.6 refund/dispute/revocation policy", () => {
  it("records a verified full refund and makes handoff unavailable", async () => { const s = setup(); const result = await s.operation.execute({ purchaseId: "purchase-1", event: "full_refund", actor: { role: "admin", id: "admin" }, reason: "customer refund", verifiedProviderEvent: true, idempotencyKey: "r1" }); expect(result.status).toBe("refunded"); expect(result.purchase.refundedAmountMinor).toBe(24900); expect(result.purchase.entitlementStatus).toBe("refunded"); expect(result.handoffAvailable).toBe(false); expect(s.audits).toHaveLength(1); });
  it("accumulates partial refunds and rejects over-refund", async () => { const s = setup(); expect((await s.operation.execute({ purchaseId: "purchase-1", event: "partial_refund", refundedAmountMinor: 5000, actor: { role: "admin", id: "a" }, reason: "partial", verifiedProviderEvent: true, idempotencyKey: "r1" })).status).toBe("partially_refunded"); expect((await s.operation.execute({ purchaseId: "purchase-1", event: "partial_refund", refundedAmountMinor: 19900, actor: { role: "admin", id: "a" }, reason: "balance", verifiedProviderEvent: true, idempotencyKey: "r2" })).status).toBe("refunded"); });
  it.each(["dispute_opened", "chargeback", "admin_suspend"] as const)("suspends access for %s", async event => { const s = setup(); const result = await s.operation.execute({ purchaseId: "purchase-1", event, actor: { role: "admin", id: "a" }, reason: "review", verifiedProviderEvent: true, idempotencyKey: event }); expect(result.status).toBe("suspended"); expect(result.handoffAvailable).toBe(false); });
  it("requires review when provider verification is absent", async () => { const s = setup(); expect((await s.operation.execute({ purchaseId: "purchase-1", event: "full_refund", actor: { role: "admin", id: "a" }, reason: "refund", idempotencyKey: "x" })).status).toBe("review_required"); expect(s.audits).toHaveLength(0); });
  it("requires Admin reason and expected version", async () => { const s = setup(); await expect(s.operation.execute({ purchaseId: "purchase-1", event: "admin_revoke", actor: { role: "admin", id: "a" }, idempotencyKey: "x" })).rejects.toThrow(); await expect(s.operation.execute({ purchaseId: "purchase-1", event: "admin_revoke", actor: { role: "admin", id: "a" }, reason: "x", expectedVersion: 9, idempotencyKey: "x" })).rejects.toThrow(); });
  it("replays idempotently and preserves lineage", async () => { const s = setup(); const input = { purchaseId: "purchase-1", event: "admin_suspend" as const, actor: { role: "admin" as const, id: "a" }, reason: "hold", idempotencyKey: "same" }; expect((await s.operation.execute(input)).status).toBe("suspended"); expect((await s.operation.execute(input)).status).toBe("unchanged"); expect(s.audits).toHaveLength(1); });
  it("does not create projects or downstream effects", async () => { const s = setup(); await s.operation.execute({ purchaseId: "purchase-1", event: "admin_revoke", actor: { role: "admin", id: "a" }, reason: "revoke", idempotencyKey: "r" }); expect(s.get()).not.toHaveProperty("projectId"); });
});
