import { describe, expect, it } from "vitest";
import { GetFurnishingPurchaseConfirmation, type FurnishingPendingHandoff } from "./furnishing-purchase-confirmation";

const attempt = { id: "attempt-1", actorId: "user-1", customerId: "customer-1", tenantId: "tenant-1", workspaceId: "workspace-1", offerId: "FS-CONSULT", offerVersion: 1, amountMinor: 24900, currency: "USD", billingModel: "one_time", status: "session_created", createdAt: "2026-08-25T20:00:00Z", expiresAt: "2026-08-25T21:00:00Z" };
const entitlement = { id: "ent-1", customerId: "customer-1", tenantId: "tenant-1", workspaceId: "workspace-1", offerId: "FS-CONSULT", offerVersion: 1, status: "active" };
const activation = { globalKillSwitch: false, globalState: "internal" as const, workspaceKillSwitch: false, workspaceEnabled: true, cohortEligible: true, capabilityEnabled: true, configurationValid: true, policyVersion: "fs008a-v1" };
function setup(overrides: any = {}) { let handoff: FurnishingPendingHandoff | null = overrides.handoff ?? null; const repo = { findAttempt: async () => overrides.attempt === undefined ? attempt : overrides.attempt, findPayment: async () => overrides.payment === undefined ? { id: "payment-1", status: "payment_verified" } : overrides.payment, findEntitlement: async () => overrides.entitlement === undefined ? entitlement : overrides.entitlement, findHandoff: async () => handoff, createHandoff: async (value: FurnishingPendingHandoff) => { handoff = value; return value; } }; const operation = new GetFurnishingPurchaseConfirmation({ repository: repo, authorization: { canRead: async ({ actorId, attempt: target }) => actorId === target.actorId }, activation: overrides.activation ?? activation, now: () => new Date("2026-08-25T20:00:00Z") }); return { operation, repo, getHandoff: () => handoff }; }

describe("FS-008B P2.5 purchase confirmation", () => {
  it.each([{ payment: null }, { payment: { status: "processing" } }])("shows processing without entitlement or retry mutation %o", async override => expect((await setup(override).operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" })).status).toBe("payment_processing"));
  it.each([{ payment: { status: "failed" } }, { attempt: { ...attempt, status: "canceled" } }, { attempt: { ...attempt, status: "expired" } }])("shows safe retry state %o", async override => expect((await setup(override).operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" })).nextStep).toBe("retry"));
  it("shows payment verified while entitlement is pending", async () => expect((await setup({ entitlement: null }).operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" })).status).toBe("entitlement_pending"));
  it("creates exactly one FS-008C pending handoff after active entitlement", async () => { const s = setup(); const first = await s.operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" }); const second = await s.operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" }); expect(first.status).toBe("active"); expect(first.handoff?.status).toBe("pending_fs008c"); expect(second.handoff?.id).toBe(first.handoff?.id); expect(s.getHandoff()?.entitlementId).toBe("ent-1"); });
  it("keeps onboarding unavailable while FS-008C is inactive", async () => { const result = await setup({ activation: { ...activation, globalState: "disabled" } }).operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" }); expect(result.status).toBe("paused"); expect(result.nextStep).toBe("fs008c_pending"); });
  it.each([{ payment: { status: "refunded" } }, { payment: { status: "reconciliation_required" } }])("maps terminal review states safely %o", async override => expect(["refunded", "reconciliation_required"]).toContain((await setup(override).operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" })).status));
  it("denies anonymous and wrong-tenant access without revealing existence", async () => { const s = setup(); expect((await s.operation.execute({ actorId: "other", checkoutAttemptId: "attempt-1" })).status).toBe("access_denied"); expect((await s.operation.execute({ actorId: "", checkoutAttemptId: "missing" })).status).toBe("access_denied"); });
  it("does not expose provider identifiers or create downstream resources", async () => { const result = await setup().operation.execute({ actorId: "user-1", checkoutAttemptId: "attempt-1" }); expect(result).not.toHaveProperty("providerPaymentReference"); expect(result).not.toHaveProperty("projectId"); expect(result).not.toHaveProperty("notificationId"); });
});
