import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import { OC001_CATALOG_FINGERPRINT, OC001_OFFER_REGISTRY, validateOc001Offer, type Oc001OfferDefinition, type Oc001OfferFamily } from "../domain";

const canonical=(value:unknown)=>JSON.stringify(value,(_key,item)=>{if(typeof item==="string"&&/^\d{4}-\d{2}-\d{2}T/.test(item)){const parsed=Date.parse(item);if(Number.isFinite(parsed))return new Date(parsed).toISOString()}return item!==null&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item});
const family=(value:Oc001OfferFamily)=>value==="guidebook"?"guidebook_studio":value;
const customerType=(value:Oc001OfferDefinition):string=>value.family==="investment_intelligence"?"investor":value.family==="furnishing"?"service_client":value.offerCode.includes("portfolio")||value.offerCode.includes("professional")||value.offerCode.includes("enterprise")?"portfolio_operator":"individual_operator";
const acquisition=(value:Oc001OfferDefinition)=>value.purchaseAction==="configure"?"proposal_required":value.launchState==="deferred"?"contact_sales":"self_service";
const billing=(value:Oc001OfferDefinition)=>value.prices.some(price=>price.model==="recurring")?"recurring":value.prices.length?"one_time":"custom_quote";

export class RegisterOc001Catalog {
  constructor(private readonly client:SupabaseClient){}
  async execute(input:Readonly<{actorId:string;correlationId:string}>){
    const {data:profile,error}=await this.client.from("profiles").select("role").eq("id",input.actorId).maybeSingle();
    if(error||profile?.role!=="admin")throw new Error("OC001_CATALOG_NOT_AUTHORIZED");
    let offers=0,prices=0;
    for(const definition of OC001_OFFER_REGISTRY){
      validateOc001Offer(definition);
      const commercial={code:definition.offerCode,version:definition.version,product_family:family(definition.family),name:definition.customerName,short_description:definition.shortDescription,status:"draft",customer_type:customerType(definition),acquisition_mode:acquisition(definition),billing_model:billing(definition),currency:definition.prices.length===1?definition.prices[0].currency:null,amount_minor:definition.prices.length===1?definition.prices[0].amountMinor:null,billing_interval:definition.prices.length===1?definition.prices[0].cadence??null:null,interval_count:definition.prices.length===1?definition.prices[0].intervalCount??null:null,standalone_eligible:true,prerequisite_offer_codes:[],compatible_offer_codes:[],upgrade_offer_codes:[],effective_from:definition.effectiveFrom,effective_until:definition.effectiveThrough??null,schema_version:2};
      const read=await this.client.from("commercial_offer_versions").select("*").eq("code",definition.offerCode).eq("version",definition.version).maybeSingle();let offer=read.data;const offerRead=read.error;
      if(offerRead)throw new Error("OC001_CATALOG_READ_FAILED");
      if(!offer){const result=await this.client.from("commercial_offer_versions").insert(commercial).select("*").single();if(result.error||!result.data)throw new Error("OC001_CATALOG_WRITE_FAILED");offer=result.data}
      else {const drift=Object.keys(commercial).filter(key=>key!=="status"&&canonical(offer[key])!==canonical(commercial[key as keyof typeof commercial]));if(drift.length){if(offer.status!=="draft")throw new Error("OC001_CATALOG_DRIFT");const result=await this.client.from("commercial_offer_versions").update(commercial).eq("id",offer.id).eq("status","draft").select("*").single();if(result.error||!result.data)throw new Error("OC001_CATALOG_WRITE_FAILED");offer=result.data}}
      const offerId=String(offer.id),detail={offer_id:offerId,offer_type:definition.offerType,full_description:definition.fullDescription,audience:definition.audience,deliverables:definition.deliverables,exclusions:definition.exclusions,eligibility_rules:definition.eligibility,configuration_fields:definition.requiredInputs,onboarding_template_code:definition.onboardingTemplateCode,destination_code:definition.destinationCode,commercial_policy_version:definition.commercialPolicyVersion,cancellation_policy_code:definition.cancellationPolicyCode??null,refund_policy_code:definition.refundPolicyCode??null,renewal_policy_code:definition.renewalPolicyCode??null,terms_version:definition.termsVersion,support_level:definition.supportLevel,expected_timeline:definition.expectedTimeline,purchase_action:definition.purchaseAction,launch_state:definition.launchState,base_offer_code:definition.baseOfferCode??null,included_hosting_months:definition.includedHostingMonths??null,credit_expiration_months:definition.creditExpirationMonths??null,scope_approval_required:definition.scopeApprovalRequired??false,created_by:input.actorId};
      await this.insertImmutable("commercial_offer_details",{offer_id:offerId},detail);
      for(const entitlement of definition.entitlements)await this.insertImmutable("commercial_offer_capabilities",{offer_id:offerId,capability_code:entitlement.capabilityCode},{offer_id:offerId,capability_code:entitlement.capabilityCode,resource_type:entitlement.resourceType});
      for(const limit of definition.limits)await this.insertImmutable("commercial_offer_limits",{offer_id:offerId,limit_code:limit.code},{offer_id:offerId,limit_code:limit.code,allowance_kind:limit.allowance.kind,allowance_value:limit.allowance.kind==="finite"?limit.allowance.value:null,period:limit.period??null,enforcement:limit.enforcement});
      for(const value of definition.prices){const row={code:value.code,version:value.version,offer_id:offerId,currency:value.currency,amount_minor:value.amountMinor,price_model:value.model,billing_cadence:value.cadence??null,interval_count:value.intervalCount??null,tax_behavior:value.taxBehavior,status:value.status,effective_from:definition.effectiveFrom,effective_through:definition.effectiveThrough??null,created_by:input.actorId};await this.insertImmutable("commercial_price_versions",{code:value.code,version:value.version},row);prices++}
      await this.client.from("commercial_catalog_audit_events").upsert({event_code:"oc001_offer_registered",offer_code:definition.offerCode,offer_version:definition.version,actor_id:input.actorId,reason_code:"immutable_registry_registration",correlation_id:input.correlationId,safe_metadata:{priceCount:definition.prices.length,family:definition.family}},{onConflict:"event_code,offer_code,offer_version,reason_code",ignoreDuplicates:true});
      offers++;
    }
    return Object.freeze({offers,prices,fingerprint:OC001_CATALOG_FINGERPRINT});
  }
  private async insertImmutable(table:string,identity:Record<string,unknown>,row:Record<string,unknown>){let query=this.client.from(table).select("*");for(const[key,value]of Object.entries(identity))query=query.eq(key,value);const{data,error}=await query.maybeSingle();if(error)throw new Error("OC001_CATALOG_READ_FAILED");if(data){for(const key of Object.keys(row).filter(key=>!["created_by","created_at"].includes(key)))if(canonical(data[key])!==canonical(row[key]))throw new Error("OC001_CATALOG_DRIFT");return}if((await this.client.from(table).insert(row)).error)throw new Error("OC001_CATALOG_WRITE_FAILED")}
}

export type PublicOc001Offer=Readonly<{offerCode:string;version:number;family:Oc001OfferFamily;customerName:string;shortDescription:string;fullDescription:string;deliverables:readonly string[];exclusions:readonly string[];limits:readonly unknown[];requiredInputs:readonly unknown[];supportLevel:string;expectedTimeline:string;termsVersion:string;prices:readonly Readonly<{code:string;version:number;currency:string;amountMinor:number;model:string;cadence?:string}>[];purchaseAction:string;checkoutAvailable:boolean;catalogFingerprint:string}>;
export class ReadPublishedOc001Catalog{constructor(private readonly client:SupabaseClient){}async execute(familyCode?:Oc001OfferFamily):Promise<readonly PublicOc001Offer[]>{const{data,error}=await this.client.rpc("read_published_offer_catalog",{p_family:familyCode??null});if(error)throw new Error("OC001_CATALOG_UNAVAILABLE");return Object.freeze((Array.isArray(data)?data:[]) as PublicOc001Offer[])}}

export type Oc001ProviderPrice=Readonly<{id:string;productId:string;active:boolean;productActive:boolean;livemode:boolean;currency:string;unitAmount:number;type:"one_time"|"recurring";cadence?:"month"|"year";intervalCount?:number}>;
export class ReconcileOc001StripeMapping{constructor(private readonly client:SupabaseClient,private readonly readProviderPrice:(id:string)=>Promise<Oc001ProviderPrice>){}async execute(input:Readonly<{actorId:string;priceCode:string;priceVersion:number;stripePriceReference:string;correlationId:string}>){const{data:profile}=await this.client.from("profiles").select("role").eq("id",input.actorId).maybeSingle();if(profile?.role!=="admin")throw new Error("OC001_MAPPING_NOT_AUTHORIZED");const{data:price,error}=await this.client.from("commercial_price_versions").select("*,commercial_offer_versions!inner(code,version)").eq("code",input.priceCode).eq("version",input.priceVersion).maybeSingle();if(error||!price)throw new Error("OC001_PRICE_UNAVAILABLE");const observation=await this.readProviderPrice(input.stripePriceReference);if(!observation.active||!observation.productActive||!observation.livemode||observation.currency!==price.currency||observation.unitAmount!==Number(price.amount_minor)||observation.type!==price.price_model||(observation.cadence??null)!==(price.billing_cadence??null)||(observation.intervalCount??null)!==(price.interval_count??null))throw new Error("OC001_PRICE_MAPPING_DRIFT");const offer=price.commercial_offer_versions as unknown as {code:string;version:number};const{data:existing,error:readError}=await this.client.from("billing_price_mappings").select("*").eq("price_code",input.priceCode).eq("price_version",input.priceVersion).eq("account_mode","live").eq("status","active").maybeSingle();if(readError)throw new Error("OC001_MAPPING_READ_FAILED");if(existing){if(existing.stripe_price_reference!==observation.id||existing.stripe_product_reference!==observation.productId||Number(existing.amount_minor)!==observation.unitAmount)throw new Error("OC001_MAPPING_DRIFT");return Object.freeze({mappingId:String(existing.id),status:"unchanged"as const})}const{data:mapping,error:writeError}=await this.client.from("billing_price_mappings").insert({offer_code:offer.code,offer_version:offer.version,price_code:input.priceCode,price_version:input.priceVersion,billing_model:observation.type,currency:observation.currency,amount_minor:observation.unitAmount,billing_interval:observation.cadence??null,interval_count:observation.intervalCount??null,stripe_product_reference:observation.productId,stripe_price_reference:observation.id,account_mode:"live",status:"active",effective_from:new Date().toISOString(),created_by:input.actorId,revision:1}).select("id").single();if(writeError||!mapping)throw new Error("OC001_MAPPING_WRITE_FAILED");await this.client.from("commercial_catalog_audit_events").insert({event_code:"oc001_price_mapping_reconciled",offer_code:offer.code,offer_version:offer.version,price_code:input.priceCode,price_version:input.priceVersion,actor_id:input.actorId,reason_code:"provider_state_verified",correlation_id:input.correlationId,safe_metadata:{accountMode:"live"}});return Object.freeze({mappingId:String(mapping.id),status:"created"as const})}}

export class PublishOc001Offer{constructor(private readonly client:SupabaseClient){}async execute(input:Readonly<{actorId:string;offerCode:string;offerVersion:number;verificationReference:string;expectedStatus:"draft"|"approved";correlationId:string}>){const{data:profile}=await this.client.from("profiles").select("role").eq("id",input.actorId).maybeSingle();if(profile?.role!=="admin"||!input.verificationReference.trim())throw new Error("OC001_PUBLICATION_NOT_AUTHORIZED");const{data:offer,error}=await this.client.from("commercial_offer_versions").select("id,status").eq("code",input.offerCode).eq("version",input.offerVersion).maybeSingle();if(error||!offer||offer.status!==input.expectedStatus)throw new Error("OC001_PUBLICATION_CONFLICT");const [{data:verification},{data:details},{data:prices},{data:mappings}]=await Promise.all([this.client.from("commercial_offer_verification_results").select("id").eq("id",input.verificationReference).eq("offer_id",offer.id).eq("status","passed").maybeSingle(),this.client.from("commercial_offer_details").select("offer_id").eq("offer_id",offer.id).maybeSingle(),this.client.from("commercial_price_versions").select("code,version,amount_minor,currency,billing_cadence,status").eq("offer_id",offer.id).eq("status","active"),this.client.from("billing_price_mappings").select("price_code,price_version,amount_minor,currency,billing_interval,account_mode,status").eq("offer_code",input.offerCode).eq("offer_version",input.offerVersion).eq("account_mode","live").eq("status","active")]);if(!verification)throw new Error("OC001_VERIFICATION_REQUIRED");if(!details)throw new Error("OC001_OFFER_INCOMPLETE");const definition=OC001_OFFER_REGISTRY.find(value=>value.offerCode===input.offerCode&&value.version===input.offerVersion);if(!definition||definition.launchState==="deferred")throw new Error("OC001_CATALOG_DRIFT");if(!prices?.length||prices.length!==mappings?.length)throw new Error("OC001_PRICE_MAPPING_UNAVAILABLE");for(const price of prices){const mapping=mappings?.find(value=>value.price_code===price.code&&value.price_version===price.version);if(!mapping||Number(mapping.amount_minor)!==Number(price.amount_minor)||mapping.currency!==price.currency||(mapping.billing_interval??null)!==(price.billing_cadence??null))throw new Error("OC001_PRICE_MAPPING_DRIFT")}
if(offer.status==="draft"){const approved=await this.client.from("commercial_offer_versions").update({status:"approved"}).eq("id",offer.id).eq("status","draft");if(approved.error)throw new Error("OC001_APPROVAL_FAILED")}
const active=await this.client.from("commercial_offer_versions").update({status:"active"}).eq("id",offer.id).eq("status","approved");if(active.error)throw new Error("OC001_ACTIVATION_FAILED");const fingerprint=createHash("sha256").update(canonical(definition)).digest("hex"),publication=await this.client.from("commercial_catalog_publications").insert({offer_id:offer.id,publication_version:1,status:"published",definition_fingerprint:fingerprint,verification_status:"passed",verification_reference:input.verificationReference,published_at:new Date().toISOString(),created_by:input.actorId});if(publication.error)throw new Error("OC001_PUBLICATION_FAILED");await this.client.from("commercial_catalog_audit_events").insert({event_code:"oc001_offer_published",offer_code:input.offerCode,offer_version:input.offerVersion,actor_id:input.actorId,reason_code:"production_verification_passed",correlation_id:input.correlationId,safe_metadata:{definitionFingerprint:fingerprint}});return Object.freeze({offerCode:input.offerCode,version:input.offerVersion,status:"active"as const,fingerprint})}}

export function validateOc001Configuration(offer:Oc001OfferDefinition,input:Readonly<Record<string,string|number>>){const normalized:Record<string,string|number>={};for(const field of offer.requiredInputs){const value=input[field.code];if(field.required&&(value===undefined||value===""))throw new Error("OC001_CONFIGURATION_REQUIRED");if(value===undefined)continue;if(field.type==="integer"){const number=Number(value);if(!Number.isSafeInteger(number)||(field.minimum!==undefined&&number<field.minimum)||(field.maximum!==undefined&&number>field.maximum))throw new Error("OC001_CONFIGURATION_INVALID");normalized[field.code]=number}else{const string=String(value);if(!field.allowedValues?.includes(string))throw new Error("OC001_CONFIGURATION_INVALID");normalized[field.code]=string}}for(const key of Object.keys(input))if(!offer.requiredInputs.some(field=>field.code===key))throw new Error("OC001_CONFIGURATION_UNKNOWN");return Object.freeze(normalized)}
export function oc001PurchaseSnapshot(offer:Oc001OfferDefinition,priceCode:string,configuration:Readonly<Record<string,string|number>>){const price=offer.prices.find(value=>value.code===priceCode&&value.status==="active");if(!price)throw new Error("OC001_PRICE_UNAVAILABLE");const safeConfiguration=validateOc001Configuration(offer,configuration),snapshot={offerCode:offer.offerCode,offerVersion:offer.version,priceCode:price.code,priceVersion:price.version,amountMinor:price.amountMinor,currency:price.currency,configuration:safeConfiguration,policies:{commercial:offer.commercialPolicyVersion,cancellation:offer.cancellationPolicyCode??null,refund:offer.refundPolicyCode??null,renewal:offer.renewalPolicyCode??null,terms:offer.termsVersion},entitlements:offer.entitlements};return Object.freeze({...snapshot,checksum:createHash("sha256").update(canonical(snapshot)).digest("hex")})}
