export type TemplateStatus="draft"|"in_review"|"approved"|"published"|"deprecated"|"archived";
export type TemplateChannel="responsive_web"|"mobile_web"|"pdf"|"guest_portal";
export type TemplateCategory="modern"|"luxury"|"boutique"|"beach"|"cabin"|"urban"|"family"|"minimal"|"custom";
export type TokenValue=string|number;
export type ThemeTokens={typography:Record<string,string>;colors:Record<string,string>;spacing:Record<string,string>;radii:Record<string,string>;borders:Record<string,string>;icons:Record<string,string>;buttons:Record<string,Record<string,TokenValue>>;cards:Record<string,TokenValue>;elevation:Record<string,string>;motion:Record<string,string>;images:Record<string,string>};
export type GuidebookTemplate={id:string;key:string;name:string;slug:string;description:string;category:TemplateCategory;status:TemplateStatus;previewMediaAssetId:string|null;currentVersionId:string|null;createdBy:string;updatedBy:string;createdAt:string;updatedAt:string};
export type ComponentTemplateStyle={componentKey:string;supported:boolean;defaultVariant:string;variants:string[];tokens:Record<string,TokenValue>;fallbackComponentKey:string|null};
export type ChannelContract={channel:TemplateChannel;support:"supported"|"fallback"|"unsupported";rendererKey:string;configuration:Record<string,unknown>};
export type TemplateVersion={id:string;templateId:string;versionNumber:number;status:TemplateStatus;tokens:ThemeTokens;componentStyles:ComponentTemplateStyle[];channels:ChannelContract[];accessibilityStatus:"not_checked"|"valid"|"invalid";changeSummary:string|null;breakingChange:boolean;createdBy:string;approvedBy:string|null;publishedAt:string|null;createdAt:string};
export type WorkspaceBrandingOverride={id:string;workspaceId:string;templateVersionId:string;logoAssetId:string|null;primaryColor:string|null;accentColor:string|null;footerText:string|null;socialLinks:Record<string,string>;createdAt:string;updatedAt:string};
export type TemplateValidationIssue={severity:"info"|"warning"|"error";code:string;message:string;path:string|null;blocking:boolean};

export const TEMPLATE_PERMISSIONS=["templates.view","templates.create","templates.edit","templates.approve","templates.publish","templates.archive","templates.duplicate"] as const;
export const MESA_MODERN_TOKENS:ThemeTokens={
 typography:{headingFamily:"var(--font-editorial-serif)",bodyFamily:"var(--font-modern-sans)",displaySize:"3rem",headingWeight:"600",bodySize:"1rem",lineHeight:"1.6"},
 colors:{primary:"#0B2B24",accent:"#C78A38",highlight:"#F3D3A1",background:"#FAFAF8",surface:"#FFFFFF",border:"#E7E0D2",text:"#111111",muted:"#6D6B68",success:"#167D6A",warning:"#CA8A04",error:"#CF3928",info:"#2A6FB0"},
 spacing:{xs:"0.25rem",sm:"0.5rem",md:"1rem",lg:"1.5rem",xl:"2rem","2xl":"3rem"},radii:{sm:"0.375rem",md:"0.75rem",lg:"1.25rem",pill:"999px"},borders:{default:"1px solid var(--template-border)",strong:"2px solid var(--template-primary)"},icons:{style:"outline",strokeWidth:"1.75"},buttons:{primary:{background:"#0B2B24",color:"#FFFFFF",radius:"0.5rem"},secondary:{background:"#FFFFFF",color:"#0B2B24",radius:"0.5rem"},ghost:{background:"transparent",color:"#0B2B24"}},cards:{radius:"0.75rem",padding:"1rem",border:"1px solid #E7E0D2"},elevation:{sm:"0 1px 2px rgb(0 0 0 / 0.06)",md:"0 10px 30px rgb(11 43 36 / 0.12)"},motion:{fast:"120ms",standard:"220ms",reduced:"0ms"},images:{hero:"3:2",card:"16:9",square:"1:1",portrait:"4:5",objectFit:"cover"}
};
export const MESA_COMPONENT_STYLES:ComponentTemplateStyle[]=[
 ["hero","split",["full_width","split","image_left","image_right","centered"]],["recommendation_card","card",["compact","card","featured","carousel"]],["rule_card","grid",["grid","list","feature"]],["wifi_card","card",["card","compact"]],["departure_checklist","list",["list","print"]],["faq_accordion","accordion",["accordion","expanded"]],["gallery","grid",["grid","carousel"]]
].map(([componentKey,defaultVariant,variants])=>({componentKey:String(componentKey),supported:true,defaultVariant:String(defaultVariant),variants:variants as string[],tokens:{},fallbackComponentKey:null}));
export const MESA_CHANNELS:ChannelContract[]=["responsive_web","mobile_web","pdf","guest_portal"].map(channel=>({channel:channel as TemplateChannel,support:"supported",rendererKey:`mesa-modern-${channel}`,configuration:channel==="pdf"?{pageSize:"letter",margin:"0.5in",pageNumbers:true,toc:true,footer:true,qr:true}:{responsive:true}}));
export function validateTemplateVersion(version:TemplateVersion):TemplateValidationIssue[]{const issues:TemplateValidationIssue[]=[];for(const group of ["typography","colors","spacing","radii","buttons","elevation"] as const)if(!Object.keys(version.tokens[group]).length)issues.push({severity:"error",code:"missing_token_group",message:`${group} tokens are required`,path:`tokens.${group}`,blocking:true});for(const key of ["primary","accent","background","surface","text"] as const)if(!version.tokens.colors[key])issues.push({severity:"error",code:"missing_color_token",message:`Color token ${key} is required`,path:`tokens.colors.${key}`,blocking:true});if(version.channels.some(c=>c.support==="unsupported"))issues.push({severity:"error",code:"unsupported_channel",message:"Every Mesa Modern v1 channel must have a renderer",path:"channels",blocking:true});if(version.accessibilityStatus!=="valid")issues.push({severity:"error",code:"accessibility_not_valid",message:"WCAG validation must pass before publication",path:"accessibilityStatus",blocking:true});return issues}
export function assertTemplateVersionImmutable(before:TemplateVersion,after:TemplateVersion){if(before.status==="published"&&JSON.stringify(before)!==JSON.stringify(after))throw new Error("published_template_version_immutable")}
export function applyBranding(tokens:ThemeTokens,override:WorkspaceBrandingOverride):ThemeTokens{return{...tokens,colors:{...tokens.colors,...(override.primaryColor?{primary:override.primaryColor}:{}),...(override.accentColor?{accent:override.accentColor}:{})}}}
export function canTransitionTemplate(from:TemplateStatus,to:TemplateStatus){return({draft:["in_review"],in_review:["draft","approved"],approved:["draft","published"],published:["deprecated"],deprecated:["archived"],archived:[]} as Record<TemplateStatus,TemplateStatus[]>)[from].includes(to)}
