import type { Decision } from "../../decisions";
import { EntityWithProps, Identifier } from "../../kernel";
import type { ObservationValue } from "../../observations";
import { createActionId, type ActionId } from "../domain/action-id";
import type { ActionType } from "../domain/action-type";
import type { LegacyActionPriority } from "./legacy-action-priority";
import { LEGACY_ACTION_STATUSES, type LegacyActionStatus } from "./legacy-action-status";

export type LegacyActionOwnerType = "user" | "team" | "automation" | "system";
export type LegacyActionOwner = Readonly<{ type: LegacyActionOwnerType; id: string; displayName: string }>;
export type LegacyActionOutcome = Readonly<{ summary: string; successful: boolean; measuredImpact?: Readonly<Record<string, number>>; lessonsLearned?: readonly string[]; metadata?: Readonly<Record<string, ObservationValue>> }>;
type LegacyActionProps = Readonly<{ title: string; summary: string; type: ActionType; priority: LegacyActionPriority; status: LegacyActionStatus; owner: LegacyActionOwner; decisionIdValues: readonly string[]; createdAt: Date; acceptedAt?: Date; scheduledFor?: Date; startedAt?: Date; completedAt?: Date; measuredAt?: Date; archivedAt?: Date; outcome?: LegacyActionOutcome; metadata: Readonly<Record<string, ObservationValue>> }>;
export type LegacyActionInput = Readonly<{ id?: ActionId; title: string; summary: string; type: ActionType; priority: LegacyActionPriority; status?: LegacyActionStatus; owner: LegacyActionOwner; decisionIds: readonly Identifier[]; createdAt: Date; acceptedAt?: Date; scheduledFor?: Date; startedAt?: Date; completedAt?: Date; measuredAt?: Date; archivedAt?: Date; outcome?: LegacyActionOutcome; metadata?: Readonly<Record<string, ObservationValue>> }>;

/** @deprecated Compatibility DTO. New code must use PlatformAction. */
export class LegacyAction extends EntityWithProps<LegacyActionProps, ActionId> {
  private constructor(id: ActionId, props: LegacyActionProps) { super(id, props); }
  public static create(input: LegacyActionInput): LegacyAction {
    const status = input.status ?? "proposed"; if (!LEGACY_ACTION_STATUSES.includes(status)) throw new TypeError("Legacy Action status is invalid.");
    const createdAt = date(input.createdAt, "Action creation date"), completedAt = optionalDate(input.completedAt, "Action completion date");
    if (completedAt && !input.outcome) throw new TypeError("A completed Action requires an outcome.");
    return new LegacyAction(input.id ?? createActionId(), { title: text(input.title, "Action title"), summary: text(input.summary, "Action summary"), type: text(input.type, "Action type"), priority: input.priority, status, owner: Object.freeze({ ...input.owner }), decisionIdValues: Object.freeze([...new Set(input.decisionIds.map((id) => id.value))]), createdAt, ...(input.acceptedAt ? { acceptedAt: date(input.acceptedAt, "Action acceptance date") } : {}), ...(input.scheduledFor ? { scheduledFor: date(input.scheduledFor, "Action schedule date") } : {}), ...(input.startedAt ? { startedAt: date(input.startedAt, "Action start date") } : {}), ...(completedAt ? { completedAt } : {}), ...(input.measuredAt ? { measuredAt: date(input.measuredAt, "Action measurement date") } : {}), ...(input.archivedAt ? { archivedAt: date(input.archivedAt, "Action archive date") } : {}), ...(input.outcome ? { outcome: normalizeOutcome(input.outcome) } : {}), metadata: Object.freeze({ ...input.metadata }) });
  }
  public get title(): string { return this.props.title; } public get summary(): string { return this.props.summary; } public get type(): ActionType { return this.props.type; } public get priority(): LegacyActionPriority { return this.props.priority; } public get status(): LegacyActionStatus { return this.props.status; } public get owner(): LegacyActionOwner { return this.props.owner; }
  public get decisionIds(): readonly Identifier[] { return this.props.decisionIdValues.map(Identifier.create); } public get createdAt(): Date { return new Date(this.props.createdAt); } public get acceptedAt(): Date | undefined { return copy(this.props.acceptedAt); } public get scheduledFor(): Date | undefined { return copy(this.props.scheduledFor); } public get startedAt(): Date | undefined { return copy(this.props.startedAt); } public get completedAt(): Date | undefined { return copy(this.props.completedAt); } public get measuredAt(): Date | undefined { return copy(this.props.measuredAt); } public get archivedAt(): Date | undefined { return copy(this.props.archivedAt); } public get outcome(): LegacyActionOutcome | undefined { return this.props.outcome; } public get metadata(): Readonly<Record<string, ObservationValue>> { return this.props.metadata; }
  public originatesFrom(value: Decision<string> | Identifier): boolean { const id = value instanceof Identifier ? value : value.id; return this.props.decisionIdValues.includes(id.value); }
  public accept(at: Date): LegacyAction { return this.transition(["proposed"], "accepted", { acceptedAt: at }); }
  public schedule(at: Date): LegacyAction { return this.transition(["accepted"], "scheduled", { scheduledFor: at }); }
  public start(at: Date): LegacyAction { return this.transition(["accepted"], "in-progress", { startedAt: at }); }
  public block(): LegacyAction { return this.transition(["accepted", "scheduled", "in-progress"], "blocked"); }
  public complete(at: Date, outcome: LegacyActionOutcome): LegacyAction { return this.transition(["accepted", "scheduled", "in-progress", "blocked"], "completed", { completedAt: at, outcome }); }
  public measure(at: Date, measurement: Pick<LegacyActionOutcome, "measuredImpact" | "lessonsLearned">): LegacyAction { if (this.status !== "completed" || !this.outcome) return this.invalid("measured"); return this.transition(["completed"], "measured", { measuredAt: at, outcome: { ...this.outcome, ...(measurement.measuredImpact ? { measuredImpact: { ...this.outcome.measuredImpact, ...measurement.measuredImpact } } : {}), lessonsLearned: [...(this.outcome.lessonsLearned ?? []), ...(measurement.lessonsLearned ?? []).map((value) => value.trim()).filter(Boolean)] } }); }
  public archive(at: Date): LegacyAction { return this.transition(["proposed", "accepted", "blocked", "completed", "measured"], "archived", { archivedAt: at }); }
  private transition(allowed: readonly LegacyActionStatus[], status: LegacyActionStatus, changes: Partial<LegacyActionInput> = {}): LegacyAction { if (!allowed.includes(this.status)) return this.invalid(status); return LegacyAction.create({ ...this.toInput(), ...changes, status }); }
  private invalid(status: LegacyActionStatus): never { throw new Error(`Cannot transition action from "${this.status}" to "${status}".`); }
  private toInput(): LegacyActionInput { return { id: this.id, title: this.title, summary: this.summary, type: this.type, priority: this.priority, status: this.status, owner: this.owner, decisionIds: this.decisionIds, createdAt: this.createdAt, ...(this.acceptedAt ? { acceptedAt: this.acceptedAt } : {}), ...(this.scheduledFor ? { scheduledFor: this.scheduledFor } : {}), ...(this.startedAt ? { startedAt: this.startedAt } : {}), ...(this.completedAt ? { completedAt: this.completedAt } : {}), ...(this.measuredAt ? { measuredAt: this.measuredAt } : {}), ...(this.archivedAt ? { archivedAt: this.archivedAt } : {}), ...(this.outcome ? { outcome: this.outcome } : {}), metadata: this.metadata }; }
}
function text(value: string, field: string): string { const result = value.trim(); if (!result) throw new TypeError(`${field} cannot be empty.`); return result; } function date(value: Date, field: string): Date { const result = new Date(value); if (Number.isNaN(result.getTime())) throw new TypeError(`${field} must be valid.`); return result; } function optionalDate(value: Date | undefined, field: string): Date | undefined { return value ? date(value, field) : undefined; } function copy(value?: Date): Date | undefined { return value ? new Date(value) : undefined; } function normalizeOutcome(value: LegacyActionOutcome): LegacyActionOutcome { return Object.freeze({ ...value, summary: text(value.summary, "Action outcome summary"), ...(value.measuredImpact ? { measuredImpact: Object.freeze({ ...value.measuredImpact }) } : {}), ...(value.lessonsLearned ? { lessonsLearned: Object.freeze([...value.lessonsLearned]) } : {}) }); }
