import{ONBOARDING_REGISTRY,type OnboardingRequirementCode,type ProductFamilyCode}from"@/platform/commerce";
export type OnboardingCaseStatus="pending"|"ready"|"in_progress"|"customer_action_required"|"internal_action_required"|"blocked"|"ready_for_provisioning"|"provisioning"|"ready_for_handoff"|"completed"|"cancelled";
export type ModuleStatus="locked"|"available"|"in_progress"|"submitted"|"changes_requested"|"verified"|"skipped"|"blocked"|"failed";
export type Responsibility="customer"|"internal"|"shared"|"system";export type CompositionStrategy="shared_once"|"once_per_product_family"|"once_per_property_context"|"once_per_commercial_engagement"|"repeatable";
export type OnboardingCase=Readonly<{id:string;tenantId:string;customerAccountId:string;sourceType:"commercial_agreement"|"administrative_grant"|"migration"|"offer_expansion";sourceReferenceId:string;status:OnboardingCaseStatus;planVersion:number;startedAt?:string;completedAt?:string;cancelledAt?:string;currentModuleInstanceId?:string;blockerCode?:OnboardingBlockerCode;assignedInternalOwnerId?:string;createdAt:string;updatedAt:string;revision:number}>;
export type OnboardingModuleDefinition=Readonly<{code:string;version:number;name:string;description:string;productFamily?:ProductFamilyCode;satisfiesRequirementCodes:readonly OnboardingRequirementCode[];responsibility:Responsibility;completionMode:"customer_submission"|"internal_confirmation"|"system_verification"|"provisioning_result";prerequisiteModuleCodes:readonly string[];compositionStrategy:CompositionStrategy;fieldSchemaCode?:string;validationPolicyCode?:string;provisioningActionCode?:string;dataClassification:"standard"|"confidential"|"restricted";skippable:boolean;skipPolicyCode?:string;estimatedMinutes?:number;status:"active"|"retired"}>;
export type OnboardingTemplate=Readonly<{code:string;version:number;name:string;appliesTo:Readonly<{productFamily?:ProductFamilyCode;offerCode?:string;offerVersion?:number;customerType?:string}>;moduleDefinitions:readonly Readonly<{moduleCode:string;moduleVersion:number;required:boolean}>[];completionPolicyCode:string;handoffPolicyCode:string;status:"draft"|"active"|"retired";effectiveFrom:string;effectiveUntil?:string;createdBy:string;createdAt:string}>;
export type OnboardingModuleInstance=Readonly<{id:string;onboardingCaseId:string;moduleCode:string;moduleVersion:number;productFamily?:ProductFamilyCode;status:ModuleStatus;responsibility:Responsibility;required:boolean;sequence:number;reusedFromModuleInstanceId?:string;startedAt?:string;submittedAt?:string;verifiedAt?:string;completedAt?:string;blockedByCode?:OnboardingBlockerCode;assignedUserId?:string;revision:number}>;
export type OnboardingSubmission=Readonly<{id:string;tenantId:string;onboardingCaseId:string;moduleInstanceId:string;schemaCode:string;schemaVersion:number;submittedBy:string;submittedAt:string;dataClassification:"standard"|"confidential"|"restricted";validationStatus:"pending"|"valid"|"invalid"|"requires_review";validatedData:Readonly<Record<string,unknown>>;revision:number}>;
export type OnboardingBlockerCode="ONBOARDING_PLAN_UNAVAILABLE"|"ONBOARDING_SOURCE_INVALID"|"ENTITLEMENT_NOT_ACTIVE"|"CUSTOMER_ACTION_REQUIRED"|"INTERNAL_REVIEW_REQUIRED"|"REQUIRED_INFORMATION_MISSING"|"SUBMISSION_INVALID"|"DOCUMENT_REQUIRED"|"DOCUMENT_REJECTED"|"PROPERTY_CONTEXT_REQUIRED"|"PROPERTY_LINK_UNAUTHORIZED"|"INTEGRATION_AUTHORIZATION_REQUIRED"|"INTEGRATION_CONNECTION_FAILED"|"DATA_VALIDATION_FAILED"|"PROVISIONING_PENDING"|"PROVISIONING_FAILED"|"OFFER_LIMIT_REACHED"|"COMMERCIAL_REVIEW_REQUIRED"|"ONBOARDING_CONFIGURATION_INVALID";
export class OnboardingError extends Error{constructor(public readonly code:OnboardingBlockerCode|"NOT_AUTHORIZED"|"STALE_REVISION"|"INVALID_TRANSITION"|"UNKNOWN_MODULE"|"UNKNOWN_FIELD"|"FILE_REJECTED",message:string){super(message);Object.freeze(this)}}
export function validateModuleDefinition(value:OnboardingModuleDefinition){if(!value.code.match(/^[a-z][a-z0-9_.]+$/)||value.version<1)fail("UNKNOWN_MODULE","Invalid module identity.");for(const code of value.satisfiesRequirementCodes)if(!ONBOARDING_REGISTRY[code])fail("ONBOARDING_CONFIGURATION_INVALID","Unknown onboarding requirement.");if(value.responsibility==="system"&&value.completionMode!=="system_verification"&&value.completionMode!=="provisioning_result")fail("ONBOARDING_CONFIGURATION_INVALID","System modules require system completion.");if(value.skippable&&!value.skipPolicyCode)fail("ONBOARDING_CONFIGURATION_INVALID","Skippable modules require policy.");return freeze(value)}
export function validateTemplate(template:OnboardingTemplate,modules:Readonly<Record<string,OnboardingModuleDefinition>>){if(!template.completionPolicyCode||!template.handoffPolicyCode)fail("ONBOARDING_CONFIGURATION_INVALID","Completion and handoff policies are required.");for(const ref of template.moduleDefinitions)if(!modules[`${ref.moduleCode}@${ref.moduleVersion}`])fail("UNKNOWN_MODULE","Template references an unknown module.");const codes=new Set(template.moduleDefinitions.map(x=>x.moduleCode)),visiting=new Set<string>(),visited=new Set<string>();const walk=(code:string)=>{if(visiting.has(code))fail("ONBOARDING_CONFIGURATION_INVALID","Circular module dependency.");if(visited.has(code))return;visiting.add(code);for(const dependency of modules[`${code}@${template.moduleDefinitions.find(x=>x.moduleCode===code)?.moduleVersion}`]?.prerequisiteModuleCodes??[])if(codes.has(dependency))walk(dependency);visiting.delete(code);visited.add(code)};for(const code of codes)walk(code);return freeze(template)}
export function assertCaseTransition(from:OnboardingCaseStatus,to:OnboardingCaseStatus){const transitions:Record<OnboardingCaseStatus,readonly OnboardingCaseStatus[]>={pending:["ready","blocked","cancelled"],ready:["in_progress","blocked","cancelled"],in_progress:["customer_action_required","internal_action_required","ready_for_provisioning","blocked","cancelled"],customer_action_required:["in_progress","internal_action_required","blocked","cancelled"],internal_action_required:["in_progress","ready_for_provisioning","blocked","cancelled"],blocked:["in_progress","customer_action_required","internal_action_required","cancelled"],ready_for_provisioning:["provisioning","blocked","cancelled"],provisioning:["ready_for_handoff","blocked"],ready_for_handoff:["completed","blocked"],completed:[],cancelled:[]};if(from!==to&&!transitions[from].includes(to))fail("INVALID_TRANSITION","Invalid onboarding case transition.")}
export function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child)}return value}function fail(code:OnboardingError["code"],message:string):never{throw new OnboardingError(code,message)}
