import{freeze,validateModuleDefinition,validateTemplate,type OnboardingModuleDefinition,type OnboardingTemplate}from"./model";
const registerModule=(value:OnboardingModuleDefinition)=>validateModuleDefinition(value);const base=(code:string,name:string,extra:Partial<OnboardingModuleDefinition>):OnboardingModuleDefinition=>registerModule({code,version:1,name,description:name,satisfiesRequirementCodes:[],responsibility:"customer",completionMode:"customer_submission",prerequisiteModuleCodes:[],compositionStrategy:"once_per_commercial_engagement",dataClassification:"standard",skippable:false,status:"active",...extra});
const definitions=[
 base("shared.customer_profile","Customer profile",{satisfiesRequirementCodes:["accept_terms"],compositionStrategy:"shared_once",fieldSchemaCode:"customer_profile.v1",estimatedMinutes:3}),
 base("hpm.workspace_setup","Workspace setup",{productFamily:"hpm",satisfiesRequirementCodes:["create_workspace"],prerequisiteModuleCodes:["shared.customer_profile"],compositionStrategy:"once_per_product_family",fieldSchemaCode:"business_profile.v1"}),
 base("hpm.property_context","HPM property context",{productFamily:"hpm",satisfiesRequirementCodes:["create_or_select_property","complete_property_profile"],prerequisiteModuleCodes:["hpm.workspace_setup"],compositionStrategy:"once_per_property_context",fieldSchemaCode:"hpm_property.v1"}),
 base("hpm.data_path","Booking data path",{productFamily:"hpm",satisfiesRequirementCodes:["connect_data_source","upload_historical_data"],prerequisiteModuleCodes:["hpm.property_context"],compositionStrategy:"once_per_product_family",fieldSchemaCode:"hpm_data_path.v1",skippable:true,skipPolicyCode:"manual_data_alternative.v1"}),
 base("hpm.provision","Provision HPM workspace",{productFamily:"hpm",responsibility:"system",completionMode:"provisioning_result",prerequisiteModuleCodes:["hpm.property_context"],compositionStrategy:"once_per_product_family",provisioningActionCode:"hpm.workspace.provision.v1"}),
 base("guidebook.brand","Guidebook brand setup",{productFamily:"guidebook_studio",prerequisiteModuleCodes:["shared.customer_profile"],compositionStrategy:"once_per_product_family",fieldSchemaCode:"guidebook_brand.v1"}),
 base("guidebook.property","Standalone Guidebook property",{productFamily:"guidebook_studio",satisfiesRequirementCodes:["complete_guidebook_intake"],prerequisiteModuleCodes:["guidebook.brand"],compositionStrategy:"once_per_property_context",fieldSchemaCode:"guidebook_property.v1"}),
 base("guidebook.draft","Create editable Guidebook draft",{productFamily:"guidebook_studio",responsibility:"system",completionMode:"provisioning_result",prerequisiteModuleCodes:["guidebook.property"],compositionStrategy:"once_per_commercial_engagement",provisioningActionCode:"guidebook.draft.provision.v1"}),
 base("furnishing.discovery","Furnishing discovery",{productFamily:"furnishing",satisfiesRequirementCodes:["complete_furnishing_intake"],prerequisiteModuleCodes:["shared.customer_profile"],compositionStrategy:"once_per_commercial_engagement",fieldSchemaCode:"furnishing_discovery.v1",dataClassification:"confidential"}),
 base("furnishing.review","Internal scope review",{productFamily:"furnishing",responsibility:"internal",completionMode:"internal_confirmation",prerequisiteModuleCodes:["furnishing.discovery"],compositionStrategy:"once_per_commercial_engagement",dataClassification:"confidential"}),
 base("investment.criteria","Investment criteria",{productFamily:"investment_intelligence",satisfiesRequirementCodes:["complete_investment_profile"],prerequisiteModuleCodes:["shared.customer_profile"],compositionStrategy:"once_per_commercial_engagement",fieldSchemaCode:"investment_criteria.v1",dataClassification:"confidential"}),
 base("investment.analysis","Create first saved analysis",{productFamily:"investment_intelligence",responsibility:"system",completionMode:"provisioning_result",prerequisiteModuleCodes:["investment.criteria"],compositionStrategy:"once_per_commercial_engagement",provisioningActionCode:"investment.analysis.provision.v1"}),
];
export const ONBOARDING_MODULE_REGISTRY=freeze(Object.fromEntries(definitions.map(value=>[`${value.code}@${value.version}`,value]))as Record<string,OnboardingModuleDefinition>);
const template=(code:string,family:NonNullable<OnboardingTemplate["appliesTo"]["productFamily"]>,refs:readonly string[]):OnboardingTemplate=>validateTemplate({code,version:1,name:`${family} onboarding`,appliesTo:{productFamily:family},moduleDefinitions:refs.map(moduleCode=>({moduleCode,moduleVersion:1,required:true})),completionPolicyCode:"all_required_verified.v1",handoffPolicyCode:`${family}.handoff.v1`,status:"active",effectiveFrom:"2026-08-11T00:00:00Z",createdBy:"system",createdAt:"2026-08-11T00:00:00Z"},ONBOARDING_MODULE_REGISTRY);
export const ONBOARDING_TEMPLATE_REGISTRY=freeze({
 "hpm.v1":template("hpm.v1","hpm",["shared.customer_profile","hpm.workspace_setup","hpm.property_context","hpm.data_path","hpm.provision"]),
 "guidebook_studio.v1":template("guidebook_studio.v1","guidebook_studio",["shared.customer_profile","guidebook.brand","guidebook.property","guidebook.draft"]),
 "furnishing.v1":template("furnishing.v1","furnishing",["shared.customer_profile","furnishing.discovery","furnishing.review"]),
 "investment_intelligence.v1":template("investment_intelligence.v1","investment_intelligence",["shared.customer_profile","investment.criteria","investment.analysis"]),
});
