import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminSectionCard } from "@/components/admin/admin-section-card";
import { saveFoundingDiscovery,saveFoundingQualification } from "@/app/actions/founding-partners";
import { addFoundingPartnerProperty,deleteFoundingPartnerProperty,saveFoundingBaselinePillar,saveFoundingDataConnection } from "@/app/actions/founding-partners-activate";
import { saveFoundingAction,saveFoundingDay90Review,saveFoundingFeedback,saveFoundingMonthlyReview,saveFoundingOpportunity,saveFoundingOutcome,updateFoundingOpportunityStatus } from "@/app/actions/founding-partners-learn";
import { BASELINE_STATUSES,CONNECTION_STATUSES,FOUNDING_PARTNER_DATA_SOURCES,FOUNDING_PARTNER_DATA_SOURCE_LABELS,HPM_PILLARS,HPM_PILLAR_LABELS } from "@/features/founding-partners/activate";
import { ACTION_STATUSES,DAY90_NEXT_STEP_LABELS,DAY90_NEXT_STEPS,FEEDBACK_TYPES,FEEDBACK_TYPE_LABELS,OPPORTUNITY_CONFIDENCE,OPPORTUNITY_STATUSES,OUTCOME_STATUSES,SIGNAL_MATURITIES,SIGNAL_MATURITY_LABELS } from "@/features/founding-partners/learn";
export const dynamic = "force-dynamic";
const fit=["strong","moderate","weak","unknown"];
const Select=({name,label,value="unknown"}:{name:string;label:string;value?:string})=><label className="grid gap-2 text-sm font-semibold">{label}<select name={name} defaultValue={value} className="min-h-11 rounded-lg border px-3 font-normal">{fit.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label>;
const Area=({name,label,value=""}:{name:string;label:string;value?:string})=><label className="grid gap-2 text-sm font-semibold">{label}<textarea name={name} defaultValue={value} rows={4} className="rounded-lg border p-3 font-normal"/></label>;
const Field=({name,label,type="text",value=""}:{name:string;label:string;type?:string;value?:string|number})=><label className="grid gap-2 text-sm font-semibold">{label}<input name={name} type={type} defaultValue={value} className="min-h-11 rounded-lg border px-3 font-normal"/></label>;
const tabs=["overview","discovery","baseline","opportunities","actions-outcomes","reviews","feedback","day90-review"] as const;
function Tabs({programId,current}:{programId:string;current:string}){
  return <nav className="overflow-x-auto border-b"><div className="flex min-w-max gap-6">{tabs.map(x=><Link key={x} href={`/admin/customers/programs/${programId}?tab=${x}`} className={`border-b-2 py-3 text-sm font-semibold capitalize ${current===x?"border-emerald-700":"border-transparent text-stone-500"}`}>{x.replaceAll("-"," ")}</Link>)}</div></nav>;
}
function StepPill({label,complete}:{label:string;complete:boolean}){
  return <div className="flex items-center gap-2 rounded-full border px-3 py-2 text-sm"><span className={`flex size-5 items-center justify-center rounded-full text-xs ${complete?"bg-emerald-700 text-white":"border"}`}>{complete?"✓":""}</span>{label}</div>;
}
export default async function ProgramPage({params,searchParams}:{params:Promise<{programId:string}>;searchParams:Promise<{tab?:string}>}){
  await requireRole(["admin"]);
  const {programId:id}=await params,tab=(await searchParams).tab??"overview",db=createAdminClient();
  const {data:program}=await db.from("customer_programs").select("*,customer_accounts(*),founding_partner_applications(*),founding_partner_qualifications(*),founding_partner_discovery(*),founding_partner_properties(*),founding_partner_data_connections(*),founding_partner_baseline(*),founding_partner_opportunities(*),founding_partner_actions(*,founding_partner_outcomes(*)),founding_partner_monthly_reviews(*),founding_partner_feedback(*),founding_partner_day90_reviews(*)").eq("id",id).maybeSingle();
  if(!program)notFound();
  const customer=program.customer_accounts as unknown as Record<string,unknown>,
    app=((program.founding_partner_applications??[])as unknown as Array<Record<string,unknown>>)[0],
    q=((program.founding_partner_qualifications??[])as unknown as Array<Record<string,unknown>>)[0]??{},
    d=((program.founding_partner_discovery??[])as unknown as Array<Record<string,unknown>>)[0]??{},
    properties=(program.founding_partner_properties??[])as unknown as Array<Record<string,unknown>>,
    connections=(program.founding_partner_data_connections??[])as unknown as Array<Record<string,unknown>>,
    baseline=(program.founding_partner_baseline??[])as unknown as Array<Record<string,unknown>>,
    opportunities=(program.founding_partner_opportunities??[])as unknown as Array<Record<string,unknown>>,
    actions=(program.founding_partner_actions??[])as unknown as Array<Record<string,unknown>&{founding_partner_outcomes?:Array<Record<string,unknown>>}>,
    monthlyReviews=((program.founding_partner_monthly_reviews??[])as unknown as Array<Record<string,unknown>>).slice().sort((a,b)=>String(b.review_month).localeCompare(String(a.review_month))),
    feedback=((program.founding_partner_feedback??[])as unknown as Array<Record<string,unknown>>).slice().sort((a,b)=>String(b.captured_at).localeCompare(String(a.captured_at))),
    day90Review=((program.founding_partner_day90_reviews??[])as unknown as Array<Record<string,unknown>>)[0];
  const steps=[
    {label:"Business profile",complete:Boolean(app)},
    {label:"Properties",complete:properties.length>0},
    {label:"Systems & data",complete:connections.length>=FOUNDING_PARTNER_DATA_SOURCES.length},
    {label:"Business goals",complete:Boolean(d?.twelve_month_build)},
    {label:"Baseline",complete:baseline.length>=HPM_PILLARS.length},
  ];
  return <div className="space-y-8 py-8">
    <div className="text-sm text-stone-500"><Link href="/admin/customers">Customers</Link> → {String(customer.display_name)} → Programs → Founding HPM Partner</div>
    <AdminPageHeader title="Founding HPM Partner Workspace" description={`${String(customer.display_name)} · Cohort ${String(program.cohort)} · ${String(program.program_status)}`}/>
    <Tabs programId={id} current={tab}/>
    {tab==="overview"?<>
      <AdminSectionCard><div className="grid gap-4 md:grid-cols-4"><Metric label="Lifecycle" value={String(customer.lifecycle_stage)}/><Metric label="Program status" value={String(program.program_status)}/><Metric label="Properties" value={String(app?.property_count??"—")}/><Metric label="Next action" value={String(program.next_action??"—")}/></div></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Onboarding progress</h2><div className="mt-5 flex flex-wrap gap-3">{steps.map(s=><StepPill key={s.label} label={s.label} complete={s.complete}/>)}</div></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Application</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Metric label="Operating model" value={String(app?.operating_model??"—")}/><Metric label="Primary markets" value={String(app?.primary_markets??"—")}/><Metric label="12-month goal" value={String(app?.twelve_month_goal??"—")}/><Metric label="Primary difficulty" value={String(app?.primary_difficulty??"—")}/></div></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Fit assessment</h2><form action={saveFoundingQualification} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Select name="growthOrientation" label="Growth orientation" value={String(q.growth_orientation??"unknown")}/><Select name="businessSeriousness" label="Business seriousness" value={String(q.business_seriousness??"unknown")}/><Select name="technologyOpenness" label="Technology openness" value={String(q.technology_openness??"unknown")}/><Select name="feedbackWillingness" label="Feedback willingness" value={String(q.feedback_willingness??"unknown")}/><Select name="hpmProblemFit" label="HPM problem fit" value={String(q.hpm_problem_fit??"unknown")}/><Select name="learningValue" label="Learning value" value={String(q.learning_value??"unknown")}/><label className="grid gap-2 text-sm font-semibold">Recommendation<select name="recommendation" defaultValue={String(q.recommendation??"discuss")} className="min-h-11 rounded-lg border px-3 font-normal"><option value="recommended">Recommended</option><option value="discuss">Discuss</option><option value="not_fit">Not Fit</option></select></label><Area name="notes" label="Required notes / reason" value={String(q.notes??"")}/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save qualification</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Properties</h2><ul className="mt-5 grid gap-3">{properties.map(p=><li key={String(p.id)} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-semibold">{String(p.name)}</p><p className="text-sm text-stone-500">{String(p.address??"—")} · {String(p.property_type??"—")} · {String(p.unit_count??"—")} units</p></div><form action={deleteFoundingPartnerProperty}><input type="hidden" name="programId" value={id}/><input type="hidden" name="propertyId" value={String(p.id)}/><button className="rounded-lg border px-3 py-2 text-sm">Remove</button></form></li>)}{properties.length===0?<p className="text-sm text-stone-500">No properties captured yet.</p>:null}</ul>
        <form action={addFoundingPartnerProperty} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Field name="name" label="Property name"/><Field name="address" label="Address"/><Field name="propertyType" label="Property type"/><Field name="unitCount" label="Unit count" type="number"/><Area name="notes" label="Notes"/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Add property</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Data connections</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{FOUNDING_PARTNER_DATA_SOURCES.map(source=>{const existing=connections.find(c=>c.source_type===source)??{};return <form key={source} action={saveFoundingDataConnection} className="grid gap-3 rounded-lg border p-4"><input type="hidden" name="programId" value={id}/><input type="hidden" name="sourceType" value={source}/><p className="font-semibold">{FOUNDING_PARTNER_DATA_SOURCE_LABELS[source]}</p><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue={String(existing.status??"missing")} className="min-h-11 rounded-lg border px-3 font-normal">{CONNECTION_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><Area name="notes" label="Notes" value={String(existing.notes??"")}/><button className="rounded-lg border px-4 py-2 text-sm font-semibold">Save</button></form>;})}</div></AdminSectionCard>
    </>:null}
    {tab==="discovery"?<AdminSectionCard><h2 className="text-xl font-semibold">Discovery</h2><form action={saveFoundingDiscovery} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Area name="businessNotes" label="Business" value={String(d.business_notes??"")}/><Area name="performanceNotes" label="Performance" value={String(d.performance_notes??"")}/><Area name="systemsNotes" label="Systems" value={String(d.systems_notes??"")}/><Area name="decisionsNotes" label="Decisions" value={String(d.decisions_notes??"")}/><Area name="hpmReactionNotes" label="HPM reaction" value={String(d.hpm_reaction_notes??"")}/><Area name="partnershipFitNotes" label="Partnership fit" value={String(d.partnership_fit_notes??"")}/><Area name="twelveMonthBuild" label="What are you building over the next 12 months?" value={String(d.twelve_month_build??"")}/><Area name="informationGapDecision" label="Last important decision without enough information" value={String(d.information_gap_decision??"")}/><Area name="tomorrowQuestion" label="One thing they wish they knew tomorrow" value={String(d.tomorrow_question??"")}/><Area name="rationale" label="Decision rationale" value={String(d.rationale??"")}/><label className="grid gap-2 text-sm font-semibold">Outcome<select name="outcome" defaultValue={String(d.outcome??"hold")} className="min-h-11 rounded-lg border px-3 font-normal"><option value="accept">Accept</option><option value="hold">Hold</option><option value="decline">Decline</option></select></label><button className="rounded-lg bg-amber-500 px-5 py-3 font-semibold md:col-span-2">Complete discovery</button></form></AdminSectionCard>:null}
    {tab==="baseline"?<AdminSectionCard><h2 className="text-xl font-semibold">HPM baseline</h2><p className="mt-2 text-sm text-stone-600">Represents data sufficiency, not a computed HPM score.</p><div className="mt-5 grid gap-5 md:grid-cols-2">{HPM_PILLARS.map(pillar=>{const existing=baseline.find(b=>b.pillar===pillar)??{};return <form key={pillar} action={saveFoundingBaselinePillar} className="grid gap-3 rounded-lg border p-4"><input type="hidden" name="programId" value={id}/><input type="hidden" name="pillar" value={pillar}/><p className="font-semibold">{HPM_PILLAR_LABELS[pillar]}</p><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue={String(existing.status??"insufficient_data")} className="min-h-11 rounded-lg border px-3 font-normal">{BASELINE_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><Field name="dataCompletenessPercent" label="Data completeness %" type="number" value={Number(existing.data_completeness_percent??0)}/><Area name="notes" label="Notes" value={String(existing.notes??"")}/><button className="rounded-lg border px-4 py-2 text-sm font-semibold">Save</button></form>;})}</div></AdminSectionCard>:null}
    {tab==="opportunities"?<>
      <AdminSectionCard><h2 className="text-xl font-semibold">Add opportunity</h2><form action={saveFoundingOpportunity} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Field name="title" label="Opportunity title"/><label className="grid gap-2 text-sm font-semibold">Pillar<select name="pillar" defaultValue="" className="min-h-11 rounded-lg border px-3 font-normal"><option value="">—</option>{HPM_PILLARS.map(p=><option key={p} value={p}>{HPM_PILLAR_LABELS[p]}</option>)}</select></label><Area name="evidence" label="Supporting evidence"/><Area name="whyItMatters" label="Why it matters"/><Field name="estimatedImpact" label="Estimated impact"/><label className="grid gap-2 text-sm font-semibold">Confidence<select name="confidence" defaultValue="unknown" className="min-h-11 rounded-lg border px-3 font-normal">{OPPORTUNITY_CONFIDENCE.map(c=><option key={c} value={c}>{c[0].toUpperCase()+c.slice(1)}</option>)}</select></label><Area name="recommendedAction" label="Recommended decision / action"/><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue="identified" className="min-h-11 rounded-lg border px-3 font-normal">{OPPORTUNITY_STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></label><Field name="sourceLineage" label="Source lineage"/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save opportunity</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Opportunities</h2><ul className="mt-5 grid gap-3">{opportunities.map(o=><li key={String(o.id)} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{String(o.title)}</p><p className="text-sm text-stone-500">{o.pillar?HPM_PILLAR_LABELS[o.pillar as (typeof HPM_PILLARS)[number]]:"—"} · Confidence: {String(o.confidence)}</p></div><form action={updateFoundingOpportunityStatus} className="flex items-center gap-2"><input type="hidden" name="programId" value={id}/><input type="hidden" name="opportunityId" value={String(o.id)}/><select name="status" defaultValue={String(o.status)} className="min-h-9 rounded-lg border px-2 text-sm">{OPPORTUNITY_STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="rounded-lg border px-3 py-2 text-sm">Update</button></form></div>{o.evidence?<p className="mt-2 text-sm text-stone-600">{String(o.evidence)}</p>:null}</li>)}{opportunities.length===0?<p className="text-sm text-stone-500">No opportunities identified yet.</p>:null}</ul></AdminSectionCard>
    </>:null}
    {tab==="actions-outcomes"?<>
      <AdminSectionCard><h2 className="text-xl font-semibold">Add action</h2><form action={saveFoundingAction} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><label className="grid gap-2 text-sm font-semibold">Related opportunity<select name="opportunityId" defaultValue="" className="min-h-11 rounded-lg border px-3 font-normal"><option value="">—</option>{opportunities.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.title)}</option>)}</select></label><Field name="owner" label="Owner"/><Area name="decision" label="Decision"/><Area name="actionDescription" label="Action"/><Field name="targetDate" label="Target date" type="date"/><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue="planned" className="min-h-11 rounded-lg border px-3 font-normal">{ACTION_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save action</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Actions & outcomes</h2><ul className="mt-5 grid gap-4">{actions.map(a=>{const outcome=(a.founding_partner_outcomes??[])[0];return <li key={String(a.id)} className="rounded-lg border p-4"><p className="font-semibold">{String(a.decision)}</p><p className="text-sm text-stone-500">Owner: {String(a.owner||"—")} · Status: {String(a.status)} · Target: {String(a.target_date??"—")}</p>
        <form action={saveFoundingOutcome} className="mt-4 grid gap-3 md:grid-cols-2 rounded-lg bg-stone-50 p-4"><input type="hidden" name="programId" value={id}/><input type="hidden" name="actionId" value={String(a.id)}/><label className="grid gap-2 text-sm font-semibold">Outcome status<select name="status" defaultValue={String(outcome?.status??"not_measured")} className="min-h-11 rounded-lg border px-3 font-normal">{OUTCOME_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><Field name="estimatedValue" label="Estimated value" value={String(outcome?.estimated_value??"")}/><Field name="realizedValue" label="Realized value" value={String(outcome?.realized_value??"")}/><Area name="notes" label="Notes" value={String(outcome?.notes??"")}/><button className="rounded-lg border px-4 py-2 text-sm font-semibold md:col-span-2">Save outcome</button></form>
      </li>;})}{actions.length===0?<p className="text-sm text-stone-500">No actions recorded yet.</p>:null}</ul></AdminSectionCard>
    </>:null}
    {tab==="reviews"?<>
      <AdminSectionCard><h2 className="text-xl font-semibold">New monthly review</h2><form action={saveFoundingMonthlyReview} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Field name="reviewMonth" label="Review month" type="month"/><Area name="summary" label="Summary"/><Area name="wins" label="Wins"/><Area name="challenges" label="Challenges"/><Area name="nextFocus" label="Next focus"/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save review</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Prior reviews</h2><ul className="mt-5 grid gap-4">{monthlyReviews.map(r=><li key={String(r.id)} className="rounded-lg border p-4"><p className="font-semibold">{String(r.review_month)}</p><p className="mt-2 whitespace-pre-wrap text-sm text-stone-600">{String(r.summary)}</p></li>)}{monthlyReviews.length===0?<p className="text-sm text-stone-500">No reviews recorded yet.</p>:null}</ul></AdminSectionCard>
    </>:null}
    {tab==="feedback"?<>
      <AdminSectionCard><h2 className="text-xl font-semibold">Capture feedback</h2><form action={saveFoundingFeedback} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><label className="grid gap-2 text-sm font-semibold">Type<select name="feedbackType" defaultValue={FEEDBACK_TYPES[0]} className="min-h-11 rounded-lg border px-3 font-normal">{FEEDBACK_TYPES.map(t=><option key={t} value={t}>{FEEDBACK_TYPE_LABELS[t]}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Signal maturity<select name="signalMaturity" defaultValue={SIGNAL_MATURITIES[0]} className="min-h-11 rounded-lg border px-3 font-normal">{SIGNAL_MATURITIES.map(m=><option key={m} value={m}>{SIGNAL_MATURITY_LABELS[m]}</option>)}</select></label><Field name="summary" label="Summary"/><Area name="detail" label="Detail"/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save feedback</button></form></AdminSectionCard>
      <AdminSectionCard><h2 className="text-xl font-semibold">Feedback log</h2><ul className="mt-5 grid gap-3">{feedback.map(f=><li key={String(f.id)} className="rounded-lg border p-4"><p className="font-semibold">{FEEDBACK_TYPE_LABELS[f.feedback_type as (typeof FEEDBACK_TYPES)[number]]} · {SIGNAL_MATURITY_LABELS[f.signal_maturity as (typeof SIGNAL_MATURITIES)[number]]}</p><p className="mt-1 text-sm text-stone-600">{String(f.summary)}</p></li>)}{feedback.length===0?<p className="text-sm text-stone-500">No feedback captured yet.</p>:null}</ul></AdminSectionCard>
    </>:null}
    {tab==="day90-review"?<AdminSectionCard><h2 className="text-xl font-semibold">Day-90 review</h2>{day90Review?<div className="mt-5 grid gap-4"><Metric label="Recommended next step" value={DAY90_NEXT_STEP_LABELS[day90Review.recommended_next_step as (typeof DAY90_NEXT_STEPS)[number]]}/><Metric label="Value delivered" value={String(day90Review.value_delivered??"—")}/><Metric label="Would pay to continue" value={day90Review.would_pay===true?"Yes":day90Review.would_pay===false?"No":"Unavailable"}/><Metric label="Rationale" value={String(day90Review.rationale)}/></div>:<form action={saveFoundingDay90Review} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Area name="valueDelivered" label="Value delivered"/><label className="grid gap-2 text-sm font-semibold">Would they pay to continue?<select name="wouldPay" defaultValue="" className="min-h-11 rounded-lg border px-3 font-normal"><option value="">Unavailable</option><option value="yes">Yes</option><option value="no">No</option></select></label><Area name="willingnessToPayNotes" label="Why or why not"/><Area name="testimonialCapture" label="Testimonial / what would make the buying decision obvious"/><label className="grid gap-2 text-sm font-semibold">Recommended next step<select name="recommendedNextStep" defaultValue={DAY90_NEXT_STEPS[0]} className="min-h-11 rounded-lg border px-3 font-normal">{DAY90_NEXT_STEPS.map(s=><option key={s} value={s}>{DAY90_NEXT_STEP_LABELS[s]}</option>)}</select></label><Area name="rationale" label="Rationale"/><button className="rounded-lg bg-amber-500 px-5 py-3 font-semibold md:col-span-2">Complete Day-90 review</button></form>}</AdminSectionCard>:null}
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 whitespace-pre-wrap">{value}</p></div>}
