import Link from "next/link";
import { notFound } from "next/navigation";
import { requireRole } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminSectionCard } from "@/components/admin/admin-section-card";
import { saveFoundingDiscovery,saveFoundingQualification } from "@/app/actions/founding-partners";
const fit=["strong","moderate","weak","unknown"];
const Select=({name,label,value="unknown"}:{name:string;label:string;value?:string})=><label className="grid gap-2 text-sm font-semibold">{label}<select name={name} defaultValue={value} className="min-h-11 rounded-lg border px-3 font-normal">{fit.map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label>;
const Area=({name,label,value=""}:{name:string;label:string;value?:string})=><label className="grid gap-2 text-sm font-semibold">{label}<textarea name={name} defaultValue={value} rows={4} className="rounded-lg border p-3 font-normal"/></label>;
export default async function ProgramPage({params}:{params:Promise<{programId:string}>}){await requireRole(["admin"]);const{id}=await Promise.resolve({id:(await params).programId}),db=createAdminClient();const{data:program}=await db.from("customer_programs").select("*,customer_accounts(*),founding_partner_applications(*),founding_partner_qualifications(*),founding_partner_discovery(*)").eq("id",id).maybeSingle();if(!program)notFound();const customer=program.customer_accounts as unknown as Record<string,unknown>,app=((program.founding_partner_applications??[])as unknown as Array<Record<string,unknown>>)[0],q=((program.founding_partner_qualifications??[])as unknown as Array<Record<string,unknown>>)[0]??{},d=((program.founding_partner_discovery??[])as unknown as Array<Record<string,unknown>>)[0]??{};
return <div className="space-y-8 py-8"><div className="text-sm text-stone-500"><Link href="/admin/customers">Customers</Link> → {String(customer.display_name)} → Programs → Founding HPM Partner</div><AdminPageHeader title="Founding HPM Partner Workspace" description={`${String(customer.display_name)} · Cohort ${String(program.cohort)} · ${String(program.program_status)}`}/>
<AdminSectionCard><div className="grid gap-4 md:grid-cols-4"><Metric label="Lifecycle" value={String(customer.lifecycle_stage)}/><Metric label="Program status" value={String(program.program_status)}/><Metric label="Properties" value={String(app?.property_count??"—")}/><Metric label="Next action" value={String(program.next_action??"—")}/></div></AdminSectionCard>
<AdminSectionCard><h2 className="text-xl font-semibold">Application</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><Metric label="Operating model" value={String(app?.operating_model??"—")}/><Metric label="Primary markets" value={String(app?.primary_markets??"—")}/><Metric label="12-month goal" value={String(app?.twelve_month_goal??"—")}/><Metric label="Primary difficulty" value={String(app?.primary_difficulty??"—")}/></div></AdminSectionCard>
<AdminSectionCard><h2 className="text-xl font-semibold">Fit assessment</h2><form action={saveFoundingQualification} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Select name="growthOrientation" label="Growth orientation" value={String(q.growth_orientation??"unknown")}/><Select name="businessSeriousness" label="Business seriousness" value={String(q.business_seriousness??"unknown")}/><Select name="technologyOpenness" label="Technology openness" value={String(q.technology_openness??"unknown")}/><Select name="feedbackWillingness" label="Feedback willingness" value={String(q.feedback_willingness??"unknown")}/><Select name="hpmProblemFit" label="HPM problem fit" value={String(q.hpm_problem_fit??"unknown")}/><Select name="learningValue" label="Learning value" value={String(q.learning_value??"unknown")}/><label className="grid gap-2 text-sm font-semibold">Recommendation<select name="recommendation" defaultValue={String(q.recommendation??"discuss")} className="min-h-11 rounded-lg border px-3 font-normal"><option value="recommended">Recommended</option><option value="discuss">Discuss</option><option value="not_fit">Not Fit</option></select></label><Area name="notes" label="Required notes / reason" value={String(q.notes??"")}/><button className="rounded-lg bg-stone-950 px-5 py-3 font-semibold text-white md:col-span-2">Save qualification</button></form></AdminSectionCard>
<AdminSectionCard><h2 className="text-xl font-semibold">Discovery</h2><form action={saveFoundingDiscovery} className="mt-5 grid gap-5 md:grid-cols-2"><input type="hidden" name="programId" value={id}/><Area name="businessNotes" label="Business" value={String(d.business_notes??"")}/><Area name="performanceNotes" label="Performance" value={String(d.performance_notes??"")}/><Area name="systemsNotes" label="Systems" value={String(d.systems_notes??"")}/><Area name="decisionsNotes" label="Decisions" value={String(d.decisions_notes??"")}/><Area name="hpmReactionNotes" label="HPM reaction" value={String(d.hpm_reaction_notes??"")}/><Area name="partnershipFitNotes" label="Partnership fit" value={String(d.partnership_fit_notes??"")}/><Area name="twelveMonthBuild" label="What are you building over the next 12 months?" value={String(d.twelve_month_build??"")}/><Area name="informationGapDecision" label="Last important decision without enough information" value={String(d.information_gap_decision??"")}/><Area name="tomorrowQuestion" label="One thing they wish they knew tomorrow" value={String(d.tomorrow_question??"")}/><Area name="rationale" label="Decision rationale" value={String(d.rationale??"")}/><label className="grid gap-2 text-sm font-semibold">Outcome<select name="outcome" defaultValue={String(d.outcome??"hold")} className="min-h-11 rounded-lg border px-3 font-normal"><option value="accept">Accept</option><option value="hold">Hold</option><option value="decline">Decline</option></select></label><button className="rounded-lg bg-amber-500 px-5 py-3 font-semibold md:col-span-2">Complete discovery</button></form></AdminSectionCard></div>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 whitespace-pre-wrap">{value}</p></div>}
