import{describe,expect,it}from"vitest";import{DEFAULT_INTEGRATION_PROVIDERS}from"@/features/integrations";import{assertTicketTransition,calculateHealth,calculateSuccessRate,configurationStatus,INTEGRATION_REGISTRY,sanitizeAuditMetadata}from".";import{resolveReportingPeriod}from"../application/reporting-period";
describe("admin operations policies",()=>{
 it("registers every active adapter",()=>{const registered=new Set(INTEGRATION_REGISTRY.flatMap(x=>x.adapterIds));expect([...DEFAULT_INTEGRATION_PROVIDERS].map(x=>x.id).filter(id=>!registered.has(id))).toEqual([]);expect(registered).toEqual(new Set(["hospitable","realtyapi","rentcast","airroi","stripe","supabase","vercel","resend"]));});
 it("maps configuration without treating it as runtime health",()=>{const stripe=INTEGRATION_REGISTRY.find(x=>x.id==="stripe")!;expect(configurationStatus(stripe,{})).toBe("not_configured");expect(configurationStatus(stripe,{STRIPE_SECRET_KEY:"rk_test_x",STRIPE_WEBHOOK_SECRET:"whsec_x"})).toBe("configured");expect(configurationStatus(stripe,{STRIPE_SECRET_KEY:"rk_test_x"})).toBe("invalid");expect(configurationStatus(INTEGRATION_REGISTRY.find(x=>x.id==="rentcast")!,{MARKET_PROVIDER_ENABLED:"false"})).toBe("disabled");});
 it("keeps missing telemetry unknown and applies documented thresholds",()=>{expect(calculateHealth([])).toBe("unknown");const row=(outcome:"success"|"failure")=>({id:crypto.randomUUID(),integrationId:"stripe" as const,observedAt:new Date().toISOString(),outcome,source:"webhook" as const});expect(calculateHealth(Array.from({length:100},(_,i)=>row(i===0?"failure":"success")))).toBe("operational");expect(calculateHealth(Array.from({length:10},(_,i)=>row(i===0?"failure":"success")))).toBe("degraded");expect(calculateHealth([row("success"),row("failure")])).toBe("partial_outage");expect(calculateHealth([row("failure")])).toBe("outage");});
 it("calculates sync success without queued, running, partial, or cancelled inflation",()=>{expect(calculateSuccessRate(["queued","running","cancelled"])).toBeUndefined();expect(calculateSuccessRate(["succeeded","partially_succeeded","failed"])).toBe(33.3);});
 it("sanitizes prohibited metadata",()=>{expect(sanitizeAuditMetadata({provider:"stripe",secret:"x",address:"x",amountMinor:50,nested:{x:true},attempt:2})).toEqual({provider:"stripe",attempt:2});});
 it("resolves valid UTC reporting periods",()=>{expect(resolveReportingPeriod("health",{from:"2026-07-01",to:"2026-07-05"})).toMatchObject({from:"2026-07-01T00:00:00.000Z",to:"2026-07-05T23:59:59.999Z"});});
 it("enforces support ticket transitions",()=>{expect(()=>assertTicketTransition("closed","resolved")).toThrow(/Unsupported/);expect(()=>assertTicketTransition("resolved","open")).not.toThrow();});
});
