export const reportCategories = [
  "executive",
  "owner",
  "investment",
  "operations",
  "custom",
] as const;
export type ReportCategory = (typeof reportCategories)[number];
export type ReportFormat = "screen" | "pdf" | "csv" | "xlsx";
export type StandardReportAvailability =
  | "available"
  | "limited"
  | "unavailable";
export type StandardReportDefinition = Readonly<{
  id: string;
  version: number;
  category: ReportCategory;
  name: string;
  description: string;
  businessQuestion: string;
  supportedScopes: readonly (
    | "workspace"
    | "portfolio"
    | "property"
    | "owner"
    | "investment"
  )[];
  defaultPeriod:
    | "business-day"
    | "current-week"
    | "current-month"
    | "year-to-date"
    | "analysis-as-of"
    | "custom";
  supportedComparisons: readonly (
    | "none"
    | "previous-period"
    | "previous-year"
    | "budget"
    | "target"
  )[];
  supportedFormats: readonly ReportFormat[];
  requiredPermissions: readonly string[];
  requiredDataCapabilities: readonly string[];
  sections: readonly string[];
  availability: StandardReportAvailability;
  availabilityReason?: string;
  legacyReportType?:
    | "investment-decision"
    | "property-performance"
    | "portfolio-performance"
    | "financial-performance";
}>;

const all: readonly StandardReportDefinition[] = [
  d(
    "executive-performance-summary",
    "executive",
    "Executive Performance Summary",
    "A period-bound leadership record of business performance.",
    "How did the business perform during the period?",
    ["workspace", "portfolio"],
    "current-month",
    ["previous-period", "budget", "target"],
    ["screen", "pdf", "csv"],
    ["reports.executive.read"],
    ["revenue", "analytics", "financial", "portfolio", "actions"],
    [
      "performance-summary",
      "property-contribution",
      "risks-opportunities",
      "actions",
      "data-quality",
    ],
    "available",
    "portfolio-performance",
  ),
  d(
    "portfolio-health-report",
    "executive",
    "Portfolio Health Report",
    "Portfolio health, change, concentration, and data readiness.",
    "Where is portfolio performance healthy, deteriorating, or requiring attention?",
    ["workspace", "portfolio"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.executive.read"],
    ["portfolio", "revenue", "financial", "guest-experience"],
    [
      "portfolio-health",
      "property-ranking",
      "concentration-risk",
      "data-quality",
    ],
    "available",
    "portfolio-performance",
  ),
  d(
    "monthly-business-review",
    "executive",
    "Monthly Business Review",
    "An HPM lifecycle record of change, decisions, execution, and learning.",
    "What changed, why did it change, and what should leadership do next?",
    ["workspace", "portfolio"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf"],
    ["reports.executive.read"],
    ["executive-intelligence", "actions", "learning"],
    ["see", "understand", "decide", "execute", "learn"],
    "limited",
    "portfolio-performance",
    "Canonical narrative and learning coverage may be partial.",
  ),
  d(
    "strategic-performance-report",
    "executive",
    "Strategic Performance Report",
    "Progress against configured goals and initiatives.",
    "Are we progressing against our goals?",
    ["workspace", "portfolio"],
    "current-month",
    ["previous-period", "budget", "target"],
    ["screen", "pdf", "csv"],
    ["reports.executive.read"],
    ["goals", "financial-forecast", "actions"],
    ["goals", "variance", "forecast", "initiatives", "risks"],
    "limited",
    "portfolio-performance",
    "Runs with actual performance and explicitly marks goals, targets, forecasts, and variance unavailable until configured.",
  ),
  d(
    "executive-risk-opportunity-report",
    "executive",
    "Executive Risk and Opportunity Report",
    "Ranked canonical risks and opportunities with evidence and actions.",
    "What requires executive attention?",
    ["workspace", "portfolio"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.executive.read"],
    ["risks", "recommendations", "actions"],
    ["risks", "opportunities", "evidence", "recommendations", "actions"],
    "limited",
    "portfolio-performance",
    "Cross-capability exposure and upside values remain unavailable where canonical sources do not provide them.",
  ),
  d(
    "owner-statement",
    "owner",
    "Owner Statement",
    "A traceable operational owner balance statement.",
    "What did my property earn, and how was the owner balance calculated?",
    ["owner", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv", "xlsx"],
    ["reports.owner.read", "reports.financial.export"],
    ["financial-reconciliation", "owner-payments", "expenses"],
    [
      "revenue",
      "fees",
      "expenses",
      "adjustments",
      "reserves",
      "distributions",
      "reconciliation",
    ],
    "unavailable",
    undefined,
    "Canonical owner distributions and reconciliation are not configured; no balance will be fabricated.",
  ),
  d(
    "owner-performance-report",
    "owner",
    "Owner Performance Report",
    "Owner-safe property performance and comparison.",
    "How did my property perform?",
    ["owner", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.owner.read"],
    ["analytics", "bookings", "property"],
    ["revenue", "occupancy", "adr", "revpar", "booking-patterns", "freshness"],
    "available",
    "property-performance",
  ),
  d(
    "owner-expense-report",
    "owner",
    "Owner Expense Report",
    "Owner-safe expense detail and category totals.",
    "What expenses were incurred for my property?",
    ["owner", "property"],
    "current-month",
    ["previous-period", "budget"],
    ["screen", "pdf", "csv", "xlsx"],
    ["reports.owner.read", "reports.financial.export"],
    ["financial-expenses"],
    [
      "category-summary",
      "expense-detail",
      "recurrence",
      "capital-classification",
      "variance",
    ],
    "limited",
    undefined,
    "Vendor, approval, reimbursement, and receipt coverage may be unavailable.",
  ),
  d(
    "owner-revenue-distribution-report",
    "owner",
    "Owner Revenue and Distribution Report",
    "Traceable translation from bookings to owner proceeds.",
    "How did bookings translate into owner distributions?",
    ["owner", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.owner.read", "reports.financial.export"],
    ["owner-payments", "financial-reconciliation"],
    [
      "income",
      "deductions",
      "expenses",
      "fees",
      "reserves",
      "adjustments",
      "payments",
    ],
    "unavailable",
    undefined,
    "Canonical distribution and payment reconciliation is not configured.",
  ),
  d(
    "owner-annual-summary",
    "owner",
    "Owner Annual Summary",
    "An operational annual property summary with owner-safe disclosures.",
    "What happened over the full year?",
    ["owner", "property"],
    "year-to-date",
    ["previous-year"],
    ["screen", "pdf", "xlsx"],
    ["reports.owner.read"],
    ["analytics", "expenses", "owner-payments"],
    [
      "monthly-performance",
      "annual-proceeds",
      "capital-events",
      "distributions",
      "disclaimer",
    ],
    "limited",
    undefined,
    "Owner distribution coverage may be unavailable; this is not tax advice.",
  ),
  d(
    "acquisition-underwriting",
    "investment",
    "Acquisition Underwriting Report",
    "Immutable purchase underwriting with assumptions, evidence, and sensitivity.",
    "Should this property be acquired?",
    ["investment"],
    "analysis-as-of",
    ["none"],
    ["screen", "pdf"],
    ["reports.investment.read"],
    ["investment-analysis-version", "market-snapshot"],
    [
      "subject",
      "assumptions",
      "financing",
      "returns",
      "risks",
      "evidence",
      "sensitivity",
      "recommendation",
    ],
    "available",
    "investment-decision",
  ),
  d(
    "rental-arbitrage-underwriting",
    "investment",
    "Rental Arbitrage Underwriting Report",
    "Immutable lease-strategy underwriting and downside analysis.",
    "Does this lease support a viable hospitality operation?",
    ["investment"],
    "analysis-as-of",
    ["none"],
    ["screen", "pdf"],
    ["reports.investment.read"],
    ["investment-analysis-version"],
    [
      "lease",
      "startup",
      "revenue",
      "expenses",
      "cash-flow",
      "failure-points",
      "evidence",
      "recommendation",
    ],
    "available",
    "investment-decision",
  ),
  d(
    "market-comparable-analysis",
    "investment",
    "Market and Comparable Analysis",
    "Sanitized market evidence, comparable weighting, and limitations.",
    "What does available market evidence indicate?",
    ["investment", "property"],
    "analysis-as-of",
    ["none"],
    ["screen", "pdf", "csv"],
    ["reports.investment.read"],
    ["market-analysis", "comparables"],
    [
      "market-profile",
      "comparables",
      "ranges",
      "seasonality",
      "sources",
      "limitations",
    ],
    "limited",
    undefined,
    "Canonical market analysis exists; standard report-run orchestration is not yet connected.",
  ),
  d(
    "scenario-comparison",
    "investment",
    "Scenario Comparison Report",
    "Risk-adjusted comparison of immutable analysis scenarios.",
    "Which strategy or assumption set produces the best risk-adjusted outcome?",
    ["investment"],
    "analysis-as-of",
    ["none"],
    ["screen", "pdf", "csv"],
    ["reports.investment.read"],
    ["investment-scenarios"],
    [
      "assumption-differences",
      "outcomes",
      "returns",
      "break-even",
      "risk",
      "sensitivity",
      "recommendation",
    ],
    "limited",
    undefined,
    "Scenario comparison exists in Investment Intelligence; standardized report generation is pending.",
  ),
  d(
    "investment-decision-record",
    "investment",
    "Investment Decision Record",
    "Durable decision, evidence, rationale, actions, outcomes, and learning.",
    "What was decided, based on what evidence, and what happened afterward?",
    ["investment"],
    "analysis-as-of",
    ["none"],
    ["screen", "pdf"],
    ["reports.investment.read"],
    ["investment-decision", "actions", "outcomes", "learning"],
    [
      "decision",
      "alternatives",
      "rationale",
      "evidence",
      "actions",
      "reanalysis",
      "outcome",
      "learning",
    ],
    "limited",
    undefined,
    "Outcome and learning sections depend on elapsed measurement windows.",
  ),
  d(
    "daily-operations",
    "operations",
    "Daily Operations Report",
    "Business-date operational readiness and exceptions.",
    "What requires operational attention today?",
    ["workspace", "portfolio", "property"],
    "business-day",
    ["none"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["bookings", "operational-tasks", "guest-issues"],
    ["stays", "turnovers", "maintenance", "guest-issues", "actions", "alerts"],
    "limited",
    undefined,
    "Canonical cleaning and maintenance task coverage is incomplete.",
  ),
  d(
    "weekly-operations-summary",
    "operations",
    "Weekly Operations Summary",
    "Weekly execution volume, timeliness, exceptions, and pressure.",
    "How effectively did operations perform this week?",
    ["workspace", "portfolio", "property"],
    "current-week",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["bookings", "actions", "guest-issues"],
    [
      "stays",
      "tasks",
      "completion",
      "maintenance",
      "guest-issues",
      "exceptions",
      "outlook",
    ],
    "limited",
    undefined,
    "Task SLA and maintenance coverage are not fully configured.",
  ),
  d(
    "housekeeping-turnover",
    "operations",
    "Housekeeping and Turnover Report",
    "Turnover completion, inspection, rework, and readiness.",
    "Were properties prepared correctly and on time?",
    ["workspace", "portfolio", "property"],
    "current-week",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["turnovers", "inspections"],
    [
      "scheduled",
      "completed",
      "late",
      "duration",
      "assignment",
      "inspection",
      "rework",
      "readiness",
    ],
    "unavailable",
    undefined,
    "Canonical turnover and inspection records are not configured.",
  ),
  d(
    "maintenance-report",
    "operations",
    "Maintenance Report",
    "Maintenance volume, cost, recurrence, and unresolved work.",
    "What maintenance work occurred, and what remains unresolved?",
    ["workspace", "portfolio", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["maintenance"],
    [
      "open",
      "new",
      "completed",
      "resolution",
      "priority",
      "cost",
      "recurrence",
      "overdue",
    ],
    "unavailable",
    undefined,
    "Canonical maintenance work orders are not configured.",
  ),
  d(
    "guest-service-report",
    "operations",
    "Guest Service Report",
    "Sanitized guest-service trends without private message content.",
    "What guest-service issues affected the operation?",
    ["workspace", "portfolio", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["guest-service-issues"],
    [
      "category",
      "priority",
      "response",
      "resolution",
      "escalation",
      "recovery",
      "trends",
      "learning",
    ],
    "limited",
    undefined,
    "Issue summaries exist; canonical SLA policy and complete service recovery records do not.",
  ),
  d(
    "operational-execution",
    "operations",
    "Operational Execution Report",
    "Action creation, ownership, completion, outcomes, and learning.",
    "Are recommended and assigned actions being completed?",
    ["workspace", "portfolio", "property"],
    "current-month",
    ["previous-period"],
    ["screen", "pdf", "csv"],
    ["reports.operations.read"],
    ["actions", "outcomes", "learning"],
    [
      "created",
      "started",
      "completed",
      "overdue",
      "ownership",
      "priority",
      "outcomes",
      "learning",
    ],
    "limited",
    undefined,
    "Action data is canonical; outcome evidence may be incomplete.",
  ),
  d(
    "custom-report-builder",
    "custom",
    "Custom Report Builder",
    "Governed composition using approved subjects, measures, dimensions, and presentations.",
    "How can approved canonical measures be assembled for a specific review?",
    ["workspace", "portfolio", "property", "owner", "investment"],
    "custom",
    ["none", "previous-period", "previous-year"],
    ["screen"],
    ["reports.custom.create"],
    ["metric-registry", "subject-registry", "export-sanitization"],
    [
      "subject",
      "scope",
      "period",
      "measures",
      "dimensions",
      "filters",
      "presentation",
      "preview",
    ],
    "unavailable",
    undefined,
    "Under development until the approved metric, dimension, query, and sanitization registries are complete.",
  ),
];
export const standardReportRegistry = Object.freeze({
  definitions: Object.freeze(all),
  get(id: string) {
    return all.find((item) => item.id === id) ?? null;
  },
  byCategory(category: ReportCategory) {
    return all.filter((item) => item.category === category);
  },
});
export function isReportCategory(value: string): value is ReportCategory {
  return (reportCategories as readonly string[]).includes(value);
}
function d(
  id: string,
  category: ReportCategory,
  name: string,
  description: string,
  businessQuestion: string,
  supportedScopes: StandardReportDefinition["supportedScopes"],
  defaultPeriod: StandardReportDefinition["defaultPeriod"],
  supportedComparisons: StandardReportDefinition["supportedComparisons"],
  supportedFormats: StandardReportDefinition["supportedFormats"],
  requiredPermissions: readonly string[],
  requiredDataCapabilities: readonly string[],
  sections: readonly string[],
  availability: StandardReportAvailability,
  legacyReportType?: StandardReportDefinition["legacyReportType"],
  availabilityReason?: string,
): StandardReportDefinition {
  return Object.freeze({
    id,
    version: 1,
    category,
    name,
    description,
    businessQuestion,
    supportedScopes: Object.freeze(supportedScopes),
    defaultPeriod,
    supportedComparisons: Object.freeze(supportedComparisons),
    supportedFormats: Object.freeze(supportedFormats),
    requiredPermissions: Object.freeze(requiredPermissions),
    requiredDataCapabilities: Object.freeze(requiredDataCapabilities),
    sections: Object.freeze(sections),
    availability,
    ...(legacyReportType ? { legacyReportType } : {}),
    ...(availabilityReason ? { availabilityReason } : {}),
  });
}
