import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import type { GeneratedReportSnapshot, CanonicalReport as Report, CanonicalReportSection as ReportSection, CanonicalReportVersion as ReportVersion } from "@/platform/reporting";
import { buildViewer, definitionsForRole, reportDataQuality, toLibraryItem } from "./application/view-models";
import { CatalogCard, ReportLibraryTable, ReportSectionRenderer, StatusBadge, VersionHistory } from "./presentation/reporting-workspace";
import { standardReportCatalog } from "@/platform/reporting";
const tenantId="11111111-1111-4111-8111-111111111111",report:Report={reportId:"report-1",tenantId,family:"executive",reportType:"performance_brief",definitionId:"executive.performance-brief.v1",createdBy:"user-1",createdAt:"2026-08-11T00:00:00Z"};
const section:ReportSection={sectionId:"summary",sectionType:"summary",title:"Executive Summary",order:0,visibility:"internal",status:"partial",metrics:[{metricId:"revenue",metricKey:"gross-revenue",label:"Gross revenue",value:0,valueType:"currency",currency:"USD",status:"available",lineage:[]},{metricId:"missing",metricKey:"occupancy-rate",label:"Occupancy",value:null,valueType:"percentage",status:"missing",lineage:[]}],findings:[{findingId:"f1",category:"summary",severity:"attention",title:"<script>alert(1)</script>",summary:"Observed fact",basis:"deterministic",supportingMetricKeys:["gross-revenue"],lineage:[]}],recommendations:[{recommendationId:"r1",category:"summary",priority:"medium",title:"Consider review",rationale:"Based on finding",basis:"deterministic",supportingFindingIds:["f1"]}],dataGaps:[{gapId:"g1",code:"MISSING",category:"missing",severity:"limiting",message:"Occupancy unavailable",affectedMetricKeys:["occupancy-rate"]}]};
const snapshot:GeneratedReportSnapshot={schemaVersion:"rp001.report-snapshot.v1",definition:{definitionId:report.definitionId,definitionVersion:1,family:"executive",reportType:report.reportType,title:"Executive Performance Brief"},report:{reportId:report.reportId,versionId:"version-1",versionNumber:1,title:"July Brief"},scope:{kind:"portfolio",tenantId},period:{startDate:"2026-07-01",endDate:"2026-07-31",timezone:"America/Chicago"},generatedAt:"2026-08-11T00:00:00Z",requestedBy:"user-1",sections:[section],freshness:{status:"stale",observedAt:"2026-07-31T00:00:00Z"},lineage:[],dataGaps:section.dataGaps,generation:{generatorVersion:"rp001c.v1",deterministic:true,normalizedRequest:{}}};
const version:ReportVersion={reportId:report.reportId,reportVersionId:"version-1",versionNumber:1,definitionId:report.definitionId,definitionVersion:1,family:"executive",reportType:report.reportType,title:"July Brief",tenantId,requestedBy:"user-1",scope:snapshot.scope,authorizedPropertyIds:[],status:"ready",period:snapshot.period,snapshot,requestedAt:"2026-08-11T00:00:00Z",generatedAt:"2026-08-11T00:00:00Z"};
describe("RP-001D reporting workspace",()=>{
  it("exposes all six definitions to authorized internal roles and only owner-safe products to owners",()=>{const permissions=standardReportCatalog.definitions.map(item=>item.requiredPermissions[0]!);expect(definitionsForRole("administrator",permissions)).toHaveLength(6);expect(definitionsForRole("owner",["reports.owner.read"]).map(item=>item.definitionId)).toEqual(["owner.performance-report.v1"])});
  it("builds library and exact-version models without changing snapshot order",()=>{const item=toLibraryItem(report,version),view=buildViewer({report,version,versions:[version]});expect(item.latestVersion.dataQuality).toBe("stale");expect(view.sections[0]).toBe(section);expect(view.isLatestVersion).toBe(true);expect(reportDataQuality({...version,status:"failed"})).toBe("failed")});
  it("renders zero separately from unavailable and escapes untrusted text",()=>{const html=renderToStaticMarkup(<ReportSectionRenderer section={section}/>);expect(html).toContain("$0.00");expect(html).toContain("Unavailable");expect(html).toContain("&lt;script&gt;");expect(html).not.toContain("<script>");expect(html).toContain("Recommendations")});
  it("renders accessible status, tables, catalog metadata, and immutable history links",()=>{const definition=standardReportCatalog.get("executive.performance-brief.v1"),html=renderToStaticMarkup(<><StatusBadge status="ready-partial"/><CatalogCard definition={definition} available/><ReportLibraryTable items={[toLibraryItem(report,version)]}/><VersionHistory reportId={report.reportId} versions={[version]}/></>);expect(html).toContain('role="status"');expect(html).toContain("How is the portfolio performing");expect(html).toContain("<th");expect(html).toContain(`/dashboard/reports/${report.reportId}/versions/${version.reportVersionId}`)});
});
