import { FoundingPartnerCta as Link,FoundingPartnerPageView } from "./analytics";
const truths=["Where is revenue at risk?","What should I improve next?","Which problems deserve my attention?","Is my business actually getting stronger?"];
const receive=["Performance assessment","Early platform access","Monthly HPM reviews","Founder collaboration","Roadmap influence"];
export default function FoundingPartnersPage(){return <main className="bg-[#f7f3ec] text-stone-950"><FoundingPartnerPageView/>
  <section className="bg-stone-950 px-6 py-24 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-400">Founding HPM Partner Program</p><h1 className="mt-6 max-w-4xl font-serif text-5xl leading-[1.05] md:text-7xl">Great Hospitality Businesses Aren&apos;t Managed.<br/>They&apos;re Continuously Improved.</h1><p className="mt-6 max-w-2xl text-lg text-stone-300">A new approach to building higher-performing hospitality businesses—with the first operators helping shape what HPM becomes.</p><Link href="/founding-partners/apply" className="mt-9 inline-flex rounded-md bg-amber-500 px-6 py-3 font-semibold text-stone-950">Start the Conversation →</Link></div></section>
  <section className="mx-auto grid max-w-6xl gap-12 px-6 py-20 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-700">Industry truth</p><h2 className="mt-4 font-serif text-4xl">The industry has more software than ever.</h2><p className="mt-4 text-stone-600">Yet operators still struggle with the questions that matter most.</p></div><ul className="grid gap-3">{truths.map(x=><li key={x} className="rounded-xl border bg-white p-5">{x}</li>)}</ul></section>
  <section className="border-y bg-white px-6 py-20 text-center"><p className="text-xs font-bold uppercase tracking-widest text-amber-700">A category built around improvement</p><h2 className="mx-auto mt-4 max-w-3xl font-serif text-5xl">Hospitality Performance Management</h2><p className="mx-auto mt-5 max-w-2xl text-stone-600">See what is happening. Understand why. Decide what matters. Execute with clarity. Learn what changed.</p></section>
  <section className="mx-auto max-w-6xl px-6 py-20"><div className="grid gap-8 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-700">Founding Partner invitation</p><h2 className="mt-4 font-serif text-4xl">We&apos;re looking for five builders—not beta testers.</h2><p className="mt-4 text-stone-600">Hospitality entrepreneurs who want to improve their businesses while helping shape what HPM becomes.</p></div><div className="rounded-2xl border bg-[#fffaf0] p-8"><h3 className="font-semibold">As a Founding Partner, you receive</h3><ul className="mt-5 grid gap-3">{receive.map(x=><li key={x}>✓ {x}</li>)}</ul></div></div></section>
  <section className="bg-stone-900 px-6 py-20 text-center text-white"><h2 className="font-serif text-4xl">This may be for you if hospitality is a business, not a hobby.</h2><p className="mx-auto mt-5 max-w-2xl text-stone-300">You value data and systems, intend to grow, and are willing to tell us where the product needs to improve.</p><Link href="/founding-partners/apply" className="mt-8 inline-flex rounded-md bg-amber-500 px-6 py-3 font-semibold text-stone-950">Start the Conversation →</Link></section>
  </main>}
