import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const read=(path:string)=>readFileSync(path,"utf8"),domain=read("src/features/guidebook-studio/domain/authoring.ts"),application=read("src/features/guidebook-studio/application/authoring.ts"),infrastructure=read("src/features/guidebook-studio/infrastructure/supabase-authoring-repositories.ts"),transport=read("src/app/actions/guidebook-authoring.ts"),ui=read("src/components/guidebooks/guidebook-authoring-workspace.tsx"),migration=read("supabase/migrations/20260731090000_gb001_guidebook_studio_v1.sql");
describe("GB-001B authoring boundaries",()=>{
 it("keeps the discriminated domain independent of frameworks and infrastructure",()=>{for(const forbidden of["next/","react","supabase","@/app/"])expect(domain).not.toContain(forbidden);for(const type of["HeadingBlock","RichTextBlock","ImageBlock","InstructionBlock","ContactBlock","LocationBlock","LinkBlock","CalloutBlock","ChecklistBlock"])expect(domain).toContain(type)});
 it("exposes every required application use case and repository contract",()=>{for(const useCase of["loadGuidebookWorkspace","loadGuidebookDraft","persistGuidebookDraft","createGuidebookSection","renameGuidebookSection","reorderGuidebookSections","setGuidebookSectionVisibility","duplicateGuidebookSection","deleteGuidebookSection","createGuidebookBlock","updateGuidebookBlock","reorderGuidebookBlocks","setGuidebookBlockVisibility","duplicateGuidebookBlock","deleteGuidebookBlock","buildGuidebookDraftPreview","evaluateGuidebookPublicationReadiness","buildPublishedGuidebookSnapshot","publishGuidebookVersion","loadGuidebookEngagementSummary"])expect(application).toContain(useCase);for(const repository of["GuidebookDraftRepository","GuidebookCommandReceiptRepository","PublishedGuidebookVersionRepository","GuidebookAnalyticsRepository"])expect(application).toContain(repository)});
 it("confines Supabase authoring-table access to infrastructure",()=>{expect(infrastructure).toContain('from("guidebook_drafts")');expect(infrastructure).toContain('rpc("persist_guidebook_draft"');expect(transport).not.toContain('.from("guidebook_');expect(ui).not.toContain("supabase")});
 it("provides durable revision, receipts, idempotency and property-scoped RLS",()=>{for(const invariant of["guidebook_drafts","persist_guidebook_draft","p_expected_revision","guidebook_command_receipts","fingerprint","in-progress","can_access_workspace_property"])expect(migration).toContain(invariant)});
 it("provides keyboard controls, explicit conflict reapplication, and confirmations",()=>{for(const behavior of["Move ","A newer draft exists","Your local edits are preserved","Review latest","Reapply my change","role=\"dialog\"","aria-modal","beforeunload","offline","Save block"])expect(ui).toContain(behavior)});
 it("delegates the live publication and analytics paths to canonical application use cases",()=>{const publication=read("src/components/guidebooks/guidebook-publication-control.tsx"),analytics=read("src/app/(dashboard)/dashboard/guidebooks/[guidebookId]/analytics/page.tsx");expect(publication).toContain("publishCanonicalGuidebookAction");expect(transport).toContain("publishGuidebookVersion");expect(transport).not.toContain("buildPublishedGuidebookSnapshot(");expect(analytics).toContain("loadGuidebookAnalyticsSummaryAction");expect(analytics).not.toContain("guidebook_analytics");expect(analytics).not.toContain("reduce(")});
 it("bounds authentication, workspace resolution, receipts, draft persistence, publication, and analytics",()=>{for(const dependency of["getSessionProfile()","resolveWorkspaceAccessContext(","drafts.load(","receipts.find(","receipts.begin(","receipts.complete(","versions!.publish(","analytics!.summary("])expect(`${transport}\n${application}`).toContain(dependency);expect(transport.match(/withGuidebookOperationDeadline/g)?.length).toBeGreaterThanOrEqual(5);expect(application).toContain("bounded(")});
 it("adopts receipts for every active lifecycle path and isolates deferred media",()=>{const detail=read("src/components/guidebooks/canonical-guidebook-builder-page.tsx"),settings=read("src/app/(dashboard)/dashboard/guidebooks/[guidebookId]/settings/page.tsx"),versions=read("src/components/guidebooks/guidebook-version-history.tsx"),create=read("src/app/(dashboard)/dashboard/guidebooks/new/page.tsx"),legacy=read("src/components/guidebooks/guidebook-rich-editor.tsx");for(const source of[detail,settings,versions,create])expect(source).toContain("guidebook-authoring");for(const command of["createGuidebookWithReceipt","archiveGuidebook","restoreGuidebook","restoreHistoricalGuidebookContent"])expect(application).toContain(command);expect(legacy).toContain("@deprecated");expect(detail).not.toContain("GuidebookRichEditor");expect(create).not.toContain("uploadGuidebookImageAction")});
 it("defines database receipt closure for creation and scoped lifecycle RPCs",()=>{for(const boundary of["create_guidebook_with_receipt","archive_guidebook_canonical","restore_guidebook_canonical","restore_guidebook_version_canonical","command_already_in_progress","command_receipt_conflict"])expect(migration).toContain(boundary);expect(migration).not.toContain("door code");expect(migration).not.toContain("wifi password")});
 it("implements migration-independent focus, dialog, offline, responsive, and reduced-motion contracts",()=>{for(const behavior of["focusAfterAuthoringCommand","data-focus-id","trapDialogFocus","beforeunload","offline","reconnecting","aria-describedby","aria-invalid","motion-reduce","max-h-[90vh]","lg:grid-cols","flex-wrap","? \"alert\" : \"status\""])expect(ui).toContain(behavior)});
});
