import {describe,expect,it,vi} from "vitest";
vi.mock("server-only",()=>({}));
import {createCreationJob,extractCreationSources,generateCreationDraft,regenerateCreationSection,restoreCreationRevision,reviewCreationFact,uploadCreationSource,type AccessPort,type CanonicalDraftPort,type CompatibilityPort,type CreationContext,type CreationRepository,type SourceStorage} from "./application";
import {GUIDEBOOK_DRAFT_SCHEMA,type GuidebookDraft} from "@/features/guidebook-studio";
import {DeterministicCreationProvider} from "./providers";
import type {CreationJob,CreationSource,ExtractedFact,GuidebookProposal} from "./domain";

const extraction={facts:[{category:"arrival",field:"access_instructions",normalizedValue:"Use the front entrance",displayValue:"Use the front entrance",sourceId:"source-1",sourceLocation:"page 2",confidence:.91,reviewStatus:"needs_review" as const,sensitivity:"sensitive" as const,highRisk:true}],missing:[],warnings:[],mediaCandidates:[],unsupported:[]};
const proposal:GuidebookProposal={title:"Test Guest Guide",description:"A generated draft.",sections:[{stableKey:"arrival",name:"Arrival",blocks:[{type:"instruction",content:{title:"Arrival",steps:["Use the front entrance"],emphasis:"important"}}]}],factIds:["fact-1"],componentVersions:[]};

function setup(){
  let sequence=0;const jobs=new Map<string,CreationJob>(),sources:CreationSource[]=[],facts:ExtractedFact[]=[],artifacts:{id:string;draftSnapshot:GuidebookDraft}[]=[],attempts=new Map<string,string>(),drafts=new Map<string,GuidebookDraft>();
  const repository:CreationRepository={
    async findJob(w,id){const j=jobs.get(id);return j?.workspaceId===w?j:null},async findJobByIdempotency(w,k){return[...jobs.values()].find(j=>j.workspaceId===w&&j.idempotencyKey===k)??null},async createJob(j){jobs.set(j.id,j)},async transition(id,expected,patch){const current=jobs.get(id)!;if(current.state!==expected)throw new Error("CREATION_STATE_CONFLICT");const next={...current,...patch};jobs.set(id,next);return next},async listSources(w,j){return sources.filter(s=>s.workspaceId===w&&s.jobId===j)},async saveSource(s){sources.push(s);return s},async updateSource(id,p){const i=sources.findIndex(s=>s.id===id);sources[i]={...sources[i]!,...p}},async listFacts(_w,j){return facts.filter(f=>f.jobId===j)},async replaceFacts(j,_w,values){facts.splice(0,facts.length,...values.map((v,index)=>({...v,id:`fact-${index+1}`})))},async reviewFact(input){const i=facts.findIndex(f=>f.id===input.factId),current=facts[i]!;if(current.highRisk&&input.status==="confirmed"&&!input.confirmHighRisk)throw new Error("HIGH_RISK_CONFIRMATION_REQUIRED");facts[i]={...current,reviewStatus:input.status,correctedValue:input.correctedValue,confirmed:current.highRisk?input.confirmHighRisk:true}},async beginAttempt(input){const key=`${input.jobId}:${input.idempotencyKey}`;if(attempts.has(key))return{id:attempts.get(key)!,duplicate:true};const id=`attempt-${++sequence}`;attempts.set(key,id);return{id,duplicate:false}},async completeAttempt(){},async recordProviderEvidence(){return`evidence-${++sequence}`},async recordProviderEvidenceOutcome(){},async recordArtifact(input){artifacts.push({id:`artifact-${artifacts.length+1}`,draftSnapshot:input.draftSnapshot})},async findArtifact(_w,_j,revision){return artifacts.find(a=>a.draftSnapshot.revision===revision)??null},async audit(){},
  };
  const storage:SourceStorage={async put(){},async readExact(){return pdf},async removeExact(){}};
  const draftPort:CanonicalDraftPort={async create(input){const draft:GuidebookDraft={guidebookId:"guidebook-1",workspaceId:input.workspaceId,propertyId:input.propertyId,schemaVersion:GUIDEBOOK_DRAFT_SCHEMA,revision:1,title:input.title,description:"",sections:[],persistedAt:"2026-08-15T00:00:00Z",persistedBy:input.actorId};drafts.set(draft.guidebookId,draft);return{guidebookId:draft.guidebookId,revision:1}},async load(input){return drafts.get(input.guidebookId)??null},async save(input){const current=drafts.get(input.draft.guidebookId);if(current?.revision!==input.context.expectedRevision)throw new Error("DRAFT_CONFLICT");drafts.set(input.draft.guidebookId,input.draft);return input.draft}};
  const compatibility:CompatibilityPort={async readyTemplate(){return true},async allowedComponents(){return new Map()}};const access:AccessPort={async stillAuthorized(context,job){return context.workspaceId===job.workspaceId&&context.propertyId===job.propertyId}};const provider=new DeterministicCreationProvider(extraction,proposal);const deps={repository,storage,drafts:draftPort,compatibility,access,extraction:provider,generation:provider,clock:{now:()=>new Date("2026-08-15T00:00:00Z"),id:()=>`id-${++sequence}`}};return{deps,jobs,sources,facts,drafts,artifacts};
}
const context:CreationContext={actorId:"actor-1",actorRole:"admin",workspaceId:"workspace-1",propertyId:"property-1",permissions:new Set(["guidebooks.manage"]),entitled:true,correlationId:"correlation-1"};
const pdf=new Uint8Array([0x25,0x50,0x44,0x46,0x2d,0x31]);

describe("Guidebook Creation Assistant vertical slice",()=>{
  it("uploads, extracts, requires confirmation, and creates one canonical draft",async()=>{const x=setup(),created=await createCreationJob(x.deps,context,{idempotencyKey:"job-key",templateVersionId:"template-v1"});const replay=await createCreationJob(x.deps,context,{idempotencyKey:"job-key",templateVersionId:"template-v1"});expect(replay.duplicate).toBe(true);await uploadCreationSource(x.deps,context,{jobId:created.job.id,filename:"manual.pdf",mediaType:"application/pdf",bytes:pdf,integritySha256:"a".repeat(64)});const duplicate=await uploadCreationSource(x.deps,context,{jobId:created.job.id,filename:"manual-copy.pdf",mediaType:"application/pdf",bytes:pdf,integritySha256:"a".repeat(64)});expect(duplicate.duplicate).toBe(true);await extractCreationSources(x.deps,context,{jobId:created.job.id,idempotencyKey:"extract-1"});await expect(reviewCreationFact(x.deps,context,{jobId:created.job.id,factId:"fact-1",status:"confirmed",confirmHighRisk:false})).rejects.toThrow("HIGH_RISK_CONFIRMATION_REQUIRED");const readiness=await reviewCreationFact(x.deps,context,{jobId:created.job.id,factId:"fact-1",status:"confirmed",confirmHighRisk:true});expect(readiness.ready).toBe(true);const generated=await generateCreationDraft(x.deps,context,{jobId:created.job.id,idempotencyKey:"generate-1",title:"Test Guide"});expect(generated).toMatchObject({guidebookId:"guidebook-1",revision:2,duplicate:false});expect(x.drafts.get("guidebook-1")?.sections[0]?.name).toBe("Arrival");expect(x.jobs.get(created.job.id)?.state).toBe("completed");expect(x.drafts.get("guidebook-1")).not.toHaveProperty("publishedVersion");});
  it("preserves unrelated sections, rejects stale regeneration, and restores a prior generated revision",async()=>{const x=setup(),{job}=await createCreationJob(x.deps,context,{idempotencyKey:"job-2",templateVersionId:"template-v1"});await uploadCreationSource(x.deps,context,{jobId:job.id,filename:"manual.pdf",mediaType:"application/pdf",bytes:pdf,integritySha256:"b".repeat(64)});await extractCreationSources(x.deps,context,{jobId:job.id,idempotencyKey:"extract-2"});await reviewCreationFact(x.deps,context,{jobId:job.id,factId:"fact-1",status:"confirmed",confirmHighRisk:true});await generateCreationDraft(x.deps,context,{jobId:job.id,idempotencyKey:"generate-2",title:"Test"});const base=x.drafts.get("guidebook-1")!,extra={...base.sections[0]!,id:"unrelated",name:"Parking"};x.drafts.set("guidebook-1",{...base,sections:[...base.sections,extra]});const regenerated=await regenerateCreationSection(x.deps,context,{jobId:job.id,sectionId:base.sections[0]!.id,expectedRevision:2,idempotencyKey:"regen-1"});expect(regenerated.sections.find(s=>s.id==="unrelated")).toEqual(extra);await expect(regenerateCreationSection(x.deps,context,{jobId:job.id,sectionId:base.sections[0]!.id,expectedRevision:2,idempotencyKey:"regen-stale"})).rejects.toThrow("CREATION_DRAFT_STALE");const restored=await restoreCreationRevision(x.deps,context,{jobId:job.id,sourceRevision:2,expectedRevision:3});expect(restored.revision).toBe(4);expect(restored.sections).toHaveLength(1);});
  it("fails closed for wrong tenant access",async()=>{const x=setup(),{job}=await createCreationJob(x.deps,context,{idempotencyKey:"job-3",templateVersionId:"template-v1"});await expect(uploadCreationSource(x.deps,{...context,workspaceId:"wrong"},{jobId:job.id,filename:"manual.pdf",mediaType:"application/pdf",bytes:pdf,integritySha256:"c".repeat(64)})).rejects.toThrow("CREATION_ASSISTANT_NOT_FOUND")});
});
