import { GUIDEBOOK_BLOCK_SCHEMA,GUIDEBOOK_DRAFT_SCHEMA,type AuthoringBlock,type AuthoringSection,type GuidebookDraft } from "@/features/guidebook-studio";
import { assertProposalSafe,generationReadiness,inspectSource,sanitizeFilename,sensitivityFor,SOURCE_LIMITS,type CreationJob,type CreationSource,type ExtractedFact,type GuidebookProposal } from "./domain";
import type { ExtractionProvider,GenerationProvider } from "./providers";

export type CreationContext=Readonly<{actorId:string;actorRole:string;workspaceId:string;propertyId:string;permissions:ReadonlySet<string>;entitled:boolean;correlationId:string}>;
export interface CreationRepository{
  findJob(workspaceId:string,jobId:string):Promise<CreationJob|null>;
  findJobByIdempotency(workspaceId:string,key:string):Promise<CreationJob|null>;
  createJob(job:CreationJob):Promise<void>;
  transition(jobId:string,expectedState:CreationJob["state"],patch:Partial<CreationJob>):Promise<CreationJob>;
  listSources(workspaceId:string,jobId:string):Promise<readonly CreationSource[]>;
  saveSource(source:CreationSource):Promise<CreationSource>;
  updateSource(sourceId:string,patch:Partial<CreationSource>):Promise<void>;
  listFacts(workspaceId:string,jobId:string):Promise<readonly ExtractedFact[]>;
  replaceFacts(jobId:string,workspaceId:string,facts:readonly ExtractedFact[]):Promise<void>;
  reviewFact(input:Readonly<{workspaceId:string;jobId:string;factId:string;status:ExtractedFact["reviewStatus"];correctedValue?:unknown;actorId:string;confirmHighRisk:boolean}>):Promise<void>;
  beginAttempt(input:Readonly<{jobId:string;workspaceId:string;stage:"extraction"|"generation"|"section_regeneration";idempotencyKey:string;providerKey:string}>):Promise<Readonly<{id:string;duplicate:boolean}>>;
  completeAttempt(id:string,input:Readonly<{status:"completed"|"retryable_failure"|"terminal_failure";requestId?:string;usage?:Readonly<Record<string,number>>;failureCode?:string}>):Promise<void>;
  recordArtifact(input:Readonly<{jobId:string;workspaceId:string;attemptId:string;guidebookId:string;draftRevision:number;type:"initial_draft"|"section_regeneration";sectionId?:string;basedOnRevision?:number;templateVersionId:string;componentLineage:unknown;factLineage:unknown;draftSnapshot:GuidebookDraft}>):Promise<void>;
  findArtifact(workspaceId:string,jobId:string,draftRevision:number):Promise<Readonly<{id:string;draftSnapshot:GuidebookDraft}>|null>;
  audit(input:Readonly<{jobId:string;workspaceId:string;actorId?:string;event:string;correlationId:string;metadata?:Readonly<Record<string,string|number|boolean|null>>}>):Promise<void>;
}
export interface SourceStorage{put(input:Readonly<{path:string;bytes:Uint8Array;mediaType:string}>):Promise<void>;removeExact(paths:readonly string[]):Promise<void>}
export interface CanonicalDraftPort{
  create(input:Readonly<{workspaceId:string;propertyId:string;actorId:string;title:string;commandId:string}>):Promise<Readonly<{guidebookId:string;revision:number}>>;
  load(input:Readonly<{workspaceId:string;guidebookId:string;actorId:string}>):Promise<GuidebookDraft|null>;
  save(input:Readonly<{context:{workspaceId:string;guidebookId:string;actorId:string;expectedRevision:number;commandId:string;correlationId:string;enteredAt:string};draft:GuidebookDraft}>):Promise<GuidebookDraft>;
}
export interface CompatibilityPort{readyTemplate(versionId:string):Promise<boolean>;allowedComponents(versionId:string):Promise<ReadonlyMap<string,string>>}
export interface AccessPort{stillAuthorized(context:CreationContext,job:CreationJob):Promise<boolean>}
export interface CreationClock{now():Date;id():string}
export type CreationDependencies=Readonly<{repository:CreationRepository;storage:SourceStorage;drafts:CanonicalDraftPort;compatibility:CompatibilityPort;access:AccessPort;extraction:ExtractionProvider;generation:GenerationProvider;clock?:CreationClock}>;
const defaultClock:CreationClock={now:()=>new Date(),id:()=>crypto.randomUUID()};

function authorize(context:CreationContext){if(!context.permissions.has("guidebooks.manage")||!context.entitled)throw new Error("CREATION_ASSISTANT_FORBIDDEN")}
async function scoped(deps:CreationDependencies,context:CreationContext,jobId:string){authorize(context);const job=await deps.repository.findJob(context.workspaceId,jobId);if(!job||job.propertyId!==context.propertyId||!(await deps.access.stillAuthorized(context,job)))throw new Error("CREATION_ASSISTANT_NOT_FOUND");return job}

export async function createCreationJob(deps:CreationDependencies,context:CreationContext,input:Readonly<{idempotencyKey:string;templateVersionId:string}>){
  authorize(context);const prior=await deps.repository.findJobByIdempotency(context.workspaceId,input.idempotencyKey);if(prior)return{job:prior,duplicate:true};
  if(!(await deps.compatibility.readyTemplate(input.templateVersionId)))throw new Error("CREATION_TEMPLATE_NOT_READY");const clock=deps.clock??defaultClock;
  const job:CreationJob={id:clock.id(),workspaceId:context.workspaceId,propertyId:context.propertyId,actorId:context.actorId,actorRole:context.actorRole,templateVersionId:input.templateVersionId,state:"draft",currentStage:"property",idempotencyKey:input.idempotencyKey,attemptCount:0,correlationId:context.correlationId};
  await deps.repository.createJob(job);await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"job.created",correlationId:context.correlationId});return{job,duplicate:false};
}

export async function uploadCreationSource(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;filename:string;mediaType:string;bytes:Uint8Array;integritySha256:string}>){
  const job=await scoped(deps,context,input.jobId);if(["extracting","generating","completed","cancelled"].includes(job.state))throw new Error("CREATION_SOURCE_UPLOAD_CLOSED");
  const sources=await deps.repository.listSources(context.workspaceId,job.id);if(sources.length>=SOURCE_LIMITS.count||input.bytes.byteLength>SOURCE_LIMITS.bytesPerFile||sources.reduce((n,s)=>n+s.byteSize,0)+input.bytes.byteLength>SOURCE_LIMITS.totalBytes)throw new Error("CREATION_SOURCE_LIMIT_EXCEEDED");
  const type=inspectSource(input.bytes,input.mediaType);if(!type)throw new Error("CREATION_SOURCE_UNSUPPORTED");const existing=sources.find(s=>s.integritySha256===input.integritySha256);if(existing)return{source:existing,duplicate:true};
  const clock=deps.clock??defaultClock,id=clock.id(),path=`${context.workspaceId}/${job.id}/${id}/${sanitizeFilename(input.filename)}`;
  await deps.storage.put({path,bytes:input.bytes,mediaType:input.mediaType});
  try{const source:CreationSource={id,jobId:job.id,workspaceId:context.workspaceId,sourceType:type,originalFilename:sanitizeFilename(input.filename),storagePath:path,mediaType:input.mediaType,byteSize:input.bytes.byteLength,integritySha256:input.integritySha256,extractionStatus:"pending"};const saved=await deps.repository.saveSource(source);if(job.state!=="ready_for_extraction")await deps.repository.transition(job.id,job.state,{state:"ready_for_extraction",currentStage:"upload"});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"source.uploaded",correlationId:context.correlationId,metadata:{sourceId:id,type,bytes:input.bytes.byteLength}});return{source:saved,duplicate:false}}catch(error){await deps.storage.removeExact([path]);throw error}
}

export async function extractCreationSources(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;idempotencyKey:string}>){
  const job=await scoped(deps,context,input.jobId),sources=await deps.repository.listSources(context.workspaceId,job.id);if(!sources.length)throw new Error("CREATION_SOURCES_REQUIRED");
  const attempt=await deps.repository.beginAttempt({jobId:job.id,workspaceId:job.workspaceId,stage:"extraction",idempotencyKey:input.idempotencyKey,providerKey:deps.extraction.key});if(attempt.duplicate)return{duplicate:true};
  await deps.repository.transition(job.id,job.state,{state:"extracting",currentStage:"extraction"});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"extraction.started",correlationId:context.correlationId});
  const controller=new AbortController();try{const output=await deps.extraction.extract({sources,correlationId:context.correlationId,signal:controller.signal});const clock=deps.clock??defaultClock;
    const facts:ExtractedFact[]=[...output.result.facts.map(f=>({id:clock.id(),jobId:job.id,category:f.category,field:f.field,normalizedValue:f.sensitivity==="secret"?null:f.normalizedValue,displayValue:f.displayValue,sourceId:f.sourceId,sourceLocation:f.sourceLocation,confidence:f.confidence,reviewStatus:f.reviewStatus,conflictGroup:f.conflictGroup,sensitivity:f.sensitivity,highRisk:f.highRisk,confirmed:false})),...output.result.missing.map(f=>({id:clock.id(),jobId:job.id,category:f.category,field:f.field,normalizedValue:null,reviewStatus:"missing" as const,sensitivity:sensitivityFor(f.category,f.field),highRisk:f.highRisk,confirmed:false}))];
    await deps.repository.replaceFacts(job.id,job.workspaceId,facts);await Promise.all(sources.map(s=>deps.repository.updateSource(s.id,{extractionStatus:"completed"})));await deps.repository.completeAttempt(attempt.id,{status:"completed",requestId:output.requestId,usage:output.usage});await deps.repository.transition(job.id,"extracting",{state:"awaiting_review",currentStage:"review"});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"extraction.completed",correlationId:context.correlationId,metadata:{factCount:facts.length,warningCount:output.result.warnings.length}});return{duplicate:false,facts};
  }catch(error){await deps.repository.completeAttempt(attempt.id,{status:"retryable_failure",failureCode:error instanceof Error?error.name:"PROVIDER_FAILED"});await deps.repository.transition(job.id,"extracting",{state:"failed",currentStage:"extraction",failureClass:"provider_failure"});throw error}
}

export async function reviewCreationFact(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;factId:string;status:"confirmed"|"rejected";correctedValue?:unknown;confirmHighRisk:boolean}>){
  const job=await scoped(deps,context,input.jobId);if(job.state!=="awaiting_review"&&job.state!=="ready_to_generate")throw new Error("CREATION_REVIEW_CLOSED");const currentFacts=await deps.repository.listFacts(job.workspaceId,job.id),current=currentFacts.find(f=>f.id===input.factId);if(!current)throw new Error("CREATION_FACT_NOT_FOUND");if(current.sensitivity==="secret"&&input.status==="confirmed")throw new Error("PROTECTED_GUEST_DATA_BOUNDARY_REQUIRED");if(current.highRisk&&input.status==="confirmed"&&!input.confirmHighRisk)throw new Error("HIGH_RISK_CONFIRMATION_REQUIRED");await deps.repository.reviewFact({workspaceId:job.workspaceId,jobId:job.id,factId:input.factId,status:input.status,correctedValue:input.correctedValue,actorId:context.actorId,confirmHighRisk:input.confirmHighRisk});const facts=await deps.repository.listFacts(job.workspaceId,job.id),readiness=generationReadiness(facts);await deps.repository.transition(job.id,job.state,{state:readiness.ready?"ready_to_generate":"awaiting_review",currentStage:"review"});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:input.confirmHighRisk?"high_risk.confirmed":"review.updated",correlationId:context.correlationId,metadata:{factId:input.factId,status:input.status}});return readiness;
}

export async function generateCreationDraft(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;idempotencyKey:string;title:string;instructions?:Readonly<Record<string,string|boolean>>}>){
  const job=await scoped(deps,context,input.jobId);if(job.state==="completed"&&job.guidebookId)return{guidebookId:job.guidebookId,revision:job.resultingDraftRevision!,duplicate:true};const retrying=job.state==="failed"&&job.currentStage==="generation";if(job.state!=="ready_to_generate"&&!retrying)throw new Error("CREATION_NOT_READY");
  const facts=await deps.repository.listFacts(job.workspaceId,job.id),readiness=generationReadiness(facts);if(!readiness.ready)throw new Error("CREATION_CONFIRMATION_REQUIRED");if(!job.templateVersionId||!(await deps.compatibility.readyTemplate(job.templateVersionId)))throw new Error("CREATION_TEMPLATE_NOT_READY");const allowed=await deps.compatibility.allowedComponents(job.templateVersionId);
  const attempt=await deps.repository.beginAttempt({jobId:job.id,workspaceId:job.workspaceId,stage:"generation",idempotencyKey:input.idempotencyKey,providerKey:deps.generation.key});if(attempt.duplicate){const resumed=await deps.repository.findJob(job.workspaceId,job.id);if(resumed?.guidebookId&&resumed.resultingDraftRevision)return{guidebookId:resumed.guidebookId,revision:resumed.resultingDraftRevision,duplicate:true};throw new Error("CREATION_ATTEMPT_IN_PROGRESS")}
  await deps.repository.transition(job.id,job.state,{state:"generating",currentStage:"generation"});try{const output=await deps.generation.generate({facts:facts.filter(f=>f.reviewStatus==="confirmed"),templateVersionId:job.templateVersionId,allowedComponents:allowed,instructions:input.instructions??{},correlationId:context.correlationId,signal:new AbortController().signal});const proposal=assertProposalSafe(output.proposal,allowed);
  if(!(await deps.access.stillAuthorized(context,job)))throw new Error("CREATION_ACCESS_REVOKED");const created=job.guidebookId?{guidebookId:job.guidebookId,revision:job.expectedDraftRevision??1}:await deps.drafts.create({workspaceId:job.workspaceId,propertyId:job.propertyId,actorId:context.actorId,title:input.title||proposal.title,commandId:`creation:${job.id}`});
  const now=(deps.clock??defaultClock).now().toISOString(),draft=proposalToDraft(proposal,{guidebookId:created.guidebookId,workspaceId:job.workspaceId,propertyId:job.propertyId,revision:created.revision+1,actorId:context.actorId,at:now,id:(deps.clock??defaultClock).id});
  const saved=await deps.drafts.save({context:{workspaceId:job.workspaceId,guidebookId:created.guidebookId,actorId:context.actorId,expectedRevision:created.revision,commandId:`creation-draft:${job.id}`,correlationId:context.correlationId,enteredAt:now},draft});
  await deps.repository.recordArtifact({jobId:job.id,workspaceId:job.workspaceId,attemptId:attempt.id,guidebookId:saved.guidebookId,draftRevision:saved.revision,type:"initial_draft",templateVersionId:job.templateVersionId,componentLineage:proposal.componentVersions,factLineage:proposal.factIds,draftSnapshot:saved});await deps.repository.completeAttempt(attempt.id,{status:"completed",requestId:output.requestId,usage:output.usage});await deps.repository.transition(job.id,"generating",{state:"completed",currentStage:"builder",guidebookId:saved.guidebookId,resultingDraftRevision:saved.revision});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"draft.revision_created",correlationId:context.correlationId,metadata:{guidebookId:saved.guidebookId,revision:saved.revision}});return{guidebookId:saved.guidebookId,revision:saved.revision,duplicate:false}}catch(error){await deps.repository.completeAttempt(attempt.id,{status:"retryable_failure",failureCode:error instanceof Error?error.name:"GENERATION_FAILED"});await deps.repository.transition(job.id,"generating",{state:"failed",currentStage:"generation",failureClass:"provider_failure"});throw error}
}

export async function regenerateCreationSection(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;sectionId:string;expectedRevision:number;idempotencyKey:string;instructions?:Readonly<Record<string,string|boolean>>}>){
  const job=await scoped(deps,context,input.jobId);if(job.state!=="completed"||!job.guidebookId||!job.templateVersionId)throw new Error("CREATION_REGENERATION_UNAVAILABLE");const current=await deps.drafts.load({workspaceId:job.workspaceId,guidebookId:job.guidebookId,actorId:context.actorId});if(!current)throw new Error("CREATION_DRAFT_NOT_FOUND");if(current.revision!==input.expectedRevision)throw new Error("CREATION_DRAFT_STALE");const target=current.sections.find(s=>s.id===input.sectionId);if(!target)throw new Error("CREATION_SECTION_NOT_FOUND");
  const attempt=await deps.repository.beginAttempt({jobId:job.id,workspaceId:job.workspaceId,stage:"section_regeneration",idempotencyKey:input.idempotencyKey,providerKey:deps.generation.key});if(attempt.duplicate)throw new Error("CREATION_ATTEMPT_ALREADY_APPLIED");const facts=await deps.repository.listFacts(job.workspaceId,job.id),allowed=await deps.compatibility.allowedComponents(job.templateVersionId),output=await deps.generation.generate({facts:facts.filter(f=>f.reviewStatus==="confirmed"),templateVersionId:job.templateVersionId,allowedComponents:allowed,instructions:{...(input.instructions??{}),sectionOnly:true,sectionName:target.name},correlationId:context.correlationId,signal:new AbortController().signal}),proposal=assertProposalSafe(output.proposal,allowed);if(proposal.sections.length!==1)throw new Error("CREATION_SECTION_PROPOSAL_INVALID");const generated=proposal.sections[0]!,now=(deps.clock??defaultClock).now().toISOString(),replacement:AuthoringSection={id:target.id,name:generated.name,position:target.position,visible:target.visible,blocks:generated.blocks.map((block,index)=>proposalBlock(block,index,(deps.clock??defaultClock).id))},draft:GuidebookDraft={...current,revision:current.revision+1,sections:current.sections.map(section=>section.id===target.id?replacement:section),persistedAt:now,persistedBy:context.actorId};const saved=await deps.drafts.save({context:{workspaceId:job.workspaceId,guidebookId:job.guidebookId,actorId:context.actorId,expectedRevision:current.revision,commandId:`section-regeneration:${attempt.id}`,correlationId:context.correlationId,enteredAt:now},draft});await deps.repository.recordArtifact({jobId:job.id,workspaceId:job.workspaceId,attemptId:attempt.id,guidebookId:saved.guidebookId,draftRevision:saved.revision,type:"section_regeneration",sectionId:target.id,basedOnRevision:current.revision,templateVersionId:job.templateVersionId,componentLineage:proposal.componentVersions,factLineage:proposal.factIds,draftSnapshot:saved});await deps.repository.completeAttempt(attempt.id,{status:"completed",requestId:output.requestId,usage:output.usage});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"section.regenerated",correlationId:context.correlationId,metadata:{sectionId:target.id,revision:saved.revision}});return saved;
}

export async function restoreCreationRevision(deps:CreationDependencies,context:CreationContext,input:Readonly<{jobId:string;sourceRevision:number;expectedRevision:number}>){const job=await scoped(deps,context,input.jobId);if(!job.guidebookId)throw new Error("CREATION_DRAFT_NOT_FOUND");const[current,artifact]=await Promise.all([deps.drafts.load({workspaceId:job.workspaceId,guidebookId:job.guidebookId,actorId:context.actorId}),deps.repository.findArtifact(job.workspaceId,job.id,input.sourceRevision)]);if(!current||!artifact)throw new Error("CREATION_REVISION_NOT_FOUND");if(current.revision!==input.expectedRevision)throw new Error("CREATION_DRAFT_STALE");const now=(deps.clock??defaultClock).now().toISOString(),restored:GuidebookDraft={...artifact.draftSnapshot,revision:current.revision+1,persistedAt:now,persistedBy:context.actorId};const saved=await deps.drafts.save({context:{workspaceId:job.workspaceId,guidebookId:job.guidebookId,actorId:context.actorId,expectedRevision:current.revision,commandId:`creation-restore:${job.id}:${input.sourceRevision}:${current.revision}`,correlationId:context.correlationId,enteredAt:now},draft:restored});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"draft.revision_restored",correlationId:context.correlationId,metadata:{sourceRevision:input.sourceRevision,resultingRevision:saved.revision}});return saved}

export async function cancelCreationJob(deps:CreationDependencies,context:CreationContext,jobId:string){const job=await scoped(deps,context,jobId);if(job.guidebookId||job.state==="completed")throw new Error("CREATION_CANCELLATION_CLOSED");if(job.state==="cancelled")return job;const cancelled=await deps.repository.transition(job.id,job.state,{state:"cancelled",currentStage:"cancelled"});await deps.repository.audit({jobId:job.id,workspaceId:job.workspaceId,actorId:context.actorId,event:"job.cancelled",correlationId:context.correlationId});return cancelled}

function proposalToDraft(proposal:GuidebookProposal,input:Readonly<{guidebookId:string;workspaceId:string;propertyId:string;revision:number;actorId:string;at:string;id():string}>):GuidebookDraft{
  const sections:AuthoringSection[]=proposal.sections.map((section,position)=>({id:input.id(),name:section.name,position,visible:true,blocks:section.blocks.map((block,index)=>proposalBlock(block,index,input.id))}));return{guidebookId:input.guidebookId,workspaceId:input.workspaceId,propertyId:input.propertyId,schemaVersion:GUIDEBOOK_DRAFT_SCHEMA,revision:input.revision,title:proposal.title,description:proposal.description,sections,persistedAt:input.at,persistedBy:input.actorId};
}
function proposalBlock(block:GuidebookProposal["sections"][number]["blocks"][number],position:number,id:()=>string):AuthoringBlock{const base={id:id(),schemaVersion:GUIDEBOOK_BLOCK_SCHEMA,position,visible:true};switch(block.type){case"heading":return{...base,type:block.type,content:block.content};case"rich-text":return{...base,type:block.type,content:block.content};case"callout":return{...base,type:block.type,content:block.content};case"image":return{...base,type:block.type,content:block.content};case"instruction":return{...base,type:block.type,content:{...block.content,steps:block.content.steps.map(text=>({id:id(),text}))}};case"checklist":return{...base,type:block.type,content:{...block.content,items:block.content.items.map(text=>({id:id(),text}))}}}}

export type CapabilityInputs=Readonly<{migrationApplied:boolean;storageValid:boolean;extractionConfigured:boolean;generationConfigured:boolean;templateReady:boolean;componentsReady:boolean;backgroundHealthy:boolean;entitled:boolean;contextValid:boolean;globalEnabled:boolean;workspaceEnabled:boolean;controlledCohort:boolean;verticalSliceVerified:boolean}>;
export function creationAssistantCapability(input:CapabilityInputs){const reasons=Object.entries(input).filter(([key,value])=>!value&&key!=="controlledCohort"&&key!=="verticalSliceVerified").map(([key])=>key);const internal=reasons.length===0&&input.controlledCohort;return{internalAvailable:internal,customerVisible:internal&&input.verticalSliceVerified,reasons};}
