import{afterEach,describe,expect,it,vi}from"vitest";import{CREATION_PROVIDER_CANDIDATE,CreationProviderError,HttpCreationProvider,productionProviderFromEnvironment,VercelAiGatewayCreationProvider}from"./providers";
const signal=new AbortController().signal;
describe("Creation provider boundary",()=>{it("validates extraction output and fails closed",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({requestId:"r",result:{facts:[{category:"wifi",field:"credentials",normalizedValue:"secret",reviewStatus:"confirmed",sensitivity:"secret",highRisk:true}],missing:[],warnings:[],mediaCandidates:[],unsupported:[]}}),{status:200}));const provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key"},fetcher);await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toMatchObject({kind:"invalid_output",retryable:false})});it("classifies rate limits as retryable without leaking provider content",async()=>{const provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key"},vi.fn().mockResolvedValue(new Response("sensitive provider body",{status:429})));await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toEqual(expect.objectContaining({kind:"rate_limit",retryable:true,message:"The creation provider could not complete the request."}))});it("classifies timeouts as retryable",async()=>{const fetcher=vi.fn().mockImplementation((_url,init)=>new Promise((_resolve,reject)=>{(init as RequestInit).signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true})})),provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key",timeoutMs:1},fetcher);await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toEqual(expect.objectContaining<Partial<CreationProviderError>>({kind:"timeout",retryable:true}))})});

describe("Vercel AI Gateway production candidate",()=>{
  afterEach(()=>{delete process.env.GUIDEBOOK_CREATION_ADAPTER;delete process.env.GUIDEBOOK_CREATION_PROVIDER_MODEL;delete process.env.GUIDEBOOK_CREATION_PROVIDER_TIMEOUT_MS;delete process.env.GUIDEBOOK_CREATION_KILL_SWITCH;delete process.env.AI_GATEWAY_API_KEY;delete process.env.VERCEL_OIDC_TOKEN});
  it("sends private source bytes directly with storage disabled and records bounded usage",async()=>{const result={facts:[],missing:[],warnings:[],mediaCandidates:[],unsupported:[]},fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"provider-request",output:[{content:[{text:JSON.stringify(result)}]}],usage:{input_tokens:12,output_tokens:4,raw_customer_content:"excluded"}}),{status:200})),provider=new VercelAiGatewayCreationProvider({token:"credential",model:CREATION_PROVIDER_CANDIDATE,timeoutMs:5000},fetcher),output=await provider.extract({sources:[{id:"source-1",jobId:"job",workspaceId:"workspace",sourceType:"text",originalFilename:"notes.txt",storagePath:"private/path",mediaType:"text/plain",byteSize:5,integritySha256:"a".repeat(64),extractionStatus:"pending",bytes:new TextEncoder().encode("hello")}],correlationId:"correlation",signal});expect(output).toMatchObject({requestId:"provider-request",usage:{input_tokens:12,output_tokens:4}});const request=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(request.store).toBe(false);expect(JSON.stringify(request)).not.toContain("private/path");expect(fetcher.mock.calls[0]?.[1]?.headers).toMatchObject({"x-correlation-id":"correlation"})});
  it("fails closed unless adapter, exact model, credential, timeout, and kill switch are valid",()=>{process.env.GUIDEBOOK_CREATION_ADAPTER="vercel-ai-gateway";process.env.GUIDEBOOK_CREATION_PROVIDER_MODEL=CREATION_PROVIDER_CANDIDATE;process.env.AI_GATEWAY_API_KEY="credential";expect(productionProviderFromEnvironment()).toBeInstanceOf(VercelAiGatewayCreationProvider);process.env.GUIDEBOOK_CREATION_KILL_SWITCH="true";expect(productionProviderFromEnvironment()).toBeNull()});
});
