import{afterEach,describe,expect,it,vi}from"vitest";import{CREATION_PROVIDER_CANDIDATE,CreationProviderError,DirectOpenAiCreationProvider,GUIDEBOOK_COST_CEILING_USD,HttpCreationProvider,OPENAI_EXTRACTION_MODEL,OPENAI_GENERATION_MODEL,productionProviderFromEnvironment,VercelAiGatewayCreationProvider}from"./providers";
vi.mock("server-only",()=>({}));
const signal=new AbortController().signal;
describe("Creation provider boundary",()=>{it("validates extraction output and fails closed",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({requestId:"r",result:{facts:[{category:"wifi",field:"credentials",normalizedValue:"secret",reviewStatus:"confirmed",sensitivity:"secret",highRisk:true}],missing:[],warnings:[],mediaCandidates:[],unsupported:[]}}),{status:200}));const provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key"},fetcher);await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toMatchObject({kind:"invalid_output",retryable:false})});it("classifies rate limits as retryable without leaking provider content",async()=>{const provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key"},vi.fn().mockResolvedValue(new Response("sensitive provider body",{status:429})));await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toEqual(expect.objectContaining({kind:"rate_limit",retryable:true,message:"The creation provider could not complete the request."}))});it("classifies timeouts as retryable",async()=>{const fetcher=vi.fn().mockImplementation((_url,init)=>new Promise((_resolve,reject)=>{(init as RequestInit).signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true})})),provider=new HttpCreationProvider({endpoint:"https://provider.test",apiKey:"key",timeoutMs:1},fetcher);await expect(provider.extract({sources:[],correlationId:"c",signal})).rejects.toEqual(expect.objectContaining<Partial<CreationProviderError>>({kind:"timeout",retryable:true}))})});

describe("Vercel AI Gateway production candidate",()=>{
  afterEach(()=>{for(const key of["GUIDEBOOK_CREATION_ADAPTER","GUIDEBOOK_CREATION_PROVIDER_MODEL","GUIDEBOOK_CREATION_EXTRACTION_MODEL","GUIDEBOOK_CREATION_GENERATION_MODEL","GUIDEBOOK_CREATION_PROVIDER_TIMEOUT_MS","GUIDEBOOK_CREATION_KILL_SWITCH","GUIDEBOOK_CREATION_ALLOW_GPT54_FALLBACK","AI_GATEWAY_API_KEY","VERCEL_OIDC_TOKEN","OPENAI_API_KEY"])delete process.env[key]});
  it("locks routing to the approved undated OpenAI Gateway model",()=>{expect(CREATION_PROVIDER_CANDIDATE).toBe("openai/gpt-5-mini");expect(CREATION_PROVIDER_CANDIDATE).not.toMatch(/5\.4|openai\/gpt-5$/)});
  it("sends private source bytes directly with storage disabled and records bounded usage",async()=>{const result={facts:[],missing:[],warnings:[],mediaCandidates:[],unsupported:[]},fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"provider-request",output:[{content:[{text:JSON.stringify(result)}]}],usage:{input_tokens:12,output_tokens:4,raw_customer_content:"excluded"}}),{status:200})),provider=new VercelAiGatewayCreationProvider({token:"credential",model:CREATION_PROVIDER_CANDIDATE,timeoutMs:5000},fetcher),output=await provider.extract({sources:[{id:"source-1",jobId:"job",workspaceId:"workspace",sourceType:"text",originalFilename:"notes.txt",storagePath:"private/path",mediaType:"text/plain",byteSize:5,integritySha256:"a".repeat(64),extractionStatus:"pending",bytes:new TextEncoder().encode("hello")}],correlationId:"correlation",signal});expect(output).toMatchObject({requestId:"provider-request",usage:{input_tokens:12,output_tokens:4}});const request=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(request.store).toBe(false);expect(JSON.stringify(request)).not.toContain("private/path");expect(fetcher.mock.calls[0]?.[1]?.headers).toMatchObject({"x-correlation-id":"correlation"})});
  it("fails closed unless adapter, exact model, credential, timeout, and kill switch are valid",()=>{process.env.GUIDEBOOK_CREATION_ADAPTER="vercel-ai-gateway";process.env.GUIDEBOOK_CREATION_PROVIDER_MODEL=CREATION_PROVIDER_CANDIDATE;process.env.AI_GATEWAY_API_KEY="credential";expect(productionProviderFromEnvironment()).toBeInstanceOf(VercelAiGatewayCreationProvider);process.env.GUIDEBOOK_CREATION_KILL_SWITCH="true";expect(productionProviderFromEnvironment()).toBeNull()});
});

describe("Direct OpenAI production adapter",()=>{
  const extraction={facts:[],missing:[],warnings:[],mediaCandidates:[],unsupported:[]};
  const proposal={title:"Controlled guide",description:"Review required.",sections:[{stableKey:"welcome",name:"Welcome",blocks:[]}],factIds:[],componentVersions:[]};
  const config={apiKey:"server-secret",extractionModel:OPENAI_EXTRACTION_MODEL,generationModel:OPENAI_GENERATION_MODEL,timeoutMs:5000,allowExplicitFallback:false};
  it("uses only GPT-5 Nano for extraction and records priced telemetry",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"resp_extract",output_text:JSON.stringify(extraction),usage:{input_tokens:100,output_tokens:20,total_tokens:120,input_tokens_details:{cached_tokens:25}}}),{status:200})),provider=new DirectOpenAiCreationProvider(config,fetcher),output=await provider.extract({sources:[{id:"source-1",jobId:"job",workspaceId:"workspace",sourceType:"text",originalFilename:"notes.txt",storagePath:"private/path",mediaType:"text/plain",byteSize:6,integritySha256:"a".repeat(64),extractionStatus:"pending",bytes:new TextEncoder().encode("line\r\n")}],correlationId:"correlation",signal});const request=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(OPENAI_EXTRACTION_MODEL).toBe("gpt-5-nano");expect(fetcher.mock.calls[0]?.[0]).toBe("https://api.openai.com/v1/responses");expect(fetcher.mock.calls[0]?.[1]?.headers).toMatchObject({authorization:"Bearer server-secret","x-client-request-id":"correlation"});expect(request).toMatchObject({model:"gpt-5-nano",store:false});expect(JSON.stringify(request)).toContain("line\\n");expect(JSON.stringify(request)).not.toContain("private/path");expect(output.usage).toMatchObject({input_tokens:100,output_tokens:20,total_tokens:120,cached_input_tokens:25,calculated_cost_usd:.00001188});expect(output.usage).not.toHaveProperty("raw_customer_content")});
  it("uses only GPT-5 Mini for generation and never falls back to 5.4 or full GPT-5",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"resp_generate",output:[{content:[{type:"output_text",text:JSON.stringify(proposal)}]}],usage:{input_tokens:200,output_tokens:40,total_tokens:240}}),{status:200})),provider=new DirectOpenAiCreationProvider(config,fetcher);await provider.generate({facts:[],templateVersionId:"template",allowedComponents:new Map(),instructions:{},correlationId:"correlation",signal});const request=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(OPENAI_GENERATION_MODEL).toBe("gpt-5-mini");expect(request.model).toBe("gpt-5-mini");expect(JSON.stringify(request)).not.toMatch(/gpt-5\.4|\"gpt-5\"/);await expect(provider.generate({facts:[],templateVersionId:"template",allowedComponents:new Map(),instructions:{explicitModelFallback:true},correlationId:"correlation",signal})).rejects.toMatchObject({kind:"terminal",retryable:false});expect(fetcher).toHaveBeenCalledTimes(1)});
  it("runs one minimal Nano smoke request through the direct adapter without files or customer content",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:"resp_smoke",model:"gpt-5-nano",output_text:'{"ok":true}',usage:{input_tokens:18,output_tokens:8,total_tokens:26,output_tokens_details:{reasoning_tokens:4}}}),{status:200,headers:{"x-request-id":"req_smoke"}})),provider=new DirectOpenAiCreationProvider({...config,projectId:"project-id"},fetcher),output=await provider.verifyNanoGeneration({correlationId:"smoke-correlation",signal});expect(fetcher).toHaveBeenCalledOnce();const request=JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body));expect(request).toMatchObject({model:"gpt-5-nano",store:false,max_output_tokens:40,input:[{role:"user",content:[{type:"input_text"}]}]});expect(JSON.stringify(request)).not.toMatch(/file|image|customer|property|guidebook/i);expect(fetcher.mock.calls[0]?.[1]?.headers).toMatchObject({"OpenAI-Project":"project-id","x-client-request-id":"smoke-correlation"});expect(output).toMatchObject({httpStatus:200,openaiRequestId:"req_smoke",model:"gpt-5-nano",usage:{input_tokens:18,output_tokens:8,reasoning_tokens:4}})});
  it("preserves the server-authoritative one-dollar ceiling and rejects fallback enablement",()=>{expect(GUIDEBOOK_COST_CEILING_USD).toBe(1);process.env.GUIDEBOOK_CREATION_ADAPTER="openai-direct";process.env.OPENAI_API_KEY="server-only";process.env.GUIDEBOOK_CREATION_ALLOW_GPT54_FALLBACK="true";expect(productionProviderFromEnvironment()).toBeNull();delete process.env.GUIDEBOOK_CREATION_ALLOW_GPT54_FALLBACK;expect(productionProviderFromEnvironment()).toBeInstanceOf(DirectOpenAiCreationProvider)});
  it("reads only OPENAI_API_KEY for the direct adapter and fails closed",()=>{delete process.env.OPENAI_API_KEY;process.env.GUIDEBOOK_CREATION_ADAPTER="openai-direct";process.env.AI_GATEWAY_API_KEY="wrong-provider";expect(productionProviderFromEnvironment()).toBeNull();process.env.OPENAI_API_KEY="server-only";expect(productionProviderFromEnvironment()).toBeInstanceOf(DirectOpenAiCreationProvider);process.env.GUIDEBOOK_CREATION_KILL_SWITCH="true";expect(productionProviderFromEnvironment()).toBeNull()});
});
