import Link from "next/link";
import { getExecutiveIntelligenceView,ExecutiveAttentionList,filterExecutiveAttention,parseExecutiveAttentionFilter,type ExecutiveAttentionFilter } from "@/features/executive-intelligence";
import { resolveAnalyticsDateRange } from "@/features/analytics";
import { understandRoutes } from "@/platform/experience";
type Params={property?:string;start?:string;end?:string;from?:string;to?:string;returnTo?:string;type?:string};
type SearchParams=Promise<Params>;
const labels:Readonly<Record<ExecutiveAttentionFilter,string>>={all:"All",performance:"Performance",risk:"Risk","data-quality":"Data Quality"};
const empty:Readonly<Record<ExecutiveAttentionFilter,readonly [string,string]>>={all:["No current attention items","Nothing in the selected scope and period currently requires deeper review."],performance:["No performance items require attention","No performance signals in the selected scope and period currently require deeper review."],risk:["No risks currently require attention","No risk records in the selected scope and period currently require deeper review."],"data-quality":["No data-quality items currently require attention","No data-quality signals in the selected scope and period currently require deeper review."]};
export default async function AttentionPage({searchParams}:Readonly<{searchParams:SearchParams}>){const params=await searchParams;const range=resolveAnalyticsDateRange({startDate:params.from??params.start,endDate:params.to??params.end});const{view}=await getExecutiveIntelligenceView({propertyId:params.property??null,startDate:range.startDate,endDate:range.endDate});const filter=parseExecutiveAttentionFilter(params.type),attention=filterExecutiveAttention(view.attention,filter),returnTo=safeReturn(params.returnTo,understandRoutes.executive);return <main className="mx-auto max-w-[1200px] space-y-6 px-4 pb-10 pt-3 sm:px-6 lg:px-8"><header className="rounded-[2rem] border border-stone-200 bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-700">Understand › Executive Intelligence › Attention</p><h1 className="mt-3 text-3xl font-semibold text-stone-950">Attention</h1><p className="mt-2 text-sm text-stone-600">What requires deeper understanding across your business?</p><nav aria-label="Filter attention queue" className="mt-5 flex flex-wrap gap-2 text-xs font-semibold" role="tablist">{Object.entries(labels).map(([value,label])=><Link key={value} role="tab" aria-selected={filter===value} href={filterHref(params,value as ExecutiveAttentionFilter)} className={`rounded-full border px-3 py-2 ${filter===value?"border-stone-950 bg-stone-950 text-white":"border-stone-200 bg-white text-stone-700 hover:border-stone-500"}`}>{label}</Link>)}</nav></header><ExecutiveAttentionList attention={attention} emptyTitle={empty[filter][0]} emptyDescription={empty[filter][1]}/><Link href={returnTo} className="inline-flex text-sm font-semibold text-teal-800 underline-offset-4 hover:underline">← Return to Executive Intelligence</Link></main>}
function safeReturn(value:string|undefined,fallback:string){return value?.startsWith("/dashboard/understand/executive")&&!value.startsWith("//")?value:fallback}
function filterHref(params:Params,type:ExecutiveAttentionFilter){const query=new URLSearchParams();for(const[key,value]of Object.entries(params)){if(key!=="type"&&value)query.set(key,value)}query.set("type",type);return `${understandRoutes.attention}?${query.toString()}`}
