import Link from "next/link";
import { getReportWorkspace } from "@/app/actions/reporting";

export default async function ReportsWorkspacePage() {
  const workspace = await getReportWorkspace();
  if (!workspace) return <main className="p-8"><h1 className="text-3xl font-semibold">Reports</h1><p className="mt-4">Sign in to view reports.</p></main>;
  return <main className="mx-auto max-w-7xl space-y-8 px-5 py-10"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Communicate</p><h1 className="mt-2 text-4xl font-semibold">Reports</h1><p className="mt-3 text-stone-600">Immutable, permission-aware documents generated from canonical platform intelligence.</p></div><Link className="rounded-full bg-stone-950 px-5 py-3 font-semibold text-white" href="/dashboard/reports/new">Create report</Link></header>
    <section><h2 className="text-2xl font-semibold">Report history</h2><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="min-w-full text-left text-sm"><thead className="bg-stone-50"><tr><th className="p-4">Report</th><th className="p-4">Type</th><th className="p-4">Scope</th><th className="p-4">Confidence</th><th className="p-4">Status</th><th className="p-4">Generated</th></tr></thead><tbody>{workspace.reports.map((report) => <tr className="border-t" key={report.id}><td className="p-4"><Link className="font-semibold" href={`/dashboard/reports/${report.id}`}>{report.title}</Link><span className="block text-xs text-stone-500">{report.report_number} · v{report.version_number}</span></td><td className="p-4 capitalize">{report.report_type.replaceAll("-"," ")}</td><td className="p-4">{(report.scope_snapshot as {label?:string})?.label ?? "Authorized scope"}</td><td className="p-4 capitalize">{report.confidence.replaceAll("-"," ")}</td><td className="p-4 capitalize">{report.status.replaceAll("-"," ")}</td><td className="p-4">{new Date(report.generated_at).toLocaleString()}</td></tr>)}</tbody></table>{!workspace.reports.length ? <div className="p-10 text-center"><p className="font-semibold">No reports have been generated</p><p className="mt-2 text-stone-600">Create a report from an Investment, Portfolio, or Financial workspace.</p></div> : null}</div></section>
  </main>;
}
