import Link from "next/link";
import { getReportWorkspace, publishReportArtifactsAction } from "@/app/actions/reporting";

export default async function ReportsWorkspacePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const params=await searchParams,type=single(params.type),status=single(params.status),q=single(params.q),page=Math.max(1,Number(single(params.page))||1);
  const workspace=await getReportWorkspace({type,status,q,page});
  if(!workspace)return <main className="p-8"><h1 className="text-3xl font-semibold">Reports</h1><p className="mt-4">Sign in to view reports.</p></main>;
  const attention=workspace.reports.filter(report=>report.freshness==="stale"||report.freshness==="degraded").length+workspace.jobs.filter(job=>job.status==="failed").length;
  return <main className="mx-auto max-w-[1440px] space-y-5 px-5 py-5">
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-700">Reports</p><h1 className="sr-only">Reports</h1><p className="mt-1 text-xs text-stone-600">Package platform intelligence into decision-ready narratives.</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border border-violet-200 bg-violet-50 px-4 py-2 text-xs font-semibold text-violet-700" href="/dashboard/reports/compare">Preview</Link><Link className="rounded-full bg-stone-950 px-5 py-2 text-xs font-semibold text-white" href="/dashboard/reports/new">Generate report</Link></div></header>
    <nav aria-label="Report views" className="flex gap-5 border-b"><Link className="border-b-2 border-stone-950 pb-3 font-semibold" href="/dashboard/reports">Current</Link><Link className="pb-3" href="/dashboard/reports?status=superseded">History</Link><Link className="pb-3" href="/dashboard/reports?status=archived">Archived</Link></nav>
    <section aria-label="Report summary" className="grid gap-3 sm:grid-cols-4"><Summary label="Visible reports" value={workspace.total}/><Summary label="Active jobs" value={workspace.jobs.filter(job=>job.status!=="failed").length}/><Summary label="Requires attention" value={attention}/><Summary label="Page" value={workspace.page}/></section>
    {workspace.jobs.length?<section aria-labelledby="generation-jobs"><h2 id="generation-jobs" className="text-xl font-semibold">Generation activity</h2><div className="mt-3 space-y-2">{workspace.jobs.map(job=><div role="status" className="rounded-xl border bg-white p-4" key={job.id}><div className="flex justify-between gap-4"><p className="font-semibold">{stage(job.stage)}</p><span className="text-sm capitalize">{job.status}</span></div><p className="mt-1 text-sm text-stone-600">{job.status==="failed"?(job.failure_message??"Generation failed. An administrator can retry recoverable jobs."):"You may leave this page; generation continues in the background."}</p></div>)}</div></section>:null}
    <form className="flex flex-wrap gap-3 rounded-2xl border bg-stone-50 p-4">
      <label className="text-sm font-semibold">Search <input className="ml-2 rounded-lg border bg-white p-2" name="q" defaultValue={q} placeholder="Title or report #"/></label>
      <label className="text-sm font-semibold">Type <select className="ml-2 rounded-lg border bg-white p-2" name="type" defaultValue={type??"all"}><option value="all">All types</option><option value="investment-decision">Investment decision</option><option value="property-performance">Property performance</option><option value="portfolio-performance">Portfolio performance</option><option value="financial-performance">Financial performance</option></select></label>
      <label className="text-sm font-semibold">Status <select className="ml-2 rounded-lg border bg-white p-2" name="status" defaultValue={status??"all"}><option value="all">Active</option><option value="generated">Generated</option><option value="published">Published</option><option value="superseded">Superseded</option><option value="archived">Archive</option></select></label>
      <button className="rounded-full border bg-white px-4 py-2 text-sm font-semibold">Apply filters</button>
    </form>
    <section><h2 className="text-2xl font-semibold">Saved reports</h2><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="min-w-full text-left text-sm"><thead className="bg-stone-50"><tr><th className="p-4">Report</th><th className="p-4">Type and scope</th><th className="p-4">Period</th><th className="p-4">Trust</th><th className="p-4">Publishing</th><th className="p-4">Actions</th></tr></thead><tbody>{workspace.reports.map(report=>{const active=report.report_artifacts.filter(item=>item.status==="active");return <tr className="border-t" key={report.id}><td className="p-4"><Link className="font-semibold" href={`/dashboard/reports/${report.id}`}>{report.title}</Link><span className="block text-xs text-stone-500">{report.report_number} · v{report.version_number}</span></td><td className="p-4 capitalize">{report.report_type.replaceAll("-"," ")}<span className="block text-xs text-stone-500">{(report.scope_snapshot as {label?:string})?.label??"Authorized scope"}</span></td><td className="p-4">{(report.period_snapshot as {label?:string}|null)?.label??"Point-in-time"}</td><td className="p-4 capitalize">{report.confidence.replaceAll("-"," ")}<span className="block text-xs text-stone-500">{report.freshness}</span></td><td className="p-4 capitalize">{report.status}<span className="block text-xs text-stone-500">{active.map(item=>item.artifact_type.toUpperCase()).join(" · ")||"No artifacts"}</span></td><td className="p-4"><div className="flex flex-wrap gap-3"><Link className="font-semibold underline" href={`/dashboard/reports/${report.id}`}>Open</Link>{report.status!=="archived"?<form action={publishReportArtifactsAction}><input name="reportId" type="hidden" value={report.id}/><input name="artifactType" type="hidden" value="both"/><input name="commandId" type="hidden" value={crypto.randomUUID()}/><button className="font-semibold underline">{active.length?"Regenerate":"Publish"}</button></form>:null}</div></td></tr>})}</tbody></table>{!workspace.reports.length?<div className="p-10 text-center"><p className="font-semibold">No reports have been generated yet.</p><p className="mx-auto mt-2 max-w-xl text-stone-600">Turn current platform intelligence into a durable snapshot for owners, investors, and operating teams.</p><Link className="mt-5 inline-block rounded-full bg-stone-950 px-5 py-3 font-semibold text-white" href="/dashboard/reports/new">Generate first report</Link></div>:null}</div></section>
    {workspace.total>workspace.pageSize?<nav aria-label="Report pages" className="flex justify-end gap-3">{workspace.page>1?<Link href={`?type=${type??"all"}&status=${status??"all"}&page=${workspace.page-1}`}>Previous</Link>:null}{workspace.page*workspace.pageSize<workspace.total?<Link href={`?type=${type??"all"}&status=${status??"all"}&page=${workspace.page+1}`}>Next</Link>:null}</nav>:null}
  </main>;
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-2xl border bg-white p-5"><p className="text-sm text-stone-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>;}
function single(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value;}
function stage(value:string){return({queued:"Queued",projection:"Preparing source intelligence",html:"Composing report",pdf:"Rendering document",storage:"Saving report",completed:"Complete"} as Record<string,string>)[value]??"Preparing report";}
