"use client";

import Link, { type LinkProps } from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { ArrowLeftRight, Building2, CalendarDays, Layers3, SlidersHorizontal, X } from "lucide-react";

export type AccountingBasis="actual"|"cash"|"accrual";
export type WorkspaceContextKind="operational"|"intelligence"|"configuration";
export type WorkspaceContextValue=Readonly<{workspaceId:string;workspaceLabel:string;scope:string;from:string;to:string;compareFrom:string;compareTo:string;basis:AccountingBasis}>;
type ContextApi=Readonly<{value:WorkspaceContextValue;update:(patch:Partial<WorkspaceContextValue>)=>void;contextualHref:(href:string)=>string;openDrawer:()=>void}>;
const Context=createContext<ContextApi|null>(null),storageKey="luxe-haven:workspace-context:v2";
const iso=(date:Date)=>date.toISOString().slice(0,10);
function defaults():WorkspaceContextValue{const to=new Date(),from=new Date(to);from.setUTCDate(from.getUTCDate()-30);const compareTo=new Date(from);compareTo.setUTCDate(compareTo.getUTCDate()-1);const compareFrom=new Date(compareTo);compareFrom.setUTCDate(compareFrom.getUTCDate()-30);return{workspaceId:"current",workspaceLabel:"Luxe Haven Collective",scope:"entire-portfolio",from:iso(from),to:iso(to),compareFrom:iso(compareFrom),compareTo:iso(compareTo),basis:"actual"};}
const keys=["workspaceId","scope","from","to","compareFrom","compareTo","basis"]as const;
function fromSearch(search:URLSearchParams,fallback:WorkspaceContextValue):WorkspaceContextValue{return{...fallback,workspaceId:search.get("workspace")||fallback.workspaceId,scope:search.get("scope")||fallback.scope,from:search.get("from")||fallback.from,to:search.get("to")||fallback.to,compareFrom:search.get("compareFrom")||fallback.compareFrom,compareTo:search.get("compareTo")||fallback.compareTo,basis:(search.get("basis")as AccountingBasis)||fallback.basis};}
function serialize(url:URL,value:WorkspaceContextValue){url.searchParams.set("workspace",value.workspaceId);url.searchParams.set("scope",value.scope);url.searchParams.set("from",value.from);url.searchParams.set("to",value.to);url.searchParams.set("compareFrom",value.compareFrom);url.searchParams.set("compareTo",value.compareTo);url.searchParams.set("basis",value.basis);return`${url.pathname}?${url.searchParams.toString()}${url.hash}`;}

export function WorkspaceContextProvider({children,workspaceLabel="Luxe Haven Collective"}:{children:ReactNode;workspaceLabel?:string}){const pathname=usePathname(),search=useSearchParams(),router=useRouter(),[drawer,setDrawer]=useState(false),[value,setValue]=useState<WorkspaceContextValue>(()=>fromSearch(search,new URLSearchParams(keys.some(key=>search.has(key==="workspaceId"?"workspace":key))?search.toString():"").size?{...defaults(),workspaceLabel}:{...defaults(),workspaceLabel}));
 useEffect(()=>{let stored:WorkspaceContextValue|undefined;try{stored=JSON.parse(localStorage.getItem(storageKey)||"")as WorkspaceContextValue}catch{}const next=fromSearch(search,stored?{...stored,workspaceLabel}:{...defaults(),workspaceLabel});const frame=requestAnimationFrame(()=>setValue(next));return()=>cancelAnimationFrame(frame)},[search,workspaceLabel]);
 useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(value))},[value]);
 const contextualHref=useCallback((href:string)=>serialize(new URL(href,"https://workspace.local"),value),[value]);
 const update=useCallback((patch:Partial<WorkspaceContextValue>)=>{setValue(current=>{const next={...current,...patch};router.replace(serialize(new URL(`${pathname}?${search.toString()}`,"https://workspace.local"),next),{scroll:false});return next})},[pathname,router,search]);
 const api=useMemo(()=>({value,update,contextualHref,openDrawer:()=>setDrawer(true)}),[value,update,contextualHref]);
 return <Context.Provider value={api}>{children}<WorkspaceContextDrawer open={drawer} onClose={()=>setDrawer(false)}/></Context.Provider>}
export function useWorkspaceContext(){const value=useContext(Context);if(!value)throw new Error("Workspace Context must be consumed within WorkspaceContextProvider.");return value;}
export function ContextLink({href,...props}:LinkProps&React.AnchorHTMLAttributes<HTMLAnchorElement>){const{contextualHref}=useWorkspaceContext();return <Link href={typeof href==="string"?contextualHref(href):href}{...props}/>}

export function workspaceContextKind(pathname:string):WorkspaceContextKind{
 if(pathname==="/dashboard"||pathname.startsWith("/properties")||pathname.startsWith("/bookings"))return"operational";
 if(pathname.startsWith("/dashboard/observe")||pathname.startsWith("/dashboard/insights")||pathname.startsWith("/dashboard/financial")||pathname.startsWith("/dashboard/understand")||pathname.startsWith("/dashboard/portfolio")||pathname.startsWith("/dashboard/learning"))return"intelligence";
 return"configuration";
}
export function WorkspaceContextBar(){const{value,update,openDrawer}=useWorkspaceContext(),pathname=usePathname(),search=useSearchParams(),kind=workspaceContextKind(pathname);return <div className="bg-white" data-workspace-context={kind}><div className="hidden items-stretch lg:flex"><ContextField icon={Building2} label="Workspace"><select value={value.workspaceId} onChange={e=>update({workspaceId:e.target.value})}><option value="current">{value.workspaceLabel}</option></select></ContextField>{kind==="configuration"?<><ContextField icon={Layers3} label="Organization"><span>Luxe Haven Holdings</span></ContextField><ContextField icon={SlidersHorizontal} label="Environment"><span>Production</span></ContextField></>:<><ContextField icon={Layers3} label="Scope"><select value={value.scope} onChange={e=>update({scope:e.target.value})}><option value="entire-portfolio">Entire Portfolio</option><option value="active-properties">Active Properties</option></select></ContextField>{kind==="operational"?<><ContextField icon={CalendarDays} label="Operational window"><OperationalWindowSelect value={value} hasExplicitPeriod={search.has("from")} onChange={update}/></ContextField><span className="ml-3 inline-flex self-center rounded-lg border border-emerald-100 bg-emerald-50 px-3 py-2 text-[11px] font-semibold text-emerald-800"><span className="mr-2 h-2 w-2 self-center rounded-full bg-emerald-500"/>Live</span></>:<><ContextField icon={CalendarDays} label="Reporting period"><button type="button" onClick={openDrawer}>{shortDate(value.from)} – {shortDate(value.to)}</button></ContextField><ContextField icon={ArrowLeftRight} label="Comparison"><button type="button" onClick={openDrawer}>{shortDate(value.compareFrom)} – {shortDate(value.compareTo)}</button></ContextField><ContextField icon={SlidersHorizontal} label="Basis"><select value={value.basis} onChange={e=>update({basis:e.target.value as AccountingBasis})}><option value="actual">Actual</option><option value="accrual">Accrual</option><option value="cash">Cash</option></select></ContextField></>}</>}</div><div className="flex items-center justify-between gap-3 border-b border-stone-200 px-4 py-3 lg:hidden"><WorkspaceContextChip kind={kind}/><button type="button" onClick={openDrawer} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-stone-300 bg-white px-4 text-xs font-semibold"><SlidersHorizontal className="h-4 w-4"/>Change context</button></div></div>}
function OperationalWindowSelect({value,hasExplicitPeriod,onChange}:{value:WorkspaceContextValue;hasExplicitPeriod:boolean;onChange:(patch:Partial<WorkspaceContextValue>)=>void}){const today=iso(new Date()),preset=!hasExplicitPeriod?"today":operationalPreset(value.from,value.to,today);return <select className="min-h-11 rounded-xl border border-stone-300 bg-white px-3 text-sm font-semibold" aria-label="Operational window" value={preset} onChange={event=>{const range=operationalRange(event.target.value,new Date());onChange(range)}}><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="next-3-days">Next 3 Days</option><option value="next-7-days">Next 7 Days</option><option value="this-week">This Week</option><option value="this-weekend">This Weekend</option><option value="custom" disabled>Custom window</option></select>}
function operationalRange(preset:string,now:Date){const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),end=new Date(start);if(preset==="tomorrow"){start.setUTCDate(start.getUTCDate()+1);end.setTime(start.getTime())}else if(preset==="next-3-days")end.setUTCDate(end.getUTCDate()+2);else if(preset==="next-7-days")end.setUTCDate(end.getUTCDate()+6);else if(preset==="this-week")end.setUTCDate(end.getUTCDate()+(7-(end.getUTCDay()||7)));else if(preset==="this-weekend"){const untilSaturday=(6-start.getUTCDay()+7)%7;start.setUTCDate(start.getUTCDate()+untilSaturday);end.setTime(start.getTime());end.setUTCDate(end.getUTCDate()+1)}return{from:iso(start),to:iso(end)}}
function operationalPreset(from:string,to:string,today:string){const ranges=["today","tomorrow","next-3-days","next-7-days","this-week","this-weekend"]as const;return ranges.find(preset=>{const range=operationalRange(preset,new Date(`${today}T00:00:00Z`));return range.from===from&&range.to===to})??"custom"}
function ContextField({icon:Icon,label,children}:{icon:typeof Building2;label:string;children:ReactNode}){return <label className="flex min-w-[170px] items-center gap-2 border-r border-stone-200 px-4 py-2 first:border-l"><Icon aria-hidden="true" className="h-4 w-4 shrink-0 text-stone-500"/><span className="min-w-0"><span className="block text-[8px] font-semibold uppercase tracking-wide text-stone-500">{label}</span><span className="block [&>button]:truncate [&>button]:text-left [&>button]:text-xs [&>button]:font-semibold [&>select]:max-w-full [&>select]:bg-transparent [&>select]:text-xs [&>select]:font-semibold">{children}</span></span></label>}
export function WorkspaceContextChip({kind="operational"}:{kind?:WorkspaceContextKind}){const{value}=useWorkspaceContext();return <span className="min-w-0"><span className="block truncate text-xs font-semibold">{value.workspaceLabel}</span><span className="block truncate text-[11px] text-stone-500">{kind==="configuration"?"Luxe Haven Holdings · Production":kind==="operational"?`${value.scope.replaceAll("-"," ")} · Operational window`:`${value.scope.replaceAll("-"," ")} · ${shortDate(value.from)} – ${shortDate(value.to)}`}</span></span>}
function shortDate(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))}
function WorkspaceContextDrawer({open,onClose}:{open:boolean;onClose:()=>void}){const{value,update}=useWorkspaceContext(),pathname=usePathname(),search=useSearchParams(),home=pathname==="/dashboard";if(!open)return null;return <div className="fixed inset-0 z-[80]" role="dialog" aria-modal="true" aria-labelledby="workspace-context-title"><button aria-label="Close workspace context" className="absolute inset-0 bg-stone-950/50" onClick={onClose}/><section className="absolute inset-y-0 right-0 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-amber-700">Shared workspace context</p><h2 id="workspace-context-title" className="mt-1 text-xl font-semibold">Change context</h2></div><button onClick={onClose} aria-label="Close" className="rounded-lg p-2 hover:bg-stone-100"><X/></button></div><div className="mt-8 grid gap-5"><DrawerSelect label="Workspace" value={value.workspaceId} onChange={workspaceId=>update({workspaceId})} options={[["current",value.workspaceLabel]]}/><DrawerSelect label="Scope" value={value.scope} onChange={scope=>update({scope})} options={[["entire-portfolio","Entire Portfolio"],["active-properties","Active Properties"]]}/>{home?<label className="grid gap-2 text-sm font-semibold">Operational window<OperationalWindowSelect value={value} hasExplicitPeriod={search.has("from")} onChange={update}/></label>:<><DateField label="Reporting period start" value={value.from} onChange={from=>update({from})}/><DateField label="Reporting period end" value={value.to} onChange={to=>update({to})}/><DateField label="Comparison start" value={value.compareFrom} onChange={compareFrom=>update({compareFrom})}/><DateField label="Comparison end" value={value.compareTo} onChange={compareTo=>update({compareTo})}/><DrawerSelect label="Accounting basis" value={value.basis} onChange={basis=>update({basis:basis as AccountingBasis})} options={[["actual","Actual"],["accrual","Accrual"],["cash","Cash"]]}/></>}</div><button onClick={onClose} className="mt-8 w-full rounded-xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white">Apply context</button></section></div>}
function DrawerSelect({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:readonly(readonly[string,string])[]}){return <label className="grid gap-2 text-sm font-semibold">{label}<select className="rounded-xl border border-stone-300 bg-white px-3 py-3 font-normal" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-2 text-sm font-semibold">{label}<input type="date" className="rounded-xl border border-stone-300 px-3 py-3 font-normal" value={value} onChange={e=>onChange(e.target.value)}/></label>}
