import Link from "next/link";
import { addInvestmentScenarioObservationAction, getInvestmentScenarioLearningRequest, recordInvestmentScenarioOutcomeAction } from "@/app/actions/investment-scenario-learning-runtime";
import type { ScenarioLearningProjection } from "@/features/investment-opportunity";

export default async function ScenarioLearningPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const{id}=await params,query=await searchParams,result=await getInvestmentScenarioLearningRequest(id,single(query.scenario));
  if(!result.ok)return <State title="Scenario outcomes are unavailable" message="Confirm your access and return to the opportunity." href={`/dashboard/investments/opportunities/${id}`}/>;
  if(!result.scenario||!result.projection)return <State title="Outcome measurement begins with a saved scenario" message="Create and save an investment strategy before recording operational outcomes." href={`/dashboard/investments/opportunities/${id}/scenarios`}/>;
  const{scenario,projection}=result;
  return <main className="mx-auto max-w-7xl space-y-8 px-5 py-10">
    <header><Link href={`/dashboard/investments/opportunities/${id}/scenarios`}>← Scenario workspace</Link><p className="eyebrow mt-5">Scenario outcomes</p><h1 className="mt-2 text-4xl font-semibold">Projected versus actual</h1><p className="mt-3 max-w-3xl text-stone-600">Treat {scenario.name} as an immutable hypothesis and measure what happened without rewriting history. Interpretations shown here are decision support; they become organizational learning only through the canonical Learning evidence policy.</p></header>
    <nav aria-label="Scenario selection" className="flex flex-wrap gap-2">{result.workspace.scenarios.map(item=><Link key={item.id} aria-current={item.id===scenario.id?"page":undefined} className={`rounded-full border px-4 py-2 text-sm font-semibold ${item.id===scenario.id?"bg-stone-950 text-white":""}`} href={`?scenario=${item.id}`}>{item.name}</Link>)}</nav>
    {projection.state==="no-outcome"?<section className="rounded-2xl border border-dashed p-8"><h2 className="text-2xl font-semibold">Measurement begins after the property enters operation.</h2><p className="mt-2 text-stone-600">Track actual performance to compare this scenario with reality. Missing financial or booking data remains unavailable rather than becoming zero.</p></section>:<Summary projection={projection}/>}
    <OutcomeForm opportunityId={id} scenarioId={scenario.id}/>
    {projection.state!=="no-outcome"?<><VarianceTable projection={projection}/><section><h2 className="text-2xl font-semibold">Assumption validation</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{projection.assumptionValidations.length?projection.assumptionValidations.map(item=><article className="rounded-xl border p-4" key={item.assumption}><div className="flex justify-between gap-3"><h3 className="font-semibold capitalize">{item.assumption.replaceAll("-"," ")}</h3><span className="text-xs font-semibold capitalize">{item.status.replaceAll("-"," ")}</span></div><p className="mt-2 text-sm text-stone-600">{item.rationale}</p></article>):<p className="text-stone-600">No explicit scenario assumptions were captured for independent validation.</p>}</div></section><section><h2 className="text-2xl font-semibold">Interpretation candidates</h2><p className="mt-2 text-sm text-stone-600">These variance interpretations are not validated organizational learning.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{projection.lessons.length?projection.lessons.map((lesson,index)=><article className="rounded-xl border p-4" key={`${lesson.category}-${index}`}><p className="eyebrow">{lesson.category}</p><h3 className="mt-2 font-semibold">{lesson.statement}</h3><p className="mt-2 text-sm text-stone-600">Evidence: {lesson.evidence.join(", ")||"No labeled evidence"}</p></article>):<p className="text-stone-600">No material variance interpretation was identified.</p>}</div></section></>:null}
    <section className="grid gap-6 lg:grid-cols-2"><ObservationForm opportunityId={id} scenarioId={scenario.id}/><div className="rounded-2xl border p-5"><h2 className="text-xl font-semibold">Operator observations</h2><ol className="mt-4 space-y-3">{result.observations.length?result.observations.map(row=><li className="rounded-xl bg-stone-50 p-3" key={String(row.id)}><p className="text-sm">{String(row.body)}</p><time className="mt-1 block text-xs text-stone-500">{date(String(row.observed_at))}</time></li>):<li className="text-sm text-stone-500">No manual observations recorded.</li>}</ol></div></section>
    <section><h2 className="text-2xl font-semibold">Similar historical scenarios</h2><p className="mt-2 text-sm text-stone-600">Similarity currently reflects acquisition strategy and evidence quality. It is context, never a standalone recommendation.</p>{result.pattern?<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{result.pattern.summary} Pattern confidence: {result.pattern.confidence}.</p>:null}<div className="mt-4 grid gap-3 md:grid-cols-2">{result.similar.length?result.similar.map(item=><article className="rounded-xl border p-4" key={item.scenarioId}><p className="font-semibold">{item.similarity}% strategy similarity</p><p className="mt-1 text-sm capitalize text-stone-600">{item.outcome.replaceAll("-"," ")} outcome · {item.confidence} evidence</p></article>):<p className="text-stone-500">No other measured scenarios are available yet.</p>}</div></section>
    {result.outcomes.length?<section><h2 className="text-2xl font-semibold">Outcome history</h2><p className="mt-2 text-sm text-stone-600">Each correction or later measurement creates a new immutable revision.</p><ol className="mt-4 grid gap-3 md:grid-cols-2">{result.outcomes.map(outcome=><li className="rounded-xl border p-4" key={outcome.id}><p className="font-semibold">Revision {outcome.revision}</p><p className="mt-1 text-sm capitalize">{outcome.recommendationOutcome.replaceAll("-"," ")} · {outcome.confidence} confidence</p><p className="mt-1 text-xs text-stone-500">{outcome.periodStart} to {outcome.periodEnd}</p></li>)}</ol></section>:null}
    <section><h2 className="text-2xl font-semibold">Learning timeline</h2><ol className="mt-4 space-y-3 border-l pl-5">{result.activity.length?result.activity.map(row=><li className="rounded-xl border p-4" key={String(row.id)}><p className="font-semibold capitalize">{String(row.event_type).replaceAll("-"," ")}</p><p className="mt-1 text-sm text-stone-600">{String(row.safe_summary)}</p><time className="mt-1 block text-xs">{date(String(row.occurred_at))}</time></li>):<li className="text-sm text-stone-500">Scenario saved. Operational learning has not started.</li>}</ol></section>
  </main>;
}
function Summary({projection}:{projection:ScenarioLearningProjection}){return <section className="grid gap-4 md:grid-cols-4"><Stat label="Prediction accuracy" value={projection.summary.predictionAccuracy}/><Stat label="Confidence calibration" value={projection.confidenceCalibration.observedAccuracy}/><Stat label="Best assumption" value={projection.summary.bestAssumption??"Unavailable"}/><Stat label="Weakest assumption" value={projection.summary.weakestAssumption??"Unavailable"}/><p className="rounded-xl bg-stone-950 p-5 text-white md:col-span-4">{projection.summary.overallLearning}</p></section>}
function VarianceTable({projection}:{projection:ScenarioLearningProjection}){return <section><h2 className="text-2xl font-semibold">Variance analysis</h2><div className="mt-4 overflow-x-auto rounded-2xl border" role="region" aria-label="Projected versus actual metrics" tabIndex={0}><table className="min-w-full text-left text-sm"><thead><tr><th className="p-4">Metric</th><th className="p-4">Projected</th><th className="p-4">Actual</th><th className="p-4">Variance</th><th className="p-4">Direction</th></tr></thead><tbody>{projection.metrics.map(item=><tr className="border-t" key={item.key}><th className="p-4">{item.label}</th><td className="p-4">{format(item.projected,item.unit)}</td><td className="p-4">{format(item.actual,item.unit)}</td><td className="p-4">{item.absoluteVariance===undefined?"Unavailable":`${item.absoluteVariance>=0?"+":""}${format(item.absoluteVariance,item.unit)}${item.percentageVariance===undefined?"":` · ${item.percentageVariance.toFixed(1)}%`}`}</td><td className="p-4 capitalize">{item.direction}</td></tr>)}</tbody></table></div></section>}
function OutcomeForm({opportunityId,scenarioId}:{opportunityId:string;scenarioId:string}){return <details className="rounded-2xl border p-5"><summary className="cursor-pointer text-lg font-semibold">Record measured outcome</summary><form action={recordInvestmentScenarioOutcomeAction} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="opportunityId" value={opportunityId}/><input type="hidden" name="scenarioId" value={scenarioId}/><input type="hidden" name="commandId" value={crypto.randomUUID()}/><Field label="Period start" name="periodStart" type="date" required/><Field label="Period end" name="periodEnd" type="date" required/>{[["annualRevenue","Actual annual revenue"],["adr","Actual ADR"],["occupancy","Actual occupancy %"],["operatingExpenses","Actual operating expenses"],["noi","Actual NOI"],["annualCashFlow","Actual annual cash flow"],["cashOnCashReturn","Actual CoC %"]].map(([name,label])=><Field key={name} label={label} name={name} type="number" step="any"/>)}<label className="text-sm font-semibold">Recommendation outcome<select name="recommendationOutcome" className="mt-1 w-full rounded-xl border p-3"><option value="successful">Successful</option><option value="mixed">Mixed</option><option value="unsuccessful">Unsuccessful</option><option value="insufficient-data">Insufficient data</option></select></label><label className="text-sm font-semibold">Evidence confidence<select name="confidence" className="mt-1 w-full rounded-xl border p-3"><option value="high">High</option><option value="moderate">Moderate</option><option value="low">Low</option><option value="insufficient-evidence">Insufficient evidence</option></select></label><label className="text-sm font-semibold">Evidence source<select name="evidenceSource" className="mt-1 w-full rounded-xl border p-3"><option value="financial">Financial</option><option value="bookings">Bookings</option><option value="market">Market</option><option value="operator-notes">Operator notes</option><option value="manual-observation">Manual observation</option></select></label><Field label="Evidence label" name="evidenceLabel" type="text" required/><button className="rounded-full bg-stone-950 px-5 py-3 font-semibold text-white sm:col-span-2">Append outcome measurement</button></form></details>}
function ObservationForm({opportunityId,scenarioId}:{opportunityId:string;scenarioId:string}){return <form action={addInvestmentScenarioObservationAction} className="rounded-2xl border p-5"><input type="hidden" name="opportunityId" value={opportunityId}/><input type="hidden" name="scenarioId" value={scenarioId}/><input type="hidden" name="commandId" value={crypto.randomUUID()}/><input type="hidden" name="observedAt" value={new Date().toISOString()}/><h2 className="text-xl font-semibold">Add operator observation</h2><textarea className="mt-4 min-h-32 w-full rounded-xl border p-3" name="body" maxLength={5000} required placeholder="Record market, neighborhood, operating, or property context."/><button className="mt-3 rounded-full border px-4 py-2 font-semibold">Append observation</button></form>}
function Field({label,...props}:{label:string;name:string;type:string;required?:boolean;step?:string}){return <label className="text-sm font-semibold">{label}<input className="mt-1 w-full rounded-xl border p-3" {...props}/></label>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-4"><p className="eyebrow">{label}</p><p className="mt-2 font-semibold capitalize">{value}</p></div>}
function format(value:number|undefined,unit:string){if(value===undefined)return"Unavailable";return unit==="currency"?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value):`${value.toFixed(1)}%`}
function single(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}function date(value:string){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}function State({title,message,href}:{title:string;message:string;href:string}){return <main className="mx-auto max-w-2xl px-5 py-20 text-center"><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-3 text-stone-600">{message}</p><Link className="mt-5 inline-block rounded-full border px-4 py-2 font-semibold" href={href}>Continue</Link></main>}
