import{describe,expect,it}from"vitest";
import{beginCanonicalLearningReview,buildLearningGuidanceProjection,calculateCanonicalLearningConfidence,generateCanonicalLearningCandidate,scheduleCanonicalLearningReview,validateCanonicalLearning}from".";
import type{LearningLineage,ValidatedLearningArtifact}from"../domain";
const ref=(type:"observation"|"decision"|"action"|"outcome"|"review",sourceId=type)=>({type,capability:"test",sourceId});
const lineage:LearningLineage={observations:[ref("observation")],decisions:[ref("decision")],actions:[ref("action")],outcomes:[ref("outcome")],reviews:[ref("review")]};
const factors={observationCount:10,consistentOutcomeCount:5,sampleSize:30,timeHorizonDays:365,businessImpact:80,dataQuality:.9,recencyDays:10,contradictionCount:0};
function candidate(){return generateCanonicalLearningCandidate({workspaceId:"w",seriesId:"series",category:"financial",statement:"Utility costs exceed forecasts.",applicability:[{dimension:"workspace",referenceId:"w"}],lineage,createdAt:"2026-07-28T00:00:00Z",confidenceFactors:factors})}
describe("canonical Learning Intelligence engine",()=>{
  it("requires the complete observation-to-review lineage",()=>{expect(()=>generateCanonicalLearningCandidate({workspaceId:"w",seriesId:"s",category:"revenue",statement:"x",applicability:[{dimension:"workspace",referenceId:"w"}],lineage:{...lineage,actions:[]},createdAt:"2026-07-28",confidenceFactors:factors})).toThrow("LEARNING_EXECUTION_REQUIRED")});
  it("generates deterministic candidates only from measurable outcomes",()=>{const first=candidate(),second=candidate();expect(first.id).toBe(second.id);expect(first.validationStatus).toBe("proposed");expect(first.lineage.outcomes).toHaveLength(1)});
  it("calculates confidence deterministically and reduces it for contradictions and stale evidence",()=>{const strong=calculateCanonicalLearningConfidence(factors),weak=calculateCanonicalLearningConfidence({...factors,recencyDays:700,contradictionCount:3});expect(strong.score).toBeGreaterThan(weak.score);expect(strong.level).toBe("high")});
  it("validates immutable versions and feeds version-specific guidance downstream",()=>{const value=candidate(),review=beginCanonicalLearningReview(scheduleCanonicalLearningReview(value,{id:"review-1",scheduledAt:"2026-07-29",reviewerProfileId:"p"}),"p");const first=validateCanonicalLearning(value,review,{id:"learning-v1",futureGuidance:"Increase utility assumptions.",reviewerProfileId:"p",validatedAt:"2026-08-01"});const second=validateCanonicalLearning(value,review,{id:"learning-v2",futureGuidance:"Increase utility assumptions by market.",reviewerProfileId:"p",validatedAt:"2026-09-01",previous:first});expect(second).toMatchObject({version:2,supersedesLearningId:"learning-v1"});expect(first.futureGuidance).toBe("Increase utility assumptions.");const guidance=buildLearningGuidanceProjection("financial",[first,second],"2026-09-02");expect(guidance.guidance[0]).toMatchObject({learningId:"learning-v2",learningVersion:2})});
  it("does not feed retired or unrelated knowledge into decisions",()=>{const value=candidate(),review=beginCanonicalLearningReview(scheduleCanonicalLearningReview(value,{id:"r",scheduledAt:"2026-07-29"}),"p");const learning=validateCanonicalLearning(value,review,{id:"l",futureGuidance:"Adjust.",reviewerProfileId:"p",validatedAt:"2026-08-01"});expect(buildLearningGuidanceProjection("revenue",[learning],"now").guidance).toEqual([]);expect(buildLearningGuidanceProjection("financial",[{...learning,status:"retired"} as ValidatedLearningArtifact],"now").guidance).toEqual([])});
});
