import { ExecutionStatus, type ExecutionDiagnostics, type ExecutionStatistics } from "../../execution";
import type { ObservationValue } from "../../observations";
import { LearningCollection } from "../domain";

export type LearningSessionInput = Readonly<{ learning: LearningCollection; status: ExecutionStatus; statistics: ExecutionStatistics; diagnostics: ExecutionDiagnostics; metadata?: Readonly<Record<string, ObservationValue>> }>;
export class LearningSession {
  public readonly learning: LearningCollection; public readonly status: ExecutionStatus; public readonly statistics: ExecutionStatistics; public readonly diagnostics: ExecutionDiagnostics; public readonly metadata: Readonly<Record<string, ObservationValue>>;
  private constructor(input: LearningSessionInput) { for (const value of [input.statistics.processed, input.statistics.succeeded, input.statistics.skipped, input.statistics.failed]) if (!Number.isSafeInteger(value) || value < 0) throw new RangeError("Learning execution statistics must be non-negative integers."); if (input.statistics.succeeded !== input.learning.size || input.statistics.succeeded + input.statistics.skipped + input.statistics.failed !== input.statistics.processed) throw new RangeError("Learning execution statistics must match policies processed."); this.learning = input.learning; this.status = input.status; this.statistics = Object.freeze({ ...input.statistics, startedAt: new Date(input.statistics.startedAt), ...(input.statistics.completedAt ? { completedAt: new Date(input.statistics.completedAt) } : {}) }); this.diagnostics = Object.freeze({ warnings: Object.freeze([...input.diagnostics.warnings]), errors: Object.freeze([...input.diagnostics.errors]), skippedItems: Object.freeze([...input.diagnostics.skippedItems]), exceptions: Object.freeze([...input.diagnostics.exceptions]) }); this.metadata = Object.freeze({ ...input.metadata }); Object.freeze(this); }
  public static create(input: LearningSessionInput): LearningSession { return new LearningSession(input); }
}
