import type { GovernedExecutionActivity, GovernedExecutionRepository, GovernedNotificationIntent } from "../application/automation-governed-execution";
import type { AutomationApproval, AutomationDispatchResult, AutomationPolicyDecision, AutomationRun, AutomationRunStep } from "../domain/automation-governed-execution";
import type { TriggerSupabaseClient } from "./supabase-automation-trigger-repository";

export class SupabaseAutomationGovernedExecutionRepository implements GovernedExecutionRepository {
  public constructor(private readonly client: TriggerSupabaseClient) {}
  async getRunByRequest(tenantId: string, runRequestId: string) { const result = await this.client.from("automation_runs").select("*").eq("workspace_id", tenantId).eq("run_request_id", runRequestId).maybeSingle(); check(result.error, "Run read failed."); return result.data ? mapRun(result.data) : null; }
  async getRun(tenantId: string, runId: string) { const result = await this.client.from("automation_runs").select("*").eq("workspace_id", tenantId).eq("id", runId).maybeSingle(); check(result.error, "Run read failed."); return result.data ? mapRun(result.data) : null; }
  async getApproval(tenantId: string, approvalId: string) { const result = await this.client.from("automation_approval_requests").select("*").eq("workspace_id", tenantId).eq("id", approvalId).maybeSingle(); check(result.error, "Approval read failed."); return result.data ? mapApproval(result.data) : null; }
  async getSteps(tenantId: string, runId: string) { const result = await this.client.from("automation_run_steps").select("*").eq("workspace_id", tenantId).eq("run_id", runId).order("step_key", { ascending: true }); check(result.error, "Run steps read failed."); return Object.freeze(rows(result.data).map(mapStep)); }
  async materialize(input: Readonly<{ run: AutomationRun; steps: readonly AutomationRunStep[]; activity: GovernedExecutionActivity }>) {
    const result = await this.client.rpc("materialize_automation_run", { p_run: runRow(input.run), p_steps: input.steps.map(stepRow), p_activity: activityRow(input.activity) }); check(result.error, "Run materialization failed."); const value = record(result.data), run = mapRun(record(value.run)); return Object.freeze({ created: Boolean(value.created), run, steps: Boolean(value.created) ? input.steps : await this.getSteps(run.tenantId, run.id) });
  }
  async applyPolicy(input: Readonly<{ run: AutomationRun; expectedVersion: number; decision: AutomationPolicyDecision; steps: readonly AutomationRunStep[]; approval?: AutomationApproval; activity: readonly GovernedExecutionActivity[]; notifications: readonly GovernedNotificationIntent[] }>) {
    const result = await this.client.rpc("apply_automation_run_policy", { p_run: runRow(input.run), p_expected_version: input.expectedVersion, p_decision: decisionRow(input.decision, input.run.tenantId), p_steps: input.steps.map(stepRow), p_approval: input.approval ? approvalRow(input.approval) : null, p_activity: input.activity.map(activityRow), p_notifications: input.notifications.map(notificationRow) }); check(result.error, "Run policy persistence failed."); return mapRun(record(result.data));
  }
  async transition(input: Readonly<{ run: AutomationRun; steps?: readonly AutomationRunStep[]; expectedVersion: number; activity: readonly GovernedExecutionActivity[]; notifications?: readonly GovernedNotificationIntent[] }>) {
    const result = await this.client.rpc("transition_automation_run", { p_run: runRow(input.run), p_expected_version: input.expectedVersion, p_steps: (input.steps ?? []).map(stepRow), p_activity: input.activity.map(activityRow), p_notifications: (input.notifications ?? []).map(notificationRow) }); check(result.error, "Run transition failed."); return mapRun(record(result.data));
  }
  async decideApproval(input: Readonly<{ approval: AutomationApproval; expectedVersion: number; run: AutomationRun; expectedRunVersion: number; steps: readonly AutomationRunStep[]; dispositionId: string; activity: readonly GovernedExecutionActivity[]; notifications: readonly GovernedNotificationIntent[] }>) { const result = await this.client.rpc("decide_automation_approval", { p_approval: approvalRow(input.approval), p_expected_approval_version: input.expectedVersion, p_run: runRow(input.run), p_expected_run_version: input.expectedRunVersion, p_steps: input.steps.map(stepRow), p_disposition_id: input.dispositionId, p_activity: input.activity.map(activityRow), p_notifications: input.notifications.map(notificationRow) }); check(result.error, "Approval decision failed."); const value = record(result.data); return Object.freeze({ approval: mapApproval(record(value.approval)), run: mapRun(record(value.run)) }); }
  async claimStep(input: Readonly<{ tenantId: string; stepId: string; expectedVersion: number; workerId: string; now: string; leaseDurationMs: number }>) { const result = await this.client.rpc("claim_automation_run_step", { p_workspace_id: input.tenantId, p_step_id: input.stepId, p_expected_version: input.expectedVersion, p_worker_id: input.workerId, p_now: input.now, p_duration_ms: input.leaseDurationMs }); check(result.error, "Run step claim failed."); return result.data ? mapStep(record(result.data)) : null; }
  async heartbeatStep(input: Readonly<{ tenantId: string; stepId: string; workerId: string; leaseGeneration: number; expectedVersion: number; now: string; leaseDurationMs: number }>) { const result = await this.client.rpc("heartbeat_automation_run_step", { p_workspace_id: input.tenantId, p_step_id: input.stepId, p_worker_id: input.workerId, p_lease_generation: input.leaseGeneration, p_expected_version: input.expectedVersion, p_now: input.now, p_duration_ms: input.leaseDurationMs }); check(result.error, "Run step heartbeat failed."); return mapStep(record(result.data)); }
  async reclaimExpiredStep(input: Readonly<{ tenantId: string; stepId: string; expectedVersion: number; now: string; outcomeChecked: boolean }>) { const result = await this.client.rpc("reclaim_expired_automation_run_step", { p_workspace_id: input.tenantId, p_step_id: input.stepId, p_expected_version: input.expectedVersion, p_now: input.now, p_outcome_checked: input.outcomeChecked }); check(result.error, "Run step reclaim failed."); return mapStep(record(result.data)); }
  async markDispatching(input: Readonly<{ step: AutomationRunStep; expectedVersion: number; now: string; activity: GovernedExecutionActivity }>) { const result = await this.client.rpc("mark_automation_step_dispatching", { p_step: stepRow(input.step), p_expected_version: input.expectedVersion, p_now: input.now, p_activity: activityRow(input.activity) }); check(result.error, "Run step dispatch preparation failed."); return mapStep(record(result.data)); }
  async recordDispatch(input: Readonly<{ run: AutomationRun; step: AutomationRunStep; expectedRunVersion: number; expectedStepVersion: number; result: AutomationDispatchResult; attemptId: string; now: string; activity: readonly GovernedExecutionActivity[]; notifications: readonly GovernedNotificationIntent[] }>) {
    const result = await this.client.rpc("record_automation_dispatch", { p_run: runRow(input.run), p_step: stepRow(input.step), p_expected_run_version: input.expectedRunVersion, p_expected_step_version: input.expectedStepVersion, p_attempt: { id: input.attemptId, workspace_id: input.run.tenantId, run_id: input.run.id, step_id: input.step.id, attempt_number: input.step.attemptCount + 1, command_id: input.step.deterministicCommandId, idempotency_key: input.step.idempotencyKey, classification: input.result.classification, owning_command_id: input.result.owningCommandId ?? null, safe_result_reference: input.result.safeResultReference ?? null, started_at: input.now, completed_at: input.now }, p_activity: input.activity.map(activityRow), p_notifications: input.notifications.map(notificationRow) }); check(result.error, "Dispatch result persistence failed."); const value = record(result.data); return Object.freeze({ run: mapRun(record(value.run)), step: mapStep(record(value.step)) });
  }
}

function mapRun(row: Record<string, unknown>): AutomationRun { return Object.freeze({ id: String(row.id), tenantId: String(row.workspace_id), propertyIds: Object.freeze(strings(row.property_ids)), automationDefinitionId: String(row.automation_id), automationDefinitionVersionId: String(row.automation_definition_version_id), automationDefinitionVersion: Number(row.automation_definition_version), runRequestId: String(row.run_request_id), triggerOccurrenceId: String(row.trigger_occurrence_id), executionPlanVersion: String(row.execution_plan_version), initiatingActorId: String(row.initiating_actor_id), serviceActorPolicyId: String(row.service_actor_policy_id), correlationId: String(row.correlation_id), causationId: String(row.causation_id), status: row.status as AutomationRun["status"], ...(row.policy_decision_id ? { policyDecisionId: String(row.policy_decision_id) } : {}), ...(row.approval_id ? { approvalId: String(row.approval_id) } : {}), createdAt: String(row.created_at), updatedAt: String(row.updated_at), ...(row.deadline_at ? { deadlineAt: String(row.deadline_at) } : {}), version: Number(row.version) }); }
function runRow(v: AutomationRun) { return { id: v.id, workspace_id: v.tenantId, property_ids: v.propertyIds, automation_id: v.automationDefinitionId, automation_definition_version_id: v.automationDefinitionVersionId, automation_definition_version: v.automationDefinitionVersion, run_request_id: v.runRequestId, trigger_occurrence_id: v.triggerOccurrenceId, execution_plan_version: v.executionPlanVersion, initiating_actor_id: v.initiatingActorId, service_actor_policy_id: v.serviceActorPolicyId, correlation_id: v.correlationId, causation_id: v.causationId, status: v.status, policy_decision_id: v.policyDecisionId ?? null, approval_id: v.approvalId ?? null, created_at: v.createdAt, updated_at: v.updatedAt, deadline_at: v.deadlineAt ?? null, version: v.version }; }
function mapStep(row: Record<string, unknown>): AutomationRunStep { return Object.freeze({ id: String(row.id), tenantId: String(row.workspace_id), runId: String(row.run_id), stepKey: String(row.step_key), owningCapability: String(row.owning_capability), commandType: String(row.command_type), commandContractVersion: String(row.command_contract_version), dependencies: Object.freeze(strings(row.dependencies)), ...(row.concurrency_group ? { concurrencyGroup: String(row.concurrency_group) } : {}), status: row.status as AutomationRunStep["status"], deterministicCommandId: String(row.deterministic_command_id), idempotencyKey: String(row.idempotency_key), ...(row.expected_target_version === null || row.expected_target_version === undefined ? {} : { expectedTargetVersion: Number(row.expected_target_version) }), attemptCount: Number(row.attempt_count), ...(row.next_attempt_at ? { nextAttemptAt: String(row.next_attempt_at) } : {}), ...(row.lease_owner ? { leaseOwner: String(row.lease_owner) } : {}), ...(row.lease_acquired_at ? { leaseAcquiredAt: String(row.lease_acquired_at) } : {}), ...(row.lease_expires_at ? { leaseExpiresAt: String(row.lease_expires_at) } : {}), leaseGeneration: Number(row.lease_generation), version: Number(row.version) }); }
function stepRow(v: AutomationRunStep) { return { id: v.id, workspace_id: v.tenantId, run_id: v.runId, step_key: v.stepKey, owning_capability: v.owningCapability, command_type: v.commandType, command_contract_version: v.commandContractVersion, dependencies: v.dependencies, concurrency_group: v.concurrencyGroup ?? null, status: v.status, deterministic_command_id: v.deterministicCommandId, idempotency_key: v.idempotencyKey, expected_target_version: v.expectedTargetVersion ?? null, attempt_count: v.attemptCount, next_attempt_at: v.nextAttemptAt ?? null, lease_owner: v.leaseOwner ?? null, lease_acquired_at: v.leaseAcquiredAt ?? null, lease_expires_at: v.leaseExpiresAt ?? null, lease_generation: v.leaseGeneration, version: v.version }; }
function decisionRow(v: AutomationPolicyDecision, tenantId: string) { return { id: v.id, workspace_id: tenantId, run_id: v.runId, disposition: v.disposition, policy_version: v.policyVersion, target_context_version: v.targetContextVersion, matched_rules: v.matchedRules, missing_facts: v.missingFacts, safe_explanation: v.safeExplanation, evaluated_at: v.evaluatedAt }; }
function approvalRow(v: AutomationApproval) { return { id: v.id, workspace_id: v.tenantId, run_id: v.runId, step_ids: v.stepIds, definition_version_id: v.definitionVersionId, command_fingerprint: v.commandFingerprint, target_context_version: v.targetContextVersion, policy_version: v.policyVersion, status: v.status, requested_at: v.requestedAt, expires_at: v.expiresAt, decided_by: v.decidedBy ?? null, decided_at: v.decidedAt ?? null, reason: v.reason ?? null, version: v.version }; }
function mapApproval(row: Record<string, unknown>): AutomationApproval { return Object.freeze({ id: String(row.id), tenantId: String(row.workspace_id), runId: String(row.run_id), stepIds: Object.freeze(strings(row.step_ids)), definitionVersionId: String(row.definition_version_id), commandFingerprint: String(row.command_fingerprint), targetContextVersion: String(row.target_context_version), policyVersion: String(row.policy_version), status: row.status as AutomationApproval["status"], requestedAt: String(row.requested_at), expiresAt: String(row.expires_at), ...(row.decided_by ? { decidedBy: String(row.decided_by) } : {}), ...(row.decided_at ? { decidedAt: String(row.decided_at) } : {}), ...(row.reason ? { reason: String(row.reason) } : {}), version: Number(row.version) }); }
function activityRow(v: GovernedExecutionActivity) { return { id: v.id, workspace_id: v.tenantId, run_id: v.runId, step_id: v.stepId ?? null, event_type: v.eventType, actor_id: v.actorId, occurred_at: v.occurredAt, correlation_id: v.correlationId, causation_id: v.causationId, aggregate_version: v.aggregateVersion, safe_metadata: v.safeMetadata }; }
function notificationRow(v: GovernedNotificationIntent) { return { id: v.id, recipient_id: v.recipientId, event_type: v.eventType, entity_id: v.entityId, idempotency_key: v.idempotencyKey, safe_template_variables: v.safeVariables, created_at: v.createdAt }; }
function check(error: { message: string; code?: string } | null, message: string): asserts error is null { if (!error) return; if (error.code === "40001") throw new Error("CONCURRENT_MODIFICATION"); if (error.code === "42501") throw new Error("CROSS_TENANT_ACCESS_DENIED"); throw new Error(message); }
function rows(value: unknown) { return Array.isArray(value) ? value.filter((entry): entry is Record<string, unknown> => Boolean(entry) && typeof entry === "object") : []; }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function strings(value: unknown) { return Array.isArray(value) ? value.map(String) : []; }
