import {
  InvestmentWorkspace,
} from "@/features/investment-intelligence";
import { SaveOpportunityPanel } from "@/features/investment-opportunity/components";
import { hydrateReanalysis, readImmutableAnalysis } from "@/features/investment-opportunity";
import { getInvestmentOpportunityRequestContext } from "@/app/actions/investment-opportunity-runtime";
import Link from "next/link";
import { AcquisitionType } from "@/features/investment-intelligence";

export default async function NewInvestmentAnalysisPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams, opportunityId = single(params.opportunity), sourceVersionId=single(params.analysis);
  const context = await getInvestmentOpportunityRequestContext();
  const authorized=single(params.mode) === "reanalyze"&&context?.ok&&opportunityId?await context.authorizeOpportunity(opportunityId,"analysis.reanalyze",sourceVersionId):false;
  const projection=authorized&&context?.ok&&opportunityId?await readImmutableAnalysis(context.repository,{ownerId:context.ownerId,opportunityId,...(sourceVersionId?{analysisVersionId:sourceVersionId}:{})}):null;
  const bootstrap=projection&&context?.ok?hydrateReanalysis(projection,{workspaceId:context.workspaceId}):null;
  const strategy = single(params.strategy), routeInitialValues = strategy === AcquisitionType.RentalArbitrage || strategy === AcquisitionType.Purchase ? { acquisitionType: strategy } : undefined;
  if(!bootstrap&&!routeInitialValues){const query=new URLSearchParams();for(const[key,value]of Object.entries(params)){if(key==="step"||key==="strategy")continue;for(const item of Array.isArray(value)?value:value?[value]:[])query.append(key,item)}const href=(value:AcquisitionType)=>{const next=new URLSearchParams(query);next.set("strategy",value);return`/dashboard/investments/new?${next}`};return <main className="mx-auto max-w-5xl px-5 py-12"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Investment Intelligence · Analyze</p><h1 className="mt-3 text-4xl font-semibold">Choose an investment strategy</h1><p className="mt-3 max-w-2xl text-stone-600">Your strategy determines the capital or lease structure in step two. The remaining guided analysis is shared.</p><div className="mt-8 grid gap-5 md:grid-cols-2"><Link href={href(AcquisitionType.Purchase)} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm outline-none hover:border-stone-950 focus-visible:ring-2 focus-visible:ring-teal-600"><span className="text-xl font-semibold">Purchase</span><span className="mt-2 block text-sm leading-6 text-stone-600">Evaluate acquisition cost, financing, equity, revenue, operations, intelligence, and decision readiness.</span><span className="mt-6 block text-sm font-semibold">Start purchase analysis →</span></Link><Link href={href(AcquisitionType.RentalArbitrage)} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm outline-none hover:border-stone-950 focus-visible:ring-2 focus-visible:ring-teal-600"><span className="text-xl font-semibold">Rental Arbitrage</span><span className="mt-2 block text-sm leading-6 text-stone-600">Evaluate lease structure, startup capital, revenue, operations, intelligence, and decision readiness.</span><span className="mt-6 block text-sm font-semibold">Start rental-arbitrage analysis →</span></Link></div></main>}
  return <InvestmentWorkspace draftScope={!bootstrap && context.ok ? context.actorId : undefined} initialValues={bootstrap?.workspaceValues??routeInitialValues} contextNotice={bootstrap ? <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-950">Reanalyzing: {projection!.opportunity.property.displayAddress}</p><p className="mt-1 text-sm text-blue-800">Source: Analysis {bootstrap.source.sourceVersionNumber} · Saved {new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeZone: "UTC" }).format(new Date(bootstrap.source.sourceCreatedAt))}</p><p className="mt-2 text-xs text-blue-700">Persisted assumptions were restored from this exact version. New provider evidence and defaults remain alternatives until explicitly accepted.</p></div><Link href={`/dashboard/investments/opportunities/${bootstrap.source.opportunityId}`} className="text-sm font-semibold text-blue-900 underline">Cancel Reanalysis</Link></div></section> : undefined} resultsActions={<SaveOpportunityPanel />} />;
}
function single(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
