import type { ReservationContext } from "@/features/reservation-context";
import { buildSuggestedReply, type CommunicationTemplate, type GuestCommunicationWorkspace, type GuestConversation, type GuestMessage } from "../domain";
export interface GuestCommunicationRepository{list(workspaceId:string):Promise<readonly GuestConversation[]>;get(workspaceId:string,conversationId:string):Promise<GuestConversation|null>;appendMessage(message:GuestMessage,expectedRevision:number):Promise<GuestConversation>;addNote(input:{conversationId:string;workspaceId:string;body:string;pinned:boolean;authorProfileId:string;expectedRevision:number}):Promise<GuestConversation>;}
export interface GuestCommunicationProvider{send(input:{providerConversationId:string;body:string;idempotencyKey:string;attachments:readonly {type:string;url:string}[]}):Promise<{providerMessageId:string;status:"sent"|"delivered"|"queued"}>;}
export interface GuestCommunicationContextPort{getReservationContext(bookingId:string):Promise<ReservationContext|null>;getPublishedGuidebook(propertyId:string):Promise<{publishedUrl:string}|null>;}
export interface GuestCommunicationAiPort{draft(input:{timeline:GuestConversation["timeline"];reservation:ReservationContext;guidebook?:{publishedUrl:string};instruction?:string}):Promise<string>;}
export function filterConversations(conversations:readonly GuestConversation[],input:{query?:string;status?:GuestConversation["status"];propertyId?:string;assignedToProfileId?:string},labels:Readonly<Record<string,string>>={}){
 const q=input.query?.trim().toLowerCase();return conversations.filter(c=>(!input.status||c.status===input.status)&&(!input.propertyId||c.propertyId===input.propertyId)&&(!input.assignedToProfileId||c.assignedToProfileId===input.assignedToProfileId)&&(!q||[c.id,c.reservationId,c.bookingId,labels[c.guestId],labels[c.propertyId],...c.timeline.map(e=>e.summary)].some(v=>v?.toLowerCase().includes(q))));
}
export async function getGuestCommunicationWorkspace(deps:{repository:GuestCommunicationRepository;context:GuestCommunicationContextPort;templates:readonly CommunicationTemplate[]},input:{workspaceId:string;conversationId:string;evaluatedAt?:string}):Promise<GuestCommunicationWorkspace|null>{
 const conversation=await deps.repository.get(input.workspaceId,input.conversationId);if(!conversation)return null;const reservation=await deps.context.getReservationContext(conversation.bookingId);if(!reservation||reservation.workspaceId!==input.workspaceId)return null;const guidebook=await deps.context.getPublishedGuidebook(conversation.propertyId);return Object.freeze({conversation,reservation,templates:Object.freeze(deps.templates.filter(t=>t.status==="active")),guidebook:{available:Boolean(guidebook),...(guidebook?{publishedUrl:guidebook.publishedUrl}:{})},linkedActionIds:Object.freeze(conversation.timeline.filter(e=>e.type==="action-created").map(e=>e.summary)),state:reservation.freshness.status==="degraded"?"degraded":reservation.operationalNeeds.length?"partial":"ready",evaluatedAt:input.evaluatedAt??new Date().toISOString()});
}
export async function generateSuggestedReply(deps:{ai:GuestCommunicationAiPort},workspace:GuestCommunicationWorkspace,instruction?:string){const draft=await deps.ai.draft({timeline:workspace.conversation.timeline,reservation:workspace.reservation,...(workspace.guidebook?.publishedUrl?{guidebook:{publishedUrl:workspace.guidebook.publishedUrl}}:{}),instruction});return buildSuggestedReply({conversation:workspace.conversation,reservation:workspace.reservation,guidebook:workspace.guidebook,draft});}
