"use client";

import { Download, ExternalLink, HelpCircle, MoreHorizontal, RefreshCw, Settings2, X } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { getIntelligenceReportRequestHref, understandRoutes } from "@/platform/experience";
import { ContextLink } from "@/platform/workspace-context";

type Capability = "revenue" | "financial" | "executive" | "portfolio";

export function IntelligencePageActions({ capability }: { capability: Capability }) {
  const pathname = usePathname(), searchParams = useSearchParams(), router = useRouter(), ref = useRef<HTMLDivElement>(null);
  const [menu, setMenu] = useState(false), [drawer, setDrawer] = useState<"sources"|"export"|"help"|null>(null);
  const [refreshing, setRefreshing] = useState(false), [feedback, setFeedback] = useState("");
  const title = capability === "financial" ? "Financial Intelligence" : capability === "revenue" ? "Revenue Intelligence" : capability === "executive" ? "Executive Intelligence" : "Portfolio Intelligence";
  const understand = capability === "executive" || capability === "portfolio";
  const returnTarget = `${pathname}${searchParams.size ? `?${searchParams.toString()}` : ""}`;
  const connectedSystemsHref = `/dashboard/workspace/connected-systems?returnTo=${encodeURIComponent(returnTarget)}`;
  const onAttention = pathname === understandRoutes.attention;
  const onDataQuality = pathname === understandRoutes.portfolioDataQuality;
  useEffect(() => { if (!menu) return; const close=(event:MouseEvent)=>{if(ref.current&&!ref.current.contains(event.target as Node))setMenu(false)}; document.addEventListener("mousedown",close); return()=>document.removeEventListener("mousedown",close); }, [menu]);
  function refresh() { setMenu(false); setRefreshing(true); setFeedback(""); router.refresh(); window.setTimeout(()=>{setRefreshing(false);setFeedback(`Data refreshed ${new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date())}`)},500); }
  return <>
    <button type="button" onClick={()=>setDrawer("export")} className="hidden min-h-10 items-center gap-2 rounded-md border border-stone-200 bg-white px-4 text-xs font-semibold text-stone-800 sm:inline-flex"><Download className="h-3.5 w-3.5"/>Export</button>
    <div ref={ref} className="relative"><button type="button" aria-label={`${title} actions`} aria-haspopup="menu" aria-expanded={menu} onClick={()=>setMenu(v=>!v)} className="grid h-10 w-10 place-items-center rounded-md border border-stone-200 bg-white"><MoreHorizontal className="h-4 w-4"/></button>{menu?<div role="menu" aria-label={`${title} actions`} className="absolute right-0 z-30 mt-1 w-60 rounded-lg border bg-white py-1 text-sm shadow-xl">
      <MenuButton icon={<RefreshCw/>} onClick={refresh}>{refreshing?"Refreshing…":understand?"Refresh intelligence":"Refresh data"}</MenuButton>
      <MenuButton icon={<ExternalLink/>} onClick={()=>{setMenu(false);setDrawer("sources")}}>View data sources</MenuButton>
      {understand && !onAttention && !onDataQuality ? <Link role="menuitem" href={`${capability === "executive" ? understandRoutes.attention : understandRoutes.portfolioDataQuality}?returnTo=${encodeURIComponent(returnTarget)}`} className="flex min-h-10 items-center gap-3 px-4 hover:bg-stone-50"><Settings2 className="h-4 w-4"/>{capability === "executive" ? "Review attention" : "Review data quality"}</Link> : !understand ? <Link role="menuitem" href={connectedSystemsHref} className="flex min-h-10 items-center gap-3 px-4 hover:bg-stone-50"><Settings2 className="h-4 w-4"/>Manage {capability === "financial" ? "financial" : "revenue"} data</Link> : null}
      <MenuButton icon={<Download/>} onClick={()=>{setMenu(false);setDrawer("export")}}>Export options</MenuButton>
      <div className="my-1 border-t"/><MenuButton icon={<HelpCircle/>} onClick={()=>{setMenu(false);setDrawer("help")}}>{title} help</MenuButton>
    </div>:null}</div>
    <span className="sr-only" role="status" aria-live="polite">{feedback}</span>
    {drawer?<Panel title={drawer==="sources"?"Data Sources":drawer==="export"?`Export ${title}`:`${title} help`} onClose={()=>setDrawer(null)}>{drawer==="sources"?<Sources capability={capability} manageHref={connectedSystemsHref}/>:drawer==="export"?<ExportOptions capability={capability} pathname={pathname}/>:<Help capability={capability}/>}</Panel>:null}
  </>;
}

export function FinancialShellActions() { return <IntelligencePageActions capability="financial"/>; }

function MenuButton({icon,children,onClick}:{icon:React.ReactElement;children:React.ReactNode;onClick:()=>void}){return <button role="menuitem" type="button" onClick={onClick} className="flex min-h-10 w-full items-center gap-3 px-4 text-left hover:bg-stone-50"><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{children}</button>}
function Panel({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-black/20" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside role="dialog" aria-modal="true" aria-label={title} className="ml-auto flex h-full w-full max-w-md flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">{title}</h2><button aria-label="Close" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-md hover:bg-stone-100"><X className="h-4 w-4"/></button></header><div className="flex-1 overflow-y-auto p-5">{children}</div></aside></div>}
function Sources({capability,manageHref}:{capability:Capability;manageHref:string}){const sources=capability==="revenue"?[["Reservation and revenue evidence","Bookings, revenue observations, and authorized operational sources"],["Comparison evidence","Prior-period observations used by the selected comparison"]]:capability==="financial"?[["Canonical financial evidence","Financial accounts, balances, transactions, and manual or imported observations"],["Revenue evidence","Authorized revenue observations used by financial projections"]]:[["Supporting intelligence","Authorized evidence projected from Observe and other canonical lifecycle sources"],["Data quality","Coverage, freshness, confidence, and unavailable evidence affecting conclusions"]];return <><p className="mb-4 text-sm leading-6 text-stone-600">Connection health and exact provider status are resolved in Connected Systems. This view does not infer provider state.</p><ul className="divide-y rounded-xl border">{sources.map(([name,detail])=><li key={name} className="p-4"><strong className="text-sm">{name}</strong><p className="mt-1 text-xs text-stone-500">{detail}</p></li>)}</ul><ContextLink href={manageHref} className="mt-6 inline-flex min-h-10 w-full items-center justify-center rounded-md border text-sm font-semibold">Manage all data sources</ContextLink></>}
function ExportOptions({capability,pathname}:{capability:Capability;pathname:string}){const[scope,setScope]=useState<"current-view"|"full-capability">("current-view");const label=pathname.endsWith("/expenses")?"Expenses":pathname.endsWith("/cash-flow")?"Cash Flow":pathname.endsWith("/forecast")?"Forecast":pathname.endsWith("/properties")?"Properties":pathname.endsWith("/concentration")?"Concentration":"Overview";const name=capability[0]!.toUpperCase()+capability.slice(1);const href=getIntelligenceReportRequestHref(capability,label.toLowerCase(),scope);return <div className="space-y-4"><label className="flex gap-3 rounded-xl border p-4"><input checked={scope==="current-view"} onChange={()=>setScope("current-view")} type="radio" name="scope"/><span><strong className="block text-sm">Current view</strong><small className="text-stone-500">Include {label.toLowerCase()} details.</small></span></label><label className="flex gap-3 rounded-xl border p-4"><input checked={scope==="full-capability"} onChange={()=>setScope("full-capability")} type="radio" name="scope"/><span><strong className="block text-sm">Full {name} Intelligence report</strong><small className="text-stone-500">Include all available views, provenance, and data gaps.</small></span></label><label className="block text-sm font-semibold">Format<select className="ui-control mt-2 w-full" defaultValue="PDF"><option>PDF</option><option>CSV</option></select></label><ContextLink href={href} className="inline-flex min-h-11 w-full items-center justify-center rounded-md bg-emerald-800 text-sm font-semibold text-white">Continue in Reports</ContextLink><p className="text-center text-xs text-stone-500">Choose an authorized report definition. The generated artifact will be saved in Reports.</p></div>}
function Help({capability}:{capability:Capability}){if(capability==="executive")return <div className="space-y-5 text-sm leading-6 text-stone-600"><p>Executive Intelligence summarizes business health and attention requiring leadership review.</p><p>Understand explains attention before decisions and actions enter their canonical lifecycle stages.</p></div>;if(capability==="portfolio")return <div className="space-y-5 text-sm leading-6 text-stone-600"><p>Portfolio Intelligence compares performance, contribution, composition, and evidence across authorized properties.</p><p>Property drill-down preserves the selected analytical context.</p></div>;return capability==="revenue"?<div className="space-y-5 text-sm leading-6 text-stone-600"><p>Revenue Intelligence explains revenue performance, demand, pricing, and booking trends.</p><p>Generated exports are immutable reporting artifacts saved in Reports.</p></div>:<div className="space-y-5 text-sm leading-6 text-stone-600"><p><strong className="text-stone-900">Overview</strong> answers whether the business is financially healthy.</p><p><strong className="text-stone-900">Expenses</strong> explains where money is being spent.</p><p><strong className="text-stone-900">Cash Flow</strong> measures liquidity from cash evidence, never inferred profit.</p><p><strong className="text-stone-900">Forecast</strong> projects performance only when its required inputs are complete.</p></div>}
