import Link from "next/link";
import type {
  ExpenseListItem, FinancialExpenseBasis, FinancialMetricSummary, FinancialOverview, FinancialValueState,
} from "../application";
import { FinancialOverviewActions, OperatingExpensesWorkspace } from "./expense-workspace";

export function FinancialOverviewView({ overview, expenses=[], properties=[], expenseView="list" }: { overview: FinancialOverview; expenses?:readonly ExpenseListItem[];properties?:readonly{id:string;name:string}[];expenseView?:"list"|"category"|"recurring" }) {
  if (overview.state === "empty") return <FinancialOverviewEmpty />;
  const basis=(overview.accountingBasis === "cash" || overview.accountingBasis === "accrual" ? "actual" : "actual") as FinancialExpenseBasis;
  return <main className="mx-auto max-w-[1500px] space-y-4 px-4 pb-8 pt-3 sm:px-6 lg:px-8">
    <div className="sr-only"><h1>Financial Overview</h1><FinancialOverviewActions reportHref={`/dashboard/reports/new?type=financial-performance&workspace=${overview.identity.workspaceId}`}/><span>{overview.scope.label} · {range(overview.period.from,overview.period.to)}</span></div>
    {overview.permissionLimited ? <Notice title="Financial Summary">You can view authorized property profitability, but workspace cash balances and sensitive owner-level financial details may be restricted.</Notice> : null}
    <section aria-label="Financial summary" className="grid overflow-hidden rounded-xl border bg-white sm:grid-cols-2 lg:grid-cols-5">{["revenue","operating-expenses","noi","operating-margin","cash-balance"].map(id=>{const metric=overview.metrics.find(item=>item.metric===id);return <article key={id} className="min-h-32 border-b border-r p-5 last:border-r-0 sm:border-b-0"><p className="text-xs font-semibold">{metricName(id)}</p><p className="mt-3 text-2xl font-semibold">{metric?formatValue(metric.current,overview.reportingCurrency):"Unavailable"}</p><p className="mt-2 text-[10px] text-stone-500">{metric?.change?change(metric,overview.reportingCurrency):"No prior-period data"}</p></article>})}</section>
    <OperatingExpensesWorkspace initialExpenses={expenses} properties={properties} workspaceId={overview.identity.workspaceId} currency={overview.reportingCurrency} basis={basis} initialView={expenseView}/>
    {overview.attention.length?<Attention overview={overview}/>:null}
    <aside className="rounded-lg border border-blue-100 bg-blue-50 p-4 text-xs text-blue-900">ⓘ All expenses are recorded as actuals and tied to source evidence. Projections, scenarios, and budgets are kept separate.</aside>
  </main>;
}

function Attention({ overview }: { overview: FinancialOverview }) {
  return <section id="financial-attention" aria-labelledby="financial-attention-heading"><Heading id="financial-attention-heading" title="Financial attention" description="Descriptive conditions requiring inspection; these are not recommendations or decisions." />{overview.attention.length ? <ul className="mt-5 grid gap-4 md:grid-cols-2">{overview.attention.map(item => <li key={item.id} className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-semibold text-amber-950">{item.title}</h3><p className="mt-2 text-sm text-amber-900">{item.description}</p><p className="mt-2 text-xs leading-5 text-amber-800">{item.whyItMatters} · {title(item.confidence)} confidence</p>{item.destination ? <Link href={item.destination} className="mt-3 inline-flex text-sm font-semibold text-amber-950 underline">Inspect evidence</Link> : null}</li>)}</ul> : <Empty>No material financial attention conditions are established.</Empty>}</section>;
}
export function FinancialOverviewEmpty() { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="status" className="rounded-[2rem] border border-stone-200 bg-white p-8 text-center"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">Financial Intelligence</p><h1 className="mt-3 text-3xl font-semibold">Financial data unavailable</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-stone-600">Connect, import, or enter financial data to begin Financial Intelligence.</p><Link href="/dashboard/workspace/connected-systems" className="mt-6 inline-flex rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white">Review connected systems</Link></section></main>; }
export function FinancialOverviewErrorView({ code, message }: { code: string; message: string }) { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="alert" aria-live="assertive" className="rounded-[2rem] border border-rose-200 bg-white p-8"><p className="text-xs font-semibold uppercase tracking-wide text-rose-700">{title(code)} error</p><h1 className="mt-3 text-3xl font-semibold">Financial Overview could not be completed</h1><p className="mt-3 text-sm text-stone-600">{message}</p></section></main>; }
export function FinancialOverviewSkeleton() { return <main aria-label="Loading Financial Overview" aria-busy="true" className="mx-auto max-w-[1500px] animate-pulse space-y-5 px-4 py-8 motion-reduce:animate-none sm:px-6 lg:px-8"><div className="h-28 rounded-xl bg-stone-200" /><div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{Array.from({ length: 5 }, (_, i) => <div className="h-32 rounded-xl bg-stone-200" key={i} />)}</div><div className="h-[32rem] rounded-2xl bg-stone-200" /></main>; }

function Heading({ id, title: label, description }: { id: string; title: string; description: string }) { return <div><h2 id={id} className="text-2xl font-semibold tracking-tight">{label}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-600">{description}</p></div>; }
function Notice({ title: label, children }: { title: string; children: React.ReactNode }) { return <aside role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>{label}.</strong> {children}</aside>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm leading-6 text-stone-600">{children}</p>; }
function formatValue(value: FinancialValueState, currency: string) { if (value.money) return money(value.money.amount, currency); if (value.percentage !== undefined) return `${(value.percentage * 100).toFixed(1)}%`; return "Unavailable"; }
function money(value: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0, signDisplay: value < 0 ? "always" : "auto" }).format(value); }
function change(metric: FinancialMetricSummary, currency: string) { const item = metric.change; if (!item) return "Comparison unavailable"; if (item.kind === "new") return "New measurement this period"; const amount = item.amount ? money(item.amount.amount, currency) : ""; return `${amount} ${item.direction} versus comparison${item.percentageChange === undefined ? "" : ` · ${Math.abs(item.percentageChange * 100).toFixed(1)}%`}`; }
function metricName(value: string) { return ({ revenue: "Revenue", "operating-expenses": "Operating Expenses", noi: "NOI", "operating-margin": "Operating Margin", "cash-balance": "Cash Balance", "net-cash-movement": "Net Cash Movement" } as Record<string,string>)[value] ?? title(value); }
function title(value: string) { return value.replaceAll("-", " ").replace(/\b\w/g, letter => letter.toUpperCase()); }
function date(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function range(from: string, to: string) { return `${date(from)} – ${date(to)}`; }
