import Link from "next/link";
import type {
  FinancialCategorySummary, IncomeStatement, IncomeStatementLine, ProfitabilityDriver,
  ProfitabilityTrend, PropertyProfitability,
} from "../application";

export function IncomeStatementView({ statement }: { statement: IncomeStatement }) {
  if (statement.state === "empty") return <IncomeStatementEmpty />;
  return <main className="mx-auto max-w-[1500px] space-y-8 px-4 py-8 sm:px-6 lg:px-8">
    <Header statement={statement} />
    {statement.permissionLimited ? <Notice title="Profitability summary">Category and property results reflect only your authorized financial scope. Restricted revenue or expense detail is omitted, not hidden.</Notice> : null}
    {statement.state === "partial" ? <Notice title="Profitability is partially available">Revenue is available, but expense coverage is insufficient for reliable NOI and margins.</Notice> : null}
    {statement.state === "degraded" ? <Notice title="Expense synchronization is stale">Recent operating costs may be incomplete and NOI may be understated.</Notice> : null}
    <StatementSummary statement={statement} />
    <div className="grid gap-8 xl:grid-cols-2"><Revenue statement={statement} /><Expenses statement={statement} /></div>
    <Margins statement={statement} />
    <Trends statement={statement} />
    <MaterialChanges statement={statement} />
    <div className="grid gap-8 xl:grid-cols-2"><Drivers title="Revenue drivers" items={statement.drivers.revenue} /><Drivers title="Expense drivers" items={statement.drivers.expenses} /></div>
    <PropertyProfitabilitySection statement={statement} />
    <Rankings statement={statement} />
    <Dimensions statement={statement} />
    <Evidence statement={statement} />
  </main>;
}
function Header({ statement }: { statement: IncomeStatement }) {
  return <header className="rounded-[2rem] bg-[#101416] p-6 text-white sm:p-8">
    <nav aria-label="Financial Intelligence"><ol className="flex flex-wrap gap-2 text-xs font-semibold"><li><Link className="rounded-full border border-white/20 px-3 py-2 text-stone-300 hover:text-white" href="/dashboard/financial">Overview</Link></li><li><span aria-current="page" className="inline-flex rounded-full bg-white px-3 py-2 text-stone-950">Profitability</span></li><li><Link className="rounded-full border border-white/20 px-3 py-2 text-stone-300" href="/dashboard/financial/cash-flow">Cash Flow</Link></li><li><Link className="rounded-full border border-white/20 px-3 py-2 text-stone-300" href="/dashboard/financial/planning">Planning</Link></li></ol></nav>
    <p className="mt-6 text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">Understand · Financial Intelligence</p>
    <div className="mt-3 flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-3xl font-semibold sm:text-4xl">Income Statement &amp; Profitability</h1><p className="mt-3 text-lg text-stone-200">{statement.scope.label}</p><p className="mt-1 text-sm text-stone-400">{statement.scope.propertyCount} included {statement.scope.propertyCount === 1 ? "property" : "properties"} · {range(statement.period.from, statement.period.to)}</p></div><dl className="grid grid-cols-2 gap-x-8 gap-y-3 sm:grid-cols-3"><Fact label="Basis" value={`${title(statement.accountingBasis)} Basis`} /><Fact label="Currency" value={statement.reportingCurrency} /><Fact label="Comparison" value={statement.comparison?.available ? title(statement.comparison.type) : "Unavailable"} /><Fact label="Confidence" value={title(statement.confidence)} /><Fact label="Freshness" value={title(statement.freshness)} /><Fact label="Evaluated" value={dateTime(statement.evaluatedAt)} /></dl></div>
    <form aria-label="Income Statement reporting context" className="mt-7 grid gap-3 border-t border-white/10 pt-6 sm:grid-cols-2 lg:grid-cols-4"><Control label="Scope" name="scope" defaultValue={statement.scope.type === "workspace" ? "workspace" : statement.scope.type} options={[["workspace","Full Workspace"],["selected-properties","Selected Properties"],["single-property","Single Property"]]} /><Control label="Period" name="period" defaultValue="this-month" options={[["this-month","This Month"],["last-month","Last Month"],["qtd","Quarter to Date"],["ytd","Year to Date"],["12m","Trailing 12 Months"],["custom","Custom"]]} /><Control label="Comparison" name="comparison" defaultValue={statement.comparison?.type ?? "none"} options={[["previous-period","Previous Period"],["previous-year","Previous Year"],["none","No Comparison"]]} /><label className="text-xs font-semibold text-stone-300">Accounting basis<input readOnly value={`${title(statement.accountingBasis)} Basis`} className="mt-2 min-h-11 w-full rounded-xl border border-white/20 bg-white/10 px-3 text-sm text-white" /></label><button className="min-h-11 rounded-full bg-white px-5 text-sm font-semibold text-stone-950 focus-visible:ring-2 focus-visible:ring-teal-300 sm:col-span-2 sm:justify-self-start lg:col-span-4">Update profitability view</button></form>
  </header>;
}
function StatementSummary({ statement }: { statement: IncomeStatement }) {
  const values = [
    ["Revenue", statement.profitability.revenue],
    ["Total Operating Costs", statement.profitability.expenses],
    ...(statement.profitability.grossProfit ? [["Gross Profit", statement.profitability.grossProfit] as const] : []),
    ["Net Operating Income", statement.profitability.noi],
  ] as const;
  return <section aria-labelledby="statement-summary-heading"><Heading id="statement-summary-heading" title="Income Statement summary" description="Canonical recognized revenue less cost of revenue and operating expenses. Cash activity is intentionally outside this statement." /><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([label, value]) => <div key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><dt className="text-sm font-semibold text-stone-600">{label}</dt><dd className="mt-3 text-2xl font-semibold">{value?.format() ?? "Unavailable"}</dd><p className="mt-3 text-xs text-stone-500">{title(statement.confidence)} confidence · {title(statement.freshness)}</p></div>)}</dl></section>;
}
function Revenue({ statement }: { statement: IncomeStatement }) { return <Card id="revenue-decomposition" title="Revenue" description="Recognized and categorized operating revenue; gross booking value and cash receipts are not substituted."><Line item={statement.revenue.total} />{statement.revenue.categories.length ? <CategoryList items={statement.revenue.categories} /> : <Empty>{statement.permissionLimited ? "Revenue category detail is restricted for this role." : "Revenue categories are unavailable."}</Empty>}</Card>; }
function Expenses({ statement }: { statement: IncomeStatement }) { return <Card id="expense-decomposition" title="Expenses" description="Operating costs are first-class profitability drivers. Uncategorized values remain visible."><Line item={statement.expenses.total} />{statement.expenses.costOfRevenue ? <Line item={statement.expenses.costOfRevenue} /> : null}<Line item={statement.expenses.operatingExpenses} />{statement.expenses.categories.length ? <CategoryList items={statement.expenses.categories} /> : <Empty>{statement.permissionLimited ? "Expense category detail is restricted for this role." : "Expense categories are unavailable."}</Empty>}<p className="mt-4 text-xs text-stone-500">Categorization coverage: {percent(statement.expenses.categorizationCoverage)} · Uncategorized: {statement.expenses.uncategorized.format()}</p></Card>; }
function Margins({ statement }: { statement: IncomeStatement }) {
  return <section aria-labelledby="profitability-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6 sm:p-8"><Heading id="profitability-heading" title="Profitability & margins" description="Margins appear only with sufficient evidence and never without coverage, confidence, and freshness." /><dl className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Fact label="NOI" value={statement.profitability.noi?.format() ?? "Unavailable"} /><Fact label="Operating margin" value={statement.profitability.operatingMargin === null ? "Unavailable" : percent(statement.profitability.operatingMargin)} />{statement.expenses.costOfRevenue ? <><Fact label="Gross profit" value={statement.profitability.grossProfit?.format() ?? "Unavailable"} /><Fact label="Gross margin" value={statement.profitability.grossMargin === null ? "Unavailable" : percent(statement.profitability.grossMargin)} /></> : null}<Fact label="Margin health" value={title(statement.profitability.marginHealth)} /><Fact label="Evidence" value={`${statement.profitability.evidenceIds.length} references`} /></dl></section>;
}
function Trends({ statement }: { statement: IncomeStatement }) { return <section aria-labelledby="profitability-trends-heading"><Heading id="profitability-trends-heading" title="Profitability trends" description="Current results compared with a compatible previous period or previous year." /><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{statement.trends.map(item => <TrendCard key={item.metric} item={item} />)}</div></section>; }
function TrendCard({ item }: { item: ProfitabilityTrend }) { const value = item.current && typeof item.current !== "number" ? item.current.format() : typeof item.current === "number" ? percent(item.current) : "Unavailable"; return <article className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-semibold">{metric(item.metric)}</p><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-stone-600">{title(item.classification)} · {title(item.varianceDirection)} variance</p><p className="mt-3 text-xs text-stone-500">{item.percentageChange === null ? "Percentage comparison unavailable" : `${percent(Math.abs(item.percentageChange))} change`} · {title(item.confidence)} confidence</p></article>; }
function MaterialChanges({ statement }: { statement: IncomeStatement }) { return <section aria-labelledby="profitability-changes-heading"><Heading id="profitability-changes-heading" title="Material profitability changes" description="Three to five evidence-backed category movements where available; near-zero baselines do not produce misleading percentages." />{statement.materialChanges.length ? <ul className="mt-5 grid gap-4 md:grid-cols-2">{statement.materialChanges.map(item => <li key={item.id} className="rounded-2xl border border-stone-200 bg-white p-5"><Pill>{title(item.classification)}</Pill><h3 className="mt-3 font-semibold">{item.label}</h3><p className="mt-2 text-sm text-stone-600">{item.variance?.format()} versus comparison · {percent(item.contribution ?? 0)} of current {item.kind}</p></li>)}</ul> : <Empty>No material compatible profitability changes are established.</Empty>}</section>; }
function Drivers({ title: label, items }: { title: string; items: readonly ProfitabilityDriver[] }) { return <Card id={slug(label)} title={label} description="Evidence-backed contributors and category movement, not causal recommendations.">{items.length ? <ul className="divide-y divide-stone-100">{items.map(item => <li key={item.id} className="flex justify-between gap-4 py-4"><div><strong>{item.label}</strong><p className="text-xs text-stone-500">{title(item.classification)} · {title(item.confidence)} confidence</p></div><div className="text-right"><strong>{item.amount.format()}</strong><p className="text-xs text-stone-500">{item.variance ? `${item.variance.format()} change` : "Comparison unavailable"}</p></div></li>)}</ul> : <Empty>No authorized category drivers are available.</Empty>}</Card>; }
function PropertyProfitabilitySection({ statement }: { statement: IncomeStatement }) { return <section aria-labelledby="property-profitability-heading"><Heading id="property-profitability-heading" title="Property profitability" description="Each authorized property reconciles upward. Missing expenses prevent a reliable property NOI." />{statement.properties.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{statement.properties.map(property => <PropertyCard key={property.propertyId} property={property} />)}</div> : <Empty>No authorized property profitability is available.</Empty>}</section>; }
function PropertyCard({ property }: { property: PropertyProfitability }) { return <article className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-semibold">{property.label}</h3><p className="mt-1 text-xs text-stone-500">{property.market ?? "Market unclassified"} · {property.operatingModel ?? "Operating model unclassified"}</p><dl className="mt-5 grid grid-cols-2 gap-4"><Fact label="Revenue" value={property.revenue.format()} /><Fact label="Expenses" value={property.expenses?.format() ?? "Unavailable"} /><Fact label="NOI" value={property.noi?.format() ?? "Unavailable"} /><Fact label="Margin" value={property.margin === null ? "Unavailable" : percent(property.margin)} /><Fact label="NOI contribution" value={property.noiContribution === null ? "Unavailable" : percent(property.noiContribution)} /><Fact label="Trend" value={title(property.trend)} /></dl><p className="mt-4 text-xs text-stone-500">{percent(property.evidenceCoverage)} evidence coverage · {title(property.confidence)} confidence · {title(property.freshness)}</p></article>; }
function Rankings({ statement }: { statement: IncomeStatement }) { const groups = [["Highest NOI",statement.rankings.highestNoi],["Highest Margin",statement.rankings.highestMargin],["Largest Revenue",statement.rankings.largestRevenue],["Largest Expense",statement.rankings.largestExpense],["Largest Improvement",statement.rankings.largestImprovement],["Largest Decline",statement.rankings.largestDecline]] as const; return <section aria-labelledby="rankings-heading"><Heading id="rankings-heading" title="Decision-specific rankings" description="Explicit financial dimensions only; properties are never labeled best or worst." /><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{groups.map(([label, items]) => <article key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-semibold">{label}</h3>{items.length ? <ol className="mt-3 space-y-3">{items.slice(0,3).map((item,index) => <li key={item.propertyId} className="flex justify-between text-sm"><span>{index + 1}. {item.label}</span><strong>{rankingValue(label,item)}</strong></li>)}</ol> : <Empty>Insufficient evidence</Empty>}</article>)}</div></section>; }
function Dimensions({ statement }: { statement: IncomeStatement }) { return <section aria-labelledby="dimensions-heading"><Heading id="dimensions-heading" title="Market & operating-model profitability" description="Normalized property results roll up by business dimension and reconcile to the current authorized scope." /><div className="mt-5 grid gap-8 xl:grid-cols-2"><Dimension title="Markets" items={statement.dimensions.markets} /><Dimension title="Operating models" items={statement.dimensions.operatingModels} /></div></section>; }
function Dimension({ title: label, items }: { title: string; items: IncomeStatement["dimensions"]["markets"] }) { return <article className="rounded-[2rem] border border-stone-200 bg-white p-6"><h3 className="text-xl font-semibold">{label}</h3>{items.length ? <ul className="mt-4 divide-y divide-stone-100">{items.map(item => <li key={item.label} className="flex justify-between py-4"><span><strong>{item.label}</strong><span className="block text-xs text-stone-500">{item.propertyIds.length} properties · {title(item.confidence)} confidence</span></span><span className="text-right"><strong>{item.noi?.format() ?? "NOI unavailable"}</strong><span className="block text-xs text-stone-500">{item.margin === null ? "Margin unavailable" : `${percent(item.margin)} margin`}</span></span></li>)}</ul> : <Empty>No dimension data.</Empty>}</article>; }
function Evidence({ statement }: { statement: IncomeStatement }) { const values = [["Revenue coverage",statement.evidence.revenueCoverage],["Expense coverage",statement.evidence.expenseCoverage],["Property coverage",statement.evidence.propertyCoverage],["Categorization coverage",statement.evidence.categorizationCoverage]] as const; return <section id="profitability-evidence" aria-labelledby="profitability-evidence-heading" className="rounded-[2rem] border border-stone-200 bg-white p-6 sm:p-8"><Heading id="profitability-evidence-heading" title="Profitability evidence" description="Coverage, categorization, confidence, and freshness qualify every profitability conclusion." /><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_2fr]"><div><p className="text-3xl font-semibold">{title(statement.evidence.confidence)}</p><p className="text-sm text-stone-600">Profitability confidence</p><p className="mt-4 text-sm">Freshness: <strong>{title(statement.evidence.freshness)}</strong></p><p className="mt-2 text-sm">History: <strong>{statement.evidence.historyMonths} months</strong></p></div><dl className="grid grid-cols-2 gap-4">{values.map(([label,value]) => <Fact key={label} label={label} value={percent(value)} />)}</dl></div>{statement.evidence.gaps.length ? <ul className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{statement.evidence.gaps.map(gap => <li key={gap}>{gap}</li>)}</ul> : null}</section>; }

export function IncomeStatementEmpty() { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="status" className="rounded-[2rem] border border-stone-200 bg-white p-8 text-center"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">Financial Intelligence</p><h1 className="mt-3 text-3xl font-semibold">Income Statement unavailable</h1><p className="mt-4 text-sm text-stone-600">Financial data has not yet been imported.</p><Link href="/dashboard/workspace/connected-systems" className="mt-6 inline-flex rounded-full bg-stone-950 px-5 py-3 text-sm font-semibold text-white">Review connected systems</Link></section></main>; }
export function IncomeStatementErrorView({ code, message }: { code: string; message: string }) { return <main className="mx-auto max-w-3xl px-4 py-16"><section role="alert" aria-live="assertive" className="rounded-[2rem] border border-rose-200 bg-white p-8"><p className="text-xs font-semibold uppercase tracking-wide text-rose-700">{title(code)} error</p><h1 className="mt-3 text-3xl font-semibold">Income Statement could not be completed</h1><p className="mt-3 text-sm text-stone-600">{message}</p></section></main>; }
export function IncomeStatementSkeleton() { return <main aria-label="Loading Income Statement" aria-busy="true" className="mx-auto max-w-[1500px] animate-pulse space-y-7 px-4 py-8 motion-reduce:animate-none"><div className="h-72 rounded-[2rem] bg-stone-200" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:4},(_,i)=><div key={i} className="h-36 rounded-2xl bg-stone-200" />)}</div><div className="grid gap-8 xl:grid-cols-2"><div className="h-80 rounded-[2rem] bg-stone-200" /><div className="h-80 rounded-[2rem] bg-stone-200" /></div><div className="h-96 rounded-[2rem] bg-stone-200" /></main>; }
function Card({ id, title: label, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section id={id} aria-labelledby={`${id}-heading`} className="rounded-[2rem] border border-stone-200 bg-white p-6"><Heading id={`${id}-heading`} title={label} description={description} /><div className="mt-5">{children}</div></section>; }
function Heading({ id, title: label, description }: { id: string; title: string; description: string }) { return <div><h2 id={id} className="text-2xl font-semibold tracking-tight">{label}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-stone-600">{description}</p></div>; }
function Line({ item }: { item: IncomeStatementLine }) { return <dl className="flex items-center justify-between gap-4 border-b border-stone-100 py-4"><Fact label={item.label} value={item.amount?.format() ?? "Unavailable"} /><span className="text-xs text-stone-500">{title(item.qualification)} · {title(item.confidence)} confidence</span></dl>; }
function CategoryList({ items }: { items: readonly FinancialCategorySummary[] }) { return <ul className="mt-3 divide-y divide-stone-100">{items.map(item => <li key={item.id} className="flex justify-between gap-4 py-3 text-sm"><span>{item.label}<span className="block text-xs text-stone-500">{item.share === null ? "Share unavailable" : `${percent(item.share)} of total`}</span></span><strong>{item.amount?.format() ?? "Unavailable"}</strong></li>)}</ul>; }
function Control({ label, name, defaultValue, options }: { label: string; name: string; defaultValue: string; options: readonly (readonly [string,string])[] }) { return <label className="text-xs font-semibold text-stone-300">{label}<select aria-label={label} name={name} defaultValue={defaultValue} className="mt-2 min-h-11 w-full rounded-xl border border-white/20 bg-white/10 px-3 text-sm text-white focus-visible:ring-2 focus-visible:ring-teal-300">{options.map(([value,text]) => <option className="text-stone-950" value={value} key={value}>{text}</option>)}</select></label>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-[11px] font-semibold uppercase tracking-[.1em] text-stone-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
function Notice({ title: label, children }: { title: string; children: React.ReactNode }) { return <aside role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>{label}.</strong> {children}</aside>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">{children}</p>; }
function Pill({ children }: { children: React.ReactNode }) { return <span className="inline-flex rounded-full border border-stone-200 bg-stone-50 px-2.5 py-1 text-[11px] font-semibold text-stone-700">{children}</span>; }
function rankingValue(label: string, item: PropertyProfitability) { return label.includes("Margin") ? item.margin === null ? "Unavailable" : percent(item.margin) : label.includes("Revenue") ? item.revenue.format() : label.includes("Expense") ? item.expenses?.format() ?? "Unavailable" : label.includes("Improvement") || label.includes("Decline") ? item.variance?.format() ?? "Unavailable" : item.noi?.format() ?? "Unavailable"; }
function metric(value: string) { return ({ revenue:"Revenue",expenses:"Expenses",noi:"NOI","operating-margin":"Operating Margin" } as Record<string,string>)[value] ?? title(value); }
function percent(value: number) { return `${(value * 100).toFixed(1)}%`; }
function title(value: string) { return value.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g, letter => letter.toUpperCase()); }
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g,"-"); }
function date(value: string) { return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); }
function range(from: string, to: string) { return `${date(from)} – ${date(to)}`; }
function dateTime(value: string) { return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"UTC"}).format(new Date(value)); }
