"use client";
import { useActionState, useState } from "react";
import { createInvestmentReportShareAction, replaceInvestmentReportShareAction, revokeInvestmentReportShareAction, type ShareActionState } from "@/app/actions/investment-report-sharing";
import type { InvestmentReportShareGrant } from "../domain/investment-report-share";

type ShareRow = Omit<InvestmentReportShareGrant, "credentialDigest"> & Readonly<{ credentialDigest?: undefined; status: "active" | "expired" | "revoked"; accessCount: number; pdfDownloadCount: number; lastAccessedAt: string | null }>;
const initial: ShareActionState = { ok: false, message: "" };

export function InvestmentReportShareManager({ reportId, reportStatus, shares }: { reportId: string; reportStatus: "active" | "archived"; shares: readonly ShareRow[] }) {
  const [open, setOpen] = useState(false), [state, action, pending] = useActionState(createInvestmentReportShareAction, initial);
  const [initialIdempotencyKey] = useState(() => crypto.randomUUID().replaceAll("-", ""));
  const idempotencyKey = state.ok ? crypto.randomUUID().replaceAll("-", "") : initialIdempotencyKey;
  return <section className="mx-auto mt-7 max-w-6xl rounded-3xl border border-stone-200 bg-white p-6 sm:p-7" aria-labelledby="share-report-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="share-report-title" className="font-serif text-2xl">Share Report</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">Create an expiring bearer link for this {reportStatus} immutable report. Anyone with the link can view it until it expires or is revoked.</p></div><button type="button" onClick={() => setOpen(value => !value)} className="rounded-full bg-stone-950 px-5 py-2.5 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-amber-600 focus-visible:ring-offset-2">{open ? "Close" : "Create secure link"}</button></div>
    {open ? <form action={action} className="mt-6 rounded-2xl bg-stone-50 p-5"><input type="hidden" name="reportId" value={reportId} /><input type="hidden" name="idempotencyKey" value={idempotencyKey} /><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Expires after<select name="durationHours" defaultValue="168" className="mt-2 block min-h-11 w-full rounded-xl border bg-white px-3"><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select></label><label className="text-sm font-semibold">Recipient label <span className="font-normal text-stone-500">(optional, owner-visible only)</span><input name="recipientLabel" maxLength={160} className="mt-2 block min-h-11 w-full rounded-xl border bg-white px-3" /></label></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox" name="allowPdfDownload" className="h-4 w-4" /> Allow recipient to download the report PDF</label><button disabled={pending} className="mt-5 rounded-full bg-stone-950 px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-wait disabled:opacity-60">{pending ? "Creating secure link…" : "Create share link"}</button><p role="status" aria-live="polite" className={`mt-3 text-sm ${state.ok ? "text-emerald-700" : "text-rose-700"}`}>{state.message}</p>{state.ok && state.url ? <OneTimeLink url={state.url} expiresAt={state.expiresAt} /> : null}</form> : null}
    <div className="mt-7"><h3 className="font-semibold">Share history</h3>{shares.length ? <div className="mt-4 space-y-3">{shares.map(share => <ShareCard key={share.id} reportId={reportId} share={share} />)}</div> : <p className="mt-3 rounded-2xl border border-dashed p-6 text-sm text-stone-600">No share links have been created for this report.</p>}</div>
  </section>;
}
function OneTimeLink({ url, expiresAt }: { url: string; expiresAt?: string }) {
  const [copied, setCopied] = useState(false);
  return <div className="mt-5 rounded-2xl border border-amber-300 bg-amber-50 p-4"><p className="font-semibold text-amber-950">Copy this link now. It will not be displayed again.</p><p className="mt-1 text-xs text-amber-900">Expires {expiresAt ? dateTime(expiresAt) : "at the selected time"}.</p><div className="mt-3 flex gap-2"><input readOnly aria-label="New share link" value={url} className="min-w-0 flex-1 rounded-xl border bg-white px-3 text-sm" /><button type="button" onClick={async () => { await navigator.clipboard.writeText(url); setCopied(true); }} className="rounded-xl bg-stone-950 px-4 py-2 text-sm font-semibold text-white">Copy Link</button></div><p role="status" aria-live="polite" className="mt-2 text-xs">{copied ? "Link copied." : ""}</p></div>;
}
function ShareCard({ reportId, share }: { reportId: string; share: ShareRow }) {
  const [replaceState, replaceAction, replacing] = useActionState(replaceInvestmentReportShareAction, initial), active = share.status === "active";
  return <article className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-4"><div><p className="font-semibold">{share.recipientLabel ?? "Unlabeled recipient"}</p><p className="mt-1 text-xs text-stone-500">Created {dateTime(share.createdAt)} · Expires {dateTime(share.expiresAt)}</p></div><span className="h-fit rounded-full bg-stone-100 px-3 py-1 text-xs font-semibold uppercase">{share.status}</span></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><Fact label="PDF" value={share.allowPdfDownload ? "Allowed" : "Not allowed"} /><Fact label="Opened" value={`${share.accessCount} times`} /><Fact label="PDF downloads" value={String(share.pdfDownloadCount)} /><Fact label="Last opened" value={share.lastAccessedAt ? dateTime(share.lastAccessedAt) : "Never"} /></dl>{active ? <div className="mt-4 flex flex-wrap gap-3"><form action={revokeInvestmentReportShareAction} onSubmit={event => { if (!window.confirm("Revoke this link immediately? It cannot be restored.")) event.preventDefault(); }}><input type="hidden" name="shareId" value={share.id} /><input type="hidden" name="reportId" value={reportId} /><button className="rounded-full border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-800">Revoke</button></form><details><summary className="cursor-pointer rounded-full border px-4 py-2 text-sm font-semibold">Create replacement</summary><form action={replaceAction} className="mt-3 grid gap-3 rounded-xl bg-stone-50 p-4"><input type="hidden" name="shareId" value={share.id} /><input type="hidden" name="returnPath" value={`/dashboard/investments/reports/${reportId}`} /><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} /><select name="durationHours" defaultValue="168" aria-label="Replacement expiration" className="min-h-11 rounded-xl border bg-white px-3"><option value="24">24 hours</option><option value="168">7 days</option><option value="720">30 days</option></select><input name="recipientLabel" aria-label="Replacement recipient label" placeholder="Recipient label (optional)" className="min-h-11 rounded-xl border px-3" /><label className="text-sm"><input type="checkbox" name="allowPdfDownload" /> Allow PDF</label><button disabled={replacing} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-semibold text-white">{replacing ? "Replacing…" : "Revoke old link and create replacement"}</button><p role="status">{replaceState.message}</p>{replaceState.ok && replaceState.url ? <OneTimeLink url={replaceState.url} expiresAt={replaceState.expiresAt} /> : null}</form></details></div> : <p className="mt-4 text-xs text-stone-500">This grant is terminal. Create a new share if access is still needed.</p>}</article>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase text-stone-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
function dateTime(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
