import type { SharedInvestmentReportView } from "../domain/investment-report-share";
import { SharedPdfDownload } from "./shared-pdf-download";

export function SharedInvestmentReport({ view }: { view: SharedInvestmentReportView }) {
  const s = view.snapshot, f = s.financials, purchase = view.strategy === "purchase";
  return <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><header className="rounded-3xl border-t-8 border-amber-700 bg-white p-6 shadow-sm sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">{view.brand}</p><p className="mt-3 text-sm font-semibold text-stone-500">{view.label}</p><h1 className="mt-3 font-serif text-4xl text-stone-950">{s.subject.name || "Investment Report"}</h1><p className="mt-2 text-stone-600">{s.subject.address || "Unavailable"}</p><dl className="mt-7 grid gap-4 border-t pt-5 sm:grid-cols-3 lg:grid-cols-6"><Fact label="Strategy" value={label(view.strategy)} /><Fact label="Generated" value={date(view.generatedAt)} /><Fact label="Analysis" value={`Version ${view.analysisVersion}`} /><Fact label="Recommendation" value={label(view.recommendation)} /><Fact label="Confidence" value={label(view.confidence)} /><Fact label="Share expires" value={dateTime(view.expiresAt)} /></dl></header>
    <section className="mt-6 rounded-3xl bg-stone-950 p-6 text-white"><h2 className="font-serif text-2xl">Executive decision summary</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><Fact label="Recommendation" value={label(view.recommendation)} /><Fact label="Investment score" value={`${view.score}/${view.scoreMaximum}`} /><Fact label="Decision readiness" value={view.decisionReadiness} /></div><p className="mt-6 leading-7 text-stone-200">{s.decision.summary}</p><ul className="mt-4 space-y-2 text-sm text-stone-300">{s.decision.rationale.map(item => <li key={item}>• {item}</li>)}</ul></section>
    <Section title="Property and opportunity summary"><Grid><Fact label="Address" value={s.subject.address || "Unavailable"} /><Fact label="Property type" value={s.subject.propertyType ?? "Unavailable"} /><Fact label="Market" value={s.subject.market ?? "Unavailable"} /><Fact label="Bedrooms" value={value(s.subject.bedrooms)} /><Fact label="Bathrooms" value={value(s.subject.bathrooms)} /><Fact label="Strategy" value={label(view.strategy)} /></Grid></Section>
    <Section title="Revenue outlook"><Grid><Fact label="Average daily rate" value={money(f.projectedAdr)} /><Fact label="Occupancy" value={percent(f.projectedOccupancy?.value)} /><Fact label="Annual gross revenue" value={money(f.projectedAnnualRevenue)} /></Grid></Section>
    <Section title="Operating expense outlook"><Grid><Fact label="Annual operating expenses" value={money(f.operatingExpenses)} /><Fact label="Net operating income" value={money(f.netOperatingIncome)} /></Grid></Section>
    <Section title={purchase ? "Purchase financial performance" : "Rental-arbitrage financial performance"}><Grid>{purchase ? <><Fact label="Purchase price" value={money(f.purchasePrice)} /><Fact label="Cap rate" value={percent(f.capRate?.value)} /><Fact label="Cash-on-cash return" value={percent(f.cashOnCashReturn?.value)} /></> : <><Fact label="Monthly rent" value={money(f.proposedMonthlyLease)} /><Fact label="ROI on invested capital" value={percent(f.cashOnCashReturn?.value)} /></>}<Fact label="Initial cash invested" value={money(f.initialCashRequired)} /><Fact label="Annual cash flow" value={money(f.annualCashFlow)} /></Grid></Section>
    <Section title="Evidence and provenance"><div className="grid gap-4 sm:grid-cols-2">{s.evidence.length ? s.evidence.map(item => <article key={item.id} className="rounded-xl bg-stone-50 p-4"><p className="font-semibold">{item.title}</p><p className="mt-2 text-sm text-stone-600">{item.source} · {label(item.confidence)} confidence</p><p className="mt-1 text-xs text-stone-500">{item.providerTimestamp ? date(item.providerTimestamp) : "Observation date unavailable"}</p></article>) : <p>No external evidence was available in the saved report.</p>}</div></Section>
    <Section title="Risks and limitations"><ul className="space-y-3 text-sm">{s.risks.map(item => <li key={item.id}><strong>{item.title}:</strong> {item.description}</li>)}{s.limitations.map(item => <li key={item.code} className="text-amber-900"><strong>Limitation:</strong> {item.description}</li>)}</ul></Section>
    <Section title="Assumption ledger"><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b"><th className="py-3">Assumption</th><th>Value</th><th>Unit</th><th>Source</th><th>Observed</th></tr></thead><tbody>{s.assumptions.map((item, index) => <tr key={`${item.label}-${index}`} className="border-b"><th className="py-3 font-medium">{label(item.label)}</th><td>{value(item.value)}</td><td>{item.unit ? label(item.unit) : "Not provided"}</td><td>{label(item.sourceType)}</td><td>{item.observedAt ? date(item.observedAt) : "Not provided"}</td></tr>)}</tbody></table></div></Section>
    <Section title="Methodology and disclaimer"><p className="text-sm leading-6 text-stone-600">This report reflects the saved investment analysis at a specific point in time. Results depend on the listed assumptions and available evidence, and projections are not guarantees. Independently verify material financial, legal, tax, insurance, zoning, and regulatory considerations.</p></Section>
    <footer className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t pt-6"><p className="text-xs text-stone-500">Confidential shared report · Access expires {dateTime(view.expiresAt)}</p>{view.allowPdfDownload ? <SharedPdfDownload /> : <p className="text-xs text-stone-500">PDF download is not enabled for this share.</p>}</footer>
  </main>;
}
export function SharedReportUnavailable() { return <main className="flex min-h-screen items-center justify-center px-4"><section className="max-w-lg rounded-3xl border bg-white p-8 text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Luxe Haven Collective</p><h1 className="mt-4 font-serif text-3xl">Shared report unavailable</h1><p className="mt-4 text-sm leading-6 text-stone-600">This shared report is unavailable. The link may be invalid, expired, or revoked.</p></section></main>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-6 rounded-3xl border bg-white p-6"><h2 className="font-serif text-2xl">{title}</h2><div className="mt-5">{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{children}</dl>; }
function Fact({ label: name, value: content }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide opacity-65">{name}</dt><dd className="mt-2 font-semibold">{content}</dd></div>; }
function label(input: string) { return input.replaceAll("-", " ").replace(/\b\w/g, c => c.toUpperCase()); }
function value(input: unknown) { return input === null || input === undefined || input === "" ? "Unavailable" : typeof input === "boolean" ? input ? "Yes" : "No" : String(input); }
function money(input?: { amount: number; currency: string }) { return input ? new Intl.NumberFormat("en-US", { style: "currency", currency: input.currency, maximumFractionDigits: 0 }).format(input.amount) : "Unavailable"; }
function percent(input?: number) { return input === undefined ? "Unavailable" : `${(Math.abs(input) <= 1 ? input * 100 : input).toFixed(1)}%`; }
function date(input: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(input)); }
function dateTime(input: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(input)); }
