import { createHash, timingSafeEqual } from "node:crypto";
import { decodeProtectedHeader, importJWK, jwtVerify, type JWK } from "jose";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptFinancialToken, plaidClient } from "./plaid-client";

type WebhookEnvelope=Readonly<{webhook_type?:unknown;webhook_code?:unknown;item_id?:unknown;error?:{error_code?:unknown};new_transactions?:unknown}>;
export async function verifyPlaidWebhook(raw:string,signature:string|null){
  if(!signature)throw new Error("WEBHOOK_SIGNATURE_MISSING");
  const header=decodeProtectedHeader(signature);if(header.alg!=="ES256"||typeof header.kid!=="string")throw new Error("WEBHOOK_SIGNATURE_INVALID");
  const response=await plaidClient().webhookVerificationKeyGet({key_id:header.kid}),key=response.data.key;
  const verified=await jwtVerify(signature,await importJWK(key as JWK,"ES256"),{algorithms:["ES256"],maxTokenAge:"5 min"});
  const claimed=verified.payload.request_body_sha256;if(typeof claimed!=="string")throw new Error("WEBHOOK_BODY_HASH_MISSING");
  const actual=createHash("sha256").update(raw).digest("hex"),left=Buffer.from(actual),right=Buffer.from(claimed);
  if(left.length!==right.length||!timingSafeEqual(left,right))throw new Error("WEBHOOK_BODY_HASH_INVALID");
  return {bodyHash:actual,issuedAt:verified.payload.iat};
}
export async function processPlaidWebhook(raw:string,signature:string|null){
  const verified=await verifyPlaidWebhook(raw,signature);let body:WebhookEnvelope;try{body=JSON.parse(raw) as WebhookEnvelope;}catch{throw new Error("WEBHOOK_BODY_INVALID");}
  const type=text(body.webhook_type),code=text(body.webhook_code),itemId=text(body.item_id);if(!type||!code)throw new Error("WEBHOOK_CONTEXT_INVALID");
  const deliveryKey=createHash("sha256").update(`${type}:${code}:${itemId}:${verified.bodyHash}`).digest("hex"),admin=createAdminClient();
  const {data:existing}=await admin.from("financial_provider_webhook_receipts").select("id,status,attempts").eq("provider","plaid").eq("delivery_key",deliveryKey).maybeSingle();
  if(existing?.status==="processed"||existing?.status==="ignored")return{accepted:true,duplicate:true};
  const {data:connection}=itemId?await admin.from("financial_provider_connections").select("id,workspace_id,status").eq("provider","plaid").eq("provider_item_ref",itemId).maybeSingle():{data:null};
  const receipt={provider:"plaid",delivery_key:deliveryKey,body_sha256:verified.bodyHash,provider_item_ref:itemId||null,connection_id:connection?.id??null,webhook_type:type,webhook_code:code,status:"processing",safe_metadata:{issuedAt:verified.issuedAt??null,newTransactions:Number(body.new_transactions)||0}};
  if(existing)await admin.from("financial_provider_webhook_receipts").update({...receipt,attempts:Number(existing.attempts)+1,last_error_code:null}).eq("id",existing.id);else{const{error}=await admin.from("financial_provider_webhook_receipts").insert(receipt);if(error?.code==="23505")return{accepted:true,duplicate:true};if(error)throw error;}
  if(!connection){await finish(deliveryKey,"ignored");return{accepted:true,ignored:true};}
  try{let outcome="ignored";
    if(type==="TRANSACTIONS"&&["SYNC_UPDATES_AVAILABLE","DEFAULT_UPDATE","INITIAL_UPDATE","HISTORICAL_UPDATE"].includes(code)){await syncPlaidConnection(String(connection.id));outcome="transactions-synchronized";}
    else if(type==="ITEM"&&(code==="PENDING_DISCONNECT"||code==="PENDING_EXPIRATION"||(code==="ERROR"&&text(body.error?.error_code)==="ITEM_LOGIN_REQUIRED"))){await setRecoveryState(String(connection.id),"reauth_required",code);outcome="reauth-required";}
    else if(type==="ITEM"&&code==="LOGIN_REPAIRED"){await setRecoveryState(String(connection.id),"provider_degraded",null);await syncPlaidConnection(String(connection.id));outcome="login-repaired";}
    else if(type==="ITEM"&&code==="USER_PERMISSION_REVOKED"){await markDisconnected(String(connection.id),"provider-revoked");outcome="provider-revoked";}
    await audit(String(connection.workspace_id),String(connection.id),`webhook-${outcome}`,deliveryKey,{webhookType:type,webhookCode:code});await finish(deliveryKey,outcome==="ignored"?"ignored":"processed");return{accepted:true,duplicate:false};
  }catch(error){const errorCode=safeError(error);await setRecoveryState(String(connection.id),errorCode==="ITEM_LOGIN_REQUIRED"?"reauth_required":"provider_degraded",errorCode);await admin.from("financial_provider_webhook_receipts").update({status:"failed",last_error_code:errorCode}).eq("provider","plaid").eq("delivery_key",deliveryKey);throw new Error("WEBHOOK_PROCESSING_FAILED");}
}
export async function syncPlaidConnection(connectionId:string){
  const admin=createAdminClient(),now=new Date().toISOString(),{data:connection,error}=await admin.from("financial_provider_connections").select("workspace_id,encrypted_access_token,transaction_cursor,status,sync_started_at,created_by_profile_id").eq("id",connectionId).single();if(error||!connection||["disconnected","failed","reauth_required"].includes(connection.status))throw error??new Error("SYNC_DISABLED");
  if(connection.status==="syncing"&&connection.sync_started_at&&Date.now()-new Date(connection.sync_started_at).getTime()<300_000)return 0;
  const {data:lease,error:leaseError}=await admin.from("financial_provider_connections").update({status:"syncing",sync_started_at:now,updated_at:now}).eq("id",connectionId).neq("status","disconnected").select("id").maybeSingle();if(leaseError||!lease)throw leaseError??new Error("SYNC_DISABLED");
  const {data:accounts,error:accountError}=await admin.from("financial_provider_accounts").select("provider_account_ref,canonical_account_id").eq("connection_id",connectionId).eq("selected",true).not("canonical_account_id","is",null);if(accountError||!accounts?.length)throw accountError??new Error("NO_SELECTED_ACCOUNTS");
  const canonical=new Map(accounts.map(a=>[String(a.provider_account_ref),String(a.canonical_account_id)])),access_token=decryptFinancialToken(connection.encrypted_access_token);let cursor=connection.transaction_cursor??undefined,hasMore=true,total=0;
  while(hasMore){const response=await plaidClient().transactionsSync({access_token,...(cursor?{cursor}:{}),count:500});for(const transaction of [...response.data.added,...response.data.modified]){const accountId=canonical.get(transaction.account_id);if(!accountId)continue;const {error:txError}=await admin.from("financial_transactions").upsert({workspace_id:connection.workspace_id,account_id:accountId,property_id:null,amount_minor:Math.round(Math.abs(transaction.amount)*100),currency:transaction.iso_currency_code??transaction.unofficial_currency_code??"USD",measurement:"actual",effective_date:transaction.date,frequency:"one-time",posting_date:transaction.authorized_date??transaction.date,status:transaction.pending?"pending":"posted",source_provider:"plaid",source_external_id:transaction.transaction_id,evidence_ids:[`bank-transaction:${transaction.transaction_id}`],idempotency_key:`plaid:${connectionId}:transaction:${transaction.transaction_id}`,created_by_profile_id:connection.created_by_profile_id,direction:transaction.amount>=0?"outflow":"inflow",description:transaction.merchant_name??transaction.name,import_category:transaction.personal_finance_category?.primary??null},{onConflict:"workspace_id,idempotency_key"});if(txError)throw txError;total++;}for(const removed of response.data.removed)await admin.from("financial_transactions").update({status:"voided"}).eq("workspace_id",connection.workspace_id).eq("source_provider","plaid").eq("source_external_id",removed.transaction_id);cursor=response.data.next_cursor;hasMore=response.data.has_more;}
  await admin.from("financial_provider_connections").update({status:"healthy",transaction_cursor:cursor,last_transactions_at:new Date().toISOString(),last_error_code:null,sync_started_at:null,updated_at:new Date().toISOString()}).eq("id",connectionId);await admin.from("financial_accounts").update({status:"active",active:true}).eq("provider_connection_id",connectionId).neq("status","disconnected");return total;
}
export async function markDisconnected(connectionId:string,reason:string){const admin=createAdminClient(),now=new Date().toISOString(),{data:connection}=await admin.from("financial_provider_connections").update({status:"disconnected",disconnected_at:now,sync_started_at:null,last_error_code:reason,updated_at:now}).eq("id",connectionId).select("workspace_id").single();await admin.from("financial_accounts").update({status:"disconnected"}).eq("provider_connection_id",connectionId);if(connection)await audit(String(connection.workspace_id),connectionId,"connection-disconnected",crypto.randomUUID(),{reason});}
export async function setRecoveryState(connectionId:string,status:"healthy"|"syncing"|"reauth_required"|"provider_degraded"|"disconnected"|"failed",errorCode:string|null){const admin=createAdminClient();await admin.from("financial_provider_connections").update({status,last_error_code:errorCode,updated_at:new Date().toISOString()}).eq("id",connectionId);if(status==="disconnected")await admin.from("financial_accounts").update({status:"disconnected"}).eq("provider_connection_id",connectionId);else if(status==="reauth_required"||status==="provider_degraded"||status==="failed")await admin.from("financial_accounts").update({status:"inactive",active:true}).eq("provider_connection_id",connectionId).neq("status","disconnected");else if(status==="healthy")await admin.from("financial_accounts").update({status:"active",active:true}).eq("provider_connection_id",connectionId).neq("status","disconnected");}
export async function audit(workspaceId:string,connectionId:string,eventType:string,correlationId:string,safeMetadata:Record<string,unknown>,actorProfileId?:string){await createAdminClient().from("financial_provider_audit_events").insert({workspace_id:workspaceId,connection_id:connectionId,event_type:eventType,correlation_id:correlationId,safe_metadata:safeMetadata,actor_profile_id:actorProfileId??null});}
async function finish(deliveryKey:string,status:"processed"|"ignored"){await createAdminClient().from("financial_provider_webhook_receipts").update({status,processed_at:new Date().toISOString(),last_error_code:null}).eq("provider","plaid").eq("delivery_key",deliveryKey);}
function text(value:unknown){return typeof value==="string"?value:"";}function safeError(error:unknown){const candidate=error as {response?:{data?:{error_code?:unknown}},message?:unknown};return text(candidate?.response?.data?.error_code)||text(candidate?.message).slice(0,80)||"PROVIDER_UNAVAILABLE";}
