import { describe, expect, it, vi } from "vitest";
import { ProviderType } from "../domain/enums/provider-type";
import type { AcquireMarketComparablesCommand } from "../domain/comparable-acquisition";
import type { MarketProperty } from "../domain/property-resolution";
import type { MarketComparableProvider, MarketComparableProviderCandidate } from "./providers/market-comparable-provider";
import { ProviderError, ProviderErrorCode } from "./providers/provider-error";
import { providerFailure, providerSuccess } from "./providers/provider-result";
import { acquireMarketComparables } from "./acquire-market-comparables";

const now = new Date("2026-07-21T12:00:00.000Z");
const subject: MarketProperty = { id: "subject-1", providerReferences: [{ provider: ProviderType.RentCast, externalId: "subject-external" }], address: { formatted: "123 Main St, Mesa, AZ 85201", addressLine1: "123 Main St", city: "Mesa", state: "AZ", postalCode: "85201" }, characteristics: { propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1800 }, financialFacts: {}, coordinates: { latitude: 33.4, longitude: -111.8 } };
const baseCandidate: MarketComparableProviderCandidate = { externalId: "comp-1", address: { formatted: "125 Main St, Mesa, AZ 85201", addressLine1: "125 Main St", city: "Mesa", state: "AZ", postalCode: "85201" }, propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1750, latitude: 33.401, longitude: -111.8, distanceMiles: 0.2, price: 425000, listedAt: new Date("2026-06-01"), listingStatus: "active", sourceRank: 1 };

function command(purpose: AcquireMarketComparablesCommand["purpose"] = "sale-valuation"): AcquireMarketComparablesCommand { return { subject, purpose, context: { acquisitionId: "acquisition-1", requestedAt: now, requestedBy: "operator" } }; }
function provider(candidates: readonly MarketComparableProviderCandidate[]): MarketComparableProvider { return { acquireComparables: vi.fn(async (request) => providerSuccess({ provider: ProviderType.RentCast, purpose: request.purpose, candidates, retrievedAt: now })) }; }

describe("acquireMarketComparables", () => {
  it("acquires factual sale candidates without qualification fields", async () => { const result = await acquireMarketComparables(command(), { provider: provider([baseCandidate]) }); expect(result.status).toBe("acquired"); expect(result.candidates[0]).toMatchObject({ id: "rentcast:comp-1:sale-valuation", purpose: "sale-valuation", listing: { price: 425000 } }); expect(result.candidates[0]).not.toHaveProperty("similarity"); expect(result.candidates[0]).not.toHaveProperty("weight"); });
  it("acquires long-term rent without manufacturing STR metrics", async () => { const result = await acquireMarketComparables(command("long-term-rent"), { provider: provider([{ ...baseCandidate, price: 2450 }]) }); expect(result.candidates[0]?.rental?.monthlyRent).toBe(2450); expect(result.candidates[0]).not.toHaveProperty("averageDailyRate"); expect(result.candidates[0]).not.toHaveProperty("occupancy"); });
  it("returns unsupported without calling the provider for STR performance", async () => { const dependency = provider([]); const result = await acquireMarketComparables(command("short-term-rental-performance"), { provider: dependency }); expect(result.status).toBe("unsupported"); expect(dependency.acquireComparables).not.toHaveBeenCalled(); });
  it("represents a successful empty response", async () => expect((await acquireMarketComparables(command(), { provider: provider([]) })).status).toBe("empty"));
  it("propagates provider failures", async () => { const error = new ProviderError({ provider: ProviderType.RentCast, code: ProviderErrorCode.RateLimited, message: "limited" }); const dependency: MarketComparableProvider = { acquireComparables: async () => providerFailure(error) }; await expect(acquireMarketComparables(command(), { provider: dependency })).rejects.toBe(error); });
  it("excludes the subject by provider identity", async () => { const result = await acquireMarketComparables(command(), { provider: provider([{ ...baseCandidate, externalId: "subject-external" }]) }); expect(result.status).toBe("empty"); expect(result.excludedSubjectCandidateIds).toEqual(["rentcast:subject-external:sale-valuation"]); });
  it("excludes the subject by exact normalized address", async () => { const result = await acquireMarketComparables(command(), { provider: provider([{ ...baseCandidate, externalId: "other-id", address: { ...subject.address, addressLine1: "123 Main Street" } }]) }); expect(result.candidates).toHaveLength(0); });
  it("does not exclude a nearby different property", async () => expect((await acquireMarketComparables(command(), { provider: provider([baseCandidate]) })).candidates).toHaveLength(1));
  it("deduplicates repeated external IDs deterministically", async () => { const duplicate = { ...baseCandidate, sourceRank: 2 }; const first = await acquireMarketComparables(command(), { provider: provider([duplicate, baseCandidate]) }); const second = await acquireMarketComparables(command(), { provider: provider([baseCandidate, duplicate]) }); expect(first).toEqual(second); expect(first.candidates).toHaveLength(1); expect(first.candidates[0]?.provenance).toHaveLength(2); });
  it("records conflicting duplicate prices", async () => { const result = await acquireMarketComparables(command(), { provider: provider([baseCandidate, { ...baseCandidate, price: 500000, sourceRank: 2 }]) }); expect(result.candidates[0]?.dataGaps.map((item) => item.code)).toContain("COMPARABLE_CONFLICTING_PROVIDER_RECORD"); });
  it("creates candidate gaps and a deterministic rollup", async () => { const partial = { externalId: "partial", address: baseCandidate.address, sourceRank: 1 }; const result = await acquireMarketComparables(command("long-term-rent"), { provider: provider([partial]) }); expect(result.candidates[0]?.dataGaps.map((item) => item.code)).toEqual(["COMPARABLE_BATHROOM_COUNT_MISSING", "COMPARABLE_BEDROOM_COUNT_MISSING", "COMPARABLE_COORDINATES_MISSING", "COMPARABLE_LISTING_STATUS_MISSING", "COMPARABLE_PROPERTY_TYPE_MISSING", "COMPARABLE_RENT_MISSING", "COMPARABLE_SQUARE_FOOTAGE_MISSING"]); expect(result.dataGaps).toEqual(result.candidates[0]?.dataGaps); });
  it("orders by distance rather than source rank or provider order", async () => { const far = { ...baseCandidate, externalId: "far", distanceMiles: 3, sourceRank: 1 }; const near = { ...baseCandidate, externalId: "near", distanceMiles: 0.1, sourceRank: 9 }; const result = await acquireMarketComparables(command(), { provider: provider([far, near]) }); expect(result.candidates.map((item) => item.providerReferences[0]?.externalId)).toEqual(["near", "far"]); });
  it("preserves search and provider lineage", async () => { const result = await acquireMarketComparables({ ...command(), criteria: { radiusMiles: 2, limit: 5 } }, { provider: provider([baseCandidate]) }); expect(result.criteria).toMatchObject({ radiusMiles: 2, limit: 5 }); expect(result.provenance[0]).toMatchObject({ provider: ProviderType.RentCast, externalId: "comp-1", dataset: "sale-avm-comparables" }); });
  it("is deeply frozen and does not mutate command or provider candidates", async () => { const input = command(); const source = structuredClone(baseCandidate); const before = structuredClone(input); const result = await acquireMarketComparables(input, { provider: provider([baseCandidate]) }); expect(input).toEqual(before); expect(baseCandidate).toEqual(source); expect(Object.isFrozen(result)).toBe(true); expect(Object.isFrozen(result.candidates[0]?.address)).toBe(true); });
  it("validates acquisition identity", async () => await expect(acquireMarketComparables({ ...command(), context: { acquisitionId: " ", requestedAt: now } }, { provider: provider([]) })).rejects.toThrow("acquisition id"));
});
