import { describe, expect, it } from "vitest";
import { ProviderType } from "../domain/enums/provider-type";
import type { MarketComparableAcquisitionResult, MarketComparableCandidate, MarketComparablePurpose } from "../domain/comparable-acquisition";
import type { MarketProperty } from "../domain/property-resolution";
import { buildDefaultMarketComparableQualificationPolicy } from "./market-comparable-qualification-policy";
import { qualifyMarketComparables } from "./qualify-market-comparables";

const evaluatedAt = new Date("2026-07-21T00:00:00.000Z");
const subject: MarketProperty = { id: "subject", providerReferences: [{ provider: ProviderType.RentCast, externalId: "subject" }], address: { formatted: "1 Main St", addressLine1: "1 Main St", city: "Mesa", state: "AZ", postalCode: "85201" }, characteristics: { propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1650, yearBuilt: 2000 }, financialFacts: {} };
function candidate(id: string, overrides: Partial<MarketComparableCandidate> = {}): MarketComparableCandidate { return { id, purpose: "sale-valuation", providerReferences: [{ provider: ProviderType.RentCast, externalId: id }], address: { formatted: `${id} Main St` }, propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1650, yearBuilt: 2000, distanceMiles: 0.5, listing: { price: 400000, status: "sold", listedAt: new Date("2026-06-01") }, dataGaps: [], provenance: [], ...overrides }; }
function acquisition(candidates: readonly MarketComparableCandidate[], purpose: MarketComparablePurpose = "sale-valuation"): MarketComparableAcquisitionResult { return { acquisitionId: "acquisition", subjectId: "subject", purpose, criteria: { radiusMiles: 5, limit: 15, propertyTypes: ["Single Family"], occurredAfter: new Date("2025-07-21"), listingStatuses: ["sold"] }, status: candidates.length ? "acquired" : "empty", candidates, excludedSubjectCandidateIds: [], dataGaps: [], provenance: [], requestedAt: evaluatedAt, completedAt: evaluatedAt }; }
function run(candidates: readonly MarketComparableCandidate[], purpose: "sale-valuation" | "long-term-rent" = "sale-valuation") { return qualifyMarketComparables({ subject, acquisition: acquisition(candidates, purpose), policy: buildDefaultMarketComparableQualificationPolicy(purpose, ["Single Family"]), context: { qualificationId: "qualification", evaluatedAt } }); }

describe("qualifyMarketComparables", () => {
  it("qualifies a complete sale set with normalized weights", () => { const result = run([candidate("a", { distanceMiles: 0.2 }), candidate("b", { distanceMiles: 1, listing: { price: 410000, status: "sold", listedAt: new Date("2026-04-01") } }), candidate("c", { distanceMiles: 2, listing: { price: 390000, status: "sold", listedAt: new Date("2026-02-01") } })]); expect(result.included).toHaveLength(3); expect(result.summary.totalNormalizedWeight).toBe(1); expect(result.included[0]?.candidate.id).toBe("a"); expect(result.summary.sufficiency).toBe("limited"); });
  it("qualifies rental candidates using rental facts", () => { const rental = (id: string, rent: number) => candidate(id, { purpose: "long-term-rent", listing: undefined, rental: { monthlyRent: rent, status: "active", listedAt: new Date("2026-06-01") } }); const result = run([rental("a", 2400), rental("b", 2450), rental("c", 2500)], "long-term-rent"); expect(result.included).toHaveLength(3); expect(result.purpose).toBe("long-term-rent"); });
  it("separates included, excluded, and unresolved", () => { const result = run([candidate("good"), candidate("far", { distanceMiles: 10 }), candidate("unknown", { squareFeet: undefined, dataGaps: [{ code: "COMPARABLE_SQUARE_FOOTAGE_MISSING", description: "missing", severity: "material" }] })]); expect(result.included.map((item) => item.candidate.id)).toEqual(["good"]); expect(result.excluded.map((item) => item.candidate.id)).toEqual(["far"]); expect(result.unresolved.map((item) => item.candidate.id)).toEqual(["unknown"]); });
  it("excludes hard outliers after similarity", () => { const result = run([candidate("a", { listing: { price: 390000, status: "sold" } }), candidate("b", { listing: { price: 400000, status: "sold" } }), candidate("x", { listing: { price: 1200000, status: "sold" } })]); expect(result.excluded.find((item) => item.candidate.id === "x")).toMatchObject({ stage: "outlier" }); expect(result.included).toHaveLength(2); });
  it.each([[0, "insufficient"], [2, "insufficient"], [3, "limited"], [5, "sufficient"]] as const)("classifies %s included as %s", (count, sufficiency) => { const result = run(Array.from({ length: count }, (_, index) => candidate(String(index), { listing: { price: 400000 + index * 1000, status: "sold" } }))); expect(result.summary.sufficiency).toBe(sufficiency); });
  it("rejects subject mismatch", () => expect(() => qualifyMarketComparables({ subject, acquisition: { ...acquisition([]), subjectId: "other" }, policy: buildDefaultMarketComparableQualificationPolicy("sale-valuation"), context: { qualificationId: "q", evaluatedAt } })).toThrow("SUBJECT_MISMATCH"));
  it("rejects purpose mismatch", () => expect(() => qualifyMarketComparables({ subject, acquisition: acquisition([], "long-term-rent"), policy: buildDefaultMarketComparableQualificationPolicy("sale-valuation"), context: { qualificationId: "q", evaluatedAt } })).toThrow("PURPOSE_MISMATCH"));
  it("rejects unsupported STR acquisition", () => expect(() => qualifyMarketComparables({ subject, acquisition: acquisition([], "short-term-rental-performance"), policy: buildDefaultMarketComparableQualificationPolicy("sale-valuation"), context: { qualificationId: "q", evaluatedAt } })).toThrow("PURPOSE_MISMATCH"));
  it("rejects duplicate candidate identities", () => expect(() => run([candidate("a"), candidate("a")])).toThrow("DUPLICATE_CANDIDATE"));
  it("preserves policy and acquisition lineage", () => { const result = run([candidate("a")]); expect(result.policySnapshot.purpose).toBe("sale-valuation"); expect(result.lineage).toEqual({ subjectId: "subject", acquisitionId: "acquisition", candidateIds: ["a"] }); });
  it("rolls up data gaps", () => { const gap = { code: "COMPARABLE_PROVIDER_TIMESTAMP_MISSING", description: "missing", severity: "informational" } as const; expect(run([candidate("a", { dataGaps: [gap] })]).dataGaps).toEqual([gap]); });
  it("is deterministic across candidate input order", () => { const a = candidate("a", { distanceMiles: 1 }); const b = candidate("b", { distanceMiles: 2 }); expect(run([b, a])).toEqual(run([a, b])); });
  it("does not let provider source rank control influence", () => { const first = run([candidate("a", { sourceRank: 99 }), candidate("b", { sourceRank: 1 })]); const second = run([candidate("a", { sourceRank: 1 }), candidate("b", { sourceRank: 99 })]); expect(first.included.map((item) => [item.candidate.id, item.normalizedWeight])).toEqual(second.included.map((item) => [item.candidate.id, item.normalizedWeight])); });
  it("deeply freezes output without mutating or freezing acquisition", () => { const source = acquisition([candidate("a")]); const before = structuredClone(source); const result = qualifyMarketComparables({ subject, acquisition: source, policy: buildDefaultMarketComparableQualificationPolicy("sale-valuation"), context: { qualificationId: "q", evaluatedAt } }); expect(source).toEqual(before); expect(Object.isFrozen(source.candidates[0])).toBe(false); expect(Object.isFrozen(result)).toBe(true); expect(Object.isFrozen(result.included)).toBe(true); expect(Object.isFrozen(result.included[0]?.candidate)).toBe(true); });
});
