import type { MarketComparableProvider } from "./providers/market-comparable-provider";
import type { MarketAnalysisConfidence, MarketAnalysisDataGap, MarketAnalysisEvidence, MarketAnalysisObservation, MarketAnalysisReportStatus, MarketLongTermRentAnalysis, MarketRisk, MarketSaleValuationAnalysis, CanonicalMarketAnalysisReport, RunMarketAnalysisCommand } from "../domain/canonical-market-analysis-report";
import type { MarketProperty } from "../domain/property-resolution";
import { acquireMarketComparables } from "./acquire-market-comparables";
import { qualifyMarketComparables } from "./qualify-market-comparables";
import { buildMarketEstimateCore } from "./build-market-estimate-analysis";

export interface RunMarketAnalysisDependencies { readonly comparableProvider: MarketComparableProvider }

export async function runMarketAnalysis(command: RunMarketAnalysisCommand, dependencies: RunMarketAnalysisDependencies): Promise<CanonicalMarketAnalysisReport> {
  validateCommand(command);
  if (command.propertyResolution.status !== "resolved") throw new Error("MARKET_ANALYSIS_PROPERTY_NOT_RESOLVED");
  const subject = structuredClone(command.propertyResolution.property);
  const analyzedAt = new Date(command.context.analyzedAt.getTime());
  const sale = command.analyses.saleValuation?.enabled ? await buildSection("sale-valuation", subject, command, dependencies) : undefined;
  const rent = command.analyses.longTermRent?.enabled ? await buildSection("long-term-rent", subject, command, dependencies) : undefined;
  const propertyGaps = command.propertyResolution.dataGaps.map((gap) => analysisGap(`property-resolution:${gap.code}`, gap.code, gap.description, gap.severity, "property-resolution", "subject"));
  const sectionGaps = [...(sale?.dataGaps ?? []), ...(rent?.dataGaps ?? [])];
  const dataGaps = uniqueBy([...propertyGaps, ...sectionGaps], (gap) => gap.id).sort((a, b) => a.id.localeCompare(b.id));
  const risks = deriveRisks(subject, sale, rent, dataGaps);
  const observations = buildObservations(command.context.analysisId, subject, sale, rent);
  const evidence = buildEvidence(command.context.analysisId, sale, rent);
  const confidence = reportConfidence([sale?.confidence, rent?.confidence].filter((item): item is MarketAnalysisConfidence => item !== undefined));
  const status = reportStatus(sale, rent, Boolean(command.analyses.saleValuation?.enabled || command.analyses.longTermRent?.enabled));
  const summary = {
    ...(sale?.estimatedValue !== undefined ? { estimatedValue: sale.estimatedValue } : {}), ...(rent?.estimatedMonthlyRent !== undefined ? { estimatedMonthlyRent: rent.estimatedMonthlyRent } : {}),
    confidenceScore: confidence.score, confidenceLevel: confidence.level, saleComparableCount: sale?.qualification.included.length ?? 0, rentalComparableCount: rent?.qualification.included.length ?? 0,
    riskCount: risks.length, dataGapCount: dataGaps.length, headline: headline(status, sale, rent), explanation: explanation(sale, rent),
  };
  const lineage = {
    propertyResolutionId: command.propertyResolution.resolutionId,
    ...(sale ? { sale: sectionLineage(sale) } : {}), ...(rent ? { longTermRent: sectionLineage(rent) } : {}),
    observationIds: observations.map((item) => item.id), evidenceIds: evidence.map((item) => item.id), policyVersion: command.policies.version,
  };
  return deepFreeze({ analysisId: command.context.analysisId, subject, status, ...(sale ? { saleValuation: sale } : {}), ...(rent ? { longTermRent: rent } : {}), confidence, risks, dataGaps, observations, evidence, summary, lineage, analyzedAt });
}

function buildSection(purpose: "sale-valuation", subject: MarketProperty, command: RunMarketAnalysisCommand, dependencies: RunMarketAnalysisDependencies): Promise<MarketSaleValuationAnalysis>;
function buildSection(purpose: "long-term-rent", subject: MarketProperty, command: RunMarketAnalysisCommand, dependencies: RunMarketAnalysisDependencies): Promise<MarketLongTermRentAnalysis>;
async function buildSection(purpose: "sale-valuation" | "long-term-rent", subject: MarketProperty, command: RunMarketAnalysisCommand, dependencies: RunMarketAnalysisDependencies): Promise<MarketSaleValuationAnalysis | MarketLongTermRentAnalysis> {
  const suffix = purpose === "sale-valuation" ? "sale" : "rent";
  const criteria = purpose === "sale-valuation" ? command.analyses.saleValuation?.acquisitionCriteria : command.analyses.longTermRent?.acquisitionCriteria;
  const qualificationPolicy = purpose === "sale-valuation" ? command.policies.saleQualification : command.policies.longTermRentQualification;
  const estimationPolicy = purpose === "sale-valuation" ? command.policies.saleEstimation : command.policies.longTermRentEstimation;
  const acquisition = await acquireMarketComparables({ subject, purpose, criteria, context: { acquisitionId: `${command.context.analysisId}:${suffix}:acquisition`, requestedAt: command.context.analyzedAt, requestedBy: command.context.requestedBy } }, { provider: dependencies.comparableProvider });
  const qualification = qualifyMarketComparables({ subject, acquisition, policy: qualificationPolicy, context: { qualificationId: `${command.context.analysisId}:${suffix}:qualification`, evaluatedAt: command.context.analyzedAt, evaluatedBy: command.context.requestedBy } });
  const core = buildMarketEstimateCore(qualification, estimationPolicy, subject.characteristics.squareFeet);
  const stage = purpose === "sale-valuation" ? "valuation" as const : "rent-analysis" as const;
  const section = purpose === "sale-valuation" ? "sale-valuation" as const : "long-term-rent" as const;
  const dataGaps = uniqueBy([
    ...acquisition.dataGaps.map((gap) => analysisGap(`${suffix}:acquisition:${gap.code}`, gap.code, gap.description, gap.severity, "comparable-acquisition", section)),
    ...qualification.dataGaps.map((gap) => analysisGap(`${suffix}:qualification:${gap.code}`, gap.code, gap.description, gap.severity, "comparable-qualification", section)),
    ...(core.status === "insufficient" ? [analysisGap(`${suffix}:estimate:INSUFFICIENT_COMPARABLE_COVERAGE`, "INSUFFICIENT_COMPARABLE_COVERAGE", "Qualified evidence cannot support an estimate under the policy.", "material", stage, section)] : []),
  ], (gap) => gap.id);
  const risks = sectionRisks(purpose, qualification, core.confidence, dataGaps);
  if (purpose === "sale-valuation") return deepFreeze({ status: core.status, ...(core.estimate !== undefined ? { estimatedValue: core.estimate } : {}), ...(core.range ? { valueRange: core.range } : {}), ...(core.unitEstimate !== undefined ? { estimatedPricePerSquareFoot: core.unitEstimate } : {}), qualification, ...(core.calculation ? { calculation: core.calculation } : {}), confidence: core.confidence, risks, dataGaps });
  return deepFreeze({ status: core.status, ...(core.estimate !== undefined ? { estimatedMonthlyRent: core.estimate } : {}), ...(core.range ? { rentRange: core.range } : {}), ...(core.unitEstimate !== undefined ? { estimatedRentPerSquareFoot: core.unitEstimate } : {}), qualification, ...(core.calculation ? { calculation: core.calculation } : {}), confidence: core.confidence, risks, dataGaps });
}

function validateCommand(command: RunMarketAnalysisCommand): void { if (!command.context.analysisId.trim()) throw new Error("Market analysis id is required."); if (Number.isNaN(command.context.analyzedAt.getTime())) throw new Error("Market analysis time must be valid."); if (!command.policies.version.trim()) throw new Error("Market analysis policy version is required."); if (command.policies.saleQualification.purpose !== "sale-valuation" || command.policies.longTermRentQualification.purpose !== "long-term-rent") throw new Error("MARKET_ANALYSIS_POLICY_PURPOSE_MISMATCH"); if (!command.policies.saleQualification.eligibility.requirePrice || !command.policies.longTermRentQualification.eligibility.requireMonthlyRent) throw new Error("MARKET_ANALYSIS_REQUIRED_VALUE_POLICY_INVALID"); validateEstimationPolicy(command.policies.saleEstimation); validateEstimationPolicy(command.policies.longTermRentEstimation); }
function analysisGap(id: string, code: string, description: string, severity: "informational" | "material" | "blocking", sourceStage: MarketAnalysisDataGap["sourceStage"], section: MarketAnalysisDataGap["section"]): MarketAnalysisDataGap { return { id, code, description, severity, sourceStage, section }; }
function sectionRisks(purpose: "sale-valuation" | "long-term-rent", qualification: MarketSaleValuationAnalysis["qualification"], confidence: MarketAnalysisConfidence, gaps: readonly MarketAnalysisDataGap[]): MarketRisk[] { const risks: MarketRisk[] = []; const evidenceIds = qualification.included.map((item) => item.candidate.id); const gapIds = gaps.map((gap) => gap.id); if (qualification.summary.sufficiency !== "sufficient") risks.push(risk(purpose === "sale-valuation" ? "SALE_EVIDENCE_LIMITED" : "RENTAL_EVIDENCE_LIMITED", "medium", `${purpose === "sale-valuation" ? "Sale" : "Rental"} evidence is limited.`, "The qualified comparable set is below preferred coverage.", evidenceIds, gapIds)); if (qualification.summary.includedCount < qualification.policySnapshot.minimumIncludedComparables) risks.push(risk("INSUFFICIENT_COMPARABLE_COVERAGE", "high", "Comparable coverage is insufficient.", "Fewer comparables were included than the policy minimum.", evidenceIds, gapIds)); if ((qualification.summary.averageSimilarityScore ?? 0) < 70) risks.push(risk("LOW_COMPARABLE_SIMILARITY", "medium", "Comparable similarity is low.", "Average included similarity is below 70.", evidenceIds, gapIds)); if (confidence.dimensions.dispersion < 10) risks.push(risk("HIGH_ESTIMATE_DISPERSION", "medium", "Estimate dispersion is high.", "Comparable values vary materially around the estimate.", evidenceIds, gapIds)); if (qualification.included.some((item) => item.normalizedWeight > 0.6)) risks.push(risk("CONCENTRATED_COMPARABLE_WEIGHT", "medium", "Comparable weight is concentrated.", "One comparable contributes more than 60 percent of analytical weight.", evidenceIds, gapIds)); if (qualification.excluded.some((item) => item.reasons.some((reason) => reason.code === "COMPARABLE_EVIDENCE_TOO_OLD"))) risks.push(risk("STALE_MARKET_EVIDENCE", "medium", "Some Market evidence is stale.", "Candidates were excluded because their evidence exceeded the recency policy.", qualification.excluded.map((item) => item.candidate.id), gapIds)); return risks.sort((a, b) => a.code.localeCompare(b.code)); }
function deriveRisks(subject: MarketProperty, sale: MarketSaleValuationAnalysis | undefined, rent: MarketLongTermRentAnalysis | undefined, gaps: readonly MarketAnalysisDataGap[]): MarketRisk[] { const risks = [...(sale?.risks ?? []), ...(rent?.risks ?? [])]; if (!subject.characteristics.propertyType || subject.characteristics.squareFeet === undefined) risks.push(risk("SUBJECT_CHARACTERISTICS_INCOMPLETE", "high", "Subject characteristics are incomplete.", "Core property facts required for market comparison are missing.", [], gaps.filter((gap) => gap.section === "subject").map((gap) => gap.id))); return mergeRisks(risks); }
function risk(code: MarketRisk["code"], severity: MarketRisk["severity"], title: string, description: string, evidenceIds: readonly string[], dataGapIds: readonly string[]): MarketRisk { return { code, severity, title, description, evidenceIds: [...evidenceIds].sort(), dataGapIds: [...dataGapIds].sort() }; }
function buildObservations(id: string, subject: MarketProperty, sale?: MarketSaleValuationAnalysis, rent?: MarketLongTermRentAnalysis): MarketAnalysisObservation[] { return [{ id: `${id}:observation:subject`, type: "subject-property", label: "Subject property", value: subject.address.formatted, sourceIds: subject.providerReferences.map((item) => item.externalId) }, ...(sale?.estimatedValue !== undefined ? [{ id: `${id}:observation:sale-value`, type: "estimated-sale-value", label: "Estimated sale value", value: sale.estimatedValue, sourceIds: sale.qualification.included.map((item) => item.candidate.id) }] : []), ...(rent?.estimatedMonthlyRent !== undefined ? [{ id: `${id}:observation:monthly-rent`, type: "estimated-monthly-rent", label: "Estimated monthly rent", value: rent.estimatedMonthlyRent, sourceIds: rent.qualification.included.map((item) => item.candidate.id) }] : [])]; }
function buildEvidence(id: string, sale?: MarketSaleValuationAnalysis, rent?: MarketLongTermRentAnalysis): MarketAnalysisEvidence[] { return [...(sale ? [{ id: `${id}:evidence:sale`, type: "qualified-sale-comparables", description: `${sale.qualification.included.length} sale comparables qualified.`, candidateIds: sale.qualification.included.map((item) => item.candidate.id) }] : []), ...(rent ? [{ id: `${id}:evidence:rent`, type: "qualified-rental-comparables", description: `${rent.qualification.included.length} rental comparables qualified.`, candidateIds: rent.qualification.included.map((item) => item.candidate.id) }] : [])]; }
function reportConfidence(sections: readonly MarketAnalysisConfidence[]): MarketAnalysisConfidence { if (!sections.length) return { score: 0, level: "none", reasons: ["No supported analysis was requested."], dimensions: { coverage: 0, similarity: 0, dispersion: 0 } }; const score = round(sections.reduce((sum, item) => sum + item.score, 0) / sections.length); return { score, level: score >= 80 ? "high" : score >= 60 ? "medium" : "low", reasons: uniqueBy(sections.flatMap((item) => item.reasons), (item) => item).sort(), dimensions: { coverage: round(average(sections.map((item) => item.dimensions.coverage))), similarity: round(average(sections.map((item) => item.dimensions.similarity))), dispersion: round(average(sections.map((item) => item.dimensions.dispersion))) } }; }
function reportStatus(sale: MarketSaleValuationAnalysis | undefined, rent: MarketLongTermRentAnalysis | undefined, requested: boolean): MarketAnalysisReportStatus { if (!requested) return "unsupported"; const sections = [sale, rent].filter((item): item is MarketSaleValuationAnalysis | MarketLongTermRentAnalysis => item !== undefined); if (sections.every((item) => item.status === "estimated")) return "complete"; if (sections.some((item) => item.status === "estimated" || item.status === "limited")) return "partial"; return "insufficient"; }
function headline(status: MarketAnalysisReportStatus, sale?: MarketSaleValuationAnalysis, rent?: MarketLongTermRentAnalysis): string { if (status === "unsupported") return "No supported Market analysis was requested."; if (status === "insufficient") return "Available evidence is insufficient to produce a Market estimate."; return `Market analysis is ${status}${sale?.estimatedValue !== undefined ? ` with an estimated sale value of $${Math.round(sale.estimatedValue).toLocaleString("en-US")}` : ""}${rent?.estimatedMonthlyRent !== undefined ? ` and estimated monthly rent of $${Math.round(rent.estimatedMonthlyRent).toLocaleString("en-US")}` : ""}.`; }
function explanation(sale?: MarketSaleValuationAnalysis, rent?: MarketLongTermRentAnalysis): string { return [`Sale evidence: ${sale?.status ?? "not requested"}.`, `Long-term rental evidence: ${rent?.status ?? "not requested"}.`].join(" "); }
function sectionLineage(section: MarketSaleValuationAnalysis | MarketLongTermRentAnalysis) { return { acquisitionId: section.qualification.acquisitionId, qualificationId: section.qualification.qualificationId, includedCandidateIds: section.qualification.included.map((item) => item.candidate.id) }; }
function uniqueBy<T>(values: readonly T[], key: (value: T) => string): T[] { return [...new Map(values.map((value) => [key(value), value])).values()]; }
function mergeRisks(risks: readonly MarketRisk[]): MarketRisk[] { const groups = new Map<MarketRisk["code"], MarketRisk[]>(); for (const item of risks) groups.set(item.code, [...(groups.get(item.code) ?? []), item]); return [...groups.entries()].map(([code, items]) => ({ ...items[0], code, severity: items.some((item) => item.severity === "high") ? "high" as const : items.some((item) => item.severity === "medium") ? "medium" as const : "low" as const, evidenceIds: [...new Set(items.flatMap((item) => item.evidenceIds))].sort(), dataGapIds: [...new Set(items.flatMap((item) => item.dataGapIds))].sort() })).sort((a, b) => a.code.localeCompare(b.code)); }
function validateEstimationPolicy(policy: RunMarketAnalysisCommand["policies"]["saleEstimation"]): void { if (!Number.isInteger(policy.minimumEstimateComparables) || policy.minimumEstimateComparables < 1 || policy.lowPercentile < 0 || policy.highPercentile > 1 || policy.lowPercentile > policy.highPercentile) throw new Error("MARKET_ANALYSIS_ESTIMATION_POLICY_INVALID"); }
function average(values: readonly number[]): number { return values.reduce((sum, value) => sum + value, 0) / values.length; }
function round(value: number): number { return Math.round(value * 100) / 100; }
function deepFreeze<T>(value: T): T { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child); } return value; }
