import { describe, expect, it, vi } from "vitest";
import { ProviderType } from "../domain/enums/provider-type";
import type { MarketPropertyResolutionResult } from "../domain/property-resolution";
import type { MarketComparableProvider, MarketComparableProviderCandidate } from "./providers/market-comparable-provider";
import { ProviderError, ProviderErrorCode } from "./providers/provider-error";
import { providerFailure, providerSuccess } from "./providers/provider-result";
import { buildDefaultMarketAnalysisPolicies } from "./market-analysis-policies";
import { runMarketAnalysis } from "./run-market-analysis";

const analyzedAt = new Date("2026-07-21T12:00:00.000Z");
const property = { id: "market-property:resolution", providerReferences: [{ provider: ProviderType.RentCast, externalId: "subject-external" }], address: { formatted: "123 Main St, Mesa, AZ 85201", addressLine1: "123 Main St", city: "Mesa", state: "AZ", postalCode: "85201" }, characteristics: { propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1650, yearBuilt: 2000 }, financialFacts: {}, coordinates: { latitude: 33.4, longitude: -111.8 } } as const;
const resolution: MarketPropertyResolutionResult = { resolutionId: "resolution", requestedAddress: { streetAddress: "123 Main St", city: "Mesa", state: "AZ", postalCode: "85201" }, normalizedAddress: { display: property.address, comparisonKey: "123 main st|mesa|AZ|85201|" }, status: "resolved", property, alternatives: [], confidence: { score: 100, level: "high", reasons: [] }, dataGaps: [], provenance: [], resolvedAt: analyzedAt };

function candidates(purpose: "sale-valuation" | "long-term-rent", count = 5): MarketComparableProviderCandidate[] { return Array.from({ length: count }, (_, index) => ({ externalId: `${purpose}-${index}`, address: { formatted: `${200 + index} Oak St, Mesa, AZ 85201`, addressLine1: `${200 + index} Oak St`, city: "Mesa", state: "AZ", postalCode: "85201" }, propertyType: "Single Family", bedrooms: 3, bathrooms: 2, squareFeet: 1600 + index * 20, yearBuilt: 1998 + index, latitude: 33.41 + index * 0.001, longitude: -111.8, distanceMiles: 0.4 + index * 0.2, price: purpose === "sale-valuation" ? 390000 + index * 10000 : 2200 + index * 100, listedAt: new Date(`2026-0${Math.min(index + 2, 6)}-01`), listingStatus: purpose === "sale-valuation" ? "sold" : "active", sourceRank: index + 1 })); }
function provider(sale = candidates("sale-valuation"), rent = candidates("long-term-rent")): MarketComparableProvider { return { acquireComparables: vi.fn(async (request) => providerSuccess({ provider: ProviderType.RentCast, purpose: request.purpose, candidates: request.purpose === "sale-valuation" ? sale : rent, retrievedAt: analyzedAt })) }; }
function command(analyses = { saleValuation: { enabled: true }, longTermRent: { enabled: true } }) { return { propertyResolution: resolution, analyses, policies: buildDefaultMarketAnalysisPolicies("Single Family"), context: { analysisId: "analysis", analyzedAt, requestedBy: "operator" } } as const; }

describe("runMarketAnalysis", () => {
  it("runs a complete dual analysis through acquisition and qualification", async () => { const report = await runMarketAnalysis(command(), { comparableProvider: provider() }); expect(report.status).toBe("complete"); expect(report.saleValuation?.estimatedValue).toBeGreaterThan(0); expect(report.longTermRent?.estimatedMonthlyRent).toBeGreaterThan(0); });
  it("supports sale-only analysis", async () => { const report = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider() }); expect(report.saleValuation).toBeDefined(); expect(report.longTermRent).toBeUndefined(); });
  it("supports rent-only analysis without STR fields", async () => { const report = await runMarketAnalysis(command({ saleValuation: { enabled: false }, longTermRent: { enabled: true } }), { comparableProvider: provider() }); expect(report.longTermRent?.estimatedMonthlyRent).toBeGreaterThan(0); expect(report).not.toHaveProperty("averageDailyRate"); expect(report).not.toHaveProperty("occupancy"); });
  it("returns unsupported when no supported section is requested without provider calls", async () => { const dependency = provider(); const report = await runMarketAnalysis(command({ saleValuation: { enabled: false }, longTermRent: { enabled: false } }), { comparableProvider: dependency }); expect(report.status).toBe("unsupported"); expect(dependency.acquireComparables).not.toHaveBeenCalled(); });
  it("returns insufficient and no estimate for empty evidence", async () => { const report = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider([], []) }); expect(report.status).toBe("insufficient"); expect(report.saleValuation?.estimatedValue).toBeUndefined(); expect(report.dataGaps.map((gap) => gap.code)).toContain("INSUFFICIENT_COMPARABLE_COVERAGE"); });
  it("returns partial for a policy-authorized limited one-comparable estimate", async () => { const report = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider(candidates("sale-valuation", 1), []) }); expect(report.status).toBe("partial"); expect(report.saleValuation?.status).toBe("limited"); });
  it("propagates provider errors", async () => { const error = new ProviderError({ provider: ProviderType.RentCast, code: ProviderErrorCode.Unavailable, message: "down" }); const dependency: MarketComparableProvider = { acquireComparables: async () => providerFailure(error) }; await expect(runMarketAnalysis(command(), { comparableProvider: dependency })).rejects.toBe(error); });
  it.each(["ambiguous", "not-found", "unsupported"] as const)("rejects %s property resolution", async (status) => { const invalid = { ...resolution, status, property: undefined } as unknown as MarketPropertyResolutionResult; await expect(runMarketAnalysis({ ...command(), propertyResolution: invalid }, { comparableProvider: provider() })).rejects.toThrow("PROPERTY_NOT_RESOLVED"); });
  it("preserves complete section lineage", async () => { const report = await runMarketAnalysis(command(), { comparableProvider: provider() }); expect(report.lineage.propertyResolutionId).toBe("resolution"); expect(report.lineage.sale?.acquisitionId).toBe("analysis:sale:acquisition"); expect(report.lineage.sale?.qualificationId).toBe("analysis:sale:qualification"); expect(report.lineage.sale?.includedCandidateIds).toEqual(report.saleValuation?.qualification.included.map((item) => item.candidate.id)); });
  it("preserves policy version", async () => expect((await runMarketAnalysis(command(), { comparableProvider: provider() })).lineage.policyVersion).toBe("market-analysis-v1"));
  it("builds deterministic observations and evidence from estimates", async () => { const report = await runMarketAnalysis(command(), { comparableProvider: provider() }); expect(report.observations.map((item) => item.type)).toEqual(["subject-property", "estimated-sale-value", "estimated-monthly-rent"]); expect(report.evidence).toHaveLength(2); });
  it("derives confidence independently from estimate magnitude", async () => { const low = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider(candidates("sale-valuation").map((item) => ({ ...item, price: (item.price ?? 0) / 100 })), []) }); const high = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider(candidates("sale-valuation"), []) }); expect(low.confidence.score).toBe(high.confidence.score); });
  it("derives explainable limited-evidence risks", async () => { const report = await runMarketAnalysis(command({ saleValuation: { enabled: true }, longTermRent: { enabled: false } }), { comparableProvider: provider(candidates("sale-valuation", 1), []) }); expect(report.risks.map((risk) => risk.code)).toContain("SALE_EVIDENCE_LIMITED"); expect(report.risks.every((risk) => Array.isArray(risk.evidenceIds))).toBe(true); });
  it("rolls up property-resolution gaps with stage lineage", async () => { const gapResolution = { ...resolution, dataGaps: [{ code: "YEAR_BUILT_MISSING", description: "Missing year", severity: "informational", sourceField: "yearBuilt" }] } as MarketPropertyResolutionResult; const report = await runMarketAnalysis({ ...command({ saleValuation: { enabled: false }, longTermRent: { enabled: false } }), propertyResolution: gapResolution }, { comparableProvider: provider() }); expect(report.dataGaps[0]).toMatchObject({ id: "property-resolution:YEAR_BUILT_MISSING", sourceStage: "property-resolution", section: "subject" }); });
  it("produces deterministic summary projection", async () => { const report = await runMarketAnalysis(command(), { comparableProvider: provider() }); expect(report.summary.estimatedValue).toBe(report.saleValuation?.estimatedValue); expect(report.summary.riskCount).toBe(report.risks.length); expect(report.summary.headline).toContain("estimated sale value"); });
  it("is deterministic under fixed context", async () => expect(await runMarketAnalysis(command(), { comparableProvider: provider() })).toEqual(await runMarketAnalysis(command(), { comparableProvider: provider() })));
  it("deeply freezes the report without mutating command or resolution", async () => { const input = command(); const before = structuredClone(input); const report = await runMarketAnalysis(input, { comparableProvider: provider() }); expect(input).toEqual(before); expect(Object.isFrozen(resolution.property)).toBe(false); expect(Object.isFrozen(report)).toBe(true); expect(Object.isFrozen(report.subject)).toBe(true); expect(Object.isFrozen(report.saleValuation?.qualification)).toBe(true); });
  it("validates analysis identity and policy purpose", async () => { await expect(runMarketAnalysis({ ...command(), context: { analysisId: " ", analyzedAt } }, { comparableProvider: provider() })).rejects.toThrow("analysis id"); const policies = buildDefaultMarketAnalysisPolicies(); await expect(runMarketAnalysis({ ...command(), policies: { ...policies, saleQualification: policies.longTermRentQualification } }, { comparableProvider: provider() })).rejects.toThrow("POLICY_PURPOSE_MISMATCH"); });
});
