import{CAPABILITY_REGISTRY,type CapabilityCode}from"@/platform/commerce";
export type FirstValueProductFamily="hpm"|"guidebook"|"furnishing"|"investment_intelligence";export type JourneyStatus="pending"|"ready"|"in_progress"|"customer_action_required"|"internal_action_required"|"system_processing"|"blocked"|"ready_for_evaluation"|"completed"|"cancelled";
export type FirstValueJourney=Readonly<{id:string;tenantId:string;customerAccountId:string;onboardingCaseId?:string;entitlementSourceId:string;productFamily:FirstValueProductFamily;sourceType:"onboarding_handoff"|"existing_product_context"|"administrative_entry"|"migration"|"expansion";sourceReferenceId:string;productContextType:string;productContextId:string;policyCode:string;policyVersion:number;status:JourneyStatus;outcomeCode?:string;blockerCode?:FirstValueBlockerCode;startedAt?:string;completedAt?:string;cancelledAt?:string;createdAt:string;updatedAt:string;revision:number}>;
export type FirstValuePolicy=Readonly<{code:string;version:number;productFamily:FirstValueProductFamily;name:string;description:string;requiredEvidenceCodes:readonly string[];requiredCapabilityCodes:readonly CapabilityCode[];evaluatorCode:string;completionOperationCode:string;destinationResolverCode:string;artifactType:string;supportsExistingArtifactReuse:boolean;reusePolicyCode?:string;status:"draft"|"active"|"retired";effectiveFrom:string;effectiveUntil?:string;createdBy:string;createdAt:string}>;
export type FirstValueActionDefinition=Readonly<{code:string;version:number;productFamily:FirstValueProductFamily;responsibility:"customer"|"internal"|"shared"|"system";operationCode:string;requiredCapabilityCodes:readonly CapabilityCode[];prerequisiteActionCodes:readonly string[];completionEvidenceCodes:readonly string[];retryPolicyCode?:string;validationPolicyCode?:string;status:"active"|"retired"}>;
export type FirstValueEvidence=Readonly<{id:string;journeyId:string;evidenceCode:string;evidenceVersion:number;sourceType:"product_resource"|"domain_decision"|"validation_result"|"provider_observation"|"customer_confirmation"|"internal_confirmation"|"migration";sourceReferenceType:string;sourceReferenceId:string;status:"valid"|"invalid"|"superseded";evaluatedAt:string;expiresAt?:string;createdAt:string}>;
export type FirstValueBlockerCode="FIRST_VALUE_ENTRY_UNAVAILABLE"|"FIRST_VALUE_POLICY_UNAVAILABLE"|"FIRST_VALUE_POLICY_INVALID"|"ONBOARDING_HANDOFF_INVALID"|"ENTITLEMENT_NOT_ACTIVE"|"CAPABILITY_NOT_GRANTED"|"PRODUCT_LIMIT_REACHED"|"PRODUCT_CONTEXT_MISSING"|"PRODUCT_CONTEXT_UNAUTHORIZED"|"CUSTOMER_INPUT_REQUIRED"|"CUSTOMER_CONFIRMATION_REQUIRED"|"INTERNAL_REVIEW_REQUIRED"|"INITIAL_DATA_REQUIRED"|"INITIAL_DATA_INVALID"|"INTEGRATION_AUTHORIZATION_REQUIRED"|"INTEGRATION_CONNECTION_FAILED"|"PROVIDER_DATA_UNAVAILABLE"|"PROVIDER_RESOLUTION_FAILED"|"ARTIFACT_CREATION_PENDING"|"ARTIFACT_CREATION_FAILED"|"ARTIFACT_NOT_USABLE"|"DESTINATION_UNAUTHORIZED"|"SYSTEM_PROCESSING"|"STALE_JOURNEY_REVISION";
export class FirstValueError extends Error{constructor(public readonly code:FirstValueBlockerCode|"NOT_AUTHORIZED"|"INVALID_TRANSITION",message:string){super(message);Object.freeze(this)}}
export function validatePolicy(value:FirstValuePolicy,components:Readonly<{evaluators:readonly string[];operations:readonly string[];destinations:readonly string[];evidence:readonly string[]}>){if(!value.artifactType||!components.evaluators.includes(value.evaluatorCode)||!components.operations.includes(value.completionOperationCode)||!components.destinations.includes(value.destinationResolverCode))fail("FIRST_VALUE_POLICY_INVALID","Policy components are invalid.");for(const code of value.requiredCapabilityCodes)if(!CAPABILITY_REGISTRY[code])fail("FIRST_VALUE_POLICY_INVALID","Policy capability is not registered.");for(const code of value.requiredEvidenceCodes)if(!components.evidence.includes(code))fail("FIRST_VALUE_POLICY_INVALID","Policy evidence is not registered.");if(value.supportsExistingArtifactReuse&&!value.reusePolicyCode)fail("FIRST_VALUE_POLICY_INVALID","Artifact reuse requires a policy.");return freeze(value)}
export function assertJourneyTransition(from:JourneyStatus,to:JourneyStatus){const allowed:Record<JourneyStatus,readonly JourneyStatus[]>={pending:["ready","blocked","cancelled"],ready:["in_progress","customer_action_required","internal_action_required","system_processing","blocked"],in_progress:["customer_action_required","internal_action_required","system_processing","ready_for_evaluation","blocked"],customer_action_required:["in_progress","blocked"],internal_action_required:["in_progress","ready_for_evaluation","blocked"],system_processing:["ready_for_evaluation","blocked"],blocked:["in_progress","customer_action_required","internal_action_required","system_processing","cancelled"],ready_for_evaluation:["completed","blocked"],completed:[],cancelled:[]};if(from!==to&&!allowed[from].includes(to))fail("INVALID_TRANSITION","Invalid first-value transition.")}
export function freeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child)}return value}function fail(code:FirstValueError["code"],message:string):never{throw new FirstValueError(code,message)}
