import{freeze,validatePolicy,type FirstValueActionDefinition,type FirstValuePolicy}from"./model";
export const FIRST_VALUE_EVIDENCE_CODES=freeze(["entitlement.active","context.authorized","hpm.dataset.validated","hpm.source.classified","hpm.projection.usable","guidebook.draft.persisted","guidebook.draft.editable","furnishing.brief.persisted","furnishing.brief.accepted","investment.assumptions.validated","investment.analysis.persisted","destination.authorized"]as const);const evaluators=["hpm.usability.v1","guidebook.editable_draft.v1","furnishing.accepted_brief.v1","investment.usable_analysis.v1"],operations=["first_value.complete.v1"],destinations=["hpm.destination.v1","guidebook.destination.v1","furnishing.destination.v1","investment.destination.v1"];
const policy=(value:Omit<FirstValuePolicy,"version"|"status"|"effectiveFrom"|"createdBy"|"createdAt"|"completionOperationCode">)=>validatePolicy({...value,version:1,status:"active",effectiveFrom:"2026-08-11T00:00:00Z",createdBy:"system",createdAt:"2026-08-11T00:00:00Z",completionOperationCode:"first_value.complete.v1"},{evaluators,operations,destinations,evidence:FIRST_VALUE_EVIDENCE_CODES});
export const FIRST_VALUE_POLICY_REGISTRY=freeze({
 hpm:policy({code:"hpm.first_value",productFamily:"hpm",name:"Usable performance workspace",description:"Validated actual or clearly classified guided-start data produces a usable projection.",requiredEvidenceCodes:["entitlement.active","context.authorized","hpm.dataset.validated","hpm.source.classified","hpm.projection.usable","destination.authorized"],requiredCapabilityCodes:["hpm.workspace.access","hpm.performance.view"],evaluatorCode:"hpm.usability.v1",destinationResolverCode:"hpm.destination.v1",artifactType:"hpm_performance_workspace",supportsExistingArtifactReuse:true,reusePolicyCode:"usable_current_workspace.v1"}),
 guidebook:policy({code:"guidebook.first_value",productFamily:"guidebook",name:"Editable Guidebook draft",description:"A persisted editable draft in an authorized Guidebook property context.",requiredEvidenceCodes:["entitlement.active","context.authorized","guidebook.draft.persisted","guidebook.draft.editable","destination.authorized"],requiredCapabilityCodes:["guidebook.create"],evaluatorCode:"guidebook.editable_draft.v1",destinationResolverCode:"guidebook.destination.v1",artifactType:"guidebook_draft",supportsExistingArtifactReuse:true,reusePolicyCode:"editable_guidebook.v1"}),
 furnishing:policy({code:"furnishing.first_value",productFamily:"furnishing",name:"Consultation-ready project brief",description:"A persisted brief accepted for consultation or sourcing review.",requiredEvidenceCodes:["entitlement.active","context.authorized","furnishing.brief.persisted","furnishing.brief.accepted","destination.authorized"],requiredCapabilityCodes:["furnishing.project.access"],evaluatorCode:"furnishing.accepted_brief.v1",destinationResolverCode:"furnishing.destination.v1",artifactType:"furnishing_project_brief",supportsExistingArtifactReuse:true,reusePolicyCode:"same_engagement_accepted_brief.v1"}),
 investment_intelligence:policy({code:"investment.first_value",productFamily:"investment_intelligence",name:"Usable saved investment analysis",description:"Validated assumptions produce a persisted analysis with source lineage.",requiredEvidenceCodes:["entitlement.active","context.authorized","investment.assumptions.validated","investment.analysis.persisted","destination.authorized"],requiredCapabilityCodes:["investment.analysis.run"],evaluatorCode:"investment.usable_analysis.v1",destinationResolverCode:"investment.destination.v1",artifactType:"investment_analysis",supportsExistingArtifactReuse:true,reusePolicyCode:"same_scope_usable_analysis.v1"}),
});
const action=(value:Omit<FirstValueActionDefinition,"version"|"status">):FirstValueActionDefinition=>freeze({...value,version:1,status:"active"});export const FIRST_VALUE_ACTION_REGISTRY=freeze({
 "hpm.generate":action({code:"hpm.generate",productFamily:"hpm",responsibility:"system",operationCode:"hpm.initial_projection.create",requiredCapabilityCodes:["hpm.performance.view"],prerequisiteActionCodes:[],completionEvidenceCodes:["hpm.dataset.validated","hpm.source.classified","hpm.projection.usable"],retryPolicyCode:"bounded_product_retry.v1"}),
 "guidebook.generate":action({code:"guidebook.generate",productFamily:"guidebook",responsibility:"system",operationCode:"guidebook.initial_draft.create",requiredCapabilityCodes:["guidebook.create"],prerequisiteActionCodes:[],completionEvidenceCodes:["guidebook.draft.persisted","guidebook.draft.editable"],retryPolicyCode:"resolve_before_create.v1"}),
 "furnishing.review":action({code:"furnishing.review",productFamily:"furnishing",responsibility:"internal",operationCode:"furnishing.brief.accept",requiredCapabilityCodes:["furnishing.project.access"],prerequisiteActionCodes:[],completionEvidenceCodes:["furnishing.brief.persisted","furnishing.brief.accepted"]}),
 "investment.generate":action({code:"investment.generate",productFamily:"investment_intelligence",responsibility:"system",operationCode:"investment.initial_analysis.create",requiredCapabilityCodes:["investment.analysis.run"],prerequisiteActionCodes:[],completionEvidenceCodes:["investment.assumptions.validated","investment.analysis.persisted"],retryPolicyCode:"resolve_before_create.v1"}),
});
