import { AcquisitionType } from "../../domain";

export type InvestmentAssumptionGuidance = Readonly<{ label: string; shortDescription: string; description: string; includes?: readonly string[]; excludes?: readonly string[]; example?: string; sourceDescription: string; routeApplicability: readonly AcquisitionType[]; displayPriority: "persistent" | "details" | "tooltip" }>;
const both = [AcquisitionType.Purchase, AcquisitionType.RentalArbitrage] as const;
const user = "User supplied until Market, Learning, or an approved default explicitly provides the value.";
export const INVESTMENT_ASSUMPTION_GUIDANCE = Object.freeze({
  startupCosts: { label: "Other startup costs", shortDescription: "One-time launch costs outside furnishing and deposit.", description: "One-time launch costs not already included in furnishing or the security deposit, such as permits, photography, smart locks, initial supplies, installation, and setup services.", includes: ["Permits", "Photography", "Smart locks", "Initial supplies", "Setup services"], excludes: ["Furnishing budget", "Security deposit", "Purchase closing costs", "Recurring operating expenses"], sourceDescription: user, routeApplicability: [AcquisitionType.RentalArbitrage], displayPriority: "persistent" },
  furnishingBudget: { label: "Furnishing budget", shortDescription: "One-time cost to furnish and equip the property.", description: "One-time cost for furniture, linens, kitchenware, décor, equipment, and applicable installation.", excludes: ["Security deposit", "Other startup costs", "Recurring supplies"], sourceDescription: user, routeApplicability: both, displayPriority: "persistent" },
  securityDeposit: { label: "Security deposit", shortDescription: "Cash required by the landlord before the lease begins.", description: "Refundable or nonrefundable cash required by the landlord before the lease begins. Do not include first month’s rent.", excludes: ["First month’s rent", "Furnishing", "Other startup costs"], sourceDescription: user, routeApplicability: [AcquisitionType.RentalArbitrage], displayPriority: "persistent" },
  managementFeePercentage: { label: "Property management fee %", shortDescription: "Manager or co-host fee based on modeled accommodation revenue.", description: "Fee charged by a property manager or co-host. The current canonical model applies it to projected accommodation revenue.", excludes: ["Booking-platform fees", "Payment processing unless contractually combined"], sourceDescription: user, routeApplicability: both, displayPriority: "persistent" },
  monthlyUtilities: { label: "Utilities per month", shortDescription: "Recurring operator-paid utility cost.", description: "Monthly electricity, gas, water, internet, and similar services paid by the operator. Rental values are excluded when utilities are included in the lease.", sourceDescription: user, routeApplicability: both, displayPriority: "persistent" },
  annualCleaning: { label: "Cleaning expense per year", shortDescription: "Annual cost paid for property cleaning.", description: "Annual cleaning expense paid by the operator. This is an expense, not a cleaning fee charged to a guest; the current model does not separately model guest-paid cleaning revenue.", excludes: ["Guest-paid cleaning revenue", "Initial deep clean included in startup costs"], sourceDescription: user, routeApplicability: both, displayPriority: "persistent" },
  projectedOccupancyPercentage: { label: "Projected occupancy", shortDescription: "Share of available nights expected to be booked.", description: "Percentage of available nights expected to be booked during the modeled year.", sourceDescription: "User supplied in the draft; the full analysis evaluates it against Market evidence.", routeApplicability: both, displayPriority: "persistent" },
  projectedAdr: { label: "Projected ADR", shortDescription: "Average accommodation revenue per occupied night.", description: "Average nightly accommodation revenue for occupied nights before modeled management expenses. The current model does not separately deduct a booking-platform fee.", sourceDescription: "User supplied in the draft; the full analysis evaluates it against Market evidence.", routeApplicability: both, displayPriority: "persistent" },
  purchasePrice: { label: "Purchase price", shortDescription: "Contract or proposed acquisition price.", description: "Price paid for the property before closing costs, financing fees, furnishing, and reserves.", sourceDescription: user, routeApplicability: [AcquisitionType.Purchase], displayPriority: "details" },
  closingCosts: { label: "Purchase closing costs", shortDescription: "One-time acquisition closing costs.", description: "One-time title, escrow, lender, legal, recording, and other closing costs not included in the purchase price.", excludes: ["Down payment", "Furnishing", "Recurring operating expenses"], sourceDescription: user, routeApplicability: [AcquisitionType.Purchase], displayPriority: "persistent" },
  downPaymentPercentage: { label: "Down payment %", shortDescription: "Purchase price funded with initial equity.", description: "Percentage of purchase price paid in cash at acquisition. Closing costs and furnishing are modeled separately.", sourceDescription: user, routeApplicability: [AcquisitionType.Purchase], displayPriority: "details" },
  interestRatePercentage: { label: "Interest rate %", shortDescription: "Annual nominal loan interest rate.", description: "Annual interest rate used with the loan term to calculate modeled debt service.", sourceDescription: user, routeApplicability: [AcquisitionType.Purchase], displayPriority: "details" },
  loanTermYears: { label: "Loan term", shortDescription: "Amortization period in years.", description: "Number of years over which modeled purchase debt is amortized.", sourceDescription: user, routeApplicability: [AcquisitionType.Purchase], displayPriority: "details" },
  monthlyLease: { label: "Monthly lease", shortDescription: "Recurring monthly rent owed to the landlord.", description: "Contract or proposed monthly lease payment, separate from Market rent estimates and utilities.", sourceDescription: user, routeApplicability: [AcquisitionType.RentalArbitrage], displayPriority: "persistent" },
  leaseTermMonths: { label: "Lease term", shortDescription: "Contract duration in months.", description: "Number of months in the proposed lease commitment.", sourceDescription: user, routeApplicability: [AcquisitionType.RentalArbitrage], displayPriority: "details" },
} satisfies Readonly<Record<string, InvestmentAssumptionGuidance>>);

export type InvestmentAssumptionGuidanceId = keyof typeof INVESTMENT_ASSUMPTION_GUIDANCE;
export function getInvestmentAssumptionGuidance(id: InvestmentAssumptionGuidanceId): InvestmentAssumptionGuidance { return INVESTMENT_ASSUMPTION_GUIDANCE[id]; }
