import "server-only";
import { randomUUID } from "node:crypto";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { advanceControlledExtraction, authorizeControlledJourneyActor, CONTROLLED_STAGES, ControlledJourneyFault, dryRunControlledExtraction } from "@/features/guidebook-creation-assistant/controlled-journey";

export const runtime="nodejs";export const dynamic="force-dynamic";
const context=z.object({verificationRunId:z.string().uuid(),customerAccountId:z.string().uuid(),entitlementId:z.string().uuid()});
const command=z.union([context.extend({expectedStage:z.literal("not_started")}).strict(),z.object({expectedStage:z.enum(CONTROLLED_STAGES)}).strict(),z.object({action:z.literal("cleanup")}).strict(),context.extend({action:z.literal("dry_run")}).strict()]);

export async function GET(request:NextRequest){const correlationId=randomUUID(),auth=await authorize(request);if(!auth.ok)return response({ok:false,code:auth.code,correlationId},auth.status);return response({ok:true,runtime:"nodejs",operation:"controlled_guidebook_extraction_v2",operationEnabled:process.env.CONTROLLED_GUIDEBOOK_EXTRACTION_ENABLED==="true",generationPermitted:false,customerEnablementDisabled:process.env.GUIDEBOOK_CREATION_ENABLED!=="true",publicCohortEmpty:!(process.env.GUIDEBOOK_CREATION_INTERNAL_COHORT??"").trim(),correlationId})}
export async function POST(request:NextRequest){const correlationId=randomUUID(),auth=await authorize(request);if(!auth.ok)return response({ok:false,code:auth.code,correlationId},auth.status);const parsed=command.safeParse(await request.json().catch(()=>null));if(!parsed.success)return response({ok:false,code:"CONTROLLED_EXTRACTION_COMMAND_INVALID",correlationId},400);try{if("action"in parsed.data&&parsed.data.action==="dry_run")return response({ok:true,...await dryRunControlledExtraction({actorId:auth.actorId,verificationRunId:parsed.data.verificationRunId,customerAccountId:parsed.data.customerAccountId,entitlementId:parsed.data.entitlementId})});return response({ok:true,...await advanceControlledExtraction({actorId:auth.actorId,authenticated:auth.client,command:parsed.data})})}catch(error){const failure=error instanceof ControlledJourneyFault?error:null;return response({ok:false,code:failure?.message??"CONTROLLED_EXTRACTION_FAILED_SAFE",correlationId},failure?.status??500)}}

async function authorize(request:NextRequest):Promise<{ok:true;actorId:string;client:SupabaseClient}|{ok:false;code:string;status:number}>{const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"").trim(),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!token||!url||!key)return{ok:false,code:"CONTROLLED_EXTRACTION_UNAUTHORIZED",status:401};const client=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await client.auth.getUser(token);if(!user)return{ok:false,code:"CONTROLLED_EXTRACTION_UNAUTHORIZED",status:401};const{data:isAdmin}=await client.rpc("is_admin");if(isAdmin!==true)return{ok:false,code:"CONTROLLED_EXTRACTION_UNAUTHORIZED",status:401};if(!(await authorizeControlledJourneyActor(user.id)))return{ok:false,code:"CONTROLLED_EXTRACTION_CAPABILITY_REQUIRED",status:403};return{ok:true,actorId:user.id,client}}
function response(body:Record<string,unknown>,status=200){return NextResponse.json(body,{status,headers:{"Cache-Control":"private, no-store, max-age=0","X-Robots-Tag":"noindex, nofollow, noarchive",Allow:"GET, POST"}})}
