import { createAcquisitionContingencyId, createAcquisitionPipelineId, createDueDiligenceItemId, type AcquisitionActorReference, type AcquisitionContingency, type DueDiligenceItem } from "../../../domain";
import type { AcquisitionRequirementOutcome, AcquisitionActionReference, AcquisitionEvidenceReference, AcquisitionDocumentReference, AcquisitionRequirementStatus, AcquisitionRequirementPriority } from "../../../domain/requirements";
import { AcquisitionPersistenceError } from "./acquisition-persistence-error";
const fail = (message: string): never => { throw new AcquisitionPersistenceError("ACQUISITION_PERSISTENCE_MAPPING_INVALID", message); };
const date = (value: unknown, field: string) => { const result = new Date(String(value)); if (!value || Number.isNaN(result.getTime())) fail(`Invalid ${field}.`); return result; };
const actor = (value: unknown): AcquisitionActorReference => { if (!value || typeof value !== "object") return fail("Invalid requirement actor."); const result = value as Record<string, unknown>; if ((result.type !== "user" && result.type !== "system") || typeof result.id !== "string" || !result.id.trim()) return fail("Invalid requirement actor."); return { type: result.type, id: result.id }; };
const array = (value: unknown) => Array.isArray(value) ? value : fail("Invalid requirement references.");
const status = (value: unknown): AcquisitionRequirementStatus => ["not-started","in-progress","satisfied","waived","failed","not-applicable"].includes(String(value)) ? value as AcquisitionRequirementStatus : fail("Invalid requirement status.");
const priority = (value: unknown): AcquisitionRequirementPriority => ["low","normal","high","critical"].includes(String(value)) ? value as AcquisitionRequirementPriority : fail("Invalid requirement priority.");
function references(value: Record<string, unknown>) { const actions = array(value.action_references).map(item => item as AcquisitionActionReference); const evidence = array(value.evidence_references).map(item => item as AcquisitionEvidenceReference); const documents = array(value.document_references).map(item => item as AcquisitionDocumentReference); return { actionReferences: Object.freeze(actions), evidenceReferences: Object.freeze(evidence), documentReferences: Object.freeze(documents) }; }
function outcome(value: unknown): AcquisitionRequirementOutcome | undefined { if (!value) return undefined; if (typeof value !== "object") return fail("Invalid requirement outcome."); const result = value as Record<string, unknown>; const resultStatus = status(result.status); if (["not-started","in-progress"].includes(resultStatus)) return fail("Invalid terminal requirement outcome."); return { status: resultStatus as Exclude<AcquisitionRequirementStatus,"not-started"|"in-progress">, ...(result.explanation ? { explanation: String(result.explanation) } : {}), ...(result.waiver ? { waiver: result.waiver as never } : {}), ...(result.concerns ? { concerns: array(result.concerns) as never } : {}), recordedAt: date(result.recorded_at, "requirement outcome timestamp"), recordedBy: actor(result.recorded_by) }; }
export type AcquisitionContingencyRow = Readonly<{ id: string; pipeline_id: string; route: string; type: string; title: string; description?: string | null; status: string; blocking: boolean; priority: string; due_at?: string | null; source: unknown; outcome?: unknown; action_references: unknown; evidence_references: unknown; document_references: unknown; created_at: string; created_by: unknown; updated_at: string }>;
export type AcquisitionDueDiligenceRow = Readonly<{ id: string; pipeline_id: string; route: string; category: string; title: string; description?: string | null; status: string; blocking: boolean; priority: string; due_at?: string | null; related_contingency_id?: string | null; outcome?: unknown; action_references: unknown; evidence_references: unknown; document_references: unknown; created_at: string; created_by: unknown; updated_at: string }>;
export type AcquisitionRequirementHistoryRow = Readonly<{ id: string; pipeline_id: string; requirement_id: string; from_status: string; to_status: string; actor: unknown; occurred_at: string; reason?: unknown; aggregate_version: number }>;
export function mapAcquisitionContingencyRow(row: AcquisitionContingencyRow): AcquisitionContingency { const value = row as Record<string, unknown>; const refs = references(value); return Object.freeze({ requirementType: "contingency", id: createAcquisitionContingencyId(row.id), pipelineId: createAcquisitionPipelineId(row.pipeline_id), route: row.route as AcquisitionContingency["route"], type: row.type as AcquisitionContingency["type"], title: row.title, ...(row.description ? { description: row.description } : {}), status: status(row.status), blocking: row.blocking, priority: priority(row.priority), ...(row.due_at ? { dueAt: date(row.due_at, "contingency due date") } : {}), source: row.source as AcquisitionContingency["source"], relatedDueDiligenceItemIds: Object.freeze([]), ...refs, ...(row.outcome ? { outcome: outcome(row.outcome) } : {}), createdAt: date(row.created_at, "contingency created timestamp"), createdBy: actor(row.created_by), updatedAt: date(row.updated_at, "contingency updated timestamp") }); }
export function mapAcquisitionDueDiligenceRow(row: AcquisitionDueDiligenceRow): DueDiligenceItem { const refs = references(row as unknown as Record<string, unknown>); return Object.freeze({ requirementType: "due-diligence", id: createDueDiligenceItemId(row.id), pipelineId: createAcquisitionPipelineId(row.pipeline_id), route: row.route as DueDiligenceItem["route"], category: row.category as DueDiligenceItem["category"], title: row.title, ...(row.description ? { description: row.description } : {}), status: status(row.status), blocking: row.blocking, priority: priority(row.priority), ...(row.due_at ? { dueAt: date(row.due_at, "diligence due date") } : {}), ...(row.related_contingency_id ? { relatedContingencyId: createAcquisitionContingencyId(row.related_contingency_id) } : {}), ...refs, ...(row.outcome ? { outcome: outcome(row.outcome) } : {}), createdAt: date(row.created_at, "diligence created timestamp"), createdBy: actor(row.created_by), updatedAt: date(row.updated_at, "diligence updated timestamp") }); }
export function mapAcquisitionRequirementHistoryRow(row: AcquisitionRequirementHistoryRow) { if (!row.id || !row.requirement_id || !Number.isInteger(row.aggregate_version) || row.aggregate_version < 1) fail("Invalid requirement history row."); return Object.freeze({ id: row.id, pipelineId: createAcquisitionPipelineId(row.pipeline_id), requirementId: row.requirement_id, fromStatus: status(row.from_status), toStatus: status(row.to_status), actor: actor(row.actor), occurredAt: date(row.occurred_at, "requirement history timestamp"), ...(row.reason ? { reason: row.reason } : {}), aggregateVersion: row.aggregate_version }); }
export function mapAcquisitionContingencyToPersistence(value: AcquisitionContingency) { return { id: value.id.value, pipeline_id: value.pipelineId.value, route: value.route, type: value.type, title: value.title, ...(value.description ? { description: value.description } : {}), status: value.status, blocking: value.blocking, priority: value.priority, ...(value.dueAt ? { due_at: value.dueAt.toISOString() } : {}), source: value.source, ...(value.outcome ? { outcome: serialize(value.outcome) } : {}), action_references: value.actionReferences, evidence_references: value.evidenceReferences, document_references: value.documentReferences, created_at: value.createdAt.toISOString(), created_by: value.createdBy, updated_at: value.updatedAt.toISOString() }; }
export function mapAcquisitionDueDiligenceToPersistence(value: DueDiligenceItem) { return { id: value.id.value, pipeline_id: value.pipelineId.value, route: value.route, category: value.category, title: value.title, ...(value.description ? { description: value.description } : {}), status: value.status, blocking: value.blocking, priority: value.priority, ...(value.dueAt ? { due_at: value.dueAt.toISOString() } : {}), ...(value.relatedContingencyId ? { related_contingency_id: value.relatedContingencyId.value } : {}), ...(value.outcome ? { outcome: serialize(value.outcome) } : {}), action_references: value.actionReferences, evidence_references: value.evidenceReferences, document_references: value.documentReferences, created_at: value.createdAt.toISOString(), created_by: value.createdBy, updated_at: value.updatedAt.toISOString() }; }
function serialize(value: unknown) { return JSON.parse(JSON.stringify(value, (_key, item) => item instanceof Date ? item.toISOString() : item)); }
