import { createOpportunityAnalysisId, type InvestmentOpportunityRoute } from "@/features/investment-opportunity/domain";
import { createAcquisitionContractId, createAcquisitionOfferId, createAcquisitionOfferSequence, createAcquisitionPipelineId, createCounterpartyResponseId, type AcquisitionActorReference, type AcquisitionOffer, type AcquisitionOfferTerms, type AcquisitionContract, type AcquisitionContractTerms, type AcceptedAgreementBasis, type CounterpartyResponse } from "../../../domain";
import { validateAcquisitionOfferTerms } from "../../../domain/offers/acquisition-offer-terms";
import { validateAcquisitionContractTerms } from "../../../domain/contracts/acquisition-contract-terms";
import { AcquisitionPersistenceError } from "./acquisition-persistence-error";

export type AcquisitionOfferRow = Readonly<{ id: string; pipeline_id: string; sequence: number; route: string; status: AcquisitionOffer["status"]; source_analysis: unknown; terms: unknown; created_by: unknown; created_at: string; submitted_at?: string | null; expires_at?: string | null; current_offer: boolean; replaces_offer_id?: string | null }>;
export type AcquisitionCounterpartyResponseRow = Readonly<{ id: string; pipeline_id: string; offer_id: string; response_type: CounterpartyResponse["type"]; counterparty: unknown; terms?: unknown; responded_at: string; recorded_at: string; recorded_by: unknown; explanation?: string | null }>;
export type AcquisitionAgreementBasisRow = Readonly<{ pipeline_id: string; source: "offer" | "counteroffer"; offer_id: string; response_id?: string | null; accepted_terms: unknown; accepted_at: string }>;
export type AcquisitionContractRow = Readonly<{ id: string; pipeline_id: string; route: string; status: "recorded"; source: unknown; terms: unknown; recorded_by: unknown; recorded_at: string }>;
const fail = (message: string): never => { throw new AcquisitionPersistenceError("ACQUISITION_PERSISTENCE_MAPPING_INVALID", message); };
const date = (value: unknown, field: string) => { const parsed = new Date(String(value)); if (!value || Number.isNaN(parsed.getTime())) fail(`Invalid ${field}.`); return parsed; };
const actor = (value: unknown): AcquisitionActorReference => { if (!value || typeof value !== "object" || Array.isArray(value)) return fail("Invalid commercial actor."); const result = value as Record<string, unknown>; if ((result.type !== "user" && result.type !== "system") || typeof result.id !== "string" || !result.id.trim()) return fail("Invalid commercial actor."); return { type: result.type, id: result.id }; };
const route = (value: unknown): InvestmentOpportunityRoute => value === "purchase" || value === "rental-arbitrage" ? value : fail("Invalid commercial route.");
const obj = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : fail("Invalid commercial JSON value.");
const reviveTerms = (value: unknown, expectedRoute: InvestmentOpportunityRoute): AcquisitionOfferTerms => { const terms = structuredClone(obj(value)) as Record<string, unknown>; if (terms.route !== expectedRoute) fail("Commercial terms route mismatch."); for (const key of ["expiration", "proposedClosingDate", "proposedCommencementDate"]) if (typeof terms[key] === "string") terms[key] = date(terms[key], key); if (expectedRoute === "rental-arbitrage") { const lease = obj(terms.leaseTerm); terms.leaseTerm = lease; } validateAcquisitionOfferTerms(terms as AcquisitionOfferTerms); return terms as AcquisitionOfferTerms; };
const reviveContractTerms = (value: unknown, expectedRoute: InvestmentOpportunityRoute): AcquisitionContractTerms => { const terms = structuredClone(obj(value)) as Record<string, unknown>; if (terms.route !== expectedRoute) fail("Contract terms route mismatch."); for (const key of ["effectiveDate", "scheduledClosingDate", "commencementDate", "possessionDate"]) if (typeof terms[key] === "string") terms[key] = date(terms[key], key); validateAcquisitionContractTerms(terms as AcquisitionContractTerms); return terms as AcquisitionContractTerms; };

export function mapAcquisitionOfferRow(row: AcquisitionOfferRow): AcquisitionOffer { const r = route(row.route), source = obj(row.source_analysis); const sourceRoute = route(source.route); if (sourceRoute !== r) fail("Offer source-analysis route mismatch."); const offer = { id: createAcquisitionOfferId(row.id), pipelineId: createAcquisitionPipelineId(row.pipeline_id), sequence: createAcquisitionOfferSequence(row.sequence), route: r, status: row.status, sourceAnalysis: { analysisId: createOpportunityAnalysisId(String(source.analysis_id)), analysisVersion: Number(source.analysis_version), analyzedAt: date(source.analyzed_at, "analysis timestamp"), route: sourceRoute, ...(source.assumption_fingerprint ? { assumptionFingerprint: String(source.assumption_fingerprint) } : {}) }, terms: reviveTerms(row.terms, r), createdBy: actor(row.created_by), createdAt: date(row.created_at, "offer created timestamp"), ...(row.submitted_at ? { submittedAt: date(row.submitted_at, "offer submitted timestamp") } : {}), current: row.current_offer, ...(row.replaces_offer_id ? { replacesOfferId: createAcquisitionOfferId(row.replaces_offer_id) } : {}) }; return Object.freeze(offer); }
export function mapAcquisitionCounterpartyResponseRow(row: AcquisitionCounterpartyResponseRow): CounterpartyResponse { const response = { id: createCounterpartyResponseId(row.id), offerId: createAcquisitionOfferId(row.offer_id), type: row.response_type, counterparty: obj(row.counterparty) as CounterpartyResponse["counterparty"], respondedAt: date(row.responded_at, "response timestamp"), recordedAt: date(row.recorded_at, "response recorded timestamp"), recordedBy: actor(row.recorded_by), ...(row.explanation ? { explanation: row.explanation } : {}), ...(row.terms ? { terms: reviveTerms(row.terms, route(obj(row.terms).route)) } : {}) }; return Object.freeze(response); }
export function mapAcquisitionAgreementBasisRow(row: AcquisitionAgreementBasisRow): AcceptedAgreementBasis { const terms = reviveTerms(row.accepted_terms, route(obj(row.accepted_terms).route)); return Object.freeze({ source: row.source, offerId: createAcquisitionOfferId(row.offer_id), ...(row.response_id ? { responseId: createCounterpartyResponseId(row.response_id) } : {}), acceptedTerms: terms, acceptedAt: date(row.accepted_at, "agreement timestamp") }); }
export function mapAcquisitionContractRow(row: AcquisitionContractRow): AcquisitionContract { const r = route(row.route); return Object.freeze({ id: createAcquisitionContractId(row.id), pipelineId: createAcquisitionPipelineId(row.pipeline_id), route: r, status: "recorded", source: obj(row.source) as AcquisitionContract["source"], terms: reviveContractTerms(row.terms, r), recordedBy: actor(row.recorded_by), recordedAt: date(row.recorded_at, "contract timestamp") }); }
export function mapAcquisitionOfferToPersistence(value: AcquisitionOffer): AcquisitionOfferRow { return { id: value.id.value, pipeline_id: value.pipelineId.value, sequence: value.sequence.value, route: value.route, status: value.status, source_analysis: { analysis_id: value.sourceAnalysis.analysisId.value, analysis_version: value.sourceAnalysis.analysisVersion, analyzed_at: value.sourceAnalysis.analyzedAt.toISOString(), route: value.sourceAnalysis.route, ...(value.sourceAnalysis.assumptionFingerprint ? { assumption_fingerprint: value.sourceAnalysis.assumptionFingerprint } : {}) }, terms: serializeTerms(value.terms), created_by: value.createdBy, created_at: value.createdAt.toISOString(), ...(value.submittedAt ? { submitted_at: value.submittedAt.toISOString() } : {}), current_offer: value.current, ...(value.replacesOfferId ? { replaces_offer_id: value.replacesOfferId.value } : {}) }; }
export function mapAcquisitionResponseToPersistence(value: CounterpartyResponse, pipelineId: string): AcquisitionCounterpartyResponseRow { return { id: value.id.value, pipeline_id: pipelineId, offer_id: value.offerId.value, response_type: value.type, counterparty: value.counterparty, ...(value.terms ? { terms: serializeTerms(value.terms) } : {}), responded_at: value.respondedAt.toISOString(), recorded_at: value.recordedAt.toISOString(), recorded_by: value.recordedBy, ...(value.explanation ? { explanation: value.explanation } : {}) }; }
export function mapAcquisitionAgreementToPersistence(value: AcceptedAgreementBasis, pipelineId: string): AcquisitionAgreementBasisRow { return { pipeline_id: pipelineId, source: value.source, offer_id: value.offerId.value, ...(value.responseId ? { response_id: value.responseId.value } : {}), accepted_terms: serializeTerms(value.acceptedTerms), accepted_at: value.acceptedAt.toISOString() }; }
export function mapAcquisitionContractToPersistence(value: AcquisitionContract): AcquisitionContractRow { return { id: value.id.value, pipeline_id: value.pipelineId.value, route: value.route, status: "recorded", source: value.source, terms: serializeTerms(value.terms), recorded_by: value.recordedBy, recorded_at: value.recordedAt.toISOString() }; }
function serializeTerms<T>(value: T): T { return JSON.parse(JSON.stringify(value, (_key, item) => item instanceof Date ? item.toISOString() : item)) as T; }
