import type { InvestmentOpportunityId } from "@/features/investment-opportunity/domain";
import { AcquisitionPipeline, type AcquisitionPipelineId, type AcquisitionPipelineRepository } from "../../../domain";
import { AcquisitionPersistenceError } from "./acquisition-persistence-error";
import { mapAcquisitionPipelineCoreFromPersistence, mapAcquisitionPipelineCoreToPersistence, type AcquisitionActivityRow, type AcquisitionPipelineCoreRow, type AcquisitionStageHistoryRow } from "./acquisition-pipeline-core-mapper";

export interface SupabaseAcquisitionPipelineGateway {
  findCoreById(id: string, ownerId?: string): Promise<Readonly<{ pipeline: AcquisitionPipelineCoreRow; history: readonly AcquisitionStageHistoryRow[]; activity: readonly AcquisitionActivityRow[] }> | null>;
  findCoreByOpportunity(opportunityId: string, ownerId?: string): Promise<Readonly<{ pipeline: AcquisitionPipelineCoreRow; history: readonly AcquisitionStageHistoryRow[]; activity: readonly AcquisitionActivityRow[] }> | null>;
  insertCore(input: Readonly<{ pipeline: AcquisitionPipelineCoreRow; history: readonly AcquisitionStageHistoryRow[]; activity: readonly AcquisitionActivityRow[] }>): Promise<void>;
  updateCore(input: Readonly<{ pipeline: AcquisitionPipelineCoreRow; expectedVersion: number; history: readonly AcquisitionStageHistoryRow[]; activity: readonly AcquisitionActivityRow[] }>): Promise<"updated" | "conflict">;
}

export class SupabaseAcquisitionPipelineRepository implements AcquisitionPipelineRepository {
  public constructor(private readonly gateway: SupabaseAcquisitionPipelineGateway, private readonly ownerId?: string) {}
  public async findById(id: AcquisitionPipelineId): Promise<AcquisitionPipeline | null> { try { const bundle = await this.gateway.findCoreById(id.value, this.ownerId); return bundle ? this.restore(bundle) : null; } catch (error) { throw this.translate(error, "ACQUISITION_PERSISTENCE_READ_FAILED"); } }
  public async findByOpportunity(opportunityId: InvestmentOpportunityId): Promise<AcquisitionPipeline | null> { try { const bundle = await this.gateway.findCoreByOpportunity(opportunityId.value, this.ownerId); return bundle ? this.restore(bundle) : null; } catch (error) { throw this.translate(error, "ACQUISITION_PERSISTENCE_READ_FAILED"); } }
  public async exists(opportunityId: InvestmentOpportunityId): Promise<boolean> { return Boolean(await this.findByOpportunity(opportunityId)); }
  public async save(pipeline: AcquisitionPipeline, expectedVersion?: number): Promise<void> { const row = mapAcquisitionPipelineCoreToPersistence(pipeline, this.ownerId ?? "00000000-0000-0000-0000-000000000000"), history = pipeline.history().map(value => ({ transition_id: value.transitionId.value, pipeline_id: pipeline.id.value, ...(value.from ? { from_stage: value.from } : { from_stage: null }), to_stage: value.to, occurred_at: value.occurredAt.toISOString(), actor: value.actor, classification: value.classification, ...(value.reason ? { reason: value.reason } : {}), aggregate_version: value.aggregateVersion.value })), activity = pipeline.activity().map(value => ({ id: value.id.value, pipeline_id: pipeline.id.value, type: value.type, occurred_at: value.occurredAt.toISOString(), actor: value.actor, details: value.details, aggregate_version: value.aggregateVersion.value, ...(value.from ? { from_stage: value.from } : { from_stage: null }), to_stage: value.to })); try { const current = await this.gateway.findCoreById(pipeline.id.value, this.ownerId); if (!current) { await this.gateway.insertCore({ pipeline: row, history, activity }); return; } if (expectedVersion === undefined) throw new AcquisitionPersistenceError("ACQUISITION_PIPELINE_VERSION_CONFLICT", "Expected pipeline version is required."); const result = await this.gateway.updateCore({ pipeline: row, expectedVersion, history: history.filter(value => value.aggregate_version > expectedVersion), activity: activity.filter(value => value.aggregate_version > expectedVersion) }); if (result === "conflict") throw new AcquisitionPersistenceError("ACQUISITION_PIPELINE_VERSION_CONFLICT"); } catch (error) { if (error instanceof AcquisitionPersistenceError) throw error; throw this.translate(error, "ACQUISITION_PERSISTENCE_WRITE_FAILED"); } }
  private restore(bundle: Readonly<{ pipeline: AcquisitionPipelineCoreRow; history: readonly AcquisitionStageHistoryRow[]; activity: readonly AcquisitionActivityRow[] }>) { try { return AcquisitionPipeline.restore(mapAcquisitionPipelineCoreFromPersistence(bundle.pipeline, bundle.history, bundle.activity)); } catch (error) { if (error instanceof AcquisitionPersistenceError) throw error; throw new AcquisitionPersistenceError("ACQUISITION_PERSISTENCE_MAPPING_INVALID", "Persisted acquisition pipeline is invalid.", { cause: error } as ErrorOptions); } }
  private translate(error: unknown, code: "ACQUISITION_PERSISTENCE_READ_FAILED" | "ACQUISITION_PERSISTENCE_WRITE_FAILED") { if (error instanceof AcquisitionPersistenceError) return error; return new AcquisitionPersistenceError(code, "Acquisition persistence operation failed.", { cause: error } as ErrorOptions); }
}
