export const ACQUISITION_ERROR_CODES = [
  "INVALID_ACQUISITION_PIPELINE_ID",
  "INVALID_ACQUISITION_TRANSITION_ID",
  "INVALID_ACQUISITION_COMMAND_ID",
  "INVALID_ACQUISITION_OFFER_ID",
  "INVALID_ACQUISITION_CONTRACT_ID",
  "INVALID_COUNTERPARTY_RESPONSE_ID",
  "INVALID_ACQUISITION_STAGE",
  "INVALID_ACQUISITION_STAGE_TRANSITION",
  "ACQUISITION_TRANSITION_REASON_REQUIRED",
  "ACQUISITION_TRANSITION_EXPLANATION_REQUIRED",
  "ACQUISITION_PIPELINE_TERMINAL",
  "UNSUPPORTED_ACQUISITION_ROUTE",
  "ACQUISITION_ROUTE_MISMATCH",
  "INVALID_PIPELINE_ACTIVATION",
  "INVALID_PIPELINE_SOURCE_ANALYSIS",
  "INVALID_ACQUISITION_ACTOR",
  "INVALID_ACQUISITION_PIPELINE_VERSION",
  "INVALID_ACQUISITION_COMMAND_CONTEXT",
  "INVALID_ACQUISITION_EXIT_REASON",
  "ACQUISITION_EXIT_REASON_NOT_APPLICABLE",
  "ACQUISITION_EXIT_EXPLANATION_REQUIRED",
  "INVALID_ACQUISITION_EXIT",
  "ACQUISITION_OFFER_NOT_FOUND",
  "ACQUISITION_OFFER_ID_ALREADY_EXISTS",
  "INVALID_ACQUISITION_OFFER_SEQUENCE",
  "ACQUISITION_OFFER_ROUTE_MISMATCH",
  "ACQUISITION_OFFER_NOT_EDITABLE",
  "ACQUISITION_OFFER_ALREADY_SUBMITTED",
  "ACQUISITION_OFFER_NOT_SUBMITTABLE",
  "ACQUISITION_OFFER_EXPIRED",
  "ACQUISITION_OFFER_ALREADY_RESPONDED",
  "ACQUISITION_OFFER_SOURCE_ANALYSIS_INVALID",
  "ACQUISITION_OFFER_TERMS_INVALID",
  "ACQUISITION_OFFER_EXPIRATION_INVALID",
  "ACQUISITION_COUNTERPARTY_RESPONSE_INVALID",
  "ACQUISITION_COUNTEROFFER_INVALID",
  "ACQUISITION_ACCEPTANCE_INVALID",
  "ACQUISITION_REPLACEMENT_OFFER_INVALID",
  "ACQUISITION_CONTRACT_ALREADY_EXISTS",
  "ACQUISITION_CONTRACT_SOURCE_INVALID",
  "ACQUISITION_CONTRACT_ROUTE_MISMATCH",
  "ACQUISITION_CONTRACT_TERMS_INVALID",
  "ACQUISITION_COMMERCIAL_STAGE_REQUIREMENTS_INCOMPLETE",
  "ACQUISITION_CONTINGENCY_NOT_FOUND",
  "ACQUISITION_CONTINGENCY_ID_ALREADY_EXISTS",
  "ACQUISITION_CONTINGENCY_TYPE_NOT_APPLICABLE",
  "ACQUISITION_CONTINGENCY_SOURCE_INVALID",
  "ACQUISITION_CONTINGENCY_TRANSITION_INVALID",
  "ACQUISITION_CONTINGENCY_WAIVER_PROHIBITED",
  "ACQUISITION_CONTINGENCY_OUTCOME_INVALID",
  "DUE_DILIGENCE_ITEM_NOT_FOUND",
  "DUE_DILIGENCE_ITEM_ID_ALREADY_EXISTS",
  "DUE_DILIGENCE_CATEGORY_INVALID",
  "DUE_DILIGENCE_TRANSITION_INVALID",
  "DUE_DILIGENCE_OUTCOME_INVALID",
  "ACQUISITION_REQUIREMENT_TEMPLATE_INVALID",
  "ACQUISITION_REQUIREMENT_TEMPLATE_ALREADY_APPLIED",
  "ACQUISITION_REQUIREMENT_REFERENCE_INVALID",
  "ACQUISITION_REQUIREMENT_REOPEN_REASON_REQUIRED",
  "ACQUISITION_REQUIREMENT_WAIVER_INVALID",
  "ACQUISITION_REQUIREMENT_OUTCOME_INVALID",
  "ACQUISITION_ACTION_REFERENCE_INVALID",
  "ACQUISITION_EVIDENCE_REFERENCE_INVALID",
  "ACQUISITION_DOCUMENT_REFERENCE_INVALID",
  "ACQUISITION_CLOSING_NOT_READY",
  "ACQUISITION_CLOSING_READINESS_STALE",
  "ACQUISITION_CLOSING_OVERRIDE_PROHIBITED",
  "ACQUISITION_CLOSING_FACTS_INVALID",
  "ACQUISITION_CLOSING_ROUTE_MISMATCH",
  "ACQUISITION_CLOSING_CONTRACT_REQUIRED",
  "ACQUISITION_OPERATING_PERMISSION_UNRESOLVED",
] as const;

export type AcquisitionErrorCode = (typeof ACQUISITION_ERROR_CODES)[number];

export class AcquisitionDomainError extends Error {
  public readonly code: AcquisitionErrorCode;
  public readonly details?: Readonly<Record<string, unknown>>;

  public constructor(code: AcquisitionErrorCode, details?: Readonly<Record<string, unknown>>) {
    super(code);
    this.name = "AcquisitionDomainError";
    this.code = code;
    this.details = details;
    Object.freeze(this);
  }
}
