import Link from "next/link";
import { getGuestCommunicationInbox } from "@/app/actions/guest-communications";

export default async function GuestCommunicationsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const params = await searchParams;
  const result = await getGuestCommunicationInbox({ query: params.q, status: params.status });
  return <div className="mx-auto max-w-7xl space-y-6 py-8">
    <header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-700">Guest experience</p><h1 className="mt-2 text-3xl font-semibold text-stone-950">Guest Communication Workspace</h1><p className="mt-2 max-w-3xl text-sm text-stone-600">Conversations connect guest messages with the reservation, property, Guidebook, and operational follow-through.</p></header>
    <form className="grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_14rem_auto]">
      <label className="text-sm font-medium text-stone-700">Search<span className="sr-only"> by guest, property, reservation, or booking ID</span><input name="q" defaultValue={params.q} placeholder="Guest, property, reservation…" className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2" /></label>
      <label className="text-sm font-medium text-stone-700">Status<select name="status" defaultValue={params.status ?? ""} className="mt-1 block w-full rounded-xl border border-stone-300 px-3 py-2"><option value="">All conversations</option><option value="unread">Unread</option><option value="needs-reply">Needs reply</option><option value="waiting-on-guest">Waiting on guest</option><option value="waiting-on-host">Waiting on host</option><option value="resolved">Resolved</option><option value="archived">Archived</option></select></label>
      <button className="self-end rounded-xl bg-stone-950 px-5 py-2 text-sm font-semibold text-white">Filter</button>
    </form>
    {!result.ok ? <div role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950">Guest Communications is unavailable or you do not have access.</div> : result.conversations.length === 0 ? <div className="rounded-2xl border border-dashed border-stone-300 bg-white p-10 text-center"><h2 className="text-lg font-semibold">No conversations</h2><p className="mt-2 text-sm text-stone-600">Synced guest conversations will appear here with their reservation context.</p></div> :
      <section aria-label="Conversation inbox" className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm">{result.conversations.map(conversation => <Link key={conversation.id} href={`/dashboard/communications/${conversation.id}`} className="grid gap-2 border-b border-stone-100 p-5 outline-none last:border-0 hover:bg-stone-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-amber-600 sm:grid-cols-[1fr_1fr_auto]"><span><span className="block font-semibold text-stone-950">{conversation.guestName}</span><span className="text-sm text-stone-500">{conversation.propertyName}</span></span><span className="text-sm text-stone-600"><span className="block capitalize">{conversation.status.replaceAll("-", " ")}</span><span>{conversation.channel} · {conversation.reservation_id}</span></span><span className="text-right text-sm text-stone-500">{conversation.unread_count ? <strong className="rounded-full bg-amber-100 px-2 py-1 text-amber-900">{conversation.unread_count} unread</strong> : null}<span className="mt-2 block">{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(conversation.last_activity_at))}</span></span></Link>)}</section>}
  </div>;
}
