import type { BuildFinancialPlanningInput, FinancialPlanning, FinancialBudgetPlan, PlanningMetric, PlanningVariance, PlanValues } from "./contracts";
import { PLANNING_POLICY, PLANNING_POLICY_VERSION } from "./policies";

const metrics:readonly PlanningMetric[]=["revenue","expenses","noi","cash","capital","reserve"];
export function reviseApprovedBudget(current:FinancialBudgetPlan,revision:Omit<FinancialBudgetPlan,"version"|"revisionOf"|"status">):FinancialBudgetPlan{
  if(current.status!=="approved"&&current.status!=="superseded")throw new Error("BUDGET_REVISION_REQUIRES_APPROVED_PLAN");
  return Object.freeze({...revision,status:"draft",version:current.version+1,revisionOf:current.id,values:Object.freeze({...revision.values}),assumptions:Object.freeze([...revision.assumptions]),evidenceIds:Object.freeze([...revision.evidenceIds])});
}
function actualValues(input:BuildFinancialPlanningInput):PlanValues{const s=input.actuals.snapshot,r=s.revenue,e=s.expenses;return Object.freeze({revenue:r,expenses:e,noi:r.subtract(e)});}
function assertCurrency(currency:string,sets:readonly (PlanValues|undefined|null)[]){for(const set of sets)for(const value of Object.values(set??{}))if(value&&value.currency!==currency)throw new Error("PLANNING_CURRENCY_MISMATCH");}
export function buildVariance(actuals:PlanValues,plan:PlanValues|undefined,confidence:FinancialPlanning["confidence"],evidenceIds:readonly string[]):readonly PlanningVariance[]{
  return Object.freeze(metrics.map((metric):PlanningVariance=>{const actual=actuals[metric]??null,target=plan?.[metric]??null;if(!actual||!target)return{metric,actual,plan:target,amount:null,percentage:null,classification:"unavailable",explanation:`${metric} variance is unavailable because compatible actual and plan values are required.`,confidence:"insufficient-evidence",evidenceIds:[]};const amount=actual.subtract(target),rate=target.amount===0?null:amount.amount/Math.abs(target.amount),neutral=rate!==null&&Math.abs(rate)<=PLANNING_POLICY.neutralVarianceRate;const favorable=metric==="expenses"||metric==="capital"?amount.amount<0:amount.amount>0;return{metric,actual,plan:target,amount,percentage:rate,classification:neutral?"neutral":amount.amount===0?"neutral":favorable?"favorable":"unfavorable",explanation:`${title(metric)} is ${amount.amount===0?"on plan":`${amount.format()} ${favorable?"favorable":"unfavorable"}`} under the account-type variance policy.`,confidence,evidenceIds}}));
}
export function buildFinancialPlanning(input:BuildFinancialPlanningInput):FinancialPlanning{
  const currency=input.actuals.identity.reportingCurrency,actuals=actualValues(input);assertCurrency(currency,[actuals,input.budget?.values,input.forecast?.values,...input.scenarios.map(x=>x.values),...input.propertyPlans.flatMap(x=>[x.budget?.values,x.forecast?.values])]);
  const budgetVariance=buildVariance(actuals,input.budget?.values,input.actuals.confidence,input.budget?.evidenceIds??[]),forecastVariance=buildVariance(actuals,input.forecast?.values,input.forecast?.confidence??"insufficient-evidence",input.forecast?.evidenceIds??[]);
  const assumptions=input.forecast?.assumptions??[],assumptionCoverage=assumptions.length?assumptions.filter(x=>x.status==="confirmed"||x.status==="changed").length/assumptions.length:0,budgetCoverage=input.budget?metrics.filter(x=>input.budget?.values[x]).length/metrics.length:0,forecastCoverage=input.forecast?metrics.filter(x=>input.forecast?.values[x]).length/metrics.length:0;
  const propertyPlans=input.propertyPlans.map(item=>{const values=actualValues({...input,actuals:item.actuals});return{propertyId:item.propertyId,label:item.label,budget:item.budget?.values??null,forecast:item.forecast?.values??null,actual:values,variances:buildVariance(values,item.budget?.values,item.actuals.confidence,item.budget?.evidenceIds??[]),noiContribution:actuals.noi?.amount?values.noi!.amount/actuals.noi.amount:null,confidence:item.actuals.confidence}});
  const relevant=budgetVariance.filter(x=>x.classification!=="unavailable"),worst=relevant.reduce((max,x)=>Math.max(max,Math.abs(x.percentage??0)),0),health=!input.budget?"unavailable":worst>=PLANNING_POLICY.offPlanVarianceRate?"off-plan":worst>=PLANNING_POLICY.attentionVarianceRate?"attention-needed":worst>=PLANNING_POLICY.minorVarianceRate?"minor-variance":"on-track";
  const gaps=[...(!input.budget?["No approved budget exists."]:[]),...(!input.forecast?["No current forecast exists."]:[]),...(input.forecast&&assumptionCoverage<PLANNING_POLICY.minimumAssumptionCoverage?["Forecast assumptions are incomplete or invalidated."]:[]),...(input.actuals.evidence.expenseCoverage<PLANNING_POLICY.minimumExpenseCoverage?["Actual expense coverage is incomplete."]:[])],confidence=!input.budget&&!input.forecast?"insufficient-evidence":gaps.length>1?"low":gaps.length?"moderate":input.actuals.confidence;
  const state=!input.budget&&!input.forecast?"empty":input.permissionLimited?"permission-limited":gaps.length?"partial":input.actuals.freshness==="stale"?"degraded":"ready";
  return Object.freeze({identity:input.actuals.identity,scope:input.scope,period:input.actuals.period,budget:input.budget??null,forecast:input.forecast??null,actuals,budgetVariance,forecastVariance,scenarios:Object.freeze(input.scenarios.map(x=>({id:x.id,label:title(x.scenario),kind:x.scenario,version:x.version,values:x.values,confidence:x.confidence,assumptionCount:x.assumptions.length}))),properties:Object.freeze(propertyPlans),health,healthExplanation:health==="unavailable"?"Planning health requires an approved budget.":health==="on-track"?"Actual performance remains within planning-policy tolerance.":health==="minor-variance"?"One or more results show a minor variance from plan.":health==="attention-needed"?"A material plan variance requires investigation.":"Actual performance is materially off the approved plan.",evidence:{budgetCoverage,forecastCoverage,propertyCoverage:input.scope.propertyCount?propertyPlans.length/input.scope.propertyCount:0,assumptionCoverage,historyMonths:input.actuals.evidence.historyMonths,gaps:Object.freeze(gaps),confidence,freshness:input.actuals.freshness},confidence,freshness:input.actuals.freshness,evaluatedAt:input.actuals.evaluatedAt,projectionVersion:input.projectionVersion??PLANNING_POLICY_VERSION,state,permissionLimited:Boolean(input.permissionLimited),canEditForecast:input.canEditForecast,canApproveBudget:input.canApproveBudget});
}
function title(value:string){return value.replaceAll("-"," ").replace(/\b\w/g,x=>x.toUpperCase())}
