import { describe,expect,it,vi } from "vitest";
import { Money } from "@/platform/kernel";
import { permissionsForRole,type WorkspaceAccessContext } from "@/features/workspace";
import { buildFinancialReadModel,type FinancialSource } from "../..";
import { buildFinancialPlanning,buildVariance,evaluateForecastReadiness,reviseApprovedBudget,type BuildFinancialPlanningInput,type FinancialBudgetPlan,type FinancialForecastPlan } from ".";
const access:WorkspaceAccessContext={profileId:"p",workspaceId:"w",ownerId:"w",ownerProfileId:"p",membershipId:"m",role:"owner",status:"active",propertyAccess:{type:"all"},permissions:permissionsForRole("owner")};
const period={kind:"year" as const,from:"2026-01-01",to:"2026-12-31",reportingCalendar:"fiscal" as const};
const assumption={id:"a",type:"occupancy" as const,label:"Occupancy",value:"72%",status:"confirmed" as const,effectiveFrom:"2026-01-01",evidenceIds:["a"]};
const budget:FinancialBudgetPlan={id:"b1",scope:{type:"workspace",workspaceId:"w",label:"Workspace"},period,values:{revenue:Money.usd(100),expenses:Money.usd(50),noi:Money.usd(50),cash:Money.usd(20),capital:Money.usd(10),reserve:Money.usd(10)},assumptions:[assumption],status:"approved",version:1,approvedAt:"2025-12-01",evidenceIds:["b"]};
const forecast:FinancialForecastPlan={id:"f1",scope:budget.scope,period,values:{revenue:Money.usd(110),expenses:Money.usd(55),noi:Money.usd(55),cash:Money.usd(22)},assumptions:[assumption],status:"current",scenario:"base",version:3,confidence:"moderate",evidenceIds:["f"]};
async function fixture(overrides:Partial<BuildFinancialPlanningInput>={}):Promise<BuildFinancialPlanningInput>{const source:FinancialSource={getIdentity:vi.fn(async()=>({workspaceId:"w",organizationId:"o",reportingCurrency:"USD",fiscalYearStartMonth:1,timezone:"UTC",reportingStandards:["GAAP"],accountingMethod:"accrual" as const})),listAccounts:vi.fn(async()=>[]),listTransactions:vi.fn(async()=>[]),getSynchronization:vi.fn(async()=>({lastSuccessfulAt:"2026-07-25T00:00:00Z",expectedProviders:1,connectedProviders:1,historyMonths:18}))};const actuals=await buildFinancialReadModel(source,{access,workspaceId:"w",propertyIds:["one"],period,evaluatedAt:"2026-07-25T00:00:00Z"});const adjusted={...actuals,snapshot:{...actuals.snapshot,revenue:Money.usd(110),expenses:Money.usd(60)}};return{actuals:adjusted,scope:{type:"workspace",label:"Full Workspace",propertyIds:["one"],propertyCount:1},budget,forecast,scenarios:[forecast,{...forecast,id:"optimistic",scenario:"optimistic",version:1,values:{revenue:Money.usd(125),expenses:Money.usd(58),noi:Money.usd(67)}}],propertyPlans:[],canViewPlanning:true,canEditForecast:true,canApproveBudget:true,...overrides}}
describe("Financial Planning",()=>{
 it("keeps approved budgets immutable by creating a draft revision",()=>{const next=reviseApprovedBudget(budget,{...budget,id:"b2",values:{...budget.values,revenue:Money.usd(120)},approvedAt:undefined});expect(next.version).toBe(2);expect(next.revisionOf).toBe("b1");expect(next.status).toBe("draft");expect(budget.values.revenue?.amount).toBe(100)});
 it("applies metric-specific favorable variance",()=>{const values=buildVariance({revenue:Money.usd(110),expenses:Money.usd(40)},{revenue:Money.usd(100),expenses:Money.usd(50)},"high",[]);expect(values.find(x=>x.metric==="revenue")?.classification).toBe("favorable");expect(values.find(x=>x.metric==="expenses")?.classification).toBe("favorable")});
 it("builds budget, forecast, scenario, evidence and health separately",async()=>{const result=buildFinancialPlanning(await fixture());expect(result.actuals.revenue?.amount).toBe(110);expect(result.budget?.values.revenue?.amount).toBe(100);expect(result.forecast?.version).toBe(3);expect(result.scenarios).toHaveLength(2);expect(result.health).toBe("off-plan");expect(result.evidence.assumptionCoverage).toBe(1)});
 it("suppresses percentage variance for zero baselines",()=>{expect(buildVariance({revenue:Money.usd(10)},{revenue:Money.zero("USD")},"high",[])[0]?.percentage).toBeNull()});
 it("reports unavailable planning health without an approved budget",async()=>{const result=buildFinancialPlanning(await fixture({budget:null}));expect(result.health).toBe("unavailable");expect(result.evidence.gaps).toContain("No approved budget exists.")});
 it("returns typed incomplete readiness before forecast projection when cash and obligations are missing",async()=>{const base=await fixture(),input={...base,actuals:{...base.actuals,evidence:{...base.actuals.evidence,historyMonths:12,expenseCoverage:1}}},readiness=evaluateForecastReadiness(input),result=buildFinancialPlanning(input);expect(readiness).toMatchObject({ready:false,missing:["cash_position","recurring_obligations"],percentage:50});expect(result.state).toBe("incomplete")});
 it("accepts a canonical cash balance as cash-position readiness evidence",async()=>{const base=await fixture({cashPositionAvailable:true}),input={...base,actuals:{...base.actuals,evidence:{...base.actuals.evidence,historyMonths:12,expenseCoverage:1}}};expect(evaluateForecastReadiness(input)).toMatchObject({requirements:{cash_position:"ready"},missing:["recurring_obligations"],percentage:75})});
 it("does not crash when a property has no NOI row",async()=>{const input=await fixture(),propertyActuals={...input.actuals,snapshot:{...input.actuals.snapshot,expenses:null}};expect(()=>buildFinancialPlanning({...input,propertyPlans:[{propertyId:"one",label:"One",actuals:propertyActuals,budget:null,forecast:null}]})).not.toThrow();expect(buildFinancialPlanning({...input,propertyPlans:[{propertyId:"one",label:"One",actuals:propertyActuals}]}).properties[0]?.noiContribution).toBeNull()});
 it("rejects silent multi-currency plans",async()=>{const input=await fixture({budget:{...budget,values:{revenue:Money.of(1,"EUR")}}});expect(()=>buildFinancialPlanning(input)).toThrow("PLANNING_CURRENCY_MISMATCH")});
});
