import { describe, expect, it } from "vitest";
import { AcquisitionPipeline, AcquisitionPipelineVersion, createAcquisitionActorReference, createAcquisitionCommandId, createAcquisitionContingencyId, createDueDiligenceItemId, createPipelineActivation, buildAcquisitionClosingReadiness, PURCHASE_ACQUISITION_REQUIREMENT_TEMPLATES, isAcquisitionContingencyTypeApplicable } from "../acquisition-pipeline";
import { createInvestmentOpportunityId, createOpportunityAnalysisId } from "../domain";
const actor = createAcquisitionActorReference({ type: "user", id: "req-owner" }); const at = new Date("2026-07-22T12:00:00.000Z"); let n = 0;
function context(version: number) { n += 1; return { commandId: createAcquisitionCommandId(`acquisition-command-req-${n}`), actor, occurredAt: new Date(at.getTime() + n * 1000), expectedPipelineVersion: AcquisitionPipelineVersion.from(version) }; }
function pipeline() { return AcquisitionPipeline.activate({ opportunityId: createInvestmentOpportunityId("investment-opportunity-requirements"), route: "purchase", activation: createPipelineActivation({ activatedAt: at, activatedBy: actor, sourceAnalysis: { analysisId: createOpportunityAnalysisId("opportunity-analysis-requirements"), analysisVersion: 1, analyzedAt: at, route: "purchase" } }), context: { commandId: createAcquisitionCommandId("acquisition-command-req-start"), actor, occurredAt: at } }); }
describe("acquisition requirements and closing readiness", () => {
  it("applies exhaustive route contingency policy and stable templates", () => { expect(isAcquisitionContingencyTypeApplicable("purchase", "financing")).toBe(true); expect(isAcquisitionContingencyTypeApplicable("rental-arbitrage", "financing")).toBe(false); expect(PURCHASE_ACQUISITION_REQUIREMENT_TEMPLATES.every(value => value.version === 1)).toBe(true); });
  it("creates distinct contingencies and diligence with a relationship", () => { const value = pipeline(); const contingency = value.addContingency({ id: createAcquisitionContingencyId("acquisition-contingency-inspection"), type: "inspection", title: "Inspection", source: { type: "operator-added", explanation: "Recorded for this deal." }, blocking: true, context: context(1) }); const diligence = value.addDueDiligenceItem({ id: createDueDiligenceItemId("due-diligence-item-inspection"), category: "property-condition", title: "Inspect property", blocking: true, relatedContingencyId: contingency.id, context: context(2) }); expect(diligence.relatedContingencyId?.value).toBe(contingency.id.value); expect(value.contingencies()).toHaveLength(1); });
  it("keeps action-like work separate from requirement outcomes", () => { const value = pipeline(); const item = value.addContingency({ type: "inspection", title: "Inspection", source: { type: "operator-added", explanation: "Required." }, blocking: true, context: context(1) }); value.startContingency(item.id, context(2)); expect(value.contingencies()[0]?.status).toBe("in-progress"); value.satisfyContingency(item.id, context(3)); expect(value.contingencies()[0]?.status).toBe("satisfied"); });
  it("returns explainable not-ready and ready projections", () => { const value = pipeline(); const notReady = buildAcquisitionClosingReadiness({ pipeline: value, evaluatedAt: at }); expect(notReady.status).toBe("not-ready"); expect(notReady.blockers.some(blocker => blocker.code === "CONTRACT_MISSING")).toBe(true); });
});
