import { describe, expect, it } from "vitest";
import { createPurchaseLifecycleResult, createRentalLifecycleResult } from "@/features/investment-intelligence/application/__tests__/fixtures/investment-lifecycle.fixture";
import { buildOpportunityAnalysisSnapshot, createInvestmentOpportunity, saveOpportunityAnalysis, updateOpportunityStatus } from "../application";
import { InMemoryInvestmentOpportunityRepository } from "../infrastructure";

const analyzedAt = new Date("2026-07-22T12:00:00.000Z"), actor = { type: "user" as const, id: "00000000-0000-0000-0000-000000000001" };
const sourceSummary = { userSuppliedCount: 4, learningSuppliedCount: 0, marketSuppliedCount: 2, defaultSuppliedCount: 1, overrides: [], marketEvidenceAvailable: true } as const;
const property = { marketPropertyId: "investment-platform-purchase", normalizedAddress: { address1: "123 Main Street", city: "Mesa", state: "AZ", postalCode: "85201" }, displayAddress: "123 Main Street, Mesa, AZ 85201", resolutionStatus: "resolved" as const, capturedAt: analyzedAt };

describe("opportunity snapshot builder", () => {
  it("preserves purchase economics without recalculation", () => { const result = createPurchaseLifecycleResult(), value = buildOpportunityAnalysisSnapshot(result, analyzedAt); expect(value.route).toBe("purchase"); expect(value.financials.purchasePrice).toEqual({ ...result.analysis.property.purchasePrice, source: "user" }); expect(value.financials.projectedAdr.amount).toBe(result.analysis.revenueProjection.projectedAdr.amount); expect(value.financials.projectedOccupancy.value).toBe(result.analysis.revenueProjection.projectedOccupancy.value); expect(value.financials.capRate?.value).toBe(result.analysis.financialPerformance.capRate.value); expect(value.recommendation.recommendation).toBe(result.analysis.recommendation); expect(value.score.value).toBe(result.analysis.score.overall.value); expect(value.confidence.level).toBe(result.analysis.confidence); });
  it("preserves rental lease and excludes purchase-only metrics", () => { const result = createRentalLifecycleResult(), value = buildOpportunityAnalysisSnapshot(result, analyzedAt); expect(value.route).toBe("rental-arbitrage"); expect(value.financials.proposedMonthlyLease?.amount).toBe(result.analysis.assumptions.monthlyLease.amount); expect(value.financials.purchasePrice).toBeUndefined(); expect(value.financials.capRate).toBeUndefined(); expect(value.financials.initialCashRequired.amount).toBe(result.analysis.financialPerformance.initialCashInvested.amount); });
  it("is deterministic for an explicit analysis timestamp", () => expect(buildOpportunityAnalysisSnapshot(createPurchaseLifecycleResult(), analyzedAt)).toEqual(buildOpportunityAnalysisSnapshot(createPurchaseLifecycleResult(), analyzedAt)));
  it("does not invent unavailable market valuation or data gaps", () => { const value = buildOpportunityAnalysisSnapshot(createPurchaseLifecycleResult(), analyzedAt); expect(value.financials.estimatedMarketValue).toBeUndefined(); expect(value.dataGaps).toEqual([]); });
});

describe("opportunity application and repository", () => {
  it("creates, reloads, lists, and owner-scopes an opportunity", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const created = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt, commandId: "create-1" }); expect(created.props.name.value).toContain("Purchase"); expect((await repository.findById(created.id, created.ownerId))?.id.equals(created.id)).toBe(true); expect((await repository.list({ ownerId: created.ownerId })).items).toHaveLength(1); expect(await repository.findById(created.id, (await import("../domain")).createOpportunityOwnerId("other"))).toBeNull(); });
  it("saves immutable sequential analyses and makes the latest current", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt }); const first = await saveOpportunityAnalysis(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 1, actor, occurredAt: analyzedAt, commandId: "save-1", analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "lifecycle-1", sourceSummary, analyzedAt } }); const second = await saveOpportunityAnalysis(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 2, actor, occurredAt: analyzedAt, commandId: "save-2", analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "lifecycle-2", sourceSummary, analyzedAt } }); expect(second.props.analyses.map(value => value.sequence)).toEqual([1, 2]); expect(second.props.currentAnalysisId?.equals(second.props.analyses[1].id)).toBe(true); expect(first.props.analyses).toHaveLength(1); });
  it("rejects a duplicate canonical lifecycle result", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt }); await saveOpportunityAnalysis(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 1, actor, analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "same", sourceSummary, analyzedAt } }); await expect(saveOpportunityAnalysis(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 2, actor, analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "same", sourceSummary, analyzedAt } })).rejects.toMatchObject({ code: "ANALYSIS_ALREADY_SAVED" }); });
  it("fails stale concurrent mutations explicitly", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt }); await updateOpportunityStatus(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 1, actor, status: "researching" }); await expect(updateOpportunityStatus(repository, { authenticatedOwnerId: actor.id, opportunityId: opportunity.id, expectedVersion: 1, actor, status: "shortlisted" })).rejects.toMatchObject({ code: "CONCURRENT_OPPORTUNITY_MODIFICATION" }); });
  it("excludes archived records unless explicitly requested", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt }); opportunity.archive({ actor, occurredAt: analyzedAt }); await repository.save(opportunity, 1); expect((await repository.list({ ownerId: opportunity.ownerId })).items).toHaveLength(0); expect((await repository.list({ ownerId: opportunity.ownerId, includeArchived: true })).items).toHaveLength(1); });
  it("uses deterministic descending analysis order", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: actor.id, route: "purchase", property, actor, occurredAt: analyzedAt, initialAnalysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "one", sourceSummary, analyzedAt } }); expect((await repository.listAnalyses(opportunity.id, opportunity.ownerId)).map(value => value.sequence)).toEqual([1]); });
});
