import { renderToStaticMarkup } from "react-dom/server";
import { describe,expect,it,vi } from "vitest";
vi.mock("next/navigation",()=>({useRouter:()=>({push:vi.fn(),refresh:vi.fn()})}));
vi.mock("@/app/actions/investment-opportunity-workflow",()=>({updateOpportunityStatusAction:vi.fn()}));
import { OpportunityComparisonSelector,OpportunityComparisonWorkspace } from "../components";
import type { OpportunityComparisonView,PortfolioWorkspaceView } from "../application";

const at=new Date("2026-07-23T00:00:00Z"),card=(id:string,route:"purchase"|"rental-arbitrage"="purchase"):PortfolioWorkspaceView["opportunities"][number]=>({id,name:`Deal ${id}`,address:`${id} Main`,route,status:"evaluating",archived:false,tags:[],recommendation:"buy",score:80,scoreMaximum:100,confidence:"high",lastAnalyzedAt:at,updatedAt:at});
describe("comparison presentation",()=>{
  it("offers URL-backed selection for analyzed opportunities",()=>{const html=renderToStaticMarkup(<OpportunityComparisonSelector opportunities={[card("a"),card("b"),card("c","rental-arbitrage")]}/>);expect(html).toContain("Select 2–4 analyzed opportunities");expect(html).toContain("Deal a");expect(html).toContain("Compare")});
  it("renders ranking policy, source differences, risks, and navigation",()=>{const candidates=["a","b"].map((id,index)=>({id,name:`Deal ${id}`,address:`${id} Main`,route:"purchase" as const,status:"evaluating" as const,canShortlist:true,aggregateVersion:2,analysisId:`analysis-${id}`,analysisSequence:1,recommendation:"buy",score:80-index,confidence:"high",analyzedAt:at,stale:index===1,metrics:{purchasePrice:{value:400000+index*10000,source:"user" as const,format:"money" as const},estimatedMarketValue:{value:450000,source:"market" as const,format:"money" as const},cashOnCashReturn:{value:12-index,source:"derived" as const,format:"percentage" as const},annualCashFlow:{value:15000,source:"derived" as const,format:"money" as const},initialCashRequired:{value:80000,source:"derived" as const,format:"money" as const}},assumptions:[],risks:[{title:"Regulation",severity:"high"}],dataGaps:index?[{code:"GAP",description:"Missing"}]:[],evidenceCount:3})),view:OpportunityComparisonView={route:"purchase",candidates,ranks:candidates.map((value,index)=>({opportunityId:value.id,rank:index+1,compositeScore:80-index,summary:"Explainable summary",strengths:["Strength"],tradeoffs:["Tradeoff"]})),highlights:["Deal a requires the least initial capital."],assumptionDifferences:[{key:"occupancy",label:"Occupancy",sourceDifference:true,values:[{opportunityId:"a",value:72,source:"user",analyzedAt:at},{opportunityId:"b",value:65,source:"market",analyzedAt:at}]}],rankingPolicy:{version:"1",weights:{investmentScore:.35,confidence:.15,cashOnCashReturn:.2,annualCashFlow:.1,capitalEfficiency:.1,riskBurden:.05,dataCompleteness:.05}}};const html=renderToStaticMarkup(<OpportunityComparisonWorkspace view={view}/>);expect(html).toContain("Rank #1");expect(html).toContain("Sources differ");expect(html).toContain("Published ranking policy");expect(html).toContain("Stale");expect(html).toContain("Regulation");expect(html).toContain(`/dashboard/investments/portfolio/a`)});
});
