import { describe,expect,it } from "vitest";
import { createPurchaseLifecycleResult,createRentalLifecycleResult } from "@/features/investment-intelligence/application/__tests__/fixtures/investment-lifecycle.fixture";
import { assessComparisonCompatibility,buildOpportunityAnalysisSnapshot,buildOpportunityComparisonView,createInvestmentOpportunity,rankOpportunities,saveOpportunityAnalysis } from "../application";
import { InMemoryInvestmentOpportunityRepository } from "../infrastructure";
import type { InvestmentLifecycleResult } from "@/features/investment-intelligence";
import type { OpportunityAnalysisSnapshot } from "../domain";

const ownerId="owner-compare",actor={type:"user" as const,id:ownerId},at=new Date("2026-07-23T12:00:00Z"),sourceSummary={userSuppliedCount:2,learningSuppliedCount:0,marketSuppliedCount:2,defaultSuppliedCount:1,overrides:[],marketEvidenceAvailable:true} as const;
async function analyzed(repository:InMemoryInvestmentOpportunityRepository,input:{name:string;route:"purchase"|"rental-arbitrage";score:number;cashReturn:number;cashFlow:number;initialCash:number;confidence?:string;gaps?:number;source?:"user"|"market";marketValue?:number}){const result:InvestmentLifecycleResult=input.route==="purchase"?createPurchaseLifecycleResult():createRentalLifecycleResult(),subject=result.analysis.property,property={marketPropertyId:subject.id,normalizedAddress:{address1:subject.location.address1,city:subject.location.city,state:subject.location.state,postalCode:subject.location.postalCode},displayAddress:`${subject.location.address1}, ${subject.location.city}`,resolutionStatus:"resolved" as const,capturedAt:at},opportunity=await createInvestmentOpportunity(repository,{authenticatedOwnerId:ownerId,actor,name:input.name,route:input.route,property,occurredAt:at}),base=buildOpportunityAnalysisSnapshot(result,at),snapshot:OpportunityAnalysisSnapshot={...base,score:{...base.score,value:input.score},confidence:{level:input.confidence??"high"},financials:{...base.financials,cashOnCashReturn:{value:input.cashReturn,source:"derived"},annualCashFlow:{amount:input.cashFlow,currency:"USD",source:"derived"},initialCashRequired:{amount:input.initialCash,currency:"USD",source:"derived"},projectedOccupancy:{...base.financials.projectedOccupancy,source:input.source??"user"},...(input.marketValue!==undefined?{estimatedMarketValue:{amount:input.marketValue,currency:"USD",source:"market" as const}}:{})},dataGaps:Array.from({length:input.gaps??0},(_,index)=>({code:`GAP_${index}`,description:"Missing evidence"}))};return saveOpportunityAnalysis(repository,{authenticatedOwnerId:ownerId,actor,opportunityId:opportunity.id,expectedVersion:1,analysis:{lifecycleResult:result,lifecycleResultId:`run-${input.name}`,sourceSummary,snapshot,analyzedAt:at}})}

describe("comparison compatibility",()=>{
  it("requires two to four accessible opportunities",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),one=await analyzed(repository,{name:"One",route:"purchase",score:80,cashReturn:10,cashFlow:10000,initialCash:100000});expect(assessComparisonCompatibility([one]).reasons).toContain("TOO_FEW_OPPORTUNITIES");expect(assessComparisonCompatibility([one,one,one,one,one]).reasons).toContain("TOO_MANY_OPPORTUNITIES");expect(assessComparisonCompatibility([one,null]).reasons).toContain("OPPORTUNITY_NOT_ACCESSIBLE")});
  it("rejects route mismatch, archives, and missing current analysis",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),purchase=await analyzed(repository,{name:"Purchase",route:"purchase",score:80,cashReturn:10,cashFlow:10000,initialCash:100000}),rental=await analyzed(repository,{name:"Rental",route:"rental-arbitrage",score:75,cashReturn:12,cashFlow:12000,initialCash:30000}),empty=await createInvestmentOpportunity(repository,{authenticatedOwnerId:ownerId,actor,name:"Empty",route:"purchase",property:purchase.props.property,occurredAt:at});expect(assessComparisonCompatibility([purchase,rental]).reasons).toContain("PURCHASE_RENTAL_ROUTE_MISMATCH");expect(assessComparisonCompatibility([purchase,empty]).reasons).toContain("MISSING_CURRENT_ANALYSIS");purchase.archive({actor,occurredAt:at});expect(assessComparisonCompatibility([purchase,empty]).reasons).toContain("ARCHIVED_OPPORTUNITY")});
});

describe("comparison projection and ranking",()=>{
  it("preserves financial distinctions and source-aware assumptions",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),a=await analyzed(repository,{name:"Alpha",route:"purchase",score:82,cashReturn:11,cashFlow:18000,initialCash:90000,source:"user",marketValue:500000}),b=await analyzed(repository,{name:"Bravo",route:"purchase",score:78,cashReturn:14,cashFlow:16000,initialCash:70000,source:"market",marketValue:475000}),view=await buildOpportunityComparisonView(repository,{ownerId,opportunityIds:[a.id.value,b.id.value],now:at});expect(view.candidates[0].metrics.purchasePrice.value).toBe(425000);expect(view.candidates[0].metrics.estimatedMarketValue.value).toBe(500000);expect(view.assumptionDifferences.find(value=>value.key==="projectedOccupancy")?.sourceDifference).toBe(true);expect(view.highlights.some(value=>value.includes("least initial capital"))).toBe(true)});
  it("uses the published multi-factor policy and explains tradeoffs",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),highScore=await analyzed(repository,{name:"Risky",route:"purchase",score:95,cashReturn:4,cashFlow:5000,initialCash:160000,confidence:"low",gaps:5}),efficient=await analyzed(repository,{name:"Efficient",route:"purchase",score:84,cashReturn:18,cashFlow:24000,initialCash:60000,confidence:"high",gaps:0}),view=await buildOpportunityComparisonView(repository,{ownerId,opportunityIds:[highScore.id.value,efficient.id.value],now:at}),winner=view.ranks[0];expect(winner.opportunityId).toBe(efficient.id.value);expect(winner.strengths).toContain("Strongest cash-on-cash return");expect(view.ranks.find(value=>value.opportunityId===highScore.id.value)?.tradeoffs).toContain("Lower-confidence analysis");expect(view.rankingPolicy.weights.investmentScore).toBe(.35)});
  it("marks analyses older than ninety days stale",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),a=await analyzed(repository,{name:"A",route:"purchase",score:80,cashReturn:10,cashFlow:10000,initialCash:100000}),b=await analyzed(repository,{name:"B",route:"purchase",score:81,cashReturn:11,cashFlow:11000,initialCash:90000}),view=await buildOpportunityComparisonView(repository,{ownerId,opportunityIds:[a.id.value,b.id.value],now:new Date("2027-01-01T00:00:00Z")});expect(view.candidates.every(value=>value.stale)).toBe(true)});
  it("returns a safe inaccessible error for another owner",async()=>{const repository=new InMemoryInvestmentOpportunityRepository(),a=await analyzed(repository,{name:"A",route:"purchase",score:80,cashReturn:10,cashFlow:10000,initialCash:100000}),b=await analyzed(repository,{name:"B",route:"purchase",score:81,cashReturn:11,cashFlow:11000,initialCash:90000});await expect(buildOpportunityComparisonView(repository,{ownerId:"other",opportunityIds:[a.id.value,b.id.value]})).rejects.toMatchObject({reasons:["OPPORTUNITY_NOT_ACCESSIBLE"]})});
  it("uses stable IDs as the final ranking tie breaker",()=>{const base={route:"purchase" as const,status:"evaluating" as const,canShortlist:true,aggregateVersion:1,analysisId:"analysis",analysisSequence:1,recommendation:"buy",score:80,confidence:"high",analyzedAt:at,stale:false,metrics:{cashOnCashReturn:{value:10,format:"percentage" as const},annualCashFlow:{value:10000,format:"money" as const},initialCashRequired:{value:100000,format:"money" as const}},assumptions:[],risks:[],dataGaps:[],evidenceCount:1,address:"Address"};expect(rankOpportunities([{...base,id:"b",name:"B"},{...base,id:"a",name:"A"}]).map(value=>value.opportunityId)).toEqual(["a","b"])});
});
