import { describe, expect, it } from "vitest";
import { createPurchaseLifecycleResult } from "@/features/investment-intelligence/application/__tests__/fixtures/investment-lifecycle.fixture";
import { createInvestmentOpportunity, loadOpportunityDetail, loadPortfolioWorkspace, saveOpportunityAnalysis, updateOpportunityStatus } from "../application";
import { InMemoryInvestmentOpportunityRepository } from "../infrastructure";

const ownerId = "00000000-0000-0000-0000-000000000001", actor = { type: "user" as const, id: ownerId }, at = new Date("2026-07-22T12:00:00.000Z"), sourceSummary = { userSuppliedCount: 1, learningSuppliedCount: 0, marketSuppliedCount: 2, defaultSuppliedCount: 0, overrides: [], marketEvidenceAvailable: true } as const;
const property = (id: number) => ({ marketPropertyId: `property-${id}`, normalizedAddress: { address1: `${id} Main Street`, city: "Mesa", state: "AZ", postalCode: `8520${id}` }, displayAddress: `${id} Main Street, Mesa, AZ 8520${id}`, resolutionStatus: "resolved" as const, capturedAt: at });
async function opportunity(repository: InMemoryInvestmentOpportunityRepository, id: number, tags: readonly string[] = []) { return createInvestmentOpportunity(repository, { authenticatedOwnerId: ownerId, name: `Deal ${id}`, route: id % 2 ? "purchase" : "rental-arbitrage", property: property(id), tags, actor, occurredAt: new Date(at.getTime() + id) }); }

describe("portfolio workspace query", () => {
  it("projects top metrics and deterministic cards", async () => { const repository = new InMemoryInvestmentOpportunityRepository(), one = await opportunity(repository, 1), two = await opportunity(repository, 2); await updateOpportunityStatus(repository, { authenticatedOwnerId: ownerId, opportunityId: one.id, expectedVersion: 1, actor, occurredAt: new Date(at.getTime() + 10), status: "researching" }); await updateOpportunityStatus(repository, { authenticatedOwnerId: ownerId, opportunityId: two.id, expectedVersion: 1, actor, occurredAt: new Date(at.getTime() + 20), status: "shortlisted" }); const view = await loadPortfolioWorkspace(repository, ownerId); expect(view.metrics).toMatchObject({ researching: 1, shortlisted: 1, evaluating: 0 }); expect(view.opportunities.map(item => item.name)).toEqual(["Deal 2", "Deal 1"]); });
  it("filters by status, route, search text, and tags", async () => { const repository = new InMemoryInvestmentOpportunityRepository(), one = await opportunity(repository, 1, ["Value Add"]); await opportunity(repository, 2); await updateOpportunityStatus(repository, { authenticatedOwnerId: ownerId, opportunityId: one.id, expectedVersion: 1, actor, status: "researching" }); expect((await loadPortfolioWorkspace(repository, ownerId, { statuses: ["researching"] })).opportunities).toHaveLength(1); expect((await loadPortfolioWorkspace(repository, ownerId, { route: "rental-arbitrage" })).opportunities[0].name).toBe("Deal 2"); expect((await loadPortfolioWorkspace(repository, ownerId, { search: "value add" })).opportunities[0].name).toBe("Deal 1"); expect((await loadPortfolioWorkspace(repository, ownerId, { search: "not found" })).empty).toBe(true); });
  it("excludes archived by default while retaining metrics behavior", async () => { const repository = new InMemoryInvestmentOpportunityRepository(), value = await opportunity(repository, 1); value.archive({ actor, occurredAt: at }); await repository.save(value, 1); expect((await loadPortfolioWorkspace(repository, ownerId)).opportunities).toHaveLength(0); expect((await loadPortfolioWorkspace(repository, ownerId, { includeArchived: true })).opportunities).toHaveLength(1); });
  it("paginates after applying presentation filters", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); await opportunity(repository, 1); await opportunity(repository, 2); await opportunity(repository, 3); const first = await loadPortfolioWorkspace(repository, ownerId, { limit: 2 }); expect(first.opportunities).toHaveLength(2); expect(first.nextCursor).toBe("2"); const second = await loadPortfolioWorkspace(repository, ownerId, { limit: 2, cursor: first.nextCursor }); expect(second.opportunities).toHaveLength(1); });
  it("projects current analysis values onto cards", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const value = await createInvestmentOpportunity(repository, { authenticatedOwnerId: ownerId, route: "purchase", property: { ...property(1), marketPropertyId: "investment-platform-purchase" }, actor, occurredAt: at }); await saveOpportunityAnalysis(repository, { authenticatedOwnerId: ownerId, opportunityId: value.id, expectedVersion: 1, actor, analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "lifecycle-1", sourceSummary, analyzedAt: at } }); const card = (await loadPortfolioWorkspace(repository, ownerId)).opportunities[0]; expect(card.recommendation).toBe(createPurchaseLifecycleResult().analysis.recommendation); expect(card.score).toBeTypeOf("number"); expect(card.lastAnalyzedAt).toEqual(at); });
});

describe("opportunity detail query", () => {
  it("returns overview, current version, history, tags, and newest activity first", async () => { const repository = new InMemoryInvestmentOpportunityRepository(); const value = await createInvestmentOpportunity(repository, { authenticatedOwnerId: ownerId, route: "purchase", property: { ...property(1), marketPropertyId: "investment-platform-purchase" }, tags: ["Texas"], actor, occurredAt: at }); const first = await saveOpportunityAnalysis(repository, { authenticatedOwnerId: ownerId, opportunityId: value.id, expectedVersion: 1, actor, occurredAt: new Date(at.getTime() + 1), analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "one", sourceSummary, analyzedAt: at } }); await saveOpportunityAnalysis(repository, { authenticatedOwnerId: ownerId, opportunityId: value.id, expectedVersion: 2, actor, occurredAt: new Date(at.getTime() + 2), analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "two", sourceSummary, analyzedAt: new Date(at.getTime() + 2) } }); const detail = await loadOpportunityDetail(repository, ownerId, first.id); expect(detail?.latestAnalysis?.sequence).toBe(2); expect(detail?.previousAnalyses.map(item => item.sequence)).toEqual([1]); expect(detail?.tags).toEqual(["Texas"]); expect(detail?.activity[0].type).toBe("analysis-saved"); });
  it("returns null for another owner", async () => { const repository = new InMemoryInvestmentOpportunityRepository(), value = await opportunity(repository, 1); expect(await loadOpportunityDetail(repository, "another-owner", value.id)).toBeNull(); });
});
