import { describe, expect, it } from "vitest";
import { createPurchaseLifecycleResult } from "@/features/investment-intelligence/application/__tests__/fixtures/investment-lifecycle.fixture";
import { addOpportunityNote, buildInvestmentDecisionLineageGraph, buildOpportunityAnalysisDetailView, buildOpportunityReanalysisInput, createInvestmentOpportunity, getAllowedOpportunityStatusTransitions, listCompatibleInvestmentOpportunities, projectOpportunityActivityTimeline, readImmutableAnalysis, saveOpportunityAnalysis } from "../application";
import { InMemoryInvestmentOpportunityRepository, InMemoryOpportunityNoteRepository } from "../infrastructure";

const ownerId = "owner-1", actor = { type: "user" as const, id: ownerId }, at = new Date("2026-07-23T12:00:00Z"), sourceSummary = { userSuppliedCount: 2, learningSuppliedCount: 0, marketSuppliedCount: 2, defaultSuppliedCount: 1, overrides: [], marketEvidenceAvailable: true } as const;
const property = { marketPropertyId: "investment-platform-purchase", normalizedAddress: { address1: "123 Main Street", city: "Mesa", state: "AZ", postalCode: "85201" }, displayAddress: "123 Main Street, Mesa, AZ 85201", resolutionStatus: "resolved" as const, capturedAt: at };
async function setup() { const repository = new InMemoryInvestmentOpportunityRepository(), opportunity = await createInvestmentOpportunity(repository, { authenticatedOwnerId: ownerId, actor, route: "purchase", property, occurredAt: at, tags: ["Value Add"] }); return { repository, opportunity }; }

describe("IA-001C workflow projections", () => {
  it("lists only compatible active opportunities", async () => { const { repository, opportunity } = await setup(); const values = await listCompatibleInvestmentOpportunities(repository, { ownerId, route: "purchase", property }); expect(values.map(value => value.id)).toEqual([opportunity.id.value]); expect(await listCompatibleInvestmentOpportunities(repository, { ownerId, route: "rental-arbitrage", property })).toEqual([]); });
  it("projects allowed transitions from the domain policy", async () => { const { opportunity } = await setup(); expect(getAllowedOpportunityStatusTransitions(opportunity)).toEqual(["researching", "shortlisted", "rejected"]); opportunity.archive({ actor, occurredAt: at }); expect(getAllowedOpportunityStatusTransitions(opportunity)).toEqual([]); });
  it("builds linkable immutable analysis detail", async () => { const { repository, opportunity } = await setup(); const saved = await saveOpportunityAnalysis(repository, { authenticatedOwnerId: ownerId, actor, opportunityId: opportunity.id, expectedVersion: 1, analysis: { lifecycleResult: createPurchaseLifecycleResult(), lifecycleResultId: "run-1", sourceSummary, analyzedAt: at } }); const analysis = saved.props.analyses[0], view = await buildOpportunityAnalysisDetailView(repository, { ownerId, opportunityId: saved.id.value, analysisId: analysis.id.value }); expect(view?.sequence).toBe(1); expect(view?.recommendation.recommendation).toBe(analysis.props.resultSnapshot.recommendation.recommendation); expect(view?.financials.purchasePrice?.amount).toBe(425000); });
  it("restores only persisted user assumptions for reanalysis", async () => { const { repository, opportunity } = await setup(); const result = createPurchaseLifecycleResult(), snapshot = { ...(await import("../application")).buildOpportunityAnalysisSnapshot(result, at), reanalysis: { userAssumptions: { "purchase-price": 425000, "projected-adr": 210 } } }; await saveOpportunityAnalysis(repository, { authenticatedOwnerId: ownerId, actor, opportunityId: opportunity.id, expectedVersion: 1, analysis: { lifecycleResult: result, lifecycleResultId: "run-1", sourceSummary, snapshot, analyzedAt: at } }); const input = await buildOpportunityReanalysisInput(repository, { ownerId, opportunityId: opportunity.id.value }); expect(input?.userAssumptions).toEqual({ "purchase-price": 425000, "projected-adr": 210 }); expect(input?.userAssumptions).not.toHaveProperty("recommendation"); expect(input?.userAssumptions).not.toHaveProperty("cap-rate"); });
  it("hydrates every source-labelled saved assumption and records reanalysis parent lineage",async()=>{const{repository,opportunity}=await setup(),result=createPurchaseLifecycleResult(),base=(await import("../application")).buildOpportunityAnalysisSnapshot(result,at),snapshot={...base,assumptions:[{key:"purchase-price",value:425000,source:"user"},{key:"annual-insurance-premium",value:1800,source:"system-default"},{key:"projected-adr",value:225,source:"market"}],reanalysis:{userAssumptions:{"purchase-price":425000}}};const first=await saveOpportunityAnalysis(repository,{authenticatedOwnerId:ownerId,actor,opportunityId:opportunity.id,expectedVersion:1,analysis:{lifecycleResult:result,lifecycleResultId:"run-1",sourceSummary,snapshot,analyzedAt:at}});const hydrated=await buildOpportunityReanalysisInput(repository,{ownerId,opportunityId:opportunity.id.value});expect(hydrated?.savedAssumptions).toEqual({"purchase-price":425000,"annual-insurance-premium":1800,"projected-adr":225});expect(hydrated?.assumptionSources["projected-adr"]).toBe("market");const second=await saveOpportunityAnalysis(repository,{authenticatedOwnerId:ownerId,actor,opportunityId:first.id,expectedVersion:2,analysis:{lifecycleResult:result,lifecycleResultId:"run-2",sourceSummary,snapshot,analyzedAt:new Date(at.getTime()+1)}});expect(second.props.analyses[1].props.lineage.sourceAnalysisVersionId).toBe(first.props.analyses[0].id.value);expect(first.props.analyses).toHaveLength(1);});
  it("attaches analysis activity to the exact immutable version",async()=>{const{repository,opportunity}=await setup(),saved=await saveOpportunityAnalysis(repository,{authenticatedOwnerId:ownerId,actor,opportunityId:opportunity.id,expectedVersion:1,analysis:{lifecycleResult:createPurchaseLifecycleResult(),lifecycleResultId:"lineage-run",sourceSummary,analyzedAt:at}}),analysis=saved.props.analyses[0],activity=saved.props.activities.find(item=>item.type==="analysis-saved");expect(activity?.analysisVersionId?.value).toBe(analysis.id.value);expect(activity?.details.analysisId).toBe(analysis.id.value);});
  it("builds a navigable immutable downstream graph and rejects cross-version artifacts",async()=>{const{repository,opportunity}=await setup(),saved=await saveOpportunityAnalysis(repository,{authenticatedOwnerId:ownerId,actor,opportunityId:opportunity.id,expectedVersion:1,analysis:{lifecycleResult:createPurchaseLifecycleResult(),lifecycleResultId:"graph-run",sourceSummary,analyzedAt:at}}),analysis=saved.props.analyses[0],projection=(await readImmutableAnalysis(repository,{ownerId,opportunityId:saved.id.value,analysisVersionId:analysis.id.value}))!,artifact={kind:"report" as const,id:"report-1",opportunityId:saved.id.value,analysisVersionId:analysis.id.value,createdAt:at.toISOString()},graph=buildInvestmentDecisionLineageGraph(projection,[artifact]);expect(graph.artifacts[0].sourceAnalysisPath).toContain(analysis.id.value);expect(graph.recommendation).toEqual(projection.snapshot.recommendation);expect(()=>buildInvestmentDecisionLineageGraph(projection,[{...artifact,analysisVersionId:"other"}])).toThrow("DOWNSTREAM_LINEAGE_MISMATCH");});
  it("formats activity deterministically without note bodies", async () => { const { opportunity } = await setup(); opportunity.transitionStatus("researching", { actor, occurredAt: new Date(at.getTime() + 1) }); const timeline = projectOpportunityActivityTimeline(opportunity.props.activities); expect(timeline[0]).toMatchObject({ title: "Status changed", detail: "Evaluating → Researching" }); expect(JSON.stringify(timeline)).not.toContain("note body"); });
});

describe("Opportunity notes", () => {
  it("validates, stores, and orders plain text notes", async () => { const repository = new InMemoryOpportunityNoteRepository(); repository.setVersion("investment-opportunity-note-test", 1); const first = await addOpportunityNote(repository, { opportunityId: "investment-opportunity-note-test", ownerId, actor, expectedVersion: 1, commandId: "command-one", body: "  Follow up with broker.  ", occurredAt: at }); expect(first.note.body.value).toBe("Follow up with broker."); const second = await addOpportunityNote(repository, { opportunityId: "investment-opportunity-note-test", ownerId, actor, expectedVersion: 2, commandId: "command-two", body: "Review lease terms", occurredAt: new Date(at.getTime() + 1) }); expect((await repository.list("investment-opportunity-note-test", ownerId)).map(note => note.id.value)).toEqual([second.note.id.value, first.note.id.value]); });
  it("rejects blank, oversized, and stale notes", async () => { const repository = new InMemoryOpportunityNoteRepository(); repository.setVersion("investment-opportunity-note-test", 2); await expect(addOpportunityNote(repository, { opportunityId: "investment-opportunity-note-test", ownerId, actor, expectedVersion: 2, commandId: "command-one", body: " " })).rejects.toMatchObject({ code: "INVALID_OPPORTUNITY_NOTE" }); await expect(addOpportunityNote(repository, { opportunityId: "investment-opportunity-note-test", ownerId, actor, expectedVersion: 2, commandId: "command-two", body: "x".repeat(5001) })).rejects.toMatchObject({ code: "INVALID_OPPORTUNITY_NOTE" }); await expect(addOpportunityNote(repository, { opportunityId: "investment-opportunity-note-test", ownerId, actor, expectedVersion: 1, commandId: "command-three", body: "Valid" })).rejects.toMatchObject({ code: "CONCURRENT_OPPORTUNITY_MODIFICATION" }); });
});
