import type { AcquisitionMoney, LeaseTerm, UtilityResponsibility, RentalConcession } from "../offers/acquisition-offer-terms";
import { AcquisitionDomainError } from "../errors";
export type PurchaseContractFinancing = Readonly<{ type: "cash" } | { type: "financed"; financingContingency: boolean; plannedDownPayment?: AcquisitionMoney }>;
export type PurchaseContractCondition = Readonly<{ type: string; explanation?: string }>;
export type PurchaseAcquisitionContractTerms = Readonly<{ route: "purchase"; contractPrice: AcquisitionMoney; earnestMoney?: AcquisitionMoney; financing: PurchaseContractFinancing; sellerConcessions?: AcquisitionMoney; effectiveDate: Date; scheduledClosingDate: Date; agreedConditions: readonly PurchaseContractCondition[] }>;
export type RentalOperatingPermission = Readonly<{ status: "explicitly-authorized"; form: "lease-clause" | "written-addendum" | "separate-authorization"; reference?: string } | { status: "not-authorized" } | { status: "unclear"; explanation: string }>;
export type PurchaseOrRentalCondition = Readonly<{ type: string; explanation?: string }>;
export type RentalArbitrageAcquisitionContractTerms = Readonly<{ route: "rental-arbitrage"; contractedMonthlyRent: AcquisitionMoney; securityDeposit?: AcquisitionMoney; leaseTerm: LeaseTerm; effectiveDate: Date; commencementDate: Date; possessionDate?: Date; operatingPermission: RentalOperatingPermission; utilityResponsibilities: readonly UtilityResponsibility[]; agreedConcessions: readonly RentalConcession[]; agreedConditions: readonly PurchaseOrRentalCondition[] }>;
export type AcquisitionContractTerms = PurchaseAcquisitionContractTerms | RentalArbitrageAcquisitionContractTerms;
export function validateAcquisitionContractTerms(terms: AcquisitionContractTerms): void { const dates = terms.route === "purchase" ? [terms.effectiveDate, terms.scheduledClosingDate] : [terms.effectiveDate, terms.commencementDate, terms.possessionDate]; if (dates.some(date => date !== undefined && Number.isNaN(date.getTime())) || terms.route === "purchase" && terms.scheduledClosingDate < terms.effectiveDate || terms.route === "rental-arbitrage" && terms.commencementDate < terms.effectiveDate) throw new AcquisitionDomainError("ACQUISITION_CONTRACT_TERMS_INVALID"); const money = terms.route === "purchase" ? terms.contractPrice : terms.contractedMonthlyRent; if (money.amount <= 0 || money.currency !== "USD") throw new AcquisitionDomainError("ACQUISITION_CONTRACT_TERMS_INVALID"); if (terms.route === "rental-arbitrage" && terms.operatingPermission.status === "unclear" && !terms.operatingPermission.explanation.trim()) throw new AcquisitionDomainError("ACQUISITION_CONTRACT_TERMS_INVALID"); }
