import{listCanonicalLearningCandidates}from"@/app/actions/platform-learning-workspace";
import{Empty,LearningHeader}from"@/components/learning/learning-workspace-ui";
import{validateCanonicalLearningCandidateAction}from"@/app/actions/canonical-learning";
export default async function LearningCandidatesPage({searchParams}:{searchParams:Promise<{workspace?:string;error?:string;correlation?:string;validated?:string}>}){
  const{workspace,error,correlation,validated}=await searchParams,candidates=await listCanonicalLearningCandidates(workspace);
  return <main className="mx-auto max-w-6xl space-y-8 px-5 py-10"><LearningHeader title="Candidate Learnings" description="Potential lessons generated from complete observation, decision, execution, measured-outcome, and review lineage. Candidates are not organizational knowledge until validated."/>
    {error?<p role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">The candidate was not validated ({error}). Correlation: {correlation}</p>:validated?<p className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Validated learning was published as a new immutable version.</p>:null}
    {candidates.length?<section className="grid gap-4 lg:grid-cols-2">{candidates.map(candidate=><article className="rounded-2xl border bg-white p-6" key={candidate.id}><div className="flex justify-between gap-4"><p className="text-xs font-semibold uppercase text-teal-700">{candidate.category}</p><p className="text-xs capitalize text-stone-500">{candidate.status}</p></div><h2 className="mt-3 text-lg font-semibold">{candidate.statement}</h2><p className="mt-3 text-sm text-stone-600">Confidence {String((candidate.confidence as{level?:unknown}).level??"unavailable")} · generated {new Date(candidate.createdAt).toLocaleDateString()}</p><form action={validateCanonicalLearningCandidateAction} className="mt-5 space-y-3"><input type="hidden" name="workspaceId" value={candidate.workspaceId}/><input type="hidden" name="candidateId" value={candidate.id}/><label className="block text-sm font-semibold">Future decision guidance<textarea required minLength={10} maxLength={2000} name="futureGuidance" className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal" placeholder="How should future decisions change because of this outcome?"/></label><button className="rounded-full bg-stone-950 px-4 py-2 text-sm font-semibold text-white">Validate learning</button></form><p className="mt-4 text-xs text-stone-500">Validation preserves this candidate and publishes a new immutable learning version.</p></article>)}</section>:<Empty title="No candidate learnings" detail="Candidates are generated after measurable outcomes complete the governed HPM learning cycle."/>}
  </main>
}
