import Link from "next/link";
import { getReportComparisonWorkspace } from "@/app/actions/reporting";

export default async function ReportComparisonPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const params=await searchParams,a=single(params.a),b=single(params.b),workspace=await getReportComparisonWorkspace(a,b);
  if(!workspace)return <main className="p-8">Sign in to compare reports.</main>;
  return <main className="mx-auto max-w-6xl space-y-8 px-5 py-10"><header><Link href="/dashboard/reports">← Reports Library</Link><h1 className="mt-5 text-4xl font-semibold">Compare report versions</h1><p className="mt-3 text-stone-600">Human-readable changes between two immutable reports in the same series.</p></header><form className="grid gap-4 rounded-2xl border p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><Select label="Report A" name="a" value={a} reports={workspace.reports}/><Select label="Report B" name="b" value={b} reports={workspace.reports}/><button className="rounded-full bg-stone-950 px-5 py-3 font-semibold text-white">Compare</button></form>{workspace.error?<p role="alert" className="rounded-xl bg-amber-50 p-4">{workspace.error}</p>:null}{workspace.comparison?<div className="space-y-6"><section className="rounded-2xl border p-5"><h2 className="text-2xl font-semibold">Executive summary</h2><Change label="Summary" before={workspace.comparison.summary.before} after={workspace.comparison.summary.after}/><div className="mt-4 grid gap-3 sm:grid-cols-2"><Change label="Confidence" before={workspace.comparison.confidence.before} after={workspace.comparison.confidence.after}/><Change label="Freshness" before={workspace.comparison.freshness.before} after={workspace.comparison.freshness.after}/></div></section><section className="rounded-2xl border p-5"><h2 className="text-2xl font-semibold">Metric changes</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-3">Metric</th><th className="p-3">Before</th><th className="p-3">After</th><th className="p-3">Change</th></tr></thead><tbody>{workspace.comparison.metrics.map(item=><tr className="border-t" key={item.key}><td className="p-3 font-semibold">{item.label}</td><td className="p-3">{item.before}</td><td className="p-3">{item.after}</td><td className="p-3 capitalize">{item.state.replaceAll("-"," ")}{item.percentChange!==undefined?` · ${item.percentChange>0?"+":""}${item.percentChange.toFixed(1)}%`:""}</td></tr>)}</tbody></table></div></section><section className="grid gap-4 sm:grid-cols-2"><Change label="Recommendation" before={workspace.comparison.recommendation.before} after={workspace.comparison.recommendation.after}/><Change label="Risks" before={workspace.comparison.risks.before} after={workspace.comparison.risks.after}/></section></div>:<p className="rounded-2xl border p-8 text-center text-stone-600">Select two versions from the same report history.</p>}</main>;
}
function Select({label,name,value,reports}:{label:string;name:string;value?:string;reports:readonly {id:string;report_number:string;title:string;version_number:number}[]}){return <label className="text-sm font-semibold">{label}<select className="mt-2 w-full rounded-xl border p-3" name={name} defaultValue={value??""}><option value="">Choose a report</option>{reports.map(report=><option key={report.id} value={report.id}>{report.title} · v{report.version_number} · {report.report_number}</option>)}</select></label>;}
function Change({label,before,after}:{label:string;before:string;after:string}){return <article className="rounded-xl border p-4"><h3 className="font-semibold">{label}</h3><p className="mt-2 text-sm text-stone-500">Before</p><p>{before}</p><p className="mt-3 text-sm text-stone-500">After</p><p>{after}</p></article>;}
function single(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value;}
