import Link from "next/link";
import { notFound } from "next/navigation";
import { getPlatformOutcomeReviewDetail } from "@/app/actions/platform-learning-workspace";
import { LearningHeader } from "@/components/learning/learning-workspace-ui";

export default async function ReviewDetailPage({params,searchParams}:{params:Promise<{reviewId:string}>;searchParams:Promise<{workspace?:string}>}) {
  const [{reviewId},{workspace}]=await Promise.all([params,searchParams]),detail=await getPlatformOutcomeReviewDetail(reviewId,workspace);
  if(!detail)notFound();
  const {review}=detail;
  return <main className="mx-auto max-w-6xl space-y-8 px-5 py-10"><LearningHeader title="Outcome Review Detail" description="Expected outcomes, observed measurements, variance, evidence, and resulting knowledge—without recalculation in presentation."/>
    <section className="grid gap-4 sm:grid-cols-4"><Card label="Status" value={review.status}/><Card label="Summary" value={review.summaryStatus??"Pending"}/><Card label="Confidence" value={review.confidence}/><Card label="Freshness" value={review.freshness}/></section>
    <Panel title="Expected versus observed">{detail.evaluations.length?<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-3">Metric</th><th className="p-3">Evaluation</th><th className="p-3">Absolute variance</th><th className="p-3">Relative variance</th><th className="p-3">Direction</th><th className="p-3">Materiality</th></tr></thead><tbody>{detail.evaluations.map((x,i)=><tr className="border-t" key={i}><td className="p-3 font-mono text-xs">{String(x.expected_outcome_id)}</td><td className="p-3 capitalize">{String(x.status).replaceAll("-"," ")}</td><td className="p-3">{display(x.absolute_variance)}</td><td className="p-3">{x.relative_variance==null?"—":`${(Number(x.relative_variance)*100).toFixed(1)}%`}</td><td className="p-3 capitalize">{String(x.direction_evaluation).replaceAll("-"," ")}</td><td className="p-3 capitalize">{String(x.materiality)}</td></tr>)}</tbody></table></div>:<p className="text-sm text-stone-500">Metric evaluations are not yet available.</p>}</Panel>
    <section className="grid gap-6 lg:grid-cols-2"><Panel title="Measurements">{detail.measurements.length?<ul className="space-y-3">{detail.measurements.map((x,i)=><li key={i} className="rounded-xl bg-stone-50 p-4"><p className="font-semibold">{metricName(x.metric_definition)}</p><p className="mt-1 text-sm capitalize">{String(x.qualification)} · {String(x.status)}</p><p className="mt-1 text-xs text-stone-500">{String(x.measurement_start)} to {String(x.measurement_end)}</p></li>)}</ul>:<p className="text-sm text-stone-500">No measured outcomes are visible.</p>}</Panel><Panel title="Evidence">{detail.evidence.length?<ul className="space-y-3">{detail.evidence.map((x,i)=><li key={i} className="rounded-xl bg-stone-50 p-4 text-sm"><span className="font-semibold">{String(x.type??"Evidence")}</span><span className="block font-mono text-xs">{String(x.sourceId??x.id??"Reference")}</span></li>)}</ul>:<p className="text-sm text-stone-500">No evidence references are visible.</p>}</Panel></section>
    <Panel title="Resulting lessons">{detail.lessons.length?<div className="flex flex-wrap gap-3">{detail.lessons.map((x,i)=><Link key={i} href={`/dashboard/learn/lessons/${String(x.id)}`} className="rounded-xl border px-4 py-3 font-semibold">{String(x.statement)} →</Link>)}</div>:<p className="text-sm text-stone-500">This review has not produced validated organizational knowledge.</p>}</Panel>
    <Panel title="Source lineage"><dl className="grid gap-4 text-sm sm:grid-cols-2"><LineageFact label="Measurement plan" value={detail.lineage.measurementPlanTitle||detail.lineage.measurementPlanVersionId}/><LineageFact label="Plan version" value={detail.lineage.measurementPlanVersionId}/></dl><div className="mt-5 flex flex-wrap gap-3">{detail.lineage.sourceActionId?<Link className="rounded-xl border px-4 py-3 font-semibold" href={`/dashboard/execute/actions/${encodeURIComponent(detail.lineage.sourceActionId)}`}>View source action →</Link>:null}{detail.lineage.sourceActionPlanId?<Link className="rounded-xl border px-4 py-3 font-semibold" href={`/dashboard/execute/plans/${encodeURIComponent(detail.lineage.sourceActionPlanId)}`}>View Action Plan →</Link>:null}{detail.lineage.sourceDecisionId?<Link className="rounded-xl border px-4 py-3 font-semibold" href={`/dashboard/portfolio/decisions/${encodeURIComponent(detail.lineage.sourceDecisionId)}`}>View source decision →</Link>:null}</div>{!detail.lineage.sourceActionId&&!detail.lineage.sourceActionPlanId&&!detail.lineage.sourceDecisionId?<p className="mt-4 text-sm text-stone-500">No execution or decision source is recorded for this measurement plan. Lineage is not inferred.</p>:null}</Panel>
    <Panel title="Lineage activity">{detail.activity.length?<ol className="space-y-3">{detail.activity.map((x,i)=><li key={i} className="border-l-2 border-teal-700 pl-4"><p className="font-semibold">{String(x.safe_summary)}</p><p className="text-xs text-stone-500">{String(x.event_type)} · {new Date(String(x.occurred_at)).toLocaleString()}</p></li>)}</ol>:<p className="text-sm text-stone-500">No additional lineage activity is visible.</p>}</Panel>
  </main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-4">{children}</div></section>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-5"><p className="text-sm text-stone-500">{label}</p><p className="mt-2 font-semibold capitalize">{value.replaceAll("-"," ")}</p></div>}
function LineageFact({label,value}:{label:string;value:string}){return <div><dt className="text-stone-500">{label}</dt><dd className="mt-1 font-semibold">{value||"Not recorded"}</dd></div>}
function display(value:unknown){return value==null?"—":String(value)}
function metricName(value:unknown){if(value&&typeof value==="object"&&"name"in value)return String((value as {name:unknown}).name);return"Measured outcome"}
