"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowDownToLine, ArrowRight, BedDouble, CalendarCheck, CircleAlert, Download, Ellipsis, Plus, RefreshCw, Search, SlidersHorizontal } from "lucide-react";

type Screen = "home" | "revenue" | "financial" | "executive" | "portfolio" | "investment" | "actions" | "outcomes" | "reports";
type Metric = { label: string; value: string; change?: string };

const screenCopy: Record<Exclude<Screen, "home">, { title: string; description: string; metrics: Metric[] }> = {
  revenue: { title: "Revenue Intelligence", description: "Monitor revenue performance, demand, pricing and booking trends.", metrics: [
    { label: "Total Revenue", value: "$142,385", change: "+8.7% vs prior period" }, { label: "Occupancy Rate", value: "68.2%", change: "+4.3% vs prior period" }, { label: "ADR", value: "$203.12", change: "+6.1% vs prior period" }, { label: "RevPAR", value: "$138.41", change: "+10.5% vs prior period" }, { label: "Booking Pace", value: "+8.3%", change: "vs same time last year" },
  ]},
  financial: { title: "Financial Intelligence", description: "Understand financial performance, cash flow and profitability.", metrics: [
    { label: "Net Operating Income", value: "$62,430", change: "+11.2% vs prior period" }, { label: "Operating Margin", value: "24.8%", change: "+2.4 pts vs prior period" }, { label: "Gross Margin", value: "56.1%", change: "+1.4 pts vs prior period" }, { label: "Cash Balance", value: "$84,250", change: "+6.0% vs prior period" }, { label: "Expense Ratio", value: "31.3%", change: "-1.6 pts vs prior period" },
  ]},
  executive: { title: "Executive Intelligence", description: "Executive health and performance summary.", metrics: [
    { label: "Net Operating Income", value: "$96,542", change: "+8.1% vs prior" }, { label: "EBITDA Margin", value: "38.4%", change: "+2.7 pts vs prior" }, { label: "Cash Balance", value: "$1.24M", change: "vs prior $1.08M" }, { label: "Guest Satisfaction", value: "4.76", change: "+0.06 vs prior" }, { label: "Overall Score", value: "82", change: "+6 pts vs prior" },
  ]},
  portfolio: { title: "Portfolio Intelligence", description: "Compare performance across your portfolio.", metrics: [
    { label: "Total Revenue", value: "$423,851", change: "+8.2% vs prior" }, { label: "Average Occupancy", value: "68.6%", change: "+4.6 pts vs prior" }, { label: "Average ADR", value: "$204.18", change: "+4.1% vs prior" }, { label: "RevPAR", value: "$140.22", change: "+5.8% vs prior" }, { label: "NOI Margin", value: "24.6%", change: "+1.0 pts vs prior" },
  ]},
  investment: { title: "Investment Intelligence", description: "Evaluate acquisitions before committing capital.", metrics: [
    { label: "Pipeline", value: "12", change: "High impact" }, { label: "Total Reviewed", value: "12", change: "opportunities" }, { label: "Average", value: "A", change: "Moderate" }, { label: "Confidence", value: "8", change: "Pending" },
  ]},
  actions: { title: "Action Center", description: "Manage and complete the work that drives results.", metrics: [] },
  outcomes: { title: "Outcomes", description: "Measure outcomes and continuously improve performance.", metrics: [
    { label: "Total Outcomes", value: "32", change: "This period" }, { label: "Positive Impact", value: "24", change: "75% of total" }, { label: "Negative Impact", value: "5", change: "16% of total" }, { label: "Inconclusive", value: "3", change: "9% of total" }, { label: "Net Impact", value: "+$48,920", change: "This period" },
  ]},
  reports: { title: "Hospitality Performance Reports", description: "Create and share business reports for every audience.", metrics: [
    { label: "Scheduled", value: "3", change: "Upcoming" }, { label: "Recent", value: "8", change: "Last 30 days" }, { label: "Drafts", value: "2", change: "In progress" }, { label: "Shared", value: "14", change: "Shared reports" },
  ]},
};

const properties = ["Ocean View Villa", "Downtown Loft", "Mountain Cabin", "Desert Escape", "Beach House"];

export function HpmDashboard({ screen }: { screen: Screen }) {
  const [tab, setTab] = useState(screen === "investment" ? "Analyze" : screen === "actions" ? "Actions" : screen === "reports" ? "Executive" : "Overview");
  const [query, setQuery] = useState("");
  if (screen === "home") return <Home />;
  const copy = screenCopy[screen];
  return <div className="hpm-page">
    <header className="hpm-title"><div><h1>{copy.title}</h1><p>{copy.description}</p></div><div className="flex gap-2">{["revenue","financial"].includes(screen) ? <button className="hpm-button secondary" onClick={()=>window.print()}><Download /> Export</button> : null}<button aria-label="More options" className="hpm-icon-button"><Ellipsis /></button>{["actions","reports"].includes(screen) ? <Link className="hpm-button" href={screen === "reports" ? "/dashboard/reports/new" : "/dashboard/actions?create=new"}>{screen === "reports" ? "Create report" : "Create new"} <Plus /></Link> : null}</div></header>
    <Tabs screen={screen} tab={tab} setTab={setTab} />
    {copy.metrics.length ? <MetricGrid metrics={copy.metrics} /> : null}
    {screen === "revenue" ? <Revenue /> : screen === "financial" ? <Financial /> : screen === "executive" ? <Executive /> : screen === "portfolio" ? <Portfolio /> : screen === "investment" ? <Investment /> : screen === "actions" ? <Actions query={query} setQuery={setQuery} /> : screen === "outcomes" ? <Outcomes /> : <Reports query={query} setQuery={setQuery} />}
  </div>;
}

function Home() { return <div className="hpm-page"><header className="hpm-title"><div><h1>Home</h1><h2>Good morning, Todd.</h2><p>Here&apos;s what needs your attention today.</p></div><Link className="hpm-button" href="/bookings">View all bookings <ArrowRight /></Link></header><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
  <HomeCard icon={<ArrowDownToLine/>} value="1" label="Arrival today" link="View details"/><HomeCard icon={<BedDouble/>} value="3" label="Guests in house" link="View details"/><HomeCard icon={<CalendarCheck/>} value="2" label="Departures today" link="View details"/><HomeCard icon={<CircleAlert/>} value="1" label="Open issue" link="View details"/><HomeCard icon={<RefreshCw/>} value="Current" label="Sync status" link="Updated 8:06 AM"/>
  </div><div className="hpm-split"><Panel title="Today’s schedule" action="View full schedule"><Rows kind="schedule"/></Panel><Panel title="Requires attention" action="View all"><Rows kind="attention"/></Panel></div><Panel title="At a glance"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Occupancy (today)" value="72%" note="+6.2 pts"/><Kpi label="ADR (today)" value="$203" note="+$14"/><Kpi label="RevPAR (today)" value="$146" note="+5.1%"/><Kpi label="Revenue (today)" value="$4,820" note="+8.7%"/><PropertyCard/></div></Panel></div> }

function Tabs({ screen, tab, setTab }: { screen: Exclude<Screen,"home">; tab:string; setTab:(v:string)=>void }) { const tabs = screen === "actions" ? ["Actions","Projects","Automations","Services"] : screen === "outcomes" ? ["Outcomes","Experiments","Knowledge","Improvement"] : screen === "reports" ? ["Executive","Owner","Investment","Operations","Custom"] : screen === "investment" ? ["Analyze","Scenarios","Opportunities"] : [screen === "executive" ? "Executive Intelligence" : screen === "portfolio" ? "Portfolio Intelligence" : "Revenue Intelligence", screen === "financial" ? "Financial Intelligence" : screen === "revenue" ? "Financial Intelligence" : "Portfolio Intelligence"];
 return <nav className="hpm-tabs" aria-label={`${screen} views`}>{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</nav> }

function MetricGrid({metrics}:{metrics:Metric[]}) { return <div className={`hpm-metrics ${metrics.length===4?"four":""}`}>{metrics.map(m=><article key={m.label}><span>{m.label}</span><strong>{m.value}</strong>{m.change?<small>↑ {m.change}</small>:null}</article>)}</div> }
function Revenue(){return <><div className="hpm-split"><Panel title="Revenue Over Time"><MiniLine/></Panel><Panel title="Revenue by Channel"><Donut/><Legend items={["Direct 36.8%","Airbnb 30.1%","Vrbo 16.7%","Booking.com 8.8%","Other 5.0%"]}/></Panel></div><div className="hpm-split"><Panel title="Top Performing Properties" action="View all properties"><PropertyTable/></Panel><Panel title="Revenue Insights"><Insight text="Revenue is up 12.4% driven by higher ADR and demand."/><Insight text="Weekend ADR outperformed weekdays by 10%."/><Insight text="Booking pace is ahead of last year by 8.3%."/></Panel></div></>}
function Financial(){return <><div className="hpm-split"><Panel title="Net Operating Income Over Time"><Bars/></Panel><Panel title="Expenses by Category"><Donut/><Legend items={["Cleaning 26.4%","Property Mgmt 17.6%","Maintenance 14.2%","Utilities 8.8%","Insurance 6.9%","Other 16.6%"]}/></Panel></div><div className="grid gap-4 lg:grid-cols-3"><Panel title="Cash Flow Summary"><div className="grid grid-cols-3 gap-2"><Kpi label="Cash In" value="$156,320" note="+12.7%"/><Kpi label="Cash Out" value="$93,090" note="+8.8%"/><Kpi label="Net Cash Flow" value="$62,430" note="+30.1%"/></div></Panel><Panel title="Upcoming Obligations"><Rows kind="obligations"/></Panel><Panel title="Financial Insights"><Insight text="NOI increased 11.2%, driven by revenue growth and expense control."/><Insight text="Expense ratio improved 1.4 pts vs prior."/></Panel></div></>}
function Executive(){return <div className="hpm-split"><Panel title="Performance Summary"><ScoreRows/></Panel><Panel title="Top Insights"><Insight text="Weekend pricing drove 18.2% incremental revenue."/><Insight text="Occupancy improved 2.8 pts vs prior period."/><Insight text="Labor cost increased 4.1% vs prior period."/></Panel></div>}
function Portfolio(){return <div className="hpm-split wide-left"><Panel title="Performance by Property"><PropertyTable detailed/></Panel><Panel title="Market Performance"><Kpi label="Beach Market" value="+20.6%" note="Excellent"/><Kpi label="City Market" value="+14.2%" note="Good"/><Kpi label="Mountain Market" value="-3.8%" note="Attention"/></Panel></div>}
function Investment(){return <div className="hpm-split wide-left"><Panel title="Top Recommendations"><table className="hpm-table"><thead><tr><th>Recommendation</th><th>Property</th><th>Potential Impact</th><th>Effort</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{[["Implement dynamic pricing","Ocean View Villa","+$40,000 / yr","Medium","High","Pending"],["Optimize weekend minimum stay","Downtown Loft","+$17,500 / yr","Low","High","Pending"],["Add midweek discount and promotion","Mountain Cabin","+$22,750 / yr","Low","High","Pending"],["Audit cleaning fee structure","Desert Escape","+$8,100 / yr","Medium","Medium","Under review"],["Increase city check-in fee","Ocean View Villa","+$12,700 / yr","Low","Medium","Pending"]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c} className={i===2?"positive":""}>{c}</td>)}</tr>)}</tbody></table></Panel><Panel title="Scenario Snapshots"><Insight text="Base Case · Current market data"/><Insight text="Conservative Case · Downside scenario"/><Insight text="High Case · Best case scenario"/><Insight text="Long Term Hold · 5 year investment view"/></Panel></div>}
function Actions({query,setQuery}:{query:string;setQuery:(v:string)=>void}){const rows=[["Replace AC unit in hallway","Ocean View Villa","High","James Carter","May 6, 2026","In progress"],["Dynamic pricing update","Downtown Loft","Medium","Sophia Lee","May 6, 2026","Ready"],["Add a parking pass to guidebook","Mountain Cabin","Low","Taylor Morgan","May 7, 2026","Ready"],["Review owner statement","Desert Escape","Medium","Jordan Smith","May 8, 2026","Blocked"],["Deep clean + inspection","Ocean View Villa","High","Operations Team","May 9, 2026","In progress"]].filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase()));return <Panel title=""><div className="hpm-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter actions"/></label><button className="hpm-button secondary"><SlidersHorizontal/> All actions</button></div><table className="hpm-table"><thead><tr><th>Action</th><th>Property</th><th>Priority</th><th>Assignee</th><th>Due date</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></Panel>}
function Outcomes(){return <Panel title="Recent Outcomes"><table className="hpm-table"><thead><tr><th>Outcome</th><th>Property</th><th>Impact</th><th>Measured</th><th>Date</th><th>Type</th></tr></thead><tbody>{[["Weekend pricing strategy","Ocean View Villa","+$4,600","Revenue","May 16, 2026","Strategy"],["Guidebook add-on upsells","Downtown Loft","+$1,200","Revenue","May 10, 2026","Experiment"],["Early check-in fee","Mountain Cabin","+$900","Revenue","May 8, 2026","Strategy"],["AC preventive maintenance","Portfolio","-$600","Operations","May 17, 2026","Maintenance"],["Guest messaging automation","Portfolio","+90%","Guest Experience","May 11, 2026","Automation"]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c} className={i===2?c.startsWith("-")?"negative":"positive":""}>{c}</td>)}</tr>)}</tbody></table></Panel>}
function Reports({query,setQuery}:{query:string;setQuery:(v:string)=>void}){const reports=[["May 2026 Executive Report","Executive","Generated","May 31, 2026, 8:15 AM"],["April 2026 Owner Report","Owner","Generated","May 5, 2026, 8:00 AM"],["Investment Review – 42nd Park St","Investment","Draft","May 1, 2026, 12:38 AM"],["Operations Review","Operations","Generated","May 1, 2026"],["June 2026 Guest Experience Report","Operations","Scheduled","Jun 1, 2026"]].filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase()));return <div className="hpm-split wide-left"><Panel title="Recent Reports"><div className="hpm-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reports"/></label></div><table className="hpm-table"><thead><tr><th>Report</th><th>Audience</th><th>Status</th><th>Generated</th><th>Actions</th></tr></thead><tbody>{reports.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}<td><button aria-label={`Open ${r[0]}`}><Ellipsis/></button></td></tr>)}</tbody></table></Panel><Panel title="Report Templates"><Insight text="Monthly Executive Report · Performance summary for executives"/><Insight text="Owner Statement · Monthly performance and owner statement"/><Insight text="Investment Review · Acquisition and portfolio analysis"/><Insight text="Operations Review · Operational performance and issue metrics"/></Panel></div>}

function Panel({title,action,children}:{title:string;action?:string;children:React.ReactNode}){return <section className="hpm-panel"><div className="hpm-panel-head"><h3>{title}</h3>{action?<button>{action} <ArrowRight/></button>:null}</div>{children}</section>}
function HomeCard({icon,value,label,link}:{icon:React.ReactNode;value:string;label:string;link:string}){return <article className="hpm-home-card"><span>{icon}</span><strong>{value}</strong><p>{label}</p><small>{link} <ArrowRight/></small></article>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="hpm-kpi"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Rows({kind}:{kind:string}){const data=kind==="schedule"?[["3:00 PM","Arrival","Ocean View Villa","2 guests"],["4:00 PM","Arrival","Downtown Loft","3 guests"],["10:00 AM","Departure","Desert Escape","2 guests"],["12:00 PM","Departure","Mountain Cabin","4 guests"]]:kind==="attention"?[["1 guest message","Requires a reply"],["1 maintenance issue","AC not cooling · Ocean View Villa"],["2 pricing opportunities","Potential revenue increase"]]:[["Property tax","May 15, 2026","$8,400"],["Loan payment","May 20, 2026","$6,720"],["Insurance","May 31, 2026","$4,800"]];return <div className="hpm-rows">{data.map(r=><div key={r.join()}>{r.map(x=><span key={x}>{x}</span>)}<ArrowRight/></div>)}</div>}
function PropertyCard(){return <div className="hpm-property"><div/><span>Ocean View Villa</span><strong>Revenue $16,800</strong><small>Occupancy 80%</small></div>}
function MiniLine(){return <div className="hpm-chart"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 150 C40 130 50 155 90 120 S150 130 190 100 S240 120 280 35 S330 90 370 55 S410 120 450 75 S500 95 540 65 S575 80 600 60" fill="none" stroke="#07966f" strokeWidth="4"/><path d="M0 155 L600 155" stroke="#e7e5e4"/></svg><div><span>May 1</span><span>May 8</span><span>May 15</span><span>May 22</span><span>May 29</span></div></div>}
function Bars(){return <div className="hpm-bars">{[30,55,42,68,38,74,48,82,51,69,45,77].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div>}
function Donut(){return <div className="hpm-donut"><strong>$70,955</strong><span>Total</span></div>}
function Legend({items}:{items:string[]}){return <div className="hpm-legend">{items.map(x=><span key={x}>{x}</span>)}</div>}
function Insight({text}:{text:string}){return <div className="hpm-insight">{text}</div>}
function PropertyTable({detailed=false}:{detailed?:boolean}){return <table className="hpm-table"><thead><tr><th>Property</th><th>Revenue</th><th>Occupancy</th><th>ADR</th><th>RevPAR</th>{detailed?<th>NOI Margin</th>:null}</tr></thead><tbody>{properties.map((p,i)=><tr key={p}><td>{p}</td><td>${[68430,51800,50430,42300,34651][i].toLocaleString()}</td><td>{[72,67,74,69,62][i]}%</td><td>${[204,194,188,196,210][i]}</td><td>${[147,130,139,135,130][i]}</td>{detailed?<td>{[28.2,23.1,24.8,21.7,18.9][i]}%</td>:null}</tr>)}</tbody></table>}
function ScoreRows(){return <div className="hpm-score-rows">{[["Financial Health","85","Strong"],["Revenue Performance","82","Strong"],["Operational Efficiency","78","Good"],["Guest Experience","88","Strong"]].map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><small>↑ {Number(r[1])-78}</small><em>{r[2]}</em></div>)}</div>}
