import type{PlatformLearningRepository}from"../application";import type{LearningAssumptionResult,LearningDomainEvent,LearningEvidence,LearningLesson,LearningLineageEdge,LearningMeasurementPlan,LearningOutcomeReview,LearningSubject,MeasuredOutcome}from"../domain";
type Row=Record<string,unknown>;type QueryResult<T=unknown>={data:T|null;error:{message:string}|null};type Query={eq(column:string,value:unknown):Query;maybeSingle():Promise<QueryResult<Row>>};type Client={from(table:string):{insert(value:unknown):Promise<QueryResult>;select(columns:string):Query}};
export class SupabasePlatformLearningRepository implements PlatformLearningRepository{constructor(private readonly client:Client){}
 async createSubject(value:LearningSubject){await insert(this.client,"learning_subjects",{id:value.id,workspace_id:value.workspaceId,subject_type:value.subjectType,source_capability:value.sourceCapability,source_id:value.sourceId,source_version:value.sourceVersion??null,created_by_profile_id:value.createdByProfileId,created_at:value.createdAt})}
 async appendLineage(value:LearningLineageEdge){await insert(this.client,"learning_lineage",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,from_reference:value.from,to_reference:value.to,relationship:value.relationship,created_at:value.createdAt})}
 async appendEvidence(value:LearningEvidence){await insert(this.client,"learning_evidence",{id:value.id,workspace_id:value.workspaceId,references:value.references,confidence:value.confidence,freshness:value.freshness,captured_at:value.capturedAt})}
 async appendMeasurementPlan(value:LearningMeasurementPlan){await insert(this.client,"learning_measurement_plans",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,baseline:value.baseline,window_type:value.measurementWindow.type,window_start:value.measurementWindow.start,window_end:value.measurementWindow.end,confidence:value.confidence,version:value.version,created_at:value.createdAt});if(value.expectedOutcomes.length)await insert(this.client,"learning_expected_outcomes",value.expectedOutcomes.map(outcome=>({id:outcome.id,workspace_id:value.workspaceId,measurement_plan_id:value.id,metric:outcome.metric,expected_value:outcome.expectedValue,expected_direction:outcome.expectedDirection,confidence:outcome.confidence,evidence_id:outcome.evidenceId??null})))}
 async appendMeasuredOutcome(value:MeasuredOutcome){await insert(this.client,"learning_measured_outcomes",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,metric:value.metric,observed_value:value.observedValue,observed_at:value.observedAt,evidence_id:value.evidenceId,recorded_at:value.recordedAt})}
 async appendOutcomeReview(value:LearningOutcomeReview){await insert(this.client,"learning_outcome_reviews",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,measurement_plan_id:value.measurementPlanId,expected_outcome_ids:value.expectedOutcomeIds,measured_outcome_ids:value.measuredOutcomeIds,status:value.status,evidence_ids:value.evidenceIds,supersedes_review_id:value.supersedesReviewId??null,created_by_profile_id:value.createdByProfileId,created_at:value.createdAt})}
 async appendAssumptionResult(value:LearningAssumptionResult){await insert(this.client,"learning_assumption_results",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,review_id:value.reviewId,assumption:value.assumption,status:value.status,confidence:value.confidence,evidence_ids:value.evidenceIds,created_at:value.createdAt})}
 async appendLesson(value:LearningLesson){await insert(this.client,"learning_lessons",{id:value.id,workspace_id:value.workspaceId,subject_id:value.subjectId,statement:value.statement,applicability:value.applicability,confidence:value.confidence,maturity:value.maturity,status:value.status,lineage_edge_ids:value.lineageEdgeIds,revision:value.revision,supersedes_lesson_id:value.supersedesLessonId??null,created_by_profile_id:value.createdByProfileId,created_at:value.createdAt});await insert(this.client,"learning_lesson_evidence",value.evidenceIds.map(evidenceId=>({lesson_id:value.id,evidence_id:evidenceId,workspace_id:value.workspaceId})))}
 async appendEvents(values:readonly LearningDomainEvent[]){if(values.length)await insert(this.client,"learning_domain_events",values.map(value=>({id:value.id,workspace_id:value.workspaceId,aggregate_id:value.aggregateId,event_type:value.type,payload:value.payload,occurred_at:value.occurredAt})))}
 async getSubject(workspaceId:string,id:string){const result=await this.client.from("learning_subjects").select("*").eq("workspace_id",workspaceId).eq("id",id).maybeSingle();if(result.error)throw new Error(result.error.message);return result.data?mapSubject(result.data):null}
 async getOutcomeReview(workspaceId:string,id:string){const result=await this.client.from("learning_outcome_reviews").select("*").eq("workspace_id",workspaceId).eq("id",id).maybeSingle();if(result.error)throw new Error(result.error.message);return result.data?mapReview(result.data):null}
 async getLesson(workspaceId:string,id:string){const result=await this.client.from("learning_lessons").select("*,learning_lesson_evidence(evidence_id)").eq("workspace_id",workspaceId).eq("id",id).maybeSingle();if(result.error)throw new Error(result.error.message);return result.data?mapLesson(result.data):null}
}
async function insert(client:Client,table:string,value:unknown){const{error}=await client.from(table).insert(value);if(error)throw new Error(error.message)}
function text(row:Row,key:string){return String(row[key]??"")}function strings(value:unknown){return Array.isArray(value)?value.map(String):[]}function rows(value:unknown):Row[]{return Array.isArray(value)?value.filter((item):item is Row=>Boolean(item)&&typeof item==="object"):[]}
function mapSubject(row:Row):LearningSubject{return{id:text(row,"id"),workspaceId:text(row,"workspace_id"),subjectType:text(row,"subject_type") as LearningSubject["subjectType"],sourceCapability:text(row,"source_capability") as LearningSubject["sourceCapability"],sourceId:text(row,"source_id"),...(row.source_version?{sourceVersion:text(row,"source_version")} :{}),createdAt:text(row,"created_at"),createdByProfileId:text(row,"created_by_profile_id")}}
function mapReview(row:Row):LearningOutcomeReview{return{id:text(row,"id"),workspaceId:text(row,"workspace_id"),subjectId:text(row,"subject_id"),measurementPlanId:text(row,"measurement_plan_id"),expectedOutcomeIds:strings(row.expected_outcome_ids),measuredOutcomeIds:strings(row.measured_outcome_ids),status:text(row,"status") as LearningOutcomeReview["status"],evidenceIds:strings(row.evidence_ids),...(row.supersedes_review_id?{supersedesReviewId:text(row,"supersedes_review_id")} :{}),createdAt:text(row,"created_at"),createdByProfileId:text(row,"created_by_profile_id")}}
function mapLesson(row:Row):LearningLesson{return{id:text(row,"id"),workspaceId:text(row,"workspace_id"),subjectId:text(row,"subject_id"),statement:text(row,"statement"),applicability:(Array.isArray(row.applicability)?row.applicability:[]) as LearningLesson["applicability"],confidence:text(row,"confidence") as LearningLesson["confidence"],maturity:text(row,"maturity") as LearningLesson["maturity"],status:text(row,"status") as LearningLesson["status"],evidenceIds:rows(row.learning_lesson_evidence).map(item=>text(item,"evidence_id")),lineageEdgeIds:strings(row.lineage_edge_ids),revision:Number(row.revision),...(row.supersedes_lesson_id?{supersedesLessonId:text(row,"supersedes_lesson_id")} :{}),createdAt:text(row,"created_at"),createdByProfileId:text(row,"created_by_profile_id")}}
