import { describe, expect, it, vi } from "vitest";
import { PlatformAction, PlatformActionCollection, createActionId, createWorkspaceId, type PlatformActionProvider } from "@/platform/actions";
import { ProviderActionCenterReader } from "./action-center-reader";
import { projectActionCenterAction } from "./action-center-projection";

const workspaceId = createWorkspaceId("workspace-1"); const actor = { type: "user" as const, id: "user-1" }; const viewer = { actor, canManage: true };
function action(priority: "critical" | "high" | "normal" | "low" | "deferred" = "normal") { return PlatformAction.createCommitted({ id: createActionId(`action-${priority}`), workspaceId, title: priority, priority, owner: { type: "team", id: "owner" }, sources: [{ type: "manual", recordedAt: new Date("2026-07-20T10:00:00Z"), recordedBy: actor }], createdAt: new Date("2026-07-20T10:00:00Z"), createdBy: actor }); }
function status(value: PlatformAction["status"]): PlatformAction { const input = { id: createActionId(`action-${value}`), workspaceId, title: value, priority: "normal" as const, owner: actor, sources: [{ type: "manual" as const, recordedAt: new Date("2026-07-20T10:00:00Z"), recordedBy: actor }], createdAt: new Date("2026-07-20T10:00:00Z"), createdBy: actor }; let current = value === "draft" ? PlatformAction.createDraft(input) : PlatformAction.createCommitted(input); const command = () => ({ workspaceId, expectedVersion: current.version, actor, occurredAt: new Date(current.updatedAt.getTime() + 60_000) }); if (value === "draft" || value === "committed") return current; if (value === "cancelled") return current.cancel(command()); current = current.markReady(command()); if (value === "ready") return current; current = current.start(command()); if (value === "in-progress") return current; if (value === "blocked") return current.block(command()); current = current.complete(command()); if (value === "completed") return current; return current.archive(command()); }
function provider(values: readonly PlatformAction[]) { return { find: vi.fn(async () => PlatformActionCollection.create(values)), findById: vi.fn(async () => values[0] ?? null) } as unknown as PlatformActionProvider; }

describe("ProviderActionCenterReader", () => {
  it("scopes provider queries and projects empty collections without fixtures", async () => { const value = provider([]); const queue = await new ProviderActionCenterReader(value).loadQueue({ workspaceId, viewer, activeOnly: true }); expect(value.find).toHaveBeenCalledWith(expect.objectContaining({ workspaceId, statuses: ["draft", "committed", "ready", "in-progress", "blocked"] })); expect(queue).toMatchObject({ isEmpty: true, activeActions: [], completedActions: [] }); });
  it("uses findById and keeps owner separate from assignment", async () => { const canonical = action(); const value = provider([canonical]); const result = await new ProviderActionCenterReader(value).loadAction({ workspaceId, actionId: canonical.id.value, viewer }); expect(value.findById).toHaveBeenCalledWith({ workspaceId, actionId: canonical.id }); expect(result?.owner.label).toBe("owner"); expect(result?.assignee).toBeUndefined(); });
  it.each(["critical", "high", "normal", "low", "deferred"] as const)("maps %s priority", (priority) => expect(projectActionCenterAction(action(priority), viewer).priority).toBe(priority));
  it.each(["draft", "committed", "ready", "in-progress", "blocked", "completed", "cancelled", "archived"] as const)("maps %s status without remapping", (value) => expect(projectActionCenterAction(status(value), viewer).status).toBe(value));
  it("excludes cancelled and archived actions from the active queue", async () => { const queue = await new ProviderActionCenterReader(provider([status("cancelled"), status("archived")])).loadQueue({ workspaceId, viewer }); expect(queue.activeActions).toEqual([]); });
  it("projects due and overdue state without mutation methods", () => { let value = action(); value = value.schedule({ workspaceId, expectedVersion: value.version, actor, occurredAt: new Date("2026-07-20T11:00:00Z"), due: new Date("2026-07-21T00:00:00Z") }); const projected = projectActionCenterAction(value, viewer, new Date("2026-07-22T00:00:00Z")); expect(projected.isOverdue).toBe(true); expect(projected.dueAt).toEqual(new Date("2026-07-21T00:00:00Z")); expect(projected).not.toHaveProperty("start"); });
  it("lets provider errors reach the page boundary", async () => { const error = new Error("read failed"); const value = { find: vi.fn(async () => { throw error; }) } as unknown as PlatformActionProvider; await expect(new ProviderActionCenterReader(value).loadQueue({ workspaceId, viewer })).rejects.toBe(error); });
});
