import type { InvestmentOpportunityId, OpportunityAnalysisId } from "@/features/investment-opportunity/domain";
import { AcquisitionDomainError, AcquisitionPipeline, createPipelineActivation, createAcquisitionExit, buildAcquisitionClosingReadiness, type AcquisitionClosingFacts, type AcquisitionExit, type AcquisitionStage, type AcquisitionTransitionReason, type OfferSourceAnalysisReference, type AcquisitionOfferTerms, type AcquisitionContractSource, type AcquisitionContractTerms } from "../../domain";
import type { AcquisitionApplicationCommandContext, AcquisitionAuthorization, AcquisitionCapability, AcquisitionClock, AcquisitionEventPublisher, AcquisitionAnalysisReader, AcquisitionTransactionalContext, AcquisitionUnitOfWork } from "../ports";
import { AcquisitionApplicationError } from "../errors";
import { buildAcquisitionPipelineView } from "../projections";

type Deps = Readonly<{ unitOfWork: AcquisitionUnitOfWork; authorization: AcquisitionAuthorization; analysisReader?: AcquisitionAnalysisReader; clock?: AcquisitionClock; events?: AcquisitionEventPublisher }>;

function appError(error: unknown): AcquisitionApplicationError { if (error instanceof AcquisitionApplicationError) return error; if (error instanceof AcquisitionDomainError) return new AcquisitionApplicationError("ACQUISITION_APPLICATION_INPUT_INVALID"); return new AcquisitionApplicationError("ACQUISITION_TRANSACTION_FAILED"); }
function context(input: AcquisitionApplicationCommandContext, clock?: AcquisitionClock) { return { ...input, occurredAt: clock?.now() ?? input.occurredAt }; }
async function authorize(deps: Deps, ctx: AcquisitionApplicationCommandContext, capability: AcquisitionCapability, resourceId?: string) { const decision = await deps.authorization.authorize({ actor: ctx.actor, ownerId: ctx.ownerId, capability, resourceId }); if (!decision.allowed) throw new AcquisitionApplicationError("ACQUISITION_NOT_AUTHORIZED"); }
async function receipt<T>(tx: AcquisitionTransactionalContext, ctx: AcquisitionApplicationCommandContext, type: string): Promise<{ value: T; replayed: boolean } | null> { const found = await tx.commandReceipts.find(ctx.commandId, ctx.ownerId); if (!found) return null; if (found.commandType !== type) throw new AcquisitionApplicationError("ACQUISITION_COMMAND_ID_REUSED"); return { value: found.result as T, replayed: true }; }
async function publish(deps: Deps, events: readonly unknown[]) { if (deps.events && events.length) await deps.events.publish(events); }

export type ActivateAcquisitionPipelineCommand = Readonly<{ context: AcquisitionApplicationCommandContext; opportunityId: InvestmentOpportunityId; analysisId: OpportunityAnalysisId; analysisVersion: number }>;
export async function activateAcquisitionPipeline(command: ActivateAcquisitionPipelineCommand, deps: Deps) {
 try { let events: readonly unknown[] = []; const result = await deps.unitOfWork.execute(async tx => { const replay = await receipt<ReturnType<typeof buildAcquisitionPipelineView>>(tx, command.context, "activate-acquisition-pipeline"); if (replay) return { ...replay, opportunityVersion: undefined };
   await authorize(deps, command.context, "acquisition.pipeline.activate"); const opportunity = await tx.investmentOpportunities.findById(command.opportunityId, command.context.ownerId); if (!opportunity) throw new AcquisitionApplicationError("ACQUISITION_OPPORTUNITY_NOT_FOUND"); if (await tx.acquisitionPipelines.exists(command.opportunityId)) throw new AcquisitionApplicationError("ACQUISITION_PIPELINE_ALREADY_EXISTS"); if (opportunity.props.archivedAt || opportunity.props.status === "acquired") throw new AcquisitionApplicationError("ACQUISITION_APPLICATION_INPUT_INVALID");
   const source = await deps.analysisReader?.getCompletedAnalysisReference({ ownerId: command.context.ownerId, opportunityId: command.opportunityId, analysisId: command.analysisId, analysisVersion: command.analysisVersion }); if (!source) throw new AcquisitionApplicationError("ACQUISITION_ANALYSIS_NOT_FOUND"); if (!source.opportunityId.equals(command.opportunityId) || source.route !== opportunity.props.route) throw new AcquisitionApplicationError("ACQUISITION_APPLICATION_INPUT_INVALID");
   const ctx = context(command.context, deps.clock); const pipeline = AcquisitionPipeline.activate({ opportunityId: command.opportunityId, route: opportunity.props.route, activation: createPipelineActivation({ activatedAt: ctx.occurredAt, activatedBy: ctx.actor, sourceAnalysis: { analysisId: source.analysisId, analysisVersion: source.version, analyzedAt: source.analyzedAt, route: source.route, ...(source.assumptionFingerprint ? { assumptionFingerprint: source.assumptionFingerprint } : {}) } }), context: ctx });
   opportunity.transitionStatus("shortlisted", { actor: ctx.actor, occurredAt: ctx.occurredAt, commandId: ctx.commandId.value }); await tx.acquisitionPipelines.save(pipeline); await tx.investmentOpportunities.save(opportunity, command.context.expectedOpportunityVersion); const view = buildAcquisitionPipelineView(pipeline, opportunity.props.status); events = []; await tx.commandReceipts.save({ commandId: ctx.commandId, ownerId: ctx.ownerId, commandType: "activate-acquisition-pipeline", aggregateId: pipeline.id, completedAt: ctx.occurredAt, result: view }); return { value: view, replayed: false, pipelineVersion: pipeline.version().value, opportunityVersion: opportunity.version }; }); await publish(deps, events); return { data: result.value, commandId: command.context.commandId, replayed: result.replayed, pipelineVersion: result.value.pipelineVersion }; } catch (error) { throw appError(error); }
}

export type TransitionAcquisitionStageCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; targetStage: AcquisitionStage; reason?: AcquisitionTransitionReason }>;
export async function transitionAcquisitionStage(command: TransitionAcquisitionStageCommand, deps: Deps) { return mutatePipeline(command.pipelineId, command.context, "transition-acquisition-stage", "acquisition.pipeline.manage", deps, async (pipeline, _tx, ctx) => { if (["offer-submitted","negotiating","under-contract","closing-preparation","closed-acquired","exited"].includes(command.targetStage)) throw new AcquisitionApplicationError("ACQUISITION_APPLICATION_INPUT_INVALID"); pipeline.transition({ ...ctx, to: command.targetStage, reason: command.reason }); return pipeline; }, true); }

export type ExitAcquisitionPipelineCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; exit: Omit<AcquisitionExit,"exitedAt"|"exitedBy"> }>;
export async function exitAcquisitionPipeline(command: ExitAcquisitionPipelineCommand, deps: Deps) { return mutatePipeline(command.pipelineId, command.context, "exit-acquisition-pipeline", "acquisition.pipeline.exit", deps, async (pipeline, tx, ctx) => { const opportunity = await tx.investmentOpportunities.findById(pipeline.opportunityId, ctx.ownerId); if (!opportunity) throw new AcquisitionApplicationError("ACQUISITION_OPPORTUNITY_NOT_FOUND"); pipeline.exit({ exit: createAcquisitionExit({ ...command.exit, exitedAt: ctx.occurredAt, exitedBy: ctx.actor, route: pipeline.route }), context: ctx }); if (opportunity.props.status !== pipeline.statusProjection().status) { opportunity.transitionStatus(pipeline.statusProjection().status, { actor: ctx.actor, occurredAt: ctx.occurredAt, commandId: ctx.commandId.value }); await tx.investmentOpportunities.save(opportunity, ctx.expectedOpportunityVersion); } return pipeline; }, true); }

async function mutatePipeline(pipelineId: import("../../domain").AcquisitionPipelineId, ctx: AcquisitionApplicationCommandContext, type: string, capability: AcquisitionCapability, deps: Deps, operation: (pipeline: AcquisitionPipeline, tx: AcquisitionTransactionalContext, ctx: ReturnType<typeof context>) => Promise<AcquisitionPipeline>, syncOpportunity = false) { try { return await deps.unitOfWork.execute(async tx => { const replay = await receipt<ReturnType<typeof buildAcquisitionPipelineView>>(tx, ctx, type); if (replay) return { data: replay.value, commandId: ctx.commandId, replayed: true }; await authorize(deps, ctx, capability, pipelineId.value); const pipeline = await tx.acquisitionPipelines.findById(pipelineId); if (!pipeline) throw new AcquisitionApplicationError("ACQUISITION_PIPELINE_NOT_FOUND"); const next = await operation(pipeline, tx, context(ctx, deps.clock)); const opportunityStatus = next.statusProjection().status; if (syncOpportunity) { const opportunity = await tx.investmentOpportunities.findById(next.opportunityId, ctx.ownerId); if (!opportunity) throw new AcquisitionApplicationError("ACQUISITION_OPPORTUNITY_NOT_FOUND"); if (opportunity.props.status !== opportunityStatus) { opportunity.transitionStatus(opportunityStatus, { actor: ctx.actor, occurredAt: context(ctx, deps.clock).occurredAt, commandId: ctx.commandId.value }); await tx.investmentOpportunities.save(opportunity, ctx.expectedOpportunityVersion); } } await tx.acquisitionPipelines.save(next, ctx.expectedPipelineVersion?.value); const view = buildAcquisitionPipelineView(next, opportunityStatus); await tx.commandReceipts.save({ commandId: ctx.commandId, ownerId: ctx.ownerId, commandType: type, aggregateId: next.id, completedAt: context(ctx, deps.clock).occurredAt, result: view }); return { data: view, commandId: ctx.commandId, replayed: false, pipelineVersion: next.version().value }; }); } catch (error) { throw appError(error); } }

export type GetAcquisitionClosingReadinessQuery = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId }>;
export async function getAcquisitionClosingReadiness(query: GetAcquisitionClosingReadinessQuery, deps: Deps) { return deps.unitOfWork.execute(async tx => { await authorize(deps, query.context, "acquisition.pipeline.read"); const pipeline = await tx.acquisitionPipelines.findById(query.pipelineId); if (!pipeline) throw new AcquisitionApplicationError("ACQUISITION_PIPELINE_NOT_FOUND"); return buildAcquisitionClosingReadiness({ pipeline, evaluatedAt: deps.clock?.now() ?? query.context.occurredAt }); }); }

export type BeginClosingPreparationCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId }>;
export async function beginClosingPreparation(command: BeginClosingPreparationCommand, deps: Deps) { try { return await deps.unitOfWork.execute(async tx => { await authorize(deps, command.context, "acquisition.closing.prepare"); const pipeline = await tx.acquisitionPipelines.findById(command.pipelineId); if (!pipeline) throw new AcquisitionApplicationError("ACQUISITION_PIPELINE_NOT_FOUND"); const readiness = buildAcquisitionClosingReadiness({ pipeline, evaluatedAt: deps.clock?.now() ?? command.context.occurredAt }); pipeline.beginClosingPreparation({ readiness, context: context(command.context, deps.clock) }); await tx.acquisitionPipelines.save(pipeline, command.context.expectedPipelineVersion?.value); return { data: buildAcquisitionPipelineView(pipeline), commandId: command.context.commandId, replayed: false, pipelineVersion: pipeline.version().value }; }); } catch (error) { throw appError(error); } }

export type CloseAcquisitionCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; closingFacts: AcquisitionClosingFacts }>;
export async function closeAcquisition(command: CloseAcquisitionCommand, deps: Deps) { try { return await deps.unitOfWork.execute(async tx => { await authorize(deps, command.context, "acquisition.close"); const pipeline = await tx.acquisitionPipelines.findById(command.pipelineId); if (!pipeline) throw new AcquisitionApplicationError("ACQUISITION_PIPELINE_NOT_FOUND"); const opportunity = await tx.investmentOpportunities.findById(pipeline.opportunityId, command.context.ownerId); if (!opportunity) throw new AcquisitionApplicationError("ACQUISITION_OPPORTUNITY_NOT_FOUND"); const readiness = buildAcquisitionClosingReadiness({ pipeline, evaluatedAt: deps.clock?.now() ?? command.context.occurredAt }); const ctx = context(command.context, deps.clock); pipeline.closeAcquisition({ facts: command.closingFacts, readiness, context: ctx }); opportunity.transitionStatus("acquired", { actor: ctx.actor, occurredAt: ctx.occurredAt, commandId: ctx.commandId.value }); await tx.acquisitionPipelines.save(pipeline, command.context.expectedPipelineVersion?.value); await tx.investmentOpportunities.save(opportunity, command.context.expectedOpportunityVersion); const view = buildAcquisitionPipelineView(pipeline, opportunity.props.status); await tx.commandReceipts.save({ commandId: ctx.commandId, ownerId: ctx.ownerId, commandType: "close-acquisition", aggregateId: pipeline.id, completedAt: ctx.occurredAt, result: view }); return { data: view, commandId: ctx.commandId, replayed: false, pipelineVersion: pipeline.version().value }; }); } catch (error) { throw appError(error); } }

export type CreateAcquisitionOfferDraftCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; sourceAnalysis: OfferSourceAnalysisReference; terms: AcquisitionOfferTerms }>;
export async function createAcquisitionOfferDraft(command: CreateAcquisitionOfferDraftCommand, deps: Deps) { return mutatePipeline(command.pipelineId, command.context, "create-acquisition-offer-draft", "acquisition.offer.manage", deps, async (pipeline, _tx, ctx) => { pipeline.createOfferDraft({ sourceAnalysis: command.sourceAnalysis, terms: command.terms, context: ctx }); return pipeline; }); }
export type SubmitAcquisitionOfferCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; offerId: import("../../domain").AcquisitionOfferId }>;
export async function submitAcquisitionOffer(command: SubmitAcquisitionOfferCommand, deps: Deps) { return mutatePipeline(command.pipelineId, command.context, "submit-acquisition-offer", "acquisition.offer.manage", deps, async (pipeline, _tx, ctx) => { pipeline.submitOffer({ offerId: command.offerId, context: ctx }); return pipeline; }, true); }
export type RecordAcquisitionContractCommand = Readonly<{ context: AcquisitionApplicationCommandContext; pipelineId: import("../../domain").AcquisitionPipelineId; source: AcquisitionContractSource; terms: AcquisitionContractTerms }>;
export async function recordAcquisitionContract(command: RecordAcquisitionContractCommand, deps: Deps) { return mutatePipeline(command.pipelineId, command.context, "record-acquisition-contract", "acquisition.contract.record", deps, async (pipeline, _tx, ctx) => { pipeline.recordContract({ source: command.source, terms: command.terms, context: ctx }); return pipeline; }, true); }
