"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { PortfolioWorkspaceView } from "../application";

export function OpportunityComparisonSelector({ opportunities }: { opportunities: PortfolioWorkspaceView["opportunities"] }) { const router = useRouter(), [selected, setSelected] = useState<readonly string[]>([]), byId = useMemo(() => new Map(opportunities.map(value => [value.id, value])), [opportunities]), selectedRoute = selected[0] ? byId.get(selected[0])?.route : undefined; const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : current.length < 4 ? [...current, id] : current); const comparable = opportunities.filter(value => !value.archived && value.score !== undefined);
  if (comparable.length < 2) return null;
  return <section className="rounded-2xl border border-stone-300 bg-stone-950 p-5 text-white"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">Compare opportunities</h2><p className="mt-1 text-sm text-stone-400">Select 2–4 analyzed opportunities using the same acquisition route.</p></div><button disabled={selected.length < 2} onClick={() => { const query = new URLSearchParams(); selected.forEach(id => query.append("id", id)); router.push(`/dashboard/investments/portfolio/compare?${query}`); }} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-stone-950 disabled:opacity-40">Compare {selected.length || ""}</button></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{comparable.map(value => { const disabled = Boolean(selectedRoute && value.route !== selectedRoute && !selected.includes(value.id)); return <label key={value.id} className={`flex items-start gap-3 rounded-xl border p-3 text-sm ${disabled ? "cursor-not-allowed border-white/5 text-stone-600" : "cursor-pointer border-white/15 text-stone-200 hover:border-white/30"}`}><input type="checkbox" checked={selected.includes(value.id)} disabled={disabled} onChange={() => toggle(value.id)} className="mt-0.5 h-4 w-4" /><span><span className="block truncate font-semibold">{value.name}</span><span className="mt-1 block text-xs text-stone-500">{value.route === "purchase" ? "Purchase" : "Rental Arbitrage"} · {value.score}/100</span></span></label>; })}</div>{selected.length === 4 ? <p className="mt-3 text-xs text-amber-300">Four-opportunity comparison limit reached.</p> : null}</section>;
}
