import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import type { OpportunityDetailView, OpportunityAnalysisVersionView } from "../application";
import { InvestmentSectionNavigation } from "./investment-section-navigation";
import { OpportunityWorkflowControls } from "./opportunity-workflow-controls";
import type { OpportunityNote } from "../domain";

export function OpportunityDetail({ opportunity, notes = [] }: { opportunity: OpportunityDetailView; notes?: readonly OpportunityNote[] }) {
  return <main className="mx-auto max-w-6xl space-y-8 px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <div className="flex flex-wrap items-center justify-between gap-4"><Link href="/dashboard/investments/opportunities" className="text-sm font-semibold text-stone-600 hover:text-stone-950">← Back to portfolio</Link><InvestmentSectionNavigation active="portfolio" /></div>
    <header className="flex flex-col gap-5 border-b border-stone-200 pb-8 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge tone="dark">{label(opportunity.status)}</Badge><Badge>{opportunity.route === "purchase" ? "Purchase" : "Rental Arbitrage"}</Badge>{opportunity.archived ? <Badge>Archived</Badge> : null}</div><h1 className="mt-4 text-3xl font-semibold tracking-tight text-stone-950 sm:text-4xl">{opportunity.address}</h1><p className="mt-2 text-sm text-stone-500">{opportunity.name}</p></div><Link href={`/dashboard/investments/new?opportunity=${opportunity.id}&mode=reanalyze`} className="inline-flex w-fit rounded-full bg-stone-950 px-5 py-2.5 text-sm font-semibold text-white">Reanalyze</Link></header>
    <OpportunityWorkflowControls opportunity={opportunity} />
    <section className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Card className="p-6"><SectionHeading title="Overview" /><dl className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4"><Fact label="Route" value={opportunity.route === "purchase" ? "Purchase" : "Rental Arbitrage"} /><Fact label="Status" value={label(opportunity.status)} /><Fact label="Created" value={date(opportunity.createdAt)} /><Fact label="Updated" value={date(opportunity.updatedAt)} /></dl></Card><Card className="p-6"><SectionHeading title="Tags" /><div className="mt-5 flex flex-wrap gap-2">{opportunity.tags.length ? opportunity.tags.map(tag => <Badge key={tag}>{tag}</Badge>) : <p className="text-sm text-stone-500">No tags added.</p>}</div></Card></section>
    <section><SectionHeading title="Latest analysis" subtitle="The current immutable Investment Intelligence result." />{opportunity.latestAnalysis ? <AnalysisCard opportunityId={opportunity.id} analysis={opportunity.latestAnalysis} featured /> : <Card className="mt-4 p-8 text-center"><p className="text-sm text-stone-600">This opportunity has no saved analysis yet.</p><Link href="/dashboard/investments/new" className="mt-4 inline-flex text-sm font-semibold text-stone-950 underline">Analyze property</Link></Card>}</section>
    <section><SectionHeading title="Previous analyses" subtitle="Earlier versions remain available and unchanged." /><div className="mt-4 space-y-3">{opportunity.previousAnalyses.length ? opportunity.previousAnalyses.map(analysis => <AnalysisCard key={analysis.id} opportunityId={opportunity.id} analysis={analysis} />) : <Card className="p-6 text-sm text-stone-500">No previous analysis versions.</Card>}</div></section>
    <section><SectionHeading title="Operator notes" subtitle="Plain-text context recorded by the opportunity owner." /><Card className="mt-4 divide-y divide-stone-100">{notes.length ? notes.map(note => <article key={note.id.value} className="p-5"><p className="whitespace-pre-wrap text-sm leading-6 text-stone-700">{note.body.value}</p><p className="mt-2 text-xs text-stone-400">{dateTime(note.createdAt)} · {note.author.id}</p></article>) : <p className="p-6 text-sm text-stone-500">No operator notes yet.</p>}</Card></section>
    <section><SectionHeading title="Activity" subtitle="System activity recorded with each opportunity mutation." /><Card className="mt-4 divide-y divide-stone-100">{opportunity.activity.length ? opportunity.activity.map(item => <div key={item.id} className="flex gap-4 p-5"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-stone-900" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-stone-900">{activityLabel(item.type)}</p><time className="text-xs text-stone-400">{dateTime(item.occurredAt)}</time></div><p className="mt-1 text-xs text-stone-500">Actor: {item.actorLabel}</p>{activityDetails(item.details) ? <p className="mt-2 text-sm text-stone-600">{activityDetails(item.details)}</p> : null}</div></div>) : <p className="p-6 text-sm text-stone-500">No activity recorded.</p>}</Card></section>
  </main>;
}
function AnalysisCard({ opportunityId, analysis, featured = false }: { opportunityId: string; analysis: OpportunityAnalysisVersionView; featured?: boolean }) { return <Card className={featured ? "mt-4 border-stone-300 p-6" : "p-5"}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Link href={`/dashboard/investments/opportunities/${opportunityId}/analyses/${analysis.id}`} className="font-semibold text-stone-950 hover:underline">Analysis {analysis.sequence}</Link>{analysis.current ? <Badge tone="success">Current</Badge> : null}</div><p className="mt-1 text-xs text-stone-500">Analyzed {dateTime(analysis.analyzedAt)}</p></div><Badge tone={analysis.recommendation === "pass" ? "danger" : analysis.recommendation === "wait" || analysis.recommendation === "buy-with-conditions" ? "warning" : "success"}>{label(analysis.recommendation)}</Badge></div><dl className="mt-5 grid grid-cols-3 gap-4 border-t border-stone-100 pt-4"><Fact label="Investment score" value={`${analysis.score}/${analysis.scoreMaximum}`} /><Fact label="Confidence" value={label(analysis.confidence)} /><Fact label={analysis.keyFinancialLabel} value={currency(analysis.keyFinancialValue)} /></dl></Card>; }
function SectionHeading({ title, subtitle }: { title: string; subtitle?: string }) { return <div><h2 className="text-lg font-semibold text-stone-950">{title}</h2>{subtitle ? <p className="mt-1 text-sm text-stone-500">{subtitle}</p> : null}</div>; }
function Fact({ label: factLabel, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-semibold uppercase tracking-[0.12em] text-stone-400">{factLabel}</dt><dd className="mt-1.5 text-sm font-semibold text-stone-800">{value}</dd></div>; }
function label(value: string) { return value.split("-").map(part => part ? part[0].toUpperCase() + part.slice(1) : part).join(" "); }
function date(value: Date) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(value); }
function dateTime(value: Date) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(value); }
function activityLabel(type: string) { const values: Record<string, string> = { "opportunity-created": "Opportunity created", "analysis-saved": "Analysis saved", "status-changed": "Status changed", "name-changed": "Name changed", "tags-changed": "Tags changed", "note-added": "Operator note added", "opportunity-archived": "Opportunity archived", "opportunity-restored": "Opportunity restored" }; return values[type] ?? label(type); }
function activityDetails(details: Readonly<Record<string, unknown>>) { if (typeof details.before === "string" && typeof details.after === "string") return `${label(details.before)} → ${label(details.after)}`; if (typeof details.sequence === "number") return `Saved analysis ${details.sequence}.`; if (Array.isArray(details.tags)) return details.tags.join(", "); return ""; }
function currency(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
