import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import type { PortfolioWorkspaceFilter, PortfolioWorkspaceView } from "../application";
import type { InvestmentOpportunityRoute, OpportunityStatus } from "../domain";
import { InvestmentSectionNavigation } from "./investment-section-navigation";
import { OpportunityComparisonSelector } from "./opportunity-comparison-selector";

const statuses: readonly Readonly<{ value: OpportunityStatus; label: string }>[] = [{ value: "evaluating", label: "Evaluating" }, { value: "researching", label: "Researching" }, { value: "shortlisted", label: "Shortlisted" }, { value: "offer-submitted", label: "Offer Submitted" }, { value: "under-contract", label: "Under Contract" }, { value: "acquired", label: "Acquired" }, { value: "rejected", label: "Rejected" }];
const metricLabels = { evaluating: "Evaluating", researching: "Researching", shortlisted: "Shortlisted", underContract: "Under Contract", acquired: "Acquired" } as const;
export function PortfolioWorkspace({ view, filter }: { view: PortfolioWorkspaceView; filter: PortfolioWorkspaceFilter }) {
  return <main className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-stone-500">Investment portfolio</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-stone-950 sm:text-4xl">Manage every acquisition opportunity.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-600">Track evaluated deals from initial research through acquisition without losing their analysis history.</p></div><InvestmentSectionNavigation active="portfolio" /></header>
    <section aria-label="Portfolio metrics" className="grid grid-cols-2 gap-3 md:grid-cols-5">{Object.entries(metricLabels).map(([key, label]) => <Card key={key} className="p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-500">{label}</p><p className="mt-2 text-2xl font-semibold text-stone-950">{view.metrics[key as keyof typeof view.metrics]}</p></Card>)}</section>
    <PortfolioFilters filter={filter} />
    <OpportunityComparisonSelector opportunities={view.opportunities} />
    {view.empty ? <PortfolioEmptyState filtered={Boolean(filter.search || filter.route || filter.statuses?.length || filter.includeArchived)} /> : <section aria-label="Opportunities" className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{view.opportunities.map(opportunity => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</section>}
    {view.nextCursor ? <div className="flex justify-center"><Link href={portfolioHref(filter, view.nextCursor)} className="rounded-full border border-stone-300 bg-white px-5 py-2.5 text-sm font-semibold text-stone-800 shadow-sm hover:border-stone-400">Next page</Link></div> : null}
  </main>;
}
function PortfolioFilters({ filter }: { filter: PortfolioWorkspaceFilter }) { return <form className="grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_auto_auto_auto]" action="/dashboard/investments/portfolio">
  <label className="sr-only" htmlFor="portfolio-search">Search opportunities</label><input id="portfolio-search" name="search" defaultValue={filter.search} placeholder="Search address, name, or tag" className="min-h-11 rounded-xl border border-stone-200 px-4 text-sm outline-none focus:border-stone-500" />
  <label className="sr-only" htmlFor="portfolio-status">Status</label><select id="portfolio-status" name="status" defaultValue={filter.statuses?.[0] ?? ""} className="min-h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm text-stone-700"><option value="">All statuses</option>{statuses.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select>
  <label className="sr-only" htmlFor="portfolio-route">Route</label><select id="portfolio-route" name="route" defaultValue={filter.route ?? ""} className="min-h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm text-stone-700"><option value="">All routes</option><option value="purchase">Purchase</option><option value="rental-arbitrage">Rental Arbitrage</option></select>
  <div className="flex items-center gap-3"><label className="flex items-center gap-2 whitespace-nowrap text-sm text-stone-600"><input type="checkbox" name="archived" value="true" defaultChecked={filter.includeArchived} className="h-4 w-4 rounded border-stone-300" />Archived</label><button className="min-h-11 rounded-xl bg-stone-950 px-5 text-sm font-semibold text-white">Filter</button></div>
</form>; }
function OpportunityCard({ opportunity }: { opportunity: PortfolioWorkspaceView["opportunities"][number] }) { return <Card className="flex min-h-72 flex-col p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-lg font-semibold text-stone-950">{opportunity.address}</p><p className="mt-1 truncate text-sm text-stone-500">{opportunity.name}</p></div><Badge tone={recommendationTone(opportunity.recommendation)}>{formatLabel(opportunity.recommendation ?? "Not analyzed")}</Badge></div><div className="mt-5 flex flex-wrap gap-2"><Badge>{opportunity.route === "purchase" ? "Purchase" : "Rental Arbitrage"}</Badge><Badge tone={statusTone(opportunity.status)}>{formatLabel(opportunity.status)}</Badge>{opportunity.archived ? <Badge>Archived</Badge> : null}</div><dl className="mt-6 grid grid-cols-3 gap-3 border-y border-stone-100 py-4"><Stat label="Score" value={opportunity.score === undefined ? "—" : `${opportunity.score}/${opportunity.scoreMaximum ?? 100}`} /><Stat label="Confidence" value={formatLabel(opportunity.confidence ?? "—")} /><Stat label="Analyzed" value={opportunity.lastAnalyzedAt ? formatDate(opportunity.lastAnalyzedAt) : "Never"} /></dl><div className="mt-auto flex items-center justify-between gap-3 pt-5"><Link href={`/dashboard/investments/portfolio/${opportunity.id}`} className="text-sm font-semibold text-stone-950 hover:underline">View opportunity</Link><Link href="/dashboard/investments" className="rounded-full border border-stone-200 px-3 py-1.5 text-xs font-semibold text-stone-600 hover:border-stone-400">Analyze property</Link></div></Card>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-semibold uppercase tracking-wide text-stone-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-stone-800">{value}</dd></div>; }
function PortfolioEmptyState({ filtered }: { filtered: boolean }) { return <Card className="px-6 py-16 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-stone-100 text-lg">⌂</div><h2 className="mt-5 text-xl font-semibold text-stone-950">{filtered ? "No opportunities match these filters." : "No saved opportunities yet."}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-600">{filtered ? "Adjust the status, route, archive, or search filters to see more opportunities." : "Run an Investment Analysis to create your first opportunity."}</p><Link href={filtered ? "/dashboard/investments/portfolio" : "/dashboard/investments"} className="mt-6 inline-flex rounded-full bg-stone-950 px-5 py-2.5 text-sm font-semibold text-white">{filtered ? "Clear filters" : "Analyze Property"}</Link></Card>; }
function portfolioHref(filter: PortfolioWorkspaceFilter, cursor: string) { const params = new URLSearchParams(); if (filter.search) params.set("search", filter.search); if (filter.statuses?.[0]) params.set("status", filter.statuses[0]); if (filter.route) params.set("route", filter.route); if (filter.includeArchived) params.set("archived", "true"); params.set("cursor", cursor); return `/dashboard/investments/portfolio?${params}`; }
function formatLabel(value: string) { return value.split("-").map(part => part ? part[0].toUpperCase() + part.slice(1) : part).join(" "); }
function formatDate(value: Date) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(value); }
function statusTone(status: OpportunityStatus): "neutral" | "success" | "warning" | "danger" | "dark" { if (status === "acquired") return "success"; if (status === "rejected") return "danger"; if (status === "under-contract" || status === "offer-submitted") return "warning"; if (status === "shortlisted") return "dark"; return "neutral"; }
function recommendationTone(value?: string): "neutral" | "success" | "warning" | "danger" { if (value === "strong-buy" || value === "buy") return "success"; if (value === "pass") return "danger"; if (value === "wait" || value === "buy-with-conditions") return "warning"; return "neutral"; }
export function parsePortfolioRoute(value?: string): InvestmentOpportunityRoute | undefined { return value === "purchase" || value === "rental-arbitrage" ? value : undefined; }
export function parsePortfolioStatus(value?: string): OpportunityStatus | undefined { return statuses.some(item => item.value === value) ? value as OpportunityStatus : undefined; }
