export const PROPERTY_PROJECTION_VERSION="property-projection.v1" as const;
export type PropertyProjectionValue=Readonly<{state:"available";value:string|readonly string[]}|{state:"missing"|"unavailable"|"not-applicable";reason:string;recovery?:string}>;
export type CanonicalPropertyProjection=Readonly<{
 projectionId:string;projectionVersion:typeof PROPERTY_PROJECTION_VERSION;version:string;generatedAt:string;updatedAt:string;source:"property-domain";
 identity:Readonly<{propertyId:string;workspaceId:string;name:string;status:string;slug:string}>;
 operational:Readonly<{address:PropertyProjectionValue;wifi:PropertyProjectionValue;parking:PropertyProjectionValue;checkInTime:PropertyProjectionValue;checkoutTime:PropertyProjectionValue;lockInstructions:PropertyProjectionValue;accessCode:PropertyProjectionValue;emergencyContact:PropertyProjectionValue;hostContact:PropertyProjectionValue;houseRules:PropertyProjectionValue;trashInstructions:PropertyProjectionValue;thermostatInstructions:PropertyProjectionValue}>;
 guest:Readonly<{amenities:readonly string[];featuredImage:PropertyProjectionValue;timezone:PropertyProjectionValue}>;
 health:Readonly<{status:"ready"|"needs-property-information"|"needs-operational-review"|"archived"|"inactive";publishable:boolean;missing:readonly string[];guidance:string}>;
 freshness:Readonly<{status:"current"|"stale"|"unavailable";lastUpdatedAt:string;synchronizationStatus:"synchronized"|"stale"|"unavailable"}>;
 navigation:Readonly<{workspace:string;operationalSettings:string;amenities:string;contacts:string;houseRules:string}>;
}>;
export type PropertyProjectionSource=Readonly<{id:string;workspaceId:string;name:string;slug?:string|null;status:string;address?:string|null;city?:string|null;state?:string|null;timezone?:string|null;checkInTime?:string|null;checkoutTime?:string|null;amenities?:readonly string[];houseRules?:readonly string[];featuredImage?:string|null;updatedAt:string}>;
export type PropertyProjectionDrift=Readonly<{status:"current"|"changed"|"unknown";changedFields:readonly Readonly<{key:string;label:string;published:unknown;current:unknown}>[];reviewRecommended:boolean;summary:string}>;

const required=["address","wifi","parking","checkInTime","checkoutTime","emergencyContact"] as const;
export function buildCanonicalPropertyProjection(source:PropertyProjectionSource,generatedAt=new Date().toISOString()):CanonicalPropertyProjection{
 const amenity=(...labels:string[])=>findInstruction(source.amenities??[],labels),address=[source.address,[source.city,source.state].filter(Boolean).join(", ")].filter(Boolean).join(", ");
 const operational={
  address:value(address,"Property address is missing.","Update property location"),
  wifi:value(amenity("wi-fi","wifi"),"Wi-Fi instructions are missing.","Update property amenities"),
  parking:value(amenity("parking"),"Parking instructions are missing.","Update property amenities"),
  checkInTime:value(source.checkInTime,"Check-in time is missing.","Update operational settings"),
  checkoutTime:value(source.checkoutTime,"Checkout time is missing.","Update operational settings"),
  lockInstructions:value(amenity("lock instructions","door instructions","access instructions"),"Lock instructions are missing.","Update operational settings"),
  accessCode:value(amenity("access code","door code"),"Access code is missing.","Update operational settings"),
  emergencyContact:value(amenity("emergency contact"),"Emergency contact is missing.","Update property contacts"),
  hostContact:value(amenity("host contact","host phone"),"Host contact is missing.","Update property contacts"),
  houseRules:(source.houseRules?.length?available(Object.freeze([...source.houseRules])):missing("House rules are missing.","Update house rules")),
  trashInstructions:value(amenity("trash","garbage"),"Trash instructions are not recorded.","Update operational settings"),
  thermostatInstructions:value(amenity("thermostat","hvac"),"Thermostat instructions are not recorded.","Update operational settings"),
 } as const;
 const missingRequired=required.filter(key=>operational[key].state!=="available"),status=source.status==="archived"?"archived":source.status!=="active"?"inactive":missingRequired.length?"needs-property-information":"ready",publishable=status==="ready",version=`ppv1-${hash(stable({identity:{id:source.id,status:source.status},operational,amenities:source.amenities??[],updatedAt:source.updatedAt}))}`;
 const workspace=`/dashboard/workspace/properties?property=${source.id}`;return deepFreeze({projectionId:`property:${source.id}`,projectionVersion:PROPERTY_PROJECTION_VERSION,version,generatedAt,updatedAt:source.updatedAt,source:"property-domain",identity:{propertyId:source.id,workspaceId:source.workspaceId,name:source.name,status:source.status,slug:source.slug??source.id},operational,guest:{amenities:Object.freeze([...(source.amenities??[])]),featuredImage:value(source.featuredImage,"No featured property image is available."),timezone:value(source.timezone,"Property timezone is unavailable.")},health:{status,publishable,missing:Object.freeze(missingRequired),guidance:healthGuidance(status,missingRequired)},freshness:{status:"current",lastUpdatedAt:source.updatedAt,synchronizationStatus:"synchronized"},navigation:{workspace,operationalSettings:`${workspace}&section=operations`,amenities:`${workspace}&section=amenities`,contacts:`${workspace}&section=contacts`,houseRules:`${workspace}&section=rules`}});
}
export function propertyProjectionVariables(projection:CanonicalPropertyProjection,guidebookUrl:string){return deepFreeze({propertyName:projection.identity.name,wifi:text(projection.operational.wifi),parking:text(projection.operational.parking),address:text(projection.operational.address),hostName:text(projection.operational.hostContact),hostPhone:text(projection.operational.hostContact),guidebookUrl,checkInTime:text(projection.operational.checkInTime),checkOutTime:text(projection.operational.checkoutTime)});}
export function propertyProjectionSnapshot(projection:CanonicalPropertyProjection){return deepFreeze({projectionId:projection.projectionId,projectionVersion:projection.projectionVersion,propertyVersion:projection.version,source:projection.source,updatedAt:projection.updatedAt,resolvedValues:{propertyName:projection.identity.name,address:text(projection.operational.address),wifi:text(projection.operational.wifi),parking:text(projection.operational.parking),checkInTime:text(projection.operational.checkInTime),checkoutTime:text(projection.operational.checkoutTime),lockInstructions:text(projection.operational.lockInstructions),accessCode:text(projection.operational.accessCode),emergencyContact:text(projection.operational.emergencyContact),hostContact:text(projection.operational.hostContact),houseRules:list(projection.operational.houseRules),trashInstructions:text(projection.operational.trashInstructions),thermostatInstructions:text(projection.operational.thermostatInstructions)}});}
export function detectPropertyProjectionDrift(current:CanonicalPropertyProjection,published?:Readonly<{propertyVersion?:string;resolvedValues?:Readonly<Record<string,unknown>>}>|null):PropertyProjectionDrift{
 if(!published)return deepFreeze({status:"unknown",changedFields:[],reviewRecommended:false,summary:"No published property projection is available for comparison."});
 if(published.propertyVersion===current.version)return deepFreeze({status:"current",changedFields:[],reviewRecommended:false,summary:"The published guidebook uses the current property projection."});
 const currentValues=propertyProjectionSnapshot(current).resolvedValues,prior=published.resolvedValues??{},labels:Record<string,string>={wifi:"Wi-Fi",parking:"Parking instructions",checkInTime:"Check-in time",checkoutTime:"Checkout time",lockInstructions:"Lock instructions",accessCode:"Access code",emergencyContact:"Emergency contact",hostContact:"Host contact",houseRules:"House rules",trashInstructions:"Trash instructions",thermostatInstructions:"Thermostat instructions",address:"Address",propertyName:"Property name"};
 const changedFields=Object.keys(currentValues).filter(key=>stable(prior[key])!==stable(currentValues[key as keyof typeof currentValues])).map(key=>({key,label:labels[key]??key,published:prior[key],current:currentValues[key as keyof typeof currentValues]}));
 return deepFreeze({status:changedFields.length?"changed":"current",changedFields,reviewRecommended:changedFields.length>0,summary:changedFields.length?`${changedFields.length} operational ${changedFields.length===1?"field has":"fields have"} changed since publication.`:"The property projection version changed without guest-facing operational drift."});
}
function findInstruction(values:readonly string[],labels:readonly string[]){for(const item of values){const normalized=item.toLowerCase();for(const label of labels){const prefix=`${label.toLowerCase()}:`;if(normalized.startsWith(prefix))return item.slice(prefix.length).trim();if(normalized===label.toLowerCase())return item;}}return null;}
function value(input:string|null|undefined,reason:string,recovery?:string):PropertyProjectionValue{return input?.trim()?available(input.trim()):missing(reason,recovery);}
function available(value:string|readonly string[]):PropertyProjectionValue{return Object.freeze({state:"available",value});}
function missing(reason:string,recovery?:string):PropertyProjectionValue{return Object.freeze({state:"missing",reason,...(recovery?{recovery}:{})});}
function text(value:PropertyProjectionValue){return value.state==="available"&&typeof value.value==="string"?value.value:null;}
function list(value:PropertyProjectionValue){return value.state==="available"&&Array.isArray(value.value)?value.value:null;}
function healthGuidance(status:CanonicalPropertyProjection["health"]["status"],missingFields:readonly string[]){if(status==="archived")return"Restore the property before publishing a guidebook.";if(status==="inactive")return"Activate the property and review operational information before publishing.";if(missingFields.length)return`Complete ${missingFields.join(", ")} in the Property workspace before publishing.`;return"Canonical property information is complete enough for guidebook publishing.";}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${key}:${stable(item)}`).join(",")}}`;return JSON.stringify(value);}
function hash(value:string){let output=2166136261;for(let index=0;index<value.length;index++){output^=value.charCodeAt(index);output=Math.imul(output,16777619)}return(output>>>0).toString(16).padStart(8,"0");}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(deepFreeze)}return value;}
