import { describe,expect,it } from "vitest";
import { AuthoritativeEntitlementEvaluator, CAPABILITY_REGISTRY, INITIAL_OFFER_CATALOG, LIMIT_STRATEGIES, ONBOARDING_REGISTRY, PRODUCT_FAMILY_REGISTRY, activateOfferEntitlements, composeLimit, publicOfferProjection, validateOfferDefinition, type Entitlement, type EntitlementAuthorization, type EntitlementRepository, type OfferDefinition } from ".";

const time="2026-08-11T12:00:00.000Z",scope={type:"customer_account"as const,customerAccountId:"account-1"};
const entitlement=(extra:Partial<Entitlement>={}):Entitlement=>({id:"ent-1",tenantId:"tenant-1",customerAccountId:"account-1",capabilityCode:"guidebook.create",resourceScope:scope,source:"offer_activation",sourceReferenceId:"activation-1",offerCode:"guidebook.standalone",offerVersion:1,status:"active",effectiveFrom:"2026-08-10T00:00:00.000Z",createdAt:time,updatedAt:time,revision:1,...extra});
class Repo implements EntitlementRepository{values:Entitlement[]=[];activation:readonly Entitlement[]|null=null;async listForAccount(){return this.values}async findActivation(){return this.activation}async activate(values:readonly Entitlement[]){this.values=[...values];this.activation=values;return values}async transition(value:Entitlement){return value}}
const authorization:EntitlementAuthorization={authenticate:async()=>true,isTenantMember:async()=>true,isResourceAuthorized:async()=>true,canManageEntitlements:async()=>true};

describe("CA-001A commercial catalog",()=>{
 it("registers four stable standalone families and complete vocabularies",()=>{expect(Object.keys(PRODUCT_FAMILY_REGISTRY)).toEqual(["hpm","guidebook_studio","furnishing","investment_intelligence"]);expect(Object.values(PRODUCT_FAMILY_REGISTRY).every(value=>value.standaloneEligible)).toBe(true);expect(CAPABILITY_REGISTRY["guidebook.property.create_standalone"].productFamily).toBe("guidebook_studio");expect(ONBOARDING_REGISTRY.complete_guidebook_intake.blocksActivation).toBe(true)});
 it("keeps unapproved initial commercial packages draft and absent from public discovery",()=>{expect(INITIAL_OFFER_CATALOG.length).toBeGreaterThanOrEqual(11);expect(INITIAL_OFFER_CATALOG.every(value=>value.status==="draft"&&value.priceDefinition===undefined&&value.includedCapabilities.length===0)).toBe(true)});
 it("rejects invalid pricing, recurring intervals, capabilities, limits and custom quote amounts",()=>{const base=INITIAL_OFFER_CATALOG[0];expect(()=>validateOfferDefinition({...base,status:"active"})).toThrowError(expect.objectContaining({code:"offer_price_required"}));expect(()=>validateOfferDefinition({...base,status:"active",priceDefinition:{currency:"usd",amountMinor:1,interval:"month"}})).toThrowError(expect.objectContaining({code:"offer_price_invalid"}));expect(()=>validateOfferDefinition({...base,status:"active",priceDefinition:{currency:"USD",amountMinor:1}})).toThrowError(expect.objectContaining({code:"offer_interval_required"}));expect(()=>validateOfferDefinition({...INITIAL_OFFER_CATALOG[2],priceDefinition:{currency:"USD",amountMinor:1}})).toThrowError(expect.objectContaining({code:"custom_quote_has_price"}));expect(()=>validateOfferDefinition({...base,limits:[{code:"property_count",allowance:{kind:"finite",value:-1},enforcement:"hard"}]})).toThrowError(expect.objectContaining({code:"limit_value_invalid"}))});
 it("removes provider references from public projections",()=>{const active={...INITIAL_OFFER_CATALOG[2],status:"active",includedCapabilities:[{capability:"hpm.workspace.access",resourceType:"workspace"}],priceDefinition:undefined}as OfferDefinition;const result=publicOfferProjection(validateOfferDefinition(active));expect(result.action).toBe("contact_sales");expect(JSON.stringify(result)).not.toContain("externalPriceReference")});
 it("uses one registered deterministic strategy per limit",()=>{expect(Object.keys(LIMIT_STRATEGIES)).toHaveLength(8);expect(composeLimit("property_count",[{allowance:{kind:"finite",value:2},specificity:1},{allowance:{kind:"finite",value:5},specificity:1}])).toEqual({kind:"finite",value:5});expect(composeLimit("investment_analysis_count_per_period",[{allowance:{kind:"finite",value:2},specificity:1},{allowance:{kind:"finite",value:5},specificity:1}])).toEqual({kind:"finite",value:7});expect(composeLimit("guidebook_count",[{allowance:{kind:"unlimited"},specificity:1}])).toEqual({kind:"unlimited"})});
});

describe("CA-001A entitlement evaluation",()=>{
 it("allows an active scoped grant and fails unknown capabilities closed",async()=>{const repo=new Repo();repo.values=[entitlement()];const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization);await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"guidebook.create",asOf:new Date(time)})).resolves.toMatchObject({allowed:true,entitlementId:"ent-1"});await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"invented.capability",asOf:new Date(time)})).resolves.toMatchObject({allowed:false,reason:"unknown_capability"})});
 it.each([["pending","entitlement_pending"],["suspended","entitlement_suspended"],["expired","entitlement_expired"],["revoked","entitlement_revoked"]]as const)("denies %s grants",async(status,reason)=>{const repo=new Repo();repo.values=[entitlement({status})];const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization);await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"guidebook.create",asOf:new Date(time)})).resolves.toMatchObject({allowed:false,reason})});
 it("does not authorize adjacent resources",async()=>{const repo=new Repo();repo.values=[entitlement({resourceScope:{type:"guidebook",guidebookId:"guide-1"}})];const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization);await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"guidebook.create",resource:{type:"guidebook",id:"guide-2"},asOf:new Date(time)})).resolves.toMatchObject({allowed:false,reason:"resource_out_of_scope"})});
 it("preserves access from another grant after one source is revoked",async()=>{const repo=new Repo();repo.values=[entitlement({id:"revoked",status:"revoked"}),entitlement({id:"valid",sourceReferenceId:"activation-2"})];const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization);await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"guidebook.create",asOf:new Date(time)})).resolves.toMatchObject({allowed:true,entitlementId:"valid"})});
 it("applies hard limits at the boundary",async()=>{const repo=new Repo();repo.values=[entitlement()];const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization,{resolve:async()=>({code:"guidebook_count",allowance:{kind:"finite",value:1},usage:1,enforcement:"hard"})});await expect(evaluator.execute({actorId:"actor",tenantId:"tenant-1",customerAccountId:"account-1",capability:"guidebook.create",asOf:new Date(time)})).resolves.toMatchObject({allowed:false,reason:"limit_reached"})});
 it("activates idempotently through an authorized boundary",async()=>{const repo=new Repo(),offer=validateOfferDefinition({...INITIAL_OFFER_CATALOG[3],status:"active",priceDefinition:{currency:"USD",amountMinor:9900},includedCapabilities:[{capability:"guidebook.create",resourceType:"guidebook"}]});const input={actorId:"admin",tenantId:"tenant-1",customerAccountId:"account-1",offer,source:"offer_activation"as const,sourceReferenceId:"controlled-1",resourceScope:scope,effectiveFrom:time,idempotencyKey:"key-1",reasonCode:"controlled_test",now:time};const first=await activateOfferEntitlements({repository:repo,authorization},input),second=await activateOfferEntitlements({repository:repo,authorization},input);expect(first).toEqual(second);expect(repo.values).toHaveLength(1)});
 it("does not let administrative role imply commercial access",async()=>{const repo=new Repo();const evaluator=new AuthoritativeEntitlementEvaluator(repo,authorization);await expect(evaluator.execute({actorId:"admin",tenantId:"tenant-1",customerAccountId:"account-1",capability:"hpm.workspace.access",asOf:new Date(time)})).resolves.toMatchObject({allowed:false,reason:"not_entitled"})});
});
