import { describe, expect, it } from "vitest";
import { OC001_CATALOG_FINGERPRINT, OC001_OFFER_REGISTRY, oc001PurchaseSnapshot, validateOc001Configuration, validateOc001Offer } from ".";

describe("OC-001 immutable offer catalog",()=>{
  it("covers every family with complete, uniquely versioned definitions",()=>{expect(new Set(OC001_OFFER_REGISTRY.map(value=>value.family))).toEqual(new Set(["hpm","guidebook","furnishing","investment_intelligence"]));expect(new Set(OC001_OFFER_REGISTRY.map(value=>`${value.offerCode}@${value.version}`)).size).toBe(OC001_OFFER_REGISTRY.length);for(const offer of OC001_OFFER_REGISTRY)expect(validateOc001Offer(offer)).toBe(offer);expect(OC001_CATALOG_FINGERPRINT).toMatch(/^[a-f0-9]{64}$/)});
  it("keeps Guidebook and Investment independent from HPM",()=>{for(const offer of OC001_OFFER_REGISTRY.filter(value=>value.family==="guidebook"||value.family==="investment_intelligence")){expect(offer.entitlements.some(value=>value.capabilityCode.startsWith("hpm."))).toBe(false);expect(offer.onboardingTemplateCode).not.toBe("hpm.v1")}});
  it("uses exact annual totals and never a browser-derived amount",()=>{const starter=OC001_OFFER_REGISTRY.find(value=>value.offerCode==="hpm.starter")!;expect(starter.prices.find(value=>value.cadence==="year")?.amountMinor).toBe(95040);const snapshot=oc001PurchaseSnapshot(starter,"hpm.starter.annual",{billing_cadence:"year"});expect(snapshot.amountMinor).toBe(95040);expect(snapshot.checksum).toMatch(/^[a-f0-9]{64}$/)});
  it("rejects unknown, incompatible, and out-of-range configuration",()=>{const furnishing=OC001_OFFER_REGISTRY.find(value=>value.offerCode==="furnishing.essential")!;expect(()=>validateOc001Configuration(furnishing,{room_count:3})).toThrow("OC001_CONFIGURATION_INVALID");expect(()=>validateOc001Configuration(furnishing,{room_count:1,price:1})).toThrow("OC001_CONFIGURATION_UNKNOWN")});
  it("keeps consultation offers out of Checkout",()=>{const enterprise=OC001_OFFER_REGISTRY.find(value=>value.offerCode==="hpm.enterprise")!;expect(enterprise.purchaseAction).toBe("request_consultation");expect(enterprise.prices).toHaveLength(0);expect(enterprise.entitlements).toHaveLength(0)});
});
