import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const sql=readFileSync("supabase/migrations/20260812130000_oc001_purchasable_offer_catalog.sql","utf8");
const approved=readFileSync("supabase/migrations/20260812131000_oc001_approved_offer_matrix.sql","utf8");
const effects=readFileSync("supabase/migrations/20260813110000_oc001_commercial_effects.sql","utf8");
describe("OC-001 persistence and security",()=>{
  it("adds only catalog and purchase-intent concerns",()=>{for(const table of["commercial_offer_details","commercial_price_versions","commercial_catalog_publications","commercial_offer_verification_results","commercial_offer_replacements","commercial_purchase_intents","commercial_catalog_audit_events"])expect(sql).toContain(`create table public.${table}`);expect(sql).not.toMatch(/create table public\.(customer_accounts|commercial_entitlements|onboarding_cases|first_value_journeys)/)});
  it("enables RLS, denies anonymous mutation, and exposes only a safe projection",()=>{for(const table of["commercial_offer_details","commercial_price_versions","commercial_catalog_publications","commercial_offer_verification_results","commercial_offer_replacements","commercial_purchase_intents","commercial_catalog_audit_events"])expect(sql).toContain(`alter table public.${table} enable row level security`);expect(sql).toMatch(/revoke all on[\s\S]+from anon/);expect(sql).toContain("read_published_offer_catalog");expect(sql).not.toMatch(/webhook_secret|secret_key|raw_payload|payment_method|card_number/i)});
  it("adds the approved configuration, credit, hosting, and allowance boundaries with RLS",()=>{for(const table of["commercial_configuration_approvals","commercial_upgrade_credits","guidebook_hosting_terms","investment_credit_ledgers"]){expect(approved).toContain(`create table public.${table}`);expect(approved).toContain(`alter table public.${table} enable row level security`)}expect(approved).toContain("d.launch_state<>'deferred'");expect(approved).not.toMatch(/webhook_secret|secret_key|raw_payload|payment_method|card_number/i)});
  it("requires verified publication and exact live mapping before Checkout appears",()=>{expect(sql).toContain("p.verification_status='passed'");expect(sql).toContain("m.account_mode='live'");expect(sql).toContain("m.amount_minor=v.amount_minor");expect(sql).toContain("OC001_PRICE_MAPPING_UNAVAILABLE")});
  it("binds purchase intents to canonical account, offer, price, policies and entitlements",()=>{for(const value of["customer_account_id","offer_code","offer_version","price_code","price_version","configuration_snapshot","policy_snapshot","entitlement_snapshot","commercial_snapshot_checksum","idempotency_key_hash"])expect(sql).toContain(value)});
  it("requires canonical verification evidence and audited entitlement transitions",()=>{expect(sql).toContain("commercial_offer_verification_results");expect(sql).toContain("commercial_catalog_publication_verification_fk");expect(sql).toContain("transition_oc001_agreement_entitlements");expect(sql).toContain("commercial_entitlement_status_history")});
  it("connects approved limits and consumable scope to active agreements",()=>{expect(effects).toContain("initialize_oc001_agreement_effects");expect(effects).toContain("commercial_limit_grants");expect(effects).toContain("investment_credit_consumptions")});
});
