"use client";
import { useState } from "react";
import { submitFurnishingActivationCommand } from "./actions";

export default function ActivationControls({ release, capabilities }: { release: any; capabilities: readonly any[] }) {
  const [reason, setReason] = useState(""); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  async function submit() { if (!reason.trim()) { setMessage("A reason is required."); return; } if (!window.confirm("Confirm this activation-control change. The FS-008A safe ceiling remains enforced.")) return; setPending(true); setMessage("Submitting…"); try { const result = await submitFurnishingActivationCommand({ command: "global-kill-switch", target: "global", targetId: String(release?.id ?? "global"), state: "disabled", expectedVersion: Number(release?.optimistic_version ?? 1), reason, actorId: "current-admin", actorRole: "admin", correlationId: crypto.randomUUID(), idempotencyKey: crypto.randomUUID() }); setMessage(result.ok ? "Control updated." : `${result.code}: ${result.message}`); } catch { setMessage("Unexpected error. Retry safely."); } finally { setPending(false); } }
  return <section className="space-y-6"><div className="rounded-2xl border-2 border-red-300 bg-red-50 p-6"><h2 className="text-xl font-semibold">Global kill switch</h2><p className="mt-2">Prominent emergency control. It always overrides every lower-level enablement.</p><button type="button" disabled={pending} onClick={submit} className="mt-4 rounded-xl bg-red-700 px-4 py-2 font-semibold text-white">{pending ? "Applying…" : "Restore / activate kill switch"}</button></div><div className="rounded-2xl border p-6"><label htmlFor="control-reason" className="font-semibold">Required reason</label><textarea id="control-reason" value={reason} onChange={e => setReason(e.target.value)} disabled={pending} className="mt-2 min-h-20 w-full rounded-xl border p-3" aria-describedby="control-help" /><p id="control-help" className="mt-2 text-sm text-stone-600">Every command includes the current version and requires confirmation. Public activation remains unavailable during FS-008A.</p>{message && <p role="status" className="mt-3">{message}</p>}</div><div className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Capability states</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{capabilities.map(item => <div className="flex justify-between rounded-xl bg-stone-50 p-3" key={item.capability}><span>{item.capability}</span><span className="font-semibold">{item.enabled ? "enabled (safe ceiling rejects effects)" : "disabled"}</span></div>)}</div><p className="mt-4 text-sm text-stone-600">Release: {release?.milestone ?? "FS-008A"} · Policy: {release?.policy_version ?? "fs008a-v1"}</p></div></section>;
  const controls = ["workspace-kill-switch", "workspace-state", "cohort-grant", "cohort-expiration", "cohort-revoke", "capability-state"];
  return <section className="space-y-6"><div className="rounded-2xl border-2 border-red-300 bg-red-50 p-6"><h2 className="text-xl font-semibold">Global kill switch</h2><p className="mt-2">Prominent emergency control. It always overrides every lower-level enablement.</p><button type="button" disabled={pending} onClick={submit} className="mt-4 rounded-xl bg-red-700 px-4 py-2 font-semibold text-white">{pending ? "Applying…" : "Restore / activate kill switch"}</button></div><div className="rounded-2xl border p-6"><label htmlFor="control-reason" className="font-semibold">Required reason</label><textarea id="control-reason" value={reason} onChange={e => setReason(e.target.value)} disabled={pending} className="mt-2 min-h-20 w-full rounded-xl border p-3" aria-describedby="control-help" /><p id="control-help" className="mt-2 text-sm text-stone-600">Every command includes the current version and requires confirmation. Public activation remains unavailable during FS-008A.</p>{message && <p role="status" className="mt-3">{message}</p>}</div><div className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Workspace, cohort, and capability controls</h2><p className="mt-2 text-sm text-stone-600">All controls validate canonical tenant scope, expected version, reason, and idempotency on the server. No roles, memberships, entitlements, or commercial effects can be granted.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{controls.map(control => <button key={control} type="button" disabled={pending} onClick={submit} className="rounded-xl border px-4 py-3 text-left hover:bg-stone-50">{control}</button>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{capabilities.map(item => <div className="flex justify-between rounded-xl bg-stone-50 p-3" key={item.capability}><span>{item.capability}</span><span className="font-semibold">{item.enabled ? "enabled (safe ceiling rejects effects)" : "disabled"}</span></div>)}</div><p className="mt-4 text-sm text-stone-600">Release: {release?.milestone ?? "FS-008A"} · Policy: {release?.policy_version ?? "fs008a-v1"}</p></div></section>;
}
