import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
describe("FS-008A P2.4B Admin activation surface", () => {
  it("requires Admin route protection and exposes the internal-only safe ceiling", () => { const page = readFileSync("src/app/(admin)/admin/furnishing/activation/page.tsx", "utf8"); expect(page).toContain("requireRole([\"admin\"])"); expect(page).toContain("Internal-only ceiling"); expect(page).not.toContain("FS-FULL\""); });
  it("has accessible reason, pending, refresh, and status behavior", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); expect(view).toContain("aria-describedby"); expect(view).toContain('role="status"'); expect(view).toContain("disabled={Boolean(pending)}"); expect(view).toContain("router.refresh()"); });
  it("hands commands to a server-only action with confirmation and concurrency fields", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); expect(view).toContain("submitFurnishingActivationCommand"); expect(view).toContain("expectedVersion"); expect(view).toContain("window.confirm"); });
  it("renders every remaining control family", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); for (const value of ["workspace-kill-switch", "workspace-state", "cohort-grant", "cohort-expiration", "cohort-revoke", "capability-state"]) expect(view).toContain(value); });
  it("maps governed controls to explicit states without one hard-coded submit payload",()=>{const view=readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx","utf8");for(const value of ["Set global state: internal","Lift global kill switch","Enable controlled workspace","Engage global kill switch"])expect(view).toContain(value);expect(view).toContain("activationControlPayload(control,reason)");expect(view).not.toContain('submitFurnishingActivationCommand({ command: "global-kill-switch"')});
});
