import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { workspaceControlsFor } from "./activation-controls";
describe("FS-008A P2.4B Admin activation surface", () => {
  it("requires Admin route protection and exposes the internal-only safe ceiling", () => { const page = readFileSync("src/app/(admin)/admin/furnishing/activation/page.tsx", "utf8"); expect(page).toContain("requireRole([\"admin\"])"); expect(page).toContain("Internal-only ceiling"); expect(page).not.toContain("FS-FULL\""); });
  it("has accessible reason, pending, server-bound loading, refresh, and status behavior", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); expect(view).toContain("aria-describedby"); expect(view).toContain('role="status"'); expect(view).toContain("useTransition"); expect(view).toContain("router.replace"); expect(view).toContain("workspaceId="); expect(view).toContain("Loading authoritative workspace"); });
  it("hands commands to a server-only action with confirmation and concurrency fields", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); expect(view).toContain("submitFurnishingActivationCommand"); expect(view).toContain("expectedVersion"); expect(view).toContain("window.confirm"); });
  it("renders every remaining control family", () => { const view = readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx", "utf8"); for (const value of ["workspace-kill-switch", "workspace-state", "cohort-grant", "cohort-expiration", "cohort-revoke", "capability-state"]) expect(view).toContain(value); });
  it("maps governed controls to explicit states without one hard-coded submit payload",()=>{const view=readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx","utf8");for(const value of ["Set global state: internal","Lift global kill switch","Enable controlled workspace","Engage global kill switch"])expect(view).toContain(value);expect(view).toContain("activationControlPayload(control,reason)");expect(view).not.toContain('submitFurnishingActivationCommand({ command: "global-kill-switch"')});
  it("resolves global and submitted workspace controls through the Admin-safe boundary",()=>{const page=readFileSync("src/app/(admin)/admin/furnishing/activation/page.tsx","utf8");expect(page).toContain('searchParams:Promise<{workspaceId?:string}>');expect(page).toContain('p_target:"global",p_target_id:"global"');expect(page).toContain('rpc("resolve_furnishing_activation_control"');expect(page).not.toContain('from("furnishing_activation_releases")');expect(page).not.toContain('from("furnishing_activation_workspaces")');expect(page).not.toContain('from("furnishing_activation_capabilities")')});
  it("validates and server-binds a direct workspace URL before resolving exact scoped state",()=>{const page=readFileSync("src/app/(admin)/admin/furnishing/activation/page.tsx","utf8");expect(page).toContain("UUID.test(workspaceId)");expect(page).toContain('p_target:"workspace",p_target_id:workspaceId,p_tenant_id:workspaceId');for(const status of ['"invalid"','"not_found"','"forbidden"','"found"'])expect(page).toContain(status)});
  it("renders authoritative identity, revocation, kill switch, and version without a version-zero client fallback",()=>{const view=readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx","utf8");for(const value of ["Authoritative version","workspace.revoked_at","workspace.kill_switch","workspace.optimistic_version"])expect(view).toContain(value);expect(view).not.toContain("selected?.optimistic_version??0");expect(view).not.toMatch(/expectedVersion:\s*0/)});
  it("cannot submit client-entered unresolved workspace controls and keeps emergency global control independent",()=>{const view=readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx","utf8");expect(view).toContain('bound=workspaceStatus==="found"');expect(view).toContain("disabled={blocked}");expect(view.indexOf("<Button control={engage}")).toBeLessThan(view.indexOf("disabled={blocked}"))});
  it("refreshes the authoritative read model after a typed stale-version response",()=>{const view=readFileSync("src/app/(admin)/admin/furnishing/activation/activation-controls.tsx","utf8");expect(view).toContain('result.code==="VERSION_CONFLICT"');expect(view).toContain("router.refresh()")});
  it("retains the authoritative missing-row version zero only in the Admin-safe database resolver",()=>{const migration=readFileSync("supabase/migrations/20260826013000_fs008g_c2_unambiguous_activation_command.sql","utf8");expect(migration).toContain("'state','disabled','version',0");expect(migration).toContain("if not found then")});
  it("binds every mutation to the authoritative revoked-row version 4",()=>{const controls=workspaceControlsFor({id:"row",workspace_id:"4abe0850-6ad7-40a0-89bb-b1fb5e6afe82",enabled:false,kill_switch:true,revoked_at:"2026-08-27T23:46:59Z",optimistic_version:4});expect(controls).toHaveLength(7);expect(new Set(controls.map(control=>control.expectedVersion))).toEqual(new Set([4]))});
  it("uses version zero only for an authoritative missing-row projection and renders no controls while unresolved",()=>{const missing=workspaceControlsFor({id:"4abe0850-6ad7-40a0-89bb-b1fb5e6afe82",workspace_id:"4abe0850-6ad7-40a0-89bb-b1fb5e6afe82",enabled:false,kill_switch:true,optimistic_version:0});expect(missing.every(control=>control.expectedVersion===0)).toBe(true);expect(workspaceControlsFor(null)).toEqual([])});
});
