import type{GuidebookDraft}from"../domain/authoring";
export type AuthoringCommandShape=Readonly<{type:string;sectionId?:string;blockId?:string}>;
export type ConflictInteraction<T>=Readonly<{phase:"conflict"|"reviewed"|"retrying"|"saved"|"failed";local:T;command:AuthoringCommandShape;serverRevision?:number;receiptSequence:number;focusTarget:string}>;
export const retainConflict=<T>(local:T,command:AuthoringCommandShape,serverRevision:number):ConflictInteraction<T>=>({phase:"conflict",local,command,serverRevision,receiptSequence:0,focusTarget:"conflict:review"});
export const reviewLatest=<T>(state:ConflictInteraction<T>):ConflictInteraction<T>=>({...state,phase:"reviewed",focusTarget:"conflict:reapply"});
export const reapplyConflict=<T>(state:ConflictInteraction<T>):ConflictInteraction<T>=>({...state,phase:"retrying",receiptSequence:state.receiptSequence+1,focusTarget:"save-status"});
export const conflictAgain=<T>(state:ConflictInteraction<T>,serverRevision:number):ConflictInteraction<T>=>({...state,phase:"conflict",serverRevision,focusTarget:"conflict:review"});
export const failReapply=<T>(state:ConflictInteraction<T>):ConflictInteraction<T>=>({...state,phase:"failed",focusTarget:"save-status"});
export const focusAfterAuthoringCommand=(command:AuthoringCommandShape,before:GuidebookDraft,after:GuidebookDraft)=>{if(command.type==="create-section"||command.type==="duplicate-section"){const added=after.sections.find(section=>!before.sections.some(previous=>previous.id===section.id));return added?`section:${added.id}`:"section:new"}if(command.type==="delete-section")return after.sections[0]?`section:${after.sections[0].id}`:"section:new";if(command.type==="create-block"||command.type==="duplicate-block"){const section=after.sections.find(item=>item.id===command.sectionId),prior=before.sections.find(item=>item.id===command.sectionId),added=section?.blocks.find(block=>!prior?.blocks.some(previous=>previous.id===block.id));return added?`block:${added.id}`:`section:${command.sectionId}`}if(command.type==="delete-block")return`section:${command.sectionId}`;if(command.type.includes("reorder")||command.type.includes("visibility")||command.type==="update-block")return command.blockId?`block:${command.blockId}`:command.sectionId?`section:${command.sectionId}`:"save-status";return"save-status"};
