import Link from "next/link";
import { notFound } from "next/navigation";
import { archiveReportAction, archiveReportArtifactAction, downloadReportArtifact, getGeneratedReportView, publishReportArtifactsAction } from "@/app/actions/reporting";
import { ReportViewer, type ReportProjection } from "@/platform/reporting";

export default async function ReportDetailPage({params}:{params:Promise<{reportId:string}>}) {
  const {reportId}=await params,view=await getGeneratedReportView(reportId);if(!view)notFound();
  const projection=view.report.projection_snapshot as ReportProjection,active=view.artifacts.filter(item=>item.status==="active");
  const publishing=view.artifactJobs.find(item=>["queued","rendering","validating","storing"].includes(item.status));
  const failed=view.artifactJobs.find(item=>item.status==="failed");
  return <main className="bg-stone-100 pb-16">
    <div className="mx-auto max-w-5xl space-y-5 px-5 py-5 print:hidden">
      <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard/reports">← Reports Library</Link><div className="flex flex-wrap gap-2"><Link className="rounded-full border bg-white px-4 py-2 font-semibold" href={`/dashboard/reports/${reportId}/print`}>Print view</Link><Link className="rounded-full border bg-white px-4 py-2 font-semibold" href={`/dashboard/reports/${reportId}/share`}>Share</Link><form action={archiveReportAction}><input name="reportId" type="hidden" value={reportId}/><input name="operation" type="hidden" value={view.report.status==="archived"?"restore":"archive"}/><button className="rounded-full border bg-white px-4 py-2 font-semibold">{view.report.status==="archived"?"Restore report":"Archive report"}</button></form></div></div>
      {view.report.opportunity_id&&view.report.analysis_version_id?<section className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><strong>Decision lineage:</strong> This immutable report was generated from <Link className="font-semibold underline" href={`/dashboard/investments/opportunities/${view.report.opportunity_id}/analyses/${view.report.analysis_version_id}`}>its source analysis</Link>. It will not move to a newer opportunity version.</section>:null}
      <section aria-labelledby="publishing" className="rounded-2xl border bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="publishing" className="text-xl font-semibold">Publishing and artifacts</h2><p className="mt-1 text-sm text-stone-600">Report status: <strong className="capitalize">{view.report.status}</strong>. PDF is required for publication; HTML is optional.</p></div>{view.report.status!=="archived"?<form action={publishReportArtifactsAction}><input name="reportId" type="hidden" value={reportId}/><input name="artifactType" type="hidden" value="both"/><input name="commandId" type="hidden" value={crypto.randomUUID()}/><button disabled={Boolean(publishing)} className="rounded-full bg-stone-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{active.length?"Regenerate artifacts":"Publish HTML and PDF"}</button></form>:null}</div>
        {publishing?<p role="status" className="mt-4 rounded-xl bg-blue-50 p-3 text-sm">Publishing {publishing.artifact_type.toUpperCase()}: {publishing.status}. You may leave this page.</p>:null}
        {failed?<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-950"><strong>{failed.artifact_type.toUpperCase()} publishing failed.</strong> {failed.failure_message}{failed.retryable?<form action={publishReportArtifactsAction} className="mt-2"><input name="reportId" type="hidden" value={reportId}/><input name="artifactType" type="hidden" value={failed.artifact_type}/><input name="commandId" type="hidden" value={failed.idempotency_key.split(":").at(-1)}/><button className="font-semibold underline">Retry safely</button></form>:null}</div>:null}
        <div className="mt-5 grid gap-3 sm:grid-cols-2">{(["pdf","html"] as const).map(type=>{const artifact=active.find(item=>item.artifact_type===type);return <article className="rounded-xl border p-4" key={type}><div className="flex items-center justify-between"><h3 className="font-semibold uppercase">{type}</h3><span className="text-xs font-semibold capitalize">{artifact?.status??"unpublished"}</span></div>{artifact?<><dl className="mt-3 space-y-1 text-xs text-stone-600"><div><dt className="inline">Renderer: </dt><dd className="inline">{artifact.renderer_version}</dd></div><div><dt className="inline">Size: </dt><dd className="inline">{formatBytes(artifact.size_bytes)}</dd></div><div><dt className="inline">Created: </dt><dd className="inline">{new Date(artifact.created_at).toLocaleString()}</dd></div></dl><div className="mt-4 flex gap-3"><form action={downloadReportArtifact}><input name="reportId" type="hidden" value={reportId}/><input name="artifactType" type="hidden" value={type}/><button className="font-semibold underline">Download {type.toUpperCase()}</button></form><form action={archiveReportArtifactAction}><input name="reportId" type="hidden" value={reportId}/><input name="artifactId" type="hidden" value={artifact.id}/><button className="text-stone-600 underline">Archive</button></form></div></>:<p className="mt-3 text-sm text-stone-500">No active {type.toUpperCase()} artifact.</p>}</article>})}</div>
      </section>
      <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Version history</h2><p className="mt-1 text-sm text-stone-600">Every immutable version remains accessible.</p></div>{view.versions.length>1?<Link className="font-semibold underline" href={`/dashboard/reports/compare?a=${view.versions.at(-1)?.id}&b=${reportId}`}>Compare versions</Link>:null}</div><ol className="mt-4 space-y-2">{view.versions.map(version=><li className={`flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 ${version.id===reportId?"bg-stone-50":""}`} key={version.id}><div><Link className="font-semibold" href={`/dashboard/reports/${version.id}`}>v{version.version_number} · {version.report_number}</Link><p className="text-xs text-stone-500">{new Date(version.generated_at).toLocaleString()} · {version.status}</p></div><span className="text-xs capitalize">{version.confidence} confidence · {version.freshness}</span></li>)}</ol></section>
      {view.activity.length?<section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Publishing activity</h2><ol className="mt-4 space-y-3">{view.activity.slice(0,10).map(item=><li className="border-l-2 pl-3 text-sm" key={item.id}><p>{item.safe_summary}</p><time className="text-xs text-stone-500">{new Date(item.occurred_at).toLocaleString()}</time></li>)}</ol></section>:null}
    </div>
    <ReportViewer projection={projection} metadata={{reportNumber:view.report.report_number,generatedAt:view.report.generated_at,templateVersion:view.report.template_version}} />
  </main>;
}
function formatBytes(value:number){return value<1024?`${value} B`:`${(value/1024).toFixed(1)} KB`;}
