import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { AdminSectionCard } from "@/components/admin/admin-section-card";
import { AdminStatCard } from "@/components/admin/admin-stat-card";
import { getAdminCustomers } from "@/features/admin/application/operations-overview";
import Link from "next/link";

export default async function CustomersPage({searchParams}:{searchParams:Promise<{program?:string;lifecycle?:string}>}) {
  const query=await searchParams,allCustomers = await getAdminCustomers(),customers=allCustomers.filter(customer=>(!query.program||customer.program===query.program)&&(!query.lifecycle||customer.lifecycleStage===query.lifecycle));
  return <div className="space-y-8 py-8">
    <AdminPageHeader title="Customers" description="Manage canonical customers, prospects, offers, programs, and activity." />
    <nav className="flex flex-wrap gap-2 text-sm"><Link className="rounded-full border px-3 py-2" href="/admin/customers">All</Link><Link className="rounded-full border px-3 py-2" href="/admin/customers?lifecycle=prospect">Prospects</Link><Link className="rounded-full border px-3 py-2" href="/admin/customers?lifecycle=applied">Applicants</Link><Link className="rounded-full border px-3 py-2" href="/admin/customers?program=Founding%20HPM%20Partner">Founding HPM Partner</Link></nav>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><AdminStatCard label="Total Customers" value={customers.length} detail="Canonical owner profiles" /><AdminStatCard label="Active Customers" value={customers.length} detail="No separate lifecycle is currently defined" /><AdminStatCard label="Pending Invites" value="Unavailable" /><AdminStatCard label="Suspended" value="Unavailable" /><AdminStatCard label="Deactivated" value="Unavailable" /></section>
    <AdminSectionCard><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><caption className="sr-only">Customers and program relationships</caption><thead className="border-b text-xs text-stone-500"><tr><th className="pb-3">Customer</th><th className="pb-3">Lifecycle</th><th className="pb-3">Program</th><th className="pb-3">Cohort</th><th className="pb-3">Properties</th><th className="pb-3">Next action</th></tr></thead><tbody>{customers.map(customer => <tr key={customer.id} className="border-b border-stone-100"><td className="py-4"><p className="font-semibold text-stone-950">{customer.name}</p><p className="text-xs text-stone-500">{customer.email??"Unavailable"}</p></td><td className="py-4 capitalize">{customer.lifecycleStage}</td><td className="py-4">{customer.programId?<Link className="font-semibold underline" href={`/admin/customers/programs/${customer.programId}`}>{customer.program}</Link>:"—"}</td><td className="py-4">{customer.cohort??"—"}</td><td className="py-4">{customer.propertyCount}</td><td className="py-4 text-stone-600">{customer.nextAction??"—"}</td></tr>)}</tbody></table>{customers.length === 0 ? <p role="status" className="py-12 text-center text-sm text-stone-500">No customers match this filter.</p> : null}</div></AdminSectionCard>
  </div>;
}
