export {
  addDays,
  buildDailyRevenueSeries,
  buildDailyOccupancySeries,
  calculateDashboardMetrics,
  generatePerformanceInsights,
  differenceInNights,
  formatCurrency,
  formatDate,
  formatDecimal,
  formatPercentage,
  generateAnalyticsRecommendations,
  getAnalyticsBookings,
  getAnalyticsProperties,
  getDashboardAnalytics,
  getMonthToDateRange,
  getOverlappingNights,
  getRecentAnalyticsBookings,
  isValidDateString,
  resolveAnalyticsDateRange,
} from "./lib";

export type {
  AnalyticsBooking,
  AnalyticsDateRange,
  AnalyticsProperty,
  AnalyticsQueryParams,
  DashboardAnalytics,
  DashboardComparison,
  DashboardMetrics,
  InsightTone,
  MetricTrend,
  MetricTrendDirection,
  OccupancyDataPoint,
  PerformanceInsight,
  RevenueBookingStatus,
  RevenueDataPoint,
AnalyticsRecommendation,
RecommendationCategory,
RecommendationConfidence,
RecommendationEvidence,
RecommendationPriority,
} from "./types";

export {
  AnalyticsControls,
  BookingsTable,
  InsightsDashboard,
  MetricTrendIndicator,
  OccupancyTrendChart,
  PerformanceSummary,
  RecommendationCard,
  ReportContext,
  RevenueIntelligence,
  RevenueTrendChart,
  StatCard,
  StatsGrid,
  StatusBadge,
} from "./components";
