import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
import {discoverySchema,foundingPartnerApplicationSchema,qualificationSchema} from "./application";
const sql=readFileSync("supabase/migrations/20260818032000_fp001_recruit_qualify.sql","utf8");
describe("FP-001 recruit and qualify",()=>{
  it("uses the canonical customer account and a separate generic program relationship",()=>{expect(sql).toContain("alter table public.customer_accounts");expect(sql).toContain("create table public.customer_programs");expect(sql).not.toContain("founding_partner_customers")});
  it("keeps anonymous writes behind one bounded RPC and enables RLS",()=>{for(const table of["customer_programs","founding_partner_applications","founding_partner_qualifications","founding_partner_discovery","founding_partner_events","customer_program_audit_events"])expect(sql).toContain(`alter table public.${table} enable row level security`);expect(sql).toContain("security definer set search_path=''");expect(sql).toContain("grant execute on function public.submit_founding_partner_application(jsonb) to anon,authenticated")});
  it("validates an application without collecting unnecessary sensitive data",()=>{expect(foundingPartnerApplicationSchema.parse({firstName:"Morgan",lastName:"Smith",email:"morgan@example.com",businessName:"Morgan Stay Co.",operatingModel:"Owner operator",propertyCount:"8",yearsOperating:"4",primaryMarkets:"Dallas",twelveMonthGoal:"Build a stronger operating system",primaryDifficulty:"Scattered information",improvementArea:"Revenue decisions",monthlyFeedbackConsent:"on",earlyCapabilityConsent:"on",programInterest:"Shape a useful HPM platform"}).email).toBe("morgan@example.com")});
  it("requires reasons for qualification and discovery outcomes",()=>{expect(()=>qualificationSchema.parse({programId:crypto.randomUUID(),growthOrientation:"strong",businessSeriousness:"strong",technologyOpenness:"strong",feedbackWillingness:"strong",hpmProblemFit:"strong",learningValue:"moderate",recommendation:"recommended",notes:""})).toThrow();expect(()=>discoverySchema.parse({programId:crypto.randomUUID(),businessNotes:"",performanceNotes:"",systemsNotes:"",decisionsNotes:"",hpmReactionNotes:"",partnershipFitNotes:"",twelveMonthBuild:"",informationGapDecision:"",tomorrowQuestion:"",outcome:"accept",rationale:""})).toThrow()});
});
