import type { ReportProjection, ReportTemplate } from "../domain";
import { REPORT_RENDERER_VERSION, orderSections } from "../application";

export async function renderReportHtml(projection: ReportProjection, template: ReportTemplate) {
  const sections = orderSections(projection.sections, template);
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(projection.title)}</title><style>${styles(template.brand.accent)}</style></head><body><main><header class="cover"><p class="brand">${escape(template.brand.name)}</p><h1>${escape(projection.title)}</h1>${projection.subtitle ? `<p class="subtitle">${escape(projection.subtitle)}</p>` : ""}<dl class="metadata"><div><dt>Scope</dt><dd>${escape(projection.scope.label)}${projection.scope.partial ? " — Partial authorized scope" : ""}</dd></div><div><dt>Generated from data evaluated</dt><dd>${escape(projection.evaluatedAt)}</dd></div><div><dt>Confidence</dt><dd>${escape(projection.confidence)}</dd></div><div><dt>Freshness</dt><dd>${escape(projection.freshness)}</dd></div></dl></header><section aria-labelledby="executive-summary"><h2 id="executive-summary">Executive Summary</h2><p>${escape(projection.summary)}</p></section>${sections.map(sectionHtml).join("")}<section aria-labelledby="report-metadata"><h2 id="report-metadata">Report Metadata</h2><p>Projection ${escape(projection.projectionVersion)} · Template ${template.version} · Renderer ${REPORT_RENDERER_VERSION}</p><ul>${projection.sourceVersions.map((source) => `<li>${escape(source.source)} — ${escape(source.version)}</li>`).join("")}</ul></section></main></body></html>`;
  const bytes = new TextEncoder().encode(html);
  return Object.freeze({ content: html, sizeBytes: bytes.byteLength });
}

function sectionHtml(section: ReportProjection["sections"][number]) {
  if (section.status === "omitted") return "";
  const unavailable = section.status === "unavailable";
  return `<section aria-labelledby="section-${escape(section.key)}"><h2 id="section-${escape(section.key)}">${escape(section.title)}</h2>${unavailable ? `<p role="note">This section was unavailable at generation time.</p>` : ""}${section.narrative ? `<p>${escape(section.narrative)}</p>` : ""}${section.metrics.length ? `<dl class="metrics">${section.metrics.map((metric) => `<div><dt>${escape(metric.label)}</dt><dd>${escape(metric.displayValue)}</dd><p>${escape(metric.qualification)}. ${escape(metric.accessibleDescription)}</p></div>`).join("")}</dl>` : ""}${section.rows?.length ? table(section.rows) : ""}<p class="qualification">Confidence: ${escape(section.confidence ?? "unavailable")} · Freshness: ${escape(section.freshness ?? "unknown")}</p></section>`;
}
function table(rows: readonly Readonly<Record<string, string>>[]) {
  const headers = Object.keys(rows[0] ?? {});
  return `<table><thead><tr>${headers.map((header) => `<th scope="col">${escape(header)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${headers.map((header) => `<td>${escape(row[header] ?? "")}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
}
function escape(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character); }
function styles(accent: string) { return `:root{color-scheme:light;--accent:${accent}}*{box-sizing:border-box}body{margin:0;color:#1c1917;background:#f5f5f4;font:16px/1.55 ui-sans-serif,system-ui}main{max-width:960px;margin:auto;background:white;padding:64px}.brand{text-transform:uppercase;letter-spacing:.2em;color:var(--accent);font-weight:700}.cover{min-height:320px;border-bottom:2px solid #e7e5e4}h1{font:700 48px/1.05 ui-serif,Georgia}h2{margin-top:48px;font:700 28px/1.2 ui-serif,Georgia}.subtitle,.qualification{color:#57534e}.metadata,.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.metadata div,.metrics div{border:1px solid #e7e5e4;padding:16px}.metrics dd{font-size:24px;font-weight:700}.metrics p{font-size:12px;color:#57534e}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #d6d3d1;padding:10px;text-align:left}@media(max-width:640px){main{padding:24px}.metadata,.metrics{grid-template-columns:1fr}h1{font-size:36px}}@media print{body{background:white}main{max-width:none;padding:20mm}.cover{break-after:page}section{break-inside:avoid}a{color:inherit}@page{size:Letter;margin:16mm}}`; }
