export type GuidebookOperationalStatus="no-guidebook"|"draft"|"ready"|"publishing"|"published"|"archived";
export type GuidebookHealthStatus="ready"|"missing-required-information"|"draft-out-of-date"|"publishing-failed"|"property-information-changed"|"guidebook-out-of-sync";
export type GuidebookPublicUrlStatus="active"|"inactive"|"archived"|"broken";
export type GuidebookWorkspaceAction=Readonly<{key:string;label:string;reason:string;priority:"critical"|"high"|"normal"|"informational";href:string}>;
export type GuidebookPropertyInput=Readonly<{id:string;name:string;status:string;address?:string|null;city?:string|null;state?:string|null;checkInTime?:string|null;checkoutTime?:string|null;amenities?:readonly string[];houseRules?:readonly string[];updatedAt:string;featuredImage?:string|null;projectionVersion?:string;operationalStatus?:string;operationalMissing?:readonly string[]}>;
export type GuidebookRecordInput=Readonly<{id:string;propertyId:string;title:string;status:string;currentVersion:number;publishedVersion?:number|null;publicSlug:string;revision:number;createdAt:string;updatedAt:string}>;
export type GuidebookSectionInput=Readonly<{key:string;visible:boolean;blockCount:number;updatedAt?:string|null}>;
export type GuidebookVersionInput=Readonly<{version:number;status:string;publishedAt:string;createdAt:string}>;
export type GuidebookActivityInput=Readonly<{id:string;guidebookId:string;eventType:string;summary:string;occurredAt:string}>;
export type GuidebookPropertyProjection=Readonly<{
 property:GuidebookPropertyInput;guidebook?:GuidebookRecordInput;status:GuidebookOperationalStatus;
 health:Readonly<{status:GuidebookHealthStatus;label:string;reasons:readonly string[];recovery:string;requiresAttention:boolean}>;
 currentVersion:number;draftAvailable:boolean;lastPublishedAt?:string;lastUpdatedAt:string;
 publicUrl:Readonly<{status:GuidebookPublicUrlStatus;path?:string}>;
 requiredSections:Readonly<{complete:number;total:number;missing:readonly string[]}>;
 suggestedActions:readonly GuidebookWorkspaceAction[];
}>;
export type GuidebookWorkspaceProjection=Readonly<{
 projectionVersion:"guidebook-workspace-projection.v1";generatedAt:string;workspaceId:string;
 portfolio:Readonly<{totalProperties:number;publishedGuidebooks:number;draftGuidebooks:number;requiringAttention:number;unpublishedProperties:number;lastPublishedAt?:string}>;
 library:readonly GuidebookPropertyProjection[];recentActivity:readonly GuidebookActivityInput[];
 entitlements:Readonly<{create:boolean;publish:boolean;host:boolean}>;permissions:Readonly<{view:boolean;manage:boolean}>;
 onboarding:"operational"|"entitled-empty"|"not-entitled";
}>;
const requiredSections=["welcome","arrival","parking","check-in","wi-fi","house-rules","emergency","checkout"]as const;
export function buildGuidebookWorkspaceProjection(input:Readonly<{workspaceId:string;properties:readonly GuidebookPropertyInput[];guidebooks:readonly GuidebookRecordInput[];sections:Readonly<Record<string,readonly GuidebookSectionInput[]>>;versions:Readonly<Record<string,readonly GuidebookVersionInput[]>>;activity:readonly GuidebookActivityInput[];entitlements:GuidebookWorkspaceProjection["entitlements"];permissions:GuidebookWorkspaceProjection["permissions"];generatedAt?:string;basePath?:string}>):GuidebookWorkspaceProjection{
 const library=input.properties.map(property=>buildGuidebookPropertyProjection({property,guidebook:input.guidebooks.find(item=>item.propertyId===property.id),sections:input.guidebooks.find(item=>item.propertyId===property.id)?input.sections[input.guidebooks.find(item=>item.propertyId===property.id)!.id]??[]:[],versions:input.guidebooks.find(item=>item.propertyId===property.id)?input.versions[input.guidebooks.find(item=>item.propertyId===property.id)!.id]??[]:[],entitlements:input.entitlements,basePath:input.basePath}));
 const published=library.filter(item=>item.publicUrl.status==="active"),drafts=library.filter(item=>Boolean(item.guidebook)&&(["draft","ready"].includes(item.status)||item.draftAvailable)),lastPublished=[...library].map(item=>item.lastPublishedAt).filter((item):item is string=>Boolean(item)).sort().at(-1);
 return deepFreeze({projectionVersion:"guidebook-workspace-projection.v1",generatedAt:input.generatedAt??new Date().toISOString(),workspaceId:input.workspaceId,portfolio:{totalProperties:library.length,publishedGuidebooks:published.length,draftGuidebooks:drafts.length,requiringAttention:library.filter(item=>item.health.requiresAttention).length,unpublishedProperties:library.filter(item=>item.publicUrl.status!=="active").length,...(lastPublished?{lastPublishedAt:lastPublished}:{})},library,recentActivity:Object.freeze([...input.activity].sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt)).slice(0,20)),entitlements:input.entitlements,permissions:input.permissions,onboarding:library.some(item=>item.guidebook)?"operational":input.entitlements.create?"entitled-empty":"not-entitled"});
}
export function buildGuidebookPropertyProjection(input:Readonly<{property:GuidebookPropertyInput;guidebook?:GuidebookRecordInput;sections:readonly GuidebookSectionInput[];versions:readonly GuidebookVersionInput[];entitlements:GuidebookWorkspaceProjection["entitlements"];basePath?:string}>):GuidebookPropertyProjection{
 const{property,guidebook}=input,latestPublished=[...input.versions].filter(item=>item.status==="published").sort((a,b)=>b.version-a.version)[0],sectionMap=new Map(input.sections.map(item=>[item.key,item])),missing=requiredSections.filter(key=>{const section=sectionMap.get(key);return!section||!section.visible||section.blockCount===0;});
 const propertyGaps=[!property.address?"property address":null,!property.checkInTime?"check-in time":null,!property.checkoutTime?"checkout time":null,!property.houseRules?.length?"house rules":null].filter((item):item is string=>Boolean(item)),required={complete:requiredSections.length-missing.length,total:requiredSections.length,missing:Object.freeze([...missing,...propertyGaps])};
 const status=guidebookStatus(guidebook,required),publicUrl=publicStatus(guidebook,latestPublished),draftAvailable=Boolean(guidebook&&latestPublished&&Date.parse(guidebook.updatedAt)>Date.parse(latestPublished.publishedAt)),health=healthProjection({property,guidebook,status,latestPublished,required,draftAvailable,publicStatus:publicUrl.status}),suggestedActions=actions({property,guidebook,status,health,required,entitlements:input.entitlements,basePath:input.basePath});
 return deepFreeze({property,...(guidebook?{guidebook}:{}),status,health,currentVersion:guidebook?.currentVersion??0,draftAvailable,lastUpdatedAt:guidebook?.updatedAt??property.updatedAt,...(latestPublished?{lastPublishedAt:latestPublished.publishedAt}:{}),publicUrl,requiredSections:required,suggestedActions});
}
export function filterGuidebookLibrary(library:readonly GuidebookPropertyProjection[],input:Readonly<{query?:string;status?:string;sort?:"property"|"updated"|"published"|"status"}>){
 const query=input.query?.trim().toLowerCase(),filtered=library.filter(item=>(!input.status||statusMatches(item,input.status))&&(!query||[item.property.name,item.guidebook?.title,item.status,item.currentVersion].some(value=>String(value??"").toLowerCase().includes(query))));
 return Object.freeze([...filtered].sort((a,b)=>input.sort==="updated"?Date.parse(b.lastUpdatedAt)-Date.parse(a.lastUpdatedAt):input.sort==="published"?Date.parse(b.lastPublishedAt??"0")-Date.parse(a.lastPublishedAt??"0"):input.sort==="status"?a.status.localeCompare(b.status):a.property.name.localeCompare(b.property.name)));
}
function guidebookStatus(guidebook:GuidebookRecordInput|undefined,required:GuidebookPropertyProjection["requiredSections"]):GuidebookOperationalStatus{if(!guidebook)return"no-guidebook";if(guidebook.status==="archived")return"archived";if(guidebook.status==="published")return"published";if(guidebook.status==="publishing")return"publishing";return required.missing.length?"draft":"ready";}
function publicStatus(guidebook:GuidebookRecordInput|undefined,latest?:GuidebookVersionInput):GuidebookPropertyProjection["publicUrl"]{if(!guidebook)return{status:"inactive"};if(guidebook.status==="archived")return{status:"archived"};if(guidebook.status==="published"&&!latest)return{status:"broken"};if(latest)return{status:"active",path:`/g/${guidebook.publicSlug}`};return{status:"inactive"};}
function healthProjection(input:{property:GuidebookPropertyInput;guidebook?:GuidebookRecordInput;status:GuidebookOperationalStatus;latestPublished?:GuidebookVersionInput;required:GuidebookPropertyProjection["requiredSections"];draftAvailable:boolean;publicStatus:GuidebookPublicUrlStatus}){let status:GuidebookHealthStatus="ready",reasons:string[]=[],recovery="No guidebook action is currently required.";if(input.publicStatus==="broken"){status="publishing-failed";reasons=["The guidebook is marked published but no active published version exists."];recovery="Open publishing and retry creation of the public version.";}else if(input.guidebook&&input.property.status==="archived"&&input.guidebook.status!=="archived"){status="guidebook-out-of-sync";reasons=["The property is archived while its guidebook remains active."];recovery="Archive the guidebook or restore the property.";}else if(input.property.operationalMissing?.length){status="missing-required-information";reasons=input.property.operationalMissing.map(item=>`Canonical ${item.replaceAll(/([A-Z])/g," $1").toLowerCase()} is missing.`);recovery="Complete operational information in the Property workspace before publishing.";}else if(input.required.missing.length){status="missing-required-information";reasons=input.required.missing.map(item=>`${item.replaceAll("-"," ")} is incomplete.`);recovery="Complete required guidebook sections before publishing.";}else if(input.latestPublished&&Date.parse(input.property.updatedAt)>Date.parse(input.latestPublished.publishedAt)){status="property-information-changed";reasons=["Canonical property information changed after the last publication."];recovery="Review synchronized property details and publish a new guidebook version.";}else if(input.draftAvailable){status="draft-out-of-date";reasons=["The working draft changed after the currently published version."];recovery="Preview the draft and publish it when ready.";}return{status,label:status.replaceAll("-"," "),reasons:Object.freeze(reasons),recovery,requiresAttention:status!=="ready"};}
function actions(input:{property:GuidebookPropertyInput;guidebook?:GuidebookRecordInput;status:GuidebookOperationalStatus;health:ReturnType<typeof healthProjection>;required:GuidebookPropertyProjection["requiredSections"];entitlements:GuidebookWorkspaceProjection["entitlements"];basePath?:string}){const result:GuidebookWorkspaceAction[]=[],base=input.basePath??"/dashboard/guidebooks";if(!input.guidebook)result.push({key:"create",label:"Create guidebook",reason:"This property has no guest guidebook.",priority:"high",href:`${base}/new?property=${input.property.id}`});else{const editor=`${base}/${input.guidebook.id}/edit`;if(input.property.operationalMissing?.length)result.push({key:"property-information",label:"Complete property information",reason:input.health.reasons[0]??"Canonical operational information is missing.",priority:"critical",href:`/dashboard/workspace/properties?property=${input.property.id}`});if(input.required.missing.some(item=>item==="wi-fi"))result.push({key:"wifi",label:"Update Wi-Fi section",reason:"The required Wi-Fi experience section is incomplete.",priority:"high",href:`${editor}#wi-fi`});if(input.required.missing.some(item=>item==="parking"))result.push({key:"parking",label:"Update parking section",reason:"The required parking experience section is incomplete.",priority:"high",href:`${editor}#parking`});if(input.required.missing.some(item=>item==="house-rules"||item==="house rules"))result.push({key:"rules",label:"Review house rules",reason:"Guest-facing house rules are incomplete.",priority:"high",href:`${editor}#house-rules`});if(input.status==="ready"&&!input.property.operationalMissing?.length)result.push({key:"publish",label:"Publish draft",reason:"Required information is complete and the draft is ready.",priority:"high",href:editor});if(["property-information-changed","draft-out-of-date"].includes(input.health.status))result.push({key:"republish",label:"Review and republish",reason:input.health.reasons[0]??"The published version requires review.",priority:"high",href:editor});if(input.health.status==="publishing-failed")result.push({key:"retry",label:"Retry publishing",reason:input.health.reasons[0],priority:"critical",href:editor});}return Object.freeze(result);}
function statusMatches(item:GuidebookPropertyProjection,status:string){if(status==="missing")return item.status==="no-guidebook";if(status==="unpublished")return item.publicUrl.status!=="active"&&item.status!=="archived";if(status==="needs-update"||status==="needs-attention")return item.health.requiresAttention;if(status==="draft")return Boolean(item.guidebook)&&(["draft","ready"].includes(item.status)||item.draftAvailable);if(status==="published")return item.publicUrl.status==="active";return item.status===status;}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);}return value;}
