import type { SupabaseClient } from "@supabase/supabase-js";
import type { ProductionReleaseCandidate, ProductionVerificationRun } from "../domain";
import type { ReleaseCandidateRepository, VerificationCoordinationAuthorization, VerificationRunRepository } from "../application/coordination";

const candidate=(row:Record<string,unknown>):ProductionReleaseCandidate=>({id:String(row.id),environmentCode:"production",repositoryCode:String(row.repository_code),commitSha:String(row.commit_sha),deploymentId:String(row.deployment_id),deploymentUrl:String(row.deployment_url),productionAlias:String(row.production_alias),...(row.build_id?{buildId:String(row.build_id)}:{}),deployedAt:new Date(String(row.deployed_at)),databaseMigrationSetHash:String(row.database_migration_set_hash),latestMigrationCode:String(row.latest_migration_code),registryVersions:(row.registry_versions??{})as Record<string,number>,verificationPlanVersion:Number(row.verification_plan_version),featureConfigurationFingerprint:String(row.feature_configuration_fingerprint),createdAt:new Date(String(row.created_at))});
const run=(row:Record<string,unknown>):ProductionVerificationRun=>({id:String(row.id),releaseCandidateId:String(row.release_candidate_id),planCode:String(row.plan_code),planVersion:Number(row.plan_version),environmentCode:"production",status:String(row.status)as ProductionVerificationRun["status"],initiatedBy:String(row.initiated_by),...(row.reviewed_by?{reviewedBy:String(row.reviewed_by)}:{}),...(row.started_at?{startedAt:new Date(String(row.started_at))}:{}),...(row.completed_at?{completedAt:new Date(String(row.completed_at))}:{}),correlationId:String(row.correlation_id),revision:Number(row.revision)});

export class SupabaseVerificationCoordinationAuthorization implements VerificationCoordinationAuthorization{constructor(private client:SupabaseClient){}async authorize(actorId:string){const {data,error}=await this.client.from("profiles").select("role").eq("id",actorId).maybeSingle();if(error)throw new Error("VERIFICATION_COORDINATION_AUTHORIZATION_FAILED");return data?.role==="admin"||data?.role==="administrator";}}
export class SupabaseReleaseCandidateRepository implements ReleaseCandidateRepository{constructor(private client:SupabaseClient){}async find(commitSha:string,deploymentId:string){const {data,error}=await this.client.from("production_release_candidates").select("*").eq("commit_sha",commitSha).eq("deployment_id",deploymentId).maybeSingle();if(error)throw new Error("CANDIDATE_READ_FAILED");return data?candidate(data):null}async create(value:Omit<ProductionReleaseCandidate,"id"|"createdAt">,actorId:string,correlationId:string){const {data,error}=await this.client.from("production_release_candidates").insert({environment_code:value.environmentCode,repository_code:value.repositoryCode,commit_sha:value.commitSha,deployment_id:value.deploymentId,deployment_url:value.deploymentUrl,production_alias:value.productionAlias,build_id:value.buildId??null,deployed_at:value.deployedAt.toISOString(),database_migration_set_hash:value.databaseMigrationSetHash,latest_migration_code:value.latestMigrationCode,registry_versions:value.registryVersions,verification_plan_version:value.verificationPlanVersion,feature_configuration_fingerprint:value.featureConfigurationFingerprint,locked_by:actorId,lock_correlation_id:correlationId}).select("*").single();if(error)throw new Error("CANDIDATE_CREATE_FAILED");return candidate(data)}}
export class SupabaseVerificationRunRepository implements VerificationRunRepository{constructor(private client:SupabaseClient){}async findActive(candidateId:string,planCode:string,planVersion:number){const {data,error}=await this.client.from("production_verification_runs").select("*").eq("release_candidate_id",candidateId).eq("plan_code",planCode).eq("plan_version",planVersion).in("status",["draft","ready","running","paused","blocked","awaiting_review"]).maybeSingle();if(error)throw new Error("RUN_READ_FAILED");return data?run(data):null}async create(input:{candidateId:string;actorId:string;reviewerId:string;correlationId:string;instances:readonly {scenarioCode:string;scenarioVersion:number;expectedOutcomeCode:string}[]}){const {data,error}=await this.client.rpc("create_ca001f_verification_run",{p_candidate_id:input.candidateId,p_actor_id:input.actorId,p_reviewer_id:input.reviewerId,p_correlation_id:input.correlationId,p_instances:input.instances});if(error||!data)throw new Error("RUN_CREATE_FAILED");return run(data as Record<string,unknown>)}}
