import type{ProductProvisioningPort,ProductProvisioningResult}from"../application";import type{ProductFamilyCode}from"@/platform/commerce";
export type OwningProductProvisioningCommand=Readonly<{actorId:string;tenantId:string;customerAccountId:string;onboardingCaseId:string;idempotencyKey:string;correlationId:string}>;
export interface OwningProductProvisioningOperation{resolve(input:OwningProductProvisioningCommand):Promise<ProductProvisioningResult|null>;execute(input:OwningProductProvisioningCommand):Promise<ProductProvisioningResult>;cleanup?(input:Readonly<OwningProductProvisioningCommand&{contextId:string}>):Promise<Readonly<{status:"completed"|"retained";referenceId:string}>>}
export interface ProductProvisioningLedger{claim(input:Readonly<OwningProductProvisioningCommand&{productFamily:ProductFamilyCode}>):Promise<"claimed"|"existing">;complete(input:Readonly<OwningProductProvisioningCommand&{productFamily:ProductFamilyCode;result:ProductProvisioningResult}>):Promise<void>;fail(input:Readonly<OwningProductProvisioningCommand&{productFamily:ProductFamilyCode;failureCode:string}>):Promise<void>}
export class AuthoritativeProductProvisioningAdapter implements ProductProvisioningPort{constructor(private readonly actorId:string,private readonly correlationId:string,private readonly productFamily:ProductFamilyCode,private readonly operation:OwningProductProvisioningOperation,private readonly ledger:ProductProvisioningLedger){}async provision(input:Readonly<{tenantId:string;customerAccountId:string;onboardingCaseId:string;idempotencyKey:string}>){const command={actorId:this.actorId,correlationId:this.correlationId,...input},resolved=await this.operation.resolve(command);if(resolved)return resolved;await this.ledger.claim({...command,productFamily:this.productFamily});try{const second=await this.operation.resolve(command);if(second)return second;const result=await this.operation.execute(command);await this.ledger.complete({...command,productFamily:this.productFamily,result});return result}catch{await this.ledger.fail({...command,productFamily:this.productFamily,failureCode:"OWNING_DOMAIN_PROVISIONING_FAILED"});throw new Error("PRODUCT_PROVISIONING_FAILED")}}}
export const createHpmProvisioningAdapter=(actorId:string,correlationId:string,operation:OwningProductProvisioningOperation,ledger:ProductProvisioningLedger)=>new AuthoritativeProductProvisioningAdapter(actorId,correlationId,"hpm",operation,ledger);
export const createGuidebookProvisioningAdapter=(actorId:string,correlationId:string,operation:OwningProductProvisioningOperation,ledger:ProductProvisioningLedger)=>new AuthoritativeProductProvisioningAdapter(actorId,correlationId,"guidebook_studio",operation,ledger);
export const createFurnishingProvisioningAdapter=(actorId:string,correlationId:string,operation:OwningProductProvisioningOperation,ledger:ProductProvisioningLedger)=>new AuthoritativeProductProvisioningAdapter(actorId,correlationId,"furnishing",operation,ledger);
export const createInvestmentProvisioningAdapter=(actorId:string,correlationId:string,operation:OwningProductProvisioningOperation,ledger:ProductProvisioningLedger)=>new AuthoritativeProductProvisioningAdapter(actorId,correlationId,"investment_intelligence",operation,ledger);
export function composeIndependentProductAdapters(input:Readonly<{actorId:string;correlationId:string;ledger:ProductProvisioningLedger;operations:Readonly<Record<ProductFamilyCode,OwningProductProvisioningOperation>>}>){return Object.freeze({hpm:createHpmProvisioningAdapter(input.actorId,input.correlationId,input.operations.hpm,input.ledger),guidebook_studio:createGuidebookProvisioningAdapter(input.actorId,input.correlationId,input.operations.guidebook_studio,input.ledger),furnishing:createFurnishingProvisioningAdapter(input.actorId,input.correlationId,input.operations.furnishing,input.ledger),investment_intelligence:createInvestmentProvisioningAdapter(input.actorId,input.correlationId,input.operations.investment_intelligence,input.ledger)})}
