import { createHash } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ModuleRepository, OnboardingAssemblyAuthorization, OnboardingLifecycleRepository, OnboardingPlanRepository } from "../application";
import { ONBOARDING_MODULE_REGISTRY, freeze, type OnboardingCase, type OnboardingModuleInstance, type OnboardingSubmission } from "../domain";
type ProductFamilyCode="hpm"|"guidebook_studio"|"furnishing"|"investment_intelligence";
const capabilityFamilies:Readonly<Record<string,ProductFamilyCode>>=Object.freeze({"hpm.workspace.access":"hpm","hpm.performance.view":"hpm","guidebook.create":"guidebook_studio","furnishing.project.access":"furnishing","investment.analysis.run":"investment_intelligence"});
const familyRequirements=Object.freeze({hpm:["create_workspace","create_or_select_property","complete_property_profile","connect_data_source","upload_historical_data"],guidebook_studio:["complete_guidebook_intake"],furnishing:["complete_furnishing_intake","schedule_consultation"],investment_intelligence:["complete_investment_profile"]}as const);

type Row = Record<string, unknown>;
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const optional = (value: unknown) => value == null ? undefined : String(value);

function caseFrom(row: Row): OnboardingCase {
  return freeze({ id:String(row.id), tenantId:String(row.tenant_id), customerAccountId:String(row.customer_account_id), sourceType:row.source_type as OnboardingCase["sourceType"], sourceReferenceId:String(row.source_reference_id), status:row.status as OnboardingCase["status"], planVersion:Number(row.plan_version), ...(optional(row.started_at)?{startedAt:optional(row.started_at)}:{}), ...(optional(row.completed_at)?{completedAt:optional(row.completed_at)}:{}), ...(optional(row.cancelled_at)?{cancelledAt:optional(row.cancelled_at)}:{}), ...(optional(row.current_module_instance_id)?{currentModuleInstanceId:optional(row.current_module_instance_id)}:{}), ...(optional(row.blocker_code)?{blockerCode:optional(row.blocker_code) as OnboardingCase["blockerCode"]}:{}), ...(optional(row.assigned_internal_owner_id)?{assignedInternalOwnerId:optional(row.assigned_internal_owner_id)}:{}), createdAt:String(row.created_at), updatedAt:String(row.updated_at), revision:Number(row.revision) });
}
function moduleFrom(row: Row): OnboardingModuleInstance {
  return freeze({ id:String(row.id), onboardingCaseId:String(row.onboarding_case_id), moduleCode:String(row.module_code), moduleVersion:Number(row.module_version), ...(optional(row.product_family)?{productFamily:optional(row.product_family) as ProductFamilyCode}:{}), status:row.status as OnboardingModuleInstance["status"], responsibility:row.responsibility as OnboardingModuleInstance["responsibility"], required:Boolean(row.required), sequence:Number(row.sequence), ...(optional(row.reused_from_module_instance_id)?{reusedFromModuleInstanceId:optional(row.reused_from_module_instance_id)}:{}), ...(optional(row.started_at)?{startedAt:optional(row.started_at)}:{}), ...(optional(row.submitted_at)?{submittedAt:optional(row.submitted_at)}:{}), ...(optional(row.verified_at)?{verifiedAt:optional(row.verified_at)}:{}), ...(optional(row.completed_at)?{completedAt:optional(row.completed_at)}:{}), ...(optional(row.blocked_by_code)?{blockedByCode:optional(row.blocked_by_code) as OnboardingModuleInstance["blockedByCode"]}:{}), ...(optional(row.assigned_user_id)?{assignedUserId:optional(row.assigned_user_id)}:{}), revision:Number(row.revision) });
}
function submissionFrom(row: Row): OnboardingSubmission { return freeze({ id:String(row.id), tenantId:String(row.tenant_id), onboardingCaseId:String(row.onboarding_case_id), moduleInstanceId:String(row.module_instance_id), schemaCode:String(row.schema_code), schemaVersion:Number(row.schema_version), submittedBy:String(row.submitted_by), submittedAt:String(row.submitted_at), dataClassification:row.data_classification as OnboardingSubmission["dataClassification"], validationStatus:row.validation_status as OnboardingSubmission["validationStatus"], validatedData:(row.validated_data??{}) as Readonly<Record<string,unknown>>, revision:Number(row.revision) }); }

export class SupabaseOnboardingPlanRepository implements OnboardingPlanRepository {
  constructor(private readonly client: SupabaseClient) {}
  async findBySource(type: OnboardingCase["sourceType"], reference: string) { const {data,error}=await this.client.from("onboarding_cases").select("*").eq("source_type",type).eq("source_reference_id",reference).maybeSingle(); if(error)throw new Error("ONBOARDING_CASE_READ_FAILED"); if(!data)return null; return this.load(String(data.id)); }
  async findReusableVerified(customerAccountId:string,moduleCode:string){const {data:errorCases,error}=await this.client.from("onboarding_cases").select("id").eq("customer_account_id",customerAccountId);if(error)throw new Error("ONBOARDING_REUSE_READ_FAILED");const ids=(errorCases??[]).map(value=>String(value.id));if(!ids.length)return null;const {data,error:moduleError}=await this.client.from("onboarding_module_instances").select("*").in("onboarding_case_id",ids).eq("module_code",moduleCode).eq("status","verified").order("verified_at",{ascending:false}).limit(1).maybeSingle();if(moduleError)throw new Error("ONBOARDING_REUSE_READ_FAILED");return data?moduleFrom(data as Row):null}
  async create(input:Parameters<OnboardingPlanRepository["create"]>[0]){const modules=input.modules.map(value=>({id:value.id,module_code:value.moduleCode,module_version:value.moduleVersion,product_family:value.productFamily??null,status:value.status,responsibility:value.responsibility,required:value.required,sequence:value.sequence,reused_from:value.reusedFromModuleInstanceId??null,verified_at:value.verifiedAt??null,completed_at:value.completedAt??null,revision:value.revision}));const {data,error}=await this.client.rpc("create_onboarding_plan",{p_actor_id:input.actorId,p_case:input.case,p_modules:modules,p_templates:input.templateReferences,p_idempotency_hash:input.idempotencyKeyHash,p_correlation_id:input.correlationId});if(error||!data)throw new Error("ONBOARDING_PLAN_CREATE_FAILED");return (await this.load(String((data as Row).id)))!}
  private async load(id:string){const [{data:caseData,error:caseError},{data:modules,error:moduleError}]=await Promise.all([this.client.from("onboarding_cases").select("*").eq("id",id).maybeSingle(),this.client.from("onboarding_module_instances").select("*").eq("onboarding_case_id",id).order("sequence")]);if(caseError||moduleError||!caseData)throw new Error("ONBOARDING_PLAN_READ_FAILED");return freeze({case:caseFrom(caseData as Row),modules:freeze((modules??[]).map(value=>moduleFrom(value as Row)))})}
}

export class SupabaseOnboardingAssemblyAuthorization implements OnboardingAssemblyAuthorization {
  constructor(private readonly client:SupabaseClient){}
  async authorize(input:Parameters<OnboardingAssemblyAuthorization["authorize"]>[0]){const [{data:profile,error:profileError},{data:member,error:memberError}]=await Promise.all([this.client.from("profiles").select("role").eq("id",input.actorId).maybeSingle(),this.client.from("customer_account_memberships").select("id").eq("profile_id",input.actorId).eq("tenant_id",input.tenantId).eq("customer_account_id",input.customerAccountId).eq("status","active").maybeSingle()]);if(profileError||memberError)throw new Error("ONBOARDING_AUTHORIZATION_FAILED");return profile?.role==="admin"||Boolean(member)}
  async resolveSource(type:OnboardingCase["sourceType"],reference:string){let tenantId:string|undefined,customerAccountId:string|undefined,offerCode="administrative.grant",offerVersion=1; if(type==="commercial_agreement"){const {data,error}=await this.client.from("commercial_agreements").select("tenant_id,customer_account_id,offer_code,offer_version").eq("id",reference).maybeSingle();if(error)throw new Error("ONBOARDING_SOURCE_READ_FAILED");if(!data)return null;tenantId=String(data.tenant_id);customerAccountId=String(data.customer_account_id);offerCode=String(data.offer_code);offerVersion=Number(data.offer_version)}const query=this.client.from("commercial_entitlements").select("tenant_id,customer_account_id,capability_code,status,effective_from,effective_until").eq("source_reference_id",reference);const {data,error}=await query;if(error)throw new Error("ONBOARDING_SOURCE_READ_FAILED");const active=(data??[]).filter(value=>value.status==="active"&&Date.parse(String(value.effective_from))<=Date.now()&&(!value.effective_until||Date.parse(String(value.effective_until))>Date.now()));if(!active.length)return null;tenantId??=String(active[0].tenant_id);customerAccountId??=String(active[0].customer_account_id);const families=[...new Set(active.flatMap(value=>{const family=capabilityFamilies[String(value.capability_code)];return family?[family]:[]}))] as ProductFamilyCode[];const offerCodes=families.map(productFamily=>({code:offerCode,version:offerVersion,productFamily,requirements:familyRequirements[productFamily]}));return freeze({tenantId,customerAccountId,offerCodes,entitledFamilies:families})}
}

export class SupabaseOnboardingModuleRepository implements ModuleRepository {
  constructor(private readonly client:SupabaseClient){}
  async loadAuthorized(input:Parameters<ModuleRepository["loadAuthorized"]>[0]){const [{data:caseData,error:caseError},{data:moduleData,error:moduleError},{data:profile,error:profileError}]=await Promise.all([this.client.from("onboarding_cases").select("*").eq("id",input.caseId).eq("tenant_id",input.tenantId).maybeSingle(),this.client.from("onboarding_module_instances").select("*").eq("id",input.moduleId).eq("onboarding_case_id",input.caseId).maybeSingle(),this.client.from("profiles").select("role").eq("id",input.actorId).maybeSingle()]);if(caseError||moduleError||profileError)throw new Error("ONBOARDING_AUTHORIZATION_FAILED");if(!caseData||!moduleData)return null;const{data:member,error:memberError}=await this.client.from("customer_account_memberships").select("id").eq("profile_id",input.actorId).eq("tenant_id",input.tenantId).eq("customer_account_id",caseData.customer_account_id).eq("status","active").maybeSingle();if(memberError)throw new Error("ONBOARDING_AUTHORIZATION_FAILED");const internal=profile?.role==="admin";if(!internal&&!member)return null;const actorKind:"internal"|"customer"=internal?"internal":"customer";return freeze({case:caseFrom(caseData as Row),module:moduleFrom(moduleData as Row),actorKind})}
  async loadLatestSubmission(moduleId:string){const{data,error}=await this.client.from("onboarding_submissions").select("*").eq("module_instance_id",moduleId).order("revision",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error("ONBOARDING_SUBMISSION_READ_FAILED");return data?submissionFrom(data as Row):null}
  async saveDraft(value:OnboardingSubmission,expectedRevision:number,idempotencyKey:string){const {data,error}=await this.client.rpc("save_onboarding_draft",{p_actor_id:value.submittedBy,p_submission:{...value},p_expected_revision:expectedRevision,p_idempotency_hash:hash(idempotencyKey),p_correlation_id:`draft:${value.id}`});if(error||!data)throw new Error(error?.message.includes("STALE")?"STALE_ONBOARDING_REVISION":"ONBOARDING_DRAFT_SAVE_FAILED");return submissionFrom(data as Row)}
  async transition(input:Parameters<ModuleRepository["transition"]>[0]){const {data,error}=await this.client.rpc("transition_onboarding_module",{p_actor_id:input.actorId,p_module_id:input.module.id,p_to_status:input.to,p_expected_revision:input.expectedRevision,p_reason_code:input.reasonCode??null,p_customer_safe_message:input.customerSafeMessage??null,p_correlation_id:input.correlationId});if(error||!data)throw new Error(error?.message.includes("STALE")?"STALE_ONBOARDING_REVISION":"ONBOARDING_TRANSITION_FAILED");const updated=moduleFrom(data as Row),unlocked:OnboardingModuleInstance[]=[];if(updated.status==="verified"){const {data:rows,error:readError}=await this.client.from("onboarding_module_instances").select("*").eq("onboarding_case_id",updated.onboardingCaseId);if(readError)throw new Error("ONBOARDING_UNLOCK_READ_FAILED");const all=(rows??[]).map(row=>moduleFrom(row as Row)),completed=new Set(all.filter(value=>value.status==="verified"||value.status==="skipped").map(value=>value.moduleCode));for(const candidate of all.filter(value=>value.status==="locked")){const definition=ONBOARDING_MODULE_REGISTRY[`${candidate.moduleCode}@${candidate.moduleVersion}`];if(definition?.prerequisiteModuleCodes.every(code=>completed.has(code))){const result=await this.client.rpc("unlock_onboarding_module",{p_actor_id:input.actorId,p_module_id:candidate.id,p_expected_revision:candidate.revision,p_correlation_id:input.correlationId});if(result.error||!result.data)throw new Error("ONBOARDING_UNLOCK_FAILED");unlocked.push(moduleFrom(result.data as Row))}}}return freeze({module:updated,unlocked:freeze(unlocked)})}
}

export class SupabaseOnboardingLifecycleRepository implements OnboardingLifecycleRepository{
  constructor(private readonly client:SupabaseClient){}
  async loadAuthorized(actorId:string,caseId:string){const{data,error}=await this.client.from("onboarding_cases").select("*").eq("id",caseId).maybeSingle();if(error||!data)return null;const[{data:profile},{data:member}]=await Promise.all([this.client.from("profiles").select("role").eq("id",actorId).maybeSingle(),this.client.from("customer_account_memberships").select("id").eq("profile_id",actorId).eq("tenant_id",data.tenant_id).eq("customer_account_id",data.customer_account_id).eq("status","active").maybeSingle()]);return profile?.role==="admin"||member?caseFrom(data as Row):null}
  async transition(input:Parameters<OnboardingLifecycleRepository["transition"]>[0]){const{data,error}=await this.client.rpc("transition_onboarding_case_lifecycle",{p_actor_id:input.actorId,p_case_id:input.caseId,p_to_status:input.to,p_expected_revision:input.expectedRevision,p_reason_code:input.reasonCode,p_correlation_id:input.correlationId});if(error||!data)throw new Error(error?.message.includes("STALE")?"STALE_ONBOARDING_REVISION":"ONBOARDING_LIFECYCLE_FAILED");return caseFrom(data as Row)}
}
