import type { CanonicalGuidebookSection, CanonicalGuidebookVersion, GuidebookComponentInstance } from "@/features/guidebook-studio";
import type { ComponentCompatibilityInput, ComponentPermission, ComponentPreset, ExperienceComponentDefinition, ExperienceComponentVersion } from "./domain";
import { evaluateComponentCompatibility, validateComponentConfiguration } from "./domain";

export type ComponentCommandContext=Readonly<{workspaceId:string;actorId:string;permissions:ReadonlySet<ComponentPermission>;propertyIds?:ReadonlySet<string>;isPlatformAdmin:boolean}>;
export type ComponentInsertion=Readonly<{id:string;idempotencyKey:string;guidebookVersion:CanonicalGuidebookVersion;section:CanonicalGuidebookSection;definition:ExperienceComponentDefinition;version:ExperienceComponentVersion;position:"beginning"|"before"|"after"|"end";anchorComponentId:string|null;visibility:"visible"|"hidden"|"conditional";conditionExpression:unknown|null;content:Readonly<Record<string,unknown>>;configuration:Readonly<Record<string,unknown>>;bindings:Readonly<Record<string,unknown>>;enabledActions:readonly string[];presetName:string|null}>;
export type ComponentMigrationImpact=Readonly<{componentDefinitionId:string;fromVersionId:string;toVersionId:string;breaking:boolean;affectedDraftInstances:number;affectedPublishedInstances:number;canAutoMigrate:boolean;rollbackVersionId:string}>;
export interface ExperienceComponentRepository {list(input:Readonly<{query?:string;category?:string;status?:string;channel?:string}>):Promise<readonly ExperienceComponentDefinition[]>;getDefinition(id:string):Promise<ExperienceComponentDefinition|null>;getVersion(id:string):Promise<ExperienceComponentVersion|null>;saveDefinition(value:ExperienceComponentDefinition):Promise<void>;saveVersion(value:ExperienceComponentVersion):Promise<void>;}
export interface ComponentInstanceRepository {findByIdempotencyKey(workspaceId:string,key:string):Promise<GuidebookComponentInstance|null>;listSectionInstances(workspaceId:string,sectionId:string):Promise<readonly GuidebookComponentInstance[]>;insertAtomic(workspaceId:string,instance:GuidebookComponentInstance,idempotencyKey:string,expectedDraftVersion:number):Promise<void>;updateAtomic(workspaceId:string,instance:GuidebookComponentInstance,expectedUpdatedAt:string):Promise<void>;removeAtomic(workspaceId:string,id:string,expectedUpdatedAt:string):Promise<void>;}
export interface ComponentPresetRepository {create(value:ComponentPreset):Promise<void>;get(workspaceId:string,id:string):Promise<ComponentPreset|null>;update(value:ComponentPreset):Promise<void>;}
export interface ComponentAuditPort {record(input:Readonly<{workspaceId:string;actorId:string;event:string;entityId:string;metadata:Readonly<Record<string,unknown>>;at:string}>):Promise<void>;}

export function authorizeComponent(context:ComponentCommandContext,permission:ComponentPermission,platformGoverned=false){if(!context.permissions.has(permission))throw new Error("COMPONENT_PERMISSION_DENIED");if(platformGoverned&&!context.isPlatformAdmin)throw new Error("COMPONENT_PLATFORM_ADMIN_REQUIRED")}
export function assertGuidebookComponentScope(context:ComponentCommandContext,workspaceId:string,propertyId:string|null){if(context.workspaceId!==workspaceId)throw new Error("COMPONENT_WORKSPACE_SCOPE_DENIED");if(propertyId&&context.propertyIds&&!context.propertyIds.has(propertyId))throw new Error("COMPONENT_PROPERTY_SCOPE_DENIED")}
export function validatePreset(preset:ComponentPreset){const serialized=JSON.stringify([preset.configuration,preset.bindingDefaults]).toLowerCase();if(["wifi.password","access.code","door_code","wifi_password"].some(key=>serialized.includes(key)))throw new Error("PRESET_SECRET_FORBIDDEN");if(preset.scope==="workspace"&&!preset.workspaceId)throw new Error("PRESET_WORKSPACE_REQUIRED")}

export async function addComponentToGuidebookSection(deps:Readonly<{instances:ComponentInstanceRepository;audit:ComponentAuditPort}>,context:ComponentCommandContext,input:ComponentInsertion,compatibility:ComponentCompatibilityInput,at:string){authorizeComponent(context,"guidebook_components.add");assertGuidebookComponentScope(context,context.workspaceId,null);if(!["draft","in_review","approved"].includes(input.guidebookVersion.lifecycleStatus))throw new Error("GUIDEBOOK_VERSION_IMMUTABLE");if(!["approved","published"].includes(input.version.lifecycleStatus))throw new Error("COMPONENT_VERSION_NOT_INSERTABLE");if(input.definition.lifecycleStatus==="deprecated"||input.definition.lifecycleStatus==="archived")throw new Error("COMPONENT_DEFINITION_NOT_INSERTABLE");const issues=[...evaluateComponentCompatibility(input.version,compatibility),...validateComponentConfiguration(input.version,input)];if(issues.some(issue=>issue.blocking))return{ok:false as const,issues};const existing=await deps.instances.findByIdempotencyKey(context.workspaceId,input.idempotencyKey);if(existing)return{ok:true as const,instance:existing,duplicate:true};const values=await deps.instances.listSectionInstances(context.workspaceId,input.section.id);const sortOrder=placement(values,input.position,input.anchorComponentId);const instance:GuidebookComponentInstance={id:input.id,sectionId:input.section.id,componentDefinitionId:input.definition.id,componentVersion:input.version.versionNumber,componentKey:input.definition.key as GuidebookComponentInstance["componentKey"],sortOrder,contentBindingMode:bindingMode(input.bindings),contentRecordId:stringOrNull(input.bindings.contentRecordId),contentCollectionId:stringOrNull(input.bindings.collectionId),configuration:{...input.configuration,inlineContent:input.content,bindings:input.bindings,enabledActions:input.enabledActions,...(input.presetName?{presetName:input.presetName}:{})},visibility:input.visibility,conditionExpression:input.conditionExpression as GuidebookComponentInstance["conditionExpression"],createdAt:at,updatedAt:at};await deps.instances.insertAtomic(context.workspaceId,instance,input.idempotencyKey,input.guidebookVersion.versionNumber);await deps.audit.record({workspaceId:context.workspaceId,actorId:context.actorId,event:"component.added_to_guidebook",entityId:instance.id,metadata:{componentKey:input.definition.key,componentVersion:input.version.versionNumber,sectionId:input.section.id},at});return{ok:true as const,instance,duplicate:false}}
export function getComponentMigrationImpact(input:Readonly<{definitionId:string;from:ExperienceComponentVersion;to:ExperienceComponentVersion;draftInstances:number;publishedInstances:number}>):ComponentMigrationImpact{return{componentDefinitionId:input.definitionId,fromVersionId:input.from.id,toVersionId:input.to.id,breaking:input.to.breakingChange,affectedDraftInstances:input.draftInstances,affectedPublishedInstances:input.publishedInstances,canAutoMigrate:!input.to.breakingChange,rollbackVersionId:input.from.id}}
export function migrateComponentInstance(instance:GuidebookComponentInstance,from:ExperienceComponentVersion,to:ExperienceComponentVersion,at:string){if(instance.componentVersion!==from.versionNumber)throw new Error("COMPONENT_MIGRATION_SOURCE_MISMATCH");if(to.componentDefinitionId!==from.componentDefinitionId)throw new Error("COMPONENT_MIGRATION_DEFINITION_MISMATCH");if(to.lifecycleStatus!=="published")throw new Error("COMPONENT_MIGRATION_TARGET_UNPUBLISHED");return{...instance,componentVersion:to.versionNumber,configuration:{...to.defaultConfiguration,...instance.configuration,migratedFromVersion:from.versionNumber},updatedAt:at}}
function placement(values:readonly GuidebookComponentInstance[],position:ComponentInsertion["position"],anchor:string|null){if(position==="beginning")return 0;if(position==="end"||!anchor)return values.length;const index=values.findIndex(item=>item.id===anchor);if(index<0)throw new Error("COMPONENT_PLACEMENT_ANCHOR_MISSING");return position==="before"?index:index+1}
function bindingMode(bindings:Readonly<Record<string,unknown>>):GuidebookComponentInstance["contentBindingMode"]{if(bindings.contentRecordId)return"content_record";if(bindings.collectionId)return"collection";if(Object.keys(bindings).some(key=>key.includes(".")||key==="variableKey"))return"property_variable";return"inline"}
function stringOrNull(value:unknown){return typeof value==="string"&&value?value:null}

export interface ExperienceComponentApi {createComponentDefinition(input:unknown,context:ComponentCommandContext):Promise<ExperienceComponentDefinition>;createComponentVersion(input:unknown,context:ComponentCommandContext):Promise<ExperienceComponentVersion>;updateDraftComponentVersion(input:unknown,context:ComponentCommandContext):Promise<ExperienceComponentVersion>;requestComponentReview(input:unknown,context:ComponentCommandContext):Promise<void>;approveComponentVersion(input:unknown,context:ComponentCommandContext):Promise<void>;publishComponentVersion(input:unknown,context:ComponentCommandContext):Promise<void>;deprecateComponentDefinition(input:unknown,context:ComponentCommandContext):Promise<void>;archiveComponentDefinition(input:unknown,context:ComponentCommandContext):Promise<void>;createComponentPreset(input:unknown,context:ComponentCommandContext):Promise<ComponentPreset>;approveComponentPreset(input:unknown,context:ComponentCommandContext):Promise<void>;archiveComponentPreset(input:unknown,context:ComponentCommandContext):Promise<void>;addComponentToGuidebookSection(input:unknown,context:ComponentCommandContext):Promise<GuidebookComponentInstance>;configureComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;bindComponentContent(input:unknown,context:ComponentCommandContext):Promise<void>;bindComponentPropertyVariable(input:unknown,context:ComponentCommandContext):Promise<void>;bindComponentMedia(input:unknown,context:ComponentCommandContext):Promise<void>;bindComponentCollection(input:unknown,context:ComponentCommandContext):Promise<void>;reorderComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;moveComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;duplicateComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;removeComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;migrateComponentInstance(input:unknown,context:ComponentCommandContext):Promise<void>;listComponentLibrary(input:unknown,context:ComponentCommandContext):Promise<unknown>;getComponentDetail(id:string,context:ComponentCommandContext):Promise<unknown>;getComponentVersion(id:string,context:ComponentCommandContext):Promise<unknown>;getComponentPreview(id:string,input:unknown,context:ComponentCommandContext):Promise<unknown>;getCompatibleComponents(input:unknown,context:ComponentCommandContext):Promise<unknown>;getComponentUsage(id:string,context:ComponentCommandContext):Promise<unknown>;getComponentConfigurationProjection(id:string,context:ComponentCommandContext):Promise<unknown>;getComponentMigrationImpact(id:string,context:ComponentCommandContext):Promise<unknown>}
