import {describe,expect,it} from "vitest";
import {assertVersionEditable,evaluateComponentCompatibility,maskSensitivePreview,renderComponentPreview,safeAnalyticsPayload,transitionDefinition,transitionVersion,validateComponentConfiguration} from "./domain";
import {buildComponentVersion,EXPERIENCE_COMPONENT_V1} from "./registry";
const wifi=()=>buildComponentVersion(EXPERIENCE_COMPONENT_V1.find(item=>item.key==="wifi_card")!);
describe("experience component governance",()=>{
 it("ships the complete approved v1 inventory with unique stable keys",()=>{expect(EXPERIENCE_COMPONENT_V1.length).toBeGreaterThanOrEqual(43);expect(new Set(EXPERIENCE_COMPONENT_V1.map(item=>item.key)).size).toBe(EXPERIENCE_COMPONENT_V1.length);for(const key of ["hero","wifi_card","faq_accordion","emergency_contact_card","recommendation_collection","departure_checklist","review_cta","sticky_action_bar"])expect(EXPERIENCE_COMPONENT_V1.some(item=>item.key===key)).toBe(true)});
 it("enforces definition and immutable version lifecycles",()=>{const definition={id:"d",key:"wifi_card",name:"Wi-Fi Card",description:"",category:"arrival" as const,lifecycleStatus:"approved" as const,currentVersionId:"v1",replacementComponentDefinitionId:null,createdBy:"a",createdAt:"now",updatedAt:"now"};expect(transitionDefinition(definition,"deprecated").lifecycleStatus).toBe("deprecated");expect(()=>transitionDefinition(definition,"draft")).toThrow("COMPONENT_DEFINITION_TRANSITION_INVALID");expect(()=>assertVersionEditable(wifi())).toThrow("COMPONENT_VERSION_IMMUTABLE");expect(()=>transitionVersion(wifi(),"superseded","a","now")).not.toThrow()});
 it("validates required bindings and allowed configuration",()=>{const issues=validateComponentConfiguration(wifi(),{content:{},configuration:{layout:"giant"},bindings:{},enabledActions:["delete_secret"]});expect(issues.map(item=>item.code)).toEqual(expect.arrayContaining(["VALUE_NOT_ALLOWED","BINDING_REQUIRED","ACTION_UNSUPPORTED"]))});
 it("rejects incompatible sections and channels before insertion",()=>{const issues=evaluateComponentCompatibility(wifi(),{sectionKind:"restaurants",templateCapabilities:[],channels:["pdf"],guidebookSchemaVersion:"lhc-guidebook.v1"});expect(issues.some(item=>item.code==="SECTION_INCOMPATIBLE")).toBe(true);expect(renderComponentPreview(wifi(),"pdf",{}).status).toBe("fallback")});
 it("masks secrets and excludes them from analytics",()=>{expect(maskSensitivePreview("LuxeMesa12",false)).not.toContain("Mesa12");expect(safeAnalyticsPayload({component_instance_id:"i",wifi_password:"secret","wifi.password":"secret",action:"copy"})).toEqual({component_instance_id:"i",action:"copy"})});
 it("declares WCAG contracts and deterministic renderers for every channel",()=>{for(const seed of EXPERIENCE_COMPONENT_V1){const version=buildComponentVersion(seed);expect(version.accessibilityContract.standard).toBe("WCAG 2.2 AA");expect(version.accessibilityContract.touchTargetMinimum).toBeGreaterThanOrEqual(44);for(const channel of ["responsive_web","mobile_web","pdf","guest_portal"] as const)expect(version.rendererContract[channel]).toBeDefined()}});
});
