import type { GuidebookSectionKind } from "@/features/guidebook-studio";

export type ExperienceComponentCategory="foundation"|"arrival"|"stay"|"safety"|"explore"|"departure"|"engagement"|"layout";
export type DefinitionLifecycle="draft"|"in_review"|"approved"|"deprecated"|"archived";
export type VersionLifecycle="draft"|"in_review"|"approved"|"published"|"superseded";
export type RendererSupport="supported"|"fallback"|"unsupported";
export type ComponentChannel="responsive_web"|"mobile_web"|"pdf"|"guest_portal";
export type SchemaField=Readonly<{key:string;label:string;type:"string"|"rich_text"|"boolean"|"number"|"url"|"phone"|"email"|"select"|"list"|"image";required:boolean;defaultValue?:unknown;allowedValues?:readonly string[];validation?:Readonly<{minLength?:number;maxLength?:number;minimum?:number;maximum?:number;pattern?:string}>;helpText:string;sensitive?:boolean}>;
export type ComponentBindingContract=Readonly<{modes:readonly ("inline"|"content_record"|"property_variable"|"collection"|"media")[];required:readonly string[];optional:readonly string[];allowedContentRecordTypes:readonly string[];propertyVariableKeys:readonly string[];media:Readonly<{required:boolean;minimum:number;maximum:number;requiresAltText:boolean}>;collection:Readonly<{allowedRecordTypes:readonly string[];minimum:number;maximum:number}>}>;
export type ComponentActionContract=Readonly<{key:string;type:"copy"|"link"|"phone"|"email"|"toggle"|"check"|"share";label:string;destinationPolicy:"none"|"safe_url"|"phone"|"email"|"bound_value";requiredPermission:string|null;analyticsEvent:string;channels:Readonly<Record<ComponentChannel,RendererSupport>>;sensitive:boolean}>;
export type ComponentValidationRule=Readonly<{code:string;fieldPath:string|null;message:string;severity:"info"|"warning"|"error";blocking:boolean}>;
export type AccessibilityContract=Readonly<{standard:"WCAG 2.2 AA";semanticRole:string;headingPolicy:string;keyboardBehavior:string;focusOrder:string;accessibleLabel:string;errorAnnouncement:string;liveRegion:string;touchTargetMinimum:number;reducedMotion:boolean;pdfTagging:string}>;
export type AnalyticsContract=Readonly<{events:readonly string[];baseContext:readonly ["guidebook_id","guidebook_version_id","publication_id","section_id","component_instance_id","component_definition_key","component_version"];prohibitedFields:readonly string[]}>;
export type RendererContract=Readonly<Record<ComponentChannel,Readonly<{support:RendererSupport;rendererKey:string|null;fallbackComponentKey:string|null;printBehavior:string|null}>>>;
export type ComponentCompatibility=Readonly<{guidebookSchemaVersions:readonly string[];sectionKinds:readonly GuidebookSectionKind[];allowedParentKeys:readonly string[];allowedChildKeys:readonly string[];templateCapabilities:readonly string[]}>;
export type ExperienceComponentDefinition=Readonly<{id:string;key:string;name:string;description:string;category:ExperienceComponentCategory;lifecycleStatus:DefinitionLifecycle;currentVersionId:string|null;replacementComponentDefinitionId:string|null;createdBy:string;createdAt:string;updatedAt:string}>;
export type ExperienceComponentVersion=Readonly<{id:string;componentDefinitionId:string;versionNumber:number;contentSchema:readonly SchemaField[];configurationSchema:readonly SchemaField[];defaultConfiguration:Readonly<Record<string,unknown>>;bindingContract:ComponentBindingContract;actionContract:readonly ComponentActionContract[];validationRules:readonly ComponentValidationRule[];accessibilityContract:AccessibilityContract;analyticsContract:AnalyticsContract;rendererContract:RendererContract;compatibility:ComponentCompatibility;lifecycleStatus:VersionLifecycle;changeSummary:string|null;breakingChange:boolean;createdBy:string;approvedBy:string|null;createdAt:string;approvedAt:string|null}>;
export type ComponentPreset=Readonly<{id:string;workspaceId:string|null;componentVersionId:string;name:string;configuration:Readonly<Record<string,unknown>>;bindingDefaults:Readonly<Record<string,unknown>>;scope:"platform"|"workspace";lifecycleStatus:"draft"|"approved"|"archived"}>;
export type ComponentValidationIssue=Readonly<{severity:"info"|"warning"|"error";code:string;message:string;fieldPath:string|null;blocking:boolean}>;
export type ComponentCompatibilityInput=Readonly<{sectionKind:GuidebookSectionKind;templateCapabilities:readonly string[];channels:readonly ComponentChannel[];guidebookSchemaVersion:string;parentComponentKey?:string}>;

export const COMPONENT_PERMISSIONS=Object.freeze(["experience_components.view","experience_components.create","experience_components.edit","experience_components.review","experience_components.approve","experience_components.publish","experience_components.deprecate","experience_components.archive","guidebook_components.add","guidebook_components.configure","guidebook_components.reorder","guidebook_components.remove","guidebook_components.migrate"] as const);
export type ComponentPermission=(typeof COMPONENT_PERMISSIONS)[number];
export const SENSITIVE_VARIABLES=Object.freeze(new Set(["wifi.network","wifi.password","access.code","access.instructions","host.phone","host.email"]));
export const ANALYTICS_PROHIBITED_FIELDS=Object.freeze(["wifi_password","door_code","guest_identity","message_contents","phone","email","sensitive_address"] as const);

const definitionTransitions:Record<DefinitionLifecycle,readonly DefinitionLifecycle[]>={draft:["in_review","archived"],in_review:["draft","approved"],approved:["deprecated","archived"],deprecated:["archived"],archived:[]};
const versionTransitions:Record<VersionLifecycle,readonly VersionLifecycle[]>={draft:["in_review"],in_review:["draft","approved"],approved:["published"],published:["superseded"],superseded:[]};
export function transitionDefinition<T extends ExperienceComponentDefinition>(value:T,next:DefinitionLifecycle):T{if(!definitionTransitions[value.lifecycleStatus].includes(next))throw new Error("COMPONENT_DEFINITION_TRANSITION_INVALID");return{...value,lifecycleStatus:next}}
export function transitionVersion<T extends ExperienceComponentVersion>(value:T,next:VersionLifecycle,actorId:string,at:string):T{if(!versionTransitions[value.lifecycleStatus].includes(next))throw new Error("COMPONENT_VERSION_TRANSITION_INVALID");if(next==="published"&&value.breakingChange&&!value.compatibility.guidebookSchemaVersions.length)throw new Error("COMPONENT_MIGRATION_PLAN_REQUIRED");return{...value,lifecycleStatus:next,...(["approved","published"].includes(next)?{approvedBy:actorId,approvedAt:at}:{})}}
export function assertVersionEditable(value:ExperienceComponentVersion){if(["published","superseded"].includes(value.lifecycleStatus))throw new Error("COMPONENT_VERSION_IMMUTABLE")}

export function validateComponentConfiguration(version:ExperienceComponentVersion,input:Readonly<{content:Readonly<Record<string,unknown>>;configuration:Readonly<Record<string,unknown>>;bindings:Readonly<Record<string,unknown>>;enabledActions:readonly string[]}>):readonly ComponentValidationIssue[]{const issues:ComponentValidationIssue[]=[];const validate=(field:SchemaField,source:Readonly<Record<string,unknown>>,prefix:string)=>{const value=source[field.key];if(field.required&&(value===undefined||value===null||value===""))issues.push(issue("FIELD_REQUIRED",`${field.label} is required.`,`${prefix}.${field.key}`));if(value!==undefined&&field.allowedValues&&!field.allowedValues.includes(String(value)))issues.push(issue("VALUE_NOT_ALLOWED",`${field.label} uses an unsupported value.`,`${prefix}.${field.key}`));if(typeof value==="string"&&field.validation?.maxLength&&value.length>field.validation.maxLength)issues.push(issue("VALUE_TOO_LONG",`${field.label} is too long.`,`${prefix}.${field.key}`));if(field.type==="url"&&value&&!safeUrl(String(value)))issues.push(issue("URL_INVALID",`${field.label} must use an approved URL scheme.`,`${prefix}.${field.key}`));};version.contentSchema.forEach(f=>validate(f,input.content,"content"));version.configurationSchema.forEach(f=>validate(f,input.configuration,"configuration"));for(const binding of version.bindingContract.required)if(input.bindings[binding]===undefined||input.bindings[binding]===null||input.bindings[binding]==="")issues.push(issue("BINDING_REQUIRED",`${binding} must be bound.`,`bindings.${binding}`));for(const action of input.enabledActions)if(!version.actionContract.some(item=>item.key===action))issues.push(issue("ACTION_UNSUPPORTED",`${action} is not supported by this component.`,`actions.${action}`));return issues}
export function evaluateComponentCompatibility(version:ExperienceComponentVersion,input:ComponentCompatibilityInput):readonly ComponentValidationIssue[]{const issues:ComponentValidationIssue[]=[];if(!version.compatibility.guidebookSchemaVersions.includes(input.guidebookSchemaVersion))issues.push(issue("SCHEMA_INCOMPATIBLE","The component does not support this guidebook schema.",null));if(version.compatibility.sectionKinds.length&&!version.compatibility.sectionKinds.includes(input.sectionKind))issues.push(issue("SECTION_INCOMPATIBLE","The component is not supported in this section.",null));for(const channel of input.channels)if(version.rendererContract[channel].support==="unsupported")issues.push(issue("CHANNEL_UNSUPPORTED",`${channel.replaceAll("_"," ")} is unsupported.`,null));for(const capability of version.compatibility.templateCapabilities)if(!input.templateCapabilities.includes(capability))issues.push(issue("TEMPLATE_INCOMPATIBLE",`The template is missing ${capability}.`,null));if(input.parentComponentKey&&version.compatibility.allowedParentKeys.length&&!version.compatibility.allowedParentKeys.includes(input.parentComponentKey))issues.push(issue("NESTING_INCOMPATIBLE","This component cannot be nested here.",null));return issues}
export function maskSensitivePreview(value:unknown,authorized:boolean){if(authorized)return value;if(typeof value!=="string")return value;return value.length<4?"••••":`${value.slice(0,2)}${"•".repeat(Math.min(8,value.length-2))}`}
export function safeAnalyticsPayload(input:Readonly<Record<string,unknown>>){const prohibited=new Set(ANALYTICS_PROHIBITED_FIELDS);return Object.freeze(Object.fromEntries(Object.entries(input).filter(([key])=>!prohibited.has(key.toLowerCase() as never)&&!SENSITIVE_VARIABLES.has(key))))}
export function renderComponentPreview(version:ExperienceComponentVersion,channel:ComponentChannel,data:Readonly<Record<string,unknown>>){const renderer=version.rendererContract[channel];if(renderer.support==="unsupported")return Object.freeze({status:"unsupported" as const,channel,message:`${channel.replaceAll("_"," ")} is not supported.`});const content=Object.fromEntries(Object.entries(data).map(([key,value])=>[key,SENSITIVE_VARIABLES.has(key)?maskSensitivePreview(value,false):value]));return Object.freeze({status:renderer.support,channel,rendererKey:renderer.rendererKey,fallbackComponentKey:renderer.fallbackComponentKey,printBehavior:renderer.printBehavior,content})}
function issue(code:string,message:string,fieldPath:string|null):ComponentValidationIssue{return{severity:"error",code,message,fieldPath,blocking:true}}
function safeUrl(value:string){try{return["https:","http:","tel:","mailto:"].includes(new URL(value).protocol)}catch{return value.startsWith("/")}}
