import { Claim, ClaimCollection, createClaimId } from "@/platform/claims";
import { Action, createActionId } from "@/platform/actions";
import { Decision, DecisionMode } from "@/platform/decisions";
import { Evaluation, EvaluationCollection, EvaluationDisposition, createEvaluationId } from "@/platform/evaluations";
import { Evidence, EvidenceCollection, EvidenceDirection, EvidenceStrength, createEvidenceId } from "@/platform/evidence";
import { IntelligenceBuilder } from "@/platform/intelligence";
import { createOutcomeId, emptyOutcomeLineage, Outcome } from "@/platform/outcomes";
import { Recommendation, RecommendationCollection, RecommendationPriority, createRecommendationId } from "@/platform/recommendations";
import { ConfidenceAssessment, ConfidenceLevel, ConfidenceScore } from "@/platform/scoring";
import { Identifier } from "@/platform/kernel";
import type { MarketAnalysisReport } from "../../domain/entities/market-analysis-report";
import type { MarketPlatformArtifacts } from "../../domain/market-platform-artifacts";
import { marketObservationProvider } from "../providers/market-observation-provider";

export function mapMarketPlatformArtifacts(report: MarketAnalysisReport): MarketPlatformArtifacts {
  const observations = marketObservationProvider.build(report), observationValues = observations.toArray();
  const subject = { type: "property", id: report.analysis.subject.id ?? report.analysis.subject.address };
  const evidenceValues = report.evidence.map((value, index) => Evidence.create({ id: createEvidenceId(`market-${slug(subject.id)}-evidence-${index + 1}`), type: `market.${value.type}`, subject, title: value.label, explanation: value.value, direction: EvidenceDirection.SUPPORTING, strength: EvidenceStrength.MODERATE, source: { capability: "market-intelligence", name: value.source ?? "market-analysis" }, observationIds: [observationValues[index % observationValues.length].id], createdAt: report.generatedAt, metadata: { provider: value.source ?? "derived" } }));
  const claims = report.findings.map((finding, index) => Claim.create({ id: createClaimId(`market-${slug(subject.id)}-claim-${index + 1}`), type: `market.${finding.type}`, subject, statement: finding.description, source: { capability: "market-intelligence", name: "market-finding-policy" }, evidenceIds: evidenceValues.map((value) => value.id), createdAt: report.generatedAt, metadata: { title: finding.title, severity: finding.severity } }));
  const confidence = confidenceAssessment(report.confidenceScore);
  const evaluations = claims.map((claim, index) => Evaluation.create({ id: createEvaluationId(`${claim.id.value}-evaluation`), type: "market.finding-assessment", claimId: claim.id, disposition: report.findings[index].type === "data-gap" ? EvaluationDisposition.INSUFFICIENT : report.findings[index].type === "risk" ? EvaluationDisposition.MIXED : EvaluationDisposition.SUPPORTED, summary: report.findings[index].description, confidence, evidenceIds: evidenceValues.map((value) => value.id), source: { capability: "market-intelligence", name: "market-finding-policy" }, evaluatedAt: report.generatedAt }));
  const recommendations = report.findings.filter((finding) => finding.type !== "observation").map((finding, index) => { const sourceIndex = report.findings.indexOf(finding); return Recommendation.create({ id: createRecommendationId(`market-${slug(subject.id)}-recommendation-${index + 1}`), summary: finding.type === "strength" ? `Consider the opportunity: ${finding.title}` : `Address before investing: ${finding.title}`, rationale: [finding.description], priority: finding.severity === "high" ? RecommendationPriority.HIGH : finding.severity === "moderate" ? RecommendationPriority.MEDIUM : RecommendationPriority.LOW, category: "market-analysis", confidence, evaluationIds: [evaluations[sourceIndex].id], evidenceIds: evidenceValues.map((value) => value.id), claimIds: [claims[sourceIndex].id], observationIds: observationValues.map((value) => value.id), metadata: { findingType: finding.type } }); });
  const decision = Decision.create({ id: Identifier.create(`decision-market-${slug(subject.id)}`), type: "market.analysis", outcome: "analyze", context: { subjectType: subject.type, subjectId: subject.id, effectiveAt: report.analysis.analyzedAt }, rationale: { summary: "Produce a comparable-based market analysis.", confidence }, decidedAt: report.analysis.analyzedAt, title: "Analyze market", summary: "Run market valuation and interpretation policies.", mode: DecisionMode.AUTOMATIC, confidence });
  const action = Action.create({ id: createActionId(`action-market-${slug(subject.id)}`), title: "Analyze market", summary: "Run market valuation and interpretation policies.", type: "market-analysis", priority: "medium", status: "completed", owner: { type: "system", id: "market-intelligence", displayName: "Market Intelligence" }, decisionIds: [decision.id], createdAt: report.analysis.analyzedAt, startedAt: report.analysis.analyzedAt, completedAt: report.generatedAt, outcome: { summary: report.summary, successful: true } });
  const lineage = emptyOutcomeLineage();
  const outcome = Outcome.create({ id: createOutcomeId(`outcome-market-${slug(subject.id)}`), title: "Market analysis completed", summary: report.summary, type: "external", status: "completed", successful: true, startedAt: report.analysis.analyzedAt, completedAt: report.generatedAt, metrics: { estimatedValue: report.estimatedValue, confidence: report.confidenceScore }, lineage: { ...lineage, actionIds: [action.id], decisionIds: [decision.id], observationIds: observationValues.map((value) => value.id), evidenceIds: evidenceValues.map((value) => value.id), claimIds: claims.map((value) => value.id), evaluationIds: evaluations.map((value) => value.id), recommendationIds: recommendations.map((value) => value.id) }, metadata: { capability: "market-intelligence" } });
  const intelligence = new IntelligenceBuilder().build({ result: { title: "Market intelligence", summary: report.summary, reportingPeriod: { start: report.analysis.analyzedAt, end: report.generatedAt }, confidence,
    insights: report.findings.filter((value) => value.type === "strength" || value.type === "observation").map((value) => ({ title: value.title, summary: value.description, supportingOutcomes: [outcome], confidence, rationale: [value.description] })),
    opportunities: report.findings.filter((value) => value.type === "strength").map((value) => ({ title: value.title, summary: value.description, supportingOutcomes: [outcome], confidence, rationale: [value.description], expectedImpact: { estimatedValue: report.estimatedValue } })),
    forecasts: [{ title: "Estimated market value", summary: report.summary, supportingOutcomes: [outcome], confidence, assumptions: ["Provider and comparable conditions remain materially consistent."], rationale: report.valuation.confidence.reasons.length ? report.valuation.confidence.reasons : ["Comparable valuation methodology."], prediction: report.estimatedValue, horizon: { start: report.generatedAt, end: new Date(report.generatedAt.getTime() + 31_536_000_000) } }],
    anomalies: report.findings.filter((value) => value.type === "risk" || value.type === "data-gap").map((value) => ({ title: value.title, summary: value.description, supportingOutcomes: [outcome], confidence, rationale: [value.description], expected: "market evidence within policy thresholds", actual: value.description, explanation: value.description })), metadata: { subjectId: subject.id } } });
  return { observations, evidence: EvidenceCollection.create(evidenceValues), claims: ClaimCollection.create(claims), evaluations: EvaluationCollection.create(evaluations), recommendations: RecommendationCollection.create(recommendations), decision, action, outcome, intelligence };
}

function confidenceAssessment(value: number): ConfidenceAssessment { return ConfidenceAssessment.create({ score: ConfidenceScore.clamp(value), level: value >= 80 ? ConfidenceLevel.HIGH : value >= 50 ? ConfidenceLevel.MODERATE : ConfidenceLevel.LOW, rationale: ["Mapped from Market valuation confidence."] }); }
function slug(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
