import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const {getUser,rpc,createClient,advance,dryRun,capability}=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),createClient:vi.fn(),advance:vi.fn(),dryRun:vi.fn(),capability:vi.fn()}));
vi.mock("server-only",()=>({}));
vi.mock("@supabase/supabase-js",()=>({createClient}));
vi.mock("@/features/guidebook-creation-assistant/controlled-journey",()=>({CONTROLLED_STAGES:["authorized","completed"],ControlledJourneyFault:class ControlledJourneyFault extends Error{constructor(message:string,public status:number){super(message)}},advanceControlledJourney:advance,dryRunControlledJourney:dryRun,authorizeControlledJourneyActor:capability}));
import {GET,POST} from"./route";
const valid={expectedStage:"not_started",verificationRunId:"1e392590-75b7-4b7b-b50e-1bef029944d0",customerAccountId:"91e996ee-939b-4017-9a76-6b774c39a69a",entitlementId:"4743f17f-3660-445f-a986-b4a41849ec27"};
describe("controlled journey runtime route",()=>{
 beforeEach(()=>{process.env.NEXT_PUBLIC_SUPABASE_URL="https://supabase.test";process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY="anon";process.env.CONTROLLED_GUIDEBOOK_JOURNEY_ENABLED="true";getUser.mockResolvedValue({data:{user:{id:"admin"}}});rpc.mockResolvedValue({data:true});capability.mockReset().mockResolvedValue(true);createClient.mockReturnValue({auth:{getUser},rpc});advance.mockReset().mockResolvedValue({stage:"authorized",correlationId:"c"});dryRun.mockReset().mockResolvedValue({status:"ready",runtime:"nodejs"});vi.stubGlobal("fetch",vi.fn())});
 afterEach(()=>{vi.restoreAllMocks();for(const key of["NEXT_PUBLIC_SUPABASE_URL","NEXT_PUBLIC_SUPABASE_ANON_KEY","CONTROLLED_GUIDEBOOK_JOURNEY_ENABLED"])delete process.env[key]});
 it("rejects anonymous and non-admin callers before orchestration",async()=>{expect((await POST(request(undefined,valid))).status).toBe(401);rpc.mockResolvedValue({data:false});expect((await POST(request("customer",valid))).status).toBe(401);expect(advance).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()});
 it("rejects administrators without the explicit verification capability",async()=>{capability.mockResolvedValue(false);expect((await POST(request("admin",valid))).status).toBe(403);expect(advance).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled()});
 it("rejects malformed and replayed stage commands safely",async()=>{expect((await POST(request("admin",{expectedStage:"wrong"}))).status).toBe(400);const Fault=(await import("@/features/guidebook-creation-assistant/controlled-journey")).ControlledJourneyFault;advance.mockRejectedValue(new Fault("CONTROLLED_JOURNEY_STAGE_REPLAY_REJECTED",409));const response=await POST(request("admin",valid));expect(response.status).toBe(409);expect(await response.json()).toEqual(expect.objectContaining({code:"CONTROLLED_JOURNEY_STAGE_REPLAY_REJECTED"}));expect(fetch).not.toHaveBeenCalled()});
 it("passes the authenticated administrator and explicit controlled context",async()=>{const response=await POST(request("admin",valid));expect(response.status).toBe(200);expect(advance).toHaveBeenCalledWith(expect.objectContaining({actorId:"admin",command:valid}));expect(await response.json()).toEqual(expect.objectContaining({ok:true,stage:"authorized"}))});
 it("supports a mutation-free production dry run",async()=>{const body={action:"dry_run",verificationRunId:valid.verificationRunId,customerAccountId:valid.customerAccountId,entitlementId:valid.entitlementId},response=await POST(request("admin",body));expect(response.status).toBe(200);expect(dryRun).toHaveBeenCalledWith({actorId:"admin",verificationRunId:valid.verificationRunId,customerAccountId:valid.customerAccountId,entitlementId:valid.entitlementId});expect(advance).not.toHaveBeenCalled()});
 it("exposes only sanitized gate state in the unlinked GET",async()=>{const response=await GET(request("admin")),body=await response.json();expect(response.status).toBe(200);expect(body).toEqual(expect.objectContaining({runtime:"nodejs",operationEnabled:true,customerEnablementDisabled:true,publicCohortEmpty:true}));expect(JSON.stringify(body)).not.toMatch(/key|secret|token/i)});
});
function request(token?:string,body?:unknown){return new Request("https://luxe.test/api/internal/guidebook-creation/controlled-journey",{method:body?"POST":"GET",headers:{...(token?{authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})})as never}
