import { createHash } from "node:crypto";
import { ReportFoundationError } from "./model";

export const STANDARD_REPORT_FAMILIES = ["executive", "owner", "investment", "operations"] as const;
export type StandardReportFamily = (typeof STANDARD_REPORT_FAMILIES)[number];
export type ComparisonMode = "none" | "previous_period" | "previous_year" | "budget" | "target" | "underwriting" | "portfolio_benchmark";
export type ReportFormat = "web" | "pdf" | "csv" | "zip";
export type StandardReportAudience = "portfolio_owner" | "executive_operator" | "administrator" | "property_owner" | "owner_representative" | "portfolio_operator" | "investor" | "acquisition_analyst" | "authorized_advisor" | "operator" | "property_manager" | "operations_staff";
export type ReportReadiness = "ready" | "partial" | "blocked" | "unavailable";
export type StandardReportSectionDefinition = Readonly<{ sectionCode:string; order:number; title:string; purpose:string; sectionType:"summary"|"metrics"|"trend"|"comparison"|"insights"|"decisions"|"actions"|"outcomes"|"evidence"|"limitations"; required:boolean; minimumReadiness:"required"|"conditional"|"optional"; contentProviderCode:string; emptyStatePolicyCode:string }>;
export type ReportInputRequirement = Readonly<{ inputCode:string; owningDomain:string; projectionCode:string; minimumFreshness?:string; minimumCoverage?:number; requiredForSections:readonly string[]; missingBehavior:"block_report"|"omit_section_with_disclosure"|"render_partial_with_disclosure" }>;
export type StandardReportDefinition = Readonly<{ reportCode:string; version:number; family:StandardReportFamily; name:string; shortDescription:string; decisionQuestion:string; audiences:readonly StandardReportAudience[]; status:"draft"|"approved"|"active"|"retired"; subjectType:"portfolio"|"property"|"opportunity"|"action_portfolio"; periodPolicyCode:string; supportedComparisons:readonly ComparisonMode[]; supportedFormats:readonly ReportFormat[]; sections:readonly StandardReportSectionDefinition[]; requiredInputs:readonly ReportInputRequirement[]; readinessPolicyCode:string; disclosurePolicyCode:string; requiredEntitlements:readonly string[]; authorizationPolicyCode:string; allowedDestinations:readonly string[]; effectiveFrom:string; effectiveThrough?:string; replacementReportCode?:string }>;

const PERIOD_PRESETS = Object.freeze(["current_month","previous_month","month_to_date","current_quarter","previous_quarter","quarter_to_date","current_year","previous_year","year_to_date","rolling_30_days","rolling_90_days","custom_range"] as const);
export { PERIOD_PRESETS as STANDARD_REPORT_PERIOD_PRESETS };
const formats = Object.freeze(["web","pdf","csv","zip"] as const), effectiveFrom="2026-08-13T00:00:00.000Z";
const audience = {
  executive:["portfolio_owner","executive_operator","administrator"], owner:["property_owner","owner_representative","portfolio_operator"], investment:["investor","acquisition_analyst","authorized_advisor"], operations:["operator","property_manager","operations_staff"],
} as const;
const entitlement = {
  executive:["offer:HPM-GROWTH","capability:reports.executive.read"], owner:["capability:hpm.workspace.access","resource:authorized_property"], investment:["capability:investment.analysis.create","resource:authorized_opportunity"], operations:["capability:hpm.workspace.access","role:authorized_operations"],
} as const;
const authorization = { executive:"standard_report.executive.v1",owner:"standard_report.owner_property.v1",investment:"standard_report.investment_opportunity.v1",operations:"standard_report.operations.v1" } as const;
const readiness = { executive:"standard_report.performance_readiness.v1",owner:"standard_report.performance_readiness.v1",investment:"standard_report.investment_readiness.v1",operations:"standard_report.operations_readiness.v1" } as const;

type SectionSpec=readonly[string,StandardReportSectionDefinition["sectionType"],StandardReportSectionDefinition["minimumReadiness"]?];
const section=(spec:SectionSpec,order:number):StandardReportSectionDefinition=>Object.freeze({sectionCode:spec[0],order,title:title(spec[0]),purpose:`Present ${title(spec[0]).toLowerCase()} from registered canonical projections.`,sectionType:spec[1],required:spec[2]!=="optional",minimumReadiness:spec[2]??"required",contentProviderCode:`standard_report.${spec[0]}.v1`,emptyStatePolicyCode:spec[2]==="optional"?"omit_with_disclosure.v1":"explain_unavailable.v1"});
const input=(code:string,sections:readonly string[],behavior:ReportInputRequirement["missingBehavior"]="block_report",owner?:string):ReportInputRequirement=>Object.freeze({inputCode:code,owningDomain:owner??domain(code),projectionCode:`canonical.${code}.v1`,...(behavior!=="block_report"?{minimumCoverage:0.01}:{}),requiredForSections:Object.freeze(sections),missingBehavior:behavior});

const inventory: readonly Readonly<{code:string;name:string;family:StandardReportFamily;question:string;subject:StandardReportDefinition["subjectType"];status?:"active"|"draft";sections:readonly SectionSpec[];inputs:readonly ReportInputRequirement[];comparisons?:readonly ComparisonMode[]}>[] = Object.freeze([
  {code:"EXEC-PERFORMANCE",name:"Executive Performance Report",family:"executive",question:"Where is performance strong or weak?",subject:"portfolio",sections:[["executive-summary","summary"],["reporting-period","comparison"],["performance-metrics","metrics"],["performance-trends","trend"],["performance-drivers","insights"],["priority-insights","insights"],["active-decisions","decisions"],["executive-actions","actions"],["data-quality","limitations"]],inputs:[input("hpm-performance-projection",["performance-metrics","performance-trends"]),input("hpm-insights",["performance-drivers","priority-insights"],"render_partial_with_disclosure"),input("decisions-actions",["active-decisions","executive-actions"],"render_partial_with_disclosure")],comparisons:["previous_period","previous_year","target"]},
  {code:"EXEC-PORTFOLIO",name:"Portfolio Performance Report",family:"executive",question:"Which properties require attention?",subject:"portfolio",sections:[["portfolio-summary","summary"],["property-ranking","comparison"],["property-performance","metrics"],["material-variances","insights"],["attention-properties","insights"],["data-quality-comparison","limitations"],["property-decisions-actions","actions"],["portfolio-priorities","actions"]],inputs:[input("hpm-portfolio-projection",["portfolio-summary","property-ranking","property-performance"]),input("hpm-insights",["material-variances","attention-properties"],"render_partial_with_disclosure"),input("decisions-actions",["property-decisions-actions","portfolio-priorities"],"render_partial_with_disclosure")],comparisons:["previous_period","previous_year","target","portfolio_benchmark"]},
  {code:"EXEC-DECISIONS",name:"Decisions & Actions Report",family:"executive",question:"What has been decided and executed?",subject:"action_portfolio",sections:[["period-decisions","decisions"],["decision-status-priority","decisions"],["supporting-insights","insights"],["approved-action-plans","actions"],["action-completion","actions"],["overdue-blocked-actions","actions"],["evidence-review","evidence"],["measured-outcomes","outcomes","conditional"],["executive-escalations","actions"]],inputs:[input("decisions-actions",["period-decisions","decision-status-priority","approved-action-plans","action-completion","overdue-blocked-actions","executive-escalations"]),input("hpm-insights",["supporting-insights"],"render_partial_with_disclosure"),input("outcomes-evidence",["evidence-review","measured-outcomes"],"omit_section_with_disclosure")],comparisons:["none","previous_period"]},
  {code:"EXEC-OUTCOMES",name:"Outcomes & Learning Report",family:"executive",question:"What actions produced measurable results?",subject:"action_portfolio",status:"draft",sections:[["measured-outcomes","outcomes"],["learning-summary","insights"],["limitations","limitations"]],inputs:[input("outcomes-evidence",["measured-outcomes","learning-summary"])],comparisons:["previous_period","target"]},
  {code:"OWNER-PERFORMANCE",name:"Property Performance Report",family:"owner",question:"How did my property perform?",subject:"property",sections:[["property-identity","summary"],["reporting-period","comparison"],["performance-metrics","metrics"],["booking-metrics","metrics"],["channel-mix","metrics","conditional"],["performance-trend","trend"],["performance-variance","comparison"],["data-quality","limitations"],["owner-summary","summary"],["attention-areas","insights"]],inputs:[input("hpm-property-performance",["property-identity","performance-metrics","booking-metrics","performance-trend","performance-variance"]),input("booking-channel-mix",["channel-mix"],"omit_section_with_disclosure"),input("hpm-insights",["owner-summary","attention-areas"],"render_partial_with_disclosure")],comparisons:["previous_period","previous_year","target"]},
  {code:"OWNER-REVENUE",name:"Revenue Performance Report",family:"owner",question:"What drove revenue and pricing results?",subject:"property",sections:[["revenue-summary","summary"],["pricing-performance","metrics"],["weekday-weekend","comparison"],["seasonal-performance","trend","conditional"],["gap-night-opportunity","insights","conditional"],["stay-discount-cancellation","metrics"],["source-concentration","comparison","conditional"],["revenue-opportunities","insights"],["approved-revenue-actions","actions"],["confidence-limitations","limitations"]],inputs:[input("hpm-revenue-performance",["revenue-summary","pricing-performance","weekday-weekend","stay-discount-cancellation"]),input("revenue-opportunities",["seasonal-performance","gap-night-opportunity","source-concentration","revenue-opportunities"],"omit_section_with_disclosure"),input("decisions-actions",["approved-revenue-actions"],"render_partial_with_disclosure")],comparisons:["previous_period","previous_year","target"]},
  {code:"OWNER-HEALTH",name:"Property Health Report",family:"owner",question:"What needs improvement?",subject:"property",sections:[["overall-hpm-health","summary"],["pillar-scores","metrics"],["supporting-observations","evidence"],["material-risks","insights"],["data-gaps","limitations"],["current-decisions","decisions"],["active-overdue-actions","actions"],["improvement-momentum","trend"],["next-priorities","actions"]],inputs:[input("canonical-hpm-health",["overall-hpm-health","pillar-scores","supporting-observations","material-risks","improvement-momentum"]),input("decisions-actions",["current-decisions","active-overdue-actions","next-priorities"],"render_partial_with_disclosure")],comparisons:["previous_period","target"]},
  {code:"OWNER-ACTIVITY",name:"Decisions & Activity Report",family:"owner",question:"What has Luxe Haven done or recommended?",subject:"property",sections:[["owner-safe-insights","insights"],["decision-activity","decisions"],["action-activity","actions"],["owner-safe-evidence","evidence"],["measured-outcomes","outcomes","conditional"],["administrative-interventions","actions","conditional"],["upcoming-work","actions"],["owner-input-required","actions"]],inputs:[input("owner-safe-decisions-actions",["owner-safe-insights","decision-activity","action-activity","owner-safe-evidence","administrative-interventions","upcoming-work","owner-input-required"]),input("outcomes-evidence",["measured-outcomes"],"omit_section_with_disclosure")],comparisons:["none","previous_period"]},
  {code:"OWNER-STATEMENT",name:"Owner Financial Statement",family:"owner",question:"What is my distributable financial result?",subject:"property",status:"draft",sections:[["financial-summary","summary"],["statement-lines","metrics"],["limitations","limitations"]],inputs:[input("owner-financial-ledger",["financial-summary","statement-lines"])],comparisons:["previous_period","previous_year"]},
  {code:"INV-ANALYSIS",name:"Investment Analysis Report",family:"investment",question:"Should I pursue this opportunity?",subject:"opportunity",sections:[["opportunity-summary","summary"],["analysis-identity","summary"],["customer-assumptions","evidence"],["provider-observations","evidence"],["investment-structure","summary"],["revenue-expense-assumptions","metrics"],["investment-returns","metrics"],["startup-furnishing-financing","metrics"],["comparable-market-evidence","comparison"],["investment-score-recommendation","insights"],["sensitivity-scenarios","comparison","conditional"],["risks-diligence-gaps","limitations"],["lineage-disclosures","limitations"],["saved-opportunity-destination","actions"]],inputs:[input("investment-analysis-version",["opportunity-summary","analysis-identity","customer-assumptions","investment-structure","revenue-expense-assumptions","investment-returns","startup-furnishing-financing","investment-score-recommendation","saved-opportunity-destination"]),input("provider-market-observations",["provider-observations","comparable-market-evidence"],"render_partial_with_disclosure"),input("investment-sensitivity",["sensitivity-scenarios"],"omit_section_with_disclosure")],comparisons:["none"]},
  {code:"INV-COMPARISON",name:"Opportunity Comparison Report",family:"investment",question:"Which opportunity is strongest?",subject:"opportunity",sections:[["comparison-summary","summary"],["analysis-basis","comparison"],["opportunity-metrics","metrics"],["market-risk-confidence","comparison"],["scores-recommendations","insights"],["non-comparable-inputs","limitations"]],inputs:[input("investment-analysis-comparison",["comparison-summary","analysis-basis","opportunity-metrics","market-risk-confidence","scores-recommendations"]),input("comparison-compatibility",["non-comparable-inputs"],"render_partial_with_disclosure")],comparisons:["none"]},
  {code:"INV-DILIGENCE",name:"Investment Due Diligence Report",family:"investment",question:"What must be validated before proceeding?",subject:"opportunity",sections:[["opportunity-overview","summary"],["assumption-validation","evidence"],["property-facts","evidence"],["market-str-evidence","evidence"],["revenue-expense-assumptions","metrics"],["regulatory-considerations","limitations","conditional"],["customer-financing-insurance","evidence","conditional"],["furnishing-launch-budget","metrics","conditional"],["open-questions-documents","actions"],["risk-register","insights"],["decision-readiness","summary"],["recommended-next-actions","actions"],["advice-disclaimer","limitations"]],inputs:[input("investment-diligence",["opportunity-overview","assumption-validation","property-facts","revenue-expense-assumptions","open-questions-documents","risk-register","decision-readiness","recommended-next-actions"]),input("provider-market-observations",["market-str-evidence"],"render_partial_with_disclosure"),input("customer-diligence-inputs",["regulatory-considerations","customer-financing-insurance","furnishing-launch-budget"],"omit_section_with_disclosure")],comparisons:["none"]},
  {code:"INV-PERFORMANCE",name:"Actual vs. Underwriting Report",family:"investment",question:"Is the investment meeting expectations?",subject:"opportunity",status:"draft",sections:[["actual-performance","metrics"],["underwriting-comparison","comparison"],["limitations","limitations"]],inputs:[input("investment-actual-vs-underwriting",["actual-performance","underwriting-comparison"])],comparisons:["underwriting"]},
  {code:"OPS-ATTENTION",name:"Operations Attention Report",family:"operations",question:"What requires action now?",subject:"action_portfolio",sections:[["operational-health","summary"],["priority-issues","insights"],["severity-impact","metrics"],["affected-property","summary"],["supporting-evidence","evidence"],["assignment-due-status","actions"],["blockers-dependencies","actions"],["escalations","actions"],["recommended-next-action","actions"]],inputs:[input("hpm-operational-attention",["operational-health","priority-issues","severity-impact","affected-property","supporting-evidence"]),input("decisions-actions",["assignment-due-status","blockers-dependencies","escalations","recommended-next-action"])],comparisons:["none","previous_period"]},
  {code:"OPS-ACTIONS",name:"Action Execution Report",family:"operations",question:"Is work progressing correctly?",subject:"action_portfolio",sections:[["action-plans","actions"],["actions-by-state","actions"],["completion-rate","metrics"],["overdue-review-failed","actions"],["dependencies-recurring","actions"],["evidence-completion","evidence"],["escalations","actions"],["measured-outcomes","outcomes","conditional"],["reassignment-intervention","actions"]],inputs:[input("decisions-actions",["action-plans","actions-by-state","completion-rate","overdue-review-failed","dependencies-recurring","evidence-completion","escalations","reassignment-intervention"]),input("outcomes-evidence",["measured-outcomes"],"omit_section_with_disclosure")],comparisons:["previous_period","target"]},
  {code:"OPS-QUALITY",name:"Property Quality Report",family:"operations",question:"Where is service quality at risk?",subject:"property",sections:[["quality-overview","summary"],["guest-experience-observations","evidence","conditional"],["review-themes","insights","conditional"],["cleaning-turnover-observations","evidence","conditional"],["guidebook-completeness","metrics","conditional"],["amenity-furnishing-exceptions","insights","conditional"],["recurring-defects","insights","conditional"],["corrective-actions","actions"],["evidence-review-status","evidence"],["quality-priorities","actions"]],inputs:[input("quality-observations",["quality-overview","guest-experience-observations","review-themes","cleaning-turnover-observations","amenity-furnishing-exceptions","recurring-defects"],"render_partial_with_disclosure"),input("guidebook-quality-projection",["guidebook-completeness"],"omit_section_with_disclosure","guidebook"),input("decisions-actions",["corrective-actions","evidence-review-status","quality-priorities"])],comparisons:["previous_period","target"]},
  {code:"OPS-TURNOVER",name:"Turnover Performance Report",family:"operations",question:"Are turnovers timely and complete?",subject:"property",status:"draft",sections:[["turnover-performance","metrics"],["turnover-exceptions","insights"],["limitations","limitations"]],inputs:[input("turnover-performance",["turnover-performance","turnover-exceptions"])],comparisons:["previous_period","target"]},
  {code:"OPS-MAINTENANCE",name:"Maintenance Performance Report",family:"operations",question:"What maintenance risk is emerging?",subject:"property",status:"draft",sections:[["maintenance-performance","metrics"],["maintenance-risks","insights"],["limitations","limitations"]],inputs:[input("maintenance-performance",["maintenance-performance","maintenance-risks"])],comparisons:["previous_period","target"]},
]);

export const STANDARD_REPORT_DEFINITIONS: readonly StandardReportDefinition[] = Object.freeze(inventory.map(item=>{const wasRecommendedActive=!item.status;return Object.freeze({reportCode:item.code,version:wasRecommendedActive?2:1,family:item.family,name:item.name,shortDescription:`${item.name} supports the decision: ${item.question}`,decisionQuestion:item.question,audiences:Object.freeze([...audience[item.family]]),status:"draft"as const,subjectType:item.subject,periodPolicyCode:item.family==="investment"?"snapshot_version.v1":"shared_date_context.v1",supportedComparisons:Object.freeze(item.comparisons??(["previous_period"] as const)),supportedFormats:formats,sections:Object.freeze(item.sections.map(section)),requiredInputs:Object.freeze(item.inputs),readinessPolicyCode:readiness[item.family],disclosurePolicyCode:item.family==="investment"?"investment_lineage_and_advice.v1":"standard_data_quality.v1",requiredEntitlements:Object.freeze([...entitlement[item.family]]),authorizationPolicyCode:authorization[item.family],allowedDestinations:Object.freeze([`reports.${item.family}.web`,`reports.${item.family}.pdf`,`reports.${item.family}.csv`,`reports.${item.family}.zip`]),effectiveFrom,...(wasRecommendedActive?{replacementReportCode:item.code}:{})});}));

export function validateStandardReportDefinition(definition:StandardReportDefinition){if(!STANDARD_REPORT_FAMILIES.includes(definition.family)||!definition.reportCode||definition.version<1||!definition.decisionQuestion||!definition.audiences.length||!definition.sections.length||!definition.requiredInputs.length||!definition.readinessPolicyCode||!definition.authorizationPolicyCode||!definition.requiredEntitlements.length)throw new ReportFoundationError("REPORT_INVALID_CONFIGURATION","Standard report definition is incomplete.");const orders=definition.sections.map(value=>value.order),codes=definition.sections.map(value=>value.sectionCode);if(new Set(orders).size!==orders.length||orders.some((value,index)=>value!==index)||new Set(codes).size!==codes.length)throw new ReportFoundationError("REPORT_INVALID_CONFIGURATION","Standard report section order is invalid.");for(const input of definition.requiredInputs)if(input.requiredForSections.some(code=>!codes.includes(code)))throw new ReportFoundationError("REPORT_INVALID_CONFIGURATION","Report input references an unknown section.");return definition;}
for(const definition of STANDARD_REPORT_DEFINITIONS)validateStandardReportDefinition(definition);
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`:JSON.stringify(value);
export const STANDARD_REPORT_CATALOG_FINGERPRINT=createHash("sha256").update(stable(STANDARD_REPORT_DEFINITIONS)).digest("hex");
export const standardReportDefinitionCatalog=Object.freeze({fingerprint:STANDARD_REPORT_CATALOG_FINGERPRINT,list:(status?:StandardReportDefinition["status"])=>Object.freeze(STANDARD_REPORT_DEFINITIONS.filter(value=>!status||value.status===status)),get:(code:string,version?:number)=>{const matching=STANDARD_REPORT_DEFINITIONS.filter(value=>value.reportCode===code&&(version===undefined||value.version===version)).sort((a,b)=>b.version-a.version),found=matching[0];if(!found)throw new ReportFoundationError("REPORT_DEFINITION_NOT_FOUND","Standard report definition was not found.");return found;}});

export function projectStandardReportCatalog(input:Readonly<{authenticated:boolean;entitlements:readonly string[];authorizedFamilies:readonly StandardReportFamily[]}>){if(!input.authenticated)return Object.freeze([]);return Object.freeze(STANDARD_REPORT_DEFINITIONS.filter(value=>value.status==="active").map(value=>{const familyAuthorized=input.authorizedFamilies.includes(value.family),entitled=value.requiredEntitlements.some(rule=>input.entitlements.includes(rule));return Object.freeze({reportCode:value.reportCode,version:value.version,family:value.family,name:value.name,description:value.shortDescription,decisionQuestion:value.decisionQuestion,subjectType:value.subjectType,supportedFormats:value.supportedFormats,periodPolicyCode:value.periodPolicyCode,expectedContent:Object.freeze(value.sections.map(section=>section.title)),dataRequirements:Object.freeze(value.requiredInputs.map(requirement=>({inputCode:requirement.inputCode,missingBehavior:requirement.missingBehavior}))),availabilityState:familyAuthorized&&entitled?"available"as const:"unavailable"as const,...(!(familyAuthorized&&entitled)?{reasonUnavailable:familyAuthorized?"ENTITLEMENT_REQUIRED":"NOT_AUTHORIZED"}: {})});}));}

export function evaluateStandardReportReadiness(input:Readonly<{definition:StandardReportDefinition;authorized:boolean;entitled:boolean;subjectAvailable:boolean;inputs:Readonly<Record<string,"available"|"partial"|"missing"|"stale">>}>):Readonly<{status:ReportReadiness;affectedSections:readonly string[];reasonCodes:readonly string[]}>{if(input.definition.status!=="active"||!input.entitled)return Object.freeze({status:"unavailable",affectedSections:Object.freeze([]),reasonCodes:Object.freeze([input.definition.status!=="active"?"REPORT_INACTIVE":"ENTITLEMENT_REQUIRED"])});if(!input.authorized||!input.subjectAvailable)return Object.freeze({status:"blocked",affectedSections:Object.freeze([]),reasonCodes:Object.freeze([!input.authorized?"REPORT_NOT_AUTHORIZED":"REPORT_SUBJECT_UNAVAILABLE"])});const blocking:string[]=[],partial:string[]=[];for(const requirement of input.definition.requiredInputs){const state=input.inputs[requirement.inputCode]??"missing";if(state==="available")continue;(requirement.missingBehavior==="block_report"?blocking:partial).push(...requirement.requiredForSections);}if(blocking.length)return Object.freeze({status:"blocked",affectedSections:Object.freeze([...new Set(blocking)]),reasonCodes:Object.freeze(["REQUIRED_INPUT_MISSING"])});if(partial.length)return Object.freeze({status:"partial",affectedSections:Object.freeze([...new Set(partial)]),reasonCodes:Object.freeze(["CONDITIONAL_INPUT_INCOMPLETE"])});return Object.freeze({status:"ready",affectedSections:Object.freeze([]),reasonCodes:Object.freeze([])});}

function title(value:string){return value.split("-").map(word=>word[0]?.toUpperCase()+word.slice(1)).join(" ");}
function domain(code:string){if(code.includes("investment")||code.includes("provider")||code.includes("diligence")||code.includes("comparison"))return"investment_intelligence";if(code.includes("decision")||code.includes("outcome"))return"hpm_decisions_actions";if(code.includes("guidebook"))return"guidebook";if(code.includes("quality")||code.includes("turnover")||code.includes("maintenance"))return"operations";return"hpm";}
