import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { evaluateStandardReportReadiness, projectStandardReportCatalog, STANDARD_REPORT_CATALOG_FINGERPRINT, STANDARD_REPORT_DEFINITIONS, STANDARD_REPORT_FAMILIES, STANDARD_REPORT_PERIOD_PRESETS, standardReportDefinitionCatalog, standardReportDefinitionFingerprint, validateStandardReportDefinition } from ".";

describe("standard report catalog",()=>{
  it("fails all thirteen recommended definitions closed after experience reconciliation",()=>{expect(standardReportDefinitionCatalog.list("active")).toHaveLength(0);expect(standardReportDefinitionCatalog.list("draft")).toHaveLength(18);expect(new Set(STANDARD_REPORT_DEFINITIONS.map(value=>value.family))).toEqual(new Set(STANDARD_REPORT_FAMILIES));expect(STANDARD_REPORT_CATALOG_FINGERPRINT).toMatch(/^[a-f0-9]{64}$/);});
  it("preserves deferred definitions at v1 and returns formerly active definitions as v2 drafts",()=>{for(const code of["EXEC-OUTCOMES","OWNER-STATEMENT","INV-PERFORMANCE","OPS-TURNOVER","OPS-MAINTENANCE"])expect(standardReportDefinitionCatalog.get(code).version).toBe(1);for(const definition of STANDARD_REPORT_DEFINITIONS.filter(value=>!["EXEC-OUTCOMES","OWNER-STATEMENT","INV-PERFORMANCE","OPS-TURNOVER","OPS-MAINTENANCE"].includes(value.reportCode)))expect(definition.version).toBe(2);});
  it("gives every definition a deterministic complete immutable contract",()=>{for(const definition of STANDARD_REPORT_DEFINITIONS){expect(validateStandardReportDefinition(definition)).toBe(definition);expect(definition.decisionQuestion).toBeTruthy();expect(definition.sections.map(value=>value.order)).toEqual(definition.sections.map((_,index)=>index));expect(definition.requiredInputs.every(input=>input.requiredForSections.every(code=>definition.sections.some(section=>section.sectionCode===code)))).toBe(true);expect(definition.supportedFormats).toEqual(["web","pdf","csv","zip"]);expect(standardReportDefinitionFingerprint(definition)).toMatch(/^[a-f0-9]{64}$/);}});
  it("uses shared periods for performance and snapshots for investment",()=>{expect(STANDARD_REPORT_PERIOD_PRESETS).toContain("month_to_date");expect(STANDARD_REPORT_PERIOD_PRESETS).toContain("custom_range");for(const definition of STANDARD_REPORT_DEFINITIONS.filter(value=>value.status==="active")){expect(definition.periodPolicyCode).toBe(definition.family==="investment"?"snapshot_version.v1":"shared_date_context.v1");if(definition.family==="investment")expect(definition.supportedComparisons).toEqual(["none"]);}});
  it("fails drafts closed while preserving deterministic readiness semantics",()=>{const definition=standardReportDefinitionCatalog.get("OWNER-REVENUE"),active={...definition,status:"active"as const};expect(evaluateStandardReportReadiness({definition,authorized:true,entitled:true,subjectAvailable:true,inputs:{}}).status).toBe("unavailable");expect(evaluateStandardReportReadiness({definition:active,authorized:true,entitled:true,subjectAvailable:true,inputs:{"hpm-revenue-performance":"available","revenue-opportunities":"missing","decisions-actions":"available"}}).status).toBe("partial");expect(evaluateStandardReportReadiness({definition:active,authorized:true,entitled:true,subjectAvailable:true,inputs:{}}).status).toBe("blocked");expect(evaluateStandardReportReadiness({definition:active,authorized:false,entitled:true,subjectAvailable:true,inputs:{}}).reasonCodes).toEqual(["REPORT_NOT_AUTHORIZED"]);});
  it("advertises no unavailable definition through the customer-safe projection",()=>{expect(projectStandardReportCatalog({authenticated:false,entitlements:[],authorizedFamilies:[]})).toEqual([]);expect(projectStandardReportCatalog({authenticated:true,entitlements:["capability:hpm.workspace.access"],authorizedFamilies:["owner"]})).toEqual([]);});
});

describe("standard report catalog persistence",()=>{const sql=readFileSync("supabase/migrations/20260813100000_standard_report_catalog.sql","utf8");it("enforces RLS, immutable publication, drift rejection, and registered operations",()=>{for(const table of["standard_report_definitions","standard_report_catalog_events"])expect(sql).toContain(`alter table public.${table} enable row level security`);expect(sql).toContain("STANDARD_REPORT_REGISTRY_DRIFT");expect(sql).toContain("STANDARD_REPORT_DEFINITION_IMMUTABLE");for(const operation of["register_standard_report_definition","clone_standard_report_definition","replace_standard_report_draft","transition_standard_report_definition"])expect(sql).toContain(operation);expect(sql).toContain("revoke all");expect(sql).not.toMatch(/grant (insert|update|delete|all) on public\.standard_report_definitions to authenticated/i);});});
