import type { SupabaseClient } from "@supabase/supabase-js";
import type { Report, ReportSnapshot, ReportVersion } from "./model";
import { ReportFoundationError } from "./model";
import type { ReportActor, ReportRepository } from "./application";
import type { ReportGenerationRepository } from "./generation";

export class SupabaseCanonicalReportRepository implements ReportRepository, ReportGenerationRepository {
  constructor(private readonly client: Pick<SupabaseClient, "from" | "rpc">, private readonly clock: () => string = () => new Date().toISOString()) {}

  async reserveGeneration(input: Parameters<ReportGenerationRepository["reserveGeneration"]>[0]) {
    const result = await this.client.rpc("reserve_canonical_report_generation", { p_report: input.report ?? null, p_report_id: input.reportId, p_version_id: input.versionId, p_definition: input.definition, p_actor_user_id: input.actor.userId, p_workspace_id: input.actor.tenantId, p_scope: input.scope, p_property_ids: input.propertyIds, p_period: input.period, p_comparison_period: input.comparisonPeriod ?? null, p_title: input.title, p_requested_at: input.requestedAt, p_idempotency_key: input.idempotencyKey ?? null, p_request_fingerprint: input.requestFingerprint });
    if (result.error) throw generationPersistenceFailure(result.error.message, result.error.code);
    const payload = result.data as unknown as { version: Record<string, unknown>; replay: boolean };
    return Object.freeze({ version: mapVersion(payload.version), replay: Boolean(payload.replay) });
  }

  async createReport(input: Report) {
    const result = await this.client.from("canonical_reports").insert({ id: input.reportId, workspace_id: input.tenantId, family: input.family, report_type: input.reportType, definition_id: input.definitionId, created_by_profile_id: input.createdBy, created_at: input.createdAt, archived_at: input.archivedAt ?? null }).select("*").single();
    if (result.error) throw persistenceFailure(result.error.code); return mapReport(result.data);
  }
  async createVersion(input: ReportVersion) {
    const propertyIds = input.scope.kind === "property" ? [input.scope.propertyId] : "propertyIds" in input.scope ? input.scope.propertyIds : [];
    const result = await this.client.from("canonical_report_versions").insert({ id: input.reportVersionId, report_id: input.reportId, workspace_id: input.tenantId, version_number: input.versionNumber, definition_id: input.definitionId, definition_version: input.definitionVersion, family: input.family, report_type: input.reportType, title: input.title, description: input.description ?? null, requested_by_profile_id: input.requestedBy, generated_for_id: input.generatedForId ?? null, scope_kind: input.scope.kind, scope_snapshot: input.scope, property_ids: propertyIds, owner_id: input.ownerId ?? (input.scope.kind === "owner_portfolio" ? input.scope.ownerId : null), opportunity_id: input.opportunityId ?? (input.scope.kind === "investment_opportunity" ? input.scope.opportunityId : null), status: input.status, period_snapshot: input.period, comparison_period_snapshot: input.comparisonPeriod ?? null, content_snapshot: input.snapshot ?? null, snapshot_schema_version: input.snapshot?.schemaVersion ?? null, source_lineage_snapshot: input.snapshot?.lineage ?? [], freshness_snapshot: input.snapshot?.freshness ?? null, data_gap_snapshot: input.snapshot?.dataGaps ?? [], requested_at: input.requestedAt, generation_started_at: input.generationStartedAt ?? null, generated_at: input.generatedAt ?? null, failure_code: input.failureCode ?? null, failure_message: input.failureMessage ?? null }).select("*").single();
    if (result.error) throw persistenceFailure(result.error.code); return mapVersion(result.data);
  }
  async markGenerating(reportVersionId: string) { await this.transition(reportVersionId, "draft", { status: "generating", generation_started_at: this.clock() }); }
  async markReady(reportVersionId: string, snapshot: ReportSnapshot) { await this.transition(reportVersionId, "generating", { status: "ready", content_snapshot: snapshot, snapshot_schema_version: snapshot.schemaVersion, source_lineage_snapshot: snapshot.lineage, freshness_snapshot: snapshot.freshness, data_gap_snapshot: snapshot.dataGaps, generated_at: this.clock(), failure_code: null, failure_message: null }); }
  async markFailed(reportVersionId: string, failure: Readonly<{ code: string; message: string }>) { await this.transition(reportVersionId, "generating", { status: "failed", failure_code: failure.code.slice(0, 100), failure_message: failure.message.slice(0, 500) }); }
  async getReport(reportId: string, actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_reports").select("*").eq("workspace_id", actor.tenantId).eq("id", reportId).maybeSingle(); if (result.error) throw persistenceFailure(result.error.code); return result.data ? mapReport(result.data) : null; }
  async getVersion(reportId: string, reportVersionId: string, actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_report_versions").select("*").eq("workspace_id", actor.tenantId).eq("report_id", reportId).eq("id", reportVersionId).maybeSingle(); if (result.error) throw persistenceFailure(result.error.code); return result.data ? mapVersion(result.data) : null; }
  async listReports(actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_reports").select("*").eq("workspace_id", actor.tenantId).is("archived_at", null).order("created_at", { ascending: false }); if (result.error) throw persistenceFailure(result.error.code); return Object.freeze((result.data ?? []).map(mapReport)); }
  async listVersions(reportId: string, actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_report_versions").select("*").eq("workspace_id", actor.tenantId).eq("report_id", reportId).order("version_number", { ascending: false }); if (result.error) throw persistenceFailure(result.error.code); return Object.freeze((result.data ?? []).map(mapVersion)); }
  async archiveReport(reportId: string, actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_reports").update({ archived_at: this.clock() }).eq("workspace_id", actor.tenantId).eq("id", reportId); if (result.error) throw persistenceFailure(result.error.code); }
  async restoreReport(reportId: string, actor: ReportActor) { assertActor(actor); const result = await this.client.from("canonical_reports").update({ archived_at: null }).eq("workspace_id", actor.tenantId).eq("id", reportId); if (result.error) throw persistenceFailure(result.error.code); }
  private async update(id: string, values: Readonly<Record<string, unknown>>) { const result = await this.client.from("canonical_report_versions").update(values).eq("id", id); if (result.error) throw persistenceFailure(result.error.code); }
  private async transition(id: string, expected: "draft" | "generating", values: Readonly<Record<string, unknown>>) { const result = await this.client.from("canonical_report_versions").update(values).eq("id", id).eq("status", expected).select("id").maybeSingle(); if (result.error) throw persistenceFailure(result.error.code); if (!result.data) throw new ReportFoundationError("REPORT_CONCURRENT_MODIFICATION", "Report generation state changed concurrently."); }
}

function assertActor(actor: ReportActor) { if (!actor.authenticated || !actor.tenantId || !actor.userId) throw new ReportFoundationError("REPORT_SCOPE_FORBIDDEN", "Report access is forbidden."); }
function persistenceFailure(code?: string) { return new ReportFoundationError(code === "23505" ? "REPORT_INVALID_CONFIGURATION" : "REPORT_SCOPE_FORBIDDEN", code === "23505" ? "Report version conflicts with an existing version." : "Report persistence failed safely."); }
function generationPersistenceFailure(message?: string, code?: string) { if (message?.includes("REPORT_IDEMPOTENCY_CONFLICT")) return new ReportFoundationError("REPORT_IDEMPOTENCY_CONFLICT", "The idempotency key was reused with different report input."); if (code === "23505") return new ReportFoundationError("REPORT_CONCURRENT_MODIFICATION", "Report generation conflicted with another request."); return new ReportFoundationError("REPORT_GENERATION_FAILED", "Report generation persistence failed safely."); }
function mapReport(row: Record<string, unknown>): Report { return Object.freeze({ reportId: String(row.id), tenantId: String(row.workspace_id), family: row.family as Report["family"], reportType: String(row.report_type), definitionId: String(row.definition_id), createdBy: String(row.created_by_profile_id), createdAt: String(row.created_at), ...(row.archived_at ? { archivedAt: String(row.archived_at) } : {}) }); }
function mapVersion(row: Record<string, unknown>): ReportVersion { const snapshot = row.content_snapshot as ReportSnapshot | null; return Object.freeze({ reportId: String(row.report_id), reportVersionId: String(row.id), versionNumber: Number(row.version_number), definitionId: String(row.definition_id), definitionVersion: Number(row.definition_version), family: row.family as ReportVersion["family"], reportType: String(row.report_type), title: String(row.title), ...(row.description ? { description: String(row.description) } : {}), tenantId: String(row.workspace_id), requestedBy: String(row.requested_by_profile_id), ...(row.generated_for_id ? { generatedForId: String(row.generated_for_id) } : {}), scope: row.scope_snapshot as ReportVersion["scope"], authorizedPropertyIds: Object.freeze((row.property_ids as unknown[] | null ?? []).map(String)), ...(row.owner_id ? { ownerId: String(row.owner_id) } : {}), ...(row.opportunity_id ? { opportunityId: String(row.opportunity_id) } : {}), status: row.status as ReportVersion["status"], period: row.period_snapshot as ReportVersion["period"], ...(row.comparison_period_snapshot ? { comparisonPeriod: row.comparison_period_snapshot as NonNullable<ReportVersion["comparisonPeriod"]> } : {}), ...(snapshot ? { snapshot } : {}), requestedAt: String(row.requested_at), ...(row.generation_started_at ? { generationStartedAt: String(row.generation_started_at) } : {}), ...(row.generated_at ? { generatedAt: String(row.generated_at) } : {}), ...(row.failure_code ? { failureCode: String(row.failure_code) } : {}), ...(row.failure_message ? { failureMessage: String(row.failure_message) } : {}) }); }
