import { ActionPlan, type ActionActor, type ActionPlanProps, type PlatformAction } from "../../domain";
import type { PlatformActionRepository } from "../../application/action-repository";
import { ExecutePersistenceConflict, type ActionPlanRepository, type ExecuteActivityEvent, type ExecuteActivityRepository, type ExecuteNotificationIntent, type ExecuteNotificationOutbox, type ExecuteTransactionContext, type ExecuteUnitOfWork } from "../../application/execute-application";
import { mapPlatformActionToPersistenceRows } from "./action-persistence-mapper";
import { resolveFurnishingActivation } from "@/features/furnishing-studio/activation";

type DatabaseError=Readonly<{message:string;code?:string}>;
type DatabaseResult=Readonly<{data:unknown;error:DatabaseError|null}>;
interface QueryBuilder extends PromiseLike<DatabaseResult>{select(columns?:string):QueryBuilder;eq(column:string,value:unknown):QueryBuilder;order(column:string,options?:Readonly<{ascending?:boolean}>):QueryBuilder;limit(count:number):QueryBuilder;}
export interface ExecuteSupabaseClient{from(table:string):QueryBuilder;rpc(name:string,args:Readonly<Record<string,unknown>>):PromiseLike<DatabaseResult>;}
type PlanRow=Readonly<{workspace_id:string;id:string;title:string;description:string|null;origin_type:ActionPlanProps["origin"]["type"];origin_id:string|null;source_capability:string|null;decision_id:string|null;scope_type:ActionPlanProps["scope"]["type"];property_ids:string[];owner_type:ActionPlanProps["owner"]["type"];owner_id:string|null;status:ActionPlanProps["status"];priority:ActionPlanProps["priority"];start_at:string|null;target_completion_at:string|null;expected_outcome:string|null;success_metrics:unknown;source_context:unknown;created_by_type:ActionActor["type"];created_by_id:string|null;activated_by_id:string|null;activated_at:string|null;completed_at:string|null;cancelled_at:string|null;created_at:string;updated_at:string;version:number}>;
type DraftRow=Readonly<{workspace_id:string;plan_id:string;id:string;position:number;title:string;description:string|null;action_type:string|null;category:string|null;priority:ActionPlanProps["priority"]|null;property_id:string|null;owner_type:ActionPlanProps["owner"]["type"]|null;owner_id:string|null;start_at:string|null;due_at:string|null;completion_criteria:unknown;evidence_policy:unknown;expected_outcome:string|null;success_metric:string|null;dependencies:unknown;measurement_requirement:unknown}>;

export class SupabaseExecutePlanRepository implements ActionPlanRepository{
  public constructor(private readonly client:ExecuteSupabaseClient){}
  public async findById(workspaceId:string,planId:string):Promise<ActionPlan|null>{const result=await this.client.from("platform_action_plans").select("*").eq("workspace_id",workspaceId).eq("id",planId).limit(1);if(result.error)throw new Error("Execute plan read failed.");const rows=asRows<PlanRow>(result.data);if(!rows[0])return null;const drafts=await this.drafts(workspaceId,planId);return mapPlan(rows[0],drafts);}
  public async list(workspaceId:string):Promise<readonly ActionPlan[]>{const result=await this.client.from("platform_action_plans").select("*").eq("workspace_id",workspaceId).order("updated_at",{ascending:false});if(result.error)throw new Error("Execute plan list failed.");const plans=asRows<PlanRow>(result.data);return Promise.all(plans.map(async(row)=>mapPlan(row,await this.drafts(workspaceId,row.id))));}
  public async add():Promise<void>{throw new Error("Execute plan writes require SupabaseExecuteUnitOfWork.");}
  public async replace():Promise<void>{throw new Error("Execute plan writes require SupabaseExecuteUnitOfWork.");}
  private async drafts(workspaceId:string,planId:string):Promise<readonly DraftRow[]>{const result=await this.client.from("platform_action_plan_draft_actions").select("*").eq("workspace_id",workspaceId).eq("plan_id",planId).order("position",{ascending:true});if(result.error)throw new Error("Execute Draft Action read failed.");return asRows<DraftRow>(result.data);}
}

export class SupabaseExecuteActivityRepository implements ExecuteActivityRepository{public constructor(private readonly client:ExecuteSupabaseClient){}public async append():Promise<void>{throw new Error("Execute activity writes require SupabaseExecuteUnitOfWork.");}public async list(workspaceId:string,entityType:ExecuteActivityEvent["entityType"],entityId:string):Promise<readonly ExecuteActivityEvent[]>{const result=await this.client.from("platform_action_activity").select("*").eq("workspace_id",workspaceId).eq("entity_type",entityType).eq("entity_id",entityId).order("occurred_at",{ascending:true});if(result.error)throw new Error("Execute activity history read failed.");return Object.freeze(asRows<Readonly<Record<string,unknown>>>(result.data).map((row)=>({id:String(row.id),workspaceId:String(row.workspace_id),entityType:row.entity_type as ExecuteActivityEvent["entityType"],entityId:String(row.entity_id),...(row.action_id?{actionId:String(row.action_id)}:{}),eventType:String(row.event_type),actor:actor(row.actor_type as ActionActor["type"],row.actor_id?String(row.actor_id):null),occurredAt:date(String(row.occurred_at)),metadata:record(row.metadata),correlationId:String(row.correlation_id??"")})));}}

export class SupabaseExecuteUnitOfWork implements ExecuteUnitOfWork{
  public constructor(private readonly dependencies:Readonly<{client:ExecuteSupabaseClient;plans:SupabaseExecutePlanRepository;actions:PlatformActionRepository;activity:SupabaseExecuteActivityRepository}>){ }
  public async execute<T>(operation:(context:ExecuteTransactionContext)=>Promise<T>):Promise<T>{const staged=new StagedWrites(this.dependencies.plans,this.dependencies.actions,this.dependencies.activity);const value=await operation(staged.context);await this.commit(staged);return value;}
  private async commit(staged:StagedWrites):Promise<void>{if(!staged.planWrite&&!staged.actions.length&&!staged.activity.length&&!staged.notifications.length)return;if(!staged.planWrite)throw new Error("Execute transaction requires a plan mutation.");const plan=staged.planWrite.plan;if(staged.actions.length){const result=await this.dependencies.client.rpc("activate_execute_action_plan",{p_workspace_id:plan.props.workspaceId,p_plan_id:plan.props.id,p_expected_version:staged.planWrite.expectedVersion,p_activated_at:plan.props.activatedAt?.toISOString(),p_actor_id:plan.props.activatedBy?.id??null,p_action_payloads:staged.actions.map((action)=>executeActionPayload(action,plan.props)),p_activity_events:staged.activity.map(activityRow),p_notification_intents:staged.notifications.map(notificationRow)});if(result.error)await this.throwPersistence(result.error,plan);return;}const result=await this.dependencies.client.rpc("save_execute_action_plan",{p_plan:planRow(plan.props),p_draft_actions:plan.props.actions.map((action)=>draftRow(plan.props.workspaceId,plan.props.id,action)),p_activity_events:staged.activity.map(activityRow),p_expected_version:staged.planWrite.isNew?null:staged.planWrite.expectedVersion});if(result.error)await this.throwPersistence(result.error,plan);}
  private async throwPersistence(error:DatabaseError,plan:ActionPlan):Promise<never>{if(error.code==="40001"){const current=await this.dependencies.plans.findById(plan.props.workspaceId,plan.props.id);throw new ExecutePersistenceConflict(current?.props.version);}throw persistenceError(error);}
}

class StagedWrites{
  planWrite?:Readonly<{plan:ActionPlan;expectedVersion:number;isNew:boolean}>;actions:PlatformAction[]=[];activity:ExecuteActivityEvent[]=[];notifications:ExecuteNotificationIntent[]=[];
  public readonly context:ExecuteTransactionContext;
  public constructor(plans:ActionPlanRepository,canonical:PlatformActionRepository,activityReader:ExecuteActivityRepository){const planRepo:ActionPlanRepository={findById:(workspace,id)=>this.planWrite?.plan.props.workspaceId===workspace&&this.planWrite.plan.props.id===id?Promise.resolve(this.planWrite.plan):plans.findById(workspace,id),list:(workspace)=>plans.list(workspace),add:async(plan)=>{if(this.planWrite)throw new Error("Only one plan mutation is allowed per Execute transaction.");this.planWrite={plan,expectedVersion:0,isNew:true};},replace:async(plan,expectedVersion)=>{if(this.planWrite)throw new Error("Only one plan mutation is allowed per Execute transaction.");this.planWrite={plan,expectedVersion,isNew:false};}};const actionRepo:PlatformActionRepository={findById:(input)=>canonical.findById(input),find:(input)=>canonical.find(input),add:async({action})=>{this.actions.push(action);},replace:async()=>{throw new Error("Canonical Action replacement is not part of plan activation.");}};const activity:ExecuteActivityRepository={append:async(events)=>{this.activity.push(...events);},list:(workspace,type,id)=>activityReader.list(workspace,type,id)};const notifications:ExecuteNotificationOutbox={add:async(intents)=>{this.notifications.push(...intents);}};this.context=Object.freeze({plans:planRepo,actions:actionRepo,activity,notifications});}
}

export class SupabaseExecuteOutboxReader{public constructor(private readonly client:ExecuteSupabaseClient){}public async listPending(workspaceId:string,limit=100):Promise<readonly Readonly<Record<string,unknown>>[]>{const result=await this.client.from("execute_notification_outbox").select("*").eq("workspace_id",workspaceId).eq("delivery_status","pending").order("created_at",{ascending:true}).limit(limit);if(result.error)throw new Error("Execute notification outbox read failed.");return Object.freeze(asRows<Readonly<Record<string,unknown>>>(result.data));}}

function mapPlan(row:PlanRow,drafts:readonly DraftRow[]):ActionPlan{const createdBy=actor(row.created_by_type,row.created_by_id);const activatedBy=row.activated_by_id?actor("user",row.activated_by_id):undefined;return ActionPlan.reconstitute({id:row.id,workspaceId:row.workspace_id,title:row.title,...(row.description?{description:row.description}:{}),origin:{type:row.origin_type,...(row.origin_id?{id:row.origin_id}:{}),...(row.source_capability?{capability:row.source_capability}:{}),context:record(row.source_context)},...(row.decision_id?{linkedDecisionId:row.decision_id}:{}),scope:{type:row.scope_type,propertyIds:Object.freeze(row.property_ids??[])},owner:actor(row.owner_type,row.owner_id),status:row.status,priority:row.priority,...(row.start_at?{startAt:date(row.start_at)}:{}),...(row.target_completion_at?{targetCompletionAt:date(row.target_completion_at)}:{}),...(row.expected_outcome?{expectedOutcome:row.expected_outcome}:{}),successMetrics:stringArray(row.success_metrics),actions:drafts.map(mapDraft),createdBy,createdAt:date(row.created_at),...(activatedBy?{activatedBy}:{}),...(row.activated_at?{activatedAt:date(row.activated_at)}:{}),...(row.completed_at?{completedAt:date(row.completed_at)}:{}),...(row.cancelled_at?{cancelledAt:date(row.cancelled_at)}:{}),version:row.version,events:[{type:"created",actor:createdBy,occurredAt:date(row.created_at),version:1},...(activatedBy&&row.activated_at?[{type:"activated" as const,actor:activatedBy,occurredAt:date(row.activated_at),version:row.version}]:[])]});}
function mapDraft(row:DraftRow){return{id:row.id,position:row.position,title:row.title,...(row.description?{description:row.description}:{}),...(row.action_type?{actionType:row.action_type}:{}),...(row.category?{category:row.category}:{}),...(row.priority?{priority:row.priority}:{}),...(row.property_id?{propertyId:row.property_id}:{}),...(row.owner_type?{owner:actor(row.owner_type,row.owner_id)}:{}),...(row.start_at?{startAt:date(row.start_at)}:{}),...(row.due_at?{dueAt:date(row.due_at)}:{}),completionCriteria:stringArray(row.completion_criteria),evidencePolicy:record(row.evidence_policy),...(row.expected_outcome?{expectedOutcome:row.expected_outcome}:{}),...(row.success_metric?{successMetric:row.success_metric}:{}),dependencies:stringArray(row.dependencies),...(row.measurement_requirement?{measurementRequirement:record(row.measurement_requirement)}:{})};}
function planRow(plan:ActionPlanProps){return{workspace_id:plan.workspaceId,id:plan.id,title:plan.title,description:plan.description??null,origin_type:plan.origin.type,origin_id:plan.origin.id??null,source_capability:plan.origin.capability??null,decision_id:plan.linkedDecisionId??null,scope_type:plan.scope.type,property_ids:plan.scope.propertyIds,owner_type:plan.owner.type,owner_id:plan.owner.id??null,status:plan.status,priority:plan.priority,start_at:plan.startAt?.toISOString()??null,target_completion_at:plan.targetCompletionAt?.toISOString()??null,expected_outcome:plan.expectedOutcome??null,success_metrics:plan.successMetrics,source_context:plan.origin.context??{},created_by_type:plan.createdBy.type,created_by_id:plan.createdBy.id??null,activated_by_id:plan.activatedBy?.id??null,activated_at:plan.activatedAt?.toISOString()??null,completed_at:plan.completedAt?.toISOString()??null,cancelled_at:plan.cancelledAt?.toISOString()??null,created_at:plan.createdAt.toISOString(),updated_at:(plan.activatedAt??plan.completedAt??plan.cancelledAt??plan.createdAt).toISOString(),version:plan.version};}
function draftRow(workspaceId:string,planId:string,action:ActionPlanProps["actions"][number]){return{workspace_id:workspaceId,plan_id:planId,id:action.id,position:action.position,title:action.title,description:action.description??null,action_type:action.actionType??null,category:action.category??null,priority:action.priority??null,property_id:action.propertyId??null,owner_type:action.owner?.type??null,owner_id:action.owner?.id??null,start_at:action.startAt?.toISOString()??null,due_at:action.dueAt?.toISOString()??null,completion_criteria:action.completionCriteria??[],evidence_policy:action.evidencePolicy??{},expected_outcome:action.expectedOutcome??null,success_metric:action.successMetric??null,dependencies:action.dependencies??[],measurement_requirement:action.measurementRequirement??null};}
function executeActionPayload(action:PlatformAction,plan:ActionPlanProps){const payload=mapPlatformActionToPersistenceRows(action),proposal=plan.actions.find((item)=>item.id===action.id.value);if(!proposal)throw new Error("Activated Action does not match its canonical plan proposal.");return{...payload,action:{...payload.action,plan_id:plan.id,property_id:proposal.propertyId??null,scope_type:proposal.propertyId?"property":plan.scope.type,category:proposal.category??"other",expected_outcome:proposal.expectedOutcome??plan.expectedOutcome??null,completion_criteria:proposal.completionCriteria??[],evidence_policy:proposal.evidencePolicy??{mode:"optional"},measurement_requirement:proposal.measurementRequirement??null,review_required:proposal.evidencePolicy?.reviewRequired===true}};}
function activityRow(event:ExecuteActivityEvent){return{workspace_id:event.workspaceId,id:event.id,entity_type:event.entityType,entity_id:event.entityId,action_id:event.actionId??null,event_type:event.eventType,actor_type:event.actor.type,actor_id:event.actor.id??null,occurred_at:event.occurredAt.toISOString(),metadata:event.metadata,correlation_id:event.correlationId,causation_id:null};}
function notificationRow(intent:ExecuteNotificationIntent){if(intent.productFamily==="furnishing"){const decision=resolveFurnishingActivation({globalKillSwitch:true,globalState:"disabled",workspaceKillSwitch:false,workspaceEnabled:false,cohortEligible:false,capabilityEnabled:false,configurationValid:true,policyVersion:"fs008a-v1"});if(!decision.allowed)throw new Error(`FURNISHING_NOTIFICATION_${decision.reason.toUpperCase()}`)}return{workspace_id:intent.workspaceId,id:intent.id,recipient_type:intent.recipientType,recipient_id:intent.recipientId,event_type:intent.eventType,entity_type:intent.entityType,entity_id:intent.entityId,safe_template_variables:intent.templateVariables,channel:intent.channel,delivery_status:intent.status,idempotency_key:intent.idempotencyKey,attempt_count:intent.attemptCount,created_at:intent.createdAt.toISOString()};}
function actor(type:ActionActor["type"],id:string|null):ActionActor{return Object.freeze({type,...(id?{id}:{})});}function date(value:string):Date{const result=new Date(value);if(Number.isNaN(result.getTime()))throw new TypeError("Execute persistence timestamp is invalid.");return result;}function stringArray(value:unknown):readonly string[]{return Object.freeze(Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[]);}function record(value:unknown):Readonly<Record<string,unknown>>{return Object.freeze(value&&typeof value==="object"&&!Array.isArray(value)?{...(value as Record<string,unknown>)}:{});}function asRows<T>(value:unknown):T[]{return Array.isArray(value)?value as T[]:[];}function persistenceError(error:DatabaseError):Error{if(error.code==="40001")return new ExecutePersistenceConflict();const value=new Error("Execute persistence command failed.");value.name=error.code??"EXECUTE_PERSISTENCE_FAILURE";return value;}
