import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
export default async function CommerceOrderDetailPage({params}:{params:Promise<{orderId:string}>}){
 const{orderId}=await params,client=await createClient();
 const[{data:order},{data:payments},{data:refunds},{data:activity},{data:receipts}]=await Promise.all([
  client.from("commerce_orders").select("id,order_number,status,payment_status,currency,subtotal_minor,total_minor,finalized_discount_minor,finalized_tax_minor,finalized_total_minor,paid_at,revision,commerce_order_lines(product_snapshot,price_snapshot,quantity,line_total_minor)").eq("id",orderId).maybeSingle(),
  client.from("commerce_payments").select("id,status,amount_minor,captured_amount_minor,refunded_amount_minor,attempt_number,created_at,failure_code").eq("order_id",orderId).order("attempt_number"),
  client.from("commerce_refunds").select("id,status,amount_minor,created_at").eq("order_id",orderId).order("created_at"),
  client.from("commerce_activity").select("id,event_type,summary,resulting_state,occurred_at").eq("order_id",orderId).order("occurred_at"),
  client.from("commerce_webhook_receipts").select("id,provider_event_type,status,attempts,last_error_code,received_at").eq("related_order_id",orderId).order("received_at"),
 ]);if(!order)notFound();
 const money=(minor:number|null)=>new Intl.NumberFormat("en-US",{style:"currency",currency:order.currency}).format(Number(minor??0)/100);
 return <main className="mx-auto max-w-6xl space-y-8 px-5 py-10"><header><p className="eyebrow">Commerce order</p><h1 className="mt-2 text-4xl font-semibold">{order.order_number}</h1><p className="mt-3 text-stone-600">Order: {order.status} · Payment: {order.payment_status??"not received"} · Revision {order.revision}</p></header><dl className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border p-5"><dt>Subtotal</dt><dd className="mt-2 text-2xl font-semibold">{money(order.subtotal_minor)}</dd></div><div className="rounded-2xl border p-5"><dt>Tax</dt><dd className="mt-2 text-2xl font-semibold">{money(order.finalized_tax_minor)}</dd></div><div className="rounded-2xl border p-5"><dt>Final total</dt><dd className="mt-2 text-2xl font-semibold">{money(order.finalized_total_minor??order.total_minor)}</dd></div></dl><section><h2 className="text-2xl font-semibold">Payment attempts</h2><ul className="mt-4 space-y-3">{(payments??[]).map(payment=><li className="rounded-xl border p-4" key={payment.id}>Attempt {payment.attempt_number}: {payment.status} · {money(payment.amount_minor)}{payment.failure_code?` · ${payment.failure_code}`:""}</li>)}</ul>{!payments?.length?<p className="mt-4 text-stone-600">No provider payment attempt has been reconciled.</p>:null}</section><section><h2 className="text-2xl font-semibold">Refunds</h2><ul className="mt-4 space-y-3">{(refunds??[]).map(refund=><li className="rounded-xl border p-4" key={refund.id}>{refund.status} · {money(refund.amount_minor)}</li>)}</ul>{!refunds?.length?<p className="mt-4 text-stone-600">No refunds.</p>:null}</section><section><h2 className="text-2xl font-semibold">Activity</h2><ol className="mt-4 space-y-3">{(activity??[]).map(item=><li className="rounded-xl border p-4" key={item.id}><span className="font-semibold">{item.event_type}</span><span className="block text-sm text-stone-600">{new Date(item.occurred_at).toLocaleString()} · {item.summary}</span></li>)}</ol></section><section><h2 className="text-2xl font-semibold">Webhook receipts</h2><p className="mt-2 text-sm text-stone-600">Safe diagnostic metadata only. Raw payloads are not displayed or retained.</p><ul className="mt-4 space-y-3">{(receipts??[]).map(receipt=><li className="rounded-xl border p-4" key={receipt.id}>{receipt.provider_event_type} · {receipt.status} · attempt {receipt.attempts}{receipt.last_error_code?` · ${receipt.last_error_code}`:""}</li>)}</ul></section></main>
}
