"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { clientWorkspaceNavigation, operationsConsoleNavigation, matchesNavigationRoute, recordPlatformNavigationEvent, resolveNavigation, resolveUserCapabilities, type NavigationItem, type NavigationAvailability, type PlatformExperience } from "@/platform/experience";

type ShellProps = Readonly<{ children: ReactNode; experience: PlatformExperience; role?: string | null }>;
const groupLabels: Record<string, string> = { home: "Home", hpm: "HPM lifecycle", business: "Business workspaces", services: "Services", settings: "Settings", operations: "Operations", platform: "Platform", content: "Content" };
const iconLabels: Record<string, string> = { home: "HM", observe: "OB", understand: "UN", decide: "DC", execute: "EX", learn: "LN", property: "PR", investment: "IN", booking: "BK", message: "MS", report: "RP", service: "SV", settings: "ST", operations: "OP", integration: "IT", content: "CT" };
const availabilityLabels: Record<NavigationAvailability, string> = { available: "", "limited-preview": "Limited", "coming-soon": "Soon" };

export function ClientWorkspaceShell({ children, role }: Omit<ShellProps, "experience">) { return <PlatformShell experience="client-workspace" role={role}>{children}</PlatformShell>; }
export function OperationsConsoleShell({ children, role }: Omit<ShellProps, "experience">) { return <PlatformShell experience="operations-console" role={role}>{children}</PlatformShell>; }

export function PlatformShell({ children, experience, role }: ShellProps) {
  const pathname = usePathname();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [collapsed, setCollapsed] = useState(false);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const capabilities = resolveUserCapabilities({ authenticated: true, role });
  const source = experience === "client-workspace" ? clientWorkspaceNavigation : operationsConsoleNavigation;
  const navigation = resolveNavigation(source, capabilities);
  const details = pageDetails(pathname, experience);
  useEffect(() => { const saved = window.localStorage.getItem(`luxe-haven:${experience}:sidebar-collapsed`); if (saved !== "true") return; const frame = window.requestAnimationFrame(() => setCollapsed(true)); return () => window.cancelAnimationFrame(frame); }, [experience]);
  useEffect(() => { if (!mobileOpen) { document.body.style.overflow = ""; triggerRef.current?.focus(); return; } document.body.style.overflow = "hidden"; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setMobileOpen(false); }; document.addEventListener("keydown", onKeyDown); return () => { document.body.style.overflow = ""; document.removeEventListener("keydown", onKeyDown); }; }, [mobileOpen]);
  const toggleCollapsed = () => { const next = !collapsed; setCollapsed(next); window.localStorage.setItem(`luxe-haven:${experience}:sidebar-collapsed`, String(next)); recordPlatformNavigationEvent("platform_navigation_collapsed", { experience, collapsed: next }); };
  return <div className="min-h-screen bg-[#f8f7f4]">
    <aside className={["fixed inset-y-0 left-0 z-40 hidden border-r border-white/10 bg-stone-950 text-white transition-[width] lg:block", collapsed ? "w-20" : "w-72"].join(" ")}><ShellNavigation experience={experience} navigation={navigation} pathname={pathname} collapsed={collapsed} onNavigate={() => undefined} onToggle={toggleCollapsed} /></aside>
    {mobileOpen ? <div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true" aria-label={`${experience === "client-workspace" ? "Workspace" : "Operations Console"} navigation`}><button type="button" aria-label="Close navigation menu" className="absolute inset-0 bg-stone-950/60 backdrop-blur-sm" onClick={() => setMobileOpen(false)} /><aside className="relative h-full w-[88%] max-w-96 shadow-2xl"><ShellNavigation experience={experience} navigation={navigation} pathname={pathname} collapsed={false} onNavigate={() => setMobileOpen(false)} onToggle={() => undefined} /></aside></div> : null}
    <div className={collapsed ? "lg:pl-20" : "lg:pl-72"}><header className="sticky top-0 z-30 border-b border-stone-200 bg-[#f8f7f4]/90 backdrop-blur-xl"><div className="flex min-h-20 items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><button ref={triggerRef} type="button" onClick={() => { setMobileOpen(true); recordPlatformNavigationEvent("platform_mobile_navigation_opened", { experience }); }} aria-label="Open navigation menu" aria-expanded={mobileOpen} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-stone-200 bg-white text-stone-950 shadow-sm lg:hidden"><span aria-hidden="true" className="space-y-1"><span className="block h-0.5 w-4 bg-current" /><span className="block h-0.5 w-4 bg-current" /><span className="block h-0.5 w-4 bg-current" /></span></button><div className="min-w-0"><p className="truncate text-xs font-semibold uppercase tracking-[0.16em] text-stone-500">{details.eyebrow}</p><p className="truncate text-lg font-semibold text-stone-950">{details.title}</p><Breadcrumbs items={details.breadcrumbs} /></div></div><div className="flex items-center gap-3"><EnvironmentIndicator /><span className="hidden rounded-full border border-stone-200 bg-white px-3 py-2 text-xs font-semibold text-stone-600 sm:inline-flex">{experience === "client-workspace" ? "Workspace" : "Internal"}</span><Link href={experience === "client-workspace" ? "/dashboard/settings" : "/admin"} aria-label="Open user profile menu" className="flex h-10 w-10 items-center justify-center rounded-full bg-stone-950 text-xs font-semibold text-white">TL</Link></div></div></header><main>{children}</main></div>
  </div>;
}

function ShellNavigation({ experience, navigation, pathname, collapsed, onNavigate, onToggle }: { experience: PlatformExperience; navigation: readonly NavigationItem[]; pathname: string; collapsed: boolean; onNavigate: () => void; onToggle: () => void }) { const groups = [...new Set(navigation.map(item => item.group))]; return <div className="flex h-full flex-col"><div className="flex min-h-20 items-center justify-between border-b border-white/10 px-4"><Link href={experience === "client-workspace" ? "/dashboard" : "/admin"} onClick={onNavigate} className="min-w-0"><span className="block truncate text-xs font-semibold uppercase tracking-[0.22em] text-stone-500">Luxe Haven</span>{!collapsed ? <span className="mt-1 block truncate text-lg font-semibold">{experience === "client-workspace" ? "HPM Workspace" : "Operations Console"}</span> : null}</Link><button type="button" onClick={onToggle} aria-label={collapsed ? "Expand navigation" : "Collapse navigation"} className="hidden h-9 w-9 items-center justify-center rounded-lg border border-white/10 text-xs text-stone-400 hover:bg-white/10 lg:flex">{collapsed ? "→" : "←"}</button></div><nav aria-label={experience === "client-workspace" ? "Workspace navigation" : "Operations Console navigation"} className="flex-1 overflow-y-auto px-3 py-5">{groups.map(group => <div key={group} className="mb-6"><p className={collapsed ? "sr-only" : "mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-stone-600"}>{groupLabels[group]}</p><div className="space-y-1">{navigation.filter(item => item.group === group).map(item => <NavigationBranch key={item.id} item={item} pathname={pathname} collapsed={collapsed} onNavigate={onNavigate} />)}</div></div>)}</nav><div className="border-t border-white/10 p-3"><Link href={experience === "client-workspace" ? "/dashboard/settings" : "/admin"} onClick={onNavigate} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-xs font-semibold text-stone-400 hover:bg-white/10 hover:text-white"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10 text-[10px]">{experience === "client-workspace" ? "ST" : "OP"}</span>{collapsed ? <span className="sr-only">{experience === "client-workspace" ? "Workspace Settings" : "Operations Console"}</span> : experience === "client-workspace" ? "Workspace Settings" : "Internal workspace"}</Link></div></div>; }
function NavigationBranch({ item, pathname, collapsed, onNavigate }: { item: NavigationItem; pathname: string; collapsed: boolean; onNavigate: () => void }) { const childActive = item.children?.some(child => matchesNavigationRoute(pathname, child.activeMatch) || child.children?.some(grandchild => matchesNavigationRoute(pathname, grandchild.activeMatch))); const active = matchesNavigationRoute(pathname, item.activeMatch) || Boolean(childActive); const contextual = active && item.group === "business"; const disabled = item.availability !== "available" || !item.href; const content = <><span className={["flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-[10px] font-semibold", active ? "bg-stone-950 text-white" : "border border-white/10 bg-white/[0.04] text-stone-400"].join(" ")}>{iconLabels[item.icon]}</span>{collapsed ? <span className="sr-only">{item.label}</span> : <span className="min-w-0 flex-1 truncate">{item.label}</span>}{!collapsed && item.availability !== "available" ? <span className="rounded-full border border-white/10 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-stone-500">{availabilityLabels[item.availability]}</span> : null}</>; return <div><div className={["flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition", active && !contextual ? "bg-white text-stone-950" : contextual ? "bg-white/10 text-white" : disabled ? "cursor-default text-stone-500" : "text-stone-400 hover:bg-white/[0.06] hover:text-white"].join(" ")} aria-current={active && !contextual ? "page" : undefined}>{disabled ? <span aria-disabled="true" title={item.description}>{content}</span> : <Link href={item.href!} onClick={() => { recordPlatformNavigationEvent("platform_navigation_item_selected", { navigationItemId: item.id, destinationRoute: item.href }); onNavigate(); }} className="flex min-h-11 flex-1 items-center gap-3">{content}</Link>}</div>{!collapsed && item.children?.length ? <div className="ml-5 mt-1 space-y-1 border-l border-white/10 pl-3">{item.children.map(child => <NavigationBranch key={child.id} item={child} pathname={pathname} collapsed={false} onNavigate={onNavigate} />)}</div> : null}</div>; }
function Breadcrumbs({ items }: { items: readonly { id: string; label: string; href?: string; current?: boolean }[] }) { return <nav aria-label="Breadcrumb" className="mt-1 hidden items-center gap-1 text-[11px] text-stone-500 sm:flex">{items.map((item, index) => <span key={item.id} className="flex items-center gap-1">{index ? <span aria-hidden="true">/</span> : null}{item.current || !item.href ? <span aria-current={item.current ? "page" : undefined} className="max-w-48 truncate">{item.label}</span> : <Link href={item.href} className="hover:text-stone-950">{item.label}</Link>}</span>)}</nav>; }
function EnvironmentIndicator() { const environment = process.env.NEXT_PUBLIC_APP_ENV; return environment && environment !== "production" ? <span className="rounded-full border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{environment}</span> : null; }
function pageDetails(pathname: string, experience: PlatformExperience) { if (experience === "operations-console") return { eyebrow: "Internal operations", title: pathname === "/admin" ? "Operations Console" : pathname.startsWith("/admin/integrations") ? "Integrations" : pathname.startsWith("/admin/properties") ? "Properties" : pathname.startsWith("/admin/owners") ? "Customers" : pathname.startsWith("/admin/inquiries") ? "Support" : "Operations Console", breadcrumbs: [{ id: "operations", label: "Operations Console", href: "/admin" }, ...(pathname === "/admin" ? [{ id: "current", label: "Dashboard", current: true }] : [{ id: "current", label: pathname.split("/")[2] ?? "Workspace", current: true }]) ] }; if (pathname.startsWith("/dashboard/investments/portfolio")) { const label = pathname.includes("/analyses/") ? "Historical Analysis" : pathname.endsWith("/compare") ? "Opportunity Comparison" : pathname.split("/").length > 5 ? "Opportunity Detail" : "Opportunity Portfolio"; return { eyebrow: "Decide · Investments", title: label, breadcrumbs: [{ id: "home", label: "Home", href: "/dashboard" }, { id: "decide", label: "Decide", href: "/dashboard/investments" }, { id: "investments", label: "Investments", href: "/dashboard/investments" }, { id: "current", label, current: true }] }; } if (pathname.startsWith("/dashboard/investments")) return { eyebrow: "Decide · Investments", title: "Investment Analysis", breadcrumbs: [{ id: "home", label: "Home", href: "/dashboard" }, { id: "decide", label: "Decide", href: "/dashboard/investments" }, { id: "current", label: "Investment Analysis", current: true }] }; if (pathname.startsWith("/dashboard/actions")) return { eyebrow: "Execute", title: "Action Center", breadcrumbs: [{ id: "home", label: "Home", href: "/dashboard" }, { id: "execute", label: "Execute", href: "/dashboard/actions" }, { id: "current", label: "Action Center", current: true }] }; if (pathname.startsWith("/dashboard/insights")) return { eyebrow: "Observe", title: "Revenue Intelligence", breadcrumbs: [{ id: "home", label: "Home", href: "/dashboard" }, { id: "observe", label: "Observe", href: "/dashboard/insights" }, { id: "current", label: "Revenue Intelligence", current: true }] }; if (pathname.startsWith("/properties")) return { eyebrow: "Properties", title: "Properties", breadcrumbs: [{ id: "home", label: "Home", href: "/dashboard" }, { id: "current", label: "Properties", current: true }] }; return { eyebrow: "Home", title: "Home", breadcrumbs: [{ id: "current", label: "Home", current: true }] }; }
