import{describe,expect,it}from"vitest";import{applyCalibrationToLesson,createLearningCalibration,getLearningAdministration,requestSafeLearningRetry,type LearningAdministrationInput,type LearningCalibration,type OrganizationalLesson}from".";
const at="2026-07-25T00:00:00Z",evidence=[{type:"review"as const,capability:"platform-learning",sourceId:"review:1"}];
const lesson:OrganizationalLesson={id:"lesson:1:v1",seriesId:"lesson:1",revision:1,workspaceId:"w",learningSubjectId:"s",category:"revenue",statement:"Weekend pricing improves RevPAR.",applicability:[{dimension:"market",value:"Phoenix"}],confidence:"moderate",maturity:"supported",status:"validated",contradictionState:"none",evidence,sourceReviewIds:["review:1","review:2"],sourceCandidateIds:["candidate:1"],policyVersion:"lesson-v1",createdByProfileId:"p",createdAt:at};
const calibration=(overrides:Partial<LearningCalibration>={}):LearningCalibration=>({id:"calibration:1",workspaceId:"w",lessonId:lesson.id,lessonSeriesId:lesson.seriesId,lessonRevision:1,direction:"increase-confidence",status:"pending",previousConfidence:"moderate",proposedConfidence:"high",previousMaturity:"supported",proposedMaturity:"established",reason:"Two additional evidence-backed reviews support the lesson.",evidence,reviewedByProfileId:"admin",policyVersion:"learning-calibration-v1",createdAt:at,...overrides});
describe("Learning calibration and administration",()=>{
 it("creates evidence-backed calibration without changing the lesson",()=>{const result=createLearningCalibration(calibration(),lesson);expect(result.event.type).toBe("CalibrationRequested");expect(lesson.confidence).toBe("moderate")});
 it("rejects skipped confidence or maturity levels",()=>expect(()=>createLearningCalibration(calibration({previousConfidence:"low",proposedConfidence:"high"}),{...lesson,confidence:"low"})).toThrow(/one governed level/i));
 it("approval creates a new immutable lesson revision",()=>{const result=applyCalibrationToLesson(calibration(),lesson,{newLessonId:"lesson:1:v2",approvedByProfileId:"admin",approvedAt:"2026-07-26T00:00:00Z",authorized:true});expect(result.lesson).toMatchObject({id:"lesson:1:v2",revision:2,confidence:"high",maturity:"established",supersedesLessonId:"lesson:1:v1"});expect(lesson.revision).toBe(1)});
 it("requires explicit approval permission",()=>expect(()=>applyCalibrationToLesson(calibration(),lesson,{newLessonId:"v2",approvedByProfileId:"p",approvedAt:at,authorized:false})).toThrow(/permission/i));
 it("projects coverage, health, distributions, queues, and alerts",()=>{const input:LearningAdministrationInput={reviews:[{id:"r",status:"waiting",createdAt:"2026-01-01",evidenceCount:0}],lessons:[{id:"l",category:"revenue",status:"validated",confidence:"low",maturity:"emerging",evidenceCount:0,createdAt:"2026-01-01"}],candidates:[{id:"c",createdAt:at}],contradictions:[{id:"x",state:"possible",createdAt:at}],calibrations:[calibration()],measurementJobs:[{id:"j",workspaceId:"w",status:"failed",attempts:3,failureCode:"provider_unavailable",createdAt:at}],governanceJobs:[],evaluatedAt:"2026-08-30T00:00:00Z"},result=getLearningAdministration(input);expect(result.queues).toMatchObject({pendingReviews:1,candidateLessons:1,calibrationReviews:1,contradictions:1,failedJobs:1});expect(result.alerts.map(x=>x.type)).toEqual(expect.arrayContaining(["evidence-quality","contradiction-rate","calibration-overdue","coverage-decline"]))});
 it("queues only authorized retryable failures",()=>{const job={id:"j",workspaceId:"w",type:"measurement-retry"as const,aggregateId:"m",status:"failed"as const,attempts:2,failureCode:"provider_unavailable",createdAt:at};expect(requestSafeLearningRetry(job,{id:"retry",requestedAt:at,authorized:true,retryableCodes:["provider_unavailable"]}).status).toBe("queued");expect(()=>requestSafeLearningRetry({...job,failureCode:"permission_denied"},{id:"retry",requestedAt:at,authorized:true,retryableCodes:["provider_unavailable"]})).toThrow(/safe/i)});
});
