import{describe,expect,it}from"vitest";import{createLearningLesson,createLearningSubject,createLineageEdge,createMeasurementPlan,createOutcomeReview,reviseLearningLesson,PlatformLearningError}from".";
const at="2026-07-25T00:00:00.000Z";
describe("canonical Learning lineage",()=>{
 it("references a feature-owned object without importing or owning it",()=>{const{subject,event}=createLearningSubject({id:"subject-1",workspaceId:"workspace-1",subjectType:"investment-scenario",sourceCapability:"investment-intelligence",sourceId:"scenario-7",sourceVersion:"3",createdAt:at,createdByProfileId:"profile-1"});expect(subject.sourceId).toBe("scenario-7");expect(event.type).toBe("LearningSubjectCreated");expect(Object.isFrozen(subject)).toBe(true)});
 it("forms typed edges and rejects self lineage",()=>{expect(createLineageEdge({id:"edge-1",workspaceId:"workspace-1",subjectId:"subject-1",from:{type:"decision",capability:"platform-decisions",sourceId:"decision-1"},to:{type:"action",capability:"action-center",sourceId:"action-1"},relationship:"executed-by",createdAt:at}).relationship).toBe("executed-by");expect(()=>createLineageEdge({id:"bad",workspaceId:"workspace-1",subjectId:"subject-1",from:{type:"action",capability:"action-center",sourceId:"same"},to:{type:"action",capability:"action-center",sourceId:"same"},relationship:"supported-by",createdAt:at})).toThrowError(PlatformLearningError)});
 it("preserves expected outcomes without evaluating them",()=>{const plan=createMeasurementPlan({id:"plan-1",workspaceId:"workspace-1",subjectId:"subject-1",baseline:{noi:100},expectedOutcomes:[{id:"expected-1",planId:"plan-1",metric:"noi",expectedValue:120,expectedDirection:"increase",confidence:"moderate"}],measurementWindow:{type:"90-days",start:"2026-07-25",end:"2026-10-23"},confidence:"moderate",version:1,createdAt:at});expect(plan.expectedOutcomes[0]?.expectedValue).toBe(120)});
 it("requires evidence for completed reviews",()=>expect(()=>createOutcomeReview({id:"review-1",workspaceId:"workspace-1",subjectId:"subject-1",measurementPlanId:"plan-1",expectedOutcomeIds:["expected-1"],measuredOutcomeIds:["measurement-1"],status:"completed",evidenceIds:[],createdAt:at,createdByProfileId:"profile-1"})).toThrowError(PlatformLearningError));
 it("creates evidence-backed lessons and appends corrections as revisions",()=>{const first=createLearningLesson({id:"lesson-1",workspaceId:"workspace-1",subjectId:"subject-1",statement:"Seasonal pricing improved NOI.",applicability:[{scope:"season",label:"summer"}],confidence:"moderate",maturity:"emerging",status:"candidate",evidenceIds:["evidence-1"],lineageEdgeIds:["edge-1"],revision:1,createdAt:at,createdByProfileId:"profile-1"}).lesson,next=reviseLearningLesson(first,{...first,id:"lesson-2",statement:"Seasonal pricing improved summer NOI.",status:"validated",createdAt:"2026-08-01T00:00:00.000Z"}).lesson;expect(first.statement).toBe("Seasonal pricing improved NOI.");expect(next.supersedesLessonId).toBe("lesson-1");expect(next.revision).toBe(2)});
});
