import{describe,expect,it}from"vitest";import{activateMeasurementPlan,createMeasurementPlanRevision,evaluateOutcomeMetric,evaluateOutcomeReviewReadiness,summarizeOutcomeReview,transitionOutcomeReview,reviseMeasuredOutcome,type ExpectedOutcomeSpecification,type LearningMetricDefinition,type MeasuredOutcomeRecord,type OperationalOutcomeReview,type VersionedMeasurementPlan}from".";
const metric=(overrides:Partial<LearningMetricDefinition>={}):LearningMetricDefinition=>({key:"adr",name:"ADR",valueType:"money",unit:"night",currency:"USD",directionality:"higher-is-better",aggregation:"average",definitionVersion:"adr-v1",...overrides});
const expected=(overrides:Partial<ExpectedOutcomeSpecification>={}):ExpectedOutcomeSpecification=>({id:"expected-1",metric:metric(),baselineValue:{type:"money",value:190,unit:"night",currency:"USD"},expectation:{type:"target",target:{type:"money",value:200,unit:"night",currency:"USD"}},tolerance:{type:"absolute",value:5},materialityPolicy:{key:"adr-materiality",metricKey:"adr",thresholds:[{level:"minor",absolute:5},{level:"material",absolute:20}],version:"v1"},required:true,measurementSource:{adapterKey:"investment",metricKey:"adr",scope:{type:"property",id:"property-1"},policyVersion:"v1"},confidence:"high",evidence:[{type:"evidence",capability:"investment-intelligence",sourceId:"evidence-1"}],...overrides});
const plan=(overrides:Partial<VersionedMeasurementPlan>={}):VersionedMeasurementPlan=>({id:"plan-1-v1",seriesId:"plan-1",workspaceId:"workspace-1",learningSubjectId:"subject-1",revision:1,status:"draft",title:"First-year review",baselineSnapshot:{capturedAt:"2026-01-01T00:00:00Z",scope:{type:"property",id:"property-1",timezone:"America/Phoenix"},values:[{metric:metric(),value:{type:"money",value:190,unit:"night",currency:"USD"}}],qualification:"actual",sourceVersions:[{source:"investment-analysis",version:"3"}],evidence:[{type:"evidence",capability:"investment-intelligence",sourceId:"evidence-1"}],confidence:"high",freshness:"current",schemaVersion:"v1"},expectedOutcomes:[expected()],executionRequirement:"action-completed",reviewWindows:[{id:"window-1",sequence:1,label:"90 days",trigger:{type:"after-action-completion",referenceId:"action-1",delayDays:90},measurementPeriod:{type:"relative",durationDays:90},reviewOpensAt:"2026-10-01T00:00:00Z",reviewDueAt:"2026-10-15T00:00:00Z",required:true,timezone:"America/Phoenix"}],ownerProfileId:"profile-1",confidence:"high",evidence:[{type:"decision",capability:"platform-decisions",sourceId:"decision-1"}],policyVersion:"measurement-v1",createdByProfileId:"profile-1",createdAt:"2026-07-01T00:00:00Z",...overrides});
const measured=(value=205,overrides:Partial<MeasuredOutcomeRecord>={}):MeasuredOutcomeRecord=>({id:"measurement-1",workspaceId:"workspace-1",outcomeReviewId:"review-1",expectedOutcomeId:"expected-1",metric:metric(),value:{type:"money",value,unit:"night",currency:"USD"},measurementPeriod:{start:"2026-07-01",end:"2026-09-30"},observedAt:"2026-10-01T00:00:00Z",qualification:"actual",source:{type:"automatic",adapterKey:"investment",sourceReference:"projection-5"},status:"measured",evidence:[{type:"evidence",capability:"investment-intelligence",sourceId:"measurement-evidence"}],confidence:"high",freshness:"current",sourceVersions:[{source:"investment-performance",version:"5"}],measurementPolicyVersion:"measurement-v1",revision:1,createdAt:"2026-10-01T00:00:00Z",...overrides});
describe("Outcome measurement",()=>{
 it("activates valid plans and requires revisions after activation",()=>{const active=activateMeasurementPlan(plan(),"2026-07-02T00:00:00Z");expect(active.status).toBe("active");const revision=createMeasurementPlanRevision(active,{...plan(),id:"plan-1-v2",createdAt:"2026-07-03T00:00:00Z"});expect(revision.revision).toBe(2);expect(revision.status).toBe("draft");expect(active.revision).toBe(1)});
 it("waits for execution before measurement",()=>{const readiness=evaluateOutcomeReviewReadiness({plan:activateMeasurementPlan(plan(),"2026-07-02T00:00:00Z"),window:plan().reviewWindows[0]!,execution:{requirement:"action-completed",sourceReferences:[],status:"waiting",evidence:[]},measurements:[],evaluatedAt:"2026-10-02T00:00:00Z",policyVersion:"readiness-v1"});expect(readiness.status).toBe("waiting-for-execution")});
 it("detects ready and overdue reviews",()=>{const active=activateMeasurementPlan(plan(),"2026-07-02T00:00:00Z"),execution={requirement:"action-completed"as const,sourceReferences:[],status:"confirmed"as const,evidence:[]};expect(evaluateOutcomeReviewReadiness({plan:active,window:active.reviewWindows[0]!,execution,measurements:[measured()],evaluatedAt:"2026-10-02T00:00:00Z",policyVersion:"v1"}).status).toBe("ready-for-review");expect(evaluateOutcomeReviewReadiness({plan:active,window:active.reviewWindows[0]!,execution,measurements:[],evaluatedAt:"2026-10-20T00:00:00Z",policyVersion:"v1"}).status).toBe("overdue")});
 it("calculates absolute and relative variance without rounding",()=>{const result=evaluateOutcomeMetric(expected(),measured(210),"evaluation-v1");expect(result.absoluteVariance).toBe(10);expect(result.relativeVariance).toBe(.05);expect(result.status).toBe("exceeded");expect(result.directionEvaluation).toBe("favorable")});
 it("keeps percentage points distinct from relative variance",()=>{const spec=expected({metric:metric({key:"occupancy",name:"Occupancy",valueType:"percentage-point",unit:"ratio",currency:undefined}),baselineValue:{type:"percentage-point",value:.65,unit:"ratio"},expectation:{type:"target",target:{type:"percentage-point",value:.7,unit:"ratio"}},materialityPolicy:{key:"occupancy",metricKey:"occupancy",thresholds:[],version:"v1"}}),actual=measured(.66,{metric:spec.metric,value:{type:"percentage-point",value:.66,unit:"ratio"}}),result=evaluateOutcomeMetric(spec,actual,"v1");expect(result.percentagePointVariance).toBeCloseTo(-.04);expect(result.relativeVariance).toBeCloseTo(-.057142857)});
 it("does not calculate relative variance against zero",()=>{const spec=expected({expectation:{type:"target",target:{type:"money",value:0,unit:"night",currency:"USD"}}}),result=evaluateOutcomeMetric(spec,measured(10),"v1");expect(result.relativeVariance).toBeUndefined()});
 it("rejects incompatible currencies as unable to evaluate",()=>{const result=evaluateOutcomeMetric(expected(),measured(205,{metric:metric({currency:"EUR"}),value:{type:"money",value:205,unit:"night",currency:"EUR"}}),"v1");expect(result.status).toBe("unable-to-evaluate");expect(result.rationale[0]).toMatch(/currency/i)});
 it("summarizes conflicting required metrics as mixed",()=>{const second=expected({id:"expected-2"}),one=evaluateOutcomeMetric(expected(),measured(210),"v1"),two=evaluateOutcomeMetric(second,measured(150,{id:"measurement-2",expectedOutcomeId:"expected-2"}),"v1");expect(summarizeOutcomeReview([expected(),second],[one,two]).status).toBe("mixed")});
 it("preserves measurement corrections as append-only revisions",()=>{const corrected=reviseMeasuredOutcome(measured(),{...measured(207),id:"measurement-2",createdAt:"2026-10-03T00:00:00Z"});expect(corrected.revision).toBe(2);expect(corrected.supersedesMeasuredOutcomeId).toBe("measurement-1")});
 it("rejects edits to completed reviews",()=>{const review={id:"review-1",seriesId:"review",workspaceId:"workspace-1",learningSubjectId:"subject-1",measurementPlanId:"plan-1-v1",measurementPlanRevision:1,reviewWindowId:"window-1",revision:1,status:"completed"as const,executionContext:{requirement:"action-completed"as const,sourceReferences:[],status:"confirmed"as const,evidence:[]},expectedOutcomeSnapshots:[expected()],measuredOutcomeIds:["measurement-1"],selections:[],metricEvaluations:[],evidence:[],confidence:"high"as const,dataFreshness:"current"as const,evaluationPolicyVersion:"v1",createdAt:"2026-07-01"} satisfies OperationalOutcomeReview;expect(()=>transitionOutcomeReview(review,"in-review","2026-10-01")).toThrow()});
});
