import Link from "next/link";
import { PageHero } from "@/components/marketing/page-hero";

const items = ["Listing conversion and positioning", "Guest experience and amenity gaps", "Pricing and occupancy opportunities", "Operations, turnovers, and maintenance rhythm", "Owner reporting and next-action clarity"];

export default function LeadMagnetPage() {
  return (
    <main>
      <PageHero eyebrow="Free Owner Tool" title="Download the Short-Term Rental Revenue Readiness Checklist." description="A practical owner-facing framework to evaluate whether your property is ready to earn stronger bookings, better reviews, and more consistent performance." />
      <section className="py-20"><div className="container-shell grid gap-10 lg:grid-cols-[1fr_.9fr]"><div className="rounded-[2rem] border border-border bg-card p-8"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-accent">Inside the checklist</p><h2 className="mt-4 font-serif text-4xl">See what is helping or hurting your property before the next guest ever books.</h2><div className="mt-8 grid gap-4">{items.map((item) => <p key={item} className="rounded-2xl bg-muted/60 p-4 font-medium">✓ {item}</p>)}</div></div><form className="rounded-[2rem] border border-border bg-[#171412] p-8 text-primary-foreground"><h2 className="font-serif text-4xl">Get the checklist</h2><p className="mt-4 leading-7 text-primary-foreground/70">Enter your details and use the checklist to audit your STR like a hospitality operator.</p><label className="mt-6 grid gap-2 text-sm font-medium">Name<input className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 outline-none" placeholder="Your name" /></label><label className="mt-5 grid gap-2 text-sm font-medium">Email<input className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 outline-none" placeholder="you@example.com" /></label><label className="mt-5 grid gap-2 text-sm font-medium">Property Market<input className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 outline-none" placeholder="Mesa, Phoenix, Scottsdale..." /></label><button className="mt-6 w-full rounded-full bg-primary-foreground px-6 py-3 text-sm font-semibold text-primary">Download Checklist</button><p className="mt-4 text-xs text-primary-foreground/50">This is currently a front-end lead capture page. CRM/email automation will be wired in a later sprint.</p></form></div></section>
      <section className="bg-muted/45 py-16"><div className="container-shell text-center"><h2 className="font-serif text-4xl">Prefer a guided review?</h2><p className="mx-auto mt-4 max-w-2xl leading-8 text-muted-foreground">Use the checklist first, then schedule a consultation to prioritize improvements with Luxe Haven.</p><Link href="/contact" className="mt-7 inline-flex rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">Schedule a Consultation</Link></div></section>
    </main>
  );
}
