alter table public.ps001d_verification_claims drop constraint ps001d_verification_claims_status_check;
alter table public.ps001d_verification_claims add constraint ps001d_verification_claims_status_check check(status in('acquired','consumed','verifying','cleaning','completed','failed','expired'));

create table public.ps001d_verification_scenario_results(
 id uuid primary key default gen_random_uuid(),claim_id uuid not null references public.ps001d_verification_claims(id),correlation_id text not null,
 scenario text not null check(scenario in('admin','owner','operator','wrong_tenant','anonymous','navigation','deep_links','refresh','history','replay_idempotency','responsive','accessibility','tenant_isolation')),
 status text not null check(status in('passed','failed')),expected_result text not null,observed_result text not null,evidence_reference text not null,
 recorded_at timestamptz not null default now(),unique(claim_id,scenario),foreign key(claim_id,correlation_id) references public.ps001d_verification_claims(id,correlation_id),
 check(length(expected_result) between 1 and 500 and length(observed_result) between 1 and 500 and evidence_reference ~ '^[A-Za-z0-9._:/-]{1,300}$')
);

create or replace function public.ps001d_guard_claim_change() returns trigger language plpgsql set search_path='' as $$begin
 if row(new.milestone,new.candidate_commit,new.deployment_id,new.tenant_id,new.correlation_id,new.operator_id,new.acquired_at,new.expires_at) is distinct from row(old.milestone,old.candidate_commit,old.deployment_id,old.tenant_id,old.correlation_id,old.operator_id,old.acquired_at,old.expires_at) then raise exception 'PS001D_CLAIM_BINDING_IMMUTABLE';end if;
 if old.status in('completed','failed','expired') then raise exception 'PS001D_CLAIM_TERMINAL';end if;
 if (old.status='acquired' and new.status not in('consumed','failed','expired')) or (old.status='consumed' and new.status not in('verifying','failed')) or (old.status='verifying' and new.status not in('cleaning','failed')) or (old.status='cleaning' and new.status not in('completed','failed')) then raise exception 'PS001D_CLAIM_TRANSITION_INVALID';end if;
 if old.mutation_started_at is not null and new.mutation_started_at is distinct from old.mutation_started_at then raise exception 'PS001D_CLAIM_CONSUMPTION_IMMUTABLE';end if;return new;end$$;

create or replace function public.begin_ps001d_verification(p_actor_id uuid,p_claim_id uuid) returns public.ps001d_verification_claims language plpgsql security definer set search_path='' as $$declare c public.ps001d_verification_claims;begin perform public.ps001d_assert_service_admin(p_actor_id);update public.ps001d_verification_claims set status='verifying' where id=p_claim_id and status='consumed' returning*into c;if not found then raise exception 'PS001D_VERIFICATION_NOT_READY';end if;return c;end$$;
create or replace function public.record_ps001d_verification_scenario(p_actor_id uuid,p_claim_id uuid,p_scenario text,p_status text,p_expected text,p_observed text,p_evidence text) returns public.ps001d_verification_scenario_results language plpgsql security definer set search_path='' as $$declare r public.ps001d_verification_scenario_results;begin perform public.ps001d_assert_service_admin(p_actor_id);if not exists(select 1 from public.ps001d_verification_claims where id=p_claim_id and status='verifying')then raise exception 'PS001D_SCENARIO_RECORDING_NOT_ALLOWED';end if;insert into public.ps001d_verification_scenario_results(claim_id,correlation_id,scenario,status,expected_result,observed_result,evidence_reference)select id,correlation_id,p_scenario,p_status,p_expected,p_observed,p_evidence from public.ps001d_verification_claims where id=p_claim_id returning*into r;return r;exception when unique_violation then raise exception 'PS001D_SCENARIO_ALREADY_RECORDED';end$$;
create or replace function public.begin_ps001d_cleaning(p_actor_id uuid,p_claim_id uuid) returns public.ps001d_verification_claims language plpgsql security definer set search_path='' as $$declare c public.ps001d_verification_claims;missing text[];begin perform public.ps001d_assert_service_admin(p_actor_id);select array_agg(s)into missing from unnest(array['admin','owner','operator','wrong_tenant','anonymous','navigation','deep_links','refresh','history','replay_idempotency','responsive','accessibility','tenant_isolation'])s where not exists(select 1 from public.ps001d_verification_scenario_results r where r.claim_id=p_claim_id and r.scenario=s and r.status='passed');if missing is not null then raise exception 'PS001D_MATRIX_INCOMPLETE:%',array_to_string(missing,',');end if;update public.ps001d_verification_claims set status='cleaning' where id=p_claim_id and status='verifying' returning*into c;if not found then raise exception 'PS001D_CLEANING_NOT_READY';end if;return c;end$$;

do $$declare f record;d text;begin for f in select p.oid from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('cleanup_ps001d_verification_fixtures','cleanup_ps001d_verification_operator_property','record_ps001d_cleanup_result') loop d:=pg_catalog.pg_get_functiondef(f.oid);d:=replace(d,'v_claim.status<>''consumed''','v_claim.status<>''cleaning''');d:=replace(d,'v_claim.status<>''consumed'' then','v_claim.status<>''cleaning'' then');execute d;end loop;end$$;

create or replace function public.complete_ps001d_verification_claim(p_actor_id uuid,p_claim_id uuid,p_candidate_commit text,p_deployment_id text,p_tenant_id uuid,p_correlation_id text) returns public.ps001d_verification_claims language plpgsql security definer set search_path='' as $$declare c public.ps001d_verification_claims;begin perform public.ps001d_assert_service_admin(p_actor_id);select*into c from public.ps001d_verification_claims where id=p_claim_id for update;if not found or c.candidate_commit<>p_candidate_commit or c.deployment_id<>p_deployment_id or c.tenant_id<>p_tenant_id or c.correlation_id<>p_correlation_id then raise exception 'PS001D_CLAIM_BINDING_MISMATCH';end if;if c.status<>'cleaning' or exists(select 1 from public.ps001d_verification_resource_ledger where claim_id=p_claim_id and status not in('cleaned','retained')) or (select count(*) from public.ps001d_verification_scenario_results where claim_id=p_claim_id and status='passed')<>13 then raise exception 'PS001D_RECONCILIATION_INCOMPLETE';end if;update public.ps001d_verification_identity_authorizations set revoked_at=coalesce(revoked_at,now())where correlation_id=p_correlation_id;update public.ps001d_verification_claims set status='completed',completed_at=now()where id=p_claim_id returning*into c;return c;end$$;
alter table public.ps001d_verification_scenario_results enable row level security;revoke all on public.ps001d_verification_scenario_results from anon,authenticated;grant select on public.ps001d_verification_scenario_results to service_role;
