-- CA-001D actor-authorized journey persistence. Product artifacts remain in owning domains.
alter table public.first_value_action_instances add column processing_lease_id uuid,add column lease_expires_at timestamptz,add column stable_failure_code text;
create function public.create_first_value_journey(p_actor_id uuid,p_journey jsonb,p_idempotency_hash text,p_correlation_id text)
returns public.first_value_journeys language plpgsql security definer set search_path='' as $$
declare v_journey public.first_value_journeys;v_allowed boolean;
begin
 select exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))or exists(select 1 from public.customer_account_memberships where profile_id=p_actor_id and tenant_id=(p_journey->>'tenantId')::uuid and customer_account_id=(p_journey->>'customerAccountId')::uuid and status='active')into v_allowed;
 if not v_allowed then raise exception'FIRST_VALUE_NOT_AUTHORIZED';end if;
 select*into v_journey from public.first_value_journeys where source_reference_id=p_journey->>'sourceReferenceId'and product_family=p_journey->>'productFamily';if found then return v_journey;end if;
 if not exists(select 1 from public.commercial_entitlements where id=(p_journey->>'entitlementSourceId')::uuid and tenant_id=(p_journey->>'tenantId')::uuid and customer_account_id=(p_journey->>'customerAccountId')::uuid and status='active'and effective_from<=now()and(effective_until is null or effective_until>now()))then raise exception'ENTITLEMENT_NOT_ACTIVE';end if;
 insert into public.first_value_journeys(id,tenant_id,customer_account_id,onboarding_case_id,entitlement_source_id,product_family,source_type,source_reference_id,product_context_type,product_context_id,policy_code,policy_version,status,idempotency_key_hash,created_at,updated_at,revision)
 values((p_journey->>'id')::uuid,(p_journey->>'tenantId')::uuid,(p_journey->>'customerAccountId')::uuid,nullif(p_journey->>'onboardingCaseId','')::uuid,(p_journey->>'entitlementSourceId')::uuid,p_journey->>'productFamily',p_journey->>'sourceType',p_journey->>'sourceReferenceId',p_journey->>'productContextType',(p_journey->>'productContextId')::uuid,p_journey->>'policyCode',(p_journey->>'policyVersion')::integer,p_journey->>'status',p_idempotency_hash,(p_journey->>'createdAt')::timestamptz,(p_journey->>'updatedAt')::timestamptz,(p_journey->>'revision')::integer)returning*into v_journey;
 insert into public.first_value_audit_events(tenant_id,journey_id,event_type,actor_id,actor_type,correlation_id,idempotency_key_hash)values(v_journey.tenant_id,v_journey.id,'first_value_journey_created',p_actor_id,case when exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))then'internal'else'customer'end,p_correlation_id,p_idempotency_hash);
 return v_journey;
end$$;

create function public.record_first_value_evidence(p_actor_id uuid,p_journey_id uuid,p_evidence jsonb,p_correlation_id text)
returns public.first_value_evidence language plpgsql security definer set search_path='' as $$
declare v_journey public.first_value_journeys;v_evidence public.first_value_evidence;
begin
 select*into v_journey from public.first_value_journeys where id=p_journey_id;if not found then raise exception'FIRST_VALUE_NOT_FOUND';end if;
 if not exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))and not exists(select 1 from public.customer_account_memberships where profile_id=p_actor_id and tenant_id=v_journey.tenant_id and customer_account_id=v_journey.customer_account_id and status='active')then raise exception'FIRST_VALUE_NOT_AUTHORIZED';end if;
 insert into public.first_value_evidence(id,tenant_id,journey_id,evidence_code,evidence_version,source_type,source_reference_type,source_reference_id,status,evaluated_at,expires_at,created_at)
 values((p_evidence->>'id')::uuid,v_journey.tenant_id,v_journey.id,p_evidence->>'evidenceCode',(p_evidence->>'evidenceVersion')::integer,p_evidence->>'sourceType',p_evidence->>'sourceReferenceType',p_evidence->>'sourceReferenceId',p_evidence->>'status',(p_evidence->>'evaluatedAt')::timestamptz,nullif(p_evidence->>'expiresAt','')::timestamptz,(p_evidence->>'createdAt')::timestamptz)
 on conflict(journey_id,evidence_code,source_reference_type,source_reference_id)do update set status=excluded.status,evaluated_at=excluded.evaluated_at,expires_at=excluded.expires_at returning*into v_evidence;
 insert into public.first_value_audit_events(tenant_id,journey_id,event_type,actor_id,actor_type,correlation_id)values(v_journey.tenant_id,v_journey.id,'first_value_evidence_recorded',p_actor_id,'system',p_correlation_id);
 return v_evidence;
end$$;

create function public.complete_first_value_journey(p_actor_id uuid,p_journey_id uuid,p_expected_revision integer,p_outcome_code text,p_destination text,p_idempotency_hash text,p_correlation_id text)
returns public.first_value_journeys language plpgsql security definer set search_path='' as $$
declare v_journey public.first_value_journeys;
begin
 select*into v_journey from public.first_value_journeys where id=p_journey_id for update;if not found then raise exception'FIRST_VALUE_NOT_FOUND';end if;if v_journey.status='completed'then return v_journey;end if;if v_journey.revision<>p_expected_revision then raise exception'STALE_JOURNEY_REVISION';end if;
 if not exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))and not exists(select 1 from public.customer_account_memberships where profile_id=p_actor_id and tenant_id=v_journey.tenant_id and customer_account_id=v_journey.customer_account_id and status='active')then raise exception'FIRST_VALUE_NOT_AUTHORIZED';end if;
 if not exists(select 1 from public.commercial_entitlements where id=v_journey.entitlement_source_id and status='active'and effective_from<=now()and(effective_until is null or effective_until>now()))then raise exception'ENTITLEMENT_NOT_ACTIVE';end if;
 if p_destination not in('/dashboard/hpm','/dashboard/guidebooks','/dashboard/furnishing/projects','/dashboard/investments')then raise exception'DESTINATION_UNAUTHORIZED';end if;
 update public.first_value_journeys set status='completed',outcome_code=p_outcome_code,completed_at=now(),updated_at=now(),revision=revision+1 where id=p_journey_id returning*into v_journey;
 insert into public.first_value_audit_events(tenant_id,journey_id,event_type,actor_id,actor_type,correlation_id,idempotency_key_hash)values(v_journey.tenant_id,v_journey.id,'first_value_outcome_achieved',p_actor_id,'customer',p_correlation_id,p_idempotency_hash);
 return v_journey;
end$$;
create function public.claim_first_value_processing(p_actor_id uuid,p_journey_id uuid,p_action_code text,p_lease_id uuid,p_lease_seconds integer,p_correlation_id text)
returns public.first_value_action_instances language plpgsql security definer set search_path=''as $$declare v_journey public.first_value_journeys;v_action public.first_value_action_instances;begin select*into v_journey from public.first_value_journeys where id=p_journey_id;if not found then raise exception'FIRST_VALUE_NOT_FOUND';end if;if not exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))and not exists(select 1 from public.customer_account_memberships where profile_id=p_actor_id and tenant_id=v_journey.tenant_id and customer_account_id=v_journey.customer_account_id and status='active')then raise exception'FIRST_VALUE_NOT_AUTHORIZED';end if;insert into public.first_value_action_instances(tenant_id,journey_id,action_code,action_version,status,responsibility,attempt_count,processing_lease_id,lease_expires_at,revision)select v_journey.tenant_id,v_journey.id,d.code,d.version,'in_progress',d.responsibility,1,p_lease_id,now()+make_interval(secs=>least(greatest(p_lease_seconds,30),900)),1 from public.first_value_action_definitions d where d.code=p_action_code and d.status='active'on conflict(journey_id,action_code,action_version)do update set status='in_progress',attempt_count=public.first_value_action_instances.attempt_count+1,processing_lease_id=p_lease_id,lease_expires_at=now()+make_interval(secs=>least(greatest(p_lease_seconds,30),900)),stable_failure_code=null,revision=public.first_value_action_instances.revision+1 where public.first_value_action_instances.status in('available','failed')or public.first_value_action_instances.lease_expires_at<now()returning*into v_action;if not found then raise exception'FIRST_VALUE_PROCESSING_BUSY';end if;update public.first_value_journeys set status='system_processing',updated_at=now(),revision=revision+1 where id=v_journey.id and status<>'completed';insert into public.first_value_audit_events(tenant_id,journey_id,event_type,actor_id,actor_type,correlation_id)values(v_journey.tenant_id,v_journey.id,'first_value_processing_started',p_actor_id,'system',p_correlation_id);return v_action;end$$;
create function public.finish_first_value_processing(p_actor_id uuid,p_journey_id uuid,p_action_code text,p_lease_id uuid,p_status text,p_failure_code text,p_correlation_id text)
returns public.first_value_action_instances language plpgsql security definer set search_path=''as $$declare v_action public.first_value_action_instances;begin select a.*into v_action from public.first_value_action_instances a join public.first_value_journeys j on j.id=a.journey_id where a.journey_id=p_journey_id and a.action_code=p_action_code and a.processing_lease_id=p_lease_id and(exists(select 1 from public.profiles where id=p_actor_id and role in('admin','administrator'))or exists(select 1 from public.customer_account_memberships where profile_id=p_actor_id and tenant_id=j.tenant_id and customer_account_id=j.customer_account_id and status='active'))for update;if not found then raise exception'FIRST_VALUE_LEASE_INVALID';end if;update public.first_value_action_instances set status=case when p_status='completed'then'completed'else'failed'end,completed_at=case when p_status='completed'then now()else completed_at end,stable_failure_code=p_failure_code,processing_lease_id=null,lease_expires_at=null,revision=revision+1 where id=v_action.id returning*into v_action;update public.first_value_journeys set status=case when p_status='completed'then'ready_for_evaluation'else'blocked'end,blocker_code=case when p_status='completed'then null else coalesce(p_failure_code,'ARTIFACT_CREATION_FAILED')end,updated_at=now(),revision=revision+1 where id=p_journey_id and status<>'completed';insert into public.first_value_audit_events(tenant_id,journey_id,event_type,actor_id,actor_type,reason_code,correlation_id)values(v_action.tenant_id,p_journey_id,case when p_status='completed'then'first_value_processing_completed'else'first_value_processing_failed'end,p_actor_id,'system',p_failure_code,p_correlation_id);return v_action;end$$;
revoke all on function public.create_first_value_journey(uuid,jsonb,text,text),public.record_first_value_evidence(uuid,uuid,jsonb,text),public.complete_first_value_journey(uuid,uuid,integer,text,text,text,text),public.claim_first_value_processing(uuid,uuid,text,uuid,integer,text),public.finish_first_value_processing(uuid,uuid,text,uuid,text,text,text)from public,anon,authenticated;
