-- CA-001B protected Stripe projections. Secrets and raw provider payloads are never persisted here.
create table public.billing_price_mappings(id uuid primary key default gen_random_uuid(),offer_code text not null,offer_version integer not null,billing_model text not null check(billing_model in('one_time','recurring')),currency text not null check(currency~'^[A-Z]{3}$'),amount_minor bigint not null check(amount_minor>=0),billing_interval text check(billing_interval in('month','year')),interval_count integer check(interval_count>0),stripe_product_reference text not null,stripe_price_reference text not null,account_mode text not null check(account_mode in('test','live')),status text not null check(status in('active','inactive','retired')),effective_from timestamptz not null,effective_until timestamptz,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),revision integer not null default 1,foreign key(offer_code,offer_version)references public.commercial_offer_versions(code,version),unique(offer_code,offer_version,billing_interval,currency,account_mode,status),check(effective_until is null or effective_until>effective_from));
create table public.billing_customer_associations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,customer_account_id uuid not null,account_mode text not null check(account_mode in('test','live')),stripe_customer_reference text not null,status text not null check(status in('active','ambiguous','retired')),created_at timestamptz not null default now(),revision integer not null default 1,foreign key(customer_account_id,tenant_id)references public.customer_accounts(id,tenant_id),unique(customer_account_id,account_mode,stripe_customer_reference));
create unique index billing_one_active_customer_uidx on public.billing_customer_associations(customer_account_id,account_mode)where status='active';
create table public.billing_checkout_attempts(id uuid primary key,tenant_id uuid not null,customer_account_id uuid not null,offer_code text not null,offer_version integer not null,billing_price_mapping_id uuid not null references public.billing_price_mappings(id),mode text not null check(mode in('payment','subscription')),status text not null check(status in('created','session_created','completed','expired','cancelled','failed')),stripe_customer_reference text,stripe_checkout_session_reference text,idempotency_key_hash text not null unique,correlation_id text not null,created_at timestamptz not null,expires_at timestamptz not null,completed_at timestamptz,failure_code text,revision integer not null default 1,foreign key(customer_account_id,tenant_id)references public.customer_accounts(id,tenant_id));
create unique index billing_checkout_provider_session_uidx on public.billing_checkout_attempts(stripe_checkout_session_reference)where stripe_checkout_session_reference is not null;
create table public.billing_provider_events(id uuid primary key,provider text not null check(provider='stripe'),provider_event_id text not null,event_type text not null,account_mode text not null check(account_mode in('test','live')),status text not null check(status in('received','processing','processed','ignored','failed','quarantined')),received_at timestamptz not null,processed_at timestamptz,correlation_id text not null,attempt_count integer not null default 0,stable_failure_code text,payload_checksum text not null,revision integer not null default 1,unique(provider_event_id,account_mode));
create table public.commercial_agreements(id uuid primary key,tenant_id uuid not null,customer_account_id uuid not null,checkout_attempt_id uuid unique references public.billing_checkout_attempts(id),offer_code text not null,offer_version integer not null,billing_price_mapping_id uuid not null references public.billing_price_mappings(id),agreement_type text not null check(agreement_type in('subscription','one_time_purchase','service_engagement')),status text not null check(status in('pending','active','past_due','payment_action_required','paused','scheduled_to_cancel','cancelled','expired','refunded','disputed')),provider text not null check(provider='stripe'),provider_customer_reference text not null,provider_agreement_reference text,current_period_start timestamptz,current_period_end timestamptz,cancel_at_period_end boolean,ended_at timestamptz,activated_at timestamptz,created_at timestamptz not null,updated_at timestamptz not null,revision integer not null default 1,foreign key(customer_account_id,tenant_id)references public.customer_accounts(id,tenant_id),foreign key(offer_code,offer_version)references public.commercial_offer_versions(code,version));
create unique index commercial_provider_agreement_uidx on public.commercial_agreements(provider,provider_agreement_reference)where provider_agreement_reference is not null;
create table public.commercial_agreement_history(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,agreement_id uuid not null references public.commercial_agreements(id),provider_event_id text,from_status text,to_status text not null,actor_id uuid references public.profiles(id),reason_code text not null,correlation_id text not null,occurred_at timestamptz not null,revision integer not null,unique(agreement_id,revision));
create table public.commercial_reconciliation_attempts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,agreement_id uuid references public.commercial_agreements(id),initiated_by uuid not null references public.profiles(id),reason text not null,correlation_id text not null,status text not null check(status in('started','repaired','unchanged','review_required','failed')),stable_failure_code text,created_at timestamptz not null default now(),completed_at timestamptz);
create index billing_provider_events_retry_idx on public.billing_provider_events(status,received_at)where status in('received','failed');create index commercial_agreements_reconcile_idx on public.commercial_agreements(status,updated_at);create index billing_checkout_expiry_idx on public.billing_checkout_attempts(status,expires_at);
alter table public.billing_price_mappings enable row level security;alter table public.billing_customer_associations enable row level security;alter table public.billing_checkout_attempts enable row level security;alter table public.billing_provider_events enable row level security;alter table public.commercial_agreements enable row level security;alter table public.commercial_agreement_history enable row level security;alter table public.commercial_reconciliation_attempts enable row level security;
create policy "members read safe checkout attempts" on public.billing_checkout_attempts for select to authenticated using(exists(select 1 from public.customer_account_memberships m where m.customer_account_id=billing_checkout_attempts.customer_account_id and m.tenant_id=billing_checkout_attempts.tenant_id and m.profile_id=auth.uid() and m.status='active'));
create policy "members read agreements" on public.commercial_agreements for select to authenticated using(exists(select 1 from public.customer_account_memberships m where m.customer_account_id=commercial_agreements.customer_account_id and m.tenant_id=commercial_agreements.tenant_id and m.profile_id=auth.uid() and m.status='active'));
create policy "admins read billing mappings" on public.billing_price_mappings for select to authenticated using(public.is_admin());create policy "admins read customer associations" on public.billing_customer_associations for select to authenticated using(public.is_admin());create policy "admins read provider ledger" on public.billing_provider_events for select to authenticated using(public.is_admin());create policy "admins read agreement history" on public.commercial_agreement_history for select to authenticated using(public.is_admin());create policy "admins read reconciliation" on public.commercial_reconciliation_attempts for select to authenticated using(public.is_admin());
revoke all on public.billing_price_mappings,public.billing_customer_associations,public.billing_checkout_attempts,public.billing_provider_events,public.commercial_agreements,public.commercial_agreement_history,public.commercial_reconciliation_attempts from anon;
revoke insert,update,delete on public.billing_price_mappings,public.billing_customer_associations,public.billing_checkout_attempts,public.billing_provider_events,public.commercial_agreements,public.commercial_agreement_history,public.commercial_reconciliation_attempts from authenticated;
grant select on public.billing_checkout_attempts,public.commercial_agreements to authenticated;
