-- FS-005: project workspace, generated plan state, selections, validation, and approval.
begin;
alter table public.furnishing_projects add column if not exists furnishing_package_version_id uuid references public.furnishing_package_versions(id), add column if not exists design_profile_version_id uuid references public.furnishing_design_profile_versions(id), add column if not exists budget_priority text not null default 'balanced' check(budget_priority in('stay_under_budget','balanced','prioritize_design')), add column if not exists last_active_room_id uuid references public.furnishing_rooms(id), add column if not exists plan_status text not null default 'not_generated' check(plan_status in('not_generated','draft','awaiting_approval','approved'));
alter table public.furnishing_rooms add column if not exists room_package_version_id uuid references public.furnishing_room_package_versions(id), add column if not exists notes text;
alter table public.furnishing_plans add column if not exists revision bigint not null default 1 check(revision>0), add column if not exists package_snapshot jsonb not null default '{}', add column if not exists design_snapshot jsonb not null default '{}', add column if not exists validation_snapshot jsonb not null default '{}', add column if not exists approval_snapshot jsonb, add column if not exists updated_at timestamptz not null default now();
alter table public.furnishing_product_selections drop constraint furnishing_product_selections_selection_status_check;
alter table public.furnishing_product_selections add constraint furnishing_product_selections_selection_status_check check(selection_status in('recommended','selected','approved','rejected','replaced','existing_inventory','skipped_optional','missing'));
alter table public.furnishing_product_selections alter column product_id drop not null;
alter table public.furnishing_product_selections add column if not exists requirement_id uuid references public.furnishing_room_requirements(id), add column if not exists requirement_name text, add column if not exists priority text not null default 'required' check(priority in('required','recommended','optional')), add column if not exists existing_quantity numeric(12,4) not null default 0 check(existing_quantity>=0), add column if not exists purchase_quantity numeric(12,4) not null default 0 check(purchase_quantity>=0), add column if not exists quantity_override numeric(12,4) check(quantity_override is null or quantity_override>=0), add column if not exists quantity_override_reason text, add column if not exists style_compatibility text check(style_compatibility is null or style_compatibility in('preferred','compatible','neutral','avoid')), add column if not exists sort_order integer not null default 0 check(sort_order>=0), add column if not exists revision bigint not null default 1 check(revision>0);
create table public.furnishing_project_notes(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.furnishing_projects(id) on delete cascade,room_id uuid references public.furnishing_rooms(id),selection_id uuid references public.furnishing_product_selections(id),body text not null check(length(trim(body))>0),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.furnishing_plan_validation_runs(id uuid primary key default gen_random_uuid(),furnishing_plan_id uuid not null references public.furnishing_plans(id) on delete cascade,revision bigint not null,errors jsonb not null default '[]',warnings jsonb not null default '[]',estimated_total_minor bigint not null default 0,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.furnishing_existing_inventory(id uuid primary key default gen_random_uuid(),selection_id uuid not null unique references public.furnishing_product_selections(id) on delete cascade,quantity numeric(12,4) not null check(quantity>0),condition text not null check(condition in('excellent','good','fair','poor','unknown')),media_asset_id uuid,notes text,recorded_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.furnishing_project_notes enable row level security;alter table public.furnishing_plan_validation_runs enable row level security;alter table public.furnishing_existing_inventory enable row level security;
create policy "Members read project notes" on public.furnishing_project_notes for select to authenticated using(exists(select 1 from public.furnishing_projects p where p.id=project_id and (public.active_workspace_role(p.workspace_id)is not null or public.is_admin())));
create policy "Members read plan validation" on public.furnishing_plan_validation_runs for select to authenticated using(exists(select 1 from public.furnishing_plans p join public.furnishing_projects project on project.id=p.project_id where p.id=furnishing_plan_id and (public.active_workspace_role(project.workspace_id)is not null or public.is_admin())));
create policy "Members read existing inventory" on public.furnishing_existing_inventory for select to authenticated using(exists(select 1 from public.furnishing_product_selections s join public.furnishing_plans p on p.id=s.furnishing_plan_id join public.furnishing_projects project on project.id=p.project_id where s.id=selection_id and (public.active_workspace_role(project.workspace_id)is not null or public.is_admin())));
create index furnishing_selection_plan_room_idx on public.furnishing_product_selections(furnishing_plan_id,room_id,sort_order) include(selection_status,estimated_total_minor);
commit;
