-- LHC-GS-004 Canonical Media Library
alter table public.guidebook_library_artifacts add column if not exists media_scope text;
alter table public.guidebook_library_artifacts add column if not exists media_access_policy text default 'private';
alter table public.guidebook_library_artifacts add column if not exists replacement_media_id uuid references public.guidebook_library_artifacts(id) on delete restrict;
alter table public.guidebook_library_artifacts add column if not exists media_archived_at timestamptz;
alter table public.guidebook_library_artifacts add constraint media_scope_check check(artifact_type<>'media'or media_scope in('platform','workspace','property'));
alter table public.guidebook_library_artifacts add constraint media_access_check check(artifact_type<>'media'or media_access_policy in('private','guest','public','signed','internal'));
alter table public.guidebook_library_media_files add column if not exists caption text;alter table public.guidebook_library_media_files add column if not exists photographer text;alter table public.guidebook_library_media_files add column if not exists copyright text;alter table public.guidebook_library_media_files add column if not exists license text;alter table public.guidebook_library_media_files add column if not exists dominant_color text;alter table public.guidebook_library_media_files add column if not exists orientation text;alter table public.guidebook_library_media_files add column if not exists exif jsonb not null default '{}';alter table public.guidebook_library_media_files add column if not exists safe_crop jsonb;alter table public.guidebook_library_media_files add column if not exists decorative boolean not null default false;
create table public.guidebook_media_derivatives(id uuid primary key default gen_random_uuid(),media_version_id uuid not null references public.guidebook_library_versions(id) on delete restrict,kind text not null check(kind in('thumbnail','small','medium','large','retina','pdf','hero','qr')),storage_path text not null unique,mime_type text not null,width integer,height integer,byte_size bigint not null check(byte_size>0),checksum_sha256 text not null,status text not null default'queued'check(status in('queued','processing','ready','failed')),created_at timestamptz not null default now(),unique(media_version_id,kind));
create table public.guidebook_media_usage(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.owners(id),asset_id uuid not null references public.guidebook_library_artifacts(id) on delete restrict,media_version_id uuid not null references public.guidebook_library_versions(id) on delete restrict,consumer_type text not null check(consumer_type in('guidebook','template','component','content_record','publication')),consumer_id uuid not null,guidebook_version_id uuid references public.guidebook_canonical_versions(id) on delete restrict,publication_status text not null check(publication_status in('draft','published','superseded')),channels text[] not null default'{}',created_at timestamptz not null default now(),unique(media_version_id,consumer_type,consumer_id));
create table public.guidebook_media_collection_items(collection_id uuid not null references public.guidebook_media_collections(id) on delete cascade,asset_id uuid not null references public.guidebook_library_artifacts(id) on delete restrict,sort_order integer not null default 0,added_by uuid references public.profiles(id),added_at timestamptz not null default now(),primary key(collection_id,asset_id));
create table public.guidebook_media_processing_jobs(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.owners(id),media_version_id uuid not null references public.guidebook_library_versions(id) on delete cascade,idempotency_key text not null,status text not null default'queued'check(status in('queued','processing','completed','failed')),steps jsonb not null default'{}',error_code text,created_at timestamptz not null default now(),completed_at timestamptz,unique(workspace_id,idempotency_key));
create table public.guidebook_media_archive_events(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.owners(id),asset_id uuid not null references public.guidebook_library_artifacts(id) on delete restrict,replacement_asset_id uuid references public.guidebook_library_artifacts(id) on delete restrict,reason text not null check(length(trim(reason))>0),block_new_use boolean not null default true,archived_by uuid not null references public.profiles(id),archived_at timestamptz not null default now());
create or replace function public.protect_published_media_version()returns trigger language plpgsql as $$declare protected boolean;begin select exists(select 1 from public.guidebook_library_artifacts a where a.id=old.artifact_id and a.artifact_type='media')and(old.status in('published','approved')or exists(select 1 from public.guidebook_media_usage u where u.media_version_id=old.id and u.publication_status='published'))into protected;if protected then raise exception'media_version_immutable';end if;return case when tg_op='DELETE'then old else new end;end$$;
create trigger protect_published_media_version before update or delete on public.guidebook_library_versions for each row execute function public.protect_published_media_version();
alter table public.guidebook_media_derivatives enable row level security;alter table public.guidebook_media_usage enable row level security;alter table public.guidebook_media_collection_items enable row level security;alter table public.guidebook_media_processing_jobs enable row level security;alter table public.guidebook_media_archive_events enable row level security;
create policy"Admins manage derivatives"on public.guidebook_media_derivatives for all to authenticated using(public.is_admin())with check(public.is_admin());create policy"Workspace media usage"on public.guidebook_media_usage for select to authenticated using(workspace_id=auth.uid()or public.is_admin());create policy"Admins manage collection items"on public.guidebook_media_collection_items for all to authenticated using(public.is_admin())with check(public.is_admin());create policy"Workspace processing jobs"on public.guidebook_media_processing_jobs for select to authenticated using(workspace_id=auth.uid()or public.is_admin());create policy"Workspace archive events"on public.guidebook_media_archive_events for select to authenticated using(workspace_id=auth.uid()or public.is_admin());
revoke all on public.guidebook_media_derivatives,public.guidebook_media_usage,public.guidebook_media_collection_items,public.guidebook_media_processing_jobs,public.guidebook_media_archive_events from anon;
