insert into public.commerce_categories(id,slug,name,description,active)values
('furnishing','furnishing','Furnishing Packages','Reusable hospitality furnishing systems.',true),('guidebooks','guidebooks','Guidebook Services','Guest experience publishing services.',true),
('consulting','consulting','Consulting','Fixed-scope expert engagements.',true),('resources','resources','Digital Resources','Immediate-access playbooks and tools.',true),('subscriptions','subscriptions','Subscriptions','Recurring platform and advisory access.',true)
on conflict(id)do nothing;
insert into public.commerce_eligibility_policies(id,audience,active,configuration)values('offer-catalog-public','public',true,'{}')on conflict(id)do nothing;
insert into public.commerce_products(id,slug,name,short_description,long_description,category_id,product_type,fulfillment_type,status,eligibility_policy_id,entitlement_template_ids,metadata,created_at,updated_at)values
('offer-modern-2br','modern-2br-apartment-package','Modern 2BR Apartment Package','Turn-key furnishing package for two-bedroom apartments.','A reusable room-by-room furnishing package with curated selections, sourcing links, alternatives, procurement checklist, and installation checklist.','furnishing','configured-product','entitlement-grant','active','offer-catalog-public','{}','{"featured":"true"}',now(),now()),
('offer-custom-guidebook','custom-digital-guidebook','Custom Digital Guidebook','A Luxe Haven-delivered guest guidebook project.','A customized, versioned digital guest guidebook created through Guidebook Studio.','guidebooks','professional-service','service-project','active','offer-catalog-public','{}','{}',now(),now()),
('offer-revenue-audit','revenue-performance-audit','Revenue Performance Audit','A fixed-scope review of hospitality revenue performance.','A governed review with findings, opportunities, and a prioritized action record.','consulting','professional-service','manual-fulfillment','active','offer-catalog-public','{}','{}',now(),now()),
('offer-investment-playbook','investment-decision-playbook','Investment Decision Playbook','Immediate-access investment decision resource.','A practical digital playbook for evaluating hospitality investment opportunities.','resources','digital-product','digital-download','active','offer-catalog-public','{}','{}',now(),now()),
('offer-hpm-advisory','hpm-advisory-monthly','HPM Advisory Monthly','Recurring Hospitality Performance Management advisory.','Monthly advisory access with structured performance review and decision support.','subscriptions','subscription','entitlement-grant','active','offer-catalog-public','{}','{}',now(),now())
on conflict(id)do nothing;
insert into public.commerce_prices(id,product_id,version,price_type,amount_minor,currency,billing_interval,status,effective_from,created_at)values
('price-modern-2br-v1','offer-modern-2br',1,'one-time',24900,'USD',null,'active',now(),now()),('price-guidebook-v1','offer-custom-guidebook',1,'one-time',39900,'USD',null,'active',now(),now()),
('price-revenue-audit-v1','offer-revenue-audit',1,'one-time',49900,'USD',null,'active',now(),now()),('price-investment-playbook-v1','offer-investment-playbook',1,'one-time',14900,'USD',null,'active',now(),now()),
('price-hpm-advisory-v1','offer-hpm-advisory',1,'recurring',149500,'USD','month','active',now(),now())on conflict(id)do nothing;
insert into public.commerce_offer_definitions(product_id,offer_type,fulfillment_model,payment_model,specialist_workspace,catalog_status,owner_name,intended_customer,best_fit,included_outcomes,expected_time_to_value,featured)values
('offer-modern-2br','configured_product','customer_configured','one_time','furnishing-studio','published','Luxe Haven Operations','Owners furnishing a two-bedroom hospitality property','Two-bedroom apartments needing a complete repeatable furnishing system','["Room-by-room checklist","Curated selections","Affiliate purchase links","Procurement checklist","Installation checklist"]','Immediately after activation',true),
('offer-custom-guidebook','fixed_scope_service','luxe_haven_delivered','one_time','guidebook-studio','published','Luxe Haven Operations','Operators needing a premium digital guest experience','Properties with complete operational content','["Guidebook project","Content structure","Published guest experience"]','Project created after payment',false),
('offer-revenue-audit','consulting_engagement','collaborative_delivery','one_time','customer-onboarding','published','Luxe Haven Advisory','Hospitality owners seeking performance clarity','Operators with sufficient booking and revenue history','["Performance findings","Opportunity register","Prioritized actions"]','Intake begins after payment',false),
('offer-investment-playbook','digital_product','immediate_access','one_time','downloads','published','Luxe Haven Advisory','Hospitality investors','Investors evaluating acquisition or arbitrage strategies','["Digital playbook","Reusable decision framework"]','Immediate download access',false),
('offer-hpm-advisory','subscription','recurring_service','subscription','customer-onboarding','published','Luxe Haven Advisory','Growing hospitality operators','Operators requiring recurring performance support','["Monthly performance review","Decision support","Action follow-up"]','Onboarding begins immediately',false)
on conflict(product_id)do nothing;
insert into public.commerce_offer_variants(product_id,name,sku,description,price_override_minor,status,sort_order)values
('offer-modern-2br','Studio','FURN-MOD-STUDIO','Studio variant',19900,'published',1),('offer-modern-2br','1 Bedroom','FURN-MOD-1BR','One-bedroom variant',22900,'published',2),('offer-modern-2br','2 Bedroom','FURN-MOD-2BR','Two-bedroom variant',24900,'published',3),('offer-modern-2br','3 Bedroom','FURN-MOD-3BR','Three-bedroom variant',29900,'published',4)
on conflict(sku)do nothing;
insert into public.commerce_offer_deliverables(product_id,name,description,quantity,delivery_method,required,fulfilled_by,expected_timing,sort_order)
select 'offer-modern-2br',x.name,x.description,1,x.method,true,x.owner,x.timing,x.pos from(values
('Room-by-room furnishing checklist','Complete furnishing requirements organized by room.','workspace','Furnishing Studio','Immediate',1),('Curated product selections','Hospitality-appropriate products and alternatives.','workspace','Furnishing Studio','Immediate',2),('Procurement checklist','Order and delivery tracking structure.','workspace','Furnishing Studio','Immediate',3),('Installation checklist','On-site completion and exception workflow.','workspace','Furnishing Studio','Immediate',4))x(name,description,method,owner,timing,pos) where not exists(select 1 from public.commerce_offer_deliverables where product_id='offer-modern-2br');
insert into public.commerce_checkout_flows(product_id,mode,settings)
select id,'self_service','{"guestCheckout":true,"accountRequired":false,"propertyInformationRequired":true,"promoCodes":true,"termsAcceptance":true}'::jsonb from public.commerce_products on conflict(product_id)do nothing;
insert into public.commerce_activation_flows(product_id,name,trigger_type,status)
select id,name||' activation',case when product_type='subscription'then'subscription_created'else'payment_succeeded'end,'active'from public.commerce_products on conflict(product_id)do nothing;
insert into public.commerce_activation_steps(flow_id,step_type,name,position,configuration)
select f.id,x.step_type,x.name,x.position,'{}'::jsonb from public.commerce_activation_flows f cross join(values('create_entitlement','Create entitlement',1),('notify_customer','Send confirmation and next steps',2))x(step_type,name,position)
where not exists(select 1 from public.commerce_activation_steps s where s.flow_id=f.id);
