-- FS-006: approved-plan procurement, budget authorization and reconciliation.
begin;

create table public.furnishing_procurement_baselines(
  id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.owners(id), property_id uuid not null references public.properties(id), project_id uuid not null references public.furnishing_projects(id) on delete cascade,
  source_plan_id uuid not null references public.furnishing_plans(id), source_plan_version integer not null check(source_plan_version>0), source_snapshot jsonb not null, source_hash text not null,
  currency text not null check(currency ~ '^[A-Z]{3}$'), status text not null default 'draft' check(status in('draft','under_review','authorized','active','closing','closed','superseded')),
  version bigint not null default 1 check(version>0), estimated_subtotal_minor bigint not null default 0 check(estimated_subtotal_minor>=0), estimated_tax_minor bigint not null default 0 check(estimated_tax_minor>=0), estimated_shipping_minor bigint not null default 0 check(estimated_shipping_minor>=0), estimated_fees_minor bigint not null default 0 check(estimated_fees_minor>=0), estimated_total_minor bigint not null default 0 check(estimated_total_minor>=0),
  idempotency_key text not null, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), authorized_by uuid references public.profiles(id), authorized_at timestamptz, closed_by uuid references public.profiles(id), closed_at timestamptz,
  unique(source_plan_id), unique(workspace_id,idempotency_key)
);
create table public.furnishing_procurement_lines(
  id uuid primary key default gen_random_uuid(), baseline_id uuid not null references public.furnishing_procurement_baselines(id) on delete cascade, source_plan_line_id uuid not null references public.furnishing_product_selections(id), room_id uuid not null references public.furnishing_rooms(id), product_id uuid references public.furnishing_products(id), selected_offer_id uuid references public.furnishing_product_offers(id), category text not null, description text not null,
  planned_quantity numeric(12,4) not null check(planned_quantity>=0), existing_inventory_quantity numeric(12,4) not null default 0 check(existing_inventory_quantity>=0), procurement_quantity numeric(12,4) generated always as (planned_quantity-existing_inventory_quantity) stored,
  unit_of_measure text not null default 'each', estimated_unit_cost_minor bigint check(estimated_unit_cost_minor is null or estimated_unit_cost_minor>=0), estimated_line_cost_minor bigint check(estimated_line_cost_minor is null or estimated_line_cost_minor>=0), currency text not null check(currency ~ '^[A-Z]{3}$'),
  committed_quantity numeric(12,4) not null default 0 check(committed_quantity>=0), received_quantity numeric(12,4) not null default 0 check(received_quantity>=0), accepted_quantity numeric(12,4) not null default 0 check(accepted_quantity>=0), returned_quantity numeric(12,4) not null default 0 check(returned_quantity>=0), cancelled_quantity numeric(12,4) not null default 0 check(cancelled_quantity>=0),
  status text not null default 'planned' check(status in('planned','ready','authorized','ordered','partially_fulfilled','fulfilled','reconciled','closed','blocked','substitution_required','cancelled','returned','partially_returned','removed_by_revision')), blocking_reason text, source_snapshot jsonb not null, revision bigint not null default 1 check(revision>0),
  check(existing_inventory_quantity<=planned_quantity), check(accepted_quantity<=received_quantity), unique(baseline_id,source_plan_line_id)
);
create table public.furnishing_project_procurement_budgets(
  id uuid primary key default gen_random_uuid(), baseline_id uuid not null references public.furnishing_procurement_baselines(id), workspace_id uuid not null references public.owners(id), property_id uuid not null references public.properties(id), project_id uuid not null references public.furnishing_projects(id), currency text not null check(currency ~ '^[A-Z]{3}$'),
  status text not null default 'draft' check(status in('draft','submitted','approved','active','closed','rejected','superseded')), base_amount_minor bigint not null check(base_amount_minor>=0), contingency_minor bigint not null default 0 check(contingency_minor>=0), pending_exposure_minor bigint not null default 0 check(pending_exposure_minor>=0), committed_minor bigint not null default 0 check(committed_minor>=0), gross_actual_minor bigint not null default 0 check(gross_actual_minor>=0), refunded_minor bigint not null default 0 check(refunded_minor>=0), credited_minor bigint not null default 0 check(credited_minor>=0), forecast_final_minor bigint not null default 0 check(forecast_final_minor>=0),
  version bigint not null default 1, submitted_by uuid references public.profiles(id), submitted_at timestamptz, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), approved_by uuid references public.profiles(id), approved_at timestamptz,
  check(approved_by is null or approved_by is distinct from submitted_by), unique(baseline_id,version)
);
create table public.furnishing_budget_allocations(
  id uuid primary key default gen_random_uuid(), budget_id uuid not null references public.furnishing_project_procurement_budgets(id) on delete cascade, allocation_type text not null check(allocation_type in('project','room','category','room_category','contingency','installation','delivery','tax_fees')), room_id uuid references public.furnishing_rooms(id), category text, amount_minor bigint not null check(amount_minor>=0), currency text not null check(currency ~ '^[A-Z]{3}$'), created_at timestamptz not null default now(),
  check((allocation_type in('room','room_category'))=(room_id is not null)), check((allocation_type in('category','room_category'))=(category is not null))
);
create table public.furnishing_budget_adjustments(
  id uuid primary key default gen_random_uuid(), budget_id uuid not null references public.furnishing_project_procurement_budgets(id), amount_minor bigint not null, currency text not null check(currency ~ '^[A-Z]{3}$'), reason text not null, status text not null default 'requested' check(status in('requested','approved','rejected')), requested_by uuid not null references public.profiles(id), requested_at timestamptz not null default now(), decided_by uuid references public.profiles(id), decided_at timestamptz, check(decided_by is null or decided_by is distinct from requested_by)
);
create table public.furnishing_purchase_batches(
  id uuid primary key default gen_random_uuid(), baseline_id uuid not null references public.furnishing_procurement_baselines(id), budget_id uuid not null references public.furnishing_project_procurement_budgets(id), retailer_id uuid not null references public.furnishing_retailers(id), delivery_destination jsonb not null, status text not null default 'draft' check(status in('draft','validated','submitted','authorized','ordered','completed','returned_for_revision','rejected','expired','cancelled','superseded')),
  subtotal_minor bigint not null default 0, discount_minor bigint not null default 0, tax_minor bigint not null default 0, shipping_minor bigint not null default 0, fees_minor bigint not null default 0, total_minor bigint not null default 0, currency text not null check(currency ~ '^[A-Z]{3}$'), readiness_snapshot jsonb not null default '{}', authorization_snapshot jsonb, version bigint not null default 1, idempotency_key text not null, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), submitted_by uuid references public.profiles(id), authorized_by uuid references public.profiles(id), authorized_at timestamptz,
  check(total_minor>=0 and subtotal_minor>=0 and discount_minor>=0 and tax_minor>=0 and shipping_minor>=0 and fees_minor>=0), check(authorized_by is null or authorized_by is distinct from submitted_by), unique(baseline_id,idempotency_key)
);
create table public.furnishing_purchase_batch_lines(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.furnishing_purchase_batches(id) on delete cascade,line_id uuid not null references public.furnishing_procurement_lines(id),quantity numeric(12,4) not null check(quantity>0),confirmed_unit_price_minor bigint not null check(confirmed_unit_price_minor>=0),offer_confirmation jsonb not null,unique(batch_id,line_id));

-- Extend the canonical FS-001 order rather than creating a parallel order aggregate.
alter table public.furnishing_procurement_orders add column if not exists baseline_id uuid references public.furnishing_procurement_baselines(id), add column if not exists batch_id uuid references public.furnishing_purchase_batches(id), add column if not exists workspace_id uuid references public.owners(id), add column if not exists order_type text not null default 'external' check(order_type in('external','purchase_order')), add column if not exists internal_order_number text, add column if not exists authorized_total_minor bigint check(authorized_total_minor is null or authorized_total_minor>=0), add column if not exists actual_total_minor bigint check(actual_total_minor is null or actual_total_minor>=0), add column if not exists terms_snapshot jsonb not null default '{}', add column if not exists evidence jsonb not null default '{}', add column if not exists version bigint not null default 1;
create unique index furnishing_order_number_unique on public.furnishing_procurement_orders(internal_order_number) where internal_order_number is not null;
create unique index furnishing_external_order_unique on public.furnishing_procurement_orders(workspace_id,retailer_id,external_order_id) where external_order_id is not null;
create table public.furnishing_procurement_order_lines(
 id uuid primary key default gen_random_uuid(), order_id uuid not null references public.furnishing_procurement_orders(id) on delete cascade, procurement_line_id uuid not null references public.furnishing_procurement_lines(id), snapshot jsonb not null, ordered_quantity numeric(12,4) not null check(ordered_quantity>0), unit_price_minor bigint not null check(unit_price_minor>=0), discount_minor bigint not null default 0, allocated_tax_minor bigint not null default 0, allocated_shipping_minor bigint not null default 0, allocated_fees_minor bigint not null default 0, line_total_minor bigint not null check(line_total_minor>=0), currency text not null check(currency ~ '^[A-Z]{3}$'), unique(order_id,procurement_line_id)
);
create table public.furnishing_shipment_lines(id uuid primary key default gen_random_uuid(),shipment_id uuid not null references public.furnishing_shipments(id) on delete cascade,order_line_id uuid not null references public.furnishing_procurement_order_lines(id),quantity numeric(12,4) not null check(quantity>0),unique(shipment_id,order_line_id));
create table public.furnishing_procurement_receipts(id uuid primary key default gen_random_uuid(),baseline_id uuid not null references public.furnishing_procurement_baselines(id),shipment_id uuid references public.furnishing_shipments(id),status text not null check(status in('partial','complete','exception')), evidence jsonb not null default '{}',notes text,received_by uuid not null references public.profiles(id),received_at timestamptz not null default now(),idempotency_key text not null,unique(baseline_id,idempotency_key));
create table public.furnishing_procurement_receipt_lines(id uuid primary key default gen_random_uuid(),receipt_id uuid not null references public.furnishing_procurement_receipts(id) on delete cascade,procurement_line_id uuid not null references public.furnishing_procurement_lines(id),quantity numeric(12,4) not null check(quantity>0),disposition text not null check(disposition in('accepted','damaged','incorrect_product','incorrect_variant','missing','rejected','awaiting_assembly','awaiting_installation','installed')),evidence jsonb not null default '{}');
create table public.furnishing_procurement_returns(id uuid primary key default gen_random_uuid(),baseline_id uuid not null references public.furnishing_procurement_baselines(id),order_line_id uuid not null references public.furnishing_procurement_order_lines(id),quantity numeric(12,4) not null check(quantity>0),reason text not null,status text not null check(status in('requested','authorized','in_transit','retailer_received','refund_pending','partially_refunded','refunded','rejected','closed')),expected_refund_minor bigint not null default 0,restocking_fee_minor bigint not null default 0,return_shipping_minor bigint not null default 0,currency text not null check(currency ~ '^[A-Z]{3}$'),evidence jsonb not null default '{}',created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.furnishing_procurement_refunds(id uuid primary key default gen_random_uuid(),return_id uuid not null references public.furnishing_procurement_returns(id),amount_minor bigint not null check(amount_minor>0),currency text not null check(currency ~ '^[A-Z]{3}$'),external_reference text,evidence jsonb not null default '{}',idempotency_key text not null,recorded_by uuid not null references public.profiles(id),recorded_at timestamptz not null default now(),unique(return_id,idempotency_key));
create table public.furnishing_procurement_substitutions(id uuid primary key default gen_random_uuid(),line_id uuid not null references public.furnishing_procurement_lines(id),substitution_type text not null check(substitution_type in('retailer_offer','equivalent_product','material_design')),original_product_id uuid references public.furnishing_products(id),replacement_product_id uuid references public.furnishing_products(id),original_offer_id uuid references public.furnishing_product_offers(id),replacement_offer_id uuid references public.furnishing_product_offers(id),status text not null check(status in('requested','approved','rejected','plan_revision_required')),reason text not null,impact_snapshot jsonb not null,requested_by uuid not null references public.profiles(id),approved_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.furnishing_procurement_exceptions(id uuid primary key default gen_random_uuid(),baseline_id uuid not null references public.furnishing_procurement_baselines(id),line_id uuid references public.furnishing_procurement_lines(id),exception_type text not null,severity text not null check(severity in('warning','blocking')),status text not null default 'open' check(status in('open','resolved','waived')),detail jsonb not null default '{}',resolution text,resolved_by uuid references public.profiles(id),resolved_at timestamptz,created_at timestamptz not null default now());
create table public.furnishing_procurement_events(id uuid primary key default gen_random_uuid(),baseline_id uuid not null references public.furnishing_procurement_baselines(id),workspace_id uuid not null references public.owners(id),property_id uuid not null references public.properties(id),project_id uuid not null references public.furnishing_projects(id),actor_id uuid not null references public.profiles(id),correlation_id uuid not null,event_type text not null,previous_version bigint,resulting_version bigint,reason text,policy_version text not null,related_type text,related_id uuid,payload jsonb not null default '{}',occurred_at timestamptz not null default now());

create index furnishing_procurement_baseline_scope_idx on public.furnishing_procurement_baselines(workspace_id,property_id,project_id,status);
create index furnishing_procurement_lines_status_idx on public.furnishing_procurement_lines(baseline_id,room_id,status);
create index furnishing_purchase_batches_status_idx on public.furnishing_purchase_batches(baseline_id,retailer_id,status);
create index furnishing_procurement_events_timeline_idx on public.furnishing_procurement_events(baseline_id,occurred_at desc);

-- Every new aggregate is tenant protected through its baseline.
do $policies$ declare t text; begin foreach t in array array['furnishing_procurement_baselines','furnishing_procurement_lines','furnishing_project_procurement_budgets','furnishing_budget_allocations','furnishing_budget_adjustments','furnishing_purchase_batches','furnishing_purchase_batch_lines','furnishing_procurement_order_lines','furnishing_shipment_lines','furnishing_procurement_receipts','furnishing_procurement_receipt_lines','furnishing_procurement_returns','furnishing_procurement_refunds','furnishing_procurement_substitutions','furnishing_procurement_exceptions','furnishing_procurement_events'] loop execute format('alter table public.%I enable row level security',t); end loop; end $policies$;
create policy "Members read procurement baselines" on public.furnishing_procurement_baselines for select to authenticated using(public.active_workspace_role(workspace_id)is not null or public.is_admin());
create policy "Members read procurement lines" on public.furnishing_procurement_lines for select to authenticated using(exists(select 1 from public.furnishing_procurement_baselines b where b.id=baseline_id and(public.active_workspace_role(b.workspace_id)is not null or public.is_admin())));
create policy "Members read procurement budgets" on public.furnishing_project_procurement_budgets for select to authenticated using(public.active_workspace_role(workspace_id)is not null or public.is_admin());
create policy "Members read procurement events" on public.furnishing_procurement_events for select to authenticated using(public.active_workspace_role(workspace_id)is not null or public.is_admin());

commit;
