-- FS-UX-009: bounded remaining-path integration fixes.
begin;

create or replace function public.save_furnishing_selection_delivery(p_input jsonb)
returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare a uuid:=auth.uid();selection_id uuid;expected bigint;requested numeric;delivery bigint;correlation uuid;command_key text;selection public.furnishing_product_selections%rowtype;plan public.furnishing_plans%rowtype;project public.furnishing_projects%rowtype;property_id uuid;rule public.furnishing_quantity_rules%rowtype;allocation public.furnishing_selection_delivery_allocations%rowtype;fingerprint text;prior public.furnishing_owner_plan_commands%rowtype;
begin
 if a is null then raise exception 'OWNER_SELECTION_UNAUTHORIZED' using errcode='42501';end if;
 begin selection_id:=(p_input->>'selection_id')::uuid;expected:=(p_input->>'expected_revision')::bigint;requested:=(p_input->>'quantity')::numeric;delivery:=(p_input->>'delivery_minor')::bigint;correlation:=(p_input->>'correlation_id')::uuid;exception when others then raise exception 'OWNER_SELECTION_COMMAND_INVALID';end;
 command_key:=left(trim(p_input->>'idempotency_key'),200);if length(command_key)<8 or requested<0 or delivery<0 then raise exception 'OWNER_SELECTION_COMMAND_INVALID';end if;
 select s.* into selection from public.furnishing_product_selections s where s.id=selection_id for update;if not found then raise exception 'OWNER_SELECTION_NOT_FOUND';end if;
 select x.* into plan from public.furnishing_plans x where x.id=selection.furnishing_plan_id for update;select p.* into project from public.furnishing_projects p where p.id=plan.project_id;property_id:=project.property_id;
 if plan.status<>'draft' or plan.revision<>expected or not public.fs008g_owner_selection_eligible(project.workspace_id) then raise exception 'OWNER_SELECTION_STALE_OR_INELIGIBLE';end if;
 select q.* into rule from public.furnishing_quantity_rules q where q.id=selection.quantity_rule_id;
 if rule.rule_type='fixed' and rule.multiplier=1 and requested<>1 then raise exception 'OWNER_SELECTION_FIXED_ONE';end if;
 if requested<coalesce(rule.minimum,0) or (rule.maximum is not null and requested>rule.maximum) then raise exception 'OWNER_SELECTION_QUANTITY_BOUNDS';end if;
 fingerprint:=encode(digest(concat_ws(':',selection_id,expected,requested,delivery,correlation),'sha256'),'hex');
 select c.* into prior from public.furnishing_owner_plan_commands c where c.idempotency_key=command_key for update;
 if found then if prior.payload_hash<>fingerprint then raise exception 'OWNER_SELECTION_REPLAY_CONFLICT';end if;return prior.after_state||jsonb_build_object('status','replayed');end if;
 update public.furnishing_product_selections set quantity_override=requested,purchase_quantity=greatest(0,requested-existing_quantity),estimated_total_minor=case when estimated_unit_price_minor is null then null else estimated_unit_price_minor*greatest(0,requested-existing_quantity) end,revision=revision+1,updated_at=now() where id=selection.id;
 insert into public.furnishing_selection_delivery_allocations(workspace_id,project_id,selection_id,property_id,quantity,delivery_minor,currency,created_by) values(project.workspace_id,project.id,selection.id,property_id,greatest(0,requested-selection.existing_quantity),delivery,selection.currency,a) on conflict on constraint furnishing_selection_delivery_allo_selection_id_property_id_key do update set quantity=excluded.quantity,delivery_minor=excluded.delivery_minor,revision=furnishing_selection_delivery_allocations.revision+1,updated_at=now() returning * into allocation;
 update public.furnishing_plans set revision=revision+1,estimated_shipping_minor=(select coalesce(sum(d.delivery_minor),0) from public.furnishing_selection_delivery_allocations d where d.project_id=project.id),estimated_total_minor=(select coalesce(sum(s.estimated_total_minor),0) from public.furnishing_product_selections s where s.furnishing_plan_id=plan.id)+(select coalesce(sum(d.delivery_minor),0) from public.furnishing_selection_delivery_allocations d where d.project_id=project.id),updated_at=now() where id=plan.id;
 insert into public.furnishing_owner_plan_commands(workspace_id,project_id,plan_id,actor_id,command_type,expected_revision,resulting_revision,payload_hash,before_state,after_state,correlation_id,idempotency_key) values(project.workspace_id,project.id,plan.id,a,'selection_saved',expected,expected+1,fingerprint,jsonb_build_object('planRevision',expected,'selectionRevision',selection.revision),jsonb_build_object('planRevision',expected+1,'selectionRevision',selection.revision+1,'budgetDerived',true),correlation,command_key) returning * into prior;
 return prior.after_state||jsonb_build_object('status','saved');
end $$;

create or replace function public.fsux7_record_receipt(i uuid,expected bigint,input jsonb,idempotency text,correlation text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p public.furnishing_installation_projects;a uuid;order_line uuid;planned uuid;qty numeric;ordered numeric;received numeric;r uuid;rl uuid;begin select * into p from public.furnishing_installation_projects where id=i for update;if not found or p.current_tracking_version<>expected then raise exception 'INSTALLATION_TRACKING_STALE';end if;a:=public.fsux7_assert_action(i,'record_receipt');if exists(select 1 from public.furnishing_procurement_receipts where installation_project_id=i and idempotency_key=idempotency)then select id into r from public.furnishing_procurement_receipts where installation_project_id=i and idempotency_key=idempotency;return jsonb_build_object('receipt_id',r,'idempotent',true);end if;order_line:=(input->>'order_line_id')::uuid;qty:=(input->>'quantity')::numeric;select ol.ordered_quantity,ol.procurement_line_id into ordered,planned from public.furnishing_procurement_order_lines ol join public.furnishing_procurement_orders o on o.id=ol.order_id where ol.id=order_line and o.installation_project_id=i and o.baseline_id=p.procurement_baseline_id for update of ol;if not found then raise exception 'RECEIPT_SOURCE_INVALID';end if;select coalesce(sum(x.quantity),0)into received from public.furnishing_procurement_receipt_lines x join public.furnishing_procurement_receipts receipt on receipt.id=x.receipt_id where x.procurement_line_id=planned and receipt.installation_project_id=i;if qty<=0 or received+qty>ordered then raise exception 'RECEIPT_QUANTITY_EXCEEDED';end if;insert into public.furnishing_procurement_receipts(baseline_id,status,evidence,received_by,idempotency_key,installation_project_id,evidence_class,correlation_id)values(p.procurement_baseline_id,case when received+qty=ordered then'complete'else'partial'end,input,a,idempotency,i,input->>'evidence_class',correlation)returning id into r;insert into public.furnishing_procurement_receipt_lines(receipt_id,procurement_line_id,quantity,disposition,evidence)values(r,planned,qty,coalesce(input->>'disposition','accepted'),input)returning id into rl;update public.furnishing_installation_projects set tracking_status='delivery_in_progress',current_tracking_version=current_tracking_version+1,updated_at=now()where id=i;return jsonb_build_object('receipt_id',r,'receipt_line_id',rl,'idempotent',false);end$$;

create or replace function public.fsux7_record_installation(i uuid,expected bigint,input jsonb,idempotency text,correlation text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare p public.furnishing_installation_projects;a uuid;planned uuid;qty numeric;received numeric;installed numeric;event_id uuid;begin select * into p from public.furnishing_installation_projects where id=i for update;if not found or p.current_tracking_version<>expected then raise exception 'INSTALLATION_TRACKING_STALE';end if;a:=public.fsux7_assert_action(i,'installation');if exists(select 1 from public.fsux7_installation_events where installation_project_id=i and idempotency_key=idempotency)then select id into event_id from public.fsux7_installation_events where installation_project_id=i and idempotency_key=idempotency;return jsonb_build_object('event_id',event_id,'idempotent',true);end if;planned:=(input->>'planned_line_id')::uuid;qty:=(input->>'quantity')::numeric;if not exists(select 1 from public.fsux7_planned_lines pl where pl.id=planned and pl.installation_project_id=i)then raise exception 'INSTALLATION_SOURCE_INVALID';end if;select coalesce(sum(rl.quantity),0)into received from public.fsux7_planned_lines pl join public.furnishing_procurement_receipt_lines rl on rl.procurement_line_id=pl.procurement_line_id join public.furnishing_procurement_receipts receipt on receipt.id=rl.receipt_id where pl.id=planned and pl.installation_project_id=i and receipt.installation_project_id=i;select coalesce(sum(e.quantity),0)into installed from public.fsux7_installation_events e where e.planned_line_id=planned and e.installation_project_id=i and e.event_type in('installed','accepted');if qty<=0 or installed+qty>received then raise exception 'INSTALLATION_QUANTITY_EXCEEDED';end if;insert into public.fsux7_installation_events(installation_project_id,planned_line_id,room_id,event_type,quantity,installer_description,evidence_class,evidence,recording_actor,correlation_id,idempotency_key)select i,pl.id,pl.room_id,'installed',qty,input->>'external_actor',input->>'evidence_class',input,a,correlation,idempotency from public.fsux7_planned_lines pl where pl.id=planned and pl.installation_project_id=i returning id into event_id;if event_id is null then raise exception 'INSTALLATION_SOURCE_INVALID';end if;update public.furnishing_installation_projects set tracking_status='installation_in_progress',current_tracking_version=current_tracking_version+1,updated_at=now()where id=i;return jsonb_build_object('event_id',event_id,'idempotent',false);end$$;

revoke all on function public.save_furnishing_selection_delivery(jsonb),public.fsux7_record_receipt(uuid,bigint,jsonb,text,text),public.fsux7_record_installation(uuid,bigint,jsonb,text,text) from public,anon,authenticated;
grant execute on function public.save_furnishing_selection_delivery(jsonb),public.fsux7_record_receipt(uuid,bigint,jsonb,text,text),public.fsux7_record_installation(uuid,bigint,jsonb,text,text) to authenticated;

commit;
