"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import {
  attachExecuteEvidenceAction,
  blockExecuteAction,
  resolveExecuteBlockerAction,
  reviewExecuteEvidenceAction,
  submitExecuteEvidenceAction,
  transitionExecuteAction,
} from "@/app/actions/execute-controls";
import { DEFAULT_ACTION_BLOCKER_SEVERITY, type ExecuteActionDetail, type ExecuteControlResult, type ExecuteControlState, type ExecuteNextCommand } from "@/platform/actions";
import { ActionPriorityBadge } from "./action-priority-badge";
import { ActionStatusBadge } from "./action-status-badge";
import { actionPlanPath } from "../domain/action-plan-route";

type Result = ExecuteControlResult<ExecuteControlState>;

export function ExecutionDetailWorkspace({ detail, workspaceId = "" }: Readonly<{ detail: ExecuteActionDetail; workspaceId?: string }>) {
  const router = useRouter(), [pending, startTransition] = useTransition(), [message, setMessage] = useState("");
  function run(operation: () => Promise<Result>) { startTransition(async () => { const result = await operation(); if (result.ok) { setMessage(""); router.refresh(); } else setMessage(result.message); }); }
  const command = (operation: Extract<ExecuteNextCommand, "start" | "submit-for-review" | "return-for-correction" | "complete" | "fail" | "retry" | "reopen">, reason?: string) => run(() => transitionExecuteAction({ actionId: detail.id, expectedVersion: detail.version, operation, ...(reason ? { reason } : {}), correlationId: `customer-action:${operation}:${crypto.randomUUID()}` }));
  const pendingEvidence = detail.evidence.filter((item) => item.status === "pending");
  return <main className="mx-auto max-w-6xl space-y-8 px-4 py-10 sm:px-6">
    <nav aria-label="Breadcrumb" className="text-sm text-stone-600"><Link className="font-semibold" href="/dashboard/execute">Execute › Action Center</Link><span aria-hidden="true"> › </span><span>Action</span></nav>
    <header><div className="flex flex-wrap gap-2"><ActionPriorityBadge priority={detail.priority} /><ActionStatusBadge status={detail.status} /><span className="text-xs text-stone-500">Version {detail.version}</span></div><h1 className="mt-5 text-4xl font-semibold">{detail.title}</h1>{detail.description ? <p className="mt-4 max-w-3xl text-stone-600">{detail.description}</p> : null}</header>
    <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Owner" value={detail.owner.id ?? detail.owner.type} /><Fact label="Assignee" value={detail.assignee?.id ?? "Unassigned"} /><Fact label="Due" value={detail.deadline?.toLocaleString() ?? "Not scheduled"} /><Fact label="Property" value={detail.propertyId ?? "Portfolio scope"} /></dl>
    <div className="flex flex-wrap gap-4">{detail.planId && workspaceId ? <Link className="font-semibold text-teal-800" href={actionPlanPath(detail.planId, workspaceId, "actions")}>View Action Plan →</Link> : null}{detail.decisionId ? <Link className="font-semibold text-teal-800" href={`/dashboard/portfolio/decisions/${encodeURIComponent(detail.decisionId)}`}>View source decision →</Link> : null}</div>
    <section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Execution requirements</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Fact label="Evidence policy" value={detail.evidencePolicy.mode.replaceAll("-", " ")} /><Fact label="Review" value={detail.reviewState.replaceAll("-", " ")} /><Fact label="Expected outcome" value={detail.expectedOutcome ?? "Not specified"} /><Fact label="Success metric" value={detail.successMetric ?? "Not specified"} /></dl>{detail.completionChecklist.length ? <ul className="mt-4 list-disc pl-5 text-sm">{detail.completionChecklist.map((item) => <li key={item}>{item}</li>)}</ul> : null}</section>
    <section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Dependencies and blockers</h2>{detail.dependencies.length ? <ul className="mt-4 space-y-2 text-sm">{detail.dependencies.map((item) => <li key={item.dependsOnActionId}>Depends on {item.dependsOnActionId}{detail.unresolvedDependencyIds.includes(item.dependsOnActionId) ? " · Incomplete" : " · Satisfied"}</li>)}</ul> : <p className="mt-3 text-sm text-stone-600">No dependencies.</p>}{detail.activeBlockers.length ? <ul className="mt-4 space-y-3">{detail.activeBlockers.map((blocker) => <li className="rounded-xl bg-amber-50 p-4 text-sm" key={blocker.id}><strong>{blocker.category.replaceAll("-", " ")}</strong><span className="block">{blocker.description}</span>{detail.validCommands.includes("resolve-blocker") ? <ReasonButton disabled={pending} label="Resolve blocker" onConfirm={(reason) => run(() => resolveExecuteBlockerAction({ actionId: detail.id, expectedVersion: detail.version, blockerId: blocker.id, resolutionNote: reason, correlationId: `customer-blocker-resolution:${crypto.randomUUID()}` }))} /> : null}</li>)}</ul> : <p className="mt-3 text-sm text-stone-600">No active blockers.</p>}{detail.validCommands.includes("block") ? <ReasonButton disabled={pending} label="Add blocker" onConfirm={(reason) => run(() => blockExecuteAction({ actionId: detail.id, expectedVersion: detail.version, blocker: { category: "other", description: reason, severity: DEFAULT_ACTION_BLOCKER_SEVERITY }, correlationId: `customer-blocker:${crypto.randomUUID()}` }))} /> : null}</section>
    <section className="rounded-2xl border p-6"><h2 className="text-xl font-semibold">Completion evidence</h2>{detail.evidence.length ? <ul className="mt-4 space-y-3">{detail.evidence.map((item) => <li className="rounded-xl bg-stone-50 p-4 text-sm" key={item.id}><strong>{item.type.replaceAll("-", " ")} · {item.status}</strong>{item.caption ? <span className="mt-1 block">{item.caption}</span> : null}{detail.validCommands.includes("review-evidence") && ["pending", "submitted"].includes(item.status) ? <div className="mt-3 flex gap-2"><button disabled={pending} onClick={() => run(() => reviewExecuteEvidenceAction({ actionId: detail.id, expectedVersion: detail.version, evidenceId: item.id, accepted: true, correlationId: `customer-evidence-review:${crypto.randomUUID()}` }))} className="rounded-lg bg-emerald-800 px-3 py-2 font-semibold text-white">Accept evidence</button><ReasonButton disabled={pending} label="Return evidence" onConfirm={(reason) => run(() => reviewExecuteEvidenceAction({ actionId: detail.id, expectedVersion: detail.version, evidenceId: item.id, accepted: false, reason, correlationId: `customer-evidence-return:${crypto.randomUUID()}` }))} /></div> : null}</li>)}</ul> : <p className="mt-3 text-sm text-stone-600">No completion evidence has been attached.</p>}{detail.validCommands.includes("add-evidence") ? <EvidenceForm disabled={pending} onAttach={(caption) => run(() => attachExecuteEvidenceAction({ actionId: detail.id, expectedVersion: detail.version, evidence: { type: "text-note", caption }, correlationId: `customer-evidence:${crypto.randomUUID()}` }))} /> : null}{detail.validCommands.includes("submit-evidence") && pendingEvidence.length ? <button className="mt-4 rounded-full border px-4 py-2 text-sm font-semibold" disabled={pending} onClick={() => run(() => submitExecuteEvidenceAction({ actionId: detail.id, expectedVersion: detail.version, evidenceIds: pendingEvidence.map((item) => item.id), correlationId: `customer-evidence-submit:${crypto.randomUUID()}` }))}>Submit evidence for review</button> : null}</section>
    <section className="rounded-2xl bg-stone-950 p-6 text-white"><h2 className="font-semibold">Available actions</h2><div className="mt-4 flex flex-wrap gap-3">{detail.validCommands.filter(isTransition).map((item) => requiresReason(item) ? <ReasonButton dark disabled={pending} key={item} label={label(item)} onConfirm={(reason) => command(item, reason)} /> : <button className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-stone-950 disabled:opacity-40" disabled={pending} key={item} onClick={() => command(item)}>{label(item)}</button>)}{!detail.validCommands.some(isTransition) ? <p className="text-sm text-stone-400">No lifecycle commands are currently available.</p> : null}</div></section>
    {message ? <p className="rounded-xl bg-rose-50 p-4 text-rose-900" role="alert">{message}</p> : null}
    <section><h2 className="text-2xl font-semibold">History</h2>{detail.activity.length ? <ol className="mt-4 space-y-3">{detail.activity.map((event) => <li className="rounded-xl border p-4 text-sm" key={event.id}><strong>{event.eventType.replaceAll("-", " ")}</strong><span className="block text-stone-600">{event.occurredAt.toLocaleString()} · {event.actor.id ?? event.actor.type}</span></li>)}</ol> : <p className="mt-4 rounded-xl border bg-stone-50 p-5 text-sm text-stone-600">No execution history is available.</p>}</section>
  </main>;
}

const transitions = new Set<ExecuteNextCommand>(["start", "submit-for-review", "return-for-correction", "complete", "fail", "retry", "reopen"]);
function isTransition(value: ExecuteNextCommand): value is Extract<ExecuteNextCommand, "start" | "submit-for-review" | "return-for-correction" | "complete" | "fail" | "retry" | "reopen"> { return transitions.has(value); }
function requiresReason(value: ExecuteNextCommand) { return ["return-for-correction", "fail", "retry", "reopen"].includes(value); }
function label(value: string) { return value.replaceAll("-", " ").replace(/^./, (character) => character.toUpperCase()); }
function Fact({ label: title, value }: Readonly<{ label: string; value: string }>) { return <div className="rounded-xl bg-stone-50 p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-stone-500">{title}</dt><dd className="mt-2 break-words font-semibold capitalize text-stone-950">{value}</dd></div>; }
function EvidenceForm({ disabled, onAttach }: Readonly<{ disabled: boolean; onAttach: (caption: string) => void }>) { const [caption, setCaption] = useState(""); return <form className="mt-5 rounded-xl bg-stone-50 p-4" onSubmit={(event) => { event.preventDefault(); onAttach(caption); setCaption(""); }}><label className="text-sm font-semibold">Evidence note<textarea className="mt-2 block min-h-24 w-full rounded-lg border p-3 font-normal" disabled={disabled} onChange={(event) => setCaption(event.target.value)} required value={caption} /></label><button className="mt-3 rounded-lg bg-stone-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" disabled={disabled || !caption.trim()}>Attach evidence</button></form>; }
function ReasonButton({ dark = false, disabled, label: title, onConfirm }: Readonly<{ dark?: boolean; disabled: boolean; label: string; onConfirm: (reason: string) => void }>) { const [open, setOpen] = useState(false), [reason, setReason] = useState(""); return open ? <form className={`w-full rounded-xl p-4 ${dark ? "border border-stone-700 bg-stone-900" : "border bg-white"}`} onSubmit={(event) => { event.preventDefault(); onConfirm(reason); setOpen(false); setReason(""); }}><label className="text-sm font-semibold">Reason for {title.toLowerCase()}<textarea className={`mt-2 block min-h-20 w-full rounded-lg border p-3 font-normal ${dark ? "border-stone-600 bg-stone-950 text-white" : ""}`} onChange={(event) => setReason(event.target.value)} required value={reason} /></label><div className="mt-3 flex gap-2"><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${dark ? "bg-white text-stone-950" : "bg-stone-950 text-white"}`} disabled={disabled || !reason.trim()}>Confirm</button><button className="rounded-lg border px-4 py-2 text-sm" onClick={() => setOpen(false)} type="button">Cancel</button></div></form> : <button className={dark ? "rounded-xl bg-white px-4 py-2 text-sm font-semibold text-stone-950" : "mt-3 rounded-lg border px-3 py-2 text-sm font-semibold"} disabled={disabled} onClick={() => setOpen(true)} type="button">{title}</button>; }
