export type LearningSubjectType="investment-scenario"|"revenue-recommendation"|"capital-allocation"|"financial-plan"|"guest-communication"|"guidebook"|"property"|"portfolio-decision"|"operational-action";
export type LearningSourceCapability="investment-intelligence"|"revenue-intelligence"|"financial-intelligence"|"guest-communications"|"guidebook-studio"|"portfolio-intelligence"|"action-center"|"operations";
export type LearningConfidence="high"|"moderate"|"low"|"insufficient-evidence";
export type LearningValue=string|number|boolean|null|Readonly<Record<string,unknown>>|readonly unknown[];
export type LearningReferenceType="observation"|"decision"|"recommendation"|"action"|"measurement"|"outcome"|"review"|"lesson"|"report"|"scenario"|"evidence";
export type LearningReference=Readonly<{type:LearningReferenceType;capability:string;sourceId:string;sourceVersion?:string}>;
export type LearningSubject=Readonly<{id:string;workspaceId:string;subjectType:LearningSubjectType;sourceCapability:LearningSourceCapability;sourceId:string;sourceVersion?:string;createdAt:string;createdByProfileId:string}>;
export type LearningLineageEdge=Readonly<{id:string;workspaceId:string;subjectId:string;from:LearningReference;to:LearningReference;relationship:"originated-from"|"recommended-by"|"decided-by"|"executed-by"|"measured-by"|"reviewed-by"|"supported-by"|"derived-lesson";createdAt:string}>;
export type LearningEvidence=Readonly<{id:string;workspaceId:string;references:readonly LearningReference[];confidence:LearningConfidence;freshness:"current"|"stale"|"unknown";capturedAt:string}>;
export type ExpectedOutcome=Readonly<{id:string;planId:string;metric:string;expectedValue:LearningValue;expectedDirection:"increase"|"decrease"|"maintain"|"achieve"|"avoid"|"complete";confidence:LearningConfidence;evidenceId?:string}>;
export type MeasuredOutcome=Readonly<{id:string;workspaceId:string;subjectId:string;metric:string;observedValue:LearningValue;observedAt:string;evidenceId:string;recordedAt:string}>;
export type LearningMeasurementPlan=Readonly<{id:string;workspaceId:string;subjectId:string;baseline:Readonly<Record<string,LearningValue>>;expectedOutcomes:readonly ExpectedOutcome[];measurementWindow:Readonly<{type:"30-days"|"90-days"|"180-days"|"annual"|"custom";start:string;end:string}>;confidence:LearningConfidence;version:number;createdAt:string}>;
export type OutcomeReviewStatus="pending"|"ready"|"completed"|"unable-to-evaluate";
export type LearningOutcomeReview=Readonly<{id:string;workspaceId:string;subjectId:string;measurementPlanId:string;expectedOutcomeIds:readonly string[];measuredOutcomeIds:readonly string[];status:OutcomeReviewStatus;evidenceIds:readonly string[];supersedesReviewId?:string;createdAt:string;createdByProfileId:string}>;
export type AssumptionResultStatus="confirmed"|"partially-confirmed"|"invalidated"|"unable-to-evaluate";
export type LearningAssumptionResult=Readonly<{id:string;workspaceId:string;subjectId:string;reviewId:string;assumption:string;status:AssumptionResultStatus;confidence:LearningConfidence;evidenceIds:readonly string[];createdAt:string}>;
export type LessonApplicability=Readonly<{scope:"workspace"|"portfolio"|"market"|"property"|"property-type"|"season"|"strategy";referenceId?:string;label?:string}>;
export type LearningLesson=Readonly<{id:string;workspaceId:string;subjectId:string;statement:string;applicability:readonly LessonApplicability[];confidence:LearningConfidence;maturity:"emerging"|"supported"|"established"|"well-validated";status:"candidate"|"validated"|"retired"|"contradicted";evidenceIds:readonly string[];lineageEdgeIds:readonly string[];revision:number;supersedesLessonId?:string;createdAt:string;createdByProfileId:string}>;
export type LearningDomainEvent=Readonly<{id:string;type:"LearningSubjectCreated"|"OutcomeReviewCreated"|"LessonCreated"|"LessonRetired";workspaceId:string;aggregateId:string;occurredAt:string;payload:Readonly<Record<string,string|number|boolean|null>>}>;
export class PlatformLearningError extends Error{constructor(public readonly code:"learning_invalid"|"learning_subject_not_found"|"learning_evidence_required"|"learning_lineage_invalid"|"learning_permission_denied"|"learning_idempotency_conflict"|"learning_unexpected",message:string){super(message);this.name="PlatformLearningError";Object.freeze(this)}}
export function createLearningSubject(input:LearningSubject):Readonly<{subject:LearningSubject;event:LearningDomainEvent}>{required(input.id,input.workspaceId,input.sourceId,input.createdByProfileId);return deepFreeze({subject:input,event:event("LearningSubjectCreated",input.workspaceId,input.id,input.createdAt,{subjectType:input.subjectType,sourceCapability:input.sourceCapability,sourceId:input.sourceId})})}
export function createLineageEdge(input:LearningLineageEdge):LearningLineageEdge{required(input.id,input.workspaceId,input.subjectId,input.from.sourceId,input.to.sourceId);if(input.from.type===input.to.type&&input.from.sourceId===input.to.sourceId)throw new PlatformLearningError("learning_lineage_invalid","A lineage edge cannot reference itself.");return deepFreeze(input)}
export function createMeasurementPlan(input:LearningMeasurementPlan):LearningMeasurementPlan{required(input.id,input.workspaceId,input.subjectId);if(!input.expectedOutcomes.length||Date.parse(input.measurementWindow.end)<=Date.parse(input.measurementWindow.start))throw new PlatformLearningError("learning_invalid","A Measurement Plan requires expected outcomes and a valid review window.");if(input.expectedOutcomes.some(outcome=>outcome.planId!==input.id))throw new PlatformLearningError("learning_lineage_invalid","Expected Outcomes must reference their Measurement Plan.");return deepFreeze(input)}
export function createOutcomeReview(input:LearningOutcomeReview):Readonly<{review:LearningOutcomeReview;event:LearningDomainEvent}>{required(input.id,input.workspaceId,input.subjectId,input.measurementPlanId,input.createdByProfileId);if(!input.expectedOutcomeIds.length)throw new PlatformLearningError("learning_invalid","An Outcome Review requires an expected outcome.");if(input.status==="completed"&&!input.evidenceIds.length)throw new PlatformLearningError("learning_evidence_required","Completed reviews require evidence.");return deepFreeze({review:input,event:event("OutcomeReviewCreated",input.workspaceId,input.id,input.createdAt,{subjectId:input.subjectId,status:input.status})})}
export function createLearningLesson(input:LearningLesson):Readonly<{lesson:LearningLesson;event:LearningDomainEvent}>{required(input.id,input.workspaceId,input.subjectId,input.statement,input.createdByProfileId);if(!input.evidenceIds.length||!input.lineageEdgeIds.length)throw new PlatformLearningError("learning_evidence_required","A Lesson requires evidence and lineage.");const type=input.status==="retired"?"LessonRetired":"LessonCreated";return deepFreeze({lesson:input,event:event(type,input.workspaceId,input.id,input.createdAt,{subjectId:input.subjectId,status:input.status,revision:input.revision})})}
export function reviseLearningLesson(previous:LearningLesson,input:Omit<LearningLesson,"revision"|"supersedesLessonId">):Readonly<{lesson:LearningLesson;event:LearningDomainEvent}>{if(previous.workspaceId!==input.workspaceId||previous.subjectId!==input.subjectId)throw new PlatformLearningError("learning_lineage_invalid","Lesson revisions must retain their subject and workspace.");return createLearningLesson({...input,revision:previous.revision+1,supersedesLessonId:previous.id})}
function event(type:LearningDomainEvent["type"],workspaceId:string,aggregateId:string,occurredAt:string,payload:LearningDomainEvent["payload"]):LearningDomainEvent{return deepFreeze({id:`${type}:${aggregateId}:${occurredAt}`,type,workspaceId,aggregateId,occurredAt,payload})}
function required(...values:string[]){if(values.some(value=>!value.trim()))throw new PlatformLearningError("learning_invalid","Required Learning identity is missing.")}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);Object.values(value).forEach(deepFreeze)}return value}
