import Link from "next/link";
import { AlertCircle, ArrowRight, Boxes, ClipboardList, FileUp, Plus, ShieldCheck, Sofa } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { getFurnishingOverview } from "@/app/actions/furnishing-overview";
import { FurnishingHeader } from "./furnishing-navigation";
// Supabase projections remain dynamic until generated FS-UX-002 database types land.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
const metricLabels = { platformProducts: "Platform library", workspaceProducts: "Workspace catalog", productsNeedingReview: "Products needing review", activeDesignWorkspaces: "Active design workspaces", budgetsNeedingAttention: "Budgets needing attention", procurementExceptions: "Procurement exceptions", installationExceptions: "Installation exceptions" } as const;
export async function FurnishingOverview({ workspaceId }: { workspaceId?: string }) {
  const data = await getFurnishingOverview(workspaceId);
  return <main className="space-y-8 px-4 pb-12 sm:px-0"><FurnishingHeader title="Furnishing Studio" description="Manage catalog readiness, design activity, budgets, procurement, and installation across controlled workspaces." current="overview" action={<div className="flex flex-wrap gap-2"><Action href="/admin/furnishing/products/new" label="Add product" icon={Plus}/><Action href="/admin/furnishing/products/import" label="Import inventory" icon={FileUp} primary/></div>} />
    <section className="flex flex-wrap items-start justify-between gap-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5" aria-labelledby="health-title"><div><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="h-5 w-5"/><h2 id="health-title" className="font-semibold">Operating normally</h2></div><p className="mt-2 max-w-4xl text-sm leading-6 text-stone-700">Available Furnishing Studio capabilities are operating within their authorized boundary.</p></div></section>
    <section aria-labelledby="summary-title"><h2 id="summary-title" className="text-xl font-semibold">Operational summary</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.metrics).map(([key, value]) => <article key={key} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-stone-200"><p className="text-sm text-stone-600">{metricLabels[key as keyof typeof metricLabels]}</p><p className="mt-2 text-3xl font-semibold">{value === null ? "Unavailable" : value}</p></article>)}</div></section>
    <section aria-labelledby="attention-title"><div className="flex items-end justify-between"><div><h2 id="attention-title" className="text-2xl font-semibold">Requires attention</h2><p className="mt-1 text-sm text-stone-600">Authoritative issues ordered for operational follow-through.</p></div></div>{data.failures.catalog ? <ProjectionFailure name="Catalog review"/> : data.attention.length ? <div className="mt-4 overflow-hidden rounded-2xl border border-stone-200 bg-white"><ul className="divide-y divide-stone-200">{data.attention.map((item) => <li key={item.id}><Link href={item.href} className="grid min-h-20 gap-2 p-4 outline-none hover:bg-stone-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-emerald-700 sm:grid-cols-[1fr_180px_120px_auto] sm:items-center"><span><span className="block font-semibold">{item.title}</span><span className="mt-1 block text-sm text-stone-600">{item.entity}</span></span><span className="text-sm">{item.category}</span><span className="text-sm text-stone-600">{item.severity}</span><span className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-800">Resolve <ArrowRight aria-hidden="true" className="h-4 w-4"/></span></Link></li>)}</ul></div> : <div className="mt-4 rounded-2xl border border-dashed border-stone-300 p-8 text-center"><h3 className="font-semibold">Nothing requires immediate attention</h3><p className="mt-2 text-sm text-stone-600">Furnishing workflows in this workspace have no unresolved operational issues.</p></div>}</section>
    <div className="grid gap-8 xl:grid-cols-2"><section aria-labelledby="active-title"><h2 id="active-title" className="text-xl font-semibold">Active work</h2>{data.failures.workspaces ? <ProjectionFailure name="Active work"/> : <div className="mt-4 rounded-2xl border bg-white p-2">{(data.activeWork as Row[]).length ? (data.activeWork as Row[]).map((item) => <Link href={`/admin/furnishing/workspaces/${item.id}`} key={item.id} className="flex min-h-16 items-center justify-between rounded-xl px-4 hover:bg-stone-50"><span><span className="block font-semibold">{item.name}</span><span className="text-sm text-stone-600">{item.properties?.name ?? "Furnishing workspace"} · {String(item.lifecycle_status).replaceAll("_", " ")}</span></span><ArrowRight aria-hidden="true" className="h-4 w-4"/></Link>) : <p className="p-6 text-sm text-stone-600">No active design workspaces.</p>}</div>}</section><section aria-labelledby="activity-title"><h2 id="activity-title" className="text-xl font-semibold">Recent activity</h2>{data.failures.activity ? <ProjectionFailure name="Recent activity"/> : <ol className="mt-4 rounded-2xl border bg-white p-4">{(data.activity as Row[]).map((event) => <li key={event.id} className="border-b py-3 last:border-0"><p className="text-sm font-semibold">{String(event.event_type).replaceAll("_", " ")}</p><p className="mt-1 text-xs text-stone-500">{event.profiles?.full_name ?? event.profiles?.email ?? "Authorized operator"} · <time>{new Date(event.occurred_at).toLocaleString()}</time></p></li>)}{!data.activity.length ? <li className="p-4 text-sm text-stone-600">No recent governed catalog activity.</li> : null}</ol>}</section></div>
    <section aria-labelledby="next-title"><h2 id="next-title" className="text-xl font-semibold">Go next</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ActionCard href="/admin/furnishing/products" label="Browse product library" icon={Boxes}/><ActionCard href="/admin/furnishing/room-packages" label="Create room package" icon={Sofa}/><ActionCard href="/admin/furnishing/workspaces" label="Start design workspace" icon={ClipboardList}/><ActionCard href="/admin/furnishing/products/import" label="Import inventory" icon={FileUp}/></div></section>
  </main>;
}
function Action({ href, label, icon: Icon, primary=false }: { href:string;label:string;icon:LucideIcon;primary?:boolean }) { return <Link href={href} className={`inline-flex min-h-11 items-center gap-2 rounded-xl px-4 text-sm font-semibold outline-none focus-visible:ring-2 focus-visible:ring-emerald-700 focus-visible:ring-offset-2 ${primary ? "bg-emerald-800 text-white" : "border bg-white"}`}><Icon aria-hidden="true" className="h-4 w-4"/>{label}</Link>; }
function ActionCard({ href,label,icon:Icon }:{href:string;label:string;icon:LucideIcon}) { return <Link href={href} className="flex min-h-20 items-center gap-3 rounded-2xl border bg-white p-4 font-semibold outline-none hover:border-emerald-300 focus-visible:ring-2 focus-visible:ring-emerald-700"><Icon aria-hidden="true" className="h-5 w-5 text-emerald-800"/>{label}<ArrowRight aria-hidden="true" className="ml-auto h-4 w-4"/></Link>; }
function ProjectionFailure({name}:{name:string}) { return <div role="status" className="mt-4 flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm"><AlertCircle aria-hidden="true" className="h-5 w-5"/><span><strong>{name} unavailable.</strong> Other overview sections remain current.</span></div>; }
