import Link from "next/link";
import { authorizePurchaseBatchAction, changeProcurementLineOfferAction, generateProcurementBaselineAction, getProcurementWorkspace, recordExternalOrderAction, recordReceivingAction, saveProcurementBudgetAction, submitPurchaseBatchAction } from "@/app/actions/furnishing-procurement";
type Row = Record<string, unknown>;
const money=(minor:unknown,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(Number(minor??0)/100);
const title=(value:unknown)=>String(value??"").replaceAll("_"," ").replace(/\b\w/g,(x)=>x.toUpperCase());
export async function ProcurementWorkspace({projectId,customer=false,view="overview"}:{projectId:string;customer?:boolean;view?:string}){
 const data=await getProcurementWorkspace(projectId), base=`/${customer?"dashboard":"admin"}/furnishing/projects/${projectId}/procurement`;
 const project=data.project as Row, baseline=data.baseline as Row|null, budget=data.budget as Row|null, lines=data.lines as Row[], batches=data.batches as Row[], orders=data.orders as Row[], exceptions=data.exceptions as Row[], events=data.events as Row[], retailers=(data as Row).retailers as Row[], shipments=(data as Row).shipments as Row[];
 const tabs=["overview","budget","items","batches","orders","shipments","receiving","returns","activity"];
 if(!baseline)return <main className="mx-auto max-w-5xl p-6 lg:p-10"><Link className="text-sm text-muted-foreground" href={`/${customer?"dashboard":"admin"}/furnishing/projects/${projectId}`}>← Approved plan</Link><section className="mt-8 rounded-2xl border bg-card p-8 text-center shadow-sm"><div className="mx-auto grid size-16 place-items-center rounded-full border-2 border-emerald-600 text-3xl text-emerald-700">✓</div><h1 className="mt-5 text-3xl font-semibold">Your furnishing plan is approved</h1><p className="mx-auto mt-3 max-w-xl text-muted-foreground">{customer?"Procurement has not started. Your Luxe Haven Admin will verify the immutable selection source before creating the baseline.":"Start procurement from the authoritative immutable snapshot when present, or the compatible approved legacy plan. Conflicting or missing lineage is denied."}</p>{customer?null:<form className="mt-7" action={async(form)=>{"use server";await generateProcurementBaselineAction(form)}}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="idempotencyKey" value={`start-${projectId}`}/><button className="rounded-md bg-amber-700 px-6 py-3 font-medium text-white">Start procurement</button></form>}</section></main>;
 const currency=String(baseline.currency??"USD"), plan=Number(baseline.estimated_total_minor??0), approved=Number(budget?.base_amount_minor??0)+Number(budget?.contingency_minor??0), committed=Number(budget?.committed_minor??0), actual=Number(budget?.gross_actual_minor??0)-Number(budget?.refunded_minor??0)-Number(budget?.credited_minor??0), available=approved-committed-actual;
 return <main className="min-h-screen bg-stone-50"><header className="border-b bg-white px-5 py-5 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-widest text-amber-700">Furnishing · Procurement</p><div className="mt-1 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">{String(project.name??"Furnishing project")}</h1><p className="text-sm text-muted-foreground">Approved plan v{String(baseline.source_plan_version)} · Procurement baseline v{String(baseline.version)}</p></div><span className="rounded-full border px-3 py-1 text-sm">{title(baseline.status)}</span></div><nav className="mt-5 flex gap-1 overflow-x-auto">{tabs.map(t=><Link key={t} href={`${base}?view=${t}`} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm ${view===t?"bg-stone-900 text-white":"hover:bg-stone-100"}`}>{title(t)}</Link>)}</nav></div></header><div className="mx-auto max-w-7xl p-5 lg:p-10">
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Plan estimate",plan],["Approved budget",approved],["Committed",committed],["Net actual",actual],["Available",available]].map(([label,value])=><article key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{String(label)}</p><p className="mt-2 text-2xl font-semibold">{money(value,currency)}</p></article>)}</section>
 {view==="overview"&&<div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="Attention queue"><Attention count={!budget?1:0} text="Budget setup required"/><Attention count={lines.filter(x=>x.status==="blocked").length} text="Items need review"/><Attention count={orders.length===0?1:0} text="No purchase orders recorded"/></Panel><Panel title="Room progress"><Rows lines={lines}/></Panel></div>}
 {view==="budget"&&<div className="mt-6 grid gap-5 lg:grid-cols-[1fr_340px]"><Panel title="Project budget"><p className="mb-5 text-sm text-muted-foreground">Establish financial authority before purchase batches can reserve funds.</p><form action={saveProcurementBudgetAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="baselineId" value={String(baseline.id)}/><Field name="baseAmount" label="Base authorization" defaultValue={(plan/100).toFixed(2)}/><Field name="contingency" label="Contingency" defaultValue={(plan*.075/100).toFixed(2)}/><button className="rounded-md bg-amber-700 px-4 py-3 text-white sm:col-span-2">Submit budget for approval</button></form></Panel><Panel title="Budget summary"><Summary label="Approved plan" value={money(plan,currency)}/><Summary label="Proposed budget" value={budget?money(approved,currency):"Not set"}/><Summary label="Status" value={budget?title(budget.status):"Setup required"}/></Panel></div>}
 {view==="items"&&<div className="mt-6"><Panel title={`Procurement items (${lines.length})`}><p className="mb-4 text-sm text-muted-foreground">Estimated prices come from your approved design plan. Availability and verified pricing reflect the retailer offer last checked below — always an estimate until an order is placed.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="py-3">Item</th><th>Room</th><th>To purchase</th><th>Plan price</th><th>Retailer</th><th>Availability</th><th>Status</th></tr></thead><tbody>{lines.map(x=>{const offer=x.furnishing_product_offers as Row|undefined;const product=x.furnishing_products as Row|undefined;const altOffers=((product?.furnishing_product_offers as Row[]|undefined)??[]).filter(o=>o.id!==offer?.id);return <tr className="border-b last:border-0" key={String(x.id)}><td className="py-4 font-medium">{String(x.description)}</td><td>{String((x.furnishing_rooms as Row|undefined)?.name??"—")}</td><td>{String(x.procurement_quantity)}</td><td>{x.estimated_line_cost_minor==null?"Price unavailable":money(x.estimated_line_cost_minor,currency)}</td><td>{String((offer?.furnishing_retailers as Row|undefined)?.name??"Not selected")}{altOffers.length?<details className="mt-1"><summary className="cursor-pointer text-xs font-medium text-amber-700">Compare {altOffers.length} offer{altOffers.length===1?"":"s"}</summary><div className="mt-2 space-y-2">{altOffers.map(o=><form key={String(o.id)} action={changeProcurementLineOfferAction} className="flex items-center justify-between gap-2 rounded-md border p-2 text-xs"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="lineId" value={String(x.id)}/><input type="hidden" name="offerId" value={String(o.id)}/><span>{String((o.furnishing_retailers as Row|undefined)?.name??"Retailer")} · {money(o.listed_price_minor,currency)} · <span className="capitalize">{String(o.availability).replaceAll("_"," ")}</span></span><button className="rounded border px-2 py-1 font-medium">Use this offer</button></form>)}</div></details>:null}</td><td>{offer?<span><span className="capitalize">{String(offer.availability).replaceAll("_"," ")}</span>{offer.last_verified_at?<span className="block text-xs text-muted-foreground">Checked {new Date(String(offer.last_verified_at)).toLocaleDateString()}</span>:<span className="block text-xs text-amber-700">Not yet verified</span>}</span>:"—"}</td><td><span className="rounded-full border px-2 py-1 text-xs">{title(x.status)}</span></td></tr>})}</tbody></table></div></Panel></div>}
 {view==="batches"&&<div className="mt-6 space-y-5"><Panel title="Create purchase batch"><p className="mb-4 text-sm text-muted-foreground">Grouping items into a batch and submitting it <strong>reserves budget only — it does not place an order.</strong> A different teammate must authorize the batch before an order can be recorded.</p>{budget?<form action={submitPurchaseBatchAction} className="flex flex-wrap items-end gap-3"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="baselineId" value={String(baseline.id)}/><label className="grid gap-1 text-sm font-medium">Retailer<select name="retailerId" required className="rounded-md border bg-white px-3 py-2"><option value="">Select retailer</option>{retailers.map(r=><option key={String(r.id)} value={String(r.id)}>{String(r.name)}</option>)}</select></label><button className="rounded-md bg-amber-700 px-4 py-2.5 text-white">Submit batch for authorization</button></form>:<p className="text-sm text-amber-700">Set up a budget first before creating purchase batches.</p>}</Panel>{batches.length===0?<Panel title="Purchase batches"><p className="rounded-lg bg-stone-50 p-8 text-center text-muted-foreground">No purchase batches yet. Confirm offers and submit a batch above.</p></Panel>:<Panel title="Purchase batches"><div className="space-y-3">{batches.map(b=><div key={String(b.id)} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{String((b.furnishing_retailers as Row|undefined)?.name??"Retailer")} · {money(b.total_minor,String(b.currency))}</p><p className="text-xs text-muted-foreground">{(b.furnishing_purchase_batch_lines as Row[]|undefined)?.length??0} items · {title(b.status)}</p></div>{b.status==="submitted"?<form action={authorizePurchaseBatchAction}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="batchId" value={String(b.id)}/><button className="rounded-md border border-emerald-700 px-3 py-2 text-sm font-medium text-emerald-800">Authorize batch</button></form>:b.status==="authorized"?<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-800">Ready to record order</span>:null}</div></div>)}</div></Panel>}</div>}
 {view==="orders"&&<div className="mt-6 space-y-5"><Panel title="Record an order"><p className="mb-4 text-sm text-muted-foreground">Luxe Haven does not place retailer orders automatically. This records an order you or your team placed directly with the retailer, against an authorized batch.</p>{batches.filter(b=>b.status==="authorized").length===0?<p className="text-sm text-muted-foreground">No authorized batches yet — authorize a purchase batch first.</p>:<div className="space-y-4">{batches.filter(b=>b.status==="authorized").map(b=><form key={String(b.id)} action={recordExternalOrderAction} className="flex flex-wrap items-end gap-3 rounded-lg border p-4"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="batchId" value={String(b.id)}/><span className="text-sm font-medium">{String((b.furnishing_retailers as Row|undefined)?.name??"Retailer")} · {money(b.total_minor,String(b.currency))}</span><label className="grid gap-1 text-xs font-medium">Order confirmation #<input name="externalOrderId" required className="rounded-md border bg-white px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-medium">Order date<input name="orderDate" type="date" className="rounded-md border bg-white px-3 py-2 text-sm"/></label><button className="rounded-md bg-amber-700 px-4 py-2.5 text-sm text-white">Record external order</button></form>)}</div>}</Panel>{orders.length===0?<Panel title="Orders & deliveries"><p className="rounded-lg bg-stone-50 p-8 text-center text-muted-foreground">No retailer orders have been recorded yet.</p></Panel>:<Panel title="Orders & deliveries"><div>{orders.map(o=><div key={String(o.id)} className="flex justify-between border-b py-3 last:border-0"><span>{String(o.vendor)} · {String(o.po_number)} · External order recorded outside Luxe Haven</span><span className="text-sm text-muted-foreground">{title(o.status)}</span></div>)}</div></Panel>}</div>}
 {view==="shipments"&&<ShipmentsPanel shipments={shipments} base={base}/>}
 {view==="receiving"&&<ReceivingPanel lines={lines} currency={currency} projectId={projectId}/>}
 {view==="returns"&&<EmptyOrList title="Returns & exceptions" empty="No current returns or procurement exceptions." rows={exceptions}/>}
 {view==="activity"&&<EmptyOrList title="Immutable activity" empty="No procurement events recorded." rows={events}/>}
 </div></main>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>}
function Attention({count,text}:{count:number;text:string}){return <div className="flex items-center gap-3 border-b py-3 last:border-0"><span className={`grid size-7 place-items-center rounded-full text-xs ${count?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800"}`}>{count}</span><span>{text}</span></div>}
function Rows({lines}:{lines:Row[]}){const rooms=new Map<string,{name:string;total:number;ready:number}>();for(const line of lines){const room=line.furnishing_rooms as Row|undefined,id=String(line.room_id),entry=rooms.get(id)??{name:String(room?.name??"Unassigned"),total:0,ready:0};entry.total++;if(["ready","authorized","ordered","fulfilled","reconciled","closed"].includes(String(line.status)))entry.ready++;rooms.set(id,entry)}return <div>{[...rooms.values()].map(x=><div key={x.name} className="flex justify-between border-b py-3 last:border-0"><span>{x.name}</span><span className="text-muted-foreground">{x.ready} / {x.total} ready</span></div>)}</div>}
function Field({name,label,defaultValue}:{name:string;label:string;defaultValue:string}){return <label className="grid gap-2 text-sm font-medium">{label}<input className="rounded-md border bg-white px-3 py-2" name={name} type="number" min="0" step="0.01" defaultValue={defaultValue} required/></label>}
function Summary({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b py-3 last:border-0"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
function EmptyOrList({title:heading,empty,rows}:{title:string;empty:string;rows:Row[]}){return <div className="mt-6"><Panel title={heading}>{rows.length===0?<p className="rounded-lg bg-stone-50 p-8 text-center text-muted-foreground">{empty}</p>:<div>{rows.map(x=><div key={String(x.id)} className="flex justify-between border-b py-3 last:border-0"><span>{title(x.event_type??x.internal_order_number??x.status??"Record")}</span><span className="text-sm text-muted-foreground">{title(x.status??x.event_type??"")}</span></div>)}</div>}</Panel></div>}
const shipmentStatusLabel:Record<string,string>={pending:"Pending",shipped:"Shipped",in_transit:"In Transit",out_for_delivery:"Out for Delivery",delivered:"Delivered",delayed:"Delayed",exception:"Delivery Exception"};
function ReceivingPanel({lines,currency,projectId}:{lines:Row[];currency:string;projectId:string}){
 const pending=lines.filter(x=>x.status==="ordered"||x.status==="partially_fulfilled"),received=lines.filter(x=>x.status==="fulfilled"||x.status==="reconciled"||x.status==="closed");
 return <div className="mt-6 space-y-5"><Panel title="Awaiting receiving"><p className="mb-4 text-sm text-muted-foreground">Record what actually arrived. A delivered shipment is not the same as an accepted item — record the received and accepted quantity separately, and note any damage.</p>{pending.length===0?<p className="rounded-lg bg-stone-50 p-8 text-center text-muted-foreground">Nothing is awaiting receiving right now.</p>:<div className="space-y-3">{pending.map(x=><form key={String(x.id)} action={recordReceivingAction} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-[1fr_auto_auto_auto_auto]"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="lineId" value={String(x.id)}/><div><p className="font-medium">{String(x.description)}</p><p className="text-xs text-muted-foreground">Ordered {String(x.procurement_quantity)} · {money(x.estimated_line_cost_minor,currency)}</p></div><label className="grid gap-1 text-xs font-medium">Received<input name="receivedQuantity" type="number" min="0" step="1" required defaultValue={String(x.procurement_quantity)} className="w-24 rounded-md border bg-white px-2 py-1.5"/></label><label className="grid gap-1 text-xs font-medium">Accepted<input name="acceptedQuantity" type="number" min="0" step="1" required defaultValue={String(x.procurement_quantity)} className="w-24 rounded-md border bg-white px-2 py-1.5"/></label><label className="grid gap-1 text-xs font-medium">Condition<select name="condition" className="rounded-md border bg-white px-2 py-1.5"><option value="good">Good</option><option value="damaged">Damaged</option><option value="missing_parts">Missing parts</option><option value="wrong_item">Wrong item</option><option value="other">Other</option></select></label><button className="h-fit self-end rounded-md bg-amber-700 px-3 py-1.5 text-sm text-white">Record</button></form>)}</div>}</Panel>{received.length>0?<Panel title="Received"><div>{received.map(x=><div key={String(x.id)} className="flex justify-between border-b py-3 last:border-0"><span>{String(x.description)}</span><span className="text-sm text-muted-foreground">Accepted {String(x.accepted_quantity)} of {String(x.received_quantity)} received</span></div>)}</div></Panel>:null}</div>;
}
function ShipmentsPanel({shipments,base}:{shipments:Row[];base:string}){
 const installationHref=base.replace(/\/procurement$/,"/installation");
 return <div className="mt-6"><Panel title="Shipping tracker">{shipments.length===0?<p className="rounded-lg bg-stone-50 p-8 text-center text-muted-foreground">No shipments recorded yet. Shipments appear here once a retailer order confirms carrier and tracking details.</p>:<div className="space-y-3">{shipments.map(s=>{const order=s.furnishing_procurement_orders as Row|undefined;return <div key={String(s.id)} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{String(order?.vendor??"Order")} {s.carrier?`· ${String(s.carrier)}`:""} {s.tracking_number?`· ${String(s.tracking_number)}`:""}</p><p className="text-xs text-muted-foreground">{s.estimated_delivery_at?`Estimated delivery ${new Date(String(s.estimated_delivery_at)).toLocaleDateString()}`:"No delivery estimate yet"}</p></div><span className={`rounded-full border px-3 py-1 text-xs font-medium ${s.status==="delivered"?"border-emerald-700 text-emerald-800":s.status==="delayed"||s.status==="exception"?"border-red-700 text-red-800":""}`}>{shipmentStatusLabel[String(s.status)]??title(s.status)}</span></div>{s.status==="delivered"?<p className="mt-3 rounded-md bg-amber-50 p-3 text-xs text-amber-800">Delivered does not mean accepted. Record received condition and quantity in <a className="font-semibold underline" href={installationHref}>Receiving</a> before this item is considered complete.</p>:null}</div>})}</div>}</Panel></div>;
}
