"use client";

import Link from "next/link";
import { useActionState } from "react";
import { approveProductRevisionAction, editFurnishingProductAction } from "@/app/actions/furnishing-catalog-governance";

type Product = { id:string; name:string; description:string|null; brand:string|null; category_id:string|null; color:string|null; material:string|null; finish:string|null; assembly_required:boolean; scope:string; workspace_id:string|null; status:string; revision:number };
type Version = { id:string; version:number; lifecycle_status:string; base_version:number|null; change_reason:string|null; created_at:string; product_snapshot?: Record<string, unknown> };
type Props = Readonly<{ product:Product; categories:{id:string;name:string;group_name:string|null}[]; usage:{packageItems:{id:string;requirement_key:string|null}[];designWorkspaces:{id:string;name:string}[];budgets:{id:string;status:string;currency:string|null;target_amount_minor:number|null}[];procurementItems:{id:string;status:string}[]};versions:Version[];editContextId?:string;approvalContextId?:string }>;
const input="mt-1 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-emerald-700";

function Result({state}:{state:{ok?:boolean;message?:string}}){return <p role="status" aria-live="polite" className={`min-h-5 text-sm ${state.ok===false?"text-red-700":"text-emerald-700"}`}>{state.message??""}</p>}

export function ProductEditWorkspace({product,categories,usage,versions,editContextId,approvalContextId}:Props){
  const [editState,editAction,editing]=useActionState(editFurnishingProductAction,{});
  const [approvalState,approvalAction,approving]=useActionState(approveProductRevisionAction,{});
  const proposal=versions.find((item)=>item.lifecycle_status==="proposed");
  const approved=product.status==="approved";
  const impactCount=usage.packageItems.length+usage.designWorkspaces.length+usage.budgets.length+usage.procurementItems.length;
  const changedFields=proposal?.product_snapshot?(["name","description","brand","category_id","color","material","finish","assembly_required"] as const).filter((key)=>String(proposal.product_snapshot?.[key]??"")!==String(product[key]??"")):[];
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><nav aria-label="Breadcrumb" className="text-sm text-stone-600"><Link href="/admin/furnishing">Furnishing Studio</Link> / <Link href={product.workspace_id?`/admin/furnishing/catalog?workspace=${product.workspace_id}`:"/admin/furnishing/products"}>{product.workspace_id?"Product Catalog":"Product Library"}</Link> / Edit</nav><h1 className="mt-2 text-3xl font-semibold text-stone-950">Edit {product.name}</h1><p className="mt-2 max-w-3xl text-stone-600">{approved?"Propose a governed revision. The approved product remains unchanged until a reviewer approves the proposal.":"Update the editable draft with optimistic version protection."}</p></div><Link className="rounded-xl border px-4 py-2 text-sm font-semibold" href={product.workspace_id?`/admin/furnishing/catalog/${product.id}?workspace=${product.workspace_id}`:`/admin/furnishing/products/${product.id}`}>Back to product</Link></header>
    <section aria-labelledby="impact-heading" className="rounded-2xl bg-amber-50 p-5"><h2 id="impact-heading" className="font-semibold text-amber-950">Usage impact · {impactCount} linked records</h2><p className="mt-1 text-sm text-amber-900">Historical snapshots will not be rewritten. A newly approved revision affects only workflows that resolve the current catalog version.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><dt>Room packages</dt><dd className="font-semibold">{usage.packageItems.length}</dd></div><div><dt>Design workspaces</dt><dd className="font-semibold">{usage.designWorkspaces.length}</dd></div><div><dt>Budgets</dt><dd className="font-semibold">{usage.budgets.length}</dd></div><div><dt>Procurement</dt><dd className="font-semibold">{usage.procurementItems.length}</dd></div></dl>{usage.designWorkspaces.length?<ul className="mt-3 text-sm">{usage.designWorkspaces.map((item)=><li key={item.id}>{item.name}</li>)}</ul>:null}</section>
    {proposal?<section className="rounded-2xl border border-emerald-200 p-5"><h2 className="text-xl font-semibold">Revision {proposal.version} awaiting review</h2><p className="mt-1 text-sm text-stone-600">Reason: {proposal.change_reason}. Approved revision {product.revision} remains live.</p><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{changedFields.map((key)=><div key={key} className="rounded-xl bg-stone-50 p-3"><dt className="font-semibold capitalize">{key.replaceAll("_"," ")}</dt><dd><span className="text-stone-500 line-through">{String(product[key]??"Not set")}</span><span className="ml-2 text-emerald-800">→ {String(proposal.product_snapshot?.[key]??"Not set")}</span></dd></div>)}</dl><form action={approvalAction} className="mt-4 space-y-3"><input type="hidden" name="commandContextId" value={approvalContextId??""}/><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="proposalId" value={proposal.id}/><input type="hidden" name="revision" value={product.revision}/><label className="block text-sm font-medium">Review decision reason<input name="reason" required minLength={3} className={input}/></label><button disabled={approving} className="min-h-11 rounded-xl bg-emerald-800 px-4 py-2 font-semibold text-white disabled:opacity-50">{approving?"Approving…":"Approve new version"}</button><Result state={approvalState}/></form></section>:null}
    <form action={editAction} className="space-y-5 rounded-2xl border border-stone-200 p-5"><input type="hidden" name="commandContextId" value={editContextId??""}/><input type="hidden" name="productId" value={product.id}/><input type="hidden" name="revision" value={product.revision}/><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Product name<input name="name" required defaultValue={product.name} className={input}/></label><label className="text-sm font-medium">Brand<input name="brand" defaultValue={product.brand??""} className={input}/></label><label className="text-sm font-medium">Category<select name="categoryId" defaultValue={product.category_id??""} className={input}><option value="">No category</option>{categories.map((category)=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="text-sm font-medium">Color<input name="color" defaultValue={product.color??""} className={input}/></label><label className="text-sm font-medium">Material<input name="material" defaultValue={product.material??""} className={input}/></label><label className="text-sm font-medium">Finish<input name="finish" defaultValue={product.finish??""} className={input}/></label></div><label className="block text-sm font-medium">Description<textarea name="description" defaultValue={product.description??""} rows={4} className={input}/></label><label className="flex min-h-11 items-center gap-3 text-sm font-medium"><input type="checkbox" name="assemblyRequired" defaultChecked={product.assembly_required}/>Assembly required</label>{approved?<label className="block text-sm font-medium">Revision reason<input name="reason" required minLength={3} className={input}/></label>:null}<button disabled={editing||Boolean(proposal)} title={proposal?"Review the open revision before proposing another.":undefined} className="min-h-11 rounded-xl bg-emerald-800 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{editing?"Saving…":approved?"Propose revision":"Save draft"}</button>{proposal?<p className="text-sm text-stone-600">A product can have only one open revision. Approve the current proposal before editing again.</p>:null}<Result state={editState}/></form>
    <section><h2 className="text-xl font-semibold">Version history</h2>{versions.length?<ol className="mt-3 space-y-2">{versions.map((version)=><li key={version.id} className="rounded-xl bg-stone-50 p-3 text-sm"><strong>Version {version.version}</strong> · {version.lifecycle_status.replaceAll("_"," ")}<span className="block text-stone-600">{version.change_reason??"No reason recorded"}</span></li>)}</ol>:<p className="mt-2 text-sm text-stone-600">No earlier version evidence exists. The first governed edit will create it.</p>}</section>
  </div>;
}
