"use server";

import { revalidatePath } from "next/cache";
import { buildDecisionExecutionPlan } from "@/features/portfolio-intelligence";
import type { ActionPlanProps, ExecuteCommandResult, ProposedPlanAction } from "@/platform/actions";
import { composeExecuteRuntime } from "./execute-runtime";

type RouteFailure=Readonly<{ok:false;code:"UNAUTHENTICATED"|"WORKSPACE_UNAVAILABLE"|"DEPENDENCY_UNAVAILABLE"|"VALIDATION_FAILED";message:string;retryable:boolean;submittedInput?:unknown}>;
type RouteResult<T>=ExecuteCommandResult<T>|RouteFailure;

export async function listExecutePlansAction(input:Readonly<{workspaceId?:string}>={}):Promise<RouteResult<readonly ActionPlanProps[]>>{const runtime=await composeExecuteRuntime(text(input.workspaceId));if(!runtime.ok)return runtimeFailure(runtime);return runtime.runtime.service.listPlans(runtime.runtime.workspaceId,runtime.runtime.actor);}
export async function getExecutePlanAction(input:Readonly<{planId:string;workspaceId?:string}>):Promise<RouteResult<ActionPlanProps>>{const planId=text(input.planId);if(!planId)return invalid("Plan ID is required.",input);const runtime=await composeExecuteRuntime(text(input.workspaceId));if(!runtime.ok)return runtimeFailure(runtime);return runtime.runtime.service.getPlan(runtime.runtime.workspaceId,planId,runtime.runtime.actor);}
export async function createManualExecutePlanAction(input:Readonly<{title:string;description?:string;scopeType:ActionPlanProps["scope"]["type"];propertyIds:readonly string[];priority:ActionPlanProps["priority"]}>):Promise<RouteResult<ActionPlanProps>>{const title=text(input.title);if(!title)return invalid("Plan title is required.",input);const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.createManualDraft({id:`plan-${crypto.randomUUID()}`,workspaceId:runtime.runtime.workspaceId,title,...(text(input.description)?{description:text(input.description)!}:{}),scope:{type:input.scopeType,propertyIds:input.propertyIds},owner:runtime.runtime.actor,priority:input.priority,actor:runtime.runtime.actor,occurredAt:new Date()});refresh(result);return result;}
export async function createExecutePlanFromDecisionAction(input:Readonly<{decisionId:string}>):Promise<RouteResult<ActionPlanProps>>{const decisionId=text(input.decisionId);if(!decisionId)return invalid("Decision ID is required.",input);const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);try{const decision=await runtime.runtime.decisions.get(runtime.runtime.workspaceId,decisionId);if(!decision||decision.status!=="approved")return invalid("Only an approved decision can create an Action Plan.",input);const canonicalDecisionId=decision.canonicalDecisionId??decision.decisionId,planId=`plan-${canonicalDecisionId}`,existing=await runtime.runtime.service.getPlan(runtime.runtime.workspaceId,planId,runtime.runtime.actor);if(existing.ok)return existing;if(existing.code!=="PLAN_NOT_FOUND")return existing;const execution=buildDecisionExecutionPlan(decision);const result=await runtime.runtime.service.createFromDecision({id:planId,workspaceId:runtime.runtime.workspaceId,decision:{id:canonicalDecisionId,title:decision.question,summary:decision.rationale,capability:"portfolio",propertyIds:decision.affectedPropertyIds,priority:"high",expectedOutcome:decision.expectedOutcomes[0]?.metric,successMetrics:decision.expectedOutcomes.map((outcome)=>outcome.metric),rationale:decision.rationale,approvedBy:{type:"user",id:decision.decidedByProfileId??decision.ownerProfileId},approvedAt:new Date(decision.decidedAt??decision.updatedAt)},owner:{type:"user",id:decision.ownerProfileId},proposedActions:execution.actions.map((action,position)=>({id:action.id,position,title:action.title,actionType:action.type,priority:"high",owner:{type:"user",id:decision.ownerProfileId},...(decision.affectedPropertyIds.length===1?{propertyId:decision.affectedPropertyIds[0]}:{})})),actor:runtime.runtime.actor});refresh(result,planId);return result;}catch{return{ok:false,code:"DEPENDENCY_UNAVAILABLE",message:"The approved decision could not be loaded. No plan was created.",retryable:true,submittedInput:input};}}
export async function updateExecutePlanAction(input:Readonly<{planId:string;expectedVersion:number;title?:string;description?:string;priority?:ActionPlanProps["priority"];expectedOutcome?:string;successMetrics?:readonly string[]}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.updateDraft({workspaceId:runtime.runtime.workspaceId,planId:input.planId,expectedVersion:input.expectedVersion,actor:runtime.runtime.actor,changes:{expectedVersion:input.expectedVersion,...(input.title!==undefined?{title:input.title}:{}),...(input.description!==undefined?{description:input.description}:{}),...(input.priority?{priority:input.priority}:{}),...(input.expectedOutcome!==undefined?{expectedOutcome:input.expectedOutcome}:{}),...(input.successMetrics?{successMetrics:input.successMetrics}:{})}});refresh(result,input.planId);return result;}
export async function addExecuteDraftAction(input:Readonly<{planId:string;expectedVersion:number;action:Omit<ProposedPlanAction,"id"|"position">;correlationId?:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.addDraftAction({workspaceId:runtime.runtime.workspaceId,planId:input.planId,expectedVersion:input.expectedVersion,actor:runtime.runtime.actor,input:input.action,...(input.correlationId?{correlationId:input.correlationId}:{})});refresh(result,input.planId);return result;}
export async function updateExecuteDraftAction(input:Readonly<{planId:string;actionId:string;expectedVersion:number;changes:Partial<Omit<ProposedPlanAction,"id"|"position">>;correlationId?:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.updateDraftAction({workspaceId:runtime.runtime.workspaceId,planId:input.planId,actionId:input.actionId,expectedVersion:input.expectedVersion,actor:runtime.runtime.actor,changes:input.changes,...(input.correlationId?{correlationId:input.correlationId}:{})});refresh(result,input.planId);return result;}
export async function removeExecuteDraftAction(input:Readonly<{planId:string;actionId:string;expectedVersion:number;correlationId?:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.removeDraftAction({workspaceId:runtime.runtime.workspaceId,planId:input.planId,actionId:input.actionId,expectedVersion:input.expectedVersion,actor:runtime.runtime.actor,...(input.correlationId?{correlationId:input.correlationId}:{})});refresh(result,input.planId);return result;}
export async function reorderExecuteDraftActions(input:Readonly<{planId:string;expectedVersion:number;orderedActionIds:readonly string[];correlationId?:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.reorderDraftActions({workspaceId:runtime.runtime.workspaceId,planId:input.planId,expectedVersion:input.expectedVersion,orderedActionIds:input.orderedActionIds,actor:runtime.runtime.actor,...(input.correlationId?{correlationId:input.correlationId}:{})});refresh(result,input.planId);return result;}
export async function activateExecutePlanAction(input:Readonly<{planId:string;expectedVersion:number;acknowledgeUnassigned?:boolean;correlationId:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.activate({workspaceId:runtime.runtime.workspaceId,planId:input.planId,expectedVersion:input.expectedVersion,actor:runtime.runtime.actor,occurredAt:new Date(),correlationId:input.correlationId,acknowledgeUnassigned:input.acknowledgeUnassigned});refresh(result,input.planId);return result;}
export async function completeExecutePlanAction(input:Readonly<{planId:string;expectedVersion:number}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.completePlan(runtime.runtime.workspaceId,input.planId,input.expectedVersion,runtime.runtime.actor,new Date());refresh(result,input.planId);return result;}
export async function cancelExecutePlanAction(input:Readonly<{planId:string;expectedVersion:number;reason:string}>):Promise<RouteResult<ActionPlanProps>>{const runtime=await composeExecuteRuntime();if(!runtime.ok)return runtimeFailure(runtime);const result=await runtime.runtime.service.cancelPlan(runtime.runtime.workspaceId,input.planId,input.expectedVersion,runtime.runtime.actor,new Date(),input.reason);refresh(result,input.planId);return result;}
export async function getExecutePlanHistoryAction(input:Readonly<{planId:string;workspaceId?:string}>){const runtime=await composeExecuteRuntime(text(input.workspaceId));if(!runtime.ok)return runtimeFailure(runtime);return runtime.runtime.service.history(runtime.runtime.workspaceId,input.planId,runtime.runtime.actor);}

function refresh<T>(result:RouteResult<T>,planId?:string){if(!result.ok)return;revalidatePath("/dashboard/execute");revalidatePath("/dashboard/actions");if(planId)revalidatePath(`/dashboard/execute/plans/${encodeURIComponent(planId)}`);}
function text(value:string|undefined){const clean=value?.trim();return clean||undefined;}function invalid(message:string,submittedInput:unknown):RouteFailure{return{ok:false,code:"VALIDATION_FAILED",message,retryable:false,submittedInput};}function runtimeFailure(result:Exclude<Awaited<ReturnType<typeof composeExecuteRuntime>>,Readonly<{ok:true}>>):RouteFailure{return{ok:false,code:result.code,message:result.message,retryable:result.code==="DEPENDENCY_UNAVAILABLE"};}
