"use server";
import"server-only";import{createAdminClient}from"@/lib/supabase/admin";import{getSessionProfile}from"@/lib/auth/session";import{evaluateWorkspacePermission,resolveWorkspaceAccessContext,SupabaseTeamAccessRepository}from"@/features/workspace";import{buildGuestRelationshipSummary,createGuestTimelineAggregate,type GuestTimelineCategory,type GuestTimelineEvent}from"@/features/guest-communications";
export async function getGuestRelationshipTimeline(input:{guestId:string;workspaceId?:string;categories?:string[];query?:string;eventType?:string;reservationId?:string;propertyId?:string;dateFrom?:string;dateTo?:string;order?:"newest"|"oldest";page?:number}){
 try{
  const{user}=await getSessionProfile();if(!user)return{ok:false as const,code:"permission_denied"};
  const admin=createAdminClient(),{data:guest}=await admin.from("guests").select("id,owner_id,display_name,language,last_observed_at,created_at").eq("id",input.guestId).maybeSingle();if(!guest)return{ok:false as const,code:"guest_not_found"};
  const access=await resolveWorkspaceAccessContext(new SupabaseTeamAccessRepository(),user.id,input.workspaceId??String(guest.owner_id));if(access.workspaceId!==guest.owner_id||!evaluateWorkspacePermission(access,"communications.view"))return{ok:false as const,code:"permission_denied"};
  const page=Math.max(1,input.page??1),pageSize=50,from=(page-1)*pageSize,ascending=input.order==="oldest";
  let query=admin.from("guest_relationship_events").select("*",{count:"exact"}).eq("workspace_id",access.workspaceId).eq("guest_id",input.guestId);
  if(input.categories?.length)query=query.in("category",input.categories);if(input.eventType)query=query.eq("event_type",input.eventType);if(input.reservationId)query=query.eq("reservation_id",input.reservationId);if(input.propertyId)query=query.eq("property_id",input.propertyId);if(input.dateFrom)query=query.gte("occurred_at",input.dateFrom);if(input.dateTo)query=query.lte("occurred_at",input.dateTo);if(input.query?.trim()){const safe=input.query.trim().replace(/[^\p{L}\p{N}\s._-]/gu," ");query=query.or(`summary.ilike.%${safe}%,event_type.ilike.%${safe}%,reservation_id.ilike.%${safe}%`);}
  query=query.order("occurred_at",{ascending}).order("sequence",{ascending}).range(from,from+pageSize-1);
  const[{data,error,count},{data:summaryRows},{data:properties},{data:connection}]=await Promise.all([query,admin.from("guest_relationship_events").select("*").eq("workspace_id",access.workspaceId).eq("guest_id",input.guestId).order("occurred_at").order("sequence").limit(10_000),admin.from("properties").select("id,name").eq("owner_id",access.ownerId),admin.from("integration_connections").select("status,last_successful_sync_at,last_failed_sync_at").eq("workspace_id",access.workspaceId).order("updated_at",{ascending:false}).limit(1).maybeSingle()]);
  if(error)throw error;const events=(data??[]).map(mapTimelineEvent),allEvents=(summaryRows??[]).map(mapTimelineEvent),aggregate=createGuestTimelineAggregate({workspaceId:access.workspaceId,guestId:input.guestId,events:allEvents}),summary=buildGuestRelationshipSummary(allEvents);
  return{ok:true as const,guest:{id:guest.id,name:guest.display_name,language:guest.language},events,summary,timeline:{firstEventAt:aggregate.firstEventAt,latestEventAt:aggregate.latestEventAt,eventCount:count??aggregate.eventCount,lastUpdatedAt:aggregate.lastUpdatedAt},page,pageSize,total:count??0,hasMore:from+events.length<(count??0),properties:properties??[],freshness:{generatedAt:new Date().toISOString(),lastProviderSyncAt:connection?.last_successful_sync_at??null,lastProviderFailureAt:connection?.last_failed_sync_at??null,providerStatus:connection?.status??"unavailable",eventCoverage:(count??0)>=10_000?"partially-available":"complete"}};
 }catch(error){console.error("guest_relationship_timeline_failed",{errorType:error instanceof Error?error.name:"unknown"});return{ok:false as const,code:"timeline_unavailable"};}
}
function mapTimelineEvent(row:Record<string,unknown>):GuestTimelineEvent{return{id:String(row.id),sequence:Number(row.sequence),workspaceId:String(row.workspace_id),guestId:String(row.guest_id),occurredAt:String(row.occurred_at),recordedAt:String(row.recorded_at),eventType:String(row.event_type),category:String(row.category)as GuestTimelineCategory,visibility:String(row.visibility)as GuestTimelineEvent["visibility"],summary:String(row.summary),actor:{type:String(row.actor_type)as GuestTimelineEvent["actor"]["type"],...(row.actor_id?{id:String(row.actor_id)}:{}),...(row.actor_display_name?{displayName:String(row.actor_display_name)}:{})},...(row.reservation_id?{reservationId:String(row.reservation_id)}:{}),...(row.booking_id?{bookingId:String(row.booking_id)}:{}),...(row.property_id?{propertyId:String(row.property_id)}:{}),...(row.conversation_id?{conversationId:String(row.conversation_id)}:{}),...(row.message_id?{messageId:String(row.message_id)}:{}),source:{type:String(row.source_type),id:String(row.source_id),...(row.source_version?{version:String(row.source_version)}:{})},metadata:(row.metadata&&typeof row.metadata==="object"?row.metadata:{})as Record<string,unknown>};}
