"use server";import"server-only";import{redirect}from"next/navigation";import{revalidatePath}from"next/cache";import{requireRole}from"@/lib/auth/session";import{createAdminClient}from"@/lib/supabase/admin";import{cancelCreationJob,createCreationJob,reviewCreationFact,restoreCreationRevision,uploadCreationSource}from"@/features/guidebook-creation-assistant/application";import{creationContextFromJob,creationDependencies,enqueueCreationWork,hasCreationEntitlement,readCreationCapability}from"@/features/guidebook-creation-assistant/runtime";
const base="/admin/guidebooks/creation-assistant";
async function admin(){return requireRole(["admin"])}
async function context(workspaceId:string,propertyId:string){const{user,profile}=await admin();return{actorId:user.id,actorRole:profile?.role??"admin",workspaceId,propertyId,permissions:new Set(["guidebooks.manage"]),entitled:await hasCreationEntitlement(workspaceId,propertyId),correlationId:crypto.randomUUID()}}
async function assertInternal(workspaceId:string,propertyId:string,actorId:string){const capability=await readCreationCapability({workspaceId,propertyId,actorId});if(!capability.internalAvailable)throw new Error("CREATION_ASSISTANT_NOT_READY")}
export async function createAssistantJobAction(form:FormData){const workspaceId=String(form.get("workspaceId")??""),propertyId=String(form.get("propertyId")??""),templateVersionId=String(form.get("templateVersionId")??""),ctx=await context(workspaceId,propertyId);await assertInternal(workspaceId,propertyId,ctx.actorId);const{job}=await createCreationJob(creationDependencies(),ctx,{idempotencyKey:String(form.get("idempotencyKey")??crypto.randomUUID()),templateVersionId});redirect(`${base}?workspace=${workspaceId}&property=${propertyId}&job=${job.id}`)}
export async function uploadAssistantSourceAction(form:FormData){const jobId=String(form.get("jobId")??""),file=form.get("file");if(!(file instanceof File))throw new Error("CREATION_SOURCE_REQUIRED");const ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);const bytes=new Uint8Array(await file.arrayBuffer()),digest=await crypto.subtle.digest("SHA-256",bytes),hash=Array.from(new Uint8Array(digest),v=>v.toString(16).padStart(2,"0")).join("");await uploadCreationSource(creationDependencies(),ctx,{jobId,filename:file.name,mediaType:file.type,bytes,integritySha256:hash});revalidatePath(base)}
export async function enqueueAssistantExtractionAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);await enqueueCreationWork({jobId,workspaceId:ctx.workspaceId,stage:"extraction",idempotencyKey:String(form.get("idempotencyKey")??crypto.randomUUID())});revalidatePath(base)}
export async function reviewAssistantFactAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);await reviewCreationFact(creationDependencies(),ctx,{jobId,factId:String(form.get("factId")??""),status:String(form.get("decision"))==="rejected"?"rejected":"confirmed",correctedValue:String(form.get("correctedValue")??"")||undefined,confirmHighRisk:form.get("confirmHighRisk")==="true"});revalidatePath(base)}
export async function enqueueAssistantGenerationAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);await enqueueCreationWork({jobId,workspaceId:ctx.workspaceId,stage:"generation",idempotencyKey:String(form.get("idempotencyKey")??crypto.randomUUID()),payload:{title:String(form.get("title")??"Guest Guide")}});revalidatePath(base)}
export async function enqueueAssistantRegenerationAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);await enqueueCreationWork({jobId,workspaceId:ctx.workspaceId,stage:"section_regeneration",idempotencyKey:String(form.get("idempotencyKey")??crypto.randomUUID()),payload:{sectionId:String(form.get("sectionId")??""),expectedRevision:Number(form.get("expectedRevision"))}});revalidatePath(base)}
export async function restoreAssistantRevisionAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await assertInternal(ctx.workspaceId,ctx.propertyId,ctx.actorId);await restoreCreationRevision(creationDependencies(),ctx,{jobId,sourceRevision:Number(form.get("sourceRevision")),expectedRevision:Number(form.get("expectedRevision"))});revalidatePath(base)}
export async function cancelAssistantJobAction(form:FormData){const jobId=String(form.get("jobId")??""),ctx=await creationContextFromJob(jobId);await admin();await cancelCreationJob(creationDependencies(),ctx,jobId);revalidatePath(base)}
export async function getAssistantInternalProjection(jobId:string){await admin();const db=createAdminClient(),{data:job}=await db.from("guidebook_creation_jobs").select("*").eq("id",jobId).maybeSingle();if(!job)return null;const[{data:sources},{data:facts},{data:work},{data:artifacts}]=await Promise.all([db.from("guidebook_creation_sources").select("id,original_filename,source_type,extraction_status,byte_size").eq("job_id",jobId),db.from("guidebook_creation_facts").select("id,category,field_key,display_value,source_location,confidence,review_status,high_risk").eq("job_id",jobId),db.from("guidebook_creation_work_items").select("id,stage,status,attempts,safe_failure_code").eq("job_id",jobId).order("created_at",{ascending:false}),db.from("guidebook_creation_artifacts").select("id,draft_revision,artifact_type,section_id,based_on_revision").eq("job_id",jobId).order("created_at",{ascending:false})]);return{job,sources:sources??[],facts:facts??[],work:work??[],artifacts:artifacts??[]}}
