"use server";
import"server-only";
import{redirect}from"next/navigation";
import{revalidatePath}from"next/cache";
import{createAdminClient}from"@/lib/supabase/admin";
import{getSessionProfile}from"@/lib/auth/session";
import{evaluatePropertyAccess,evaluateWorkspacePermission,resolveWorkspaceAccessContext,SupabaseTeamAccessRepository}from"@/features/workspace";
import{getCommerceAccessWorkspace}from"./commerce-access";

async function context(workspaceId?:string,permission:"guidebooks.view"|"guidebooks.manage"="guidebooks.view"){const{user}=await getSessionProfile();if(!user)throw new Error("permission_denied");const access=await resolveWorkspaceAccessContext(new SupabaseTeamAccessRepository(),user.id,workspaceId);if(!evaluateWorkspacePermission(access,permission))throw new Error("permission_denied");return{user,access}}
async function entitlements(){const access=await getCommerceAccessWorkspace();const available=(key:string)=>access?.entitlements.some(item=>item.key===key&&item.status==="available")??false;return{create:available("guidebooks.create"),publish:available("guidebooks.publish"),host:available("guidebooks.host")}}
export async function getGuidebookStudioRequest(workspaceId?:string){try{const{access}=await context(workspaceId),admin=createAdminClient(),[{data:guidebooks},{data:properties},rights]=await Promise.all([admin.from("guidebooks").select("*").eq("workspace_id",access.workspaceId).order("updated_at",{ascending:false}),admin.from("properties").select("id,name,status,featured_image").eq("owner_id",access.ownerId).order("name"),entitlements()]);return{ok:true as const,workspaceId:access.workspaceId,guidebooks:(guidebooks??[]).filter((g:{property_id:string})=>evaluatePropertyAccess(access,g.property_id)),properties:(properties??[]).filter((p:{id:string})=>evaluatePropertyAccess(access,p.id)),entitlements:rights}}catch(error){return{ok:false as const,code:error instanceof Error?error.message:"unexpected"}}}
export async function createGuidebookAction(formData:FormData){const workspaceId=String(formData.get("workspaceId")??""),propertyId=String(formData.get("propertyId")??""),title=String(formData.get("title")??"").trim();const{user,access}=await context(workspaceId,"guidebooks.manage");if(!evaluatePropertyAccess(access,propertyId))throw new Error("permission_denied");const rights=await entitlements();if(!rights.create)throw new Error("entitlement_required");const admin=createAdminClient(),id=crypto.randomUUID(),now=new Date().toISOString(),slug=crypto.randomUUID().replaceAll("-","");const{error}=await admin.from("guidebooks").insert({id,workspace_id:access.workspaceId,property_id:propertyId,title:title||"Guest Guide",description:"Everything guests need for an effortless stay.",status:"draft",public_slug:slug,created_at:now,updated_at:now});if(error)throw error;const defaults=["Welcome","Arrival","Parking","Check-in","Wi-Fi","Property Guide","Amenities","House Rules","Neighborhood","Restaurants","Things To Do","Transportation","Emergency","Checkout"];await admin.from("guidebook_sections").insert(defaults.map((name,position)=>({guidebook_id:id,section_key:name.toLowerCase().replaceAll(" ","-"),title:name,position,visible:true})));await admin.from("guidebook_activity").insert({guidebook_id:id,event_type:"guidebook-created",actor_profile_id:user.id,safe_summary:"Guidebook draft created."});redirect(`/dashboard/guidebooks/${id}`)}
export async function getGuidebookEditorRequest(id:string){try{const admin=createAdminClient(),{data:guidebook}=await admin.from("guidebooks").select("*").eq("id",id).maybeSingle();if(!guidebook)return{ok:false as const,code:"guidebook_not_found"};const{access}=await context(guidebook.workspace_id);if(!evaluatePropertyAccess(access,guidebook.property_id))return{ok:false as const,code:"permission_denied"};const[{data:property},{data:sections},{data:recommendations},{data:versions},{data:analytics},rights]=await Promise.all([admin.from("properties").select("id,name,address,address_line_1,address_line_2,city,state,postal_code,latitude,longitude,check_in_time,check_out_time,amenities,house_rules,featured_image,updated_at").eq("id",guidebook.property_id).single(),admin.from("guidebook_sections").select("*,guidebook_blocks(*)").eq("guidebook_id",id).order("position"),admin.from("guidebook_recommendations").select("*").eq("guidebook_id",id).order("position"),admin.from("guidebook_versions").select("id,version,status,published_at,created_at").eq("guidebook_id",id).order("version",{ascending:false}),admin.from("guidebook_analytics").select("event_type,section_key,occurred_at,visitor_hash").eq("guidebook_id",id).limit(5000),entitlements()]);return{ok:true as const,guidebook,property,sections:sections??[],recommendations:recommendations??[],versions:versions??[],analytics:analytics??[],entitlements:rights}}catch(error){return{ok:false as const,code:error instanceof Error?error.message:"unexpected"}}}
export async function addGuidebookBlockAction(formData:FormData){const guidebookId=String(formData.get("guidebookId")??""),sectionId=String(formData.get("sectionId")??""),text=String(formData.get("text")??"").trim(),blockType=String(formData.get("blockType")??"rich-text");const editor=await getGuidebookEditorRequest(guidebookId);if(!editor.ok)throw new Error(editor.code);await context(editor.guidebook.workspace_id,"guidebooks.manage");if(!text)throw new Error("guidebook_invalid");const section=editor.sections.find((item:{id:string})=>item.id===sectionId);if(!section)throw new Error("guidebook_invalid");const position=Array.isArray(section.guidebook_blocks)?section.guidebook_blocks.length:0,content=blockType==="heading"?{text}:blockType==="callout"?{text,tone:"information"}:{markdown:text};const admin=createAdminClient(),{error}=await admin.from("guidebook_blocks").insert({section_id:sectionId,block_type:blockType,position,content,guest_safe:true});if(error)throw error;await admin.from("guidebooks").update({updated_at:new Date().toISOString(),revision:editor.guidebook.revision+1}).eq("id",guidebookId).eq("revision",editor.guidebook.revision);revalidatePath(`/dashboard/guidebooks/${guidebookId}`)}
export async function publishGuidebookAction(formData:FormData){const id=String(formData.get("guidebookId")??""),expectedRevision=Number(formData.get("revision")),editor=await getGuidebookEditorRequest(id);if(!editor.ok)throw new Error(editor.code);const{user}=await context(editor.guidebook.workspace_id,"guidebooks.manage");if(!editor.entitlements.publish||!editor.entitlements.host)throw new Error("entitlement_required");if(editor.guidebook.revision!==expectedRevision)throw new Error("revision_conflict");const sections=editor.sections.filter((s:{visible:boolean})=>s.visible),hasContent=sections.some((s:{guidebook_blocks:unknown[]})=>s.guidebook_blocks?.length);if(!hasContent)throw new Error("publication_invalid");const now=new Date().toISOString(),property=editor.property as Record<string,unknown>,snapshot={title:editor.guidebook.title,description:editor.guidebook.description,brand:editor.guidebook.brand,sections,recommendations:editor.recommendations,property:{propertyId:property.id,name:property.name,address:property.address_line_1??property.address??"",city:property.city,state:property.state,checkInTime:property.check_in_time,checkoutTime:property.check_out_time,amenities:property.amenities??[],houseRules:property.house_rules??[],latitude:property.latitude,longitude:property.longitude,sourceUpdatedAt:property.updated_at}};const admin=createAdminClient(),{error}=await admin.rpc("publish_guidebook_version",{p_guidebook_id:id,p_expected_revision:expectedRevision,p_snapshot:snapshot,p_published_by:user.id,p_published_at:now});if(error)throw new Error(error.message);revalidatePath(`/dashboard/guidebooks/${id}`);revalidatePath(`/g/${editor.guidebook.public_slug}`)}
export async function getPublishedGuidebookRequest(slug:string,source:"link"|"qr"="link"){const admin=createAdminClient(),{data:guidebook}=await admin.from("guidebooks").select("id,title,description,public_slug,published_version,status,brand").eq("public_slug",slug).eq("status","published").maybeSingle();if(!guidebook||!guidebook.published_version)return null;const{data:version}=await admin.from("guidebook_versions").select("version,snapshot,published_at").eq("guidebook_id",guidebook.id).eq("version",guidebook.published_version).eq("status","published").maybeSingle();if(!version)return null;await admin.from("guidebook_analytics").insert({guidebook_id:guidebook.id,version:version.version,event_type:source==="qr"?"qr-scan":"view",metadata:{source}});return{...version.snapshot as Record<string,unknown>,publicSlug:slug,version:version.version,publishedAt:version.published_at}}
