"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { addOpportunityNote, archiveInvestmentOpportunity, buildOpportunityAnalysisSnapshotFromWorkspace, buildOpportunityPropertyReference, buildOpportunitySourceSummary, createInvestmentOpportunity, createInvestmentOpportunityId, InvestmentOpportunityError, listCompatibleInvestmentOpportunities, restoreInvestmentOpportunity, saveOpportunityAnalysis, updateInvestmentOpportunity, updateOpportunityStatus, type OpportunityStatus } from "@/features/investment-opportunity";
import { getInvestmentOpportunityRequestContext } from "./investment-opportunity-runtime";
import { resolveInvestmentAnalysis } from "./investment-analysis-save-store";

export type OpportunityMutationResult<T> = Readonly<{ ok: true; data: T }> | Readonly<{ ok: false; code: string; message: string; fieldErrors?: Readonly<Record<string, readonly string[]>>; currentVersion?: number }>;
type WorkflowFailure = Extract<OpportunityMutationResult<never>, { ok: false }>;
const saveSchema = z.object({ analysisToken: z.string().min(1), name: z.string().trim().max(120).optional(), tags: z.array(z.string().max(40)).max(20), idempotencyKey: z.string().min(8).max(160), note: z.string().trim().max(5000).optional() });
const existingSchema = saveSchema.pick({ analysisToken: true, idempotencyKey: true }).extend({ opportunityId: z.string().min(1), expectedVersion: z.number().int().positive() });
const mutationSchema = z.object({ opportunityId: z.string().min(1), expectedVersion: z.number().int().positive(), commandId: z.string().min(8).max(160) });

export async function saveAnalysisAsNewOpportunityAction(input: unknown): Promise<OpportunityMutationResult<{ opportunityId: string; analysisId: string; analysisSequence: 1; aggregateVersion: number; redirectPath: string }>> {
  const parsed = saveSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.flatten().fieldErrors);
  const context = await workflowContext(); if (!context.ok) return context;
  const stored = await resolveInvestmentAnalysis(parsed.data.analysisToken, context.ownerId); if (!stored) return failure("ANALYSIS_TOKEN_EXPIRED", "This analysis is no longer available to save. Run the analysis again.");
  try {
    const property = buildOpportunityPropertyReference(stored.result, stored.analyzedAt), analysis = buildSaveInput(stored);
    const opportunity = await createInvestmentOpportunity(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, route: stored.result.lifecycleResult.acquisitionType, property, ...(parsed.data.name ? { name: parsed.data.name } : {}), tags: parsed.data.tags, initialAnalysis: analysis, commandId: parsed.data.idempotencyKey });
    const saved = opportunity.props.analyses[0]; if (!saved) throw new Error("Initial analysis was not saved.");
    if (parsed.data.note) await addOpportunityNote(context.noteRepository, { opportunityId: opportunity.id.value, ownerId: context.ownerId, body: parsed.data.note, actor: context.actor, expectedVersion: opportunity.version, commandId: `${parsed.data.idempotencyKey}:note` });
    revalidate(opportunity.id.value); return { ok: true, data: { opportunityId: opportunity.id.value, analysisId: saved.id.value, analysisSequence: 1, aggregateVersion: opportunity.version + (parsed.data.note ? 1 : 0), redirectPath: `/dashboard/investments/portfolio/${opportunity.id.value}` } };
  } catch (error) { return mapError(error); }
}
export async function saveAnalysisToOpportunityAction(input: unknown): Promise<OpportunityMutationResult<{ opportunityId: string; analysisId: string; analysisSequence: number; aggregateVersion: number; redirectPath: string }>> {
  const parsed = existingSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.flatten().fieldErrors);
  const context = await workflowContext(); if (!context.ok) return context; const stored = await resolveInvestmentAnalysis(parsed.data.analysisToken, context.ownerId); if (!stored) return failure("ANALYSIS_TOKEN_EXPIRED", "This analysis is no longer available to save. Run the analysis again.");
  try { const opportunity = await saveOpportunityAnalysis(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, opportunityId: createInvestmentOpportunityId(parsed.data.opportunityId), expectedVersion: parsed.data.expectedVersion, commandId: parsed.data.idempotencyKey, analysis: buildSaveInput(stored) }); const saved = opportunity.props.analyses.at(-1)!; revalidate(opportunity.id.value); return { ok: true, data: { opportunityId: opportunity.id.value, analysisId: saved.id.value, analysisSequence: saved.sequence, aggregateVersion: opportunity.version, redirectPath: `/dashboard/investments/portfolio/${opportunity.id.value}` } }; } catch (error) { return mapError(error); }
}
export async function listCompatibleOpportunitiesAction(analysisToken: string): Promise<OpportunityMutationResult<readonly Readonly<{ id: string; name: string; status: OpportunityStatus; aggregateVersion: number; analysisCount: number; currentRecommendation?: string; lastAnalyzedAt?: Date }>[]> > {
  const context = await workflowContext(); if (!context.ok) return context; const stored = await resolveInvestmentAnalysis(analysisToken, context.ownerId); if (!stored) return failure("ANALYSIS_TOKEN_EXPIRED", "This analysis is no longer available to save. Run the analysis again.");
  const values = await listCompatibleInvestmentOpportunities(context.repository, { ownerId: context.ownerId, route: stored.result.lifecycleResult.acquisitionType, property: buildOpportunityPropertyReference(stored.result, stored.analyzedAt) }); return { ok: true, data: values };
}
export async function updateOpportunityMetadataAction(input: unknown) { const parsed = mutationSchema.extend({ name: z.string().trim().min(1).max(120).optional(), tags: z.array(z.string().max(40)).max(20).optional() }).safeParse(input); return mutate(parsed, (context, value) => updateInvestmentOpportunity(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, opportunityId: createInvestmentOpportunityId(value.opportunityId), expectedVersion: value.expectedVersion, commandId: value.commandId, name: value.name, tags: value.tags })); }
export async function updateOpportunityStatusAction(input: unknown) { const parsed = mutationSchema.extend({ status: z.enum(["evaluating", "researching", "shortlisted", "offer-submitted", "under-contract", "acquired", "rejected"]) }).safeParse(input); return mutate(parsed, (context, value) => updateOpportunityStatus(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, opportunityId: createInvestmentOpportunityId(value.opportunityId), expectedVersion: value.expectedVersion, commandId: value.commandId, status: value.status })); }
export async function archiveOpportunityAction(input: unknown) { const parsed = mutationSchema.safeParse(input); return mutate(parsed, (context, value) => archiveInvestmentOpportunity(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, opportunityId: createInvestmentOpportunityId(value.opportunityId), expectedVersion: value.expectedVersion, commandId: value.commandId })); }
export async function restoreOpportunityAction(input: unknown) { const parsed = mutationSchema.safeParse(input); return mutate(parsed, (context, value) => restoreInvestmentOpportunity(context.repository, { authenticatedOwnerId: context.ownerId, actor: context.actor, opportunityId: createInvestmentOpportunityId(value.opportunityId), expectedVersion: value.expectedVersion, commandId: value.commandId })); }
export async function addOpportunityNoteAction(input: unknown) { const parsed = mutationSchema.extend({ body: z.string().trim().min(1).max(5000) }).safeParse(input); if (!parsed.success) return invalid(parsed.error.flatten().fieldErrors); const context = await workflowContext(); if (!context.ok) return context; try { const result = await addOpportunityNote(context.noteRepository, { opportunityId: parsed.data.opportunityId, ownerId: context.ownerId, body: parsed.data.body, actor: context.actor, expectedVersion: parsed.data.expectedVersion, commandId: parsed.data.commandId }); revalidate(parsed.data.opportunityId); return { ok: true as const, data: { aggregateVersion: result.aggregateVersion, noteId: result.note.id.value } }; } catch (error) { return mapError(error); } }

function buildSaveInput(stored: NonNullable<Awaited<ReturnType<typeof resolveInvestmentAnalysis>>>) { const result = stored.result; return { lifecycleResult: result.lifecycleResult, lifecycleResultId: result.lineage.workspaceRunId, analyzedAt: stored.analyzedAt, snapshot: buildOpportunityAnalysisSnapshotFromWorkspace(result, stored.analyzedAt), sourceSummary: buildOpportunitySourceSummary(result), policyVersions: { marketAnalysisPolicy: result.investmentMarketContext.lineage.policyVersion }, lineage: { investmentAnalysisContextId: result.lineage.workspaceRunId, investmentMarketContextId: result.investmentMarketContext.marketAnalysisId, marketAnalysisReportId: result.marketReport.analysisId } }; }
async function workflowContext() { try { const { user } = await requireRole(["admin", "owner"]), context = await getInvestmentOpportunityRequestContext(); if (!context.ok || context.ownerId !== user.id) return failure("OPPORTUNITY_ACCESS_DENIED", "You are not authorized to manage opportunities."); return { ...context, actor: { type: "user" as const, id: user.id } }; } catch { return failure("OPPORTUNITY_ACCESS_DENIED", "You are not authorized to manage opportunities."); } }
async function mutate<T>(parsed: Readonly<{ success: true; data: T }> | Readonly<{ success: false; error: z.ZodError }>, command: (context: Exclude<Awaited<ReturnType<typeof workflowContext>>, WorkflowFailure>, value: T) => Promise<{ id: { value: string }; version: number }>) { if (!parsed.success) return invalid(parsed.error.flatten().fieldErrors); const context = await workflowContext(); if (!context.ok) return context; try { const opportunity = await command(context, parsed.data); revalidate(opportunity.id.value); return { ok: true as const, data: { opportunityId: opportunity.id.value, aggregateVersion: opportunity.version } }; } catch (error) { return mapError(error); } }
function revalidate(id: string) { revalidatePath("/dashboard/investments/portfolio"); revalidatePath(`/dashboard/investments/portfolio/${id}`); revalidatePath(`/dashboard/investments/portfolio/${id}/analyses`); }
function invalid(errors: Record<string, string[] | undefined>): WorkflowFailure { return { ok: false, code: "INVALID_INPUT", message: "Review the highlighted fields.", fieldErrors: Object.fromEntries(Object.entries(errors).filter((entry): entry is [string, string[]] => Boolean(entry[1]))) }; }
function failure(code: string, message: string, currentVersion?: number): WorkflowFailure { return { ok: false, code, message, ...(currentVersion ? { currentVersion } : {}) }; }
function mapError(error: unknown): WorkflowFailure { if (error instanceof InvestmentOpportunityError) { const messages: Record<string, string> = { ANALYSIS_ALREADY_SAVED: "This analysis is already saved to this opportunity.", CONCURRENT_OPPORTUNITY_MODIFICATION: "This opportunity changed while you were editing it. Refresh and review the latest version.", OPPORTUNITY_ARCHIVED: "Restore this opportunity before making changes.", ANALYSIS_INVALID: "This analysis is not compatible with the selected opportunity." }; return failure(error.code, messages[error.code] ?? error.message); } return failure("OPPORTUNITY_PERSISTENCE_FAILED", "The opportunity could not be updated. Try again."); }
