\set ON_ERROR_STOP on
begin;
select set_config('request.jwt.claim.role','authenticated',true);
do $$
declare r public.furnishing_activation_releases; w uuid:='20000000-0000-4000-8000-000000000001'; admin_id uuid:='10000000-0000-4000-8000-000000000001'; operator_id uuid:='82000000-0000-4000-8000-000000000001'; denied_id uuid:='82000000-0000-4000-8000-000000000002'; cap text; response jsonb; rv bigint; wv bigint; cv bigint; events_before bigint; products_before bigint; projects_before bigint; budgets_before bigint; orders_before bigint;
begin
 insert into auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(operator_id,'authenticated','authenticated','fsux8-release-operator@example.invalid','',now(),now(),now(),'{}','{}'),(denied_id,'authenticated','authenticated','fsux8-denied@example.invalid','',now(),now(),now(),'{}','{}') on conflict(id) do nothing;
 insert into public.profiles(id,email,role) values(operator_id,'fsux8-release-operator@example.invalid','owner'),(denied_id,'fsux8-denied@example.invalid','owner') on conflict(id) do nothing;
 select * into r from public.furnishing_activation_releases where milestone='FS-008A' order by updated_at desc limit 1;
 update public.furnishing_activation_releases set global_state='internal',global_kill_switch=true,configuration_valid=true,optimistic_version=10,policy_version='fs008a-v1' where id=r.id;
 insert into public.furnishing_activation_workspaces(release_id,workspace_id,enabled,kill_switch,cohort,effective_from,expires_at,approved_by,reason,optimistic_version) values(r.id,w,true,false,'internal',now(),now()+interval '1 day',admin_id,'FSUX8 database lifecycle',10) on conflict(release_id,workspace_id) do update set enabled=true,kill_switch=false,cohort='internal',expires_at=now()+interval '1 day',revoked_at=null,optimistic_version=10;
 delete from public.furnishing_activation_capabilities where release_id=r.id and capability=any(array['catalog_viewing','design_workspace','budgeting','procurement_readiness']);
 insert into public.furnishing_activation_capabilities(release_id,capability,enabled,optimistic_version) select r.id,x,false,0 from unnest(array['catalog_viewing','design_workspace','budgeting','procurement_readiness']) x;
 insert into public.fsux8_release_permissions(actor_id,workspace_id,permission,status,granted_by,reason,expires_at) select admin_id,case when p in('global_suspend','global_recover','release_mode') then null else w end,p,'active',admin_id,'FSUX8 controlled database proof',now()+interval '1 day' from unnest(array['workspace_recover','global_recover']) p on conflict(actor_id,workspace_id,permission) do update set status='active',expires_at=excluded.expires_at;
 insert into public.fsux8_release_permissions(actor_id,workspace_id,permission,status,granted_by,reason,expires_at) select operator_id,case when p in('global_suspend','global_recover','release_mode') then null else w end,p,'active',admin_id,'FSUX8 release operator matrix',now()+interval '1 day' from unnest(array['view','control','verify','workspace_suspend','global_suspend','workspace_recover','global_recover','cohort_control']) p on conflict(actor_id,workspace_id,permission) do update set status='active',expires_at=excluded.expires_at;
 if not public.fsux8_has_release_permission(operator_id,'control',w) or public.fsux8_has_release_permission(denied_id,'control',w) then raise exception 'FSUX8_PERMISSION_MATRIX_INVALID'; end if;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 select count(*),count(*) from public.furnishing_activation_audit_events into events_before,products_before; select count(*) into products_before from public.furnishing_products;select count(*) into projects_before from public.furnishing_projects;select count(*) into budgets_before from public.furnishing_budgets;select count(*) into orders_before from public.furnishing_procurement_orders;
 rv:=10;wv:=10;
 begin perform public.fsux8_apply_control_v2('enable',w,'design_workspace',rv,0,'fs008a-v1','production','Out of order activation must fail','fsux8-invalid-order','fsux8-invalid-order',null);raise exception 'FSUX8_OUT_OF_ORDER_ALLOWED';exception when others then if sqlerrm='FSUX8_OUT_OF_ORDER_ALLOWED'then raise;end if;end;
 foreach cap in array array['catalog_viewing','design_workspace','budgeting','procurement_readiness'] loop
  select optimistic_version into cv from public.furnishing_activation_capabilities where release_id=r.id and capability=cap;
  response:=public.fsux8_apply_control_v2('enable',w,cap,rv,cv,'fs008a-v1','production','Enable bounded capability for database proof','fsux8-enable-'||cap,'fsux8-enable-'||cap,null);
  cv:=(response->>'version')::bigint;
  response:=public.fsux8_verify_capability_v2(w,cap,cv,'fs008a-v1','Execute authoritative server verification checks','fsux8-verify-'||cap,'fsux8-verify-'||cap);
  if response->>'verification'<>'verified' then raise exception 'FSUX8_CAPABILITY_VERIFICATION_FAILED %',cap;end if;
 end loop;
 begin perform public.fsux8_apply_control_v2('disable',w,'catalog_viewing',rv,(select optimistic_version from public.furnishing_activation_capabilities where release_id=r.id and capability='catalog_viewing'),'fs008a-v1','production','Invalid forward rollback must fail','fsux8-invalid-rollback','fsux8-invalid-rollback',null);raise exception 'FSUX8_INVALID_ROLLBACK_ALLOWED';exception when others then if sqlerrm='FSUX8_INVALID_ROLLBACK_ALLOWED'then raise;end if;end;
 foreach cap in array array['procurement_readiness','budgeting','design_workspace','catalog_viewing'] loop select optimistic_version into cv from public.furnishing_activation_capabilities where release_id=r.id and capability=cap;perform public.fsux8_apply_control_v2('disable',w,cap,rv,cv,'fs008a-v1','production','Reverse dependency rollback database proof','fsux8-disable-'||cap,'fsux8-disable-'||cap,null);end loop;
 foreach cap in array array['catalog_viewing','design_workspace','budgeting','procurement_readiness'] loop select optimistic_version into cv from public.furnishing_activation_capabilities where release_id=r.id and capability=cap;response:=public.fsux8_apply_control_v2('enable',w,cap,rv,cv,'fs008a-v1','production','Re-enable bounded capability before suspension','fsux8-reenable-'||cap,'fsux8-reenable-'||cap,null);perform public.fsux8_verify_capability_v2(w,cap,(response->>'version')::bigint,'fs008a-v1','Reverify capability before suspension proof','fsux8-reverify-'||cap,'fsux8-reverify-'||cap);end loop;
 select optimistic_version into wv from public.furnishing_activation_workspaces where release_id=r.id and workspace_id=w;
 response:=public.fsux8_apply_control_v2('suspend_workspace',w,null,rv,wv,'fs008a-v1','production','Suspend controlled workspace for recovery proof','fsux8-workspace-suspend','fsux8-workspace-suspend',null);wv:=(response->>'version')::bigint;
 begin perform public.fsux8_apply_control_v2('recover_workspace',w,null,rv,wv,'fs008a-v1','production','Attempt stale unresolved recovery','fsux8-bad-recovery','fsux8-bad-recovery',null);raise exception 'FSUX8_UNRESOLVED_RECOVERY_ALLOWED';exception when others then if sqlerrm='FSUX8_UNRESOLVED_RECOVERY_ALLOWED'then raise;end if;end;
 response:=public.fsux8_apply_control_v2('recover_workspace',w,null,rv,wv,'fs008a-v1','production','Authorize workspace recovery after review','fsux8-workspace-recover','fsux8-workspace-recover','Controlled risk reconciled and formally resolved');
 if response->>'capabilitiesRequireReverification'<>'true' then raise exception 'FSUX8_RECOVERY_REVERIFY_MISSING';end if;
 response:=public.fsux8_apply_control_v2('suspend_global',null,null,rv,rv,'fs008a-v1','production','Suspend globally for precedence proof','fsux8-global-suspend','fsux8-global-suspend',null);rv:=(response->>'version')::bigint;
 begin perform public.fsux8_verify_capability_v2(w,'catalog_viewing',(select optimistic_version from public.furnishing_activation_capabilities where release_id=r.id and capability='catalog_viewing'),'fs008a-v1','Verification must lose to global suspension','fsux8-suspended-verify','fsux8-suspended-verify');raise exception 'FSUX8_GLOBAL_PRECEDENCE_FAILED';exception when others then if sqlerrm='FSUX8_GLOBAL_PRECEDENCE_FAILED'then raise;end if;end;
 response:=public.fsux8_apply_control_v2('recover_global',null,null,rv,rv,'fs008a-v1','production','Authorize global recovery to protected state','fsux8-global-recover','fsux8-global-recover','Systemic risk reconciled and formally resolved');rv:=(response->>'version')::bigint;
 if response->>'protected'<>'true' then raise exception 'FSUX8_GLOBAL_RECOVERY_NOT_PROTECTED';end if;
 if public.fsux8_apply_control_v2('recover_global',null,null,rv,rv,'fs008a-v1','production','Authorize global recovery to protected state','fsux8-global-recover','fsux8-global-recover','Systemic risk reconciled and formally resolved')->>'status'<>'recovered' then raise exception 'FSUX8_RECOVERY_REPLAY_FAILED';end if;
 if (select count(*) from public.furnishing_products)<>products_before or (select count(*) from public.furnishing_projects)<>projects_before or (select count(*) from public.furnishing_budgets)<>budgets_before or (select count(*) from public.furnishing_procurement_orders)<>orders_before then raise exception 'FSUX8_EXTERNAL_OR_LIFECYCLE_EFFECT_DETECTED';end if;
 if exists(select 1 from public.fsux8_capability_verification_runs r2 left join public.fsux8_capability_verification_checks c on c.run_id=r2.id where r2.status='passed' group by r2.id having count(c.id)=0 or bool_or(c.status='failed')) then raise exception 'FSUX8_VERIFICATION_EVIDENCE_MISMATCH';end if;
 if not exists(select 1 from public.fsux8_release_suspensions where scope='workspace' and state='recovered' and recovery_event_id is not null) or not exists(select 1 from public.fsux8_release_suspensions where scope='global' and state='recovered' and recovery_event_id is not null) then raise exception 'FSUX8_RECOVERY_EVIDENCE_MISSING';end if;
 if (select global_state from public.furnishing_activation_releases where id=r.id)<>'internal' or not (select global_kill_switch from public.furnishing_activation_releases where id=r.id) then raise exception 'FSUX8_PROTECTED_BASELINE_MISMATCH';end if;
end$$;
rollback;
select 'FS_UX_008_DATABASE_LIFECYCLE_AUTHORIZATION_PASS' as result;
