import { chromium, type Browser, type Page } from "playwright-core";
import { createClient } from "@supabase/supabase-js";
import { mkdirSync, writeFileSync } from "node:fs";
import { randomBytes, randomUUID } from "node:crypto";

const required = (name: string) => { const value=process.env[name]?.trim(); if(!value) throw new Error(`${name}_MISSING`); return value; };
const base=(process.env.PS001B_BASE_URL??"https://luxehavencollective.co").replace(/\/$/,"");
const admin=createClient(required("NEXT_PUBLIC_SUPABASE_URL"),required("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false,autoRefreshToken:false}});
const correlationId=`ps001b-${randomUUID()}`,password=`Lh!${randomBytes(18).toString("base64url")}`,stamp=correlationId.slice(-12);
const evidenceDir=`docs/evidence/PS-001B/${correlationId}`;
const evidence:{correlationId:string;candidate:Record<string,string>;startedAt:string;steps:unknown[];result?:string;failure?:string;completedAt?:string}={correlationId,candidate:{commit:"91adc182",deployment:"dpl_8oigBrnep6bsLXyTf2rc58rSCBfh",base},startedAt:new Date().toISOString(),steps:[]};
const identities:Record<string,{id:string;email:string;workspaceId?:string;propertyId?:string}>={};
const record=(name:string,data:Record<string,unknown>={})=>evidence.steps.push({name,at:new Date().toISOString(),...data});

async function must<T>(promise:PromiseLike<{data:T;error:unknown}>,code:string){const result=await promise;if(result.error)throw new Error(`${code}:${JSON.stringify(result.error)}`);return result.data;}
async function createIdentity(key:string,role:"owner"|"admin"="owner") { const email=`${correlationId}-${key}@example.invalid`,created=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{role,full_name:`PS-001B ${key}`}});if(created.error||!created.data.user)throw created.error??new Error("USER_CREATE_FAILED");const id=created.data.user.id;await must(admin.from("profiles").upsert({id,email,full_name:`PS-001B ${key}`,role}),`${key}_PROFILE`);identities[key]={id,email};return identities[key]!; }
async function createWorkspace(identity:{id:string;email:string;workspaceId?:string},membershipRole:"owner"|"administrator"="owner"){const owner=await must(admin.from("owners").insert({profile_id:identity.id,company_name:`PS-001B ${stamp}`}).select("id").single(),"OWNER_CREATE") as {id:string};identity.workspaceId=owner.id;await must(admin.from("workspace_memberships").insert({workspace_id:owner.id,profile_id:identity.id,role:membershipRole,status:"active",property_access_mode:"all",joined_at:new Date().toISOString()}).select(),"MEMBERSHIP_CREATE");return owner.id;}
async function seedComplete(identity:{id:string;workspaceId?:string;propertyId?:string}){const workspaceId=identity.workspaceId!;const property=await must(admin.from("properties").insert({owner_id:workspaceId,name:`Controlled Mesa ${stamp}`,slug:`ps001b-${stamp}`,description:"Controlled PS-001B evidence",address_line_1:"100 Verification Way",postal_code:"85201",country:"US",city:"Mesa",state:"AZ",bedrooms:3,bathrooms:2,max_guests:6,nightly_rate:250,status:"active",timezone:"America/Phoenix",source:"manual"}).select("id").single(),"PROPERTY_CREATE") as {id:string};identity.propertyId=property.id;
  await must(admin.from("bookings").insert([{property_id:property.id,guest_full_name:"Controlled Guest A",check_in:"2026-08-02",check_out:"2026-08-06",guests:4,nightly_rate:250,cleaning_fee:120,taxes:140,service_fee:40,total_amount:1300,status:"completed",payment_status:"paid",source:"Direct"},{property_id:property.id,guest_full_name:"Controlled Guest B",check_in:"2026-08-12",check_out:"2026-08-16",guests:2,nightly_rate:275,cleaning_fee:120,taxes:150,service_fee:40,total_amount:1410,status:"confirmed",payment_status:"paid",source:"Direct"},{property_id:property.id,guest_full_name:"Comparison Guest",check_in:"2026-07-10",check_out:"2026-07-14",guests:3,nightly_rate:225,cleaning_fee:100,taxes:120,service_fee:35,total_amount:1155,status:"completed",payment_status:"paid",source:"Direct"}]).select(),"BOOKINGS_CREATE");
  const accounts=await must(admin.from("financial_accounts").insert([{workspace_id:workspaceId,code:"REV",name:"Rental revenue",category:"revenue",account_type:null,source_type:"manual"},{workspace_id:workspaceId,code:"OPEX",name:"Operating expenses",category:"operating-expense",account_type:null,source_type:"csv"},{workspace_id:workspaceId,code:"CASH",name:"Operating cash",category:"asset",account_type:"operating",source_type:"manual"}]).select("id,code"),"ACCOUNTS_CREATE") as {id:string;code:string}[];const account=(code:string)=>accounts.find(item=>item.code===code)!.id;
  await must(admin.from("financial_transactions").insert([{workspace_id:workspaceId,account_id:account("REV"),property_id:property.id,amount_minor:271000,currency:"USD",measurement:"actual",effective_date:"2026-08-16",posting_date:"2026-08-16",status:"posted",source_provider:"controlled",evidence_ids:[correlationId],idempotency_key:`${correlationId}-rev`,direction:"inflow",description:"Controlled revenue"},{workspace_id:workspaceId,account_id:account("OPEX"),property_id:property.id,amount_minor:-81000,currency:"USD",measurement:"actual",effective_date:"2026-08-18",posting_date:"2026-08-18",status:"posted",source_provider:"controlled",evidence_ids:[correlationId],idempotency_key:`${correlationId}-opex`,direction:"outflow",description:"Controlled operating expense"}]).select(),"TRANSACTIONS_CREATE");
  await must(admin.from("cash_balance_observations").insert({workspace_id:workspaceId,account_id:account("CASH"),property_id:property.id,amount_minor:4800000,currency:"USD",as_of:"2026-08-23",source_type:"manual",source_reference:correlationId,idempotency_key:`${correlationId}-cash`,recorded_by_profile_id:identity.id}).select(),"BALANCE_CREATE");record("complete-evidence-seeded",{workspaceId,propertyId:property.id});}
async function login(page:Page,identity:{email:string},next="/dashboard/observe/revenue"){await page.goto(`${base}/login?next=${encodeURIComponent(next)}`,{waitUntil:"domcontentloaded"});await page.getByLabel("Email").fill(identity.email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:/sign in/i}).click();await page.waitForURL(url=>url.pathname.startsWith("/dashboard")||url.pathname.startsWith("/properties"),{timeout:30_000});}
const contextQuery=(workspaceId:string)=>`workspace=${workspaceId}&scope=entire-portfolio&from=2026-08-01&to=2026-08-31&compareFrom=2026-07-01&compareTo=2026-07-31&basis=actual`;
async function goto(page:Page,path:string,workspaceId:string){await page.goto(`${base}${path}${path.includes("?")?"&":"?"}${contextQuery(workspaceId)}`,{waitUntil:"networkidle"});const body=await page.locator("body").innerText();if(/404|Application error|Internal Server Error/i.test(body))throw new Error(`ROUTE_FAILED:${path}`);return body;}
async function shot(page:Page,name:string){await page.screenshot({path:`${evidenceDir}/${name}.png`,fullPage:true});}
async function generateAndInspectReport(page:Page,owner:{id:string;workspaceId?:string},scope:"current-view"|"full-capability"){
  const workspaceId=owner.workspaceId!,title=`PS-001B ${scope} ${stamp}`;
  await goto(page,"/dashboard/observe/revenue",workspaceId);await page.getByRole("button",{name:"Export"}).click();
  if(scope==="full-capability")await page.getByText("Full Revenue Intelligence report",{exact:true}).click();
  await page.getByRole("link",{name:"Continue in Reports"}).click();await page.waitForURL(/\/dashboard\/reports\/new\?/);
  await page.getByRole("link",{name:"Configure report"}).first().click();await page.waitForURL(/\/dashboard\/reports\/new\/.+/);
  await page.getByLabel(new RegExp(`Controlled Mesa ${stamp}`)).check();await page.getByLabel("Report title").fill(title);try{await Promise.all([page.waitForURL(/\/dashboard\/reports\?generated=/,{timeout:30_000}),page.getByRole("button",{name:"Generate report"}).click()]);}catch(error){await shot(page,`report-generation-failure-${scope}`);throw new Error(`REPORT_GENERATION_NAV_${scope}:${page.url()}:${(await page.locator("body").innerText()).slice(-1200)}:${error instanceof Error?error.message:String(error)}`);}
  const version=await must(admin.from("canonical_report_versions").select("id,report_id,workspace_id,status,scope_snapshot,period_snapshot,comparison_period_snapshot,content_snapshot,generated_at,requested_by_profile_id").eq("workspace_id",workspaceId).eq("requested_by_profile_id",owner.id).eq("title",title).single(),`REPORT_${scope}`) as Record<string,unknown>;
  const snapshot=version.content_snapshot as {generation?:{normalizedRequest?:{scope?:Record<string,unknown>;period?:Record<string,unknown>;comparisonPeriod?:Record<string,unknown>;sourceContext?:Record<string,string>}}};const normalized=snapshot.generation?.normalizedRequest;
  if(version.status!=="ready"||!version.generated_at||version.workspace_id!==workspaceId||version.requested_by_profile_id!==owner.id)throw new Error(`REPORT_ARTIFACT_STATE_${scope}`);
  if(normalized?.scope?.tenantId!==workspaceId||normalized.period?.startDate!=="2026-08-01"||normalized.period?.endDate!=="2026-08-31"||normalized.comparisonPeriod?.startDate!=="2026-07-01"||normalized.comparisonPeriod?.endDate!=="2026-07-31")throw new Error(`REPORT_SNAPSHOT_CONTEXT_${scope}`);
  if(normalized.sourceContext?.sourceCapability!=="revenue"||normalized.sourceContext?.sourceView!=="overview"||normalized.sourceContext?.reportScope!==scope||normalized.sourceContext?.accountingBasis!=="actual")throw new Error(`REPORT_SNAPSHOT_INTENT_${scope}`);
  await page.goto(`${base}/dashboard/reports/${version.report_id}/versions/${version.id}`,{waitUntil:"networkidle"});if(!/Report|Generated|Evidence/i.test(await page.locator("body").innerText()))throw new Error(`REPORT_ARTIFACT_RENDER_${scope}`);await shot(page,`report-artifact-${scope}`);record(`report-${scope}-artifact-inspected`,{reportId:version.report_id,versionId:version.id,generatedAt:version.generated_at,immutableSnapshot:true});
}
async function ownerJourneys(browser:Browser,owner:{id:string;email:string;workspaceId?:string;propertyId?:string}){const page=await browser.newPage({viewport:{width:1440,height:1000}});await login(page,owner);const workspaceId=owner.workspaceId!;
  let body=await goto(page,"/dashboard/observe/revenue",workspaceId);if(!/Revenue Intelligence/i.test(body))throw new Error("REVENUE_MISSING");await shot(page,"complete-evidence-revenue");
  await page.getByRole("button",{name:"Export"}).click();await page.getByRole("link",{name:"Continue in Reports"}).click();await page.waitForURL(/\/dashboard\/reports\/new\?/);if(!page.url().includes("from=2026-08-01")||!page.url().includes("basis=actual"))throw new Error("REPORT_HANDOFF_CONTEXT_LOST");record("revenue-current-report-handoff",{url:page.url()});
  await generateAndInspectReport(page,owner,"current-view");await generateAndInspectReport(page,owner,"full-capability");
  body=await goto(page,"/dashboard/observe/financial/cash-flow",workspaceId);if(!/Cash Flow/i.test(body))throw new Error("CASH_FLOW_MISSING");await goto(page,"/dashboard/observe/financial/forecast",workspaceId);await page.getByRole("button",{name:/Financial Intelligence actions/i}).click();await page.getByRole("menuitem",{name:"View data sources"}).click();if(await page.getByText(/Hospitable.*Connected/i).count())throw new Error("FABRICATED_PROVIDER_STATE");await shot(page,"financial-data-sources");record("observe-journey-passed");
  await goto(page,"/dashboard/understand/executive",workspaceId);await page.getByRole("button",{name:/Executive Intelligence actions/i}).click();await page.getByRole("menuitem",{name:/Review attention/i}).click();for(const filter of ["Performance","Risk","Data Quality"]){await page.getByRole("tab",{name:filter}).click();await page.waitForURL(url=>url.searchParams.get("type")===filter.toLowerCase().replace(" ","-"));if(await page.getByRole("tab",{name:filter}).getAttribute("aria-selected")!=="true")throw new Error(`ATTENTION_FILTER_${filter}`);}await shot(page,"executive-attention-filter");await page.goBack();await page.goForward();await page.getByRole("link",{name:/Return to Executive Intelligence/i}).click();record("executive-journey-passed");
  await goto(page,"/dashboard/understand/portfolio",workspaceId);const review=page.getByRole("link",{name:/Review .*Controlled Mesa/i}).first();if(await review.count()){await review.click();await page.waitForURL(/property=/);await shot(page,"property-intelligence");await page.getByRole("link",{name:/Back to portfolio intelligence/i}).click();}await goto(page,"/dashboard/understand/portfolio/properties",workspaceId);await goto(page,"/dashboard/understand/portfolio",workspaceId);const signals=page.getByRole("button",{name:/Inspect supporting signals/i}).first();if(await signals.count()){await signals.click();await page.getByRole("dialog",{name:"Supporting signals"}).waitFor();await shot(page,"supporting-signals");await Promise.all([page.waitForURL(url=>url.pathname===understandDataQualityPath()),page.getByRole("link",{name:"Investigate further"}).click()]);}else await goto(page,"/dashboard/understand/portfolio/data-quality",workspaceId);await shot(page,"portfolio-data-quality");if(await page.getByRole("navigation",{name:/Portfolio Intelligence views/i}).count())throw new Error("DIAGNOSTIC_PRIMARY_TABS_PRESENT");record("portfolio-journey-passed");await page.close();}
function understandDataQualityPath(){return "/dashboard/understand/portfolio/data-quality";}
async function responsive(browser:Browser,owner:{email:string;workspaceId?:string}){for(const [name,width,height] of [["desktop",1440,900],["tablet",820,1000],["mobile",390,844]] as const){const page=await browser.newPage({viewport:{width,height}});await login(page,owner);await goto(page,"/dashboard/understand/portfolio/data-quality",owner.workspaceId!);if(width<1024){const menu=page.getByRole("button",{name:/Open navigation menu/i});if(!await menu.count())throw new Error(`RESPONSIVE_NAV_${name}`);}await shot(page,`responsive-${name}`);await page.close();record(`responsive-${name}-passed`);}}
async function authorization(browser:Browser,owner:{email:string;workspaceId?:string},adminIdentity:{email:string},wrong:{email:string;workspaceId?:string},revoked:{email:string;workspaceId?:string}){const anonymous=await browser.newPage();await anonymous.goto(`${base}/dashboard/observe/revenue`);if(!new URL(anonymous.url()).pathname.startsWith("/login"))throw new Error("ANONYMOUS_BOUNDARY_FAILED");await anonymous.close();record("anonymous-denied");for(const [name,identity] of [["admin",adminIdentity],["wrong-tenant",wrong]] as const){const page=await browser.newPage();await login(page,identity);const body=await goto(page,"/dashboard/understand/portfolio",identity===wrong?wrong.workspaceId!:owner.workspaceId!);if(name==="wrong-tenant"&&body.includes(`Controlled Mesa ${stamp}`))throw new Error("WRONG_TENANT_LEAK");await page.close();record(`${name}-verified`);}await must(admin.from("workspace_memberships").update({status:"suspended",updated_at:new Date().toISOString()}).eq("profile_id",identities.revoked!.id).select(),"REVOKE_MEMBERSHIP");const page=await browser.newPage();await login(page,revoked);await page.goto(`${base}/dashboard/observe/revenue`,{waitUntil:"networkidle"});if(!(await page.locator("body").innerText()).includes("You no longer have access to this workspace"))throw new Error("REVOKED_ACCESS_RETAINED");await page.close();record("revoked-denied");}
async function partial(browser:Browser,owner:{email:string;workspaceId?:string}){await must(admin.from("financial_transactions").delete().eq("idempotency_key",`${correlationId}-opex`).select(),"PARTIAL_REMOVE_EXPENSE");const page=await browser.newPage({viewport:{width:1440,height:1000}});await login(page,owner);const body=await goto(page,"/dashboard/observe/financial",owner.workspaceId!);if(!/insufficient|incomplete|missing|no expense/i.test(body))throw new Error("PARTIAL_EVIDENCE_NOT_DISCLOSED");if(/Operating Expenses\s*\$0(?:\.00)?\b/i.test(body))throw new Error("PARTIAL_UNKNOWN_RENDERED_AS_ZERO");await shot(page,"partial-evidence-financial");await page.close();record("partial-evidence-passed");}
async function degraded(browser:Browser,owner:{email:string;workspaceId?:string}){await admin.from("cash_balance_observations").update({as_of:"2026-05-01"}).eq("source_reference",correlationId);const page=await browser.newPage({viewport:{width:1440,height:1000}});await login(page,owner);const body=await goto(page,"/dashboard/observe/financial/cash-flow",owner.workspaceId!);if(!/stale|partial|insufficient/i.test(body))throw new Error("DEGRADED_EVIDENCE_NOT_DISCLOSED");if(/\$0[^\d].*Cash Flow Statement/i.test(body))throw new Error("UNKNOWN_RENDERED_AS_ZERO");await shot(page,"degraded-evidence-cash-flow");await page.close();record("degraded-evidence-passed");}
async function cleanup(){for(const identity of Object.values(identities)){if(identity.workspaceId){await admin.from("canonical_report_exports").delete().eq("workspace_id",identity.workspaceId);await admin.from("canonical_report_versions").delete().eq("workspace_id",identity.workspaceId);await admin.from("canonical_reports").delete().eq("workspace_id",identity.workspaceId);await admin.from("workspace_memberships").delete().eq("workspace_id",identity.workspaceId);}if(identity.id)await admin.auth.admin.deleteUser(identity.id);}record("synthetic-cleanup-completed");}
async function main(){mkdirSync(evidenceDir,{recursive:true});const owner=await createIdentity("owner"),adminIdentity=await createIdentity("admin","admin"),wrong=await createIdentity("wrong"),revoked=await createIdentity("revoked");await createWorkspace(owner);await createWorkspace(wrong);await createWorkspace(revoked);await admin.from("workspace_memberships").insert({workspace_id:owner.workspaceId,profile_id:adminIdentity.id,role:"administrator",status:"active",property_access_mode:"all",joined_at:new Date().toISOString()});await seedComplete(owner);const browser=await chromium.launch({executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",headless:true});try{await ownerJourneys(browser,owner);await responsive(browser,owner);await authorization(browser,owner,adminIdentity,wrong,revoked);await partial(browser,owner);await degraded(browser,owner);evidence.result="passed";}finally{await browser.close();}}
async function run(){try{await main();}catch(error){evidence.result="failed";evidence.failure=error instanceof Error?error.message:String(error);}finally{await cleanup();evidence.completedAt=new Date().toISOString();writeFileSync(`${evidenceDir}/verification.json`,JSON.stringify(evidence,null,2));process.stdout.write(`${JSON.stringify(evidence,null,2)}\n`);}if(evidence.result!=="passed")process.exitCode=1;}void run();
