import { InvestmentOpportunity, OpportunityAnalysis, OpportunityName, createInvestmentOpportunityId, createOpportunityActivityId, createOpportunityAnalysisId, createOpportunityOwnerId, type OpportunityActivity, type OpportunityAddress, type OpportunityAnalysisProps, type OpportunityTag } from "../../domain";

export type InvestmentOpportunityPersistencePayload = Readonly<{ opportunity: Readonly<Record<string, unknown>>; analyses: readonly Readonly<Record<string, unknown>>[]; tags: readonly Readonly<Record<string, unknown>>[]; activity: readonly Readonly<Record<string, unknown>>[] }>;
export type InvestmentOpportunityPersistenceRecord = Readonly<{ opportunity: Record<string, unknown>; analyses: readonly Record<string, unknown>[]; tags: readonly Record<string, unknown>[]; activity: readonly Record<string, unknown>[] }>;
const iso = (date: Date) => date.toISOString();

export function toInvestmentOpportunityPersistence(opportunity: InvestmentOpportunity): InvestmentOpportunityPersistencePayload {
  const props = opportunity.props;
  return {
    opportunity: { id: props.id.value, owner_id: props.ownerId.value, name: props.name.value, route: props.route, status: props.status, market_property_id: props.property.marketPropertyId ?? null, display_address: props.property.displayAddress, normalized_address: props.property.normalizedAddress, property_snapshot: { ...props.property, capturedAt: iso(props.property.capturedAt) }, current_analysis_id: props.currentAnalysisId?.value ?? null, archived_at: props.archivedAt ? iso(props.archivedAt) : null, created_at: iso(props.createdAt), updated_at: iso(props.updatedAt), version: props.version },
    analyses: props.analyses.map(value => { const item = value.props; return { id: item.id.value, opportunity_id: item.opportunityId.value, sequence: item.sequence, route: item.route, investment_analysis_id: item.investmentAnalysisId, investment_decision_id: item.investmentDecisionId ?? null, market_analysis_id: item.marketAnalysisId ?? null, result_snapshot: datesToJson(item.resultSnapshot), source_summary: item.sourceSummary, policy_versions: item.policyVersions, lineage: item.lineage, created_by: item.createdBy, created_at: iso(item.createdAt) }; }),
    tags: props.tags.map(tag => ({ opportunity_id: props.id.value, normalized_value: tag.normalizedValue, display_value: tag.displayValue, created_at: iso(props.createdAt) })),
    activity: props.activities.map(item => ({ id: item.id.value, opportunity_id: item.opportunityId.value, type: item.type, actor: item.actor, details: item.details, occurred_at: iso(item.occurredAt), aggregate_version: item.aggregateVersion, command_id: item.commandId ?? null })),
  };
}

export function fromInvestmentOpportunityPersistence(record: InvestmentOpportunityPersistenceRecord): InvestmentOpportunity {
  const row = record.opportunity, id = createInvestmentOpportunityId(text(row.id));
  const analyses = record.analyses.map(item => OpportunityAnalysis.create({ id: createOpportunityAnalysisId(text(item.id)), opportunityId: id, sequence: number(item.sequence), route: route(item.route), investmentAnalysisId: text(item.investment_analysis_id), ...(optionalText(item.investment_decision_id) ? { investmentDecisionId: optionalText(item.investment_decision_id) } : {}), ...(optionalText(item.market_analysis_id) ? { marketAnalysisId: optionalText(item.market_analysis_id) } : {}), resultSnapshot: snapshot(item.result_snapshot), sourceSummary: object(item.source_summary) as unknown as OpportunityAnalysisProps["sourceSummary"], policyVersions: object(item.policy_versions) as unknown as OpportunityAnalysisProps["policyVersions"], lineage: object(item.lineage) as unknown as OpportunityAnalysisProps["lineage"], createdBy: object(item.created_by) as unknown as OpportunityAnalysisProps["createdBy"], createdAt: date(item.created_at) }));
  const property = object(row.property_snapshot) as Record<string, unknown>;
  const activities: OpportunityActivity[] = record.activity.map(item => ({ id: createOpportunityActivityId(text(item.id)), opportunityId: id, type: text(item.type) as OpportunityActivity["type"], actor: object(item.actor) as OpportunityActivity["actor"], details: object(item.details), occurredAt: date(item.occurred_at), aggregateVersion: number(item.aggregate_version), ...(optionalText(item.command_id) ? { commandId: optionalText(item.command_id) } : {}) }));
  return InvestmentOpportunity.restore({ id, ownerId: createOpportunityOwnerId(text(row.owner_id)), name: OpportunityName.create(text(row.name)), route: route(row.route), property: { ...property, normalizedAddress: object(property.normalizedAddress) as unknown as OpportunityAddress, displayAddress: text(property.displayAddress), resolutionStatus: property.resolutionStatus === "resolved" ? "resolved" : "user-supplied", capturedAt: date(property.capturedAt) }, status: text(row.status) as InvestmentOpportunity["props"]["status"], analyses, ...(optionalText(row.current_analysis_id) ? { currentAnalysisId: createOpportunityAnalysisId(optionalText(row.current_analysis_id)) } : {}), tags: record.tags.map(item => ({ normalizedValue: text(item.normalized_value), displayValue: text(item.display_value) } satisfies OpportunityTag)), activities, createdAt: date(row.created_at), updatedAt: date(row.updated_at), ...(row.archived_at ? { archivedAt: date(row.archived_at) } : {}), version: number(row.version) });
}
function datesToJson<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T; }
function object(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new TypeError("Expected persistence object."); return value as Record<string, unknown>; }
function text(value: unknown): string { if (typeof value !== "string" || !value.trim()) throw new TypeError("Expected persistence text."); return value; }
function optionalText(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value : undefined; }
function number(value: unknown): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new TypeError("Expected persistence number."); return value; }
function date(value: unknown): Date { const parsed = new Date(text(value)); if (Number.isNaN(parsed.getTime())) throw new TypeError("Expected persistence timestamp."); return parsed; }
function route(value: unknown) { const parsed = text(value); if (parsed !== "purchase" && parsed !== "rental-arbitrage") throw new TypeError("Invalid persisted route."); return parsed; }
function snapshot(value: unknown): OpportunityAnalysisProps["resultSnapshot"] { const raw = object(value), analyzedAt = date(raw.analyzedAt); return { ...(raw as unknown as OpportunityAnalysisProps["resultSnapshot"]), analyzedAt }; }
