export type MediaType="image"|"video"|"document"|"icon"|"illustration"|"logo";export type MediaScope="platform"|"workspace"|"property";export type MediaStatus="draft"|"processing"|"approved"|"broken"|"archived";export type MediaAccess="private"|"guest"|"public"|"signed"|"internal";
export type MediaAsset=Readonly<{id:string;workspaceId:string;propertyId:string|null;name:string;slug:string;mediaType:MediaType;category:string;scope:MediaScope;accessPolicy:MediaAccess;status:MediaStatus;currentVersionId:string|null;altText:string|null;decorative:boolean;caption:string|null;tags:readonly string[];createdBy:string;updatedBy:string;createdAt:string;updatedAt:string;archivedAt:string|null;replacementAssetId:string|null}>;
export type MediaMetadata=Readonly<{title:string;altText:string|null;decorative:boolean;caption:string|null;photographer:string|null;copyright:string|null;license:string|null;tags:readonly string[];dominantColor:string|null;orientation:"landscape"|"portrait"|"square"|"unknown";exif:Readonly<Record<string,unknown>>;safeCrop:Readonly<{x:number;y:number;width:number;height:number}>|null;location:Readonly<{latitude:number;longitude:number}>|null}>;
export type MediaDerivativeKind="thumbnail"|"small"|"medium"|"large"|"retina"|"pdf"|"hero"|"qr";
export type MediaDerivative=Readonly<{id:string;mediaVersionId:string;kind:MediaDerivativeKind;storagePath:string;mimeType:string;width:number|null;height:number|null;byteSize:number;checksumSha256:string;status:"queued"|"processing"|"ready"|"failed";createdAt:string}>;
export type MediaVersion=Readonly<{id:string;assetId:string;versionNumber:number;status:"processing"|"approved"|"archived";storagePath:string;originalFilename:string;mimeType:string;byteSize:number;width:number|null;height:number|null;durationSeconds:number|null;checksumSha256:string;metadata:MediaMetadata;derivatives:readonly MediaDerivative[];basedOnVersionId:string|null;createdBy:string;createdAt:string;approvedBy:string|null;approvedAt:string|null}>;
export type MediaUsage=Readonly<{id:string;assetId:string;mediaVersionId:string;consumerType:"guidebook"|"template"|"component"|"content_record"|"publication";consumerId:string;guidebookVersionId:string|null;publicationStatus:"draft"|"published"|"superseded";channels:readonly string[];createdAt:string}>;
export type MediaCollection=Readonly<{id:string;workspaceId:string|null;propertyId:string|null;name:string;slug:string;description:string;scope:MediaScope;createdBy:string;createdAt:string}>;
export type MediaValidationIssue=Readonly<{code:string;message:string;blocking:boolean}>;
export const MEDIA_CATEGORIES=Object.freeze(["property_photos","lifestyle","hero_images","amenities","room_photos","maps","icons","logos","illustrations","emergency","pdf_attachments","instruction_manuals","videos","qr_assets","downloads","custom"] as const);
export const MEDIA_PERMISSIONS=Object.freeze(["media.view","media.upload","media.edit","media.approve","media.archive","media.replace","media.delete","media.publish","media.insert"] as const);export type MediaPermission=(typeof MEDIA_PERMISSIONS)[number];
export const SUPPORTED_MEDIA=Object.freeze({"image/jpeg":"image","image/png":"image","image/webp":"image","image/svg+xml":"image","image/avif":"image","video/mp4":"video","video/quicktime":"video","video/webm":"video","application/pdf":"document"} as const);
export function validateMediaAsset(asset:MediaAsset,version:MediaVersion):readonly MediaValidationIssue[]{const issues:MediaValidationIssue[]=[];if(!(version.mimeType in SUPPORTED_MEDIA))issues.push({code:"FORMAT_UNSUPPORTED",message:"The file format is unsupported.",blocking:true});if(asset.mediaType==="image"&&!asset.decorative&&!asset.altText?.trim())issues.push({code:"ALT_TEXT_REQUIRED",message:"Provide alt text or mark the image decorative.",blocking:true});if(version.derivatives.some(v=>v.status==="failed"))issues.push({code:"DERIVATIVE_FAILED",message:"One or more required derivatives failed.",blocking:true});if(!asset.name.trim())issues.push({code:"NAME_REQUIRED",message:"Asset name is required.",blocking:true});return issues}
export function requiredDerivatives(type:MediaType):readonly MediaDerivativeKind[]{return type==="image"?["thumbnail","small","medium","large","retina","pdf","hero"]:type==="document"?["thumbnail"]:[]}
export function detectDuplicate(checksum:string,versions:readonly MediaVersion[]){return versions.find(v=>v.checksumSha256===checksum)??null}
export function createMediaVersion(source:MediaVersion,input:{id:string;storagePath:string;filename:string;mimeType:string;byteSize:number;checksum:string;actorId:string;at:string}):MediaVersion{return{...source,id:input.id,versionNumber:source.versionNumber+1,status:"processing",storagePath:input.storagePath,originalFilename:input.filename,mimeType:input.mimeType,byteSize:input.byteSize,checksumSha256:input.checksum,derivatives:[],basedOnVersionId:source.id,createdBy:input.actorId,createdAt:input.at,approvedBy:null,approvedAt:null}}
export function assertMediaVersionImmutable(version:MediaVersion,usages:readonly MediaUsage[]){if(version.status==="approved"||usages.some(v=>v.publicationStatus==="published"))throw new Error("MEDIA_VERSION_IMMUTABLE")}
export function mediaImpact(usages:readonly MediaUsage[]){return{guidebooks:new Set(usages.filter(v=>v.consumerType==="guidebook").map(v=>v.consumerId)).size,publishedVersions:new Set(usages.filter(v=>v.publicationStatus==="published").map(v=>v.guidebookVersionId)).size,templates:new Set(usages.filter(v=>v.consumerType==="template").map(v=>v.consumerId)).size,components:new Set(usages.filter(v=>v.consumerType==="component").map(v=>v.consumerId)).size,contentRecords:new Set(usages.filter(v=>v.consumerType==="content_record").map(v=>v.consumerId)).size,channels:[...new Set(usages.flatMap(v=>v.channels))],requiresReplacement:usages.some(v=>v.publicationStatus==="published")}}
